### ISSUE TITLE
Server Name Indication    (method for using virtual hosts with SSL; seems fairly well supported out ...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1000]
Server Name Indication

http://en.wikipedia.org/wiki/Server_Name_Indication

(method for using virtual hosts with SSL; seems fairly well supported out in the wild)

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+22__
Issue added by __orospakr__ on __2014-02-18__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Fyrd** [comment]
Duplicate of #979, transferring half the votes there.

**Comment by MrMcFortna** [comment]
+1
