### ISSUE TITLE
CSSMatrix

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1001]
CSSMatrix: http://www.w3.org/TR/2011/WD-css3-2d-transforms-20111215/#cssmatrix-interface

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+22**
Issue added by **DanTheMan** on **2014-09-30**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/CSSMatrix
It's deprecated and no longer part of the spec: http://dev.w3.org/csswg/css-transforms/

**Comment by lagden** [comment]
👍

**Comment by cvrebert** [comment]
Subsequently, most of its API was merged into `DOMMatrix`, and `WebKitCSSMatrix` was made an alias of `DOMMatrix`.
See https://drafts.fxtf.org/geometry/#webkitcssmatrix

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=dommatrix
