### ISSUE TITLE
browser support for letter-spacing css property.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1002]
browser support for letter-spacing css property. Include info on whether browsers support fractional pixels as values (e.g. 1.5px)

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+26__
Issue added by __kamilkp__ on __2014-07-25__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by schalkneethling** [comment]
+1

**Comment by AdamMerrifield** [comment]
+1

**Comment by cvrebert** [comment]
Now available at http://caniuse.com/#feat=css-letter-spacing
