### ISSUE TITLE
Media element (<audio>/<video>) attributes: currentTime, volume, playbackRate etc.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1003]
Media element (&lt;audio&gt;/&lt;video&gt;) attributes: currentTime, volume, playbackRate etc.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+21**
Issue added by **Jackson** on **2012-07-02**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by MrMcFortna** [comment]
+1

**Comment by dimsolution** [comment]
+1

**Comment by Fyrd** [comment]
Have added these to the entries for [video](http://caniuse.com/#feat=video) and [audio](http://caniuse.com/#feat=audio) as support largely matches support of their media elements.

**Comment by dimsolution** [comment]
@Fyrd good job !
