### ISSUE TITLE
HTML5 attribute for reverse ordered lists. It's as simple as <ol reversed></ol> Woul...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1004]
HTML5 attribute for reverse ordered lists. It&#39;s as simple as &lt;ol reversed&gt;&lt;/ol&gt; Would be great to see compatibility lists for the same.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+29__
Issue added by __imohkay__ on __2013-03-22__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by ximex** [comment]
+1

**Comment by aneves** [comment]
+1

**Comment by KolyaKorruptis** [comment]
+1

**Comment by cvrebert** [comment]
Now available at http://caniuse.com/#feat=ol-reversed
