### ISSUE TITLE
CSS text-transform property 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1009]
CSS text-transform property
https://developer.mozilla.org/en/docs/Web/CSS/text-transform

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+21__
Issue added by __Billy__ on __2014-07-30__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Ugoku** [comment]
+1

**Comment by jziggas** [comment]
+1

**Comment by Leega0** [comment]
+1

**Comment by jobst** [comment]
+1

**Comment by MomoSir** [comment]
+1

**Comment by lembitk** [comment]
+1

**Comment by RoelVliegen** [comment]
+1

**Comment by gustavpursche** [comment]
+1

**Comment by mik-laj** [comment]
I think that this issue should be closed.
http://caniuse.com/#search=text-transform

**Comment by cvrebert** [comment]
@Fyrd Looks like this is already covered, per the previous comment.

**Comment by Fyrd** [comment]
Yup, closing this issue as the CSS 2.1 values are already covered.

MDN mentions some additional values in the CSS3 spec which I thought may be worth tracking, but looks like only `full-width` is in the latest spec and is at-risk. If anyone is still interested in tracking support for that value, please open a new issue.
