### ISSUE TITLE
input type="search"

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1011]
input type=&quot;search&quot;

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+19__
Issue added by __Dukes__ on __2012-07-25__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by actionthomas** [comment]
+1

**Comment by ximex** [comment]
+1

**Comment by sergeh** [comment]
+1

**Comment by Koelli91** [comment]
+1

**Comment by desertcrystal** [comment]
+1

**Comment by stephmarx** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=input-search
