### ISSUE TITLE
include which (if any) browsers support BPG Image Format:  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1013]
include which (if any) browsers support BPG Image Format:

http://bellard.org/bpg/

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+18__
Issue added by __nodefortytwo__ on __2014-12-05__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Spazturtle** [comment]
+1
But as BPG uses H.265 (HEVC) wouldn't it be best to add H.265 to caniuse first?

**Comment by Ugoku** [comment]
+1

**Comment by valtlait** [comment]
+1

**Comment by borg1980** [comment]
+1

**Comment by eek** [comment]
+1

**Comment by cvrebert** [comment]
Might as well wait for [netvc](https://datatracker.ietf.org/wg/netvc/charter/) and then base a new image format on that.

**Comment by domhaase** [comment]
+1

**Comment by Ugoku** [comment]
[Polyfill using a service worker](https://github.com/flaki/bpg2jpg) ([via](https://medium.com/@slsoftworks/beyond-offline-bf5c013ec8e7))

**Comment by andrewb273** [comment]
+1

**Comment by bugthunk** [comment]
+1

**Comment by Blueblau** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by thedonquixotic** [comment]
+1

**Comment by iamDecode** [comment]
+1

**Comment by JamesMcGuigan** [comment]
+1

**Comment by jensenbox** [comment]
+1

**Comment by lorddaedra** [comment]
+1

**Comment by PaintNinja** [comment]
+1

**Comment by sandstrom** [comment]
+1

**Comment by Arttse** [comment]
+1

**Comment by EarMaster** [comment]
+1

**Comment by as-com** [comment]
+1

**Comment by blitzprog** [comment]
+1

**Comment by CRGreathouse** [comment]
+1

**Comment by wernight** [comment]
+1

**Comment by azidoner** [comment]
+2

**Comment by gregmatys** [comment]
+1

**Comment by azimot** [comment]
sure +1

**Comment by Fyrd** [comment]
There appear to be no plans to support this in any browser, so have added it as a basic search results entry until that changes:
http://caniuse.com/#search=bpg
