### ISSUE TITLE
Advanced SVG text features, such as TextArea, FlowText and the "editable" attribute.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1015]
Advanced SVG text features, such as TextArea, FlowText and the &quot;editable&quot; attribute.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+18**
Issue added by **Colin Robertson** on **2011-10-11**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Llbe** [comment]
+1

**Comment by tigt** [comment]
These features have been dropped entirely and got overhauled in SVG2 (which is also not seeing much implementor interest.)

**Comment by Fyrd** [comment]
Closing this issue based on ^. If the features ever re-appear with support maybe will re-open then.
