### ISSUE TITLE
CSS3 "initial" value Specs

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1016]
CSS3 &quot;initial&quot; value
Specs: http://www.w3.org/TR/css3-cascade/#initial

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+22__
Issue added by __Luckylooke__ on __2013-07-18__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Schweinepriester** [comment]
+1

see <https://css-tricks.com/getting-acquainted-with-initial/> => <https://developer.mozilla.org/en-US/docs/Web/CSS/initial>

**Comment by AdamMerrifield** [comment]
+1

**Comment by Serator** [comment]
+1

**Comment by cvrebert** [comment]
Now available at http://caniuse.com/#feat=css-initial-value
