### ISSUE TITLE
Add support for bind(), a very useful Javascript method. Not supported by ios safari.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1017]
Add support for bind(), a very useful Javascript method. Not supported by ios safari.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+18__
Issue added by __steeg__ on __2012-03-29__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Kangax has this: http://kangax.github.io/compat-table/es5/#Function.prototype.bind

**Comment by Fyrd** [comment]
Now also part of http://caniuse.com/#feat=es5
