### ISSUE TITLE
CSS3 text-justify

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1021]
CSS3 text-justify

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+25__
Issue added by __JL__ on __2014-03-26__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by HolgerJeromin** [comment]
dulicate of #1023

**Comment by Ugoku** [comment]
+1

**Comment by Rezaldy** [comment]
+1

**Comment by cvrebert** [comment]
* http://dev.w3.org/csswg/css-text-3/#text-justify-property
* http://www.quirksmode.org/css/text/#t012

**Comment by richardbruskowski** [comment]
+1

**Comment by mik-laj** [comment]
+1

**Comment by ginosie** [comment]
+1

**Comment by dominiccarrington** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-text-justify
