### ISSUE TITLE
Would be nice to have a test for the Intl object, part of ECMAScript Internationalization API.  The ...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1022]
Would be nice to have a test for the Intl object, part of ECMAScript Internationalization API.

The test could be as simple as check for window.Intl

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+17__
Issue added by __Artemy Tregubenko__ on __2014-04-15__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
http://kangax.github.io/compat-table/esintl/

**Comment by dstorey** [comment]
This and #1424 should be covered by http://caniuse.com/#feat=internationalization

**Comment by Fyrd** [comment]
Yup, closing the issue.
