### ISSUE TITLE
CSS3 text-justify

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1023]
CSS3 text-justify

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+17__
Issue added by __zachleat__ on __2012-02-03__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by MrMcFortna** [comment]
+1

**Comment by Fyrd** [comment]
Duplicate of #1021 so adding half the votes there

**Comment by ytrezq** [comment]
:+1:
