### ISSUE TITLE
Perspective element  Reference:  www.w3schools.com/cssref/css3_pr_perspective.asp

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1024]
Perspective element

Reference:

www.w3schools.com/cssref/css3_pr_perspective.asp

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+17__
Issue added by __lawreaf__ on __2014-02-11__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Data is already present: http://caniuse.com/#feat=transforms3d

**Comment by Fyrd** [comment]
Yup.
