### ISSUE TITLE
Lazy Load, as supported by IE11.   "Lowers the loading priority of a resource." Example: &...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1026]
Lazy Load, as supported by IE11.
http://msdn.microsoft.com/en-us/library/ie/dn369270(v=vs.85).aspx

&quot;Lowers the loading priority of a resource.&quot;
Example: &lt;img src=&quot;myImage.jpg&quot; lazyload=&quot;1&quot;&gt;

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+17__
Issue added by __TJ Fogarty__ on __2014-02-20__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Trenker** [comment]
+1

**Comment by stuartm** [comment]
+1

**Comment by tvler** [comment]
+1

**Comment by samaxes** [comment]
+1

**Comment by dipser** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=lazyload
