### ISSUE TITLE
background-position

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1028]
background-position

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+17__
Issue added by __Oxana__ on __2012-03-15__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Related: #989

**Comment by milkovsky** [comment]
http://caniuse.com/#search=background-position is supported in IE8. Please fix.
I tested.
You can also check other resources:
- http://www.w3schools.com/cssref/pr_background-position.asp
- http://htmlbook.ru/css/background-position

**Comment by Schweinepriester** [comment]
Isn't his already covered by http://caniuse.com/#search=background-position (either the longhand or 'well-supported')?

**Comment by Fyrd** [comment]
Yup, is indeed covered.
