### ISSUE TITLE
Indeterminate Checkboxes

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1030]
Indeterminate Checkboxes: http://css-tricks.com/indeterminate-checkboxes/

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+16__
Issue added by __ys__ on __2014-04-22__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Lynda333** [comment]
+1

**Comment by valtlait** [comment]
+1

**Comment by YuriyVlasenko** [comment]
+1

**Comment by DJDavid98** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=indeterminate-checkbox
