### ISSUE TITLE
The wbr element 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1032]
The wbr element http://www.w3.org/TR/html5/text-level-semantics.html#the-wbr-element

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+22__
Issue added by __Stefan__ on __2014-03-22__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Ugoku** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by tobias-faust** [comment]
+1

**Comment by radek-anuszewski** [comment]
+1

**Comment by askdesigners** [comment]
+1

**Comment by cvrebert** [comment]
Now available at http://caniuse.com/#feat=wbr-element
