### ISSUE TITLE
WebGL2 is being developed now.  It would be good to have a support table ready for this. Firefox 25 ...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1034]
WebGL2 is being developed now.

It would be good to have a support table ready for this. Firefox 25 and later support this right now behind a flag. (See https://wiki.mozilla.org/Platform/GFX/WebGL2 )

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+16__
Issue added by __Nexii Malthus__ on __2014-11-26__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by AdamMerrifield** [comment]
+1

**Comment by deadmanswitch** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=webgl2

**Comment by cvrebert** [comment]
@Fyrd "Data pending review" label should be removed then.
