### ISSUE TITLE
More CSS3 specifications.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1035]
More CSS3 specifications.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+16__
Issue added by __Binyamin Laukstein__ on __2011-08-22__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
This seems too vague.

**Comment by Fyrd** [comment]
Agreed.
