### ISSUE TITLE
Would love to know can I use Media Source Extensions on some browsers?

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1036]
Would love to know can I use Media Source Extensions on some browsers?

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+16__
Issue added by __luongnv89__ on __2014-08-01__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by dstorey** [comment]
This is a duplicate of #986

**Comment by Fyrd** [comment]
Yup. Moving half the votes there.
