### ISSUE TITLE
 -webkit-scrollbar

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1037]
-webkit-scrollbar

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+16__
Issue added by __egpierro__ on __2014-04-22__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by extempl** [comment]
+1

**Comment by cvrebert** [comment]
Duplicate of #1449.
