### ISSUE TITLE
Add column-span and column-fill features

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1043]
Add column-span and column-fill features

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+15**
Issue added by **Moinax** on **2014-05-24**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by CapitanRedBeard** [comment]
+1

**Comment by Schweinepriester** [comment]
Probably already covered by <http://caniuse.com/#feat=multicolumn>?

**Comment by bsene** [comment]
+1

**Comment by Fyrd** [comment]
Covered by:
https://caniuse.com/#feat=multicolumn
https://caniuse.com/#feat=mdn-css_properties_column-span
https://caniuse.com/#feat=mdn-css_properties_column-fill
