### ISSUE TITLE
insertAdjacentHTML

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1044]
insertAdjacentHTML

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+22__
Issue added by __Oria__ on __2014-04-30__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by shuizhongyueming** [comment]
+1

**Comment by cvrebert** [comment]
Now available at http://caniuse.com/#feat=insertadjacenthtml

**Comment by shuizhongyueming** [comment]
I can see it
![image](https://cloud.githubusercontent.com/assets/2059860/9703378/2069f42c-54b5-11e5-9899-a0f59cf30d2c.png)
