### ISSUE TITLE
I suggest adding "CSS Device Adaptation" to caniuse.com  It's the standard that W3C ar...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1048]
I suggest adding &quot;CSS Device Adaptation&quot; to caniuse.com

It&#39;s the standard that W3C are moving towards, using CSS to specify viewport properties as opposed to the currently used meta tag. It&#39;s neater with CSS.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+14__
Issue added by __john doe__ on __2014-04-02__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by dstorey** [comment]
This is a duplicate of #1012

**Comment by Fyrd** [comment]
Also already added at http://caniuse.com/#feat=css-deviceadaptation
