### ISSUE TITLE
CSS Exclusions  Part of IE10, CSS Exclusions can be positioned at a specified distance from the top,...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1049]
CSS Exclusions

Part of IE10, CSS Exclusions can be positioned at a specified distance from the top, bottom, left, or right sides of a containing block, while remaining part of the document flow.

http://dev.w3.org/csswg/css3-exclusions/

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+14__
Issue added by __bodash__ on __2012-02-24__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Covered by http://caniuse.com/#feat=css-exclusions
