### ISSUE TITLE
Hardware accelerated Canvas / page rendering

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1050]
Hardware accelerated Canvas / page rendering

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+14__
Issue added by __Necroman__ on __2011-08-22__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
This sounds like an out-of-scope implementation detail, unless there's some API I haven't heard of that allows detection of this.

**Comment by Fyrd** [comment]
Agreed.
