### ISSUE TITLE
The HTML5 document.head DOM tree accessor

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1052]
The HTML5 document.head DOM tree accessor

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+14__
Issue added by __Mathias Bynens__ on __2011-08-22__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Document/head#Browser_compatibility

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=documenthead
