### ISSUE TITLE
Put on list CSS Zoom. This seems it function on major browsers and IEs.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1053]
Put on list CSS Zoom. This seems it function on major browsers and IEs.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+14__
Issue added by __Diego Eis__ on __2012-01-24__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
-1

**Comment by pkuczynski** [comment]
This is a duplicate of #1453 and it can be closed @Fyrd

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-zoom
