### ISSUE TITLE
CSS3 @namespace Support

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1054]
CSS3 @namespace Support
http://www.w3.org/TR/css3-namespace/
Though it is one of the least well known of all of the CSS3 modules. &ldquo;namespaces&rdquo; distinguish multiple uses of the same element name from each other. Supported in current FF, Safari, Chrome

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+20**
Issue added by **Estelle** on **2011-10-31**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by tgraham-antenna** [comment]
+1

**Comment by cvrebert** [comment]
-1

**Comment by 304NotModified** [comment]
+1

**Comment by DiMFail** [comment]
+1

**Comment by Benimation** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-namespaces
