### ISSUE TITLE
line-clamp e.g.  .line-clamp {   display: -webkit-box;   -webkit-line-clamp: 3;   -webkit-box-orient...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1055]
line-clamp
e.g.

.line-clamp {
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;  
}

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+14__
Issue added by __Julian__ on __2014-04-18__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by felixdulfer** [comment]
+1

**Comment by MarkMurphy** [comment]
+1 I would also like to see this added.

**Comment by julienbornstein** [comment]
+1

**Comment by secrethome** [comment]
+1

**Comment by atakangktepe** [comment]
+1

**Comment by keyboSlice** [comment]
+1

**Comment by dstorey** [comment]
Not a reason not to add this, but just a note that it shouldn't be encouraged to use this vendor specific API https://twitter.com/gregwhitworth/status/626968958759907330

**Comment by extempl** [comment]
+1

**Comment by ryaneof** [comment]
+1

**Comment by mekwall** [comment]
+1

**Comment by jaksah** [comment]
+1

**Comment by elhay-avihezer** [comment]
+1

**Comment by Llbe** [comment]
+1

**Comment by jeroentradecast** [comment]
+1

**Comment by remitoffoli** [comment]
+1

**Comment by tomsaffell** [comment]
+1

**Comment by JarJak** [comment]
+1

**Comment by people-06** [comment]
+1

**Comment by adamkowalczyk** [comment]
+1

**Comment by amatecha** [comment]
+1

**Comment by omonk** [comment]
+1

**Comment by sebastiangraz** [comment]
+1

**Comment by robcolburn** [comment]
+1

Generally, this is only supported by Webkit / Blink, though I don't have the details. Edge & Firefox have old / ignored feature requests. If you care about this feature, please up-vote the tickets.

https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/11392557-css-line-clamping

https://bugzilla.mozilla.org/show_bug.cgi?id=866102

Also, does anyone have any links to standards/specs docs on this?

**Comment by L0stSoul** [comment]
+1;

**Comment by malixsys** [comment]
+1

**Comment by infinityplusone** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-line-clamp

**Comment by p01** [comment]
https://drafts.csswg.org/css-overflow-4/#max-lines
