### ISSUE TITLE
Node.textContent (

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1056]
Node.textContent (https://developer.mozilla.org/en-US/docs/Web/API/Node.textContent)

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+16__
Issue added by __Nathan__ on __2014-04-10__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by franckl** [comment]
+1

**Comment by cvrebert** [comment]
@Fyrd Is data for this feature still desired? IE waited until IE9 to support it; everyone else has supported it since "forever"; see https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#Browser_compatibility

**Comment by Fyrd** [comment]
@cvrebert Yeah, I guess so... IE8 still has 6.3% usage in China so I imagine that information would still be of value to a number of (poor unfortunate) developers.

**Comment by cvrebert** [comment]
Now available at http://caniuse.com/#feat=textcontent
