### ISSUE TITLE
inputmode is going to be supported at some point

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1057]
inputmode is going to be supported at some point: http://www.whatwg.org/specs/web-apps/current-work/multipage/association-of-controls-and-forms.html#attr-fe-inputmode

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+14__
Issue added by __njzk2__ on __2014-05-28__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by proimage** [comment]
+1 - saddened to find inputmode not on caniuse yet.

**Comment by AdamBuczynski** [comment]
+1

**Comment by cvrebert** [comment]
+1

**Comment by bookwyrm** [comment]
+1

**Comment by olafkarsten** [comment]
+1

**Comment by awerlang** [comment]
+1

**Comment by capeterson** [comment]
+1

**Comment by wpk-** [comment]
+1

**Comment by cvrebert** [comment]
https://dev.modern.ie/platform/status/inputmode/

**Comment by madmaxlax** [comment]
+1

**Comment by breckenedge** [comment]
+1

**Comment by BonzaiThePenguin** [comment]
+1

**Comment by c01nd01r** [comment]
+1

**Comment by metalhaze** [comment]
+1

**Comment by bennyp123** [comment]
+1

**Comment by chaals** [comment]
+1

**Comment by gustavoconci** [comment]
+1

**Comment by ABM-Dan** [comment]
+1

**Comment by mickaelmarchal** [comment]
+1

**Comment by thany** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=input-inputmode
