### ISSUE TITLE
Adding the CSS `all` property. Firefox 27 now supports the `unset` value of `all`. It would be good ...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1059]
Adding the CSS `all` property. Firefox 27 now supports the `unset` value of `all`. It would be good to see where others are with this, too.

http://dev.w3.org/csswg/css-cascade/#all-shorthand

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+21__
Issue added by __Matt Smith__ on __2014-02-11__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by SaraSoueidan** [comment]
Yes, please! +1 for adding the suppprt table.

**Comment by csuhta** [comment]
+1

**Comment by iamstarkov** [comment]
:+1:

**Comment by mpopp75** [comment]
+1

**Comment by frontdevde** [comment]
+1

**Comment by AllThingsSmitty** [comment]
:+1:

**Comment by roxstyle** [comment]
+1

**Comment by davidhund** [comment]
+1 :+1:

**Comment by memolog** [comment]
+1 :smile:

**Comment by jwdallas** [comment]
+1

**Comment by voracity** [comment]
+1

**Comment by Lynda333** [comment]
+1

**Comment by aneves** [comment]
+1

**Comment by jackmcpickle** [comment]
+1

**Comment by valtlait** [comment]
+1

**Comment by pverbeek** [comment]
+1

**Comment by bennettfeely** [comment]
+1

**Comment by ovaxio** [comment]
+1

**Comment by cvrebert** [comment]
These have been added in #1853 & #1854.

**Comment by cvrebert** [comment]
@Fyrd This can be closed now.

**Comment by AllThingsSmitty** [comment]
Yay! 🎉💃🏻✨🚀

**Comment by Fyrd** [comment]
Yup, now available at http://caniuse.com/#feat=css-unset-value,css-all largely thanks to @cvrebert !

**Comment by cvrebert** [comment]
Support for `unset` has landed in WebKit: http://trac.webkit.org/changeset/191151

**Comment by cvrebert** [comment]
Support for `all` has landed in WebKit: http://trac.webkit.org/changeset/191178
