### ISSUE TITLE
transitionend and animationend support

### ISSUE THREAD

**Issue by laukstein** [Fyrd/caniuse#106]
JavaScript event to detect when CSS3 animations and transitions end https://plus.google.com/u/0/110977198681221304891/posts/PcrM4jPd7sX
- W3C WD http://dev.w3.org/csswg/css3-transitions/#transition-events
- MDN transitionend https://developer.mozilla.org/en-US/docs/Mozilla_event_reference/transitionend
- MDN animationend https://developer.mozilla.org/en-US/docs/Mozilla_event_reference/animationend

**Comment by 1j01** [comment]
:+1:
