### ISSUE TITLE
Browser support for the HTML5 implementation of negative tabIndex values

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1062]
Browser support for the HTML5 implementation of negative tabIndex values (to indicate elements that should be left out of the tabIndex) is apparently spotty/irregular. So I came here to see what browsers supported it partially/fully... &quot;Not Found&quot; :(

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+14__
Issue added by __Bleus__ on __2014-09-24__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by titpetric** [comment]
+1

**Comment by joevus** [comment]
I'd add my voice to having a tabindex table. Besides for negative values, I'd like to just see tabindex in general.

**Comment by LovelyHorse** [comment]
+1

**Comment by agentfitz** [comment]
+1

**Comment by clementhannicq** [comment]
+1

**Comment by oles-** [comment]
+1

**Comment by xerere** [comment]
+1

**Comment by devonparsons** [comment]
+1

**Comment by Schweinepriester** [comment]
+1 and this:

> I'd add my voice to having a tabindex table. Besides for negative values, I'd like to just see tabindex in general.

**Comment by marteki** [comment]
+1

**Comment by Neozaru** [comment]
+1

**Comment by tmcgann** [comment]
+1

**Comment by Fyrd** [comment]
Now (finally) available at http://caniuse.com/#feat=tabindex-attr
