### ISSUE TITLE
text-wrap

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1064]
text-wrap

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+14**
Issue added by **Jason R** on **2011-08-24**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
This only seems to exist in an unofficial draft: http://dev.w3.org/csswg/css-text-4/#text-wrap

**Comment by Mortal** [comment]
+1

**Comment by 304NotModified** [comment]
+1

**Comment by ian-pvd** [comment]
CSS Text Module Level 4 was updated to a working draft on September 20th, 2018 and includes additional details for `text-wrap`
https://www.w3.org/TR/css-text-4/

**Comment by kokoshneta** [comment]
+1

**Comment by X4nd0R** [comment]
+1

**Comment by theredcursed** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

`text-wrap: balance` is being prototyped by Chrome:
- https://mastodon.social/@intenttoship@botsin.space/109823494566296914
- https://groups.google.com/a/chromium.org/g/blink-dev/c/yEwHDXaRIF8/m/3n8ENrVlAwAJ
- https://chromestatus.com/feature/5196960707903488

**Comment by Schweinepriester** [comment]
Intent to Ship now by Chrome:
- https://groups.google.com/a/chromium.org/g/blink-dev/c/f5eLz6PIXaI/m/R__N3BdjAAAJ
- https://chromestatus.com/feature/5196960707903488
- Shipping: 113

**Comment by aetinx** [comment]
+1

**Comment by bobbymannino** [comment]
+1

**Comment by matthew-dean** [comment]
Please add `text-wrap: balance`!

**Comment by Ugoku** [comment]
`text-wrap: balance` is [now in Chrome Canary](https://developer.chrome.com/blog/css-text-wrap-balance/) (113). Here's [Mozilla's issue tracker](https://bugzilla.mozilla.org/show_bug.cgi?id=1731541), couldn't find any info on Safari.

**Comment by sandyio** [comment]
+1

**Comment by silverwind** [comment]
`text-wrap` is notably still absent from MDN. Didn't find an open issue [there](https://github.com/mdn/content).

**Comment by darekkay** [comment]
`text-wrap` is now [available](https://caniuse.com/?search=text-wrap) on CanIUse. I think this issue can be closed.

**Comment by Fyrd** [comment]
As the [MDN BCD entry](https://caniuse.com/?search=text-wrap) is for the entire `text-wrap` property which includes possible future values of "pretty" and "stable" I figured it would be of value to add a caniuse entry specific to `balanced` so that's now available here: https://caniuse.com/css-text-wrap-balance
