### ISSUE TITLE
Couldn't find anything for HTML Media Capture on caniuse.com.  Suggest adding this to feature li...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1067]
Couldn&#39;t find anything for HTML Media Capture on caniuse.com.  Suggest adding this to feature list

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+13__
Issue added by __JohnS__ on __2012-05-02__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by dstorey** [comment]
This is already available: http://caniuse.com/#feat=stream
