### ISSUE TITLE
HTML5 input type "month"  Browser compatibility with HTML5's input type "month&qu...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1071]
HTML5 input type &quot;month&quot;

Browser compatibility with HTML5&#39;s input type &quot;month&quot; and whether it invokes the native date picker, or maintains a standard &quot;input&quot; text field.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+13**
Issue added by **Jacob D** on **2014-02-06**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Possibly part of http://caniuse.com/#feat=input-datetime , although that doesn't seem to give enough detail about the individual temporal input types, whose support differs.

**Comment by valbg** [comment]
Yeah, that is not the same thing. I also think this is going to be useful thing to be added.

**Comment by dstorey** [comment]
This currently covers month, as Edge "12" got partial for supporting date, month, week, but not time and datetime-local. They could all be split up (like say html5test) but that would make a bunch of entries

**Comment by koyae** [comment]
+1 for wanting this to be implemented.

**Comment by codynguyen1116** [comment]
+1

**Comment by Residu** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

I believe this issue should also include the `week` attribute not just `month`.

**Comment by cvrebert** [comment]
+1

**Comment by thomasreiser** [comment]
+1

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by webmaster777** [comment]
+1

**Comment by Fyrd** [comment]
Have updated https://caniuse.com/#feat=input-datetime information and support data to explicitly include `month` and `week` type support.
