### ISSUE TITLE
Mutation events

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1074]
Mutation events

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+22__
Issue added by __Mathias Bynens__ on __2012-03-21__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by dstorey** [comment]
This is already available http://caniuse.com/#feat=mutationobserver

**Comment by Fyrd** [comment]
Actually...that's mutation observer, some people have mentioned that would be useful to see support for the legacy mutation events as fallback.

**Comment by cvrebert** [comment]
Duplicate of #1458.

**Comment by cvrebert** [comment]
+1 because IE (as always)

**Comment by stof** [comment]
+1

**Comment by mik-laj** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=mutation-events
