### ISSUE TITLE
Add Pointer Lock  to the list

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1075]
Add Pointer Lock https://dvcs.w3.org/hg/pointerlock/raw-file/default/index.html to the list

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+12__
Issue added by __wuz__ on __2014-04-08__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by HolgerJeromin** [comment]
same as #983

**Comment by HolgerJeromin** [comment]
same as #983

**Comment by Fyrd** [comment]
Duplicate of #983 so adding half the votes there
