### ISSUE TITLE
CSS3 Template Layout 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1077]
CSS3 Template Layout
http://www.w3.org/TR/2009/WD-css3-layout-20090402/

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+14**
Issue added by **Victor Costan** on **2011-11-03**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by lembitk** [comment]
This could/should be closed – [CSS Grid Layout is available](https://caniuse.com/#feat=css-grid) (and the W3C link above refers to a _very_ old version of the specification; also, this is/were a duplicate of #1334, closed already…)

**Comment by Fyrd** [comment]
Yeah, since CSS Grid replaced this concept I agree it's safe to close this request.
