### ISSUE TITLE
ECMAScript Internationalization API (ECMA-402)    

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1078]
ECMAScript Internationalization API (ECMA-402)
   http://www.ecma-international.org/publications/standards/Ecma-402.htm

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+12__
Issue added by __Mihai Nita__ on __2013-08-27__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by dstorey** [comment]
This is already available http://caniuse.com/#feat=internationalization
