### ISSUE TITLE
Object.create(); Object.defineProperty(); property getters/setters;

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1083]
Object.create(); Object.defineProperty(); property getters/setters;

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+12__
Issue added by __AlexWayne__ on __2012-01-23__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
http://kangax.github.io/compat-table/es5/#Object.create
http://kangax.github.io/compat-table/es5/#Object.defineProperty

**Comment by Fyrd** [comment]
Part of http://caniuse.com/#feat=es5
