### ISSUE TITLE
Event capturing (addEventListener with capturing=true). IE started supporting addEventListener only ...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1085]
Event capturing (addEventListener with capturing=true). IE started supporting addEventListener only recently, but it&#39;s hard to find if they also started supporting capturing (e.g. in IE10).

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+19__
Issue added by __tynstar__ on __2013-07-16__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by valioDOTch** [comment]
+1
