### ISSUE TITLE
Please add mask-image CSS style to the list. It's already supported in many current-version brow...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1086]
Please add mask-image CSS style to the list.
It&#39;s already supported in many current-version browsers.
Thanks.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+12__
Issue added by __Francisc__ on __2012-05-03__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Data is already present: http://caniuse.com/#feat=css-masks

**Comment by yukulele** [comment]
+1

**Comment by yukulele** [comment]
@cvrebert it's not the same:
https://developer.mozilla.org/fr/docs/Web/CSS/mask
https://developer.mozilla.org/fr/docs/Web/CSS/mask-image
