### ISSUE TITLE
display: inline-table

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1087]
display: inline-table

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+17__
Issue added by __Eric Nguyen__ on __2012-09-26__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by hguiney** [comment]
+1

**Comment by KanorUbu** [comment]
+1

**Comment by Fyrd** [comment]
Have included this information in http://caniuse.com/#feat=css-table (basically the same, except `inline-table` was not supported in Firefox 2)
