### ISSUE TITLE
innerText

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1088]
innerText

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+11__
Issue added by __FrankC__ on __2014-06-05__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
`outerHTML` and `innerHTML` are already covered: http://caniuse.com/#feat=xml-serializer
`innerText` doesn't seem to be currently covered.

**Comment by cvrebert** [comment]
@Fyrd Narrow this issue to just `innerText` per previous comment?

**Comment by Fyrd** [comment]
Done.

**Comment by cvrebert** [comment]
Now available at http://caniuse.com/#feat=innertext
