### ISSUE TITLE
text-size-adjust

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1089]
text-size-adjust

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+11__
Issue added by __shannonmoeller__ on __2011-08-24__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by dstorey** [comment]
http://caniuse.com/#feat=text-size-adjust
