### ISSUE TITLE
HSV definitions in CSS for colors

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1090]
HSV definitions in CSS for colors

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+11__
Issue added by __Max V&ouml;lkel__ on __2012-01-16__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Is this referring to HSL colors?

**Comment by Fyrd** [comment]
Most likely, since I don't think HSV ever got spec'd or implemented. So already added at http://caniuse.com/#feat=css3-colors
