### ISSUE TITLE
Hi,  could you please add a property "text-fill-color" (works only for webkit browser for ...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1091]
Hi,

could you please add a property &quot;text-fill-color&quot; (works only for webkit browser for this moment).

Thanks in advance

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+11__
Issue added by __text-fill-color__ on __2014-05-10__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by radubr** [comment]
+1

**Comment by cvrebert** [comment]
http://caniuse.com/#feat=text-stroke should already cover this

**Comment by RTakes** [comment]
+1

**Comment by Schweinepriester** [comment]
If <http://caniuse.com/#feat=text-stroke> covers this, make `text-fill-color` find it?

**Comment by Schweinepriester** [comment]
Fixed by dafd6c68c2091f17c2b437622107c5b5e34211ea
