### ISSUE TITLE
HTML <button> formaction Attribute   you can use the w3schools site as reference ...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1094]
HTML &lt;button&gt; formaction Attribute

http://www.w3schools.com/tags/att_button_formaction.asp
you can use the w3schools site as reference ...

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+11__
Issue added by __Kay Strobach__ on __2014-04-09__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1233.
