### ISSUE TITLE
addEventListener / removeEventListener

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1096]
Would be nice to see a support table for addEventListener. I know that IE6-8 don&#39;t support it, but I&#39;m not sure about older versions of the other browsers. Thanks.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+17__
Issue added by __Louis L.__ on __2011-08-25__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1250.

**Comment by Fyrd** [comment]
Duplicate of #1085, adding half the votes there

**Comment by valioDOTch** [comment]
+1

**Comment by errm** [comment]
+1

**Comment by ximex** [comment]
+1

**Comment by arekrob** [comment]
+1

**Comment by dandv** [comment]
Basically, supported everywhere but IE <9.

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Browser_compatibility

**Comment by orzechowskikamil** [comment]
Why not put it directly on caniuse database, instead of forcing people digging across issues to get that knowledge?

**Comment by SeanBannister** [comment]
+1

**Comment by FQ400** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=addeventlistener thanks to @cvrebert

**Comment by cvrebert** [comment]
@Fyrd Looks like there's some problem with the rendering of the link in Note 1...

**Comment by Fyrd** [comment]
@cvrebert Ah yes, I think my basic markdown parser doesn't like nested things. I'll look into it, thanks.

**Comment by Fyrd** [comment]
@cvrebert Aaaand fixed!
