### ISSUE TITLE
<input type='tel'>  W3C Spec  Reading article

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1097]
&lt;input type=&#39;tel&#39;&gt;

W3C Spec: http://www.w3.org/TR/html-markup/input.tel.html

Reading article: http://www.htmlgoodies.com/html5/tutorials/whats-new-in-html5-forms-email-url-and-telephone-input-types.html

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+14__
Issue added by __Ricardo Zea__ on __2014-04-16__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Fixed by https://github.com/Fyrd/caniuse/commit/3b130d66cf4010f764ca83d950266f40db69bb3f#diff-77e11bb4b208d0b4c6bf2f930d7837fd

**Comment by Fyrd** [comment]
Yup...when my research is complete.

**Comment by Fyrd** [comment]
Aaand added now at http://caniuse.com/#feat=input-email-tel-url
