### ISSUE TITLE
Custom events 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1098]
Custom events http://www.sitepoint.com/javascript-custom-events/

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+11__
Issue added by __user__ on __2015-03-01__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent#Browser_compatibility

**Comment by jacob418** [comment]
+1

**Comment by ekaradon** [comment]
+1

**Comment by Crashthatch** [comment]
+1

**Comment by godchuanz** [comment]
+1

**Comment by EugenAz** [comment]
+1

**Comment by reyhappen** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=customevent
