### ISSUE TITLE
document.currentScript is useful for scripts which need to be aware of where their script tag is in ...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1099]
document.currentScript is useful for scripts which need to be aware of where their script tag is in relation to the rest of the DOM, such as when a script needs to operate only on its sibling elements.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+16__
Issue added by __danhunsaker__ on __2014-06-03__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Jamtis** [comment]
+1

**Comment by Bartvds** [comment]
+1

**Comment by itsrachelfish** [comment]
+1

**Comment by TremayneChrist** [comment]
+1

**Comment by gagern** [comment]
+1 :+1:

See https://html.spec.whatwg.org/multipage/dom.html#dom-document-currentscript for documentation.

**Comment by staio** [comment]
+1

**Comment by Jakobud** [comment]
+1

**Comment by BobStein** [comment]
+1 - PDF.js crashes on document.currentScript in IE11. So: http://caniuse.com/#search=currentScript

Alas ...

**Comment by anymos** [comment]
+1

**Comment by micromaomao** [comment]
+1

**Comment by elhaard** [comment]
+1

**Comment by d-ark** [comment]
+1

**Comment by ak5** [comment]
+1

**Comment by forberg** [comment]
+1

**Comment by Stephan972** [comment]
+1

MDC lists the browsers supporting `document.currentScript`.
See: https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript

As of this writing, IE doesn't support this feature. Support is unknown for IE Mobile and Opera Mobile.

**Comment by alexanderdickson** [comment]
+1

**Comment by mjhm** [comment]
+1

**Comment by APerson241** [comment]
+1

**Comment by mkdgs** [comment]
+1

**Comment by brion** [comment]
+1 note this is implemented in Microsoft Edge at least as of Windows Insider build 14295 (haven't tested release builds). Would be nice to list this sort of thing. :)

**Comment by stuartpb** [comment]
+1

**Comment by TakayoshiKochi** [comment]
+1

**Comment by louislepper** [comment]
+1

**Comment by WhiteWind** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=document-currentscript
