### ISSUE TITLE
Support `ch` (character unit)

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1101]
Support `ch` (character unit)

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+11__
Issue added by __Hugo Giraudel__ on __2014-07-25__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by mikebranski** [comment]
+1

**Comment by JoshuaWise** [comment]
+1

**Comment by hudakdidit** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by idupree** [comment]
Note that IE supports ch with the (IMHO) wrong width. Firefox and Chrome get it right.  https://stackoverflow.com/questions/17825638/css3-ch-unit-inconsistent-between-ie9-and-other-browsers

**Comment by dkerzig** [comment]
+1

**Comment by Schweinepriester** [comment]
From <http://www.w3schools.com/cssref/css_units.asp>:

- Chrome 27+
- IE 9+
- Firefox 1+
- Safari 7+
- Opera 20+

From <https://css-tricks.com/the-lengths-of-css/> (2013):

> Notable browser support issues: IE 9+, no Android default browser

**Comment by TWiStErRob** [comment]
+1

**Comment by lozandier** [comment]
+1

**Comment by jaicab** [comment]
+1

**Comment by CREEATION** [comment]
+1

**Comment by appie18** [comment]
+1

**Comment by krassowski** [comment]
+1

**Comment by gerbenvandijk** [comment]
+1

**Comment by Bisaloo** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=ch-unit
