### ISSUE TITLE
console.time and console.timeEnd, two very useful functions for measuring performance

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1102]
console.time and console.timeEnd, two very useful functions for measuring performance

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+10**
Issue added by **LinusU** on **2014-04-01**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by jdempcy** [comment]
+1

**Comment by 304NotModified** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=console-time
