### ISSUE TITLE
This may fall under the umbrella of HTML5 Forms, but a section on which browsers support the form at...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1103]
This may fall under the umbrella of HTML5 Forms, but a section on which browsers support the form attribute on form child elements (e.g. input, button, etc.) would be useful.

http://www.w3.org/TR/html5/forms.html#category-form-attr

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+10__
Issue added by __Jody__ on __2014-06-12__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Refs http://caniuse.com/#feat=forms

**Comment by Fyrd** [comment]
Added at http://caniuse.com/#feat=form-attribute
