### ISSUE TITLE
the maxlength attribute property support would be a good to know.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1106]
the maxlength attribute property support would be a good to know.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+10__
Issue added by __TrishZwei__ on __2015-02-06__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Working on a PR for this, just one more round of testing left.

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=maxlength Thanks @cvrebert !

**Comment by cvrebert** [comment]
@Fyrd Thanks for the additional testing! That `#6` you found is a doozy.
