### ISSUE TITLE
The Output Element  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1107]
The Output Element  http://www.w3.org/TR/html5/the-button-element.html#the-output-element

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+12**
Issue added by **Paul Verbeek** on **2011-12-28**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Ugoku** [comment]
+1
Could be a subitem of [New semantic elements](http://caniuse.com/#feat=html5semantic) ?

**Comment by baloneysandwiches** [comment]
Support is non-existent in IE.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/output

despite having been a full-blown spec recommendation for years:

http://www.w3.org/TR/html5/forms.html#the-output-element

This isn't really a subitem of new semantic elements, in terms of implementation or spec history. The semantic usefulness of `<output>` in a developer toolkit should be obvious. IMHO this is exactly the sort of circumstance that caniuse is great at illuminating. +1 for a separate page.

**Comment by Ugoku** [comment]
Since it's in the same spec as `meter`, `progress`, `input[type=color]` etc. (which all have a separate item on caniuse) it might indeed make more sense to have a separate item for `output` :)

**Comment by cvrebert** [comment]
https://dev.modern.ie/platform/status/outputelement/

**Comment by knod** [comment]
I searched for the output element today and didn't find it. Is that intended?

**Comment by djmattyg007** [comment]
Calling in two years later. It would be nice if support for the `<output>` tag could be added. +1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-html_elements_output
