### ISSUE TITLE
font-smooth

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1108]
font-smooth

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+10__
Issue added by __efusien__ on __2011-11-03__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1475?

**Comment by Fyrd** [comment]
Yeah, already added at http://caniuse.com/#feat=font-smooth
