### ISSUE TITLE
first-line pseudo selector?

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1109]
first-line pseudo selector?

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+13__
Issue added by __murraybiscuit__ on __2014-03-22__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by gandoulfe** [comment]
+1

**Comment by pawdat** [comment]
+1

**Comment by vcichecka** [comment]
+1

**Comment by klmdb** [comment]
+1

**Comment by Buntuu** [comment]
+1

**Comment by Warrows** [comment]
+1

**Comment by Kudusch** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by micahherstand** [comment]
+1

**Comment by ipekt** [comment]
+1

**Comment by flightcom** [comment]
+1

**Comment by douglasquintanilha** [comment]
+1

**Comment by bparmley** [comment]
+1

**Comment by bronzehedwick** [comment]
:+1:

**Comment by jensimmons** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-first-line
