### ISSUE TITLE
TLS/SSL version and cipher grids. It's very much a client compatibility issue, just not for fron...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1110]
TLS/SSL version and cipher grids. It&#39;s very much a client compatibility issue, just not for front-end engineers. The existing format is perfect. Happy to help collect data.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+10__
Issue added by __James Socol__ on __2014-10-15__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1144.
