### ISSUE TITLE
Can you expand the site to include javascript features?  For example, where can I use "let&quot...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1111]
Can you expand the site to include javascript features?

For example, where can I use &quot;let&quot; from ECMAScript 6?

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+10__
Issue added by __Kohesion__ on __2012-02-14__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
This is more of a general question of project scope rather than a specific suggestion.
Kangax has a lot of this data; e.g. http://kangax.github.io/compat-table/es6/#let

**Comment by cvrebert** [comment]
Duplicate of #492.

**Comment by Fyrd** [comment]
Closing as duplicate, more info at #492.
