### ISSUE TITLE
Add Web MIDI API

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1112]
Add Web MIDI API: https://dvcs.w3.org/hg/audio/raw-file/tip/midi/specification.html

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+10__
Issue added by __Matt__ on __2012-06-18__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by dstorey** [comment]
http://caniuse.com/#feat=midi
