### ISSUE TITLE
::selection for css selection styling 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1113]
::selection for css selection styling
http://www.w3schools.com/cssref/sel_selection.asp

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+10__
Issue added by __Beba__ on __2013-02-10__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by dstorey** [comment]
http://caniuse.com/#feat=css-selection
