### ISSUE TITLE
css3 ::marker psuedo-element support

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1114]
css3 ::marker psuedo-element support

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+13**
Issue added by **skeg64** on **2012-08-17**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
This is part of [CSS Lists and Counters Module Level 3](http://dev.w3.org/csswg/css-lists-3/).

**Comment by vmarkovtsev** [comment]
+1

**Comment by m93a** [comment]
+1

**Comment by nimmolo** [comment]
oui oui oui

**Comment by le6o** [comment]
+1

**Comment by ThomasLandauer** [comment]
+1

**Comment by sujato** [comment]
+1

**Comment by crazytonyi** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-marker-pseudo
(sorry folks, no support anywhere yet)
