### ISSUE TITLE
HTML Media Capture is at a Candidate Recommendation as of 09 May 2013. I would like this updated on ...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1115]
HTML Media Capture is at a Candidate Recommendation as of 09 May 2013. I would like this updated on caniuse and also renamed to &#39;HTML Media Capture&#39;. 

Includes MediaStreamTrack
http://www.w3.org/TR/mediacapture-streams/

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+10**
Issue added by **simzy39** on **2013-05-09**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Spec: http://www.w3.org/TR/html-media-capture/

---

> Includes MediaStreamTrack
> http://www.w3.org/TR/mediacapture-streams/

That part is already present as http://caniuse.com/#feat=stream

**Comment by petewarman** [comment]
+1 The CR spec is here by the way: [https://www.w3.org/TR/2013/CR-html-media-capture-20130509/](https://www.w3.org/TR/2013/CR-html-media-capture-20130509/)

**Comment by naicuoctavian** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=html-media-capture

**Comment by matiaslopezd** [comment]
@Fyrd Updated 2019:

https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack
