### ISSUE TITLE
gzip compression

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1116]
gzip compression

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+10**
Issue added by **Zeke** on **2014-08-24**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by ludwigschubert** [comment]
+1

**Comment by Ugoku** [comment]
-1
Seems unnecessary in 2015

**Comment by ludwigschubert** [comment]
@Ugoku I kind of agree, but would imagine a lot of people need to look that fact up. And normally I go to caniuse for looking up compatibility. Maybe there's a way of adding a low-maintenance "don't worry about it, gzip support is practically universal" page?

**Comment by Ugoku** [comment]
Okay, now I'm genuinely curious :) why do you need compatibility info on gzip? Like you said, don't worry about it, support is practically universal. gzip compatibility for me falls in the realm of `inline-block` compatibility.
If a low-maintenance solution is possible for things that have been around forever, I would be all in favour of that.

**Comment by ludwigschubert** [comment]
:D No good reason other than reference, I suppose. gzip compatibility, like the ubiquity of `inline-block` support, can be considered common knowledge for front-end devs, but might not _be_ common knowledge for everyone. 
E.g. those new to web development will still find a lot of outdated compatibility warnings on the web, and are used to checking caniuse.com as an up-to-date reference.

I should add that I have no idea how many of these once-unsupported-now-standard cases there might be out there.

**Comment by Ugoku** [comment]
Hm yeah, when you put it like that, it makes sense to include it.
Like you said though, there are many cases where you could argue the same. Should `!important` (#1388) be on there? (Not asking you specifically, but in general)
I guess the only person to properly answer that question is @Fyrd

**Comment by Fyrd** [comment]
There's some things that indeed have been supported since forever (like in IE6, Firefox 2, Chrome 1, etc) that aren't worth having tables for. Instead I have a file I put some basic info for these that shows up on search so people know they can safely use it. At some point I'll go through all these issues and look for such requests so I can include them there.

**Comment by vandres** [comment]
+1

**Comment by veob** [comment]
I agree with **ludwigschubert**

**Comment by veob** [comment]
+1

**Comment by josephsnow** [comment]
+1

**Comment by bfred-it** [comment]
+1 on "yes, everywhere" tables

**Comment by greenify** [comment]
+1 on yes too ;-)

**Comment by alexanderkjeldaas** [comment]
this should be qualified that it is for server responses.   browsers might support gzip on requests as well.

**Comment by Fyrd** [comment]
Now available as search result at http://caniuse.com/#search=gzip%20compression
