### ISSUE TITLE
Selection range

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1117]
Selection range

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+10__
Issue added by __Bjarke__ on __2011-12-20__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Related to #1070?

**Comment by dandv** [comment]
See my PR #1696

**Comment by Fyrd** [comment]
Duplicate of #1070  (#1696 covers this mostly, but need to investigate the selection part specifically)
