### ISSUE TITLE
SetImmediate

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1119]
SetImmediate

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+13__
Issue added by __Tomas__ on __2014-07-09__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by wmassingham** [comment]
+1

**Comment by godchuanz** [comment]
+1

**Comment by callumlocke** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=setimmediate
