### ISSUE TITLE
Custom scrollbars. Supported in webkit browsers only at the moment.  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1120]
Custom scrollbars. Supported in webkit browsers only at the moment.

http://css-tricks.com/custom-scrollbars-in-webkit/

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+10__
Issue added by ____ on __2012-08-15__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by extempl** [comment]
+1

**Comment by cvrebert** [comment]
-1

**Comment by cvrebert** [comment]
Duplicate of #1449.
