### ISSUE TITLE
scrollbar

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1121]
scrollbar

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+9__
Issue added by __Codler__ on __2012-03-22__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
@Fyrd This description is way too vague.

**Comment by Fyrd** [comment]
Yup.
