### ISSUE TITLE
Word breaks (<wbr/>) and soft hyphens (&shy;).   QuirksMode covers this, but is a bit out ...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1123]
Word breaks (&lt;wbr/&gt;) and soft hyphens (&amp;shy;). 

QuirksMode covers this, but is a bit out of date: http://www.quirksmode.org/oddsandends/wbr.html

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+9__
Issue added by __Callum__ on __2011-10-11__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
The `<wbr>` part duplicates #1032.

**Comment by cvrebert** [comment]
The soft hyphens part duplicates #1218.
