### ISSUE TITLE
requestAutoComplete 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1124]
requestAutoComplete http://www.whatwg.org/specs/web-apps/current-work/#dom-form-requestautocomplete

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+9**
Issue added by **Seth Ladd** on **2014-05-20**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by bolvaritamas** [comment]
+1

**Comment by KingMob** [comment]
+1

**Comment by theohogberg** [comment]
+1!

**Comment by jx2150** [comment]
+1

**Comment by cvrebert** [comment]
This feature has been removed from the HTML spec: https://github.com/whatwg/html/pull/1227
Only Chrome ever shipped it, and Chrome is now in the process of un-shipping it.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_htmlformelement_requestautocomplete
The data's a bit incomplete but given this is a deprecated feature that saw little support I think it's safe to close this issue.
