### ISSUE TITLE
Apple HLS - HTTP Live Streaming  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1126]
Apple HLS - HTTP Live Streaming

http://support.brightcove.com/en/video-cloud/docs/delivering-live-streams

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+9__
Issue added by __Owen M__ on __2014-04-24__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by timelf123** [comment]
+1

http://www.jwplayer.com/html5/hls/

**Comment by etherElric** [comment]
+1

**Comment by kalleboo** [comment]
+1

This used to be an Apple-only thing, but now Microsoft Edge has support in Windows 10 so it makes sense to start tracking

**Comment by ray-kay** [comment]
+1
After researching live streaming technologies with adaptive bandwidth capabilities I picked Apples HLS. It's a simple idea and highly performant. Might be THE future of live streaming multimedia content.

**Comment by servercimen** [comment]
+1

**Comment by digitalreb** [comment]
+1

**Comment by MarkMurphy** [comment]
+1

**Comment by artlung** [comment]
+1

**Comment by orzage** [comment]
+1

**Comment by dmcpeak7** [comment]
+1

**Comment by TheDeadCode** [comment]
+3 (We're technically 3 here hehe)

**Comment by DaleGardner** [comment]
+1

**Comment by lukasz-zaroda** [comment]
+1

**Comment by timelf123** [comment]
DASH is the new new. https://developer.mozilla.org/en-US/Apps/Fundamentals/Audio_and_video_delivery/Live_streaming_web_audio_and_video

Otherwise you can use something like this https://github.com/dailymotion/hls.js to add support for HLS, which is not an approved standard. Apple created it before the HTML5 standard was done

**Comment by billy-he** [comment]
+1

**Comment by Benimation** [comment]
+1

**Comment by mkurz** [comment]
+1

**Comment by ColinNiu** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=http-live-streaming
