### ISSUE TITLE
Media Fragments URI 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1127]
Media Fragments URI http://www.w3.org/TR/media-frags

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+16**
Issue added by **Josh T.** on **2011-09-03**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by morrislaptop** [comment]
+1

**Comment by digitalreb** [comment]
+1

**Comment by darwayne** [comment]
+1

**Comment by tigt** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=media-fragments
