### ISSUE TITLE
Webkit-based browsers extend the MediaQuery W3C Standard with specific queries for animation, transi...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1128]
Webkit-based browsers extend the MediaQuery W3C Standard with specific queries for animation, transition, etc.
I know, the MediaQueries feature is currently on board. It would be good to know, which browser supports which query. What do you think?

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+9**
Issue added by **JHerunt** on **2012-07-25**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
[Feature queries](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports) are starting to replace these.

**Comment by Fyrd** [comment]
Yeah, seems these are covered from the MDN BCD data now:
https://caniuse.com/#feat=mdn-css_at-rules_media_-webkit-transform-3d
https://caniuse.com/#feat=mdn-css_at-rules_media_-webkit-transition
etc
