### ISSUE TITLE
document.activeElement

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1129]
document.activeElement

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+16__
Issue added by __ludder__ on __2012-07-19__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
@Fyrd Is data for this also still wanted? See https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement#Browser_compatibility

**Comment by Fyrd** [comment]
Nah, let's dump it. Thanks for pointing it out.

**Comment by Fyrd** [comment]
Added as a searchable property at http://caniuse.com/#search=activeElement
