### ISSUE TITLE
The bdi (bidi isolate) element, added in HTML5 to ease inserting RTL text into an LTR page or vice-v...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1131]
The bdi (bidi isolate) element, added in HTML5 to ease inserting RTL text into an LTR page or vice-versa. I do not know if it will be supported in IE10, and I am not sure how far back its current support in WebKit and Firefox goes.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+14**
Issue added by **Aharon Lanin** on **2012-04-03**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by fabi1cazenave** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by cben** [comment]
+1

W3C's testing: http://www.w3.org/International/tests/repository/html5/the-dir-attribute/results-dir-auto#bdi

**Comment by cben** [comment]
A much wider question is whether there is support for bidi isolation at all.
Also reletad: dir="auto" [#1479] and `unicode-bidi: isolate / isolate-override` [#996].

Spec: http://www.w3.org/TR/html5/dom.html#the-dir-attribute
Comprehensive doc: http://www.w3.org/International/articles/inline-bidi-markup/

As a developer I'd want answers to 2 "big" questions:

- In which browsers dir=auto autodetecs base direction and *layout* (by flipping CSS `start`<->`end`)?

- Which browsers support bidi isolation?

I'm aware of 4 ways that are supposed to trigger bidi isolation:

1. HTML5 redefined that any element with `dir="rtl"/"ltr"/"auto"` should be bidi-isolated.
2. `<bdi>` element.  AFAICT, it's specced to be exactly equivalent to `<span dir="auto">`.
3. `unicode-bidi: isolate / isolate-override` CSS.
4. Unicode 6.3 RLI..PDI / LRI..PDI / FSI..PDI control characters.

It seems that (1) and (2) have roughly same support [basically everyone except IE] and I'd expect to see them on same page; any differences can be covered by footnotes.
[According to http://www.w3.org/International/wiki/Html-bidi-isolation#Internet_Explorer_behaviour,
IE<=7 had one non-standard behavior and IE>=8 has a different non-standard behaviour, both somewhere between old embedding and isolation]

(3) probably deserves a separate page.  While currently all but usual IE/Edge suspects have [prefixed only!] support, it might have landed in different versions than dir=... and bdi triggering isolation?
There is a relation though: given (3) it's [easy to force support for (1) and (2)](http://www.w3.org/International/articles/inline-bidi-markup/#cssshim).
[W3C's tests: http://www.w3.org/International/tests/repo/results/writing-modes-bidi]

(4) Is discouraged, doesn't interact well with markup and CSS.  Quick testing suggests it only works on Firefox.  I also suspect support will depend on OS and not just browser.  IMHO it's fine to omit.

**Comment by MoyanGG** [comment]
＋1

**Comment by rudijuri** [comment]
Now, only Edge/IE10 doesn't support this element: I would be conducive to reconsider the exclusion of bdi tag

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-html_elements_bdi
