### ISSUE TITLE
Trying to find out what browsers support CSS "vertical-align:" with a length value (ie &qu...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1136]
Trying to find out what browsers support CSS &quot;vertical-align:&quot; with a length value (ie &quot;20px&quot;). My Firefox ver 32.0.3 supports it but I was surprised that my Dreamweaver CS6 (ver 12.0) does not.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+9__
Issue added by __JacobP81__ on __2014-10-10__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Covered by http://caniuse.com/#search=vertical-align ?

**Comment by Fyrd** [comment]
Yeah.
