### ISSUE TITLE
I want to know if the input attribute readonly is useable

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1137]
I want to know if the input attribute readonly is useable

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+9__
Issue added by __tobaiasjl__ on __2014-09-04__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
+1

**Comment by Sennahoi** [comment]
+1

**Comment by DanielFurmanov** [comment]
+1 Much need, so hoping

**Comment by antoniofrignani** [comment]
+1

**Comment by LesleyDuyndam** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by Screatch** [comment]
+1

**Comment by TZanke** [comment]
+1

**Comment by rapilabs** [comment]
+1

**Comment by cvrebert** [comment]
Now available at http://caniuse.com/#feat=readonly-attr
