### ISSUE TITLE
Please add browser support for the x-frame-options security header  Thanks!

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1138]
Please add browser support for the x-frame-options security header
http://datatracker.ietf.org/doc/rfc7034/
Thanks!

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+13__
Issue added by __Dan A__ on __2014-04-10__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by hthole** [comment]
+1

**Comment by kelunik** [comment]
+1

**Comment by marumari** [comment]
I agree that this would be nice.  MDN has the various browser support levels:

https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options

**Comment by ryanvgates** [comment]
+1

**Comment by fmoo** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by thomaskonrad** [comment]
+1

**Comment by lpaloahd** [comment]
+1

**Comment by 304NotModified** [comment]
+1

**Comment by Qqwy** [comment]
+1 !

**Comment by ChaosEngine** [comment]
+1

**Comment by kelunik** [comment]
Please stop using +1, use GitHub reactions instead, otherwise it will trigger a notification for everyone.

**Comment by Schweinepriester** [comment]
@kelunik: Nope, not yet, see https://github.com/Fyrd/caniuse/issues/2408

**Comment by nicolasgarnil** [comment]
+1

**Comment by Jurugu00** [comment]
+1

**Comment by Calico90** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=x-frame-options
