### ISSUE TITLE
Number.toFixed()  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1140]
Number.toFixed()

http://www.w3schools.com/jsref/jsref_tofixed.asp

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+9__
Issue added by __m__ on __2014-09-19__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
This is really old (ECMAScript 3rd Ed.) and well-supported these days: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed#Specifications

**Comment by Ugoku** [comment]
-1
Seems unnecessary in 2015

**Comment by cvrebert** [comment]
-1

**Comment by Fyrd** [comment]
Agreed, closing this issue.
