### ISSUE TITLE
Pointer lock API (requestPointerLock, exitPointerLock, see 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1141]
Pointer lock API (requestPointerLock, exitPointerLock, see http://www.html5rocks.com/en/tutorials/pointerlock/intro/)

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+9__
Issue added by __Eric__ on __2012-08-18__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by HolgerJeromin** [comment]
same as #983

**Comment by Fyrd** [comment]
Duplicate of #983 so adding half the votes there
