### ISSUE TITLE
the withCredentials property in xhr = new XMLHttpRequest() is used to check for XMLHttpRequest suppo...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1142]
the withCredentials property in xhr = new XMLHttpRequest() is used to check for XMLHttpRequest support when creating CORS requests, specifically to detect if XDomainRequest should be used instead in Internet Explorer

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+9**
Issue added by **decibelplaces** on **2014-11-16**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
I believe this falls under http://caniuse.com/#feat=cors

**Comment by cvrebert** [comment]
@Fyrd Close as defunct?

**Comment by Fyrd** [comment]
Yeah, probably covered by cors, though now also available at https://caniuse.com/#feat=mdn-api_xmlhttprequest_withcredentials
