### ISSUE TITLE
Add supported https protocols (like SSL 2, SSL 3, TLS 1.0, TLS 1.1 TLS 1.2) and Supported Cipher sui...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1144]
Add supported https protocols (like SSL 2, SSL 3, TLS 1.0, TLS 1.1 TLS 1.2) and Supported Cipher suits.

More info see
- https://www.ssllabs.com/ssltest/viewMyClient.html 
- https://www.ssllabs.com/ssltest/clients.html

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+14__
Issue added by __andreus__ on __2015-03-07__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by tjconcept** [comment]
+1

**Comment by ximex** [comment]
+1

**Comment by nicdumz** [comment]
+1

**Comment by nicdumz** [comment]
In particular, I came here to figure out which browser were supporting SHA2 certificates.

**Comment by florianjacob** [comment]
+1

**Comment by rugk** [comment]
Well SHA2 support is another thing, but the specific SSL/TLS protocols would be nice to add so :+1:.

**Comment by frkay** [comment]
+1 especially since end of the road for TLS 1.0 has been set to June 2016 by PCI DSS 3.1, check:
https://www.pcisecuritystandards.org/documents/Migrating_from_SSL_Early_TLS_Information%20Supplement_v1.pdf
Safari desktop before 7, Internet Explorer 6, 7, 8, 9 (and even 10 when not properly configured), a lot of Android browsers do not handle TLS 1.1 and will be left in the dark.

**Comment by frkay** [comment]
To check SHA-2 compatibility:
https://support.globalsign.com/customer/portal/articles/1499561-sha-256-compatibility

**Comment by Koelli91** [comment]
+1

**Comment by lorddaedra** [comment]
:+1:

**Comment by RoelVliegen** [comment]
+1

**Comment by Naddiseo** [comment]
+1

**Comment by phanbu** [comment]
+1

**Comment by TaoK** [comment]
+1

**Comment by Fale** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by equalsJeffH** [comment]
+1

**Comment by smasher164** [comment]
+1

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by CAfromCA** [comment]
+1

**Comment by tyscorp** [comment]
+1

**Comment by frkay** [comment]
I would also add TLS extensions like SNI, since no SNI support (like IE/XP) means no way to connect to virtual domains (multiple HTTPS site on the same IP).
https://en.wikipedia.org/wiki/Server_Name_Indication

**Comment by DareBoost** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by maverickp** [comment]
+1

**Comment by Bisaloo** [comment]
+1

**Comment by radkodinev** [comment]
+1

**Comment by Llbe** [comment]
+1

**Comment by Llbe** [comment]
@frkay: see http://caniuse.com/#feat=sni

**Comment by vsvasya** [comment]
+1

**Comment by CRGreathouse** [comment]
+1

**Comment by 304NotModified** [comment]
+1

**Comment by AdrianoCahete** [comment]
+1

**Comment by scelliott** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by nhoizey** [comment]
+1

**Comment by olizilla** [comment]
+1

**Comment by relaxnow** [comment]
+1

**Comment by ESandman** [comment]
+1

**Comment by DiMFail** [comment]
+1

**Comment by rugk** [comment]
As TLS 1.3 is [on the way](https://tlswg.github.io/tls13-spec/) this feature should really be added soon...
Is not there a high priority tag?

This is the [most commented](https://github.com/Fyrd/caniuse/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Support+data+suggestion%22+sort%3Acomments-desc+) and almost the [most upvoted](https://github.com/Fyrd/caniuse/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Support+data+suggestion%22+sort%3Areactions-%2B1-desc+) data suggestion at all.

So how long will it take?

**Comment by Foorack** [comment]
+1

**Comment by nextPrime** [comment]
+1

**Comment by Cnordbo** [comment]
+1

**Comment by ScottRFrost** [comment]
+1

**Comment by Fyrd** [comment]
TLS 1.2 now available at http://caniuse.com/#feat=tls1-2
TLS 1.1 now available at http://caniuse.com/#feat=tls1-1

Search entries have been added for [TLS 1.0](http://caniuse.com/#search=tls%201.0) (supported everywhere) and [SSL](http://caniuse.com/#search=ssl) (disabled virtually everywhere)

For anyone interested in separate tables for the cipher suites, please include separate requests.

**Comment by rugk** [comment]
Awesome. Now you can go on with https://github.com/Fyrd/caniuse/issues/2225 and of course do add TLS 1.3. (It is [already supported](https://www.soeren-hentzschel.at/firefox/firefox-49-mit-erster-tls-1-3-unterstuetzung/) in the Nightly of Firefox 49)
