### ISSUE TITLE
Show support table with history as time-based, instead of versions-back-based. With Chrome and IE ve...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1147]
Show support table with history as time-based, instead of versions-back-based.
With Chrome and IE very different versioning system, the table looks a little biased.
Showing it as &quot;time since obsolete,&quot; or similar, would give better feel for the data.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+8**
Issue added by **Aviv** on **2012-02-20**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by davesmiths** [comment]
+1 this would be great. I'm interested in this: to prevent making accidental comparisons between IE6/7/8 and Firefox/Chrome 30 somethings, to see which browser has had a feature the longest (just curious), to see when a feature crossed a usage threshold

**Comment by Fyrd** [comment]
The UI has changed quite a bit since this issue was filed and I believe the "Date relative" mode handles this suggestion now.
