### ISSUE TITLE
angularjs browser compatibility

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1148]
angularjs browser compatibility

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+8__
Issue added by __eldos__ on __2014-08-07__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
@Fyrd This seems out of scope.

**Comment by Fyrd** [comment]
Yup.
