### ISSUE TITLE
Add System Info API 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1149]
Add System Info API http://www.w3.org/TR/system-info-api/

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+8**
Issue added by **hks** on **2012-06-11**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
-1

> **Work on this document has been discontinued and it should not be referenced or used as a basis for implementation.**
> Work on the System Information API specification was discontinued in favor of modular specifications, for example Battery Status API, Ambient Light Events, Proximity Events, and the Vibration API (call for consensus to discontinue work).
