### ISSUE TITLE
html tags, fieldset : all; keygen : not ie; legend : all;

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1150]
html tags,
fieldset : all;
keygen : not ie;
legend : all;

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+8__
Issue added by __Spark__ on __2014-04-01__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
I don't see the point for `<fieldset>` and `<legend>`; they're universally supported.
The `<keygen>` part of the suggestion is more sensible.

**Comment by 1ace** [comment]
+1 for `<keygen>`

**Comment by Fyrd** [comment]
`<fieldset>` & `<legend>` are now available at http://caniuse.com/#search=html4 
`<keygen>
