### ISSUE TITLE
Javascript events such as onbeforeprint and onafterprint that are raised before and after print even...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1152]
Javascript events such as onbeforeprint and onafterprint that are raised before and after print events respectively.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+8**
Issue added by **Jigar** on **2013-03-04**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
+1
MDN has no compat data on this.

**Comment by markwpiper** [comment]
+1

**Comment by chrismiddleton** [comment]
+1

**Comment by bchociej** [comment]
+1

**Comment by the-wazz** [comment]
+1

**Comment by Hajus** [comment]
+1

**Comment by luzfcb** [comment]
+1

**Comment by 3runoDesign** [comment]
+1

**Comment by J3QQ4** [comment]
+1 
Suppored in IE6+ and Firefox only

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=beforeafterprint
