### ISSUE TITLE
Ecma 262-5 availability: Object.defineProperty,  Object.create,  getters/setters,  Object.seal,  Obj...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1153]
Ecma 262-5 availability:
Object.defineProperty, 
Object.create, 
getters/setters, 
Object.seal, 
Object.isSealed, 
Object.freeze, 
Object.isFrozen, 
Object.preventExtensions, 
Function.prototype.bind, 
&quot;use strict&quot; 
etc..

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+8__
Issue added by __Alex Reese__ on __2012-05-12__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Refs #492, http://kangax.github.io/compat-table/es5

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=es5
