### ISSUE TITLE
The <keygen> tag is a bit of a mess when it comes to support, so it would be quite a useful ad...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1155]
The &lt;keygen&gt; tag is a bit of a mess when it comes to support, so it would be quite a useful addition.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+11**
Issue added by **David Mulder** on **2014-10-30**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1194.

**Comment by 1ace** [comment]
:+1: +1

**Comment by codyn329** [comment]
+1

**Comment by cvrebert** [comment]
`<keygen>` is being deprecated: https://github.com/whatwg/html/pull/26

**Comment by menorless** [comment]
+1

**Comment by dstorey** [comment]
-1. People shouldn't be using <keygen> at this stage for numerous issues listed in Chrome's intent to deprecate. Our internal data from web crawls show that in the wild it is almost never used.

**Comment by asimkt** [comment]
+1 I think even if it's going to deprecated or never going to use is not a good cause to not showing the support of the type. People are using `caniuse` for checking how much support the type gets. Showing the deprecation status in the results of `caniuse` is the best way to let people know about the issue.

**Comment by Schweinepriester** [comment]
+1 for visibility.

<https://webkit.org/blog/7093/release-notes-for-safari-technology-preview-19/>:

> Changed the keygen element to require 2048 or higher RSA key lengths

**Comment by timmc** [comment]
+1 because I just went to search for it, which means probably other people did too?

If it's deprecated in Chrome, that just makes it all the easier to track. :-P

**Comment by xtian** [comment]
+1

**Comment by vtlynch** [comment]
+1

**Comment by js-choi** [comment]
+1 for increasing awareness about deprecation and pointing people to alternatives.

**Comment by mik-laj** [comment]
+1

**Comment by Schweinepriester** [comment]
<https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/69#Removals_2>:

> The HTML [`<keygen>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/keygen "The HTML <keygen> element exists to facilitate generation of key material, and submission of the public key as part of an HTML form. This mechanism is designed for use with Web-based certificate management systems. It is expected that the <keygen> element will be used in an HTML form along with other information needed to construct a certificate request, and that the result of the process will be a signed certificate.") element has been removed from Firefox. It was deprecated some time ago, and its purpose has generally been supplanted by other technologies ([bug 1315460](https://bugzilla.mozilla.org/show_bug.cgi?id=1315460 "FIXED: Remove support for HTML Keygen")).

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-html_elements_keygen though looks like that data may need updating if Chrome's support was removed...
