### ISSUE TITLE
Mouse Lock API  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1157]
Mouse Lock API
http://dvcs.w3.org/hg/webevents/raw-file/default/mouse-lock.html
https://developer.mozilla.org/en/API/Mouse_Lock_API

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+8__
Issue added by __sideshowbarker__ on __2012-01-20__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by HolgerJeromin** [comment]
same as #983

**Comment by cvrebert** [comment]
@Fyrd Please close as duplicate.
