### ISSUE TITLE
Encrypted Media Extensions

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1161]
Encrypted Media Extensions: https://dvcs.w3.org/hg/html-media/raw-file/tip/encrypted-media/encrypted-media.html

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+11**
Issue added by **Evan** on **2014-07-21**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by sprice** [comment]
+1

**Comment by cvrebert** [comment]
-1

**Comment by ximex** [comment]
+1

**Comment by bitdivine** [comment]
+1

**Comment by soluml** [comment]
+1

**Comment by ajeffrey** [comment]
+1

**Comment by dconnolly** [comment]
+1

**Comment by digitalreb** [comment]
+1

**Comment by OrenMe** [comment]
+1

**Comment by Keavon** [comment]
+1

**Comment by tk-rand** [comment]
+1

**Comment by mvhirsch** [comment]
+1

**Comment by Calico90** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=eme

**Comment by Calico90** [comment]
Great! But not yet in the Security category.
