### ISSUE TITLE
input event

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1165]
I&#39;d like that information about https://developer.mozilla.org/en-US/docs/Web/Reference/Events/input to be included

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+13__
Issue added by __dsueiro at gmail__ on __2014-06-05__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
+1

**Comment by snater** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=input-event
