### ISSUE TITLE
dns-prefetch -> 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1167]
dns-prefetch -&gt; https://developer.mozilla.org/en-US/docs/Web/HTTP/Controlling_DNS_prefetching

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+8__
Issue added by __oli__ on __2014-08-27__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1072.

**Comment by kimslawson** [comment]
+1
