### ISSUE TITLE
`integrity` attribute for script tags. Per 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1170]
`integrity` attribute for script tags. Per http://www.w3.org/TR/SRI/

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+8__
Issue added by __kortaggio__ on __2014-09-23__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by llabball** [comment]
+1

**Comment by mozfreddyb** [comment]
+1

**Comment by jonathanKingston** [comment]
:+1: - should be in FF 42 and is in Chrome 45

**Comment by bgidley** [comment]
+1

**Comment by devjack** [comment]
+1

**Comment by maki-chan** [comment]
Title should be changed, the attribute is also allowed for `<link>` tags with `rel="stylesheet"`

**Comment by ScottHelme** [comment]
+1

**Comment by thekondrashov** [comment]
+1

**Comment by compeak** [comment]
+1

**Comment by yukulele** [comment]
+1

**Comment by mozfreddyb** [comment]
Counting over 15 more +1s in the duplicate at #1881.

@Fyrd How many votes do you usually expect for adding this? Do you accept pull requests? :)

**Comment by ametaireau** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by trullock** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=subresource-integrity
