### ISSUE TITLE
<a ping> anchor ping attribute   

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1172]
&lt;a ping&gt; anchor ping attribute

https://plus.google.com/u/0/+IlyaGrigorik/posts/fPJNzUf76Nx
http://www.whatwg.org/specs/web-apps/current-work/multipage/links.html#ping

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+16__
Issue added by __Dean Taylor__ on __2013-10-03__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
-1

**Comment by MadaraUchiha** [comment]
+1

**Comment by mik-laj** [comment]
+1

**Comment by nuno-andrade-ui** [comment]
+1

**Comment by dshope** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by pdufour** [comment]
+1

**Comment by erdavila** [comment]
+1

**Comment by harshal** [comment]
+1

**Comment by umbrae** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=ping
