### ISSUE TITLE
It would be nice if DNS preresolving could be added to caniuse, see

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1175]
It would be nice if DNS preresolving could be added to caniuse, see: http://blog.chromium.org/2008/09/dns-prefetching-or-pre-resolving.html

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+8__
Issue added by __Ernst de Haan__ on __2014-03-28__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1072.

**Comment by kimslawson** [comment]
+1
