### ISSUE TITLE
Vibration API  Available: - in Firefox (as mozVibrate) - in Webkit nightly (as webkitVibrate)  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1177]
Vibration API

Available:
- in Firefox (as mozVibrate)
- in Webkit nightly (as webkitVibrate)

http://www.w3.org/TR/vibration/

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+7__
Issue added by __Alexandre Morgaut__ on __2012-10-02__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by HolgerJeromin** [comment]
this is released: http://caniuse.com/#search=vibration
