### ISSUE TITLE
activeElement

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1178]
activeElement

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+7__
Issue added by __spurv__ on __2013-05-03__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1129.

**Comment by cvrebert** [comment]
@Fyrd Please close as duplicate.
