### ISSUE TITLE
What about including a CSS4 selectors table? You can test this feature here

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1182]
What about including a CSS4 selectors table?
You can test this feature here: http://css4-selectors.com/browser-selector-test/

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+9__
Issue added by __enricflorit__ on __2013-07-25__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1058.
