### ISSUE TITLE
Hyperlink auditing / ping attribute on a link  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1183]
Hyperlink auditing / ping attribute on a link

http://www.whatwg.org/specs/web-apps/current-work/multipage/links.html#hyperlink-auditing

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+7__
Issue added by __Bryan__ on __2011-11-06__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1172.
