### ISSUE TITLE
document.currentScript –  – is implemented by Firefox 4+, so far.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1186]
document.currentScript &ndash;&nbsp;https://developer.mozilla.org/en/DOM/document.currentScript &ndash;&nbsp;is implemented by Firefox 4+, so far.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+7__
Issue added by __ecmanaut__ on __2012-05-01__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1099.
