### ISSUE TITLE
Web Cryptography API, Encrypted Media Extensions and Web Cryptography API. Needed for streaming of p...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1187]
Web Cryptography API, Encrypted Media Extensions and Web Cryptography API. Needed for streaming of premium content. Chrome supports former two. IE11 supports all three.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+7__
Issue added by __David Storey__ on __2013-06-28__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
The EME part is a duplicate of #1161.

**Comment by cvrebert** [comment]
And crypto is covered by http://caniuse.com/#feat=cryptography
@Fyrd Please close?
