### ISSUE TITLE
Based on this page   I suggest to add  addRule and  insertRule  Thanks

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1188]
Based on this page : http://stackoverflow.com/questions/707565/how-do-you-add-css-with-javascript

I suggest to add 
addRule and 
insertRule

Thanks

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+7**
Issue added by **linediconsine** on **2014-04-28**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
i.e. https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet

**Comment by alimoosavi15** [comment]
http://www.quirksmode.org/dom/w3c_css.html

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_cssstylesheet_addrule & https://caniuse.com/#feat=mdn-api_cssstylesheet_insertrule
