### ISSUE TITLE
polymer 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1190]
polymer
https://www.polymer-project.org/

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+7__
Issue added by __dotnetwise__ on __2014-10-08__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
This seems out of scope.

**Comment by Fyrd** [comment]
Yup.
