### ISSUE TITLE
document.elementFromPoint

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1193]
document.elementFromPoint

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+8__
Issue added by __tomjr__ on __2014-09-05__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by techsin** [comment]
+1

**Comment by cvrebert** [comment]
* https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint
* http://www.quirksmode.org/dom/tests/elementfrompoint.html
* https://github.com/moll/js-element-from-point#further-reading

**Comment by itsrachelfish** [comment]
:+1:

**Comment by goatslacker** [comment]
+1

**Comment by JoshuaCarmody** [comment]
Came here to suggest this, since I went to check support on caniuse.com and didn't find anything.

**Comment by robverhoef** [comment]
+1

**Comment by zeprone** [comment]
+1

**Comment by quangkieu** [comment]
+1

**Comment by thachmai** [comment]
+1

**Comment by zongren** [comment]
+1

**Comment by ManuelB** [comment]
+1

**Comment by danielmag** [comment]
+1

**Comment by hampelm** [comment]
+1

**Comment by skerit** [comment]
+1

**Comment by qfan** [comment]
+1

**Comment by hxmilyy** [comment]
+1

**Comment by hkhesehus** [comment]
+1

**Comment by javpaw** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=element-from-point
