### ISSUE TITLE
It would be good to show status for TextEncoder/TextDecoder

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1195]
It would be good to show status for TextEncoder/TextDecoder from http://encoding.spec.whatwg.org/#interface-textencoder and http://encoding.spec.whatwg.org/#interface-textdecoder

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+10__
Issue added by __bz__ on __2014-03-21__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by gordonwoodhull** [comment]
+1

**Comment by mlimper** [comment]
+1

**Comment by addaleax** [comment]
+1

**Comment by Darker** [comment]
+1 +1

Relevant resources:
https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder#Browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder#Browser_compatibility

**Comment by jacoscaz** [comment]
+1

**Comment by cblichmann** [comment]
+1

**Comment by 74h7k3fg** [comment]
+1

**Comment by Bandreus** [comment]
+1

**Comment by arv** [comment]
+1

**Comment by albell** [comment]
+1 @Darker thanks for the links. Please comment if anyone has info about the Mozilla support table being inaccurate.

**Comment by oising** [comment]
+1

**Comment by lingtalfi** [comment]
+1
https://developers.google.com/web/updates/2014/08/Easier-ArrayBuffer-String-conversion-with-the-Encoding-API

**Comment by brion** [comment]
+1

**Comment by zhanghc89** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=textencoder
