### ISSUE TITLE
Messaging API (SMS) 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1196]
Messaging API (SMS)
http://www.w3.org/TR/messaging-api/

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+7**
Issue added by **Alexandre Morgaut** on **2012-06-03**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by xtian** [comment]
-1 

> Work on this document has been discontinued and it should not be referenced or used as a basis for implementation.

**Comment by M2Ys4U** [comment]
-1

**Comment by NOtherDev** [comment]
-1

**Comment by Fyrd** [comment]
Deprecated spec and I don't think this was implemented anywhere.
