### ISSUE TITLE
rel="noreferrer"

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1197]
rel=&quot;noreferrer&quot;: http://www.w3.org/html/wg/drafts/html/master/links.html#link-type-noreferrer

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+7**
Issue added by **Ralph C** on **2014-02-13**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
This is **separate** from https://github.com/Fyrd/caniuse/blob/master/features-json/referrer-policy.json

**Comment by wrygiel** [comment]
+1

**Comment by entendu** [comment]
+1

**Comment by z38** [comment]
+1

**Comment by thomaspre** [comment]
+1

**Comment by fjsj** [comment]
+1

**Comment by tonyjin** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by jasonadt** [comment]
+1

**Comment by Nothing4You** [comment]
+1

**Comment by neilj** [comment]
+1

**Comment by Llbe** [comment]
+1

**Comment by Schweinepriester** [comment]
+1, but I think #1254 is the better issue for this, as `rel="noreferrer"` is correct, not `ref="noreferrer"`.

**Comment by ygoe** [comment]
+1

**Comment by Fyrd** [comment]
Renamed to correct attribute name.

**Comment by agwells** [comment]
+1

**Comment by theotix** [comment]
+1

**Comment by Calico90** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=rel-noreferrer

**Comment by ygoe** [comment]
Are you sure IE11 doesn't support this? To me it looks like it's perfectly not sending the referrer on such links.

**Comment by Nothing4You** [comment]
Tested with IE11 version 11.953.14393.0, can confirm that it looks like it's working fine

**Comment by Fyrd** [comment]
Interesting, so it doesn't work in my test in Win 8.1 or an older version of Win 10, but it does the latest. Have updated the support with a note to reflect this. Thanks!

**Comment by ygoe** [comment]
I still have the Anniversary Update (Windows 10.1607) and it works there. I don't have any older versions to test.
