### ISSUE TITLE
Efficient Script Yielding (setImmediate) 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1202]
Efficient Script Yielding (setImmediate) : https://dvcs.w3.org/hg/webperf/raw-file/tip/specs/setImmediate/Overview.html

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+7__
Issue added by __Fyrd__ on __2011-12-19__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1119.
