### ISSUE TITLE
Please add, Window.event.KeyCode and Window.event.charCode also to the directory.  Event.keyCode wor...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1205]
Please add, Window.event.KeyCode and Window.event.charCode also to the directory.

Event.keyCode works for both IE and Chrome but does not work in Firefox,
Event.charCode works for Firefox.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+7__
Issue added by __Harsha__ on __2014-07-28__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
+1

**Comment by KevinField** [comment]
+1

**Comment by greypants** [comment]
+1

**Comment by cvrebert** [comment]
`KeyboardEvent.keyCode` is "universally" supported; see https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode#Browser_compatibility

**Comment by KevinField** [comment]
@cvrebert yes, but it's also deprecated, see the note at the top of the page you linked to.

**Comment by Fyrd** [comment]
`charCode` and others are now available at http://caniuse.com/#search=keyboardevent
(keyCode covered by #1988)
