### ISSUE TITLE
Scheme-less URIs, aka the relative URIs. See

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1206]
Scheme-less URIs, aka the relative URIs. See: http://stackoverflow.com/questions/550038/is-it-valid-to-replace-http-with-in-a-script-src-http.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+7**
Issue added by **randomir** on **2013-04-25**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Ugoku** [comment]
-1
This has been around for so long, it seems useless. Also, it's not [recommended usage anymore](http://www.paulirish.com/2010/the-protocol-relative-url/)

**Comment by Schweinepriester** [comment]
-1

**Comment by Fyrd** [comment]
Closing per comments above and due to lack of interest.
