### ISSUE TITLE
mp3, ogg, webm, wav, aac... for audio

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1208]
mp3, ogg, webm, wav, aac... for audio

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+7__
Issue added by __mh_nichts__ on __2014-09-02__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by duanyao** [comment]
+1

**Comment by Fyrd** [comment]
Duplicate of #988 so moving half the votes there.
