### ISSUE TITLE
attr() from CSS3 Values and Units, specifically properties other than 'content' and non-stri...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1209]
attr() from CSS3 Values and Units, specifically properties other than &#39;content&#39; and non-string values

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+7__
Issue added by __Brett C.__ on __2013-02-22__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by sabberworm** [comment]
+1

**Comment by matthewalbani** [comment]
+1

**Comment by TWiStErRob** [comment]
+1

**Comment by zinkkrysty** [comment]
+1

**Comment by connorshea** [comment]
+1

**Comment by Fyrd** [comment]
Actually this one's support is already covered by http://caniuse.com/#feat=css-gencontent ...just need to do something about it not showing up at the top when searching for `attr()`

**Comment by cvrebert** [comment]
@Fyrd Umm...:
> attr() from CSS3 Values and Units, **specifically properties other than 'content'**

**Comment by Fyrd** [comment]
@cvrebert Ha, that's what I get for not paying attention.

**Comment by HoBi** [comment]
+1

**Comment by charlietoleary** [comment]
+1

**Comment by cvrebert** [comment]
+1

**Comment by stevenvachon** [comment]
Do it.

**Comment by smohadjer** [comment]
+1

**Comment by wikt0r** [comment]
+1

**Comment by AlanLeonard** [comment]
+1

**Comment by cvrebert** [comment]
* https://bugs.webkit.org/show_bug.cgi?id=26609
* https://bugzilla.mozilla.org/show_bug.cgi?id=435426
* https://bugs.chromium.org/p/chromium/issues/detail?id=246571
* https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/7671960-css-attr-as-defined-in-css-values-level-3

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css3-attr (no support anywhere yet)

**Comment by TWiStErRob** [comment]
So if #1866 is a dupe of this, then how does "no support anywhere" cover #1866?

**Comment by cvrebert** [comment]
@TWiStErRob http://caniuse.com/#feat=css-gencontent covers CSS2's `content: attr(...);`

**Comment by TWiStErRob** [comment]
Ah thanks, that makes sense. Would it be possible to optimise the search a little? For me searching for "attr" lists "css-gencontent" at position 24 out of 33, I think that's too low.
