### ISSUE TITLE
:invalid CSS pseudo-class 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1210]
:invalid CSS pseudo-class
https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+7__
Issue added by __bkaplan__ on __2014-05-07__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Already covered by http://caniuse.com/#search=invalid
