### ISSUE TITLE
CSS3 "cross-fade" as in:  <image-combination> = cross-fade( <image >, <imag...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1219]
CSS3 &quot;cross-fade&quot; as in: 
&lt;image-combination&gt; = cross-fade( &lt;image &gt;, &lt;image&gt;, &lt;percentage&gt;)

(As seen in this tutorial: http://www.imajine.in/tutorials/css/crossfade.aspx)

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+7__
Issue added by __Maria__ on __2012-06-09__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
http://www.w3.org/TR/css4-images/#cross-fade-function

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-cross-fade
