### ISSUE TITLE
ArrayBuffer;  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1220]
ArrayBuffer;  https://developer.mozilla.org/en/JavaScript_typed_arrays/ArrayBuffer

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __mud__ on __2011-11-23__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Covered by http://caniuse.com/#feat=typedarrays

**Comment by cvrebert** [comment]
@Fyrd Close this since the data is already present?

**Comment by Fyrd** [comment]
Alright, added a note on this at http://caniuse.com/#feat=typedarrays
