### ISSUE TITLE
CSS4 Specify the subject of a selector by prepending $  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1221]
CSS4 Specify the subject of a selector by prepending $

http://www.w3.org/TR/2011/WD-selectors4-20110929/#subject

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __Daniel Heath__ on __2011-12-07__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Refs #1182.

**Comment by cvrebert** [comment]
This feature was removed in the 2012 draft (http://www.w3.org/TR/2012/WD-selectors4-20120823/) and remains gone in the current editor's draft (https://drafts.csswg.org/selectors-4/).

See also:
> **Changes**
> [...]
> * [Replaced subject indicator feature with :has().](https://drafts.csswg.org/selectors-4/#changes)

**Comment by cvrebert** [comment]
And `:has()` is covered by #1268.

**Comment by cvrebert** [comment]
@Fyrd This suggestion seems to have become invalid; see above comments.

**Comment by Fyrd** [comment]
Yeah, you're right. Closing.
