### ISSUE TITLE
Browser support for RTP streams?

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1224]
Browser support for RTP streams?

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+6**
Issue added by **kero** on **2012-08-23**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Schweinepriester** [comment]
Maybe covered by MDN? <https://caniuse.com/?search=RTP%20streams>

**Comment by GPHemsley** [comment]
What is the scope of this issue? RTP in WebRTC?
https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Intro_to_RTP

If so, then it does indeed appear to be covered by MDN data:
https://caniuse.com/mdn-api_rtcrtpsender
https://caniuse.com/mdn-api_rtcrtpreceiver
https://caniuse.com/mdn-api_rtcrtptransceiver

(via mdn/browser-compat-data#994, mdn/browser-compat-data#993, mdn/browser-compat-data#948)

**Comment by Fyrd** [comment]
Agreed that it seems covered, plus I'm not seeing anyone ask more specifically about this feature, so closing.
