### ISSUE TITLE
:first-line pseudo selector

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1226]
:first-line pseudo selector

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __pixelcort__ on __2012-03-15__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
@Fyrd Duplicate of #1109.
