### ISSUE TITLE
Javascript: Array.prototype.fill()  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1227]
Javascript: Array.prototype.fill()

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+6**
Issue added by **Pembeci** on **2015-01-15**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
http://kangax.github.io/compat-table/es6/#Array.prototype_methods_Array.prototype.fill

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_builtins_array_fill and part of https://caniuse.com/#feat=es6
