### ISSUE TITLE
clipboardData: text, rtf, html, image, etc.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1228]
clipboardData: text, rtf, html, image, etc.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+6**
Issue added by **Alok Menghrajani** on **2011-11-11**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Falls under http://caniuse.com/#feat=clipboard , although this doesn't seem to be specifically covered currently.

**Comment by 304NotModified** [comment]
+1

**Comment by Fyrd** [comment]
Covered by https://caniuse.com/#feat=mdn-api_clipboardevent_clipboarddata

**Comment by yoyo837** [comment]
Need a more specific introduction format: `text/html`, `text/plain`, `text/rtf`...
