### ISSUE TITLE
CSS Paged Media 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1229]
CSS Paged Media
https://developer.mozilla.org/en-US/docs/Web/CSS/@page

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+15__
Issue added by __Nick Walker__ on __2014-08-07__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by CaesarSchinas** [comment]
+1

**Comment by jessedyck** [comment]
+1

**Comment by cvrebert** [comment]
+1

**Comment by iainhouston** [comment]
+1

**Comment by tgraham-antenna** [comment]
+1

**Comment by jan-tosovsky-cz** [comment]
+1

**Comment by kwkbtr** [comment]
+1

**Comment by MurakamiShinyu** [comment]
+1

**Comment by DavidSabine** [comment]
+1

**Comment by dauwhe** [comment]
+1

**Comment by johanneswilm** [comment]
+1

**Comment by claicham** [comment]
+1

**Comment by sobolz** [comment]
+1

**Comment by mik-laj** [comment]
+1

**Comment by Benimation** [comment]
+1

**Comment by miclf** [comment]
+1

**Comment by tuespetre** [comment]
+1

**Comment by tuespetre** [comment]
#### Tracked Bugs:
Webkit: https://bugs.webkit.org/show_bug.cgi?id=85062
Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=286443
Edge: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/12839052-css-paged-media-module-level-3

**Comment by Llbe** [comment]
+1

**Comment by DiMFail** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-paged-media
