### ISSUE TITLE
ChildNode.remove() 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1230]
ChildNode.remove()
https://developer.mozilla.org/en-US/docs/Web/API/ChildNode.remove

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __Jeffrey Y__ on __2014-05-04__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by jboolean** [comment]
+1

**Comment by mchateloin** [comment]
+1 

Looks like in IE11 and below you have to use ChildNode.removeNode(): https://msdn.microsoft.com/en-us/library/ms536708(v=vs.85).aspx

**Comment by mahemoff** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=childnode-remove
