### ISSUE TITLE
From   "The input and button elements have formaction, formenctype, formmethod, formnovalidate,...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1233]
From http://www.w3.org/TR/html5-diff/#new-attributes

&quot;The input and button elements have formaction, formenctype, formmethod, formnovalidate, and formtarget as new attributes. If present, they override the [...] attributes on the form element.&quot;

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __Validatorian__ on __2013-02-16__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1562.
