### ISSUE TITLE
Object.assign

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1234]
Object.assign

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+6**
Issue added by **Kaleb** on **2014-12-09**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
http://kangax.github.io/compat-table/es6/#Object_static_methods_Object.assign

**Comment by chilicoder** [comment]
+1

**Comment by dejwid** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

**Comment by koutsenko** [comment]
Still no support? :(

**Comment by 304NotModified** [comment]
+1

**Comment by Fyrd** [comment]
Covered by https://caniuse.com/#feat=mdn-javascript_builtins_object_assign & https://caniuse.com/#feat=es6
