### ISSUE TITLE
Transferable Objects (in the context of Web Workers)

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1241]
Transferable Objects (in the context of Web Workers): http://www.whatwg.org/specs/web-apps/current-work/multipage/common-dom-interfaces.html#transferable-objects

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __Joel__ on __2011-12-28__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by antimatter15** [comment]
+1

**Comment by pornel** [comment]
:+1:

**Comment by qm3ster** [comment]
+1

**Comment by Fyrd** [comment]
Duplicate of #1132 (which has more votes)
