### ISSUE TITLE
As there are still plenty of CSS2 rules that aren't fully supported it would be great to have th...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1243]
As there are still plenty of CSS2 rules that aren&#39;t fully supported it would be great to have those added as well.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __hindins__ on __2013-02-28__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
This seems too vague.

**Comment by Fyrd** [comment]
Yeah.
