### ISSUE TITLE
image-rendering: auto image-rendering: crisp-edges image-rendering: pixelated image-rendering: inher...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1246]
image-rendering: auto
image-rendering: crisp-edges
image-rendering: pixelated
image-rendering: inherit

https://developer.mozilla.org/en/docs/Web/CSS/image-rendering

Pixel artists everywhere will be delighted.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __S Davis__ on __2014-05-02__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Covered by http://caniuse.com/#feat=css-crisp-edges

**Comment by yisibl** [comment]
WebKit Nightly support `image-rendering: pixelated`

* Bugs: https://bugs.webkit.org/show_bug.cgi?id=146771
* Demo: https://css-tricks.com/almanac/properties/i/image-rendering/
