### ISSUE TITLE
HPKP is draft for security 'certificate pinning' through a new HTTP header.  This protection...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1248]
HPKP is draft for security &#39;certificate pinning&#39; through a new HTTP header.  This protection reduces the likelihood of successful MITM attacks against TLS through rogue or compromised CAs.

https://tools.ietf.org/html/draft-ietf-websec-key-pinning-21

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __s__ on __2014-10-30__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by hthole** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=publickeypinning
