### ISSUE TITLE
Please add NetworkInformation.connection API.   

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1249]
Please add NetworkInformation.connection API.

http://davidbcalhoun.com/2010/using-navigator-connection-android/
https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation.connection

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __Torsten W__ on __2014-07-25__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1031.
