### ISSUE TITLE
TextEncoder interface:    Latest Opera and Firefox already support it.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1251]
TextEncoder interface:

http://encoding.spec.whatwg.org/#interface-textencoder

Latest Opera and Firefox already support it.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __Kornel__ on __2014-02-18__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1195.
