### ISSUE TITLE
DeviceOrientation API for accessing Accelerometer & Gyroscope sensor data

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1252]
DeviceOrientation API for accessing Accelerometer &amp; Gyroscope sensor data

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __mmiesi__ on __2012-03-06__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Covered by http://caniuse.com/#feat=deviceorientation
