### ISSUE TITLE
Element.closest()  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1253]
Element.closest()

https://dom.spec.whatwg.org/#dom-element-closest

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __Greg__ on __2014-11-04__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
+1

**Comment by xing-zhi** [comment]
+1

**Comment by Ugoku** [comment]
+1

**Comment by TrySound** [comment]
Also there is a [polyfill](https://github.com/jonathantneal/closest) for closest and matches.

**Comment by boxofrox** [comment]
+1

**Comment by afroald** [comment]
+1

**Comment by vsemozhetbyt** [comment]
+1

**Comment by benkaiser** [comment]
+1

**Comment by CaitlinWeb** [comment]
+1

**Comment by jboolean** [comment]
+1

**Comment by TrySound** [comment]
+1

**Comment by Llbe** [comment]
+1

**Comment by jaydenseric** [comment]
+1

**Comment by stof** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=element-closest
