### ISSUE TITLE
rel="noreferrer"

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1254]
rel=&quot;noreferrer&quot;

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+6**
Issue added by **mishak** on **2014-05-09**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
https://html.spec.whatwg.org/multipage/semantics.html#link-type-noreferrer

**Comment by Schweinepriester** [comment]
Isn't this the better version of #1197, because `rel=…` seems to be correct, not `ref=…` as seen in the [link above](https://html.spec.whatwg.org/multipage/semantics.html#link-type-noreferrer)?

**Comment by agwells** [comment]
+1

**Comment by Fyrd** [comment]
Duplicate of #1197, have renamed it accordingly.
