### ISSUE TITLE
`@viewport` media query?  According to the treehouse article,  it's supposed to be a standard an...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1256]
`@viewport` media query?

According to the treehouse article, http://blog.teamtreehouse.com/thinking-ahead-css-device-adaptation-with-viewport it&#39;s supposed to be a standard and replace the `&lt;meta name=&quot;viewport&quot;&gt;` tag

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __cheapsteak__ on __2014-07-23__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
This is part of the CSS Device Adaptation Module (http://dev.w3.org/csswg/css-device-adapt/).

**Comment by cvrebert** [comment]
Already covered by http://caniuse.com/#feat=css-deviceadaptation
