### ISSUE TITLE
Add browser support for text-decoration-skip [ - Not sure if any browsers support it yet, but someth...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1257]
Add browser support for text-decoration-skip [http://dev.w3.org/csswg/css-text-decor-3/#text-decoration-skip] - Not sure if any browsers support it yet, but something to keep on the horizon.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+6**
Issue added by **Schalk** on **2014-03-26**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by adamschwartz** [comment]
:+1: 

I believe Safari 8 is now partially supporting this (and possibly earlier versions did as well) with the `-webkit-` prefix. Currently I believe only `none` and `ink` are supported. Here’s a screenshot of a [jsFiddle](http://jsfiddle.net/adamschwartz/y1xbe36a/) I made to test:

<img alt="text decoration skip test" src="https://cloud.githubusercontent.com/assets/154613/8973450/cb759264-3632-11e5-8cec-73baa259dde5.png">

**Comment by lassediercks** [comment]
Afaik the shorthand property `text-decoration`is widerly supported but the longhand ones are not. 

Is this the reason why [the caniuse search for text-decoration](http://caniuse.com/#search=text-decoration) tells me that it's only usable in firefox?

**Comment by Schweinepriester** [comment]
+1, this should be separate from the reference at <http://caniuse.com/#feat=text-decoration>

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_properties_text-decoration-skip
