### ISSUE TITLE
http://www.w3.org/TR/css3-marquee/ is not searchable here in Caniuse.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1258]
http://www.w3.org/TR/css3-marquee/ is not searchable here in Caniuse.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __TylerH__ on __2014-09-30__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1499.
