### ISSUE TITLE
<input type='tel'>

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1259]
&lt;input type=&#39;tel&#39;&gt;

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __Val__ on __2014-09-29__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1097.
