### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/Events/wheel

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1260]
https://developer.mozilla.org/en-US/docs/Web/Events/wheel

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+6**
Issue added by **Thomas** on **2014-06-23**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by KeitIG** [comment]
+1

**Comment by mmastrac** [comment]
+1

**Comment by amermahmud** [comment]
+1

**Comment by SimonSelg** [comment]
+1

**Comment by tapananand** [comment]
+1

**Comment by BryanTheCrow** [comment]
+1 ... note Edge claims to support this... but its support is spotty with trackpad scroll gestures. Specifically it does not work properly with so-called "precision" trackpads, like those found on the Surface family of devices.

**Comment by w0d** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_element_wheel_event
