### ISSUE TITLE
The 'media' attribute from the source element for HTML5's audio and video elements.  Thi...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1261]
The &#39;media&#39; attribute from the source element for HTML5&#39;s audio and video elements.

This attribute allows you to specify an audio or video source that matches a particular media query.

(currently supported by all major desktop and mobile browsers)

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+6**
Issue added by **Ian Devlin** on **2014-02-12**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
MDN suggests that this would fall under http://caniuse.com/#feat=picture , though I don't see any text specifically addressing it.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_htmlsourceelement_media
