### ISSUE TITLE
Why do white-space not appear to be in the list? :)

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1262]
Why do white-space not appear to be in the list? :)

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+8**
Issue added by **sebascar** on **2012-07-07**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by TZanke** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by YuCJ** [comment]
+1

**Comment by ThePsionic** [comment]
+1

**Comment by kiding** [comment]
The new (old?) `white-space: break-spaces` property is being implemented by the browsers. See the commit references in https://github.com/w3c/csswg-drafts/pull/2841.

**Comment by Schweinepriester** [comment]
> The new (old?) `white-space: break-spaces` property is being implemented by the browsers.

Indeed, coming with:

- Chrome 76 (https://www.chromestatus.com/feature/4842781306519552)
- Firefox 69 (https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/69)
- Safari TP 80 thus implying Safari 13 (https://webkit.org/blog/8825/release-notes-for-safari-technology-preview-80/)

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_properties_white-space
( & break-spaces here: https://caniuse.com/#feat=mdn-css_properties_white-space_break-spaces )
