### ISSUE TITLE
bdi stands for Bi-directional Isolation. New feature implemented in FF 10

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1263]
bdi stands for Bi-directional Isolation. New feature implemented in FF 10

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __Denis V__ on __2012-01-31__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1131.
