### ISSUE TITLE
Add HTML5 spellcheck attr.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1265]
Add HTML5 spellcheck attr.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __qq__ on __2014-02-27__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Already covered: http://caniuse.com/#feat=spellcheck-attribute
