### ISSUE TITLE
Javascript "devicemotion" should be added to the site.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1267]
Javascript &quot;devicemotion&quot; should be added to the site.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __Ralph__ on __2014-07-27__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Covered by http://caniuse.com/#feat=deviceorientation
