### ISSUE TITLE
Include the :has selector from CSS level 4 draft 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1268]
Include the :has selector from CSS level 4 draft : http://dev.w3.org/csswg/selectors4/#relational

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+7__
Issue added by __Sebastien__ on __2014-10-29__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Refs #1182.

**Comment by TuggyNE** [comment]
+1 on this, I'd like to track this a little more easily and see what the status is. (Probably still "none", but that's useful information.)

**Comment by cvrebert** [comment]
+1

**Comment by cvrebert** [comment]
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=418039

**Comment by ianstormtaylor** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by Ugoku** [comment]
+1

**Comment by kazelsama** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-has (don't get your hopes up, no browsers are developing this yet)
