### ISSUE TITLE
blink tag

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1269]
blink tag

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+6**
Issue added by **thejohnsmith** on **2015-02-17**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
The marquee portion duplicates #1499.

**Comment by Fyrd** [comment]
Removed the marquee portion.

**Comment by cvrebert** [comment]
-1

**Comment by Fyrd** [comment]
For now I have included this in the "obsolete elements" list at http://caniuse.com/#search=blink

As authors are advised not to use these tags I'm not in a rush to include support data, but if eventually it gets enough votes I'll reconsider.

**Comment by w3l** [comment]
+1

**Comment by ArkadiuszPodolski** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
Dnia Czwartek, 31 Grudnia 2015 00:59 w3l <notifications@github.com> napisa³(a)

+1

**Comment by claudepache** [comment]
Removed from Firefox 23 (Aug 2013) https://bugzilla.mozilla.org/show_bug.cgi?id=857820.
Also removed from Opera long ago.
Has never been supported by IE, Chrome, Safari.
Don’t know whether it’s still supported by Lynx, though...

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-html_elements_blink
