### ISSUE TITLE
Please can you add 'beforeunload' and 'onbeforeunload'

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1270]
Please can you add &#39;beforeunload&#39; and &#39;onbeforeunload&#39;

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+6__
Issue added by __Errolo__ on __2014-11-20__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1391 ?

**Comment by Fyrd** [comment]
Yup.

**Comment by liufa** [comment]
+1
