### ISSUE TITLE
rebeccapurple color 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1271]
rebeccapurple color http://dev.w3.org/csswg/css-color/#valuedef-color-rebeccapurple

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+6**
Issue added by **MoOx** on **2014-08-13**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Ugoku** [comment]
+1

**Comment by danwood** [comment]
+1

**Comment by rudedogg** [comment]
+1

**Comment by astoilkov** [comment]
+1

**Comment by fivegreenapples** [comment]
+1

**Comment by Semigradsky** [comment]
+1

**Comment by ben-eb** [comment]
### Issues

* Webkit bug: https://bugs.webkit.org/show_bug.cgi?id=133804
* Chrome bug: https://src.chromium.org/viewvc/blink?view=revision&revision=179321
* Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1024642

### Demo

http://dabblet.com/gist/69fee57c26b73996b53f

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-rebeccapurple
