### ISSUE TITLE
Dialogs implemented using separate documents  window.showModalDialog()  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1273]
Dialogs implemented using separate documents

window.showModalDialog()

http://www.whatwg.org/specs/web-apps/current-work/multipage/timers.html#dialogs-implemented-using-separate-documents

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+5**
Issue added by **Alexandre Morgaut** on **2012-05-01**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
-1
It's super-deprecated and Chrome is in the process of killing it.

**Comment by monkpit** [comment]
@cvrebert Isn't that why it should be a part of the site? It works just fine in versions of IE and firefox. +1

**Comment by xairrick** [comment]
+1 what @cvrebert  said.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_window_showmodaldialog
