### ISSUE TITLE
I would like to see document.readyState supported values in the caniuse.com

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1274]
I would like to see document.readyState supported values in the caniuse.com

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+5**
Issue added by **velu** on **2014-10-29**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by aceade** [comment]
+1
I ran into an issue where IE10 doesn't support a readyState of 'interactive' - unlike Firefox, Chrome, and IE 11. However, it does support a readyState of 'complete'.

**Comment by JoyceBabu** [comment]
+1

**Comment by karthiick** [comment]
+1

**Comment by jpc-ae** [comment]
+1
This and onreadystatechange need to be included as they work as a slightly more advanced alternative to DOMContentLoaded, which is already included.

**Comment by spoutnikz** [comment]
+1

**Comment by epigeyre** [comment]
+1

**Comment by knynkwl** [comment]
+1

**Comment by aximario** [comment]
+1

**Comment by knynkwl** [comment]
+1

**Comment by CKH4** [comment]
+1

**Comment by murashki** [comment]
+1

**Comment by samChang72** [comment]
+1

**Comment by spade69** [comment]
+1 lol

**Comment by marsiancba** [comment]
+1

**Comment by Peeeep** [comment]
+1

**Comment by jhabdas** [comment]
<img width="845" alt="screen shot 2017-06-19 at 6 42 13 pm" src="https://user-images.githubusercontent.com/440298/27281606-16cdb9d2-551f-11e7-9d46-91a4c92566ce.png">

Please make this happen. http://devdocs.io/dom/document/readystate

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_document_readystate

**Comment by antonjuulnaber** [comment]
@Fyrd This issue is still exposed in the [feature suggestion list on caniuse](https://caniuse.com/issue-list) (currently ranked `#7`)
