### ISSUE TITLE
"click" function on anchor DOM element (a)

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1275]
&quot;click&quot; function on anchor DOM element (a)

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+5**
Issue added by **Wes** on **2014-09-09**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
-1

**Comment by GCDeveloper** [comment]
+1

**Comment by Fyrd** [comment]
The click method exists on all elements, not just anchors. Support table now available here:
https://caniuse.com/#feat=mdn-api_htmlelement_click
