### ISSUE TITLE
Similar to MPEG-4 / WebM support page, you might want to add a page for MPEG-DASH support.  See:   A...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1278]
Similar to MPEG-4 / WebM support page, you might want to add a page for MPEG-DASH support.

See:
http://stackoverflow.com/questions/22292224/which-web-browsers-support-the-mpeg-dash-streaming-protocol

Also, MSE support would be good to explain.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+5**
Issue added by **ginger** on **2014-11-09**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by sprice** [comment]
+1

**Comment by jeremyshantz** [comment]
+1

**Comment by jrstanley** [comment]
+1

**Comment by ysbcc** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mpeg-dash
