### ISSUE TITLE
user-input  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1280]
user-input

http://www.w3.org/TR/2000/WD-css3-userint-20000216#user-input

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+5**
Issue added by **epeleg** on **2012-07-24**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
-1
It's unlikely that this was ever implemented outside of Mozilla's prefixed [`-moz-user-input`](https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-user-input).
The spec in question was never completed and was superseded by [CSS3 UI](https://drafts.csswg.org/css-ui/), which doesn't define such a property.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_properties_-moz-user-input
