### ISSUE TITLE
box-decoration-break (see 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1281]
box-decoration-break (see http://www.w3.org/TR/css3-background/#box-decoration-break)

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __Lensco__ on __2012-06-08__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Already covered: http://caniuse.com/#feat=css-boxdecorationbreak
