### ISSUE TITLE
letter-spacing with a decimal point  Not all browsers fully support letter-spacing, with fractional ...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1282]
letter-spacing with a decimal point

Not all browsers fully support letter-spacing, with fractional pixels, e.g. letter-spacing: 1.5px

(e.g. Chrome doesn&#39;t properly support letter-spacing with decimal points, and rounds them)

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __jj05__ on __2012-09-05__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Approximate duplicate of #1002.

**Comment by Fyrd** [comment]
Updated #1002 to include that info so I can close this as duplicate.
