### ISSUE TITLE
zoom - css property

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1285]
zoom - css property

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __Edgaras__ on __2012-11-06__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
-1

**Comment by pkuczynski** [comment]
This is a duplicate of #1453 and it can be closed @Fyrd
