### ISSUE TITLE
Add cursor.  Justification: IE9/IE10 don't support PNG/JPG cursors, Mac/Firefox and Mac/Chrome h...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1286]
Add cursor.

Justification: IE9/IE10 don&#39;t support PNG/JPG cursors, Mac/Firefox and Mac/Chrome have great difficulties displaying it...

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __Paul__ on __2013-01-15__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1288.
