### ISSUE TITLE
hanging-punctuation would be a nice addition to the list of things available or not!

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1287]
hanging-punctuation would be a nice addition to the list of things available or not!

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+5**
Issue added by **Eamon** on **2014-10-15**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
http://dev.w3.org/csswg/css-text-3/#hanging-punctuation-property

**Comment by pbowyer** [comment]
:+1:

**Comment by joeldrapper** [comment]
:+1:

**Comment by dangodev** [comment]
:+1:

**Comment by jboolean** [comment]
+1

**Comment by lembitk** [comment]
+1

**Comment by gmangesh** [comment]
+1

**Comment by waarissyb** [comment]
+1. There’s now support in Webkit: https://twitter.com/grorgwork/status/705546895528034305

**Comment by ChristophLabacher** [comment]
:+1:

**Comment by chrisburnell** [comment]
+1

**Comment by adactio** [comment]
+1

**Comment by g10** [comment]
👍 cfr. https://developer.apple.com/safari/technology-preview/release-notes/

**Comment by Eltn** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by Bisaloo** [comment]
+1

**Comment by sambaldwin** [comment]
👍

**Comment by proimage** [comment]
+1

**Comment by caesar** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-hanging-punctuation
