### ISSUE TITLE
Add the "cursor" CSS property

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1288]
Add the &quot;cursor&quot; CSS property

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by ____ on __2011-12-19__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Covered by http://caniuse.com/#feat=css3-cursors & http://caniuse.com/#feat=css3-cursors-newer ?

**Comment by Fyrd** [comment]
Yup.
