### ISSUE TITLE
getElementsByName

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1290]
getElementsByName

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+5**
Issue added by **Arthas** on **2012-10-12**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
This is part of DOM Level 2 and works in IE6, Firefox 2, Safari 3 (maybe earlier).
@Fyrd This seems to fail the "Feature is not already widely supported" inclusion criteria.

**Comment by Fyrd** [comment]
@cvrebert It kinda works, but according to http://quirksmode.org/dom/core/#t134 it has some serious bugs in IE 9 and below so that may be worth pointing out.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_document_getelementsbyname
(doesn't have info about bugs in IE9 and below but I think we're past caring about that by now)
