### ISSUE TITLE
The <main> ELEMENT.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1295]
The &lt;main&gt; ELEMENT.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __Andrew Luhring__ on __2013-07-22__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Covered by http://caniuse.com/#feat=html5semantic
