### ISSUE TITLE
dropzone  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1296]
dropzone

http://www.whatwg.org/specs/web-apps/current-work/multipage/dnd.html#the-dropzone-attribute

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __snifty__ on __2012-07-20__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Covered by http://caniuse.com/#feat=dragndrop :
> Currently no browser supports the `dropzone` attribute.

**Comment by Fyrd** [comment]
Yup.
