### ISSUE TITLE
Support for list-style-type

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1297]
Support for list-style-type

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+5**
Issue added by **Matt Flaschen** on **2014-08-06**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Rupurudu** [comment]
+1

**Comment by sabberworm** [comment]
Is this a duplicate of #1354? I’m especially interested in which browser supports having a `<string>` value to define your own counter glyph.

**Comment by someother1** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_properties_list-style-type
