### ISSUE TITLE
PATCH method (rfc5789 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1298]
PATCH method (rfc5789 https://tools.ietf.org/html/rfc5789)

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __toto__ on __2014-04-11__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by shalomb** [comment]
+1

**Comment by cvrebert** [comment]
Duplicate of #1181 ?

**Comment by Fyrd** [comment]
Yup, closing.
