### ISSUE TITLE
document.evaluate

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1299]
document.evaluate

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __qstrahl__ on __2014-08-06__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1558.

**Comment by Fyrd** [comment]
Duplicate of #1145
