### ISSUE TITLE
list-style-image

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1300]
list-style-image

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+5**
Issue added by **ravanson** on **2014-03-18**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by sammbeller** [comment]
+1

**Comment by 304NotModified** [comment]
+1

**Comment by dartess** [comment]
@Fyrd 
Is supported in 2.1  http://caniuse.com/#search=list-style-image
Can, it is necessary to close?

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_properties_list-style-image
