### ISSUE TITLE
XMLHTTPRequest (1)

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1301]
XMLHTTPRequest (1)

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+5**
Issue added by **dforce** on **2013-03-27**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
-1
Level 1 is so widely supported that I don't see the point, and there's already http://caniuse.com/#feat=xhr2

**Comment by Ugoku** [comment]
-1
Makes no sense in 2015

**Comment by dannytech** [comment]
-1
Not useful anymore
