### ISSUE TITLE
It would be helpful to have support for the state of paged media ( @page )

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1302]
It would be helpful to have support for the state of paged media ( @page )

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __Marco__ on __2014-04-04__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1229
