### ISSUE TITLE
WeakMap API  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1303]
WeakMap API

https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/WeakMap

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+5**
Issue added by **ehynds** on **2012-04-15**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
http://kangax.github.io/compat-table/es6/#WeakMap

**Comment by andersonl-selina** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-javascript_builtins_weakmap
