### ISSUE TITLE
Please add insertAdjacentHTML

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1305]
Please add insertAdjacentHTML

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __shcoder.ru__ on __2014-09-07__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1044.
