### ISSUE TITLE
navigator.hardwareConcurrency    Chrome: Native support All other browsers that support Workers: few...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1306]
navigator.hardwareConcurrency

http://wiki.whatwg.org/wiki/Navigator_HW_Concurrency

Chrome: Native support
All other browsers that support Workers: few seconds async timing attack w/polyfill
Native support in Safari coming soon

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+5**
Issue added by **Eli Grey** on **2014-05-15**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by solendil** [comment]
This is a very useful feature for javascript intensive applications like [FractalJS](https://github.com/solendil/FractalJS).
+1

**Comment by kenrussell** [comment]
+1

**Comment by cyrusboadway** [comment]
+1

**Comment by mudcube** [comment]
+1

**Comment by eligrey** [comment]
+1

**Comment by nmrugg** [comment]
+1

**Comment by SergioCrisostomo** [comment]
+1

**Comment by zackee12** [comment]
+1

**Comment by lpd-au** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=hardwareconcurrency
