### ISSUE TITLE
How about overflow-scrolling? iOS Safari needs the webkit vendor prefix for example. Can't find ...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1308]
How about overflow-scrolling? iOS Safari needs the webkit vendor prefix for example. Can&#39;t find it on MDN. See http://www.quirksmode.org/css/css2/overflowscrolling.html.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+6**
Issue added by **Adam** on **2014-09-16**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by yisibl** [comment]
+1

**Comment by yisibl** [comment]
+1

**Comment by wmill** [comment]
+1, it's on MDN https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling

**Comment by Huxpro** [comment]
+1

**Comment by a932455223** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

- Apple doc: <https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariCSSRef/Articles/StandardCSSProperties.html>
- Another ress: <https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/>

**Comment by Tonylvv** [comment]
+1

**Comment by hbrls** [comment]
How can I detect this feature? Will `'WebkitOverflowScrolling' in document.documentElement.style` work?

**Comment by isaacsgraphic** [comment]
+1

**Comment by thybzi** [comment]
+1

**Comment by anyotherway** [comment]
Hi all, almost 2 years later and STILL !? no overflow-scrolling at caniuse.com. Sure thing, Opera's 0.000000001% of market will complain. Elsewhere, check out our viewport grid that depends entirely on overflow-scrolling to work.
[CSS Play ~ Viewport Grid](http://www.cssplay.co.uk/layouts/cssplay-grid-viewport.html)
W3's take.
2012, [Features Overflow-Scrolling](https://www.w3.org/community/coremob/wiki/Features/Overflow_Scrolling_and_Fixed_Positioning)
Current, [Overflow Visual Effect](https://www.w3.org/TR/CSS2/visufx.html#overflow)

Hint-Hint, Nudge-Nudge, kids. Let's do it!

**Comment by kaidin** [comment]
+1

**Comment by mervinva** [comment]
+1

**Comment by Bhagita** [comment]
+1

overflow-scrolling is absolutely needed on apple touch devices, with a prefix. It can severely hamper the user experience should this be omitted.

**Comment by hejiaji** [comment]
It has been 3 years and this is still not in the list?? Any updates on this?

**Comment by VivianWang1993** [comment]
Hello? +1

**Comment by korenb** [comment]
+1

**Comment by TwisterMW** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_properties_-webkit-overflow-scrolling

**Comment by chestnutchen** [comment]
> Now available at https://caniuse.com/#feat=mdn-css_properties_-webkit-overflow-scrolling

Seems that MDN deleted this page https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling. Does anyone know what is going on?

**Comment by wmill** [comment]
It looks like it's considered obsolete due to changes in mobile browser defaults. 

https://github.com/tailwindlabs/tailwindcss.com/issues/483

https://developer.apple.com/documentation/safari-release-notes/safari-13-release-notes
