### ISSUE TITLE
css3 animation-play-state please

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1310]
css3 animation-play-state please

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+5**
Issue added by **Kim SJ** on **2014-03-25**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by nikoloza** [comment]
+1

**Comment by geedix** [comment]
+1

**Comment by geedix** [comment]
+1

**Comment by FennecFoxie** [comment]
+1:

**Comment by re6exp** [comment]
+1

**Comment by sommerset** [comment]
+1

**Comment by hooddanielc** [comment]
+1

**Comment by Schweinepriester** [comment]
+1, at least finding <http://caniuse.com/#feat=css-animation>, as `animation-play-state` is defined in <https://www.w3.org/TR/css3-animations/#animation-play-state-property> as well, if the support matches `animation`.

Links:

- <http://www.w3schools.com/cssref/css3_pr_animation-play-state.asp>
- <https://developer.mozilla.org/de/docs/Web/CSS/animation-play-state>

**Comment by Mmzer** [comment]
+1

**Comment by Hydrock** [comment]
+1

**Comment by DIYgod** [comment]
+1

**Comment by davecarlile** [comment]
+1

**Comment by nikewu** [comment]
+1

**Comment by mirraj2** [comment]
+1

**Comment by Simonwep** [comment]
+1, at least mdn shows the browser support https://developer.mozilla.org/en-US/docs/Web/CSS/animation-play-state Would be awesome to also have it on caniuse! :)

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_properties_animation-play-state
