### ISSUE TITLE
setSelectionRange, selectionStart and selectionEnd

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1311]
setSelectionRange, selectionStart and selectionEnd for `input` & `textarea` elements

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+5**
Issue added by **Akion** on **2013-10-16**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Presumably refers to the properties of https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement

**Comment by soul-wos-vn** [comment]
+1

**Comment by alltouch** [comment]
+1

**Comment by danielhickman** [comment]
+1

**Comment by Fyrd** [comment]
Falls under #1070

**Comment by Fyrd** [comment]
Re-opened. Further investigation shows these are not covered by the Selection Range API and support should be tracked separately.

**Comment by redgvin** [comment]
+1

**Comment by antennaio** [comment]
+1

**Comment by laubsauger** [comment]
+1

**Comment by fabm22** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by paolomoretti** [comment]
+1

**Comment by benoneal** [comment]
+1

**Comment by Calico90** [comment]
+1

**Comment by Spotnyk** [comment]
+1 (please)

**Comment by markwoon** [comment]
+1

**Comment by wendaosanshou** [comment]
+1

**Comment by ribrdb** [comment]
+1

**Comment by meddox** [comment]
+1

**Comment by skeets23** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=input-selection
