### ISSUE TITLE
URL Standard  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1312]
URL Standard

http://url.spec.whatwg.org

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+5**
Issue added by **Christian Wesselhoeft** on **2013-11-01**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
+1

**Comment by renato-zannon** [comment]
+1

**Comment by glen-84** [comment]
+1

**Comment by yukulele** [comment]
+1

**Comment by m4h3** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by kapouer** [comment]
+1

and there is a polyfill available.

**Comment by ghosttie** [comment]
+1

**Comment by manubb** [comment]
+1

**Comment by kapouer** [comment]
Also a quite precise browser compatibility table is available at
https://developer.mozilla.org/en-US/docs/Web/API/URL

**Comment by cvrebert** [comment]
(The `URLSearchParams` subfeature has been added in #2787.)

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=url
