### ISSUE TITLE
break-inside for columns.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1317]
break-inside for columns.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+5**
Issue added by **rdoyle** on **2014-10-29**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by m-artin** [comment]
+1

**Comment by ndorfin** [comment]
Not sure, but it looks like this is covered by http://caniuse.com/#feat=css-page-break ?

**Comment by shrpne** [comment]
+1

**Comment by shrpne** [comment]
@Fyrd `break-inside`, `break-after` and `break-before` are generic properties to control break rules for columns, pages, and regions.
So I think http://caniuse.com/#feat=css-page-break should be reworked and became a part of `break-` properties

**Comment by rachelandrew** [comment]
I think the break-* data is also incorrect. Chrome appears to support `break-before` and `break-after`. It's pretty confusing lumping the old `page-break-*` with the new ones. It would be useful for people to be able to see exactly what combination of these things will work for them.

**Comment by Fyrd** [comment]
break-inside for multi-column is now available at https://caniuse.com/#feat=mdn-css_properties_break-inside_multicol_context
