### ISSUE TITLE
`onPaste`, like:  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1320]
`onPaste`, like:
http://msdn.microsoft.com/en-us/library/ie/ms536955.aspx
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement.onpaste

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __Shahar Or__ on __2014-09-15__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Fyrd** [comment]
Part of http://caniuse.com/#feat=clipboard

**Comment by ilizunov** [comment]
@Fyrd but what about search suggestions?
`onPaste` and `onCopy` are normal keywords, but **Clipboard** feature couldn't be found with these keywords.
