### ISSUE TITLE
maxlength for textarea

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1321]
maxlength for textarea

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __Dael__ on __2012-02-24__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1106.

**Comment by cvrebert** [comment]
@Fyrd This can be closed as a duplicate.
