### ISSUE TITLE
registerContentHandler(), registerProtocolHandler(), and friends

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1323]
registerContentHandler(), registerProtocolHandler(), and friends: http://whatwg.org/html#custom-handlers

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+5**
Issue added by **Hixie** on **2014-01-26**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Part of http://caniuse.com/#feat=registerprotocolhandler , although `registerContentHandler` isn't currently mentioned

**Comment by Fyrd** [comment]
Looks like registerContentHandler has an entry at https://caniuse.com/#feat=mdn-api_navigator_registercontenthandler which is incomplete, but since it's an obsolete/deprecated feature I think that's fine.
