### ISSUE TITLE
events of DOM such as DOMNodeInserted,DOMNodeRemoved needs to be added in caniuse.com

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1324]
events of DOM such as DOMNodeInserted,DOMNodeRemoved needs to be added in caniuse.com

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __asp__ on __2015-03-04__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1074.
