### ISSUE TITLE
HTML5 Link Prefetching:  Link prefetching is a browser mechanism, which utilizes browser idle time t...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1326]
HTML5 Link Prefetching:

Link prefetching is a browser mechanism, which utilizes browser idle time to download or prefetch documents that the user might visit in the near future.

https://developer.mozilla.org/en/link_prefetching_faq

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __roberkules__ on __2012-06-12__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Fyrd** [comment]
Duplicate of #981 so moving half the votes there

**Comment by kimslawson** [comment]
+1
