### ISSUE TITLE
empty-cells (

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1328]
empty-cells (http://www.w3schools.com/cssref/pr_tab_empty-cells.asp)

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+5**
Issue added by **wilk** on **2014-05-14**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/empty-cells#Browser_compatibility

**Comment by ashikjs** [comment]
`empty-cells` Browser  Supported

[Source Link ](https://css-tricks.com/almanac/properties/e/empty-cells/)

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_properties_empty-cells
