### ISSUE TITLE
Push API (

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1329]
Push API (https://w3c.github.io/push-api/).

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __Owen Campbell-Moore__ on __2015-02-11__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by hitautodestruct** [comment]
+1

**Comment by jpmedley** [comment]
+1

**Comment by jimmywarting** [comment]
+1

**Comment by M2Ys4U** [comment]
+1

**Comment by NOtherDev** [comment]
+1

**Comment by autonome** [comment]
+1

**Comment by digitarald** [comment]
+1

**Comment by wfwalker** [comment]
+1

**Comment by marco-c** [comment]
+1

**Comment by thomsta** [comment]
+1

**Comment by janruehling** [comment]
+1

**Comment by kitcambridge** [comment]
+1

**Comment by collimarco** [comment]
+1

**Comment by awebdeveloper** [comment]
+1

**Comment by jaisanth** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=push-api

**Comment by awebdeveloper** [comment]
Safari supports push notifications

https://developer.apple.com/notifications/safari-push-notifications/

**Comment by marco-c** [comment]
> Safari supports push notifications

This is not the Push API but some proprietary API.

**Comment by jimmywarting** [comment]
Think it's worth mentioning safari push in the `notes tab` even if it dosen't deserve to be in caniuse

something like
[3] Although, Safari supports push notification, it's still not the same thing as w3c specification, and it don't require browser to be running
