### ISSUE TITLE
window.crypto.getRandomBytes

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1331]
window.crypto.getRandomBytes

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+5__
Issue added by __Nilos__ on __2012-06-02__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
My speculation is that this was replaced by https://developer.mozilla.org/en-US/docs/Web/API/RandomSource/getRandomValues , which falls under http://caniuse.com/#feat=cryptography

**Comment by Fyrd** [comment]
Yeah, agreed.
