### ISSUE TITLE
CSS "visibility" (hidden/visible/etc)

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1333]
CSS &quot;visibility&quot; (hidden/visible/etc)

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+5**
Issue added by **Dan S** on **2014-05-05**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
-1

**Comment by yisibl** [comment]
-1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_properties_visibility
