### ISSUE TITLE
please add dialog tag (new tag in chrome 25)

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1339]
please add dialog tag (new tag in chrome 25)

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Ali.MD__ on __2013-08-16__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
+1

**Comment by cvrebert** [comment]
Already covered: http://caniuse.com/#feat=dialog
