### ISSUE TITLE
position: initial; - 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1342]
position: initial; - https://developer.mozilla.org/en-US/docs/Web/CSS/initial

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __csscallum__ on __2014-02-14__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1016.
