### ISSUE TITLE
Add current browser support for HTML5 tag "hgroup" (

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1346]
Add current browser support for HTML5 tag &quot;hgroup&quot; (http://www.w3.org/TR/html-markup/hgroup.html)

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **Andrrrrr** on **2014-12-17**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Ugoku** [comment]
-1
hgroup has been [removed from the spec](http://html5doctor.com/the-hgroup-element/)

**Comment by Fyrd** [comment]
Included at http://caniuse.com/#search=hgroup as an obsolete tag
