### ISSUE TITLE
Version Compatibilities of different javascript frameworks like angular.js

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1348]
Version Compatibilities of different javascript frameworks like angular.js

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __eldos__ on __2014-08-16__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
This sounds out of scope for caniuse.
