### ISSUE TITLE
ES6 rest parameters 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1349]
ES6 rest parameters http://wiki.ecmascript.org/doku.php?id=harmony:rest_parameters

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Jonas Sicking__ on __2013-03-11__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
http://kangax.github.io/compat-table/es6/#rest_parameters

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=rest-parameters
