### ISSUE TITLE
Directory upload:  <input type="file" directory mozdirectory webkitdirectory>

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1350]
Directory upload:

&lt;input type=&quot;file&quot; directory mozdirectory webkitdirectory&gt;

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **Blixt** on **2014-02-10**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by yisibl** [comment]
+1

**Comment by PhilipDavis** [comment]
+1

**Comment by dstorey** [comment]
https://dev.modern.ie/platform/status/webkitdirectoryandwebkitrelativepath

**Comment by matthewstokeley** [comment]
+1

**Comment by kirillsalykin** [comment]
+1

**Comment by digitalreb** [comment]
+1

**Comment by KaPaHgaIII** [comment]
+1

**Comment by 304NotModified** [comment]
+1

**Comment by TooTallNate** [comment]
+1

**Comment by poligarcia** [comment]
+1

**Comment by tolstenko** [comment]
+1

**Comment by ardean** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

https://developer.mozilla.org/de/Firefox/Releases/50#Changes_for_Web_developers

> For compatibility purposes, the non-standard `webkitdirectory` attribute of the <input> element, as well as the property `HTMLInputElement.webkitDirectory` property, have been implemented

**Comment by konnichimade** [comment]
+1

**Comment by zevero** [comment]
+1

**Comment by SteveGZr** [comment]
+1

**Comment by ChenxiangKasscloud** [comment]
+1

**Comment by zian974** [comment]
+1

**Comment by linghao2014** [comment]
+1

**Comment by Llbe** [comment]
+1

**Comment by anonyco** [comment]
+1

**Comment by RoelRoel** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=input-file-directory
