### ISSUE TITLE
CSS3 marquee features such as:  overflow-y: marquee-line/marquee-block, marquee-style, scroll, marqu...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1352]
CSS3 marquee features such as:
overflow-y: marquee-line/marquee-block, marquee-style, scroll, marquee-play-count, marquee-direction, marquee-speed

At the time, only Chrome seems to have decent support.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Firefall__ on __2013-03-25__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1499.
