### ISSUE TITLE
list-style-type 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1354]
list-style-type http://www.w3schools.com/cssref/pr_list-style-type.asp

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **Bruce Sauls** on **2011-12-16**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by yisibl** [comment]
+1

**Comment by nextlevelshit** [comment]
+1

**Comment by gorn** [comment]
+1

**Comment by Rupurudu** [comment]
+1

**Comment by Spreadyy** [comment]
+1

**Comment by lx4r** [comment]
+1

**Comment by salarmehr** [comment]
https://stackoverflow.com/a/17828274/752603

**Comment by someother1** [comment]
+1

**Comment by theSdev** [comment]
+1

**Comment by maple3142** [comment]
+1

**Comment by denilsonsa** [comment]
Chrome bug: https://crbug.com/687946
Available in Firefox since version 39: https://www.mozilla.org/en-US/firefox/39.0/releasenotes/
MDN compatibility table: https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type#Browser_compatibility

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-css_properties_list-style-type (see sub-features for details)
