### ISSUE TITLE
HTML5 Events Like onoffline, onpopstate, etc.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1355]
HTML5 Events
Like onoffline, onpopstate, etc.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **danny** on **2011-12-28**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by midasdas** [comment]
+1

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-html_elements_body_onoffline & https://caniuse.com/#feat=mdn-html_elements_body_onpopstate
