### ISSUE TITLE
Hi guys!  Please add the animation-delay CSS property.  Thanks in advance, Kenny

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1357]
Hi guys!

Please add the animation-delay CSS property.

Thanks in advance,
Kenny

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Kenny__ on __2013-07-15__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Presumably covered by http://caniuse.com/#feat=css-animation
