### ISSUE TITLE
SVG Foreign Object is a way to combine different XML namespaces elements into the SVG. 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1359]
SVG Foreign Object is a way to combine different XML namespaces elements into the SVG. https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **Jaroslav Bauml** on **2014-11-06**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by au-phiware** [comment]
:+1:

**Comment by brianrichins** [comment]
+1, fighting SVG differences across mobile browsers and Foreign Object apparently isn't supported at all on some of them :(

**Comment by strarsis** [comment]
Yes, foreignObject is extremely useful for applying SVG based effects on normal HTML. 
Can a test be written for this (modernizr style) for testing this automatically in many browsers?

**Comment by GPHemsley** [comment]
Looks like this is now covered by MDN data:
https://caniuse.com/mdn-svg_elements_foreignobject

(via mdn/browser-compat-data#1529)
