### ISSUE TITLE
I would like to know which browsers support the forceSpellCheck() method (

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1360]
I would like to know which browsers support the forceSpellCheck() method (https://html.spec.whatwg.org/multipage/interaction.html#dom-forcespellcheck)

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **David** on **2014-11-18**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by JBoman32768** [comment]
+1 ... it doesn't seem to be present in IE11 :(

**Comment by Schweinepriester** [comment]
+1

**Comment by sspi** [comment]
+1

**Comment by Schweinepriester** [comment]
Available via MDN: <https://caniuse.com/mdn-api_htmlelement_forcespellcheck>
