### ISSUE TITLE
extend-to-zoom

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1361]
extend-to-zoom

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **garpur** on **2014-05-23**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
This would fall under http://caniuse.com/#feat=css-deviceadaptation , although it's not currently specifically mentioned.

**Comment by Fyrd** [comment]
Added in description of https://caniuse.com/css-deviceadaptation
