### ISSUE TITLE
I'd like to see support for "text-outline". This is the w3c proposal, but meanwhile we...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1362]
I&#39;d like to see support for &quot;text-outline&quot;. This is the w3c proposal, but meanwhile webkit supports it as &quot;text-stroke&quot;, I think, but I haven&#39;t checked it by myself.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __warrenJ__ on __2012-10-04__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Covered by http://caniuse.com/#feat=text-stroke
