### ISSUE TITLE
ES6, aka ECMAScript 2015

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1363]
ES6 Features - https://developer.mozilla.org/en-US/docs/JavaScript/ECMAScript_6_support_in_Mozilla

There&#39;s a whole bunch of upcoming ES6 features, some of which already implemented, some yet. Would be good if caniuse documented these.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __balupton__ on __2013-03-26__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by niyazpk** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by pcolombo** [comment]
+1 Standard was approved 6/17 - http://www.ecma-international.org/ecma-262/6.0/

**Comment by Schweinepriester** [comment]
A good resource: https://kangax.github.io/compat-table/es6/

**Comment by gcacars** [comment]
+1

**Comment by nightpool** [comment]
+1

**Comment by Fyrd** [comment]
Duplicate of #492. Currently no plans of including all of ES6 wholesale (as the kangax tables already do that) but the more popular features may be added one by one.

**Comment by jkohlin** [comment]
+1
