### ISSUE TITLE
Please add CSS display: run-in support tables 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1369]
Please add CSS display: run-in support tables
http://css-tricks.com/run-in/

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+6**
Issue added by **Dmitry Pashkevich** on **2012-02-25**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by codeofsumit** [comment]
+1

**Comment by emilchristensen** [comment]
+1

**Comment by wqse** [comment]
+1

**Comment by Lapuh1st** [comment]
+1

**Comment by okdewit** [comment]
+1

**Comment by sultangaleev** [comment]
+1

**Comment by novascreen** [comment]
+1

**Comment by fabmlk** [comment]
+1

**Comment by rctneil** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=run-in
