### ISSUE TITLE
http://caniuse.com/input-typecolor should show browser support for input color tags, but shows 404 i...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1370]
http://caniuse.com/input-typecolor should show browser support for input color tags, but shows 404 instead.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Nick__ on __2012-01-23__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Already covered by http://caniuse.com/#feat=input-color
