### ISSUE TITLE
Which browsers support colgroup completely?

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1371]
Which browsers support colgroup completely?

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **Krunal** on **2011-08-29**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by aneves** [comment]
+1

**Comment by galechus** [comment]
+1

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-html_elements_colgroup
