### ISSUE TITLE
getComputedStyle

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1372]
getComputedStyle

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __CasualSuperman__ on __2011-12-04__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Already covered: http://caniuse.com/#feat=getcomputedstyle
