### ISSUE TITLE
Outline Outline-offset Outline-radius etc.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1373]
Outline
Outline-offset
Outline-radius
etc.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **Nick C** on **2011-12-01**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by awidgery** [comment]
+1

**Comment by JoachimTillessen** [comment]
+1

**Comment by joshgarciadesign** [comment]
+1

**Comment by FlixFlix** [comment]
+1

**Comment by djravine** [comment]
+1

**Comment by ChandlerVer5** [comment]
+1

**Comment by eccentricdz** [comment]
+1

**Comment by rafr3** [comment]
+1 
outline-offset works fine in Firefox, but not in MS Edge

**Comment by PeterBowater** [comment]
+1

**Comment by caraheacock** [comment]
+1

**Comment by jveens** [comment]
+1

**Comment by sergey-kozlov** [comment]
+1

**Comment by txji** [comment]
+1

**Comment by sergey-kozlov** [comment]
+1 again

**Comment by Schweinepriester** [comment]
+1

From <https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/desktop/14915/>:

> Partial implementation of CSS outline-offset

**Comment by thomascampbelladams** [comment]
+1

Definitely needs these properties in there, especially since it seems like outline-offset still has spotty support (apparently IE and Edge still don't support it???)

**Comment by marulango** [comment]
+1

**Comment by erikiva** [comment]
+1

**Comment by Fyrd** [comment]
The `outline` support table has now been updated with included support for `outline-offset`:
https://caniuse.com/#feat=outline

`outline-radius` is unofficial and is only supported by Firefox, now mentioned in the Notes section.
