### ISSUE TITLE
Unless I'm being thick, I cannot seem to find references to either of these CSS values in canius...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1379]
Unless I&#39;m being thick, I cannot seem to find references to either of these CSS values in caniuse:
https://developer.mozilla.org/en-US/docs/Web/CSS/initial
https://developer.mozilla.org/en-US/docs/Web/CSS/inherit

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Joey Hoer__ on __2014-02-11__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1016.

**Comment by Schweinepriester** [comment]
`inherit` seems to be still missing?

It is well supported though, therefore not that high priority...

<https://developer.mozilla.org/de/docs/Web/CSS/inherit>
