### ISSUE TITLE
device motion and DeviceMotionEvent as covered in  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1385]
device motion and DeviceMotionEvent as covered in 
http://www.html5rocks.com/en/tutorials/device/orientation/

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Dennis S__ on __2012-09-12__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Covered by http://caniuse.com/#feat=deviceorientation

**Comment by Fyrd** [comment]
Yup.
