### ISSUE TITLE
windows phone HTML5/svg support.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1387]
windows phone HTML5/svg support.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **wonderwhit** on **2012-03-08**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
@Fyrd This seems too general, and caniuse already has IE Mobile data.
