### ISSUE TITLE
Can you add a feature to the website itself to "Send me an email when this feature is supported...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1390]
Can you add a feature to the website itself to &quot;Send me an email when this feature is supported in all browsers (or browsers x, y, z)&quot;?

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Technical__ on __2013-01-09__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #869?

**Comment by Fyrd** [comment]
Yeah, seems like. Thanks.
