### ISSUE TITLE
saveAs does not seem to be on the site (or else, I'm just incapable of finding it). It would be ...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1393]
saveAs does not seem to be on the site (or else, I&#39;m just incapable of finding it). It would be handy to have here!

Thanks,
Chris

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+8**
Issue added by ____ on **2014-02-24**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
This seems to be referring to the defunct "File API: Writer" spec: http://www.w3.org/TR/2012/WD-file-writer-api-20120417/

**Comment by chrisarmstrong** [comment]
+1

**Comment by Fyrd** [comment]
Seems old, deprecated and probably not supported anymore, so closing.
