### ISSUE TITLE
localeCompare  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1394]
localeCompare

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **gaten** on **2014-03-31**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by eperret** [comment]
+1

**Comment by goligo** [comment]
+1

**Comment by goozo** [comment]
+1

**Comment by galenyuan** [comment]
+1

**Comment by Moykn** [comment]
+1

**Comment by Etoma** [comment]
+1

**Comment by Loliner** [comment]
+1

**Comment by Moykn** [comment]
+1

**Comment by KKrisu** [comment]
+1

**Comment by marcosgallardo** [comment]
+1

**Comment by Download** [comment]
+1

**Comment by gotdibbs** [comment]
+1

**Comment by luckylooke** [comment]
+1

**Comment by wemyss** [comment]
+1

**Comment by leem32** [comment]
+1

**Comment by barbalex** [comment]
+1

**Comment by korelstar** [comment]
+1

**Comment by nigelnt** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=localecompare
