### ISSUE TITLE
Browser support for crossorigin attribute on img/video (as described in  ) would be useful

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1396]
Browser support for crossorigin attribute on img/video (as described in https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes ) would be useful

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+5**
Issue added by **Fred** on **2014-08-14**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cedarwu** [comment]
+1 also support for crossorigin of script

**Comment by Lynn-cc** [comment]
+1 also support for crossorigin of script

**Comment by KKrisu** [comment]
+1 also support for crossorigin of script

**Comment by digitalreb** [comment]
+1

**Comment by cvsml** [comment]
+1
This configuration is very obscure and exposing it can help a lot of people.
The mozilla page OP attached even contains support versions saving you guys some work ;)

**Comment by thoragio** [comment]
+1

**Comment by tcsthyc** [comment]
+1

**Comment by liuzirui1122** [comment]
+1

**Comment by lwdgit** [comment]
+1

**Comment by Calico90** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_htmlmediaelement_crossorigin & https://caniuse.com/#feat=mdn-api_htmlimageelement_crossorigin
