### ISSUE TITLE
The mouseenter and mouseleave events

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1398]
The mouseenter and mouseleave events

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **mmj** on **2014-10-14**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by temberature** [comment]
+1

**Comment by betabong** [comment]
+1

**Comment by jeerbl** [comment]
+1

**Comment by SuperPat45** [comment]
+1

**Comment by jordankaiser** [comment]
+1

**Comment by jacketwpbb** [comment]
+1

**Comment by YanXiaoBai** [comment]
+1

**Comment by tcr** [comment]
+1

**Comment by richja** [comment]
+1

**Comment by 304NotModified** [comment]
+1

**Comment by Nathan8489** [comment]
+1

**Comment by PeakFish** [comment]
also onmouseover and onmouseout

**Comment by hwaphon** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_element_mouseenter_event & https://caniuse.com/#feat=mdn-api_element_mouseleave_event
