### ISSUE TITLE
image-rect isn't supported by anybody but Mozilla as far as I can tell, but I'd love it to b...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1399]
image-rect isn&#39;t supported by anybody but Mozilla as far as I can tell, but I&#39;d love it to be more widely available. caniuse can provide pressure to do that. :)

https://developer.mozilla.org/en-US/docs/CSS/-moz-image-rect

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **Nathan Hammond** on **2013-01-16**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by gfox1984** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_properties_background-image_image-rect
