### ISSUE TITLE
I suggest you to put browser acceptance of the javascript property clientHeight

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1400]
I suggest you to put browser acceptance of the javascript property clientHeight

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **Jp** on **2014-02-20**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
-1
Use getBoundingClientRect() instead. [It's supported all the way back to IE6.](http://caniuse.com/#feat=getboundingclientrect)

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_element_clientheight
