### ISSUE TITLE
"border-corner-shape"   

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1401]
&quot;border-corner-shape&quot;

http://dev.w3.org/csswg/css-backgrounds-4/#corner-shaping
http://leaverou.github.io/corner-shape/

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **zasdasda** on **2014-04-08**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Schweinepriester** [comment]
@Fyrd:

#1477 and this one request the same.
As there are more votes on #1477, close this one as duplicate (and maybe slightly rename the other)?

**Comment by odahcam** [comment]
+1

**Comment by Fyrd** [comment]
Yup, duplicate of #1477
