### ISSUE TITLE
Pointer Lock API

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1404]
Pointer Lock API

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Adam__ on __2014-09-08__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by HolgerJeromin** [comment]
same as #983

**Comment by Fyrd** [comment]
Duplicate of #983 so adding half the votes there
