### ISSUE TITLE
scroll-behavior

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1406]
scroll-behavior

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Janek__ on __2014-12-16__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by nikkyandrei** [comment]
+1

**Comment by youngroger** [comment]
+1

**Comment by shavounet** [comment]
+1

**Comment by zgreen** [comment]
+1

**Comment by joeybaker** [comment]
+1

**Comment by fxedel** [comment]
+1

**Comment by Swatinem** [comment]
+1

**Comment by danez** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-scroll-behavior Thanks @danez !
