### ISSUE TITLE
CSS element() (part of CSS image level 4). That should be included since the site includes CSS Canva...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1407]
CSS element() (part of CSS image level 4).
That should be included since the site includes CSS Canvas Drawings which isn&#39;t even official (while CSS element() is).

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __ntim__ on __2015-02-24__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by yisibl** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-element-function
