### ISSUE TITLE
caniuse.com/#feat=clipboardevent should redirect to caniuse.com/#feat=clipboard

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1409]
caniuse.com/#feat=clipboardevent should redirect to caniuse.com/#feat=clipboard

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __dotnetCarpenter__ on __2015-03-03__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
@Fyrd This is more of a simple alias.

**Comment by Fyrd** [comment]
Yeah, have added it to keywords.
