### ISSUE TITLE
Add support for CSS's @import

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1411]
Add support for CSS&#39;s @import

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **The Suspect** on **2015-01-04**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by jonnyarnold** [comment]
+1

**Comment by TheFirstLairron** [comment]
+1

**Comment by Calico90** [comment]
+1

**Comment by bimmermeow** [comment]
+1

**Comment by Darker** [comment]
+1

**Comment by zhenialeks** [comment]
+1

**Comment by unitof** [comment]
I'll see if I can figure out what's needed to do this. Support seems pretty [universal](https://developer.mozilla.org/en-US/docs/Web/CSS/@import) now, but that's what I just tried going to CIU to confirm and couldn't.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_at-rules_import
