### ISSUE TITLE
HttpOnly flag for cookies, what browsers support? it would be nice to have that in the caniuse.com  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1415]
HttpOnly flag for cookies, what browsers support? it would be nice to have that in the caniuse.com
https://www.owasp.org/index.php/HTTPOnly

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **velu** on **2014-06-20**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by georgeu2000** [comment]
Seems like a great way to protect cookies. 

+1

**Comment by Calico90** [comment]
+1

**Comment by Calico90** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Secure_and_HttpOnly_cookies

**Comment by Calico90** [comment]
As stated by @Fyrd on the site https://www.owasp.org/index.php/HttpOnly is already a table with the supporting browsers table. Can it be added to caniuse?

**Comment by l0s** [comment]
+1

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-http_headers_set-cookie_httponly
