### ISSUE TITLE
Interesting stuff here: 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1417]
Interesting stuff here:
https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __vince357__ on __2014-09-26__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1281.
