### ISSUE TITLE
lastModified HTML5 DOM property

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1418]
lastModified HTML5 DOM property

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **Ben** on **2013-08-24**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
The `currentScript` part duplicates #1099.

**Comment by Fyrd** [comment]
Okay, removed currentScript from title & description

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_document_lastmodified
