### ISSUE TITLE
I second the request for text-transform. Thanks for your hard work!

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1422]
I second the request for text-transform. Thanks for your hard work!

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Jess__ on __2015-03-12__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1009.
