### ISSUE TITLE
Please add "imageSmoothingEnabled".  Chrome supports it unprefixed. IE11, Firefox, and Saf...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1423]
Please add &quot;imageSmoothingEnabled&quot;.

Chrome supports it unprefixed. IE11, Firefox, and Safari support it with a vendor prefix.

I&#39;m curious when it was first supported by these browsers.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **John Tantalo** on **2014-02-12**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
i.e. https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled
Related to http://caniuse.com/#feat=canvas

**Comment by tps12** [comment]
+1

**Comment by tripu** [comment]
Also, [`imageSmoothingQuality`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingQuality)

**Comment by jcaillot** [comment]
For Safari, support started with 10+
https://developer.apple.com/documentation/webkitjs/canvasrenderingcontext2d

**Comment by lpd-au** [comment]
+1

@Fyrd I was under the impression reactions counted as upvotes now, but this issue has only 6 votes on the feature list...

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_canvasrenderingcontext2d_imagesmoothingenabled
