### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator Intl api

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1424]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator
Intl api

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __mplungjan__ on __2013-08-08__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Refs #1022

**Comment by Fyrd** [comment]
Available at http://caniuse.com/#feat=internationalization
