### ISSUE TITLE
playbackRate in video

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1430]
playbackRate in video

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **Chris C** on **2012-10-24**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by JoernBerkefeld** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_htmlmediaelement_playbackrate
