### ISSUE TITLE
It would be interesting to include an overview of implementation of Web Crypto API:    It is being a...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1432]
It would be interesting to include an overview of implementation of Web Crypto API: 
http://www.w3.org/TR/WebCryptoAPI/

It is being actively implemented in all major browsers:
http://www.chromestatus.com/features/5030265697075200

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __StefanB__ on __2014-01-08__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Covered by http://caniuse.com/#feat=cryptography
