### ISSUE TITLE
css3 order property:   

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1434]
css3 order property: 
http://www.w3.org/TR/css3-flexbox/#order-property, https://developer.mozilla.org/en-US/docs/Web/CSS/order

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Waldir__ on __2014-05-14__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by ChristianSiegert** [comment]
+1

**Comment by cvrebert** [comment]
Part of http://caniuse.com/#feat=flexbox , although not currently explicitly mentioned there.

**Comment by Fyrd** [comment]
Mentioned there now.
