### ISSUE TITLE
W3 Vibration API, as seen in mobile Firefox.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1435]
W3 Vibration API, as seen in mobile Firefox.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Rei-chan__ on __2012-05-23__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by HolgerJeromin** [comment]
this is released: http://caniuse.com/#search=vibration
