### ISSUE TITLE
I couldn't find a compatibility table for animation-fill-mode.   Currently needs browser prefixe...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1436]
I couldn&#39;t find a compatibility table for animation-fill-mode. 

Currently needs browser prefixes such as -webkit, -moz and -o. 

The MDN has support info... https://developer.mozilla.org/en-US/docs/Web/CSS/animation-fill-mode

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **Andrew** on **2014-02-23**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cgddrd** [comment]
This would be really useful on CanIUse. +1

**Comment by shameeryou** [comment]
+1

**Comment by thepatrik** [comment]
+1

**Comment by lazarljubenovic** [comment]
+1

**Comment by AllanStepps** [comment]
+1

**Comment by idlethumbs** [comment]
+1

**Comment by andresmoritan** [comment]
+1

**Comment by MiMaMuh** [comment]
+1

**Comment by benique** [comment]
+1

**Comment by fonzie42** [comment]
+1

**Comment by lazarljubenovic** [comment]
There's a thumbs up feature now. Please use it instead of pinging everyone.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_properties_animation-fill-mode
