### ISSUE TITLE
display: run-in (

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1437]
display: run-in (http://css-tricks.com/almanac/properties/d/display#run-in)

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by ____ on __2014-03-01__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1369.
