### ISSUE TITLE
asm.js 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1438]
asm.js http://asmjs.org/

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Marv__ on __2014-08-22__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by finom** [comment]
+1

**Comment by acmertz** [comment]
+1

**Comment by TerrorJack** [comment]
+1

**Comment by xtian** [comment]
+1

**Comment by kanaka** [comment]
+1 especially since it is now enabled by default in MS Edge: https://dev.modern.ie/platform/changelog/10532-pc/

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=asmjs
