### ISSUE TITLE
Why don't we add quotes property? 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1439]
Why don&#39;t we add quotes property?
http://www.w3schools.com/cssref/pr_gen_quotes.asp

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **nrvnm** on **2014-10-01**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by profstein** [comment]
+1 this would be nice to know if it's supported. See this article and subsequent comments for more info on how people are using it and the issues with different languages https://css-tricks.com/almanac/properties/q/quotes/

**Comment by BenjaminHoegh** [comment]
2018 And we still missing quotes! what just happened here?

**Comment by jivanpal** [comment]
12 months later and no data 😢 [MDN has compatibility data](https://developer.mozilla.org/en-US/docs/Web/CSS/quotes#Browser_Compatibility), for reference.

**Comment by jivanpal** [comment]
Similarly, data for HTML <q> tag support should be added; this is not present in e.g. [the HTML5 semantic tag list](https://caniuse.com/#feat=html5semantic).

**Comment by xixianykus** [comment]
Agree CSS quotes would be very useful if covered. It's from CSS2.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_properties_quotes
