### ISSUE TITLE
column-span and other column-* proprieties of CSS3 Multi-column layout module

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1440]
column-span and other column-\* proprieties of CSS3 Multi-column layout module

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+4**
Issue added by **m.** on **2012-07-09**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by CapitanRedBeard** [comment]
+1

**Comment by TheFlighteur** [comment]
+1

**Comment by pveeckhout** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_properties_column-span etc
