### ISSUE TITLE
text-align:justify

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1441]
text-align:justify

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Lane Zhao__ on __2014-09-03__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by yisibl** [comment]
+1

**Comment by defims** [comment]
+1

**Comment by Fyrd** [comment]
Part of http://caniuse.com/#search=text-align so closing this issue.
