### ISSUE TITLE
Add the new <main> tag (

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1442]
Add the new &lt;main&gt; tag (http://www.w3.org/TR/2012/WD-html-main-element-20121217/)

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+4__
Issue added by __Matheus Araujo__ on __2013-03-14__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by yisibl** [comment]
+1

**Comment by Ugoku** [comment]
-1
This is already included as subitem of [New semantic elements](http://caniuse.com/#feat=html5semantic), there's no need for a separate feature.

**Comment by Fyrd** [comment]
Yup, already included as @Ugoku mentioned.
