### ISSUE TITLE
We need a way to know if browsers that support feature A also support feature B.  This would help ch...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1445]
We need a way to know if browsers that support feature A also support feature B.

This would help choosing a selector to filter out browsers that can&#39;t use a layout property, for instance, or provide an appropriate fallback value when needed.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+3**
Issue added by **Goulven** on **2012-12-23**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
This needs the "Site functionality" label.

**Comment by Fyrd** [comment]
Done.

**Comment by Fyrd** [comment]
This is basically the same as #2318, so closing as duplicate.
