### ISSUE TITLE
column-break-after  atm only via: -webkit-column-break-after

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1446]
column-break-after

atm only via: -webkit-column-break-after

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+3**
Issue added by **gar_onn** on **2012-07-22**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Chris-May** [comment]
Looks like Webkit and Chrome have added a few prefixed items to columns:
-webkit-column-break-before
-webkit-column-break-inside
-webkit-column-break-after

**Comment by Chris-May** [comment]
I've found more background on my previous comment. From [this MDN article](https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-before), it seems `page-break-before` is migrating to `break-before`, which is supposed to be more generic for use in column and region breaks.

`break-before` is [currently not supported anywhere](https://developer.mozilla.org/en-US/docs/Web/CSS/break-beforeBrowser_compatibility), but as the footnote marks:
>WebKit and Blink browsers don't support this property, but some have the non-standard -webkit-column-break-before and -webkit-region-break-before with similar parameters as page-break-before.
 
It seems `break-before` is listed in specifications that are either in Working Draft or Candidate Recommendation statuses.

**Comment by GPHemsley** [comment]
Looks like this is now covered by MDN data, with a lot more nuance given the more recent specs:
https://caniuse.com/mdn-css_properties_break-after_paged_context
https://caniuse.com/mdn-css_properties_break-after_multicol_context
https://caniuse.com/mdn-css_properties_break-after_multicol_context_always
https://caniuse.com/mdn-css_properties_break-after_multicol_context_column
https://caniuse.com/mdn-css_properties_break-after_multicol_context_avoid-column
etc.

(via mdn/browser-compat-data#700, mdn/browser-compat-data#3330)
