### ISSUE TITLE
target-new

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1447]
target-new

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+3**
Issue added by **Scott Smith** on **2013-01-05**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
This appears to refer to http://www.w3.org/TR/2004/WD-css3-hyperlinks-20040224/#the-target-new
The latest version has been nuked and states:
> *This specification has been discontinued. At this point no further work is planned.*

**Comment by cvrebert** [comment]
@Fyrd Close since nobody seems to have ever implemented this?

**Comment by cgwrench** [comment]
This appears to be a duplicate of #1410. Looks like both issues could be closed.
