### ISSUE TITLE
Date.now() 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1451]
Date.now()
http://kangax.github.io/es5-compat-table/#Date.now

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __Aaron__ on __2014-03-16__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1118.
