### ISSUE TITLE
fieldset disabled attribute  I was hoping a wide support but looks like it only works in Chrome and ...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1452]
fieldset disabled attribute

I was hoping a wide support but looks like it only works in Chrome and FF.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __Stefano__ on __2014-05-09__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
+1
