### ISSUE TITLE
zoom  Originally IE only, not recommended to use elsewhere (it's better to use CSS Transforms). ...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1453]
zoom

Originally IE only, not recommended to use elsewhere (it&#39;s better to use CSS Transforms). Still would be nice to list.

Sources:
http://msdn.microsoft.com/en-us/library/ie/ms531189(v=vs.85).aspx
http://css-tricks.com/almanac/properties/z/zoom/

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __diggie__ on __2014-04-20__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by pkuczynski** [comment]
I am working on it...

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-zoom
