### ISSUE TITLE
 -webkit-overflow-scrolling: touch

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1454]
-webkit-overflow-scrolling: touch

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __JFlo__ on __2013-03-07__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1308.
