### ISSUE TITLE
Add table-layout support, whether browers:  - implement the 'fixed' layout properly, evenly ...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1457]
Add table-layout support, whether browers:
- implement the &#39;fixed&#39; layout properly, evenly distributing space between columns with width: auto;
- support fixed layout tables when the tables have width: auto (spec says UAs MAY support this)

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+3**
Issue added by **markrian** on **2014-02-07**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by tbrisker** [comment]
+1

**Comment by srycroft** [comment]
+1

**Comment by trumbitta** [comment]
+1

**Comment by Fyrd** [comment]
table-layout is available at https://caniuse.com/mdn-css_properties_table-layout

I think considering CSS flexbox and grid are better layout options these days it's not worth tracking more specific behavior as asked for originally in this ticket.
