### ISSUE TITLE
The `ch` width unit; support can be tested via:  ```js function supportsCh () { 	var dummy = documen...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1459]
The `ch` width unit; support can be tested via:

```js
function supportsCh () {
	var dummy = document.createElement(&#39;_&#39;);
	dummy.style.width = &#39;1ch&#39;;
	return !!dummy.style.width;
}
```

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __Forbes Lindesay__ on __2013-08-08__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1101.
