### ISSUE TITLE
the CSS attribute "image-rendering"

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1460]
the CSS attribute &quot;image-rendering&quot;

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __chaiomanot__ on __2014-11-08__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by yisibl** [comment]
+ 1

**Comment by cvrebert** [comment]
Duplicate of #1246.
