### ISSUE TITLE
CSS3 Module: Paged Media Which browser do support it?

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1465]
CSS3 Module: Paged Media
Which browser do support it?

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __Sebastian Michaelsen__ on __2013-02-04__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1229.
