### ISSUE TITLE
text-wrap: balance    

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1467]
text-wrap: balance

http://dev.w3.org/csswg/css-text-4/#valdef-text-wrap-balance

http://blogs.adobe.com/webplatform/2013/01/30/balancing-text-for-better-readability/

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __medmunds__ on __2015-03-31__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Covered by #1064?

**Comment by Fyrd** [comment]
Yup.
