### ISSUE TITLE
border-image-outset

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1470]
border-image-outset

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __Rob Speed__ on __2014-11-23__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Presumably covered by http://caniuse.com/#feat=border-image

**Comment by Fyrd** [comment]
Yup.
