### ISSUE TITLE
Number.EPSILON

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1471]
Number.EPSILON

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __aarzee__ on __2015-03-26__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
http://kangax.github.io/compat-table/es6/#Number_properties_Number.EPSILON

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=es6-number
