### ISSUE TITLE
It would be wonderful if the browser release date was included in the compatibility table. Some brow...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1472]
It would be wonderful if the browser release date was included in the compatibility table. Some browsers push updates often and knowing when  a feature was supported could be more valuable then knowing which version first supported it.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __JMWeb__ on __2013-08-21__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by AdamMerrifield** [comment]
+1

**Comment by algazarra** [comment]
+1

**Comment by duanyao** [comment]
+1

**Comment by Fyrd** [comment]
Duplicate of #202
