### ISSUE TITLE
SpeechGrammar

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1473]
SpeechGrammar

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __Yonko__ on __2014-07-17__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Covered by http://caniuse.com/#feat=web-speech ?

**Comment by Fyrd** [comment]
Yup.
