### ISSUE TITLE
I just needed to know if the simple vertical-align was cross compatible ..

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1478]
I just needed to know if the simple vertical-align was cross compatible ..

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __Tadd Mencer__ on __2013-03-12__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1307.
