### ISSUE TITLE
Web Audio API.  It's different (and better) to the "Audio Data API".  Not listed anywh...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1491]
Web Audio API.  It&#39;s different (and better) to the &quot;Audio Data API&quot;.  Not listed anywhere currently, but Chrome has a webkit-namespaced implementation.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __AG__ on __2011-10-23__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Covered by http://caniuse.com/#feat=audio-api
