### ISSUE TITLE
javascript 'let' and 'const' functions/statements are not supported across all browse...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1493]
javascript &#39;let&#39; and  &#39;const&#39; functions/statements are not supported across all browsers, and are critical in recursive environments for straightening out closures and function objects.  A support table would be helpful!

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __themolecule__ on __2012-02-15__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
http://kangax.github.io/compat-table/es5/#Function.prototype.bind
http://kangax.github.io/compat-table/es6/#let

**Comment by Ugoku** [comment]
+1
I think `const` also belongs in this list.

**Comment by tigerhawkvok** [comment]
+1

**Comment by nightpool** [comment]
+1

**Comment by Fyrd** [comment]
`bind` is part of http://caniuse.com/#feat=es5 so removing it from this list.

**Comment by dstorey** [comment]
I’m looking into making a pull request to add these soon.

**Comment by Webysther** [comment]
+1

**Comment by Fyrd** [comment]
let available at http://caniuse.com/#feat=let
const now available at http://caniuse.com/#feat=const
