### ISSUE TITLE
document.execCommand

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1494]
document.execCommand

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __dave &#868;&#878;&#867;&#873;__ on __2014-08-19__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by garhbod** [comment]
http://www.quirksmode.org/dom/execCommand.html

**Comment by lizter** [comment]
+1

**Comment by kyleknighted** [comment]
+1
https://developer.mozilla.org/en-US/docs/Web/API/document/execCommand

**Comment by borisschapira** [comment]
+1

**Comment by danborufka** [comment]
+1

**Comment by mrapogee** [comment]
+1

**Comment by jelder** [comment]
+1

**Comment by NKjoep** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=document-execcommand
