### ISSUE TITLE
CSS3 marquee support.  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1499]
CSS3 marquee support.

http://www.w3.org/TR/css3-marquee/

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+15**
Issue added by **Mark T** on **2013-06-19**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
-1

**Comment by xtian** [comment]
-1

> Development of the marquee features of CSS has been abandoned.

**Comment by yukulele** [comment]
:+1:

**Comment by yuval-a** [comment]
+1

**Comment by yukulele** [comment]
no agree with @xtian, caniuse is support table, not a reference, an some unoff features are present in it, like http://caniuse.com/#feat=css-zoom

**Comment by BeejeeDS** [comment]
+1

**Comment by FireCoding** [comment]
+1

**Comment by mik-laj** [comment]
+1

**Comment by Schweinepriester** [comment]
Available via MDN: <https://caniuse.com/?search=marquee> esp. <https://caniuse.com/mdn-html_elements_marquee>
