### ISSUE TITLE
Input type email.  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1502]
Input type email.

http://developers.whatwg.org/states-of-the-type-attribute.html#e-mail-state-%28type=email%29

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by ____ on __2013-07-06__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by HolgerJeromin** [comment]
same as #975
