### ISSUE TITLE
document.compareDocumentPosition A great method to determine if one element contains another for goa...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1504]
document.compareDocumentPosition
A great method to determine if one element contains another for goals such as resolving duplicate id scenarios.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __JAB Creations__ on __2013-01-22__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by dyf19118** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=comparedocumentposition
