### ISSUE TITLE
sizes attribute

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1508]
sizes attribute

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+3**
Issue added by **Ricardo Zea** on **2015-04-08**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Ugoku** [comment]
+1

**Comment by mnsth** [comment]
+1

**Comment by jp7carlos** [comment]
+1

**Comment by vkimura** [comment]
+1

**Comment by erindotio** [comment]
+1

**Comment by iGadget73** [comment]
+1

**Comment by CSobol** [comment]
Do this please

**Comment by BeejeeDS** [comment]
+1

**Comment by Sioweb** [comment]
+1

**Comment by mdrummond** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by arnabonline** [comment]
+1

**Comment by Kolombiken** [comment]
+1

**Comment by olbrown** [comment]
+1

**Comment by timothy003** [comment]
+1

**Comment by schalkneethling** [comment]
+1

**Comment by sischnei** [comment]
+1

**Comment by norgeous** [comment]
+1

**Comment by partnuz** [comment]
+1

**Comment by KaelWD** [comment]
+1

**Comment by josepBG** [comment]
+1

**Comment by kfuzaylov** [comment]
+1

**Comment by ComiR** [comment]
+1

**Comment by anaibol** [comment]
+1

**Comment by fvm** [comment]
+1

**Comment by Fyrd** [comment]
Did the research, it appears all browsers with support for `srcset` have support for the `sizes` attribute too, so have folded in under there (also `sizes` requires `srcset` to have any effect). See http://caniuse.com/#feat=srcset
