### ISSUE TITLE
CSS3 min() and max() functions as values for properties that accept <dimension> as a value.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1509]
CSS3 min() and max() functions as values for properties that accept &lt;dimension&gt; as a value.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+3**
Issue added by **Nick G** on **2013-12-05**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by manuelbieh** [comment]
+1

**Comment by bfred-it** [comment]
+1

**Comment by Sacripant** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by Llbe** [comment]
+1

**Comment by ben-caplan** [comment]
+1

**Comment by cvrebert** [comment]
https://webkit.org/blog/7989/release-notes-for-safari-technology-preview-41/

> Added support for `min()` and `max()` in `calc()` (r222190)

**Comment by kbav** [comment]
+1

**Comment by js-choi** [comment]
+1.

**Comment by hacknug** [comment]
+1

**Comment by oscarotero** [comment]
+1

**Comment by Didel** [comment]
+1

**Comment by Malvoz** [comment]
+1

**Comment by derz** [comment]
+1

**Comment by claudepache** [comment]
+1

**Comment by jaydansand** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=css-math-functions

**Comment by Didel** [comment]
Now if only more browsers would support this...
