### ISSUE TITLE
can I use "attribute" in Chrome for IOS. I don't see this on the list of mobile browse...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1512]
can I use &quot;attribute&quot; in Chrome for IOS. I don&#39;t see this on the list of mobile browsers.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __Addzies__ on __2014-03-26__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1551.
