### ISSUE TITLE
domNode.insertBefore

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1516]
domNode.insertBefore

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __aerin__ on __2014-04-13__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore

**Comment by Fyrd** [comment]
Fully supported.
Can now be found at http://caniuse.com/#search=insertBefore
