### ISSUE TITLE
writing-mode compatibility

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1523]
writing-mode compatibility

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __nacho__ on __2015-01-20__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Fyrd** [comment]
Duplicate of #996 so adding half the votes there

**Comment by DylanPiercey** [comment]
+1
