### ISSUE TITLE
In the next update of Chrome please provide a Cache settings so we can move the location of the Chro...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1525]
In the next update of Chrome please provide a Cache settings so we can move the location of the Chrome&#39;s Cache, cookies, history, temp files to a folder of our choice on a drive of our choice.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __Gymrat__ on __2014-12-23__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
-1
@Fyrd This should be closed as invalid.

**Comment by Fyrd** [comment]
@cvrebert Yup, thanks. I think some people assumed Google Moderator was somehow for any google bugs.
