### ISSUE TITLE
+1 for adding a compatibility table.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1527]
+1 for adding a compatibility table.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __Sara Soueidan__ on __2015-05-01__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by vladimirmartsul** [comment]
+1

**Comment by Fyrd** [comment]
Not sure what happened here, but...there's nothing specified here.
