### ISSUE TITLE
.style.setAttribute() Does every browser support it? Sometimes it's hard to know it it's not...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1528]
.style.setAttribute() Does every browser support it? Sometimes it&#39;s hard to know it it&#39;s not there because every browser supports it or because it just hasn&#39;t been suggested.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+3**
Issue added by **knod** on **2015-04-24**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by RileyMajor** [comment]
+1

**Comment by cvrebert** [comment]
Duplicate of #2378 ?
There's no `setAttribute` in the spec, only `setProperty`.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_cssstyledeclaration_setproperty
