### ISSUE TITLE
Please add a support table for the CanvasRenderingContext2D.filter property that firefox supports.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1530]
Please add a support table for the CanvasRenderingContext2D.filter property that firefox supports.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+3**
Issue added by **ILOVEPIE** on **2015-04-25**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Saturnyn** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_canvasrenderingcontext2d_filter
