### ISSUE TITLE
window.applicationCache

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1531]
window.applicationCache

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __James__ on __2015-03-10__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by vladimirmartsul** [comment]
+1

**Comment by cvrebert** [comment]
Covered by http://caniuse.com/#feat=offline-apps
