### ISSUE TITLE
Please add "Web Manifest":    It's currently supported in Chrome on Android and Mozill...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1532]
Please add &quot;Web Manifest&quot;: 
http://w3c.github.io/manifest/

It&#39;s currently supported in Chrome on Android and Mozilla is implementing in Gecko.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+3**
Issue added by **Marcos** on **2015-01-27**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
-1

**Comment by NOtherDev** [comment]
+1

**Comment by nhoizey** [comment]
+1

**Comment by borisschapira** [comment]
+1

**Comment by webatou** [comment]
+1

**Comment by NOtherDev** [comment]
Manifest is actually just a JSON file with the metadata. The actual feature is how the file is used and what we're probably want here is the browser-assisted home screen installation feature with standalone appearance. 

If so, it's not only Chrome & Opera on Android, but also [Safari on iOS](https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html) - although this is not a standard approach, it lets add the web app to the home screen and run without Safari UI. I think that might be valuable inclusion.

**Comment by stevenvachon** [comment]
+1

**Comment by jpmedley** [comment]
+1

**Comment by ghtore** [comment]
+1

**Comment by blq** [comment]
+1

**Comment by franciov** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by johnstok** [comment]
+1

**Comment by kenchris** [comment]
:+1:

**Comment by slightlyoff** [comment]
:+1:

**Comment by patrickkettner** [comment]
@fyrd happy to put together the list for this, but how do you want to measure support? a `relList.supports('manifest')`? Or do you want the browser to do something with the data visually in some way?

**Comment by Fyrd** [comment]
@patrickkettner Haven't looked into this much yet myself, but I'd say there's at least partial support if the browser clearly has read the manifest and done something with it. We can use numbered notes to specify how browsers are supporting some values but not others.

**Comment by patrickkettner** [comment]
> clearly has read the manifest and done something with it.

doing something with it is almost always a visual indication. A butter bar, or a thing that triggers an action, etc. The issue is that just because the browser supports the manifest format, doesn't mean that it does anything with it. Current Chrome mobile requires a manifest for PWA installation flow, but won't prompt a user to install on first visit. So none of the data required may be used.

Then there is things like desktop chrome, which by default doesn't do anything with manifest files, but can request them, read them, and validate them through dev tooling. It does support the manifest files, but doesn't "do" anything with them.

I am mostly thinking of this from a automated-testing point of view, so if you would rather just go off of first person knowledge, thats fine too. Just let me know how you'd like to roll.

**Comment by kenchris** [comment]
Actually Chrome desktop has "Add to desktop..." options in menu -> More tools" which I believe does use at least the title, and icon. Maybe @PaulKinlan can confirm/deny

**Comment by patrickkettner** [comment]
@kenchris I am not seeing that

![image](https://cloud.githubusercontent.com/assets/465414/18966436/04c6fe64-8636-11e6-9be1-5217fe922a26.png)

which version are you on?

**Comment by kenchris** [comment]
I have it on Linux and Chrome OS. I run beta on both I believe

**Comment by patrickkettner** [comment]
Not seeing it on Linux. Have flags set?

**Comment by kenchris** [comment]
![addtodesktop](https://cloud.githubusercontent.com/assets/1101339/18985698/727b7a2a-86f9-11e6-9b22-5fd4a3aeeaa5.png)

Yeah that might be it, I have the "shelf" flag set as seen on the screenshot above.

**Comment by Benimation** [comment]
+1

**Comment by stephanie-walter** [comment]
+1 :)

**Comment by simon-previdente** [comment]
+1

**Comment by jonathanulco** [comment]
+1

**Comment by patrickkettner** [comment]
whats up?

**Comment by Fyrd** [comment]
Nothing, just don't like closing issues before the feature's on the site.

**Comment by patrickkettner** [comment]
*phew* - worried there was some kind of discrepancy :]

**Comment by Fyrd** [comment]
This actually got added on Oct 18, 2016 at http://caniuse.com/#feat=web-app-manifest
