### ISSUE TITLE
text-rendering: optimizeLegibility    

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1533]
text-rendering: optimizeLegibility

https://developer.mozilla.org/en-US/docs/Web/CSS/text-rendering

http://www.w3.org/TR/SVG11/painting.html#TextRenderingProperty

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __:b__ on __2014-06-03__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by vladimirmartsul** [comment]
+1

**Comment by Fyrd** [comment]
Already added at http://caniuse.com/#feat=kerning-pairs-ligatures
