### ISSUE TITLE
x-frame-options allow-from

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1534]
x-frame-options allow-from

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __JP__ on __2015-02-12__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by vladimirmartsul** [comment]
+1

**Comment by cvrebert** [comment]
Approximate duplicate of #1138.
