### ISSUE TITLE
Can I use "onmouseover", "onmouseout"?

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1536]
Can I use &quot;onmouseover&quot;, &quot;onmouseout&quot;?

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+3**
Issue added by **heda** on **2014-09-02**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by taylordcraig** [comment]
+1, I would love a caniuse table to see browser compatibility on this.

**Comment by Egrodo** [comment]
+1

**Comment by ruchern** [comment]
Yes, you definitely can.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#search=onmouseover & https://caniuse.com/#search=onmouseout
