### ISSUE TITLE
Hi, 2 things: 1. ElementFromPoint is interesting & has odd behavior in Firefox. 2. Your own &quo...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1537]
Hi, 2 things:
1. ElementFromPoint is interesting &amp; has odd behavior in Firefox.
2. Your own &quot;Suggest this feature to be added&quot; is broken.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __snadrus__ on __2014-01-21__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Duplicate of #1193.

**Comment by techsin** [comment]
+1
