### ISSUE TITLE
URL utils

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1539]
Documented here: http://url.spec.whatwg.org/#api
And here: https://developer.mozilla.org/en-US/docs/Web/API/URL

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __James__ on __2014-03-30__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by realityking** [comment]
+1

**Comment by xtian** [comment]
Dupe of Fyrd/caniuse#1312?

**Comment by jtangelder** [comment]
:+1:

**Comment by glen-84** [comment]
+1

**Comment by yukulele** [comment]
+1

**Comment by 304NotModified** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by tapananand** [comment]
+1

**Comment by Fyrd** [comment]
Somehow missed it, but yes this is a duplicate of #1312
