### ISSUE TITLE
strong

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1540]
strong

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+3**
Issue added by **Nico** on **2015-01-06**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
-1

**Comment by cvrebert** [comment]
@Fyrd Close as unnecessary?

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-html_elements_strong
