### ISSUE TITLE
form input property "valueAsNumber"

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1542]
form input property &quot;valueAsNumber&quot;

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+3**
Issue added by ____ on **2012-09-24**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by odegroot** [comment]
+1

**Comment by kadauber** [comment]
+1

**Comment by Schweinepriester** [comment]
Available via MDN: <https://caniuse.com/mdn-api_htmlinputelement_valueasnumber>

However the link to MDN appears to be missing. <https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement> would probably be the correct one.

**Comment by Fyrd** [comment]
Closing as per @Schweinepriester 's link
