### ISSUE TITLE
rel=prefetch & rel=preload support

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1543]
rel=prefetch &amp; rel=preload support

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __Vasil Toshkov__ on __2015-02-12__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Fyrd** [comment]
Duplicate of #981

**Comment by kimslawson** [comment]
+1
