### ISSUE TITLE
i would like to see the comparation of ZOOM style between browsers. Thank you so much!

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1545]
i would like to see the comparation of ZOOM style between browsers. Thank you so much!

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __thaodns__ on __2012-12-06__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by pkuczynski** [comment]
This is duplicate of #1453, isn't it? So it should be closed...
