### ISSUE TITLE
Luminosity media query 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1549]
Luminosity media query
http://dev.w3.org/csswg/mediaqueries4/#luminosity

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+3**
Issue added by **thermistor** on **2014-08-06**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Part of #1069.
Current spec URL: http://dev.w3.org/csswg/mediaqueries-4/#light-level

**Comment by adiabatic** [comment]
+1

**Comment by cvrebert** [comment]
-1

**Comment by mjamesderocher** [comment]
+1

**Comment by Schweinepriester** [comment]
`light-level` (aka. luminosity) seems to be missing from the spec now?

**Comment by cvrebert** [comment]
Yeah, it got punted to Level 5: https://github.com/w3c/csswg-drafts/commit/29b3d5ca56cc5b394629b25b6d6c12c7edabbe15

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_at-rules_media_light-level
