### ISSUE TITLE
'caniuse.com' should have small-caps (and other font variants?) broken out as a separate fea...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1550]
&#39;caniuse.com&#39; should have small-caps (and other font variants?) broken out as a separate feature.

iOS versions &lt;= 4.3.5 don&#39;t render .ttf &amp; .svg web fonts when the CSS property &#39;font-variant:  small-caps&#39; is used.

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+3**
Issue added by **A fate  worse than Beth** on **2011-09-06**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by vladimirmartsul** [comment]
+1

**Comment by jensimmons** [comment]
Yes, all of these should be separate CSS properties:
```
font-variant-ligatures
font-variant-caps
font-variant-east-asian
font-variant-alternates
font-variant-numeric 
font-variant-position
```

**Comment by RoelN** [comment]
+1

**Comment by Fyrd** [comment]
These are all available now, e.g. https://caniuse.com/#feat=mdn-css_properties_font-variant-caps
