### ISSUE TITLE
Add iOS Chrome to the support tables

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1551]
Add iOS Chrome to the support tables

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __cheeaun__ on __2013-01-19__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by gregzx** [comment]
Chrome for iOS is based on default iOS webkit. is there any difference between Chrome for iOS and Safari on iOS?

**Comment by Fyrd** [comment]
There's no big difference, no...I think there's a few network and UI related things that could be different, but I think adding notes in those cases is sufficient.
