### ISSUE TITLE
Please add some type of public API (maybe REST) for using caniuse from plugins for example.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1552]
Please add some type of public API (maybe REST) for using caniuse from plugins for example.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __Enrique__ on __2012-05-03__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
This needs the "Site functionality" label.

**Comment by Fyrd** [comment]
This request was made before caniuse was on GitHub and npm, seems that's been sufficient for anyone trying interested in working with the data, so closing this request.
