### ISSUE TITLE
CSS shapes

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1554]
CSS shapes

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __rdoyle__ on __2014-03-25__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by vladimirmartsul** [comment]
+1

**Comment by Fyrd** [comment]
Already added at http://caniuse.com/#feat=css-shapes
