### ISSUE TITLE
backdrop-filter

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1555]
backdrop-filter

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __rale__ on __2015-02-18__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by youngroger** [comment]
+1

**Comment by netlovers** [comment]
+1

**Comment by appsforartists** [comment]
+1

It's going to be in Safari 9.  It'd be good to know if/when other browsers expect to support it.

**Comment by Ugoku** [comment]
+1
[Link to spec](http://dev.w3.org/fxtf/filters/#typedef-filter-function-list)

**Comment by vitorbal** [comment]
+1

**Comment by ivanreese** [comment]
+1

**Comment by davidkaneda** [comment]
+1 (as if voting here will help browsers adopt faster... want this bad)

**Comment by appsforartists** [comment]
Looks like it'd be fairly easy to add. Duplicate [this file](https://github.com/Fyrd/caniuse/blob/master/features-json/css-filters.json) and set everything to `n` except for `saf9` and `ios_saf9`.  I know it isn't in Chrome.  It's not on [modern.ie](https://status.modern.ie/filters?term=filter), so I presume it isn't in IE either.  It'd be easy enough to test in Firefox.

**Comment by Ugoku** [comment]
Can confirm that [this demo](http://product.voxmedia.com/til/2015/2/17/8053347/css-ios-transparency-with-webkit-backdrop-filter) does not work in Firefox 38, Opera 31, Chrome 43.

**Comment by mik01aj** [comment]
+1

**Comment by alexandrethsilva** [comment]
+1

**Comment by robflaherty** [comment]
+1

**Comment by pascalgagneur** [comment]
+1

**Comment by mikestecker** [comment]
+1

**Comment by evolutionjay** [comment]
+1
