### ISSUE TITLE
Please add support tables for x-xss-protection security header. Thanks!

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1556]
Please add support tables for x-xss-protection security header.
Thanks!

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+3**
Issue added by **Dan A** on **2014-04-10**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by vladimirmartsul** [comment]
+1

**Comment by hthole** [comment]
+1

**Comment by ondrakoupil** [comment]
+1

**Comment by Myiyk** [comment]
+1

**Comment by 304NotModified** [comment]
+1

**Comment by ayomawdb** [comment]
+1

**Comment by Calico90** [comment]
+1

**Comment by t1gor** [comment]
Any idea when this might actually happen? Or any other source we could look this info in?

**Comment by Calico90** [comment]
No idea, but hopefully soon :)

**Comment by afx2000** [comment]
+1

**Comment by BreakfastSerial** [comment]
**+1**

**Comment by antonjuulnaber** [comment]
It doesn't seem like this will ever happen, so I wanted to leave a quick note for anyone else coming here:

The x-xss-protection header is not very useful anymore.
- Chrome, Edge, Firefox does not have or have removed support for the header.
- IE has support, but who cares.
- Safari has support, but most of the features are enabled by default (without using the header).

On top of that, the actual effectiveness of the header is widely questioned.
A much better way to secure against XSS attacks is to implement a strong Content-Security-Policy.

**Comment by atjn** [comment]
I think you can close this. It is available at https://caniuse.com/#feat=mdn-http_headers_x-xss-protection
