### ISSUE TITLE
Can we include Server Name Indication support to caniuse? Now that Amazon AWS is starting to use it ...

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1559]
Can we include Server Name Indication support to caniuse? Now that Amazon AWS is starting to use it in a big way, this kind of information would be useful to know. I know it&#39;s not strictly a HTML thing, but it is browser dependent...

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __H. Chang__ on __2014-04-29__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by vladimirmartsul** [comment]
+1

**Comment by Fyrd** [comment]
Duplicate of #979  so adding half the votes there
