### ISSUE TITLE
Please add :autofill to the DB

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1560]
Please add :autofill to the DB

---
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)

Moderator votes: **+3**
Issue added by **Bobby** on **2015-02-10**
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by pkuczynski** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/:-webkit-autofill

**Comment by appsforartists** [comment]
:+1:

**Comment by appsforartists** [comment]
We should also add this note:

> Any variant of `querySelector(":autofill")` should be wrapped in a `try` block, as both Chrome and Firefox will throw errors if they don't recognize a selector.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_selectors_-webkit-autofill
