### ISSUE TITLE
addEventListener and attachEvent

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1561]
addEventListener and attachEvent

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __Shiva__ on __2014-11-19__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by HolgerJeromin** [comment]
duplicate to #1250

**Comment by Fyrd** [comment]
Duplicate of #1085 so adding half the votes there.
