### ISSUE TITLE
Attributes for form submission

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1562]
Attributes for form submission: http://www.whatwg.org/specs/web-apps/current-work/#attributes-for-form-submission
Includes: formaction, formenctype, formmethod, formnovalidate, and formtarget as new attributes

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+12__
Issue added by __Alexander Y__ on __2013-03-19__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
Faster link: https://html.spec.whatwg.org/multipage/forms.html#attributes-for-form-submission

**Comment by alistairshaw** [comment]
+1

**Comment by kenmorechalfant** [comment]
+1

**Comment by HipsterJazzbo** [comment]
+1

**Comment by onlynone** [comment]
+1

**Comment by MrAntix** [comment]
+1

**Comment by mintbridge** [comment]
+1

**Comment by yukulele** [comment]
+1

**Comment by zsk526** [comment]
+1

**Comment by yukulele** [comment]
* chrome9+
* firefox4+
* ie10+
* opera10+
* safari5+
https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input#Compatibilit.C3.A9s_des_navigateurs

**Comment by martijn80** [comment]
+1

**Comment by nickleus** [comment]
+1

**Comment by TisButMe** [comment]
+1

**Comment by blowski** [comment]
+1

**Comment by alallier** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=form-submit-attributes
