### ISSUE TITLE
Canvas .toDataUrl()

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1564]
Canvas .toDataUrl()

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __peppe__ on __2014-12-04__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by pkuczynski** [comment]
Shouldn't that be closed too if you cancel my pull request?

**Comment by Fyrd** [comment]
Yeah, this support is now included in http://caniuse.com/#feat=canvas
