### ISSUE TITLE
encodeURI

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#1565]
encodeURI

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+3__
Issue added by __plk3000__ on __2014-10-04__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
This is ancient (ECMAScript 3rd Edition).

**Comment by Ugoku** [comment]
-1
for reason given by cvrebert. This has worked since IE5.5

**Comment by xtian** [comment]
-1

**Comment by cvrebert** [comment]
X-Ref: #1743

**Comment by Fyrd** [comment]
Closing due to complete support.
