### ISSUE TITLE
Error link in page http://caniuse.com/feed.php?id=156

### ISSUE THREAD

**Issue by lguzzon** [Fyrd/caniuse#1566]
the link "... ment. These votes are then tallied and the resulting list in order of votes is generated here."
@ word "generated here" wrongly points to http://caniuse.site/issue-list and not http://caniuse.com/issue-list
Surely a typo error ;)

**Comment by awayken** [comment]
The incorrect URL shows here, too: http://caniuse.com/feed/156

**Comment by Fyrd** [comment]
Thanks, fixed!
