### ISSUE TITLE
divide linear-gradient and radial-gradient

### ISSUE THREAD

**Issue by oti** [Fyrd/caniuse#1567]
linear-gradient is already unprefixed in almost modern browsers, but radial-gradient is not yet ([JSFiddle](https://jsfiddle.net/jbg5a8oc/)).

In caniuse, these gradient property statuses has been combined into [one](http://caniuse.com/#search=gradient). So, this has caused the Autoprefixer does not correctly process the radial-gradient. I hope divide linear-gradient and radial-gradient.

**Comment by Fyrd** [comment]
Nope, common mistake. You're using the old syntax which only works prefixed. That's invalid according the current spec (unprefixed). In your fiddle if you change your value to `background-image: radial-gradient(ellipse closest-side at center, blue 0%, orange 100%);` you'll notice it works fine.

**Comment by oti** [comment]
oh sorry... thank you very much! :)
