### ISSUE TITLE
Add accessibility tools like Jaws, NVDA and Apple VoiceOver to support tables

### ISSUE THREAD

**Issue by evanwills** [Fyrd/caniuse#1571]
It would be absolutely awesome if Can I Use included accessibility tools like Jaws (in IE on Windows) NVDA (in Firefox on Windows) support tables and VoiceOver on IOS & OSX.

(According to a Web Accessibility workshop presenter form Vision Australia (http://www.visionaustralia.org/), apparently Jaws (http://www.freedomscientific.com/Products/Blindness/JAWS) support for non-IE browsers is poor so Jaws users tend to stick to IE. Likewise NVDA (http://www.nvaccess.org/) supports Firefox better than other browsers so NVDA users tend to stick to FF. Apple users have VoiceOver (https://www.apple.com/au/accessibility/osx/voiceover/ & https://www.apple.com/au/accessibility/ios/voiceover/) built in so it would be great to include that too.)

(PS: I know this stuff might be hard to build automated tests for.)
(PPS: "Can I Use" rocks. Thanks so much for building and sharing it)

**Comment by Fyrd** [comment]
I'd also love to see this data made available and if someone makes a site for it I'd be happy to link there. Unfortunately it's another dimension of testing compared to what's on caniuse now so this is not an effort I'd be able to take on in addition. Thanks for the kind words and the suggestion though, I'd love to see this happen.

**Comment by evanwills** [comment]
@Fyrd No worries.

I'm going to have a go at doing it. I'll let you know how I go.

Thanks again.
