### ISSUE TITLE
image tag

### ISSUE THREAD

**Issue by adaptabi** [Fyrd/caniuse#1575]
http://lynn.ru/examples/svg/en.html

<image tag is intercepted as <img tag in browsers, hence you can do

``` html
<svg width="96" height="96">
    <image xlink:href="svg.svg" src="svg.png" width="96" height="96"/>
</svg>
```

**Comment by Fyrd** [comment]
Part of https://caniuse.com/#feat=svg but now also https://caniuse.com/#feat=mdn-svg_elements_image
