### ISSUE TITLE
Repeat browser legend at the bottom of the support grid

### ISSUE THREAD

**Issue by tslatt** [Fyrd/caniuse#1577]
At this point there are so many browser versions listed in the grid that shows you the version support by browser, that once you get to the bottom of the grid to look at the most recent browser version row, you can't see the header showing you which browsers those are. You should repeat the grid header at the bottom, so folks don't have to continually scroll up and down to figure out which column is which browser.

**Comment by peiche** [comment]
+1

**Comment by Fyrd** [comment]
Just solved this problem in an even better way, using sticky headers. Now no matter how tall each table can get the headers will still be visible. Enjoy!
