### ISSUE TITLE
CSS filter() function (as value in background images, etc)

### ISSUE THREAD

**Issue by rockwalrus** [Fyrd/caniuse#1580]
This function lets you apply filters to images wherever images show up in CSS.  Chrome dashbord link: https://www.chromestatus.com/feature/5425136400334848

**Comment by cvrebert** [comment]
@rockwalrus Doesn't http://caniuse.com/#feat=css-filters already cover this?

**Comment by rockwalrus** [comment]
@cvrebert no.  for instance, firefox supports ```filter: grayscale(1)``` but not ```background-image: filter(url(image.png), grayscale(1))```

The standards reference is http://www.w3.org/TR/filter-effects/#FilterCSSImageValue

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-filter-function
