### ISSUE TITLE
Deploy updates to server please :)

### ISSUE THREAD

**Issue by jakub-g** [Fyrd/caniuse#1587]
Hi,

when I go to caniuse.com it seems the data there is quite outdated, it says February 21, 2015. There were dozens of changes in github repo since.

For instance I see here
 http://caniuse.com/#feat=user-timing
the data is "two Firefoxes ago", Firefox 38  - current stable - actually supports the feature and the data update even landed in github repo update a month ago but was not deployed since

Any chance to align the website with github repo?

**Comment by jakub-g** [comment]
Actually, what about hosting the page via `gh-pages` and configuring a Travis CI build that would auto-deploy to `gh-pages` after push to `master` & successful build?

**Comment by Fyrd** [comment]
The data actually appears on the site before it appears on github, I believe you're experiencing some caching issue. Reloading the page should bring it up to date.

**Comment by jakub-g** [comment]
Yeah indeed, after I did `CTRL-F5` in Firefox it refreshed the data.

I checked with an HTTP sniffer and when you request the index page, it responds with the following header

`Last-Modified: Sun, 20 Jul 2014 16:48:55 GMT`

Then the browser each time when requesting the index sends the this header:

`If-Modified-Since: Sun, 20 Jul 2014 16:48:55 GMT`

and the server always responds with `304 Not Modified`

You have to explicitly CTRL-F5 or purge cache to get update (it seems my Firefox cache is very large and keeps stuff around for months)

I guess you could tinker with your server's config to send proper `Last-Modified:` date (it seems it sends the modification date of `index.php` disregarding other contents embedded inside it)

**Comment by Fyrd** [comment]
@jakub-g Ah, good find! Indeed the date was being calculated incorrectly. Should now be fixed. Thanks for pointing that out!
