### ISSUE TITLE
Add support for the 'inert' attribute

### ISSUE THREAD

**Issue by nspaeth** [Fyrd/caniuse#1599]
This attribute is described here: https://html.spec.whatwg.org/multipage/interaction.html#inert-subtrees

**Comment by cvrebert** [comment]
That doesn't define an attribute, it just defines a concept. The word "attribute" doesn't even appear anywhere in that section.

**Comment by Fyrd** [comment]
Yeah, I believe this is covered by [support for the dialog element](http://caniuse.com/#feat=dialog)

**Comment by xamgore** [comment]
@Fyrd, may be it is the right moment to open the issue?

**Comment by Malvoz** [comment]
@xamgore 
Issue https://github.com/Fyrd/caniuse/issues/3090 covers this, with links to Chrome's intent to implement and other tracking bugs.
