### ISSUE TITLE
Image-Rendering IE

### ISSUE THREAD

**Issue by mattferderer** [Fyrd/caniuse#1604]
I don't believe IE11 or Edge support -ms-interpolation-mode. I've read that IE9 and newer do not support it. I've tried it on IE11 and it made no changes on pixelated images.

**Comment by Fyrd** [comment]
Works in my test. Not that it only works on actual images, not CSS background (as mentioned under know issues)

**Comment by mattferderer** [comment]
While it shows up in IE11 in the inspector view, it doesn't seem to make any changes to my eyes. 
http://plnkr.co/edit/l3xXUqPGfGcs0mGImHrH?p=preview

[Mozilla's wiki](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering) argues that it is only supported by IE7 & IE8.  Unfortunately I am unable to find Microsoft documentation on this and the link provided by the Mozilla wiki does not work.

**Comment by BarryCap** [comment]
Why did you close this issue? Is `-ms-interpolation-mode` searchable in Can I use? **No.** So this issue must not be closed.

![bilinear](https://user-images.githubusercontent.com/63713811/122223236-48c0e100-ceb3-11eb-9692-3efad641d654.png) ![nearest-neighbor](https://user-images.githubusercontent.com/63713811/122223310-59715700-ceb3-11eb-9a1f-ba84d6f4368f.png)
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&ensp;`-ms-interpolation-mode: bilinear`&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&ensp;`-ms-interpolation-mode: nearest-neighbor`




Don't you see a difference? This is IE 11.
