### ISSUE TITLE
Add use-text-color

### ISSUE THREAD

**Issue by RyanReese09** [Fyrd/caniuse#1607]
As a border-color CSS value, use-text-color is not added in.

E-mail to reach me: rreese@usna.edu
Ryan Reese
Web Developer

**Comment by cvrebert** [comment]
This appears to be a Mozilla-specific extension (`-moz-use-text-color`) with no un-prefixed or other-vendor-prefixed versions. (See https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Mozilla_Extensions#border-color).
It's equivalent to `currentColor`, which is supported all the way back to Firefox 2 per http://caniuse.com/#feat=currentcolor

**Comment by RyanReese09** [comment]
Thanks!

**Comment by Schweinepriester** [comment]
Just in case anybody stumbles upon this issue:

`-moz-use-text-color` was removed in Firefox 52 (<https://developer.mozilla.org/en-US/Firefox/Releases/52> or [bug 1306214](https://bugzilla.mozilla.org/show_bug.cgi?id=1306214)).
