### ISSUE TITLE
Enable HTTPS for the site

### ISSUE THREAD

**Issue by TonyZTan** [Fyrd/caniuse#1611]
Caniuse.com provides important information about a wide variety of browser features, including security-related ones such as HSTS, yet the website does not support HTTPS at all. As the web is becoming encrypted to protect user's privacy (browsing habits, etc.) and guarantee content authenticity (preventing ISPs from inserting ads, etc.) following the lead of big tech companies (such as Google, [here](http://googlewebmastercentral.blogspot.com/2014/08/https-as-ranking-signal.html)), it would be great if caniuse can support HTTPS. [TLS is not slow anymore](https://istlsfastyet.com), and TLS certificates can now be obtained for free, from providers such as [StartCom](https://www.startssl.com/), [WoSign](https://buy.wosign.com/free/), and soon [Let's Encrypt](https://letsencrypt.org).

If the existing hosting infrastructure does not support enabling HTTPS, you can still allow users to use HTTPS by signing up for a free plan at [CloudFlare](https://www.cloudflare.com/), a CDN that provides [free HTTPS support for all websites](https://www.cloudflare.com/ssl). To use them, you would only need to change the DNS records. If this option is used, no server-changes are necessary at all.

Please consider enabling HTTPS for caniuse.com. Thank you!

**Comment by Fyrd** [comment]
I'll get around to this eventually. :) Duplicate of #885.
