### ISSUE TITLE
"First-Party-Only" cookies

### ISSUE THREAD

**Issue by cyberixae** [Fyrd/caniuse#1613]
The "First-Party-Only" flag is used in cookies to limit the set of servers that will receive the cookie. It is a security feature that should decrease the amount of cross-site request forgery (CSRF) vulnerabilities.

https://tools.ietf.org/html/draft-west-first-party-cookies-03
https://www.chromestatus.com/features/4672634709082112

**Comment by Ugoku** [comment]
+1

**Comment by xtian** [comment]
+1

**Comment by mkurz** [comment]
+1

**Comment by 304NotModified** [comment]
+1

**Comment by mkurz** [comment]
This is now called `SameSite` cookie attribute.
Google is shipping it in version 51 (without a flag!).
See https://www.chromestatus.com/features/4672634709082112

**Comment by another-dave** [comment]
👍  +1

**Comment by MaxGabriel** [comment]
👍 +1

**Comment by Flimm** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=same-site-cookie-attribute
