### ISSUE TITLE
Previous Element Selector

### ISSUE THREAD

**Issue by hovermind** [Fyrd/caniuse#1614]
!previous + next {
 property: value;
}

**Comment by cvrebert** [comment]
The `!` syntax was in [an old draft of Selectors Level 4](http://www.w3.org/TR/2013/WD-selectors4-20130502/#subject), but doesn't seem to be part of [the current draft](http://dev.w3.org/csswg/selectors/)

**Comment by cvrebert** [comment]
@Fyrd Close this because of https://github.com/Fyrd/caniuse/issues/1058#issuecomment-211222206 ?
