### ISSUE TITLE
Settings UI could be more user-friendly

### ISSUE THREAD

**Issue by Ketsuban** [Fyrd/caniuse#1615]
I apologise if this is the wrong place for reporting issues with the site, but I couldn't find a repository specifically for it as opposed to the database. I'm principally concerned with the minimum usage cutoff slider, since that's what I just used—I have other complaints, but they're more relevant to a proper UX review than this report about one widget.

* The slider has no options for text entry. This wouldn't be a problem, except that…
* The slider doesn't increment particularly sanely when scrolled with the keyboard. Starting at zero, successive taps of the right arrow key got me two increments displayed as 0.00%, followed by 0.01%, 0.02%, 0.05%, 0.07% and so on. The first halfway reasonable value I was able to select was 0.1%, but others (including the default of 0.5%) were inaccessible—it jumped from 0.47% to 0.54%. If you change it from 0.5% you're somewhat stuck, because…
* There's no way to reset the value to default without knowing that the site stores that value in localStorage and how to alter the localStorage data for a site.

**Comment by Fyrd** [comment]
Okay, yeah, it would be nice to have nicer numbers appear, so I've made some changes to do just that. This includes:

* Nicer numbers when dragging the slider
* Making the % field editable on click so any value can be set
* Allowing it to be set back to default when value is set to an empty string (not ideal, may come up with something better to reset all settings)

Thanks for the suggestion!

**Comment by Schweinepriester** [comment]
Nicer reset still needed... :)
