### ISSUE TITLE
lockOrientation missing

### ISSUE THREAD

**Issue by BananaAcid** [Fyrd/caniuse#1617]
as described here: https://developer.mozilla.org/en-US/docs/Web/API/Screen/lockOrientation#Browser_compatibility

and https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation

usage example:
http://stackoverflow.com/a/30222772/1644202

**Comment by cvrebert** [comment]
Seems like it falls under http://caniuse.com/#feat=screen-orientation The properties/methods you mention are presumably from an old version of the spec.

**Comment by Fyrd** [comment]
Yeah, I've updated http://caniuse.com/#feat=screen-orientation a bit to clarify and made lockOrientation searches point at it.
