### ISSUE TITLE
orientationchange Event

### ISSUE THREAD

**Issue by mjgw** [Fyrd/caniuse#1631]
It would be wonderful to be able to check and see which browsers support this event

**Comment by cvrebert** [comment]
@mjgw http://caniuse.com/#feat=screen-orientation

**Comment by Fyrd** [comment]
Actually...the original orientationchange from the older spec (now removed) has much better support, so it's probably worth including by itself.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_window_orientationchange_event
