### ISSUE TITLE
Bindings - Lexical Declarations (const, let)

### ISSUE THREAD

**Issue by Webysther** [Fyrd/caniuse#1635]
https://www.chromestatus.com/features/4645595339816960
https://people.mozilla.org/~jorendorff/es6-draft.html#sec-let-and-const-declarations
https://googlechrome.github.io/samples/lexical-declarations-es6/index.html

**Comment by cvrebert** [comment]
Approximate duplicate of #1493.

**Comment by Webysther** [comment]
yes, only the naming isnt correct. :-)

**Comment by Fyrd** [comment]
Alright, added `const` to #1493 and closing this.
