### ISSUE TITLE
window.frames list

### ISSUE THREAD

**Issue by cobbdb** [Fyrd/caniuse#1642]
I don't see much information out there for browser support for window.frames
https://developer.mozilla.org/en-US/docs/Web/API/Window/frames
http://www.w3schools.com/jsref/prop_win_frames.asp

MDN lists it as non-standard so it'd be great to have some confidence as to where it is supported.

This stackoverflow question has responses stating that it is very widely supported
http://stackoverflow.com/questions/2947082/whats-the-most-concise-cross-browser-way-to-access-an-iframe-elements-window

**Comment by cvrebert** [comment]
-1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_window_frames
