### ISSUE TITLE
Html form tag <label>

### ISSUE THREAD

**Issue by hyperTwitch** [Fyrd/caniuse#1646]
Used in forms to associate text with elements such as inputs. Currently not a tag listed in the site.

W3 spec link: http://www.w3.org/TR/2014/REC-html5-20141028/forms.html#the-label-element
Status: W3C Recommendation(?)
Category: HTML5

Parent feature: forms
Keywords: label, form

**Comment by Fyrd** [comment]
HTML4 tag, already supported everywhere.
