### ISSUE TITLE
iOS9 Transform support inconsistant

### ISSUE THREAD

**Issue by Dangoo** [Fyrd/caniuse#1647]
According to caniuse-table, "CSS 3D Transforms" will lose their -webkit prefix, while "CSS Transforms (2D)" are still flagged with "Supported with prefix `-webkit`"

The Apple Docs tell this story:

The properties in Newly supported ECMAScript 6 properties are now fully supported by Safari, without the -webkit- prefix.
…
transform
transform-origin
transform-style

**Comment by ryami333** [comment]
+1
Here is the documentation: https://developer.apple.com/library/prerelease/mac/releasenotes/General/WhatsNewInSafari/Articles/Safari_9.html#//apple_ref/doc/uid/TP40014305-CH9-SW28

**Comment by Fyrd** [comment]
Yeah, an oversight on my part. Fixed now, thanks for pointing it out.
