### ISSUE TITLE
JSON.parse reviver argument recursion

### ISSUE THREAD

**Issue by atsger** [Fyrd/caniuse#1653]
My users have reported a very annoying bug in my software. After debugging I ended up discovering a very annoying lack of support in IE that should be known by everyone:

(Some versions of?) IE won't call your `reviver` argument recursively when using `JSON.parse`.

Here, I created a gist to demonstrate:
https://gist.github.com/atsger/8b2339bf17e44de92ac4
It shows 'false' on my IE11@Win7x64.

*Have a look at [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) too to see how this feature should have implemented.*

**Comment by atsger** [comment]
OK, here comes the interesting part: IE8@WinXPx86 returns 'true'.
Redmond, I need an explanation. (Don't tell me you degraded your code!)

**Comment by Ugoku** [comment]
Edge on Windows 10 build 10130 also returns `true`. Same for IE11 on the same machine. Can try IE11 on Win 8.1 tomorrow.

**Comment by atsger** [comment]
I ended up including conditionally [JSON 3](https://github.com/bestiejs/json3) after the same quick test I've wrote into the gist.
However I was curious (just like Chitanda).

In the end I visited [NetRenderer](http://netrenderer.com/) and tested the gist, so right now we have the following facts:
* on Win10 Edge and IE11 returns 'true' (thanks to @Ugoku!)
* on Win7 IE11 returns 'false' (I did multiple tests on different specifications)
* IE9-11 returns 'false' (according to NetRenderer - no OS info available)
* IE8 returns 'true' (according to NetRenderer - no OS info available, and according to my WinXP test)
* IE8 was the first IE with JSON support (written on [MSDN](https://msdn.microsoft.com/en-us/library/cc836458(v=vs.94).aspx))

:confused: Well....... maybe I have a theory.

What if there is some OS version-specific dll which performs the action? That could explain the different behavior of IE11.

**Comment by Ugoku** [comment]
Bit later than expected, but tested in IE11 on Windows 8.1: returns false just like on Windows 7.

**Comment by Fyrd** [comment]
Added as a known issue.

**Comment by richardszalay** [comment]
Are we sure that this is an issue with json parsing?  Given the repro gist, it could as well be an issue with  the order of the properties being enumerated, [which  isn't guaranteed](http://stackoverflow.com/a/5525820/3603)

**Comment by atsger** [comment]
After all this waiting here is my explanation: according to ECMAScript specification Object property order is indeed not guaranteed -- however the attached code does not "use" Object property order. Take a closer look: it's about JSON string parsing (`log` string variable stores the order of the keys to be parsed in the JSON string). And strings *do* guarantee the order of their characters, what a chaotic universe would ours be if it wouldn't be like that?!

**Comment by richardszalay** [comment]
Does the specification require that the implementation call the reviver in the order that the properties appear in the source string? What if the implementation creates the structure of the object and then goes back to revive the properties?

I'm not saying that's the case, only that the gist's assertion of correctness is based heavily on that assumption.

**Comment by ivanzvakoms** [comment]
On Win7 IE11:
![screen shot 2016-11-23 at 11 37 27 pm](https://cloud.githubusercontent.com/assets/12155794/20579556/f054e15a-b1d5-11e6-8656-b62be9ae4695.png)

**Comment by BubbleLeaf** [comment]
the problem is key of object.if you do the test with word like this , you will get "true" 。 
![image](https://user-images.githubusercontent.com/16011072/32038917-a0c3964e-ba5e-11e7-98e0-9ceea2fae0a2.png)
