### ISSUE TITLE
HSTS & IE11 Support

### ISSUE THREAD

**Issue by gellerb** [Fyrd/caniuse#1658]
Currently, the results for HSTS on IE11 suggest it's supported. However, the support was actually added
a few days ago with security patch MS15-056[1]. Can we add an asterisk to suggest that there's a caveat involved? Otherwise, one would think all IE11 versions are shipped with HSTS support.

[1] https://connect.microsoft.com/IE/feedback/details/793747/ie11-feature-request-support-for-the-strict-transport-security-header

**Comment by Fyrd** [comment]
Good point, thanks. A note on this has now been added.
