### ISSUE TITLE
Microsoft Edge !== Microsoft Internet Explorer

### ISSUE THREAD

**Issue by mzgol** [Fyrd/caniuse#1660]
Microsoft Edge, while forked from Internet Explorer is officially a different browser. It should be presented as such in the data. Currently the package & the site seems to suggest that there exists an IE Edge browser that's the successor to IE 11.

If you don't want to introduce another column on the site, you could change the "IE" header to "IE/Edge" but data should still be separated.

**Comment by Fyrd** [comment]
Sounds good, I'll probably do this eventually. It would be nice if Edge actually had version numbers of some sort. I've heard there'll be build numbers but that could get pretty ugly.

**Comment by KaptenJansson** [comment]
I also vote for treating Edge as a separate browser due to not bringing over the IE legacy stuff (which is on purpose AFAIK so that they can start fresh without being dragged down by interop).

But having it as an IE version is good enough for now, at least it's there.

**Comment by mzgol** [comment]
In the future it might be worthy to show when Edge would have gained support for something, similarly to how Chrome/Firefox is handled even though older versions are not commonly used (e.g. to see how likely are most Edge users to be on a new enough version - if the feature appeared a week ago, it's not safe yet). In that case, older Edge versions will have diminishing relevance and IE11 will still be important.

Of course it's a little harder with Edge since it won't have versions... but you can always version by build or approximate date of an update.

**Comment by BenLeggiero** [comment]
It also uses a completely new rendering engine which masquerades as Blink, so knowing what it actually does and doesn't support is essential.

**Comment by mzgol** [comment]
> It also uses a completely new rendering engine

"Completely new" is a stretch. This is just a recent Trident fork so it shares a lot with IE11, even though they removed a lot of cruft like ActiveX & document modes.

**Comment by mzgol** [comment]
BTW, keeping `Edge` as a version may break some modules depending on values being numbers or ranges like [browserslist](npmjs.com/package/browserslist) (see e.g. [logic handling strings like `"ie >= 10"`](https://github.com/ai/browserslist/blob/8335dfeb4aa229e555e5d569c9a32deb65c3a49f/index.js#L298-L301)) used by Autoprefixer. I'm sure they'll fix it on their side when Edge gets released but that shows that current data format is not perfectly consistent with other values.

**Comment by mzgol** [comment]
Latest Edge versions do have build numbers in the user agent. It used to be `Edge/12.0` but now we have the build number instead of `0`. Later it was `Edge/12.9600`, the next build [should be](https://github.com/jquery/jquery/commit/8e111df641cca3e1b75b31a1971bfc89014b4ded#commitcomment-11850878) `Edge/12.10130`.

**Comment by Fyrd** [comment]
Have just made this change as per @mzgol's suggestion (separate in data, joined on site). 

For now the version appears as "1" in the data...and I haven't yet decided how to do subsequent versions. While build numbers is an option, I doubt StatCounter and Google Analytics while bother making a distinction which would make it impossible to tell how many users use each. 

Most likely I'll eventually wind up keeping track of just the latest couple of versions and dump all the usage numbers in the latest one. We'll see.
