### ISSUE TITLE
Support for 'debugger;' in dev tools

### ISSUE THREAD

**Issue by wmill** [Fyrd/caniuse#1664]
In Chrome you can use the command 'debugger' to insert a breakpoint at source level.

It would be good to know if other platforms support this.

**Comment by cvrebert** [comment]
+1

**Comment by devrelm** [comment]
There's more info on the `debugger` statement [in the MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger).

According to that page, it appears to have pretty wide support, though I haven't done my own testing yet. If it's as widely sorted as it appears to be, I just can't believe I've only just learned about it.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_statements_debugger
