### ISSUE TITLE
Bubble

### ISSUE THREAD

**Issue by estraschnov** [Fyrd/caniuse#1667]
Hello,

We're building a visual development framework (https://bubble.is) and we'd love to be part of caniuse. Could chat about that?

Emmanuel

**Comment by Fyrd** [comment]
Not sure what you mean by being "part of"...the site is managed by just myself, with data contributions possible according to https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md

But feel free to contact me via http://a.deveria.com/contact/ if you'd like to explain privately.
