### ISSUE TITLE
scroll-snap

### ISSUE THREAD

**Issue by mikestecker** [Fyrd/caniuse#1673]
Safari 9 adds new scroll-snap properties:

-webkit-scroll-snap-type
-webkit-scroll-snap-points-y
-webkit-scroll-snap-points-x
-webkit-scroll-snap-destination
-webkit-scroll-snap-coordinate

https://developer.apple.com/library/safari/releasenotes/General/WhatsNewInSafari/Articles/Safari_9.html#//apple_ref/doc/uid/TP40014305-CH9-SW21

**Comment by cvrebert** [comment]
i.e. http://dev.w3.org/csswg/css-snappoints/ (CSS Scroll Snap Points Module Level 1)

**Comment by Fyrd** [comment]
Already added at http://caniuse.com/#feat=css-snappoints . Are there particular search terms you were using that didn't result in the table showing up?
