### ISSUE TITLE
Misleading refer to permissive CC BY 4.0 license, having restrictive terms on data usage.

### ISSUE THREAD

**Issue by senotrusov** [Fyrd/caniuse#1676]
Hello!

In the readme file you state that data is available for use under a CC BY 4.0 license. The same statement can be found in the FAQ section on the http://caniuse.com/ website.

However, in the readme file, later in the same paragraph you provide the additional restrictions: "While usage of the data for alternative tools, visualizations, etc. is encouraged, it is not permitted to use it directly to create another browser support website".

Having that restriction you can't state that data is available for use under a CC BY 4.0 license alone.

Practically speaking having any additional restrictions to the widely known licences can be a serious barrier for use products in the corporate environments as such additions usually must be reviewed by corporate layers, and in many cases any non-widely known licence is banned from use.

In addition I would like to note that terminology such as "another browser support website" may have many possible interpretations.

Thank you.

**Comment by Fyrd** [comment]
Yes, I was recently informed of this by another source as well. That line has now been removed.

**Comment by senotrusov** [comment]
Thank you!
