### ISSUE TITLE
Include document.scrollingElement

### ISSUE THREAD

**Issue by nathanhammond** [Fyrd/caniuse#1677]
https://developer.mozilla.org/en-US/docs/Web/API/document/scrollingElement

**Comment by mikesherov** [comment]
+1

**Comment by Ugoku** [comment]
+1

**Comment by godchuanz** [comment]
+1

**Comment by Pudge601** [comment]
+1

**Comment by ahules** [comment]
+1

**Comment by mikesherov** [comment]
Github has reactions now. Please consider using them instead of a +1 comment to show your support, as they won't generate notifications (email and onsite). Thanks!

**Comment by cpplearner** [comment]
@mikesherov see #2408

**Comment by mikesherov** [comment]
I'm an idiot. Thanks!

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=document-scrollingelement
