### ISSUE TITLE
Conical gradients

### ISSUE THREAD

**Issue by mrbinky3000** [Fyrd/caniuse#1678]
Nt.

**Comment by Ugoku** [comment]
+1

**Comment by cvrebert** [comment]
What CSS property/function or spec does this refer to?

**Comment by Ugoku** [comment]
[This one](http://w3.org/TR/css4-images/#conic-gradients)
@leaverou did a talk on this last week and provided a [polyfill](http://leaverou.github.io/conic-gradient/)

I didn't know I wanted this until I saw what was possible with it!

**Comment by Serator** [comment]
+1

**Comment by LeaVerou** [comment]
+1

**Comment by Nantonos** [comment]
Yes it would be great to see support for this on caniuse as it develops

**Comment by yukulele** [comment]
+1

**Comment by xaddict** [comment]
+1

**Comment by justin-matthew** [comment]
@LeaVerou brought me here. Yes please +1

**Comment by codynguyen1116** [comment]
+1

**Comment by kosmar** [comment]
+1

**Comment by lancegliser** [comment]
+1

**Comment by Ugoku** [comment]
Chrome published an "intent to implement" yesterday, bringing this one step closer to being usable: 
https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/-z66SwKdklc/5t-NBchECQAJ

**Comment by Schweinepriester** [comment]
+1

Coming to Chrome: <https://twitter.com/leaverou/status/844999672997523456> => <https://groups.google.com/a/chromium.org/forum/m/#!msg/blink-dev/-z66SwKdklc/5t-NBchECQAJ>

**Comment by Ugoku** [comment]
[Available in Chrome behind a flag](https://twitter.com/anatudor/status/885151789741486082)

**Comment by dartess** [comment]
https://github.com/Fyrd/caniuse/pull/3614

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=css-conic-gradients
