### ISSUE TITLE
srcset+sizes in Chrome (iOS) is partial

### ISSUE THREAD

**Issue by isarmstrong** [Fyrd/caniuse#1679]
Re: https://github.com/Fyrd/caniuse/blob/master/features-json/srcset.json

Support appears to be partial, similar to Safari. The sizes parameter is ignored when using "w" conditions and only the lowest source is applied, which is problematic to say the least.

**Comment by Fyrd** [comment]
Chrome iOS uses the same engine as iOS Safari, so this is already covered.
