### ISSUE TITLE
Display flex set span as a document.activeElement in IE11

### ISSUE THREAD

**Issue by havenchyk** [Fyrd/caniuse#1682]
We've found an issue with flex in IE11. 

Span element has focus even without tabindex selected. For details please look at example. http://jsbin.com/numibokune/1/edit?html,css,js,console,output

I'm not sure if it's a best place to submit bug, but this issue can be added at least to the list of bugs.

Thanks.

**Comment by cvrebert** [comment]
You can file a bug with Microsoft at https://connect.microsoft.com/IE/Feedback

**Comment by havenchyk** [comment]
@cvrebert thanks, I'll definitely do it.

**Comment by havenchyk** [comment]
@cvrebert should I add it to the list of bugs for flexible layout model page?

**Comment by cvrebert** [comment]
> should I add it to the list of bugs for flexible layout model page?

I don't know what you're referring to.

**Comment by havenchyk** [comment]
I meant this page http://caniuse.com/#feat=flexbox

**Comment by cvrebert** [comment]
\*shrug* Can't really answer that since I'm not a maintainer.

**Comment by havenchyk** [comment]
@cvrebert ok, thanks

**Comment by Fyrd** [comment]
Added as known issue.
