### ISSUE TITLE
parseInt (with leading zeros, without radix parameter)

### ISSUE THREAD

**Issue by valioDOTch** [Fyrd/caniuse#1686]
It would be nice to have a compatibility chart about which JS engines interpret parseInt("010") as 10 and which interpret it (in the deprecated way) as 8.

[Mozilla states](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt) that
*"Many implementations have not adopted this behavior as of 2013, and because older browsers must be supported, always specify a radix."*

It remains unclear for me though which ones exhibit which behavior.

**Comment by claudepache** [comment]
See http://kangax.github.io/compat-table/es5/ row "parseInt() ignores leading zeros"

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=es5 (see numbered note 1)

**Comment by valioDOTch** [comment]
Great, thanks! :+1:

**Comment by valioDOTch** [comment]
I guess there's no easy way to make this findable via "parseInt", is there?
Because else I'm afraid hardly anyone will find this in case of doubt...
