### ISSUE TITLE
classList: add/remove multiple

### ISSUE THREAD

**Issue by Ugoku** [Fyrd/caniuse#1705]
[classList is already on caniuse](http://caniuse.com/#feat=classlist) but it's missing support data on a sub-feature: the ability to add/remove multiple classes in one go. This allows you to do:

    element.classList.add('foo', 'bar');

instead of

    element.classList.add('foo');
    element.classList.add('bar');

This was apparently added in [Firefox 26](https://bugzilla.mozilla.org/show_bug.cgi?id=814014#c48), [Chrome 28](http://html5doctor.com/the-classlist-api/#comment-37025) and [Opera 15](http://html5doctor.com/the-classlist-api/#comment-37412). The link to Chrome 28 mentions it does not work in Safari 6. I do not have access to a Safari browser to test if it works now in later versions.

From my own test, I can say that this works in IE11 and Edge. Emulating IE10 in IE11 does *not* work.

I would suggest this is added as footnote.

**Comment by cvrebert** [comment]
https://connect.microsoft.com/IE/Feedback/Details/920755 alleges that it doesn't work in IE11.

**Comment by cvrebert** [comment]
I can confirm that it doesn't work in Safari 6.0.5 but does in Safari 7.0.6.

**Comment by Ugoku** [comment]
Oh damn, this is one of those things where the same IE on different OS'es produces different results...

IE11 on Windows 10 works, IE11 on Windows 8.1 does not.

**Comment by mzgol** [comment]
> IE11 on Windows 10 works, IE11 on Windows 8.1 does not.

That would be scary but fortunately that's not true. It doesn't work in IE 11 both on Windows 10 (current build, 10240) & Windows 8.1 (yes, I've checked).

It does work in Edge, though.

**Comment by mzgol** [comment]
BTW, it seems it's correctly presented on the site currently at http://caniuse.com/#feat=classlist. Should this be closed as fixed?

**Comment by branneman** [comment]
I think this should stay open. At this moment it doesn't work in all IE10+11 versions. There's currently a note about a second parameter for the `toggle()` function. But this is something different.

![image](https://cloud.githubusercontent.com/assets/172579/9198220/deecacf8-403a-11e5-93cd-6764e00a92a1.png)

**Comment by mzgol** [comment]
@branneman It's listed under "known issues" but maybe it should be treated not as a bug but as partial support as you suggested.

**Comment by branneman** [comment]
I think it is partial support yes, and I think the best solution would be to add another note, stating that this browser does not support adding/removing multiple in one go.

It's clearly something different than the second parameter of the `toggle` method.

**Comment by Fyrd** [comment]
As suggested, have added this support as a note and updated the data accordingly.
