### ISSUE TITLE
CSS <angle> - particularly the "turn" unit

### ISSUE THREAD

**Issue by kensnyder** [Fyrd/caniuse#1709]
See MDN article [here](https://developer.mozilla.org/en-US/docs/Web/CSS/angle). It looks like currently all browsers support `deg`, `rad`, `grad` and some support `turn`.

**Comment by Ugoku** [comment]
+1

**Comment by TrySound** [comment]
+1

**Comment by itpastorn** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

<https://css-tricks.com/lets-look-50-interesting-css-properties-values/#angle>

**Comment by programmer5000-com** [comment]
+1

**Comment by fxmountain** [comment]
+1

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-css_types_angle & https://caniuse.com/#feat=mdn-css_types_angle_turn
