### ISSUE TITLE
Can I use ECDSA certificates?

### ISSUE THREAD

**Issue by thijzert** [Fyrd/caniuse#1716]
I know it may be a bit out of place here, but I'd really like to know what browsers I'd be leaving behind if i were to deploy an ECDSA-only HTTPS site.

A cursory glance in SSLLabs [[1](https://www.ssllabs.com/ssltest/clients.html)] indicates I may be leaving some old versions of IE behind. However, their browser repository is neither as complete nor as accessible as caniuse.com.

**Comment by coolaj86** [comment]
+1

**Comment by as-com** [comment]
+1

**Comment by bokeyy** [comment]
+1

**Comment by pornel** [comment]
Here's a test URL using this type of certificate:

https://ecdsa.scotthelme.co.uk/

**Comment by alexanderkjeldaas** [comment]
Also relevant to gauge the efficienty of seting up dual ssl in nginx backed by letsencrypt.

**Comment by Calico90** [comment]
+1

**Comment by Bisaloo** [comment]
+1

**Comment by thijzert** [comment]
Actually, in the two years since I submitted this issue I've learned that if it were up to browsers, everyone would switch to ECDSA yesterday. However, the bottleneck in this scenario are corporate firewalls that MitM (decrypt and re-encrypt) all network traffic. If those devices aren't aware of ECDSA, the connection fails regardless of browser version. This is much harder to measure, unfortunately. 

If we include it in this list one could get the false sense of security that an ECDSA-only site can be reached by ~98% of all browsers, but in reality, depending on your target audience, you're only available to e.g. ~70% of your customers.

**Comment by dylmye** [comment]
This issue has been open for a long time. I also want to add that TLS 1.2 isn't supported. Any update?

**Comment by wiml** [comment]
+1

**Comment by thijzert** [comment]
In this brave new world of corporate firewalls, middleboxes, and crappy anti-virus software, collecting usage and availability data on network-level stuff is moot for browsers.

In the same vein, you wouldn't ask "Does Firefox 43 support IPv6?" since that largely depends on your ISP. (And also on your host OS, its configuration, and all routers between you and the target server.)
