### ISSUE TITLE
Extra boxes in Firefox when hovering over cells with notes in the line of current browsers

### ISSUE THREAD

**Issue by dandv** [Fyrd/caniuse#1720]
At http://caniuse.com/#feat=clipboard for instance, in FF 39 - 41, hover over IE 11.

![caniuse box](https://cloud.githubusercontent.com/assets/33569/8613925/63aa66bc-2699-11e5-9dd8-47a8f38cb4e3.gif)

**Comment by Fyrd** [comment]
I'd previously written this off as a weird FF bug but have looked into it more and found a workaround. Should be fixed now!
