### ISSUE TITLE
The `autocapitalize` attribute of <input>s

### ISSUE THREAD

**Issue by cvrebert** [Fyrd/caniuse#1729]
- MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-autocapitalize
- Safari: https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/Attributes.html#//apple_ref/doc/uid/TP40008058-autocapitalize
- Chrome: https://www.chromestatus.com/feature/4529989986811904
- Spec proposal: https://github.com/mounirlamouri/html-autocapitalize/blob/master/proposal.md
- W3C bug: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28228

**Comment by cvrebert** [comment]
`autocapitalize` is now part of the HTML spec:
https://html.spec.whatwg.org/#dom-autocapitalize
(PR: https://github.com/whatwg/html/pull/3273)

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-html_elements_form_autocapitalize
