### ISSUE TITLE
"Accessible colors" link does not change colors of summary chart when search is empty

### ISSUE THREAD

**Issue by tschuy** [Fyrd/caniuse#1731]
Go to http://caniuse.com/ and search for a single space. Scroll down to the bottom of the page and hit "accessible colors". The colors of the summary chart stay the same even though everything else changes.

**Comment by Fyrd** [comment]
The summary table was removed recently due to bugginess, though it's re-enabled on the new beta site (https://beta.caniuse.com) where this issue does not exist.
