### ISSUE TITLE
Add support for control.labels 

### ISSUE THREAD

**Issue by lanzkron** [Fyrd/caniuse#1733]
http://www.w3.org/TR/html5/forms.html#the-label-element
Has the following :

> Labelable elements have a NodeList object associated with them that represents the list of label elements, in tree order, whose labeled control is the element in question. The labels IDL attribute of labelable elements, on getting, must return that NodeList object.

In other words for the following HTML:

```
  <label for="someId">A label</label> <input id="someId"/>
```

The following code should output evaluate as `true`.

```
 document.getElementById('someId').labels.length == 1
```

**Comment by xi** [comment]
MDN has [some information](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#Browser_compatibility) on that, but not much either.

**Comment by Schweinepriester** [comment]
<https://developer.mozilla.org/en-US/Firefox/Releases/56>:

> Implemented labels property for labelable form controls

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_htmlinputelement_labels
