### ISSUE TITLE
Apply opacity to browser blocks according to browser usage

### ISSUE THREAD

**Issue by jfgigand** [Fyrd/caniuse#1736]
The browser usage percentage is great, in the tooltip that appears when hovering a browser block in feature pages.

We could easily have a checkbox to apply on demand an opacity for each browser block in such a way that the volume of green or red tells immediately about the global browser usage for the feature.

The formula could be, for each block:
opacity = blockGlobalUsage / Math.max( allBlockGlobalUsage )

What do you think?

**Comment by Fyrd** [comment]
@jfgigand Interesting idea, though I feel this is largely covered already by the "usage relative" view mode...also I'd be worried that with opacity being too low it would be too hard to read.

**Comment by Fyrd** [comment]
Closing this since I feel "usage relative" mode already covers it.

**Comment by jfgigand** [comment]
Okay, thanks!


2015-07-24 4:32 GMT+02:00 Alexis Deveria <notifications@github.com>:
