### ISSUE TITLE
Typo in the embedded info box?

### ISSUE THREAD

**Issue by tieneguasa** [Fyrd/caniuse#1737]
Hello!
First of all, thank you for caniuse!

I don't know if this is really an issue, it is only a typo, but it appears in every embedded caniuse info box:
At the bottom of the info box there are always a couple of links:
"Compatibility table provided by Can I use... — Seperate page — About embedding "
I think, it should be "Separate page". Sorry, I'm absolutely not picky, but as I saw it I thought that if it really is a typo, you could want to know it.

Have a nice day and thank you again!
Alberto

**Comment by Fyrd** [comment]
Thanks for pointing that out, fixed now!
