### ISSUE TITLE
Support for line-break

### ISSUE THREAD

**Issue by tnguyen14** [Fyrd/caniuse#1738]
I find this property on MDN while trying to figure out how to support Japanese line-breaking of text 
https://developer.mozilla.org/en-US/docs/Web/CSS/line-break

I couldn't find it on the caniuse website, or on the issue tracker history.

**Comment by Schweinepriester** [comment]
+1

<https://webkit.org/blog/7432/release-notes-for-safari-technology-preview-25/>:

> Unprefixed `-webkit-line-break`

**Comment by YuCJ** [comment]
+1

**Comment by ian-pvd** [comment]
+1

https://www.w3.org/TR/css-text-3/#line-break-property

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_properties_line-break
