### ISSUE TITLE
Add :any-link pseudo-class

### ISSUE THREAD

**Issue by ghost** [Fyrd/caniuse#1742]
http://www.w3.org/TR/selectors4/#the-any-link-pseudo

**Comment by cvrebert** [comment]
Subfeature of #1058

**Comment by cvrebert** [comment]
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=843579

**Comment by cvrebert** [comment]
#2685 added data for this.

**Comment by Schweinepriester** [comment]
+1

[FF50](https://developer.mozilla.org/de/Firefox/Releases/50)

> The :any-link pseudo-class is now unprefixed

**Comment by Schweinepriester** [comment]
+2 :P

- <https://www.chromestatus.com/feature/5724922840088576>: Chrome 65+, Opera 52+, both on all platforms
- <https://developer.mozilla.org/en-US/docs/Web/CSS/:any-link#Browser_compatibility>: Seems like only Edge is missing

**Comment by scottmartin-ln** [comment]
+3, it's over a year since the last comment and 4 years since the original suggestion.

**Comment by iGadget73** [comment]
+100 

> Do it! Do it! 
(quoting Starsky & Hutch)

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=css-any-link
