### ISSUE TITLE
encodeURIComponent

### ISSUE THREAD

**Issue by wewoor** [Fyrd/caniuse#1743]
no this feature check

**Comment by Ugoku** [comment]
[MDN](https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) suggests this has been available since forever.

**Comment by cvrebert** [comment]
@Fyrd Given that this dates back to ES3, do you really want data for this?

**Comment by Fyrd** [comment]
Nope, closing this issue.
