### ISSUE TITLE
Incorrect known issue - svg data uri encoding

### ISSUE THREAD

**Issue by lukeapage** [Fyrd/caniuse#1746]
http://caniuse.com/#feat=datauri

Known issue - For SVG data URIs IE only supports base64 encoding.

This is not quite correct - see http://dbushell.com/demos/svg/utf8uri/test2.html

IE does support non-base64 encoded, but unlike other browsers it requires the characters to be uri encoded.

more detail: https://github.com/Compass/compass/issues/1460#issuecomment-65132746

**Comment by lukeapage** [comment]
evidence:
https://www.browserstack.com/screenshots/1e6e40274b91d9803014b2abb649588ad37642b5

**Comment by lukeapage** [comment]
Hrmm it seems that only chrome supports the URI not encoded.
Firefox and Opera both behave like IE
Probably someone needs to check against a spec and determine if chrome is more forgiving and then decide whether there shown be a known issue at all.

**Comment by Ugoku** [comment]
Which Opera version are you using? Version 12?

In Opera 32 (and Vivaldi) I'm seeing the same as in Chrome, as expected since they're both Chromium-based.

The [specification](http://tools.ietf.org/html/rfc2397) says:

> Without ";base64", the data (as a sequence of octets) is represented using ASCII encoding for octets inside the range of safe URL characters and using the standard %xx hex encoding of URLs for octets outside that range.

I'd say Chromium is wrong here.

**Comment by lukeapage** [comment]
yes it was 12 - see the links to browser stack.

So should the "known bug" be just removed ?

**Comment by Fyrd** [comment]
I've changed the bug description to be more accurate. Thanks for pointing this out!

**Comment by LeaVerou** [comment]
To add to the spec quote above, [this](http://tools.ietf.org/html/rfc3986#section-2.2) is where non-safe URL characters are defined:

 ```
reserved    = gen-delims / sub-delims

gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"

sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="
```

No other characters beyond these should need escaping.

(ht @nantonos for pointing to that spec — from memory!)
