### ISSUE TITLE
GA import excludes IE

### ISSUE THREAD

**Issue by selfthinker** [Fyrd/caniuse#1748]
I used the Google Analytics import feature a few times before and love it. But when I tried to import new statistics today, every version of IE (and some other browsers) are always excluded.
These are the first few entries for the excluded browsers in my case:

> **Browsers not included**
IE 11	11.66%
iOS Safari 8.4	7.86%
IE 9	1.9%
IE 10	1.24%
IE 8	1.2%
Safari 537.undefined	0.53%
...

Without IE in the statistics they are obviously not very usable. So I have to delete them again for the time being.

**Comment by Fyrd** [comment]
@selfthinker Thanks for letting me know about this! Should be fixed now, may need to reload the page. (I'll also work on include iOS 8.4 soon)
