### ISSUE TITLE
[general-site] Strange numbers for support ratio

### ISSUE THREAD

**Issue by zerkms** [Fyrd/caniuse#1749]
Let's take `box-shadow` for example.

    New Zealand 80.77%	+	0.1%	=	80.87%
    unprefixed: 80.59%

    Global 90.61%	+	0.12%	=	90.73%
    unprefixed: 90.3%

Which means that 19.13% of NZ internet users don't have support for it.

If I expand all the browsers and add their percentages together I cannot get a number even near to that:

0.01% (ie6) + 0.03% (ie7) + 0.75% (ie8) + 0.01% (ff3) + 0.14% (opera mini) = 0.94%

Which is far from 19.13%

What am I missing?

**Comment by Fyrd** [comment]
@zerkms Thanks for pointing this out. Looks like an error caused by me including iOS 8.4 to the version range, as a result all iOS Safari users were missing. If you reload the page it should update to the fixed regional data and the numbers should make a lot more sense.

**Comment by zerkms** [comment]
@Fyrd thanks

Now it's closer, I still cannot get the exact numbers though :-(

    New Zealand 97.73%	+	0.1%	=	97.83%

but

0.01% (ie6) + 0.03% (ie7) + 0.75% (ie8) + 0.01% (ff3) + 0.14% (opera mini) = 0.94%

while it is expected to be 2.17% (100% - 97.83%)

**Comment by Fyrd** [comment]
The remaining about is the total of untracked browsers. While I don't have a list of those per region, you can see the untracked global browsers at http://caniuse.com/usage-table

**Comment by zerkms** [comment]
Now that explains everything, thanks :-)
