### ISSUE TITLE
quic support or compatibility?

### ISSUE THREAD

**Issue by nathanbower** [Fyrd/caniuse#1752]
Which browsers are supporting quic (Quick UDP Internet Connections) and in what capacity?

It would be great if you could add a support matrix for quic.

Cheers,
Nathan

**Comment by Ugoku** [comment]
+1

**Comment by gregorybruneau** [comment]
+1

**Comment by xtian** [comment]
+1

**Comment by DaleGardner** [comment]
:+1:

**Comment by Zewy** [comment]
+1

**Comment by tomByrer** [comment]
Caddy (GoLang based webserver) supports QUIC
https://caddyserver.com/features

**Comment by mobiliodevelopment** [comment]
+1

Now LiteSpeed support QUIC

**Comment by anaibol** [comment]
+1

**Comment by vpavlov80** [comment]
+1

**Comment by stonelf** [comment]
+1

**Comment by xiongbao** [comment]
+1s

**Comment by vincentlws** [comment]
+1

**Comment by lcxfs1991** [comment]
+ 1

**Comment by ysbcc** [comment]
+1

**Comment by herbertliu** [comment]
+1

**Comment by xsbchen** [comment]
+1

**Comment by nankee** [comment]
+1

**Comment by dntzhang** [comment]
+1

**Comment by zhulin2609** [comment]
+1s

**Comment by homker** [comment]
+1

**Comment by miniflycn** [comment]
+1

**Comment by petergeng** [comment]
+1

**Comment by smilingdolphin** [comment]
+1

**Comment by Fyrd** [comment]
Does anyone know of a simple browser test for QUIC support?

**Comment by anaibol** [comment]
+1

**Comment by decal** [comment]
+1

**Comment by Majkl578** [comment]
> Does anyone know of a simple browser test for QUIC support?

1) Open Google Chrome.
2) Go to https.//google.com/

![QUIC](https://user-images.githubusercontent.com/144181/37493113-1d147a70-28a4-11e8-8433-693bc95d8d3d.png)

**Comment by Majkl578** [comment]
Tracker issue for Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1158011
Chrome Platform Status: https://www.chromestatus.com/feature/5338403830759424

**Comment by Fyrd** [comment]
@Majkl578 That helps a little, but I'd prefer some site/webpage I can point any arbitrary browser at and immediately see whether they have support or not.

**Comment by chrisblakley** [comment]
+1

**Comment by mnot** [comment]
Google QUIC, IETF QUIC, or both?

**Comment by djkrishnasty** [comment]
@Fyrd I was able to test this feature by looking at the protocol column under the network tab. The browsers that do support QUIC(such as chrome/opera) show the protocol as `http/2+quic/43` when the servers(youtube.com) support the protocol as well. Hope that helps.

**Comment by Majkl578** [comment]
> Google QUIC, IETF QUIC, or both?

HTTP/3?

**Comment by djkrishnasty** [comment]
@Majkl578 I thought this issue was specifically for Google's QUIC implementation given the date it was opened. There seems to be another issue(#4632) open for tracking HTTP/3 support.

**Comment by ProFire** [comment]
+1

**Comment by AnthonyLenglet** [comment]
With the addition of http/3 statistic, we might be able to close this ! 🎉

**Comment by Fyrd** [comment]
Yup, I think this is covered by https://caniuse.com/#feat=http3 now.
