### ISSUE TITLE
Server-Sent Events

### ISSUE THREAD

**Issue by fmoo** [Fyrd/caniuse#1753]
W3C recommendation: http://www.w3.org/TR/eventsource/
MDN: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events

**Comment by Fyrd** [comment]
It's on the site. You can find it searching for either [server-sent events](http://caniuse.com/#search=server-sent%20events) or [eventsource](http://caniuse.com/#search=eventsource) so I'm not quite sure how you missed it. :)

**Comment by fmoo** [comment]
Don't know how I missed that... Sorry for the distraction!
