### ISSUE TITLE
Include Microsoft Ajax extensions and other frameworks

### ISSUE THREAD

**Issue by cveld** [Fyrd/caniuse#1755]
It would be great if you could search for things like "Date.format" and then come to the discovery that it is included in the Microsoft Ajax JavaScript extensions. E.g. see https://msdn.microsoft.com/en-us/library/vstudio/bb384009(v=vs.100).aspx

**Comment by Fyrd** [comment]
I think it makes sense to include that as one of the links for a related feature, sure. Feel free to suggest or submit PRs for any for existing ones.
