### ISSUE TITLE
Split WebCrypto API

### ISSUE THREAD

**Issue by jedie** [Fyrd/caniuse#1759]
http://caniuse.com/#feat=cryptography is nice, but you can not see which method are supported and which not :(

This is IMHO a essential information here.

e.g. look at: "Web Cryptography API Live Table" -> https://diafygi.github.io/webcrypto-examples/

**Comment by Fyrd** [comment]
Thanks, I've added that table as a link. Caniuse is for general support overviews of technologies however, not the kind of specifics you're looking for. I'll be happy to link to such a resource though.

**Comment by jedie** [comment]
In the meantime, i created https://github.com/jedie/WebCrypto-compatibility to collect results of https://diafygi.github.io/webcrypto-examples/ with different browser/OS.
