### ISSUE TITLE
"defs" can not be found on caniuse

### ISSUE THREAD

**Issue by RogerAntonio** [Fyrd/caniuse#1765]
I'm trying to figure out why Firefox won't show my svg mask using text and paths.
It works fine on Chrome and Safari, but on Firefox it shows a black rectangle.
So far as I can see, I can't check the support for "defs" tags.

**Comment by Fyrd** [comment]
"defs" is supported in all SVG-supporting browsers, so is part of http://caniuse.com/#feat=svg

Not sure what issue it is you're seeing, but it's not lack of `defs` support.

**Comment by RogerAntonio** [comment]
Alright, thank you for clearing it up!
