### ISSUE TITLE
Be harsher on browsers that support a feature through a prefix

### ISSUE THREAD

**Issue by annevk** [Fyrd/caniuse#1768]
E.g., looking at http://caniuse.com/#feat=cryptography it doesn't seem correct that Safari appears all green, while you have to code towards it specifically. All green should mean supports the standard, period.

**Comment by Fyrd** [comment]
For developers it mostly matters that the functionality is there. Having to use a prefix is a minor inconvenience compared to partial support or a buggy implementation, so I feel simply having the prefix indicator is sufficient.
