### ISSUE TITLE
SVG stroke-alignment attribute

### ISSUE THREAD

**Issue by extempl** [Fyrd/caniuse#1772]
https://svgwg.org/svg2-draft/painting.html#SpecifyingStrokeAlignment

**Comment by valtlait** [comment]
+1

**Comment by Llbe** [comment]
+1

**Comment by Llbe** [comment]
It has been moved into a stroke module: https://svgwg.org/specs/strokes/#SpecifyingStrokeAlignment

**Comment by milkisevil** [comment]
:+1:

**Comment by erskelen** [comment]
:+1:

**Comment by codynguyen1116** [comment]
+1

**Comment by D1plo1d** [comment]
+1

**Comment by jzjzjzj** [comment]
:+1:

**Comment by jourdanritchey** [comment]
+1 https://www.w3.org/TR/svg-strokes/#SpecifyingStrokeAlignment

**Comment by spencercap** [comment]
+1 doesn't work. 
`<svg style="background: light-blue;" height="500" width="500">
  <circle cx="250" cy="250" r="250" stroke="black" stroke-width="10" stroke-alignment="inner" fill="none" />
</svg>`

tried Chrome & Safari

**Comment by millerized** [comment]
👍

**Comment by MilanJansenOGD** [comment]
:+1:

**Comment by Fyrd** [comment]
Have added a search result for this at http://caniuse.com/#search=stroke-align . Currently there don't appear to be any plans from any browsers to support this property, couldn't even find implementation bugs for them. If this changes I'll re-open this bug and add a proper support table.

**Comment by spencercap** [comment]
bummer .. ):
