### ISSUE TITLE
Individual transform properties

### ISSUE THREAD

**Issue by Ugoku** [Fyrd/caniuse#1776]
This allows you to do `.foo { rotate: 45deg; }` instead of `.foo { transform: rotate(45deg); }`

[Link to spec](https://drafts.csswg.org/css-transforms-2/#individual-transforms)
[Available in Chrome Canary now](https://twitter.com/simevidas/status/627956718098485248)

**Comment by valtlait** [comment]
+1

**Comment by Fyrd** [comment]
Available at:
https://caniuse.com/#feat=mdn-css_properties_rotate
https://caniuse.com/#feat=mdn-css_properties_scale
https://caniuse.com/#feat=mdn-css_properties_transform
