### ISSUE TITLE
Picture element will be supported on Edge

### ISSUE THREAD

**Issue by pictor** [Fyrd/caniuse#1779]
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6261271-picture-element?tracking_code=e9bf83c24b007e930955dfa6b299df3c

**Comment by dstorey** [comment]
Note: we have just announced that it is on the backlog (as with Web Components  beyond template), not when it will ship or that it is in active development.

**Comment by Fyrd** [comment]
Yeah, no point in keeping this issue open.
