### ISSUE TITLE
What is the support on clear: both?

### ISSUE THREAD

**Issue by mrcleanandfresh** [Fyrd/caniuse#1781]
I did a search for this on caniuse.com and it didn't return anything. What is the support on `clear: both` or `clearfix`es like those popularized by [Nicholas Gallagher](http://nicolasgallagher.com/micro-clearfix-hack/)?

**Comment by Fyrd** [comment]
If you follow the link you included you'll see it's supported in all currently browsers for some time already.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_properties_clear
