### ISSUE TITLE
Browser support for Focus Management function

### ISSUE THREAD

**Issue by ShubhamAdpushup** [Fyrd/caniuse#1782]
[`document.hasFocus`](https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus) is function to determine if the activeElement in the document has focus or not and is a part of [HTML5 spec](http://www.whatwg.org/specs/web-apps/current-work/#focus-management).

**Comment by slavafomin** [comment]
:+1:

**Comment by spade69** [comment]
it 's missed ?   It 's supported by IE4+ FireFox3+  Safari 4+  Chrome and Opera 8+
So we can say that you can use this feature everywhere...

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_document_hasfocus
