### ISSUE TITLE
MSE in Safari on iOS

### ISSUE THREAD

**Issue by NekR** [Fyrd/caniuse#1783]
caniuse.com says that iOS 8+ has Media Source Extensions, but I just checked it in iOS 8.1 emulator both for browser tab and Home Screen pinned sites and there is not ``MediaSource`` constructor. Is it available on real devices?

P.S. MDN also says that it's not available at iOS

**Comment by Fyrd** [comment]
@NekR You're absolutely right, my test confirms that too. Fixed now. Not sure how the mistake happened, but thanks for pointing it out!

**Comment by NekR** [comment]
@Fyrd :+1:
