### ISSUE TITLE
Please add MediaRecorder API

### ISSUE THREAD

**Issue by Mark-L6n** [Fyrd/caniuse#1784]
Could you add MediaRecorder?  As of this writing (8/7/15), Firefox supports it.  See [Mozilla](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder_API) and [W3C](http://www.w3.org/TR/mediastream-recording/).

**Comment by callmecavs** [comment]
+1

**Comment by unao** [comment]
+1

**Comment by harrislapiroff** [comment]
+1

**Comment by mattgarven** [comment]
+1

**Comment by varunFX** [comment]
+1

**Comment by Mido22** [comment]
+1

**Comment by pwnall** [comment]
+1

It seems like this may ship in Chrome M49: https://code.google.com/p/chromium/issues/detail?id=261321

**Comment by resting** [comment]
+1

**Comment by SteveALee** [comment]
+1
breaking news - https://developers.google.com/web/updates/2016/01/mediarecorder

**Comment by brion** [comment]
+1

**Comment by kbarkati** [comment]
+1

**Comment by jhuckaby** [comment]
+1

**Comment by Gayout** [comment]
+1

**Comment by christian-beckmann** [comment]
+1

**Comment by lopezdonaque** [comment]
+1

**Comment by rafaelsierra** [comment]
Chrome also supports it

https://www.chromestatus.com/feature/5929649028726784

+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=mediarecorder
