### ISSUE TITLE
Chrome Android status for Opus is wrong

### ISSUE THREAD

**Issue by sesse** [Fyrd/caniuse#1785]
Hi,

http://caniuse.com/#feat=opus claims that Chrome on Android does not support Opus. However, it works great for me; I can play Opus (in the Ogg container) through <audio> in a JavaScript tag, and I can play WebM video with Opus instead of Vorbis in the audio track. (However, Chromecast does not.) Could you please make a correction?

Chrome 44.0.2403.133, Android 5.1.1, Nexus 5.

**Comment by sesse** [comment]
Also, Firefox does not support Opus in WebM (you already have a note that Opera doesn't), as far as I can see. I haven't tried in Ogg.

**Comment by Fyrd** [comment]
@sesse Support means supported using the `audio` tag. Here's my test that fails in Chrome for Android (but works for Chrome Desktop):
http://tests.caniuse.com/?feat=opus

Have clarified the info a bit though and included your second comment to the known issues.

**Comment by sesse** [comment]
Heh, you're right. I really thought I tested this in Android earlier, but I see my test file now fails there, too. (Did it break, I wonder?)

Thanks for checking.
