### ISSUE TITLE
Add support information for the translate attribute

### ISSUE THREAD

**Issue by schalkneethling** [Fyrd/caniuse#1790]
HTML supports an attribute called `translate` but, there seems to be no support information for it. See:
http://www.w3.org/TR/html5/dom.html#the-translate-attribute

**Comment by Malvoz** [comment]
Browser support tests at:
https://w3c.github.io/i18n-tests/results/the-translate-attribute#detect

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-html_global_attributes_translate
