### ISSUE TITLE
Missing font-synthesis CSS 3 property

### ISSUE THREAD

**Issue by gund** [Fyrd/caniuse#1799]
There is no font-synthesis CSS 3 property.

Here is the information from MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/font-synthesis
CSSWG: https://drafts.csswg.org/css-fonts-3/#propdef-font-synthesis

Thanks!

**Comment by iDGS** [comment]
http://www.w3.org/TR/css-fonts-3/#propdef-font-synthesis

**Comment by Schweinepriester** [comment]
+1

<https://twitter.com/zachleat/status/808794986082947072>

**Comment by svgeesus** [comment]
Extended to cover faux smallcaps in CSS 4 Fonts
https://drafts.csswg.org/css-fonts-4/#propdef-font-synthesis

**Comment by maddesigns** [comment]
+1

**Comment by code-warrior** [comment]
👍

**Comment by bekahmcdonald** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_properties_font-synthesis
