### ISSUE TITLE
Column headers don't fit

### ISSUE THREAD

**Issue by dvorapa** [Fyrd/caniuse#1801]
1. go to the homepage
2. type "columns"
3. click "show all" at the first result
4. scroll down under top of the Opera's first version

My result:
![snimek obrazovky porizeny 2015-08-11 18 38 10](https://cloud.githubusercontent.com/assets/5113916/9203562/31994afc-4058-11e5-99b4-583c93a74967.png)

**Comment by Fyrd** [comment]
Thanks for reporting. Should be fixed now.
