### ISSUE TITLE
location.origin

### ISSUE THREAD

**Issue by zkochan** [Fyrd/caniuse#1803]
[http://www.w3schools.com/jsref/prop_loc_origin.asp](http://www.w3schools.com/jsref/prop_loc_origin.asp)

**Comment by cvrebert** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/URLUtils/origin#Browser_compatibility

**Comment by Schweinepriester** [comment]
+1

https://developer.mozilla.org/en-US/docs/Web/API/Window/location#Browser_compatibility

**Comment by billhannah** [comment]
+1

**Comment by tim-nz** [comment]
+1

**Comment by wmleidy** [comment]
+1

**Comment by thw0rted** [comment]
:+1:

**Comment by zaixia-damao** [comment]
double +1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_location_origin
