### ISSUE TITLE
draggable option

### ISSUE THREAD

**Issue by RensBloom** [Fyrd/caniuse#1807]
There is an option to disable dragging of elements in HTML5 (`draggable="false"`) as well as in CSS (`-webkit-user-drag: none;`). It would be great if these two could be added.

**Comment by wemyss** [comment]
+ 1

**Comment by codynguyen1116** [comment]
+1

**Comment by shankarsridhar** [comment]
+1

**Comment by martijn80** [comment]
+1

**Comment by PermApelsin** [comment]
+1

**Comment by dotjersh** [comment]
+1

**Comment by aubergine10** [comment]
### CSS 'user-drag' property

* `-webkit-user-drag`
* `-khtml-user-drag` (for older webkit browsers)

I don't have any info on hand as to which browsers or versions support those css properties. On caniuse, searching for the properties gives no results.

Permitted values:

* `auto` (default) - default browser behaviour
* `element` - entire element should be dragged, not just contents
* `none` - dragging is not permitted for both element and contents

### Draggable element property

Part of the drag and drop API, the modern approach is the `draggable` attribute on elements:

```html
  <div draggable="true">whole div will be dragged</div>
  <div draggable="false">you cannot drag this div or its text</div>
```

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable

Searching caniuse leads to a feature page: https://caniuse.com/#feat=dragndrop

It would be good if the component parts of the feature could get their own pages to promote collection of browser compatibility especially on mobile devices.

**Comment by samrith-s** [comment]
+1 to this as well.

**Comment by Fyrd** [comment]
Draggable attribute available at https://caniuse.com/#feat=mdn-html_global_attributes_draggable

**Comment by Fyrd** [comment]
`-webkit-user-drag` now available at https://caniuse.com/webkit-user-drag

**Comment by broseph-juce** [comment]
Hey, I'm new to github (literally signed up to post this) so apologies if commenting here like this is incorrect etiquette... 
I just thought you should be aware that I found the following info at stackoverflow, thought it might be of use:

  -webkit-user-drag: none;
  -khtml-user-drag: none;
  -moz-user-drag: none;
  -o-user-drag: none;
  user-drag: none;

[Original Post](
https://stackoverflow.com/questions/7439042/css-js-to-prevent-dragging-of-ghost-image)

**Comment by Fyrd** [comment]
@broseph-juce Thanks, I also ran into that in my research, however I couldn't find any evidence of browsers actually supporting the `-moz-`, `-o-` or the unprefixed version, so I think those were only ever included in the hopes that other browsers might adopt them (or just habit when writing prefixed properties). The `-khtml-` prefix is something of a legacy prefix that maps to `-webkit-`.
