### ISSUE TITLE
Geometry Interfaces Module Level 1

### ISSUE THREAD

**Issue by cvrebert** [Fyrd/caniuse#1811]
https://drafts.fxtf.org/geometry/

**Comment by cvrebert** [comment]
[WebKit bug 133916: Implement DOMPoint/DOMPointReadOnly](https://bugs.webkit.org/show_bug.cgi?id=133916)

**Comment by cvrebert** [comment]
[WebKit bug 110001: [meta] Implement DOMMatrix](https://bugs.webkit.org/show_bug.cgi?id=110001)

**Comment by cvrebert** [comment]
Chrome bug: https://code.google.com/p/chromium/issues/detail?id=388780

**Comment by Schweinepriester** [comment]
+1

<https://webkit.org/blog/7030/release-notes-for-safari-technology-preview-16/>:

> - Implemented `DOMPoint` and `DOMPointReadOnly`
> - Implemented `DOMRect` and `DOMRectReadOnly`

**Comment by cvrebert** [comment]
* https://developer.microsoft.com/en-us/microsoft-edge/platform/status/geometryinterfaces/ ("Under Consideration")

**Comment by Fyrd** [comment]
Available at:
https://caniuse.com/#feat=dommatrix
https://caniuse.com/#feat=mdn-api_dompoint
https://caniuse.com/#feat=mdn-api_dompointreadonly
etc
