### ISSUE TITLE
Add ObjectRTC (AKA WebRTC 1.1)

### ISSUE THREAD

**Issue by dstorey** [Fyrd/caniuse#1817]
Alternative more JS friendly proposal for RTC on the Web. Sometimes called WebRTC 1.1. Under development in MS Edge, and spec edited by Google and Microsoft.https://www.w3.org/community/ortc/

**Comment by dstorey** [comment]
This is now in a public Windows Insider Preview

**Comment by chaos986** [comment]
+1
