### ISSUE TITLE
Add Microsoft Edge preview

### ISSUE THREAD

**Issue by dstorey** [Fyrd/caniuse#1822]
A Windows Insider Preview (build 10525) went out today. http://blogs.windows.com/bloggingwindows/2015/08/18/announcing-windows-10-insider-preview-build-10525/

There is nothing new yet in the public release, except ORTC (which isn‘t included on CanIUse) but there will be in the future. It would be good to have a new entry after Edge to include the features when they go into preview.

**Comment by Fyrd** [comment]
Sounds good in theory, a bit tricky in practice. Will need to give it some thought to see how I'd need to handle updates, etc. Not having proper version numbers makes things more difficult too.

**Comment by dstorey** [comment]
We have build numbers, but that is of course hard to use ahead of time, as we don't know what the final release number will be.

**Comment by Fyrd** [comment]
Yeah. And those numbers are big and clunky and don't nicely fit inside cells like other version numbers. :(

**Comment by dstorey** [comment]
I’ve discussed with the team, and what we’re doing with revving the UA string between versions, and the best bet is to use Edge 12 for what exists already and Edge 13 for upcoming (preview), and so on. Technically it isn't the 12th and 13th version of Edge, but it is the engine revisions we really care about here. I’d still make Edge a new column though, as IE11 will eventually get buried otherwise.

**Comment by Fyrd** [comment]
That's great news! Should certainly make things easier, also when referencing the different versions. And yes, if this is the case I'll be happy to make Edge its own column.

**Comment by Ugoku** [comment]
> Technically it isn't the 12th and 13th version of Edge
Edge is version 20 right now. If the preview uses 21, why not just use that instead of 12/13? Skipping versions has been done in the past (Opera 12.1 -> 15)

**Comment by dstorey** [comment]
@Ugoku because it stands to reason that the app and platform could update independently. I'm not saying they will, but it is possible. The version in the UA string that you can check is the platform version number.

**Comment by Ugoku** [comment]
Ah, good point. My bad, I hadn't checked Edge's user agent.

**Comment by dstorey** [comment]
A preview release with a bunch of features went out today. I'll make a PR with the support update (if you don't get to it first) once there is an ability to add edge preview features.

**Comment by Fyrd** [comment]
@dstorey Okay, I'll try to get to that soon, maybe this weekend.

**Comment by Studio384** [comment]
@Ugoku The current preview in build 10532 still uses Edge 20(.10532), not 21.

**Comment by Fyrd** [comment]
This has been taken care of now with bfc406f2b2c5fa73980aa4ecea23dad9b6d57289 and 225e17fe0a7cf834075da5b88b6d73d7cecc6e75
