### ISSUE TITLE
Update SVG fragment identifiers

### ISSUE THREAD

**Issue by yisibl** [Fyrd/caniuse#1823]
[WebKit now support](https://bugs.webkit.org/show_bug.cgi?id=91790) SVG fragment in the CSS background image. 

Please update:

1. http://caniuse.com/#feat=svg-fragment
2. http://caniuse.com/#feat=svg-css

Opera 12.1 also not support.

Demo: 
* http://jsbin.com/?html,css,output
* http://jsfiddle.net/simurai/7GCGr

**Comment by Fyrd** [comment]
Thanks, updated. Didn't mention Opera 12.1 as virtually no one cares about supporting it anyway. Besides, it does support SVG fragments in background images when using a `view` element in the SVG.
