### ISSUE TITLE
thead & tfoot

### ISSUE THREAD

**Issue by kentonquatman** [Fyrd/caniuse#1825]
I wanted to check the browser support status for thead and tfoot, and I noticed they were missing from caniuse.

**Comment by cvrebert** [comment]
They're both part of HTML4; MDN's compatibility info suggests that they're universally supported.

**Comment by kentonquatman** [comment]
Thanks for following up with me. I did look into it further and saw that those elements were fully supported. I just noticed the Can I Use didn’t have data for those elements, so I thought I would suggest them.

Thanks again!
Kenton

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#search=thead & http://caniuse.com/#search=tfoot
