### ISSUE TITLE
Add 'nested media queries' 

### ISSUE THREAD

**Issue by ArwedSchmidt** [Fyrd/caniuse#1826]
CanIUse:

@media screen {
    @media (min-width: 768px) {
        // Minimal example.
    }
}

The above is a minimal example. Nesting becomes usefull when you deal with huge selectors like an 'retina/high-dpi'-query like

@media 	only screen and ( -webkit-min-device-pixel-ratio: 1.3 ),
	        only screen and (    min--moz-device-pixel-ratio: 1.3 ),
	        only screen and (      -o-min-device-pixel-ratio: 2.6/2 ), 
	        only screen and (         min-device-pixel-ratio: 1.3 ),
	        only screen and ( min-resolution: 124.8dpi ),
	        only screen and ( min-resolution: 1.3dppx ) {
	            // Here e.g. media queries for different breakpoints
}

See https://stackoverflow.com/questions/11746581/nesting-media-rules-in-css for further insights to this matter.

**Comment by bjb568** [comment]
+1

**Comment by cvrebert** [comment]
+1

**Comment by Ugoku** [comment]
+1

**Comment by lembitk** [comment]
+1

**Comment by cvrebert** [comment]
I think caniuse already has this data:
https://github.com/Fyrd/caniuse/blob/4929e46a422584022c64a079893b8d0b0ad3bab7/features-json/css-mediaqueries.json#L242

**Comment by cvrebert** [comment]
@Fyrd Seems like this can be closed? See previous comment.

**Comment by Fyrd** [comment]
Yeah, this is already covered.
