### ISSUE TITLE
marquee

### ISSUE THREAD

**Issue by iGadget73** [Fyrd/caniuse#1832]
Because the <marquee> tag is deprecated - but still usable - it would be good to have a list of browsers that still support it and how deeply it is supported.

**Comment by Ugoku** [comment]
Tested on Windows 10: Edge, Opera, Chrome, Firefox all still support it.

**Comment by yukulele** [comment]
Also on iOS

**Comment by iGadget73** [comment]
Not here but in the page itself..!

**Comment by Fyrd** [comment]
For now I have included this in the "obsolete elements" list at http://caniuse.com/#search=marquee

As authors are advised not to use these tags I'm not in a rush to include support data, but if eventually it gets enough votes I'll reconsider.

**Comment by yukulele** [comment]
caniuse is not shouldiuse!

**Comment by Fyrd** [comment]
Which is why I'm leaving this open. But considering the size of http://caniuse.com/issue-list/ it makes sense to prioritize features browsers are adding support for and that developers are interested in rather than ones that are losing support.

**Comment by cvrebert** [comment]
-1

**Comment by jabcreations** [comment]
HTML 5.2
https://www.w3.org/TR/html52/rendering.html#the-marquee-element-rendering

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-html_elements_marquee
