### ISSUE TITLE
getClientRects

### ISSUE THREAD

**Issue by dandv** [Fyrd/caniuse#1842]
Not documented at https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects

**Comment by NicolasNarvaez** [comment]
What happened to this?
Currently i can only trust in getBoundingClientRect :/

**Comment by fameriks** [comment]
No updates for almost 4 years, is this just lost?

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_element_getclientrects
