### ISSUE TITLE
Suggestion: Add the Firefox Developer browser

### ISSUE THREAD

**Issue by Maruchin** [Fyrd/caniuse#1845]
Hi! :) I'd love to see the Firefox developer browser on your site (seeing as the site is a tool meant for us developers). https://www.mozilla.org/en-US/firefox/developer/

I did a test on http://css3test.com/ and it scores 65% - Determined by passing 829 tests out of 1474 total for 336 features. Firefox and Chrome get a respective score of 55% and 51% css3 implementation.

**Comment by Hejprint** [comment]
+1

**Comment by Ugoku** [comment]
-1
Firefox developer edition is already on the site. Firefox (regular) is v40 right now. Firefox beta is 41, Firefox developer (aurora) is 42. Right?

**Comment by Maruchin** [comment]
Ah didn't know that. If that's the case then it doesn't matter no :)

**Comment by Maruchin** [comment]
http://css3test.com/ btw. Small typo in the url.

**Comment by Fyrd** [comment]
Yeah, this is covered by future Firefox versions. Closing the issue.
