### ISSUE TITLE
Add `onunload` event

### ISSUE THREAD

**Issue by dr-dimitru** [Fyrd/caniuse#1847]

**Comment by cvrebert** [comment]
https://developer.mozilla.org/en-US/docs/Web/Events/unload

**Comment by dr-dimitru** [comment]
@cvrebert I know, but I would like to have it on caniuse

**Comment by cvrebert** [comment]
I only added the link for convenience. It's not a comment on the merits of adding this or not.

**Comment by dr-dimitru** [comment]
@Fyrd also I've found what most events is not available for check on caniuse, maybe there is reason for this?

**Comment by Fyrd** [comment]
@dr-dimitru Standard events (click, change, etc) that have been supported since forever aren't on the site. Caniuse is intended for "newer" technologies with that have varied support.

**Comment by Fyrd** [comment]
Covered by https://caniuse.com/#feat=mdn-api_window_unload_event now
