### ISSUE TITLE
requestidlecallback

### ISSUE THREAD

**Issue by segdeha** [Fyrd/caniuse#1848]
https://developers.google.com/web/updates/2015/08/27/using-requestidlecallback

Chrome has added this new perf-related feature to Canary (see the article above). Thanks for your consideration!

**Comment by cvrebert** [comment]
https://www.chromestatus.com/feature/5572795866021888

**Comment by Ugoku** [comment]
+1

**Comment by frozonfreak** [comment]
+1

**Comment by zeh-workco** [comment]
+1

Editor's draft: https://w3c.github.io/requestidlecallback/

**Comment by JoostKiens** [comment]
:+1:

**Comment by jpmedley** [comment]
+1

**Comment by andremw-cit** [comment]
+1

**Comment by rajsite** [comment]
+1

**Comment by Ugoku** [comment]
Shim (not a polyfill) available here: https://gist.github.com/paullewis/55efe5d6f05434a96c36

**Comment by Nevraeka** [comment]
:+1: 

- [Mozilla Bug Status](https://bugzilla.mozilla.org/show_bug.cgi?id=1198381)

**Comment by julmot** [comment]
:+1:

**Comment by tomByrer** [comment]
+1
Added to Chrome 47:
https://youtu.be/0O0QwqSf6nA?list=PLNYkxOF6rcIDfz8XEA3loxY32tYh7CI3m&t=116

Another shim/polyfill:
https://github.com/aFarkas/requestIdleCallback

@Fyrd Would it be better if suggestions like this would be submitted as a PR, or do you prefer to green-flag them first?

**Comment by stavarengo** [comment]
+1

**Comment by nathanbower** [comment]
+1

**Comment by wolthers** [comment]
+1

**Comment by blq** [comment]
+1 
(I'd say this might be a quite underestimated feature, if used correctly)

**Comment by theruther4d** [comment]
👍

**Comment by ijse** [comment]
+1

**Comment by hkrutzer** [comment]
Firefox is adding this https://github.com/mozilla/platform-status/blob/master/features/request-idle-callback.md

**Comment by jrstanley** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=requestidlecallback
