### ISSUE TITLE
Add ES6 Generators

### ISSUE THREAD

**Issue by dstorey** [Fyrd/caniuse#1863]
Generators are one of the marquee ES6 features, and should be added

**Comment by Benimation** [comment]
+1

**Comment by lingtalfi** [comment]
+1

**Comment by AMorgaut** [comment]
+1

**Comment by kazzkiq** [comment]
How come this have just a few votes? Generators are one of the main features of [ECMAScript 2015 ](http://es6-features.org/#GeneratorFunctionDirectUse)specs and are around for quite a while now.

**Comment by timdol** [comment]
+1

**Comment by scottmas** [comment]
+1

**Comment by yukulele** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=es6-generators
