### ISSUE TITLE
Add ES6 modules

### ISSUE THREAD

**Issue by prettydiff** [Fyrd/caniuse#1869]
Please add ES6 modules.  I am sure support is likely red across the board, but it would be handy to spell that out as a major missing feature is the browsers.
- http://www.2ality.com/2014/09/es6-modules-final.html
- https://medium.com/ecmascript-2015/es6-modules-d5646d1b9a08

**Comment by cvrebert** [comment]
X-Ref: https://github.com/kangax/compat-table/issues/316

Seems like they haven't been fully shipped in any browser:
* http://bugzil.la/568953
* http://wkbug.com/147340
* https://code.google.com/p/v8/issues/detail?id=1569
* https://dev.modern.ie/platform/status/moduleses6/

**Comment by dstorey** [comment]
Modules are "medium" on our (Edge’s) priority list. So, we've not started development, but development is likely some time in future.

**Comment by hanfeisun** [comment]
+1 I searched ES6 module syntax on caniuse and found nothing...

**Comment by Benimation** [comment]
+1

**Comment by mc-suchecki** [comment]
+1

**Comment by prettydiff** [comment]
This is now underway for Edge: https://dev.windows.com/en-us/microsoft-edge/platform/status/moduleses6

I believe modules are already in V8, but hidden behind a flag until address resolution can be standardized. https://github.com/nodejs/node-v0.x-archive/wiki/ES6-%28a.k.a.-Harmony%29-Features-Implemented-in-V8-and-Available-in-Node

**Comment by markasoftware** [comment]
+1

**Comment by yukulele** [comment]
+1

**Comment by acbabis** [comment]
Edge has partial support behind a flag now: https://blogs.windows.com/msedgedev/2016/05/17/es6-modules-and-beyond/

**Comment by markasoftware** [comment]
o crap ie is ahead of the game

**Comment by dandart** [comment]
since Edge has it it's worth adding

**Comment by jpickwell** [comment]
+1 (+1 for Edge => mind blown)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export

For the specs:
* 6 (http://www.ecma-international.org/ecma-262/6.0/#sec-modules)
* next (https://tc39.github.io/ecma262/#sec-modules)

**Comment by nkronlage** [comment]
https://blog.whatwg.org/js-modules has some more bug ids:

* https://bugs.chromium.org/p/chromium/issues/detail?id=594639
* https://bugzilla.mozilla.org/show_bug.cgi?id=1240072
* https://bugs.webkit.org/show_bug.cgi?id=148897

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=es6-module
