### ISSUE TITLE
Add ES7/ES2016 async functions

### ISSUE THREAD

**Issue by dstorey** [Fyrd/caniuse#1871]
- One of the top trending features requests on Edge userVoice and one of the top JS features by votes too
- async/await is a very popular feature in other languages such as C#, and somewhat related to popular features such as Promises 
- An ES7 feature is already included here (object.observe)
- Implementation(s) have started

**Comment by domenic** [comment]
As a general note, I'd prefer to remove ES versions, especially future ones. Version numbers are not very meaningful, and it's not guaranteed that something will land in a specific version.

**Comment by tclzcja** [comment]
Just want to add that async function is already implemented in Microsoft Edge Windows Insider Preview Build 10532+. So this is a good time to add that entry in caniuse.

**Comment by claar** [comment]
Searched for "await" today and was surprised not to find it in this awesome site.

**Comment by NichUK** [comment]
+1

**Comment by Ugoku** [comment]
+1

Landed in Chrome Canary recently

**Comment by Schweinepriester** [comment]
+1

For the time being see <http://kangax.github.io/compat-table/es2016plus/#test-async_functions> as always, but I'd like to see this on caniuse, too.

**Comment by mdsharpe** [comment]
+1

**Comment by fundon** [comment]
https://developers.google.com/web/fundamentals/getting-started/primers/async-functions

**Comment by vith** [comment]
Firefox:

> Support for `async/await` has been added in the Nightly build from the 31st of October (bug [#1185106](https://bugzilla.mozilla.org/show_bug.cgi?id=1185106)). Great stuff!

via https://blog.nightly.mozilla.org/2016/11/01/async-await-support-in-firefox/

**Comment by michaellewiswilson** [comment]
+1

**Comment by mikaturk** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=async-functions
