### ISSUE TITLE
Add Subresource Integrity

### ISSUE THREAD

**Issue by Gaff** [Fyrd/caniuse#1881]
It has a w3c page and it's in some versions of Chrome apparently: https://w3c.github.io/webappsec/specs/subresourceintegrity/

**Comment by xtian** [comment]
+1

**Comment by cvrebert** [comment]
+

**Comment by mxstbr** [comment]
+1

**Comment by qgy18** [comment]
+1

**Comment by okor** [comment]
+1

**Comment by snadrus** [comment]
+ 1
From HTML5 Weekly:
GitHub Enables Subresource Integrity for CDN Assets NEWS 
Uses a new browser technology called Subresource Integrity.  
GITHUB ENGINEERING

**Comment by yukulele** [comment]
+1

**Comment by yukulele** [comment]
Article on Mozilla Hacks: https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/

**Comment by yukulele** [comment]
you can test it on your browser here:
https://srihash.org/

**Comment by connorshea** [comment]
+1

**Comment by connorshea** [comment]
[GitHub uses it](http://githubengineering.com/subresource-integrity/).

**Comment by brendanheywood** [comment]
+1

**Comment by arianitu** [comment]
:+1:

**Comment by arianitu** [comment]
+1

**Comment by vermorel** [comment]
+1

**Comment by jpmedley** [comment]
+1

**Comment by samarpanda** [comment]
:+1:

**Comment by M2Ys4U** [comment]
+1

**Comment by paulirish** [comment]
support right now… 

* [FF 43+](https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/)
* [Chrome 45+](https://www.chromestatus.com/features/6183089948590080) (and Opera 32+)

**Comment by yukulele** [comment]
https://github.com/Fyrd/caniuse/issues/1170

**Comment by MattiSG** [comment]
+1

Duplicate of #1170.

**Comment by thekondrashov** [comment]
+1

**Comment by Schweinepriester** [comment]
> Duplicate of #1170.

+1

**Comment by cvrebert** [comment]
https://dev.modern.ie/platform/status/subresourceintegrity/

**Comment by ApfelUser** [comment]
+1

**Comment by sandstrom** [comment]
+1

**Comment by Naddiseo** [comment]
+1

**Comment by Mictian** [comment]
+1

**Comment by branneman** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=subresource-integrity

**Comment by Gaff** [comment]
Yay - thanks!
