### ISSUE TITLE
Client Hints

### ISSUE THREAD

**Issue by seadour** [Fyrd/caniuse#1883]
https://github.com/igrigorik/http-client-hints

https://tools.ietf.org/html/draft-grigorik-http-client-hints-03

Available in Chrome 46 (beta)
Under consideration for Firefox and Edge

Firefox status: https://bugzilla.mozilla.org/show_bug.cgi?id=935216
Edge status: https://dev.modern.ie/platform/status/httpclienthints/

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=client-hints-dpr-width-viewport

**Comment by Malvoz** [comment]
@fyrd 
I couldn't find this feature searching for its HTTP header name, could you please add "Accept-CH"?
