### ISSUE TITLE
Viewport vw vh vm vmin vmax, known issues needs serious rethink

### ISSUE THREAD

**Issue by anyotherway** [Fyrd/caniuse#1886]
Whoever wrote Known Issues for all the viewport measures, does not know what a viewport is. 
http://caniuse.com/#search=vw... FREAK!
Viewport is a new player for CSS and HTML - it has lots of sharp hooks, be sensible.
Please have someone who has at least read W3 specs intelligently... rewrite.
Let's start with, what is VM showing compatibility stats for? Careful! Is caniuse doing C++ now?
Also, we'll get to the first 6 mistakes later, but lets jump right into detritus.
7 ...3D transforms unexpected behavior !!!
worked out with STU at cssplay.co.uk that any variation in expected behavior results from specific interaction of CSS elements due to "weighting" - only use compatible code INTELLIGENTLY and you are fine.
OK, you think we are just intelligently disagreeing? Read on and reconsider this concern later.
8 ...incorrectly consider 100vw to be the entire page !!!
100 units of any viewport measure for any element IS THE ENTIRE PHYSICAL VISIBLE SCREEN IN ANY DEVICE. 
READ W3 SPEC.
if there is a scrollbar in the display, there may be a pixel added for each interior scroll bar border
however, this defect vanishes when ONLY USE COMPATIBLE CODE, 
It is an odd defect that Apple and Microsoft have reduced from incrementing pixels to frozen pixels as they "engineer a final understanding". But this odd beaavior is rare.
Only expresses consistently in a page grid model, for properly coded data. 
This defect does increment style corruption around sloppy coding.
So let's get this rule straight.
PIXEL MEASURE IS NOT COMPATIBLE WITH FLUID PERCENTAGE VIEWPORT.
There is no such thing as (1px + 1% = fanciful-puhlease) clearly demonstrated across all physical device displays at once
1px+1%=NOTHING! because no two viewports are absolutely identical.
True, we have identified an interesting browser cache residue issue only for PAGE GRID.
A page grid is where a collection of nominal pages are tiled, each page with 100vm dimension.
Note: "vm" is a theoretical 100% vertical and 100% horizontal, filled viewport. 
VM IS NOT A VIEWPORT MEASURE - LOSE THE DREAM STATE WHILE YOU CODE!
9 ...zoomed !!!
As per W3 spec, viewport zooming "pans" in the devices browser viewport "across all devices".
Unknown to many (assumed and accepted ignorance) viewport is calculating 3 dimensions not 2 dimensions. Viewport is an active projection that includeS a "dead margin" in most older displays.
Panning or slight delayed animation of the zoom is factored in to allow adaptation of slow hardware
10 ...inside an iframe !!! THIS IS NOT AN ISSUE !!!
wtf iframe, will the stars stop shining because (iframe), good grief.
You can't invent a 3D physical device display hardware to somehow be two physical dimensions at once.
Viewport unit measures TOTAL AVALABLE PHYSICAL SCREEN DIMENSION - PROJECTION.
*DING!*
As for all the preceeding 6 confused 'issue' items, please review, test and assess intelligently. PLEASE READ W3 and find out what a viewport is and why pixel brains forcing pixels to style beside any viewport measure is NOT A GOOD IDEA. Apple and I tested properly coded viewport in IOS 6 on iPhone 5 in the Genius lab. It failed. Likewise, IE6 with Microsoft was a fail. Viewport is a Web 3.0 tool in its CSS and HTML variant. HEY PEOPLE, GIVE THANKS! We can now style viewport. THIS IS AMAZING. Style will not change your device onto a chicken burger when you are hungry! Viewport for engineers has been around since the very beginning. HOW CAN YOU GET IT SO WRONG?! [please fix)

**Comment by tabatkins** [comment]
Basically everything you have just said is wrong.  On top of that, you're being a real jerk about it.

Step away from the computer, review your life, and be kinder in the future.  Particularly when you're wrong.

**Comment by Fyrd** [comment]
There may be some part of this that makes some small amount of sense but as far as I can tell it's mostly yelling at developers for supposedly not understanding the spec. Considering @tabatkins' (a CSS spec writer himself) response I see no need to reconsider the current known issues for viewport units.
