### ISSUE TITLE
history.scrollRestoration

### ISSUE THREAD

**Issue by ghost** [Fyrd/caniuse#1889]
Unification of behavior,  and ability to control, the scroll restoration behavior by the browser when using the history API (to prevent undesired automatic page scrolls on `popstate`, etc).
- Just [adopted by Chrome](https://developers.google.com/web/updates/2015/09/history-api-scroll-restoration)
- [Specs](http://majido.github.io/scroll-restoration-proposal/history-based-api.html#web-idl)
- Easier to auto-test with `'scrollRestoration' in window.history`

**Comment by cvrebert** [comment]
https://www.chromestatus.com/features/5657284784947200

**Comment by Ugoku** [comment]
+1

**Comment by laukstein** [comment]
Chrome 46 (landed) https://code.google.com/p/chromium/issues/detail?id=477353
Firefox 46 (landed, will ship in April 2016) https://bugzilla.mozilla.org/show_bug.cgi?id=1155730
Webkit (in progress) https://bugs.webkit.org/show_bug.cgi?id=147782

**Comment by nkronlage** [comment]
Safari Tech Preview Release 26 added support for this property:

https://developer.apple.com/safari/technology-preview/release-notes/

**Comment by Schweinepriester** [comment]
+1

Support in Safari & iOS 11 per <https://webkit.org/blog/7956/new-webkit-features-in-safari-11/>:

> Support for `history.scrollRestoration` was added to give developers control over when to maintain scroll position when a user navigates back through browser history.

MDN: https://developer.mozilla.org/de/docs/Web/API/History#Browser_compatibility

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_history_scrollrestoration
