### ISSUE TITLE
SDCH

### ISSUE THREAD

**Issue by binoculars** [Fyrd/caniuse#1898]
Feature suggestion for Shared Dictionary Compression over HTTP (SDCH) aka "Sandwich" for VCDIFF / delta encoding (contrast with gzip), supported by Chrome.

### Links
- [HTTP compression Wikipedia Article](https://en.wikipedia.org/wiki/HTTP_compression)
- [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=641069)

**Comment by wub** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by frontenddeveloping** [comment]
+1

**Comment by ejohnsonTKTNET** [comment]
+1

**Comment by inscale** [comment]
+1

**Comment by soluml** [comment]
+1

**Comment by inscale** [comment]
[Firefox Bugzilla: Implement SDCH](https://bugzilla.mozilla.org/show_bug.cgi?id=641069)

[Chromium: Enable SDCH support over HTTPS](https://bugs.chromium.org/p/chromium/issues/detail?id=313716)

[Chromium codebase](https://chromium.googlesource.com/chromium/src/net/+/master/base/): see files prefixed "sdch_"
* https://chromium.googlesource.com/chromium/src/net/+/master/sdch/
* https://src.chromium.org/viewvc/chrome/trunk/src/net/base/sdch_manager.cc
* https://src.chromium.org/viewvc/chrome/trunk/src/net/base/sdch_manager_unittest.cc

[Chromium Open Issues](https://bugs.chromium.org/p/chromium/issues/list?q=component%3AInternals%3ENetwork%3ESDCH)

**Comment by inscale** [comment]
Easy way: search for "sdch" in the "Accept-Encoding" request header, like in "gzip, deflate, sdch, br".

Hard way: analyze all [related headers](https://lists.w3.org/Archives/Public/ietf-http-wg/2008JulSep/att-0441/Shared_Dictionary_Compression_over_HTTP.pdf)

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=sdch

**Comment by binoculars** [comment]
@Fyrd Awesome! Thank you :smile:

**Comment by inscale** [comment]
@Fyrd why did you guys remove it from the website?

**Comment by Fyrd** [comment]
@inscale Hmm, not sure what happened there, but it's back again now.

**Comment by inscale** [comment]
Thank you @Fyrd !
