### ISSUE TITLE
Support for <button> attributes

### ISSUE THREAD

**Issue by LeartS** [Fyrd/caniuse#1905]
It would be useful to add the compatibility table for the various form-related attributes of the button element: `formaction`, `formmethod`, `formenctype` etc. See [relevant MDN table](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Browser_compatibility).

**Comment by cvrebert** [comment]
Duplicate of #1562.
You should've found #1233 when searching the issues.
