### ISSUE TITLE
Add more CSS3 media query sub-types: e.g. 'orientation' and 'aspect-ratio'

### ISSUE THREAD

**Issue by hyrmedia** [Fyrd/caniuse#1911]
In particular I was looking for 'orientation' and 'aspect-ratio'.

See: http://www.w3.org/TR/css3-mediaqueries/

**Comment by lembitk** [comment]
+1

**Comment by kevinwheeler** [comment]
+1 aspect-ratio

**Comment by KyleRayMorgan** [comment]
+1 orientation

**Comment by YohannParis** [comment]
+1

**Comment by tureey** [comment]
+1 aspect-ratio

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_at-rules_media_orientation & https://caniuse.com/#feat=mdn-css_at-rules_media_aspect-ratio
