### ISSUE TITLE
support data:  CSS selectors :out-of-range, :in-range

### ISSUE THREAD

**Issue by Cutcopy** [Fyrd/caniuse#1922]
http://www.w3schools.com/cssref/sel_out-of-range.asp

W3 says it's not supported in any IE but I don't know if they've fixed it for Edge.

**Comment by cvrebert** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/%3Aout-of-range#Browser_compatibility
I just tested in Edge; it still has not been implemented.

**Comment by Cutcopy** [comment]
Sad, I could definitely image a lot of uses for it.

**Comment by cvrebert** [comment]
I couldn't find a feature request for it in https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer . You might consider filing one.

**Comment by dstorey** [comment]
https://dev.modern.ie/platform/status/cssrangepseudoclasses/

**Comment by lembitk** [comment]
+1

**Comment by andrelima** [comment]
It's in Edge now:
https://dev.modern.ie/platform/changelog/desktop/10547/

**Comment by cvrebert** [comment]
+1

**Comment by mattwojo** [comment]
Is this being added to caniuse?
 
It's now supported in Microsoft Edge browser, but not supported in IE8-11 https://msdn.microsoft.com/en-us/library/hh781508(v=vs.85).aspx 
https://html5test.com/compare/feature/form-selectors-in-range.html

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-in-out-of-range
