### ISSUE TITLE
Add support for initial-letter CSS property

### ISSUE THREAD

**Issue by hay** [Fyrd/caniuse#1926]
There's a W3C proposal for a new `initial-letter` property to introduce [proper dropcap support in CSS](https://drafts.csswg.org/css-inline/#initial-letter-styling).

Apparently this will be a feature of the [upcoming iOS 9 Safari](https://developer.apple.com/library/prerelease/ios/releasenotes/General/WhatsNewInSafari/Articles/Safari_9.html#//apple_ref/doc/uid/TP40014305-CH9-DontLinkElementID_3).

For those who think: but haven't we already got the `:first-letter` pseudoselector? You're right: but styling a dropcap also needs to take in account all the text surrounding the character, and that's notoriously tricky with regular CSS properties. This property will, for once and for all, allow 'proper' styling of dropcaps in CSS.

**Comment by Ugoku** [comment]
+1

**Comment by lembitk** [comment]
+1

**Comment by cbourgois** [comment]
+1

**Comment by Quinter** [comment]
+1

**Comment by tobireif** [comment]
It now is in Safari.

**Comment by connorshea** [comment]
+1

**Comment by jensimmons** [comment]
+1

**Comment by jawinn** [comment]
+1

**Comment by jensimmons** [comment]
I posted a demo of this property at http://labs.jensimmons.com/progressinglayout/example-initial-letter.html with a note about a current bug.

**Comment by hay** [comment]
@jensimmons i'm getting a 404 on that page :/

**Comment by jensimmons** [comment]
Sorry about that — I'm half-way through setting up a new site of layout examples, and moved things around after posting here. Durp! 

The initial-letter demo is here now: http://labs.jensimmons.com/examples/initial-letter.html

**Comment by dauwhe** [comment]
+1

**Comment by APerson241** [comment]
+1

**Comment by jensimmons** [comment]
Looks like the bug in Safari will be fixed in 9.1.1. It's fixed in the new Safari Technology Preview.

**Comment by achoukah** [comment]
I'm a sucker for things like this – sounds like a lovely idea. I'm sure there is a request somewhere here for :nth-letter(n) and possibly :range-letters(2.10)

**Comment by ryanwalters** [comment]
+1

**Comment by cadars** [comment]
+1

**Comment by julientaq** [comment]
+1

**Comment by cvrebert** [comment]
* https://webkit.org/status/#feature-initial-letter

**Comment by Schweinepriester** [comment]
+1

**Comment by maddesigns** [comment]
+1

**Comment by siiron** [comment]
+1

**Comment by jensimmons** [comment]
Some news about Initial Letter:
It is being added to Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1040714 
The fix for the Safari 9 bug shipped in Safari 10.

**Comment by lujanfernaud** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-initial-letter

**Comment by hay** [comment]
Thanks @Fyrd!
