### ISSUE TITLE
not proper version for microsoft edge 

### ISSUE THREAD

**Issue by chintan9** [Fyrd/caniuse#1928]
version is not matched yet 

![image](https://cloud.githubusercontent.com/assets/1642564/9800031/b83cbd0e-57d8-11e5-8231-6c0ec2956175.png)

![image](https://cloud.githubusercontent.com/assets/1642564/9800082/fd4164d6-57d8-11e5-9c90-cafe9c3efcf4.png)

**Comment by dstorey** [comment]
Version 2* in the about box is the app version. Version 12, 13, etc. in the UA string is the platform version. For a site like can i use, tracking the platform version makes more sense. The app version is not exposed in the UA string (web sites don't need to care about it). Mapping from platform to app version doesn't make sense either as one could change without the other.

**Comment by Fyrd** [comment]
Thanks for explaining, @dstorey.

I've just added added a note for Edge (click on the header in table view) that explains the logic too, hopefully that'll help avoid confusion.
