### ISSUE TITLE
Array.prototype.sort

### ISSUE THREAD

**Issue by bigtunacan** [Fyrd/caniuse#1941]
Array.prototype.sort https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort is missing from caniuse

**Comment by cvrebert** [comment]
It's basically universally supported per the "Browser compatibility" section of that MDN page. Also:
> [Good/preferred pull requests for new features meet the following criteria:](https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md#adding-a-feature)
> * Feature is not already widely supported (e.g. since IE6+, Firefox 2+, Chrome 1+ etc). This is because caniuse is intended to answer questions about mixed support, not to provide complete information on all web technologies.
