### ISSUE TITLE
Correction for CSS pointer-events and SVG on Safari 5.1

### ISSUE THREAD

**Issue by Llbe** [Fyrd/caniuse#1954]
Under Known Issues for CSS pointer-events it is stated: "Does not work on SVG elements in Safari 5.1 or Android <= 4.1". I have searched among issues here but I can't find the source of this info.

However, I have tested and pointer-events does work on SVG elements in Safari 5.1 (5.1.5).

Additionally https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events states it is supported since Safari 3.

**Comment by Fyrd** [comment]
Yeah, just wrote a specific test for this and can't reproduce either, so removing that issue (it was submitted anonymously without details, should have investigated, so my bad). Thanks!
