### ISSUE TITLE
Screen readers shares.

### ISSUE THREAD

**Issue by ytrezq** [Fyrd/caniuse#1955]
Some features in ʜᴛᴍʟ like ᴀʀɪᴀ are not directed to be supported by web‑browsers but by screen readers for blind people.
When I search if a feature is supported by screen readers, I see various lists. However this doesn’t help because I have no idea about the traffic coverage, even for the English language.

So would it be possible to get English screen reader coverage for the relevant features ? The first part would be to find statistics about current shares for the English language.

**Comment by dstorey** [comment]
by shares do you mean market share for screen readers? I'm not sure that is possible as you can't detect if a screen reader is present or not.

**Comment by ytrezq** [comment]
@dstorey : Yes I do. Remember detection isn’t the only way to get statistics *(I’m thinking to Audience measurement)*.

**Comment by ytrezq** [comment]
[Update](http://www.iheni.com/screen-reader-software-usage-shifts-on-desktop-and-mobile/)

**Comment by ytrezq** [comment]
�>

**Comment by Fyrd** [comment]
While I agree this would be useful information to have, it's another dimension that's unfortunately much harder to test and is therefore out of scope for caniuse. Will be happy to link to this information if any other site starts managing it.

**Comment by ytrezq** [comment]
@Fyrd : [better survey](http://webaim.org/projects/screenreadersurvey6/)
