### ISSUE TITLE
Correction proposal - MSE - Media Source Extensions

### ISSUE THREAD

**Issue by lyricalpolymath** [Fyrd/caniuse#1962]
Hello,
Thanks for the amazing tool :)

I've found there might be an error in http://caniuse.com/#feat=mediasource
as it points out that for Firefox it works only with the 
`media.mediasource.enabled` flag set to true

but  I know that **in my browser (Firefox 40) the flag was already set to true**
and it probably certainly is by default turned on in Firefox 41 (the latest version as of today 2015.09.22).

Looking backwards to find when they turned it on by default, I've found this information

the original [documentation for MediaSource](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource) suggests that MediaSource is available Since Firefox 25, turning on the `media.mediasource.enabled` flag
unfortunately the note doesn't state in which later version of Firefox they turned it on by default.

I'm guessing that the flag probably got enabled by default 

at some time AFTER Firefox 33
because the [release notes for Firefox 33](https://developer.mozilla.org/en-US/Firefox/Releases/33) suggest that
> `media.mediasource.enabled preference, enabled by default in Nightly and Aurora only`

I'm guessing that **probably it got definitively turned on WITH Firefox 37**
as this [release note for Firefox 37](https://www.mozilla.org/en-US/firefox/37.0/releasenotes/) suggest:
> Implemented a subset of the Media Source Extensions (MSE) API to allow native HTML5 playback on YouTube (Windows Vista or later only)

and **WITH Firefox 38**
as this [release note for Firefox 38]( https://www.mozilla.org/en-US/firefox/38.0/releasenotes/) suggests:
> Mac OS X: Implemented a subset of the Media Source Extensions (MSE) API to allow native HTML5 playback on YouTube

## Possible tests
- Many People here confirm that their flag is actually set to true, informing also the browser version
- We ask Mozzilla :) (Do you guys have any contacts?)

**Comment by dstorey** [comment]
It doesn't work for me in both CanIUse tests and HTML5Tests in Firefox 40 stable. Nor is the bug closed at https://bugzilla.mozilla.org/show_bug.cgi?id=778617

**Comment by lyricalpolymath** [comment]
@dstorey what doesn't work? 
I'm talking only about the fact that the note on turning on the media.mediasources.enabled flag isn't enough. 
The flags are already turned on in Firefox > 38 ... or at least they were already turned on in my Firefox 40.
the note should reflect that Firefox has released support for MSE ONLY to Youtube, so it won't work on your browser if you try to turn on the flag..also because the flag is already turned on

**Comment by Fyrd** [comment]
I added a note on this a few weeks ago, so closing this issue.
