### ISSUE TITLE
window.location.replace

### ISSUE THREAD

**Issue by ArtskydJ** [Fyrd/caniuse#1972]
[`window.location.replace()`](https://developer.mozilla.org/en-US/docs/Web/API/Location/replace)

I've heard that it works in IE9 and that it does not work in IE9.

http://caniuse.com/#search=window.location does not include `replace` in the list, maybe it needs to be updated?

**Comment by slix** [comment]
I support this. I need to support older versions of IE, and I can't find any sources for which IE versions support `replace`.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/mdn-api_location_replace (just tested in IE6 and works fine even there)
