### ISSUE TITLE
Add css pseudo-classes :read-only and :read-write browsers support

### ISSUE THREAD

**Issue by yodeco** [Fyrd/caniuse#1976]
Add css pseudo-classes :read-only and :read-write browsers support

**Comment by cvrebert** [comment]
https://dev.modern.ie/platform/status/cssmutabilitypseudoclasses/
https://bugzilla.mozilla.org/show_bug.cgi?id=312971

**Comment by cvrebert** [comment]
+1

**Comment by brookjordan** [comment]
What's the status of this?

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=css-read-only-write
