### ISSUE TITLE
why not suggests 'rotate3d' ?

### ISSUE THREAD

**Issue by zhuyingda** [Fyrd/caniuse#1978]
I met a problem about rotate3d when I use ios devices.It seems like the ios Safari doesn't support rotate3d. The rotate(2d) property runs well in ios devices.

**Comment by cvrebert** [comment]
http://result.webplatformstaging.org/gist/1ab11df04d00329d1622/f0d660c73d5a151e0a61d4edafe4d88d437d21b7 works fine on my iPhone...

**Comment by Fyrd** [comment]
Yeah, please submit a test case where it's not working, as most tests indicate that it does.

**Comment by Keksdose** [comment]
www.mediaschuette.de
Got the same problem on an iPhone 4, using many different browsers (Safari, Chrome Dolphin and Maxthon). Puffin does the job slowly.

**Comment by cvrebert** [comment]
@Keksdose Although there is some problem with the transition, `rotate3d` itself seems to work:
<img width="327" alt="trans" src="https://cloud.githubusercontent.com/assets/419884/12637684/01fffd3a-c54c-11e5-9802-6935b71dc771.png">

Example: http://jsbin.com/loxiyo/1/edit?html,css,output
