### ISSUE TITLE
enable mail notification when feature X is available for Y% of users

### ISSUE THREAD

**Issue by nschloe** [Fyrd/caniuse#1979]
Sometimes we're not making use of a feature because too many users have a browser that doesn't support that feature. caniuse.com is of course the place where we get the information.

I'd be great if there was some sort of service that allows anyone to sign up for a notification as soon as a particular feature is available to more than a specified amount of web users.

**Comment by jpmedley** [comment]
+1

**Comment by cvrebert** [comment]
Related to #869.

**Comment by Fyrd** [comment]
Yeah, close enough to @869 so marking as duplicate.
