### ISSUE TITLE
CanIUse embed

### ISSUE THREAD

**Issue by mkstix6** [Fyrd/caniuse#1991]
Somewhere, I've see someone easily embed caniuse chunks onto their page.
It's really nice and it's just a url.
But I can't find instructions on how to do it myself easily. Without the original example (I can't remember where I saw it) I can't work it out.

Could we have some instructions somewhere on caniuse.com.

**Comment by MartinMuzatko** [comment]
Would love to have this feature too.

**Comment by ireade** [comment]
Hey @mkstix6 @MartinMuzatko , I created one - [caniuse.bitsofco.de](http://caniuse.bitsofco.de)

**Comment by bfred-it** [comment]
It would be great to have an image version of that to use on GitHub
