### ISSUE TITLE
IndexedDB table doesn't mention it's not available in UIWebView

### ISSUE THREAD

**Issue by mzgol** [Fyrd/caniuse#1994]
The table at http://caniuse.com/#feat=indexeddb for iOS shows only a note about a buggy implementation but nothing about it missing from UIWebView and, as a consequence, Chrome for iOS.

I thought a separate column for UIWebView might be useful considering that there are significant differences but I see it's been rejected in #1578 so at least a note should be added.

**Comment by Fyrd** [comment]
Good point, actually wasn't aware of this. Has been fixed now, thanks!
