### ISSUE TITLE
Add Array.prototype.includes

### ISSUE THREAD

**Issue by jboolean** [Fyrd/caniuse#1995]

**Comment by cvrebert** [comment]
http://kangax.github.io/compat-table/es7/#Array.prototype.includes
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Browser_compatibility

**Comment by APerson241** [comment]
+1

**Comment by willmcenaney** [comment]
+1

**Comment by hovissimo** [comment]
While Github added a lovely thumbs-up voting button, it says explicitly in the projects documentation that '+1' comments should be used to support a feature.  Further, it's apparent that those comments are being automatically counted and shown here: http://caniuse.com/issue-list/

If you want to show your support for this issue, please use the old +1 comments.

**Comment by hovissimo** [comment]
+1

**Comment by hovissimo** [comment]
Also see #2071

**Comment by Nateowami** [comment]
+1

**Comment by ForsakenHarmony** [comment]
please?

**Comment by donnietron** [comment]
+1

**Comment by andrewjtait** [comment]
+1

**Comment by SeanArmstrong** [comment]
+1

**Comment by jelmerjellema** [comment]
+1

**Comment by skylarmt** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=array-includes
