### ISSUE TITLE
SVG 1.2

### ISSUE THREAD

**Issue by MagixInTheAir** [Fyrd/caniuse#2000]
SVG 1.2 support and statistics. pls. :D

**Comment by cvrebert** [comment]
Erm, you mean SVG ***Tiny*** 1.2? There's no plain SVG 1.2.
Apparently the major browsers only implement some bits and pieces from Tiny; see https://github.com/whatwg/html/issues/126

**Comment by MagixKiller** [comment]
Well, I read somewhere that is was impossible to have line-braks in SVG1.1 but it was possible in SVG1.2, I have no more experience with this. So I thought: "how supported is SVG 1.2?" and jumped to caniuse.com, found nothing, so opened an issue. I guess it's SVG Tiny 1.2, then :+1:

**Comment by dstorey** [comment]
I think 1.2 tiny was deprecated in favour of SVG2. Only Opera (I believe) implemented any substantial parts of 1.2 tiny (including the only named textArea that allowed line wrapping), and now Presto is dead (RIP) I'm not sure how useful this is? Probably should just break out the parts that are implemented on their own that are still on the standards track.

**Comment by Tigt** [comment]
SVG is so big that you could make your own caniuse for it alone. Definitely shouldn't list new features under a unified banner like that.

**Comment by Fyrd** [comment]
Closing in favor of SVG 2 features, tracked at #1143
