### ISSUE TITLE
font-display support

### ISSUE THREAD

**Issue by diego-martin** [Fyrd/caniuse#2001]
We should start adding this one.

**Comment by cvrebert** [comment]
https://www.chromestatus.com/feature/4799947908055040
Not currently implemented anywhere, but Chrome seems to be working on it.

**Comment by diego-martin** [comment]
I have been checking and I guess `font-loading` should replace this property.

**Comment by Schweinepriester** [comment]
+1

**Comment by meineartfeder** [comment]
+1

**Comment by Schweinepriester** [comment]
https://twitter.com/zachleat/status/671699868436455424

> The font loading solution we’ve been waiting for, `font-display`, is now available on Chrome Canary!

**Comment by brysongilbert** [comment]
+1

**Comment by intemperie** [comment]
+1

**Comment by geoffdavis92** [comment]
+1, especially since [this article](https://developers.google.com/web/updates/2016/02/font-display) has been distributed across several email lists.

**Comment by justincavery** [comment]
+1 video also available https://www.youtube.com/watch?v=PuGmlOe5wRk

**Comment by codynguyen1116** [comment]
+1

**Comment by calvinf** [comment]
`font-display` is a font-display descriptor and is a separate browser feature from the font loading API.

**Comment by tedw** [comment]
>`font-display` is currently behind the Experimental Web Platform Features flag in desktop Chrome 49, and is shipping in Opera and Opera for Android.

https://developers.google.com/web/updates/2016/02/font-display

**Comment by mastix** [comment]
font-display is getting more serious now - time to add it. :)

**Comment by nicothin** [comment]
+1

**Comment by animaux** [comment]
+1

**Comment by sivan** [comment]
+1

**Comment by rdazvd** [comment]
A new [CSS-Tricks article](https://css-tricks.com/font-display-masses/) came out, providing an overview of `font-display` and strategies to provide fallbacks through feature detection which make this property, to some extent, usable. It urges to be added.

**Comment by iGadget73** [comment]
+1

**Comment by wezz** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-font-rendering-controls

**Comment by geoffdavis92** [comment]
Thanks @Fyrd

**Comment by lingtalfi** [comment]
+1
