### ISSUE TITLE
Why doesn't Opera Mini version 11 appear in compatibility tables

### ISSUE THREAD

**Issue by markweston** [Fyrd/caniuse#2002]
Hi.

I've recently been developing for Opera Mini and noticed that the Can I use compatibility tables only show it for versions 5-8, but it is up to version 11 now as you can see from the links below:
https://itunes.apple.com/app/id363729560
http://www.opera.com/mobile/download/versions/

Why doesn't this version show in the compatibility tables?

Thanks

**Comment by Fyrd** [comment]
Yeah, I should update that number...except the version number is completely irrelevant to what it supports, since it'll always either use the in-built webview (on iPhone) or use the Opera 12.1-based server rendering in mini-mode or Opera Mini on other devices.

**Comment by evilebottnawi** [comment]
@Fyrd bump. wait for the update?

**Comment by Fyrd** [comment]
As per my previous comment, including a version number is unnecessary (and varies between platforms), so instead of "5-8" or anything ike that I have changed it to appear as "all".
