### ISSUE TITLE
upgrade-insecure-requests

### ISSUE THREAD

**Issue by lgarron** [Fyrd/caniuse#2013]
I would love to be able to track this feature.
http://www.w3.org/TR/upgrade-insecure-requests/

It has been supported since:
- [Chrome 43](https://www.chromestatus.com/feature/6534575509471232)
- [Opera 30](https://www.chromestatus.com/feature/6534575509471232)
- [Firefox 42](https://bugzilla.mozilla.org/show_bug.cgi?id=1139297)

**Comment by cvrebert** [comment]
caniuse already has this: http://caniuse.com/#feat=upgradeinsecurerequests

**Comment by Fyrd** [comment]
Yup, already available.

**Comment by lgarron** [comment]
Ooh. A search for http://caniuse.com/#search=upgrade-insecure-requests didn't work. Is it possible to add an alias/redirect?
