### ISSUE TITLE
Include webmail filters

### ISSUE THREAD

**Issue by kbrock** [Fyrd/caniuse#2017]
Hello,

Is it possible to let people know what tags and attributes are filtered out from the different web email services?

e.g.: Will this tag / attribute work when I mail this to a gmail user viewing this in webmail?

--Keenan

**Comment by Fyrd** [comment]
There are no plans to add this data to caniuse, but you can find quite a bit of info about this here:
https://www.campaignmonitor.com/css/

**Comment by kbrock** [comment]
@fryd thanks

**Comment by mattisherwood** [comment]
I do like the data that https://www.campaignmonitor.com/css/ gives, but love the way you interpret/deliver yours, especially with the visual charts combining it with the popularity of each browser version, so I was hoping that the info could perhaps be put through the same structure.
Not to worry though; you're doing a great job anyways!

**Comment by petermikitsh** [comment]
Yeah it would be great if all of the work that has been done on the caniuse interface could also be repurposed for email client support. The only real difference would be instead of browsers, you'd have email clients. I'd imagine the data structure would be similar.

**Comment by petermikitsh** [comment]
@Fyrd Is the web interface that consumes the data in this repository available?
