### ISSUE TITLE
Show Browser Release Date / Add age-aligned mode

### ISSUE THREAD

**Issue by NKjoep** [Fyrd/caniuse#202]
Hi,

Think about extending the UA info adding the release date.

Example, when you see feature X is not working with android 2.3 would be very very handy to quickly find when android 2.3 was public released.

What do you think?

----

Edit: Please share your love for this open issue, leave here your reactions or comments. We really want to see this feature online soon. Thanks!

**Comment by redeye86** [comment]
+1

**Comment by manngo** [comment]
+1

Agreed. Browser such as Firefox and Chrome have very short release cycles while Safari and IE/Edge have much longer cycles. As such, whether a feature was supported, say, two versions ago, has a different meaning for these browsers.

So for example, a feature which was implemented in versions, say, 1 year ago, would be be safer to use than features implemented 2 versions ago.

**Comment by AdamMerrifield** [comment]
+1

**Comment by peterdd** [comment]
@NKjoep: Could you please edit your first comment to engage peoples to vote for #202?

Vertical aligned for the current main web browsers for instance..

Versionitis is a serious disease of todays web browser manufacturers.

https://upload.wikimedia.org/wikipedia/commons/7/74/Timeline_of_web_browsers.svg

**Comment by NKjoep** [comment]
@peterdd I edited the first comment, I agree on *versionitis* being a serious illness nowadays.

**Comment by Fyrd** [comment]
Browser release dates are now included in the tooltip when you hover/tap on a version.

Have started working on the UI for a "release date relative mode".

**Comment by Fyrd** [comment]
New UI is now available! See http://caniuse.com/feed/157 for details.

**Comment by peterdd** [comment]
How about some horizontal year lines in the _date relative_ view?
