### ISSUE TITLE
Calc does not work properly in IE for generated content

### ISSUE THREAD

**Issue by aneves** [Fyrd/caniuse#2022]
Calculating the size of generated content from the related block's size is working incorrectly.
Try opening the [online sample](http://jsfiddle.net/mzp01tvu/) in IE11, and then in Firefox or Chrome.

Issue found and reported in:
http://stackoverflow.com/questions/31323915/internet-explorer-incorrectly-calculates-percentage-height-for-generated-content

Code to reproduce:

	<!DOCTYPE html>
	<html>
		<head>
			<style type="text/css">
				#borked {
					background: yellow;
					position: relative;
					height: 100%;
				}
				#borked~* {
					height: 100px;
				}
				#borked::before {
					content: "";
					position: absolute;
					top: 0;
					width: 100%;
					height: 100%;
					background-color: rgba(255, 0, 0, 0.3);
				}
			</style>
		</head>
		<body>
			<table>
				<tr><td id="borked">abc</td><td>def</td></tr>
			</table>
		</body>
		<script type="text/javascript">
			"use strict";
			var borked = document.getElementById("borked");
			var c = document.createElement("td");
			c.textContent = "(1st cell seems to be " + borked.clientHeight + "px tall)";
			borked.parentElement.appendChild(c);
		</script>
	</html>

**Comment by cvrebert** [comment]
Maybe file a bug with Microsoft via https://connect.microsoft.com/IE/Feedback/SubmitFeedback ?

**Comment by Fyrd** [comment]
Added under known issues.
