### ISSUE TITLE
Can I use google web fonts?

### ISSUE THREAD

**Issue by panfanky** [Fyrd/caniuse#2025]
Would be happy if you analysed this topic. There are reported issues of google fonts getting choppy on i.e. firefox

**Comment by cvrebert** [comment]
caniuse doesn't really cover product-specific info like that. It covers Web platform features; the relevant ones here presumably being font file formats and font APIs: http://caniuse.com/#search=font
Of course, if there's some specific browser bug in one of the features that Google Web Fonts utilizes, an entry in the "Known issues" tab for that feature would likely be appropriate.

**Comment by Fyrd** [comment]
Yeah, @cvrebert is right, no plans on supporting services like that.
