### ISSUE TITLE
Wrong info on iOS9 / Safari 9 support for font-feature-settings

### ISSUE THREAD

**Issue by swernerx** [Fyrd/caniuse#2028]
It seems like Safari 9 / iOS 9 got the support for "font-feature-settings". Prefixed only. This is currently wrong in the database as it seems. There does not seem to be any official announcement yet, but the property is recognized correctly.
![safari 9 font-feature-settings](https://cloud.githubusercontent.com/assets/145201/10430076/78ff3e4e-70fd-11e5-8016-ea9d20ecf1fb.png)

**Comment by swernerx** [comment]
Okay. Official info is that parsing support is there. But it's not actually supported (does not change anything). See also: https://twitter.com/Litherum/status/653577638963875841

**Comment by swernerx** [comment]
See also: http://trac.webkit.org/browser/trunk/Source/WebCore/platform/graphics/FontCascade.cpp

**Comment by litherum** [comment]
In nightly builds, full support exists and it is unprefixed.
