### ISSUE TITLE
SPDY/3 and SPDY/3.1

### ISSUE THREAD

**Issue by skynet** [Fyrd/caniuse#2029]
For: http://caniuse.com/#feat=spdy

SPDY/3, and SPDY/3.1 are incompatible protocols. Since you don't separate SPDY versions, the numbers of actual support of SPDY/3.1 across clients are lower. Check this conversation: 

https://disqus.com/home/discussion/nginxblog/nginx_open_source_reflecting_back_and_looking_ahead_03/#comment-2280878755

**Comment by Fyrd** [comment]
As SPDY is now deprecated and support is being removed from browsers, this doesn't seem worth updating anymore, so closing this issue.
