### ISSUE TITLE
Add other values of `user-select` property

### ISSUE THREAD

**Issue by nategreen** [Fyrd/caniuse#2031]
[From the spec](http://www.w3.org/TR/css-ui-4/#content-selection)...`user-select: none` is in there but there is no data for `user-select: all` or `user-select: contain`

Thanks!

**Comment by Fyrd** [comment]
Yeah, this was mostly 'cause `user-select` only recently started being spec'd, originally only support for "none" seemed to be consistent.

**Comment by prust** [comment]
👍

**Comment by Schweinepriester** [comment]
+1

Saw https://css-tricks.com/force-selection-text-block which has a demo for `user-select: all`: https://codepen.io/chriscoyier/pen/dXKxvv (doesn't work in Chrome 52, does work in 54/canary)

**Comment by konradk-sparkbit** [comment]
+1

**Comment by Fyrd** [comment]
These are now available via MDN BCD data.
