### ISSUE TITLE
Add HTMLInputElement.select()

### ISSUE THREAD

**Issue by jmm** [Fyrd/caniuse#2033]
The key thing to document is support for each state (`@type` value). For example, according to the [WHATWG HTML5 spec](https://html.spec.whatwg.org/multipage/forms.html#input-type-attr-summary) it applies to `type=number`, while according to the [W3C version](http://www.w3.org/TR/html5/forms.html#input-type-attr-summary) of the spec it doesn't. `type=number` is my suggestion of where to start if it's not comprehensive.

Thanks!

**Comment by cvrebert** [comment]
The non-Editor's-Draft W3C version is always outdated.
http://www.w3.org/html/wg/drafts/html/master/semantics.html#input-type-attr-summary matches WHATWG.

**Comment by jmm** [comment]
@cvrebert Ah, thank you! Wow, I thought I was confused before with WHATWG HTML5 and W3C HTML5. I've pretty much just been ignoring the W3C version in favor of WHATWG for years and didn't even realize W3C has an "HTML 5.1". It's a side issue obviously to documenting actual support, but that is great that they're in sync on that feature.

**Comment by Schweinepriester** [comment]
The basic thing is available via MDN now:
- https://caniuse.com/mdn-api_htmlinputelement_select
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/select

Probably doesn't cover different `type` values though.

**Comment by GPHemsley** [comment]
The spec definitions of [`HTMLInputElement.select()`](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#dom-textarea/input-select) and [`<input>`](https://html.spec.whatwg.org/multipage/input.html#the-input-element) combine to determine whether text selection [applies](https://html.spec.whatwg.org/multipage/input.html#concept-input-apply).

There shouldn't be a need to document support for their intersection separately.
