### ISSUE TITLE
Support for Web Audio API in Safari should be marked 'partial'

### ISSUE THREAD

**Issue by fedhat** [Fyrd/caniuse#2035]
Safari 8 and 9 offer only partial support for the Web Audio API (mainly just the playback portions). If you search for 'Web Audio API', Safari 8 and 9 incorrectly have green boxes, with small yellow minus signs indicating that it requires a 'webkit' prefix. The whole box should be yellow because Safari 8 and 9 don't support large portions of the Web Audio API, including getUserMedia() which is necessary to record audio.

**Comment by hebbet** [comment]
made a pr #2036

**Comment by Fyrd** [comment]
`getUserMedia()` is not part of the Web Audio API (it's mentioned in the specification, but not defined there) and is already covered at http://caniuse.com/#feat=stream

Can you be more specific on what (other) parts aren't supported?

**Comment by fedhat** [comment]
I'm not sure I see the distinction you're making. You're correct that there is a separate spec named Media Capture and Streams, which covers getUserMedia() and the related MediaStream interface, but the working draft of the Web Audio API states:

The API supports these primary features:
	[....]
	* Processing live audio input using a MediaStream from getUserMedia().
	[....]

The way that you obtain a MediaStream object is via getUserMedia(). Are you saying that because getUserMedia() and MediaStream are covered in a separate spec -- which is not supported by any version of Safari -- a search for Web Audio API on caniuse.com should report that the API is fully supported in Safari? I don't think it's reasonable to expect users of caniuse.com to have a mental map of which specs cover which parts of the API and know to search for 'getUserMedia' -- which correctly states that it's not supported on Safari -- or 'MediaStream' which returns 0 results.

I'm just suggesting that when users search for "Web Audio API" the Safari column contain yellow boxes rather than green boxes, since getUserMedia() and MediaStream are referenced by the Web Audio API, and thus considered part of the Web Audio API but are not supported in Safari, though other parts of the API are support.

**Comment by Fyrd** [comment]
The specification supports processing from MediaStreams, but that's just one possible input. I don't get the impression that support for MediaStreams is required to support the Web Audio API. As I recall, the Web Audio API was originally released before getUserMedia, as you can manipulate audio without requiring the ability to get it from a microphone or webcam feed.

Also, looking at the [Media Capture and Streams](http://www.w3.org/TR/mediacapture-streams/) spec the web audio API is referenced as an API compatible with Web Audio, it does not state that it falls under it.

However, I agree that a number of users of the Web Audio API may also expect it to include support for streams as input, so I've just added a note to clarify that. I've also added MediaStream as a searchable keyword for it. I believe that should be sufficient, so with that I'm closing this issue.
