### ISSUE TITLE
window.addListener()

### ISSUE THREAD

**Issue by BlackMagic** [Fyrd/caniuse#2037]
Should this be covered? It is used with window.matchMedia(), which is covered.

**Comment by Fyrd** [comment]
I assume this should be `MediaQueryList.addListener()`, then?

**Comment by BlackMagic** [comment]
I'm not sure. I'm not an expert in this area. This source 
<https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryListListener> doesn't 
refer to it specifically, and is more than vague about browser support 
for |MediaQueryList|.

addListener() is associated with Window.matchMedia(), described here 
<https://developer.mozilla.org/en/docs/Web/API/Window/matchMedia>. The 
way I use addListener() is as follows:

var mql = window.matchMedia('(min-width : 990px)');

mql.addListener(/callback_function_name/);

matchMedia appears on caniuse <http://caniuse.com/#search=matchMedia>, 
but addListener doesn't. Since addListener is an important element in 
setting up media queries in Javascript I though it should be mentioned. 
It works in any browser that supports matchMedia. I have used it to 
build a lightweight Javascript media query manager.

**Comment by BlackMagic** [comment]
While I think of it, iOS9 has dropped support for flexbox. canIuse shows 
flexbox as being supported on iOS9.

Flexbox is supported on iOS8 and OSX, but not on iOS9. I've reported the 
issue to Apple in Australia.

I'm attaching 2 screenshots taken on an iPhone to illustrate the problem.

**Comment by BlackMagic** [comment]
Another discovery I made today is that Opera Mini supports the JavaScript matchMedia API, including event listeners, contrary to what appears on the caniuse website at <http://caniuse.com/#search=matchMedia>

I tested Opera Mini and Opera Mini beta 5.2 on an android tablet against a website that uses matchMedia and it worked fine.

**Comment by adamschwartz** [comment]
👍

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_mediaquerylist_addlistener
