### ISSUE TITLE
The "revert" keyword value from CSS4

### ISSUE THREAD

**Issue by cvrebert** [Fyrd/caniuse#2039]
http://www.w3.org/TR/css-cascade-4/#valdef-all-revert
https://drafts.csswg.org/css-cascade-4/#default

It's been implemented in WebKit: https://bugs.webkit.org/show_bug.cgi?id=149702
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1215878
MS Edge UserVoice: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/10469316-the-css4-revert-value

**Comment by Schweinepriester** [comment]
+1
