### ISSUE TITLE
Add Javascript Pointer Events

### ISSUE THREAD

**Issue by skibulk** [Fyrd/caniuse#2040]
Not to be confused with CSS "point-events". W3.org Recommendation: http://www.w3.org/TR/pointerevents/

This feature has already been implemented in Microsoft's Edge Browser. Both Chrome and Firefox have confirmed that they will also implement Pointer Events.

**Comment by Llbe** [comment]
+1

**Comment by Fyrd** [comment]
Already available at http://caniuse.com/#feat=pointer

**Comment by appsforartists** [comment]
What does the search key off of?  `pointerevent` [pulls up](http://caniuse.com/#search=pointerevent) "CSS pointer-events," but not DOM PointerEvents.
