### ISSUE TITLE
window.location.reload()

### ISSUE THREAD

**Issue by hyperhtml** [Fyrd/caniuse#2046]
It is not supported in IE9 and below:
https://social.msdn.microsoft.com/Forums/ie/en-US/de9c5845-5fac-4fda-9b2d-2b435e805abd/windowlocationreloadtrue-is-not-working-in-ie-9?forum=ieextensiondevelopment

Supported by all other modern browsers.

**Comment by Llbe** [comment]
It is supported in IE9. https://developer.mozilla.org/en-US/docs/Web/API/Location/reload
