### ISSUE TITLE
Sub-resource integrity

### ISSUE THREAD

**Issue by gavinwahl** [Fyrd/caniuse#2048]
<http://www.w3.org/TR/SRI/>

Supported by Chrome 45: <https://www.chromestatus.com/feature/6183089948590080> and Firefox 43: <https://developer.mozilla.org/en-US/Firefox/Releases/43>

**Comment by cvrebert** [comment]
Duplicate of #1881.

**Comment by gavinwahl** [comment]
Man, github search must not work at all
