### ISSUE TITLE
Missing "Infinity" JS value

### ISSUE THREAD

**Issue by MathRobin** [Fyrd/caniuse#2051]
title — Infinity
description — Infinity is standard value from JS 1.3 but can't find it on "Can i use"
spec — https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Infinity
status — rec - W3C Recommendation
categories — JS API
stats — a - (A)lmost supported (aka Partial support)
notes — Don't know if old IE or others support it
keywords — Math, standard
shown — false

**Comment by Fyrd** [comment]
Now has search result:
http://caniuse.com/#search=infinity
