### ISSUE TITLE
DNS-based Authentication of Named Entities (DANE)

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#2055]
Add support for DNS-based Authentication of Named Entities (DANE)?
- https://en.wikipedia.org/wiki/Domain_Name_System_Security_Extensions#DANE_Working_Group
- https://en.wikipedia.org/wiki/DNS-based_Authentication_of_Named_Entities

**Comment by xtian** [comment]
+1

**Comment by Calico90** [comment]
+1

**Comment by dannytech** [comment]
+1

**Comment by EpicWumbo2048** [comment]
+1

**Comment by mikeburroughs** [comment]
+1

**Comment by Giraffe1966** [comment]
+1

**Comment by lookas2001** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=dnssec
