### ISSUE TITLE
document.elementsFromPoint

### ISSUE THREAD

**Issue by AndrewRayCode** [Fyrd/caniuse#2064]
Looks like it's pretty dicey:

https://developer.mozilla.org/en-US/docs/Web/API/Document/elementsFromPoint

vs singular is supported https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint

**Comment by ESandman** [comment]
+1

**Comment by Cnordbo** [comment]
+1

**Comment by albell** [comment]
+1 There's a real need for proper, accurate info here. MDN currently says Chrome 43+, FF 46+ IE 10+, Opera ?, Safari no support.

E.g. Hard to believe Opera doesn't support it and Chrome does.

**Comment by orangesandlemons** [comment]
+1

**Comment by nerochiaro** [comment]
+1

**Comment by venkatvb** [comment]
+1

**Comment by crucifyer** [comment]
+1

**Comment by lukeapage** [comment]
+1 for instance mdn doesn't say when the non prefixed version landed in IE/edge

**Comment by david-treblig** [comment]
+1 Needed that today and couldn't find browser support anywhere. Thanks!

**Comment by WearyMonkey** [comment]
+1

**Comment by BrendanAnnable** [comment]
+1

**Comment by MCTaylor17** [comment]
I too would like to see this added.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_documentorshadowroot_elementsfrompoint
