### ISSUE TITLE
Status of ES6 Proxy in Blink doesn't match Chrome Platform Status

### ISSUE THREAD

**Issue by cvrebert** [Fyrd/caniuse#2068]
Per https://www.chromestatus.com/feature/4811188005240832 , it's behind a flag, but this isn't noted in the chart for http://caniuse.com/#feat=proxy

**Comment by Fyrd** [comment]
Looks like they removed it again (according to https://github.com/tvcutsem/harmony-reflect and my own test), but have updated the data to reflect the versions that did have support behind a flag. Thanks!
