### ISSUE TITLE
Support for Multiline Strings

### ISSUE THREAD

**Issue by Lonniebiz** [Fyrd/caniuse#2070]
Example:

var text = `
This
Is
A
Multiline
String
`;

http://www.ecma-international.org/ecma-262/6.0/#sec-template-literal-lexical-components

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings

https://developers.google.com/web/updates/2015/01/ES6-Template-Strings?hl=en#multiline-strings

**Comment by Ugoku** [comment]
+1

**Comment by ewoerner** [comment]
This seems to be a duplicate of already implemented #2193?

**Comment by Lonniebiz** [comment]
#2070 (this issue) was submitted on 11-04-2015. #2193 is a duplicate that was later submitted on 01-04-2016. Call me petty and I'll call you Betty!

**Comment by Fyrd** [comment]
Added "multiline" as search keyword for https://caniuse.com/#feat=template-literals
