### ISSUE TITLE
Add String.prototype.includes()

### ISSUE THREAD

**Issue by MatayoshiMariano** [Fyrd/caniuse#2071]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes

**Comment by williamboman** [comment]
+1

**Comment by jsturgis** [comment]
+1

**Comment by APerson241** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

For the time being also viewable here:

- https://kangax.github.io/compat-table/es6/#test-String.prototype_methods_String.prototype.includes
- http://www.w3schools.com/jsref/jsref_includes.asp

**Comment by wmill** [comment]
+1

**Comment by jeffmcmahan** [comment]
Just noticed caniuse does link to https://kangax.github.io/compat-table/es6/#test-String.prototype_methods_String.prototype.includes, but it provides said link in documenting the non-existent "String#contains" and "Array#contains" methods.

See: http://caniuse.com/#search=.contains

**Comment by hovissimo** [comment]
While Github added a lovely thumbs-up voting button, it says explicitly in the projects documentation that '+1' comments should be used to support a feature. Further, it's apparent that those comments are being automatically counted and shown here: http://caniuse.com/issue-list/

If you want to show your support for this issue, please use the old +1 comments.

**Comment by hovissimo** [comment]
+1

**Comment by cherukumilli** [comment]
+1

**Comment by ryb73** [comment]
+1

**Comment by Nateowami** [comment]
+1

**Comment by Offirmo** [comment]
+1

**Comment by andyfry01** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=es6-string-includes
