### ISSUE TITLE
Array.prototype.splice() is missing from site

### ISSUE THREAD

**Issue by ruvengam** [Fyrd/caniuse#2072]
You are missing Array.prototype.splice() method in the web site.
This is very common method in JavaScript.

**Comment by cvrebert** [comment]
> This is very common method in JavaScript.

Hence why it's supported "universally": https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice#Browser_compatibility

**Comment by Ugoku** [comment]
-1
This is available everywhere as cvrebert said.

**Comment by Fyrd** [comment]
Now has search result:
http://caniuse.com/#search=splice
