### ISSUE TITLE
Add in Range.createContextualFragment

### ISSUE THREAD

**Issue by rgbkrk** [Fyrd/caniuse#2073]
[Range.createContextualFragment on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Range/createContextualFragment#Browser_compatibility)

**Comment by rgbkrk** [comment]
Perhaps this is covered in part by [dom-range](http://caniuse.com/#feat=dom-range)?

**Comment by itsrachelfish** [comment]
:+1:

**Comment by adjenks** [comment]
👍

**Comment by amychurchwell** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-api_range_createcontextualfragment
