### ISSUE TITLE
Web NFC API

### ISSUE THREAD

**Issue by Drizzt321** [Fyrd/caniuse#2085]
Currently Web NFC is a draft API. Firefox OS 2.0 (https://developer.mozilla.org/en-US/docs/Web/API/NFC_API/Using_the_NFC_API) supports this, and Chrome platform intends to support this (https://www.chromestatus.com/feature/6261030015467520). You should add data support for which browsers support this.

http://www.w3.org/TR/2014/WD-nfc-20140114/

**Comment by Ugoku** [comment]
+1

**Comment by cvrebert** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/webnfcapi/

**Comment by jrstanley** [comment]
+1

**Comment by ClintonGallagher** [comment]
2017-06-06 Web NFC is not recognized at caniuse.com. I entered a new issue here and an email response informed me that Web NFC API is already being discussed here in this thread. 

this week the 2017 Apple Web Developer Conference announced iPhone 7 models will no longer be crippled and will support the use of NFC tags and other forms of the informally named "discovery mode" such as exchanging data between two NFC-enabled devices.

NXP NTAG 413 DNA is the latest tag chipset. Vary advanced stuff.

All of the dominant mobile phone platforms now support NFC.

**Comment by jrstanley** [comment]
@ClintonGallagher I would still like to see this data on Can I use, and the news from Apple is good. However, I don't think that WebKit have announced any commitment to the Web NFC API as yet.

This feature is now 'in development' in Chrome (rather than just an intent to ship in Nov 2015).

**Comment by ClintonGallagher** [comment]
With this NFC support in Apple's iOS Core documentation
https://developer.apple.com/documentation/corenfc#topics

I don't think it will be long before WebKit and other browser vendor get back to taking care of business

**Comment by ssc-hrep3** [comment]
+1

**Comment by rpeinl** [comment]
+1

**Comment by awebdeveloper** [comment]
https://www.chromestatus.com/features/6261030015467520

https://developer.microsoft.com/en-us/microsoft-edge/platform/catalog/?q=specName%3Aweb-nfc

https://www.w3.org/TR/nfc/

**Comment by Neologist** [comment]
+1

**Comment by ClintonGallagher** [comment]
W3C Working group has abandoned Web NFC just when its beginning to go mainstream. Makes no sense unless there's something I don't know about that's come along to replace it.

**Comment by Joe-Palmer** [comment]
There seem to have been quite a few updates since the 16 June 2015 date on the [W3](https://www.w3.org/TR/nfc/) page:

https://bugs.chromium.org/p/chromium/issues/detail?id=520391&desc=2
https://www.chromestatus.com/feature/6261030015467520
https://w3c.github.io/web-nfc/

It looks to me as if it is not dead...

**Comment by mik-laj** [comment]
+1

**Comment by SimonKlausLudwig** [comment]
+1

**Comment by basst85** [comment]
Web NFC is supported now in Chrome 81

**Comment by bludev** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=webnfc
