### ISSUE TITLE
Use tags

### ISSUE THREAD

**Issue by tseabra-rocket** [Fyrd/caniuse#2087]
I get an error installing autoprefixer via NPM.

```
npm ERR! notarget No compatible version found: caniuse-db@'>=1.0.30000359 <2.0.0'
npm ERR! notarget It was specified as a dependency of 'autoprefixer'
```

You should use tags to control your versions.
Please create a tag when you want to update a version of your code.

info:
https://github.com/postcss/autoprefixer/blob/master/package.json

**Comment by tseabra-rocket** [comment]
Please close this
The issue was with npm-cache module.

**Comment by cvrebert** [comment]
@tseabra-rocket You can close this yourself using the "Close" button at the bottom of the comment textarea.
