### ISSUE TITLE
Generate browser support for uploaded stylesheet file

### ISSUE THREAD

**Issue by szamano92** [Fyrd/caniuse#2088]
The easiest way to describe my idea is step list.
1. Upload stylesheet file
2. Parse every property / pseudoclass etc.
3. Collect and display supported browsers for given set 

It would be very useful feature and if you won't develop this I will probably try it myself.

(Sorry for spelling. I'm not fluent in English)

**Comment by Fyrd** [comment]
There's already a tool for this at http://doiuse.com so no plans to include on the caniuse.com site.
