### ISSUE TITLE
WebGL IE11 link broken

### ISSUE THREAD

**Issue by corvae** [Fyrd/caniuse#2089]
The link under Known Issues for WebGL (http://connect.microsoft.com/IE/feedback/details/795172/ie11-fails-more-than-half-tests-in-official-webgl-conformance-test-suite) return 401 Unauthorized. Don't know if this is temporary, but right now it doesn't work for me.

**Comment by cvrebert** [comment]
The link loads just fine for me currently.

**Comment by corvae** [comment]
Sure does, I'll close this.
