### ISSUE TITLE
Add Firefox platform feature statuses

### ISSUE THREAD

**Issue by cvrebert** [Fyrd/caniuse#2090]
* https://mozilla.github.io/platatus/#canvas_media_capture
* https://mozilla.github.io/platatus/status.json
* https://github.com/mozilla/platatus

**Comment by Fyrd** [comment]
Awesome, been a bit out of the loop lately so thanks for pointing this out. Hopefully can get it added soon.

**Comment by Fyrd** [comment]
Done! I've made a pass through their current listed and added IDs, though should probably also remove links already covered.

**Comment by cvrebert** [comment]
X-Ref https://github.com/mozilla/platatus/issues/36

**Comment by digitarald** [comment]
Thanks a lot @cvrebert, great to see everything becoming interconnected even before we hit platatus' v1 milestone! There should be an official update on platatus soon and moving to an official domain and repo.
