### ISSUE TITLE
Subtitles in HTML5 Video - VTT

### ISSUE THREAD

**Issue by edent** [Fyrd/caniuse#2093]
Show support for video subtitles `.vtt` 

Ref:

* https://w3c.github.io/webvtt/
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track
* https://developer.mozilla.org/en-US/docs/Web/API/Web_Video_Text_Tracks_Format

**Comment by Fyrd** [comment]
Already available at http://caniuse.com/#feat=webvtt

I've added "vtt" & "subtitles" as keywords now, should help make it more findable
