### ISSUE TITLE
IE/Edge/Safari only support HTTP/2 over TLS

### ISSUE THREAD

**Issue by ScottHelme** [Fyrd/caniuse#2098]
The MSDN page states that: 

"HTTP/2 will be used by Microsoft Edge on SSL/TLS connections (https) when supported by the host server. Microsoft Edge will fall back to HTTP/1.1 when HTTP/2 is not available or the connection is not secure."

On the HTTP/2 support page it is not indicated that Edge only supports HTTP/2 over TLS. 

https://msdn.microsoft.com/en-us/library/dn905221(v=vs.85).aspx
http://caniuse.com/#feat=http2

**Comment by ScottHelme** [comment]
This MSDN page also states:

"Note: in the Technical Preview versions of both IE and IIS, non-secure connections (i.e. HTTP) are not supported on HTTP/2; only secure connections (i.e. HTTPS) are supported on HTTP/2."

http://blogs.msdn.com/b/ie/archive/2014/10/08/http-2-the-long-awaited-sequel.aspx

**Comment by ScottHelme** [comment]
Further details: Safari in OS X 10.11 and iOS 9 support HTTP/2 over an encrypted connection only.

https://developer.apple.com/videos/play/wwdc2015-711/

Watch from around 13 mins for all details. Encryption only confirmation @ 24:00 and version support @ 25:00.

**Comment by Ugoku** [comment]
[quote from the HTTP2 GitHub page](https://http2.github.io/faq/#does-http2-require-encryption): "currently no browser supports HTTP/2 unencrypted" and I doubt that's going to change soon, if ever.

**Comment by Fyrd** [comment]
This was updated accordingly some time ago, so closing this issue.
