### ISSUE TITLE
Add web assembly/wasm

### ISSUE THREAD

**Issue by kanaka** [Fyrd/caniuse#2099]
Related to asm.js but should probably be called out separately.

Links:
- https://brendaneich.com/2015/06/from-asm-js-to-webassembly/
- http://www.2ality.com/2015/06/web-assembly.html
- https://github.com/WebAssembly
- https://github.com/WebAssembly/design
- https://github.com/WebAssembly/spec
- https://github.com/WebAssembly/wasm-e2e
- https://www.chromestatus.com/features#Webassembly (proposed status for Chrome)

**Comment by cvrebert** [comment]
Duplicate of #1674.

**Comment by Fyrd** [comment]
This was added some time ago at https://caniuse.com/#feat=wasm
