### ISSUE TITLE
Firefox 44 will enable unicode-range by default

### ISSUE THREAD

**Issue by acdha** [Fyrd/caniuse#2100]
https://groups.google.com/forum/#!topic/mozilla.dev.platform/QFJO6aqQwIs

> We intend to ship unicode-range in Firefox 44. It has been implemented for
non-Linux platforms for over a year now behind the
"layout.css.unicode-range.enabled" pref. The pref has been enabled by
default for Nightly and Developer builds but not for Beta and Release
builds. Once changes to Linux font handling have been enabled (bug
1180560), this feature will now be available on all platforms.

https://bugzilla.mozilla.org/show_bug.cgi?id=1119062

**Comment by Fyrd** [comment]
This was recently added. Thanks!
