### ISSUE TITLE
Add try/catch/finally

### ISSUE THREAD

**Issue by tmorrow-hyphensolutions** [Fyrd/caniuse#2102]
http://www.w3schools.com/jsref/jsref_try_catch.asp

**Comment by icambron** [comment]
:-1: I don't know if there's like an official policy on this stuff, but I think the value of caniuse would be diminished by including every JS feature released in 1999.

**Comment by Fyrd** [comment]
Indeed, caniuse is intended for newer technologies, not to point out things that have been supported for ages like this. However I'll leave this issue open, as at some point I may make this searchable to point out that it's fully supported.

**Comment by toddmo** [comment]
I'm sorry. I didn't check first that it was deprecated first, my bad. I agree that it would help if it redirected like wiki, with a redirection comment at the top, like wikipedia. Thanks!

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_statements_try_catch
