### ISSUE TITLE
Add the CSS scrollbar Properties

### ISSUE THREAD

**Issue by myles** [Fyrd/caniuse#2108]
Related Issues: #1121, #1449

There are a bunch of scrollbar properties that work with IE9 and Opera<sup>[1](#issue-footnote-1)</sup>:

* `scrollbar-arrow-color`: Specifies the color of the arrow elements of a scroll arrow - <https://msdn.microsoft.com/en-us/library/ms531154(v=vs.85).aspx>
* `scrollbar-base-color`: Specifies the base color of the main elements of a scroll bar - <https://msdn.microsoft.com/en-us/library/ms531155(v=vs.85).aspx>
* `scrollbar-face-color`: Specifies the color of the scroll box and scroll arrows of a scroll bar - <https://msdn.microsoft.com/en-us/library/ms531157(v=vs.85).aspx>
* `scrollbar-highlight-color`: Specifies the color of the slider tray, and the top and left edges of the scroll box and scroll arrows of a scroll bar - <https://msdn.microsoft.com/en-us/library/ms531158(v=vs.85).aspx>
* `scrollbar-track-color`: Specifies the color of the track element of a scroll bar  - <https://msdn.microsoft.com/en-us/library/ms531160(v=vs.85).aspx>

There are also a few vendor prefixed properties for IE9:

* `-ms-scrollbar-3dlight-color`: Specifies the color of the top and left edges of the scroll box and scroll arrows of a scroll bar - <https://msdn.microsoft.com/en-us/library/ms531153(v=vs.85).aspx>
* `-ms-scrollbar-darkshadow-color`: Specifies the color of the gutter of a scroll bar - <https://msdn.microsoft.com/en-us/library/ms531156(v=vs.85).aspx>
* `-ms-scrollbar-shadow-color`:  Specifies the color of the bottom and right edges of the scroll box and scroll arrows of a scroll bar - <https://msdn.microsoft.com/en-us/library/ms531159(v=vs.85).aspx>

**Footnotes**

* <a name="issue-footnote-1">1</a>: I haven't been able to find this in Opera's official documentation.

**Comment by Ugoku** [comment]
AFAIK, this only works in Presto-Opera, so versions up to and including 12.5, *not* in versions 15 and up. I also doubt this works on any platform other than Windows, or on Windows 8+. Could easily be tested though :)

**Comment by cvrebert** [comment]
-1

**Comment by berkandirim** [comment]
What about ::-webkit-scrollbar?

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-scrollbar
