### ISSUE TITLE
Add additional searchable terms for CSS3 Selectors

### ISSUE THREAD

**Issue by davidjb** [Fyrd/caniuse#2110]
I've been looking to contrast CSS3 selectors via CanIUse, and after tying various search terms, I still couldn't find `CSS3 Selectors`.  The main issue was that I was taking a cue from the `CSS 2.1 Selectors` entry, which has a space and getting no results (http://caniuse.com/#search=css%203%20selectors).

I then tried a number of different search terms:
- http://caniuse.com/#search=css%203 - shows only CSS 3D transforms
- http://caniuse.com/#search=css%20selectors -- shows only CSS 2.1
- http://caniuse.com/#search=css3 - requires showing more results and a lot of scrolling.

Finally landing on `CSS3 selectors` (no space) as the search term I needed to have typed in to find it.    Could extra searchable keywords be added to this entry so it is more easily discoverable?

**Comment by Fyrd** [comment]
I believe this got fixed some time ago, https://caniuse.com/#search=css%20selectors and http://caniuse.com/#search=css%203%20selectors for example now show the expected result.
