### ISSUE TITLE
Add: window.locationbar window.menubar window.personalbar window.statusbar window.toolbar

### ISSUE THREAD

**Issue by oriadam** [Fyrd/caniuse#2111]
Please add caniuse details for the subject features.
Details:
https://developer.mozilla.org/en-US/docs/Web/API/Window/locationbar
https://developer.mozilla.org/en-US/docs/Web/API/Window/menubar
https://developer.mozilla.org/en-US/docs/Web/API/Window/personalbar
https://developer.mozilla.org/en-US/docs/Web/API/window/scrollbars
https://developer.mozilla.org/en-US/docs/Web/API/Window/statusbar
https://developer.mozilla.org/en-US/docs/Web/API/Window/toolbar

**Comment by cvrebert** [comment]
-1

**Comment by charleslei** [comment]
+1

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_window_locationbar etc.
