### ISSUE TITLE
Add: the 'isolation' CSS property

### ISSUE THREAD

**Issue by juanbrujo** [Fyrd/caniuse#2114]
CSS `isolation` property allows to isolate groups of elements from their deeper background and to blend their background color together, useful in conjunction with `background-blend-mode`.

at present time it is a _Candidate Recommendation_

https://drafts.fxtf.org/compositing-1/#isolation

**Comment by benjamincharity** [comment]
:+1:

**Comment by mediaformat** [comment]
+1

**Comment by Pudge601** [comment]
+1

**Comment by giffeler** [comment]
+1

**Comment by Malvoz** [comment]
+1

**Comment by NikolaySolodukhin** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mdn-css_properties_isolation
