### ISSUE TITLE
Update Android Browser?

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#2115]
- [Android 6 is available](https://en.wikipedia.org/wiki/Android_version_history#Android_6.0_Marshmallow_.28API_level_23.29)
- [WebView is at v46](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=de) (cant find those damn version number on desktop oO)

=> 

`Android 5.x-6.x WebView: Chromium 46`?

**Comment by Fyrd** [comment]
Thanks for the reminder, done. What do you mean by not being able to find the version number on desktop?

**Comment by Schweinepriester** [comment]
I mean i can't find the version number in the play store (via this link: <https://play.google.com/store/apps/details?id=com.google.android.webview&hl=de>) on desktop e.g. Chrome; it seems to be only displayed in the actual play store app.
A friend of mine with an Android phone looked it up for me.
Also couldn't find it officially anywhere else, but since I wanted proof for the claim in this issue... 

Thanks for updating the data! :)

**Comment by Fyrd** [comment]
Ah, gotcha. Yeah I just check the user agent string in a webview to find out, but having an android phone helps with that. :)

**Comment by Schweinepriester** [comment]
WebView is now also at v47... 0:-)
