### ISSUE TITLE
font-variant-numeric

### ISSUE THREAD

**Issue by ierhyna** [Fyrd/caniuse#2116]
There is no information about font-variant-numeric feature support.
(MDN: https://developer.mozilla.org/en/docs/Web/CSS/font-variant-numeric)
Thanks!

**Comment by Ugoku** [comment]
+1

**Comment by kiding** [comment]
Not only `font-variant-numeric`, but also many properties defined by [CSS Fonts Module Level 3](https://www.w3.org/TR/css-fonts-3/#font-rend-props) are missing, which include;

- `font-variant-ligatures`
- `font-variant-position`__*__
- `font-variant-caps`
- `font-variant-numeric`
- `font-variant-east-asian` 
- `font-variant` (shorthand)
- `font-language-override`__*__

> __*__ Features at risk, may be removed in the future.

Some are [only supported by Firefox](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant), and Safari [started to support them recently.](https://webkit.org/blog/5735/css-font-features/) I'd like to suggest we change the issue to conform with all the CSS Fonts properties.

**Comment by drott** [comment]
+1

**Comment by drott** [comment]
I implemented font-variant-numeric and font-variant-caps in Chrome 52, compare https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/p9k6H2tUADk

**Comment by kiding** [comment]
@drott Very cool!

**Comment by maddesigns** [comment]
+1

**Comment by Megabyte-16** [comment]
+1

**Comment by garrik** [comment]
+1

**Comment by chharvey** [comment]
#1550 seems to have already proposed this, but I like that @kiding has enumerated out the sub-properties for all to see. @kiding, can you cite any sources on the "features at risk," i.e., where are you getting that information?

**Comment by kiding** [comment]
@chharvey [The W3C CSS standard](https://www.w3.org/TR/css-fonts-3/) has "Features at risk" section near the top of the document, right below the status section.

**Comment by svgeesus** [comment]
The Features at risk section in CSS Fonts 3 is empty; some features stopped being at risk, and a couple were moved to CS Fonts 4.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=font-variant-numeric
