### ISSUE TITLE
Add data for imageSmoothingEnabled Property (Canvas-related)

### ISSUE THREAD

**Issue by kirupa** [Fyrd/caniuse#2117]
More details here: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled

:-)

**Comment by tripu** [comment]
(Duplicate of #1423. Remove?)

**Comment by tripu** [comment]
@Fyrd (ping :) isn't this a duplicate?

**Comment by Fyrd** [comment]
Yes, yes it is.
