### ISSUE TITLE
IE11 does not accept 0 as a valid length for the flex-basis property.

### ISSUE THREAD

**Issue by joineral32-cengage** [Fyrd/caniuse#2121]
IE11 appears to have the following bug with flexbox. When using the flex property in IE11, setting a length value of '0' for the flex-basis component of the flex property (e.g. flex: 1 1 0) is not recognized as a valid value, and can cause the browser to ignore the flex property.

This appears to be confirmed by Microsoft's documentation for flex-basis in IE11:
https://msdn.microsoft.com/en-us/library/dn254946(v=vs.85).aspx
See: "Width as specified by a number, followed by a length unit. Negative numbers are invalid."

**Comment by damienmckenna** [comment]
This was reported as a bug in the YUI compressor: https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port/issues/26

**Comment by damienmckenna** [comment]
I opened a new PR to note this bug/feature: #2532

**Comment by damienmckenna** [comment]
FYI flexbugs already lists this one:

https://github.com/philipwalton/flexbugs#4-flex-shorthand-declarations-with-unitless-flex-basis-values-are-ignored

**Comment by Fyrd** [comment]
Closing this issue, since the PR got merged.
