### ISSUE TITLE
Chrome removes support for SVGPathSeg

### ISSUE THREAD

**Issue by Llbe** [Fyrd/caniuse#2126]
I suggest adding this under Known Issues: Chrome 48+ has no longer support for the SVGPathSeg interface.

This interface has a low usage. However there are yet no alternative interface in Chrome and all other browsers support this interface. There was no pre-warning of this removal (but it was removed from SVG 2 draft in June). Not a very smooth transition. The main problem here is performance when editing paths.

Polyfill: https://github.com/progers/pathseg/blob/master/pathseg.js

Polyfill for the SVG 2 drafting interface: https://github.com/jarek-foksa/path-data-polyfill.js

Source: https://www.chromestatus.com/feature/5708851034718208

**Comment by Llbe** [comment]
.. for the SVG basic support that is: http://caniuse.com/#feat=svg

**Comment by Fyrd** [comment]
Thanks, added as known issues.
