### ISSUE TITLE
Support for rel='preload'

### ISSUE THREAD

**Issue by etylsarin** [Fyrd/caniuse#2130]
W3C editor's draft: https://w3c.github.io/preload/

**Comment by Schweinepriester** [comment]
https://twitter.com/ebidel/status/690058172283904000 => https://chromium.googlesource.com/chromium/src/+/dcbdcdb41ad3b1dbb0426b3092592b2c451ad098

> \<link rel=preload\> for scripts/styles landed today in Blink

+1, btw. again :)

**Comment by MarcoHengstenberg** [comment]
+1 as we already got the first browser supporting the feature

**Comment by Schweinepriester** [comment]
<https://twitter.com/smashingmag/status/692489614167269378> => 
- polyfill: <https://github.com/filamentgroup/loadCSS>
- demo: <http://filamentgroup.github.io/loadCSS/test/preload.html>

**Comment by paulirish** [comment]
Chrome 50 [now](https://bugs.chromium.org/p/chromium/issues/detail?id=552289#c7) has support for `<link rel=preload>`.

It supports the following `as` values (also called ["request destinations"](https://fetch.spec.whatwg.org/#concept-request-destination)):

| `as` value | example |
| --- | --- |
| `script` | `<link rel=preload href="dummy.js" as=script>` |
| `style` | `<link rel=preload href="dummy.css" as=style>` |
| `image` | `<link rel=preload href="square.png" as=image>` |
| `font` | `<link rel=preload href="Ahem.ttf" as=font crossorigin>` |
| `video` | `<link rel=preload href="test.mp4" as=video>` |
| `audio` | `<link rel=preload href="test.oga" as=audio>` |
| `track` | `<link rel=preload href="captions.vtt" as=track>` |
| (invalid) | `<link rel=preload href="dummy.xml" as=foobarxmlthing>` |
| (blank) | `<link rel=preload href="dummy.xml">` |

In Chrome, the `script`, `style`, `image`, and `font` get very specific treatment and are fetched as typical resources of that type, applying any neccessary prioritization, etc. Currently all other types are successfully fetched, though as a generic resource.

A test page: https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/LayoutTests/http/tests/preload/onload_event.html

**Comment by jelmerdemaat** [comment]
+1 (to upvote on feature suggestion list).

**Comment by forberg** [comment]
+1

**Comment by pablomoretti** [comment]
+1

**Comment by Chuclucillo** [comment]
+1

**Comment by orzage** [comment]
+1

**Comment by rsteinwand** [comment]
+1

**Comment by PeterJCLaw** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=link-rel-preload
