### ISSUE TITLE
Add Quota Management API

### ISSUE THREAD

**Issue by deadmanswitch** [Fyrd/caniuse#2132]
Quota Management API specification defines an API to manage usage and availability of local storage resources, and defines a means by which a user agent (UA) may grant Web applications permission to use more local space, temporarily or persistently, via various different storage APIs.

**Comment by cvrebert** [comment]
Duplicate of #1277. Did you search the existing issues beforehand?

**Comment by deadmanswitch** [comment]
Yes, but I haven't found it
