### ISSUE TITLE
Please allow to query for several features at once and show the union result.

### ISSUE THREAD

**Issue by venthur** [Fyrd/caniuse#2139]
Say I use `getUserMedia` and `Data URIs` in my application and want to see the percentage of supported browsers with **both** features available. Currently there is no way to express such a query on http://caniuse.com.

This feature seems to be partly implemented already. When you look for something general with several matches like `data`, you'll see the stats for each match and a summary at the end of the page for all matches combinded.

It would be very helpful if the website would support a syntax that allows to combine features myself, like: `getUserMedia, Data URIs`.

**Comment by Fyrd** [comment]
While there's no UI for this, it's technically already possible to see this with comma-separated feature IDs, e.g. http://caniuse.com/#feat=stream,datauri

**Comment by Fyrd** [comment]
The beta site (https://beta.caniuse.com) now adds UI for this, you can star features to add them to a saved list, which includes a "Feature summary" table with multiple views for the combined support data (including a Union option).

Will close this issue once it's on the main site.

**Comment by Fyrd** [comment]
This is now available on the main site.
