### ISSUE TITLE
Add CSS text-combine-upright property 

### ISSUE THREAD

**Issue by yisibl** [Fyrd/caniuse#2159]
https://bugzilla.mozilla.org/show_bug.cgi?id=1097499
WebKit support old name: text-combine https://bugs.webkit.org/show_bug.cgi?id=48538
WebKit update text-combine to match spec: https://bugs.webkit.org/show_bug.cgi?id=150821
https://bugs.webkit.org/show_bug.cgi?id=150821

https://developer.mozilla.org/en-US/docs/Web/CSS/text-combine-upright

**Comment by kojiishi** [comment]
* Trident/Edge supports in an old name with prefix as `-ms-text-combine-horizontal` ([MSDN](https://msdn.microsoft.com/ja-jp/library/dn337005.aspx)).
* Chrome upgraded to the current syntax and removed the prefix in [48](http://crbug.com/533448).

**Comment by yisibl** [comment]
@kojiishi Thanks!
 Does Chrome have a plan to support `text-combine-upright: digits 4`?

**Comment by gregwhitworth** [comment]
@kojiishi @yisibl Thanks - was gonna come in here and say that, you rock!! That said in Edge 15 it is un-prefixed so that we could help get into CR for this spec.

**Comment by kojiishi** [comment]
@yisibl 
> Does Chrome have a plan to support `text-combine-upright: digits 4`?

Sorry I missed this. No, only Edge supports `digits` value as of today.

**Comment by kojiishi** [comment]
@gregwhitworth 
> Edge 15 it is un-prefixed

Yay, thank you for the efforts!

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-css_properties_text-combine-upright
