### ISSUE TITLE
 Add support for src="//{something}" form

### ISSUE THREAD

**Issue by ywarnier** [Fyrd/caniuse#2160]
In https://tools.ietf.org/html/rfc1808#section-4 (see http://stackoverflow.com/a/4661857/1406662 for more info), the possibility to introduce URLs of the form "//{content}" (without http or https) is defined (examples in section 5).

It would be great to know which browsers support this notation.

**Comment by cvrebert** [comment]
Better known as [protocol-relative URLs](http://www.paulirish.com/2010/the-protocol-relative-url/).
As noted in the blog post, they're now an antipattern. Their support is likely near-universal, considering that they work even in IE6.

**Comment by ywarnier** [comment]
Great, I didn't know if that was really the case. Thanks.
