### ISSUE TITLE
Time to move SVG fonts to unofficial?

### ISSUE THREAD

**Issue by dstorey** [Fyrd/caniuse#2166]
I think it is time to move to unofficial:

* Most important from an official / unofficial viewport, they've been removed from SVG2: http://www.w3.org/TR/SVG2/changes.html#fonts
* There is no traction. Safari is the only one left supporting them now Blink has deprecated them and Presto is no longer maintained.
* Now deprecated, they shouldn't be encouraged to be used. There are other alternatives, including WOFF and Web Fonts (called out in SVG2 spec).

**Comment by Fyrd** [comment]
Yeah, agreed. Done!
