### ISSUE TITLE
WebKit Nightly support WOFF2

### ISSUE THREAD

**Issue by yisibl** [Fyrd/caniuse#2167]
https://bugs.webkit.org/show_bug.cgi?id=150830

**Comment by Schweinepriester** [comment]
Hurray! :)

**Comment by yisibl** [comment]
Test: http://codepen.io/yisi/pen/dGzeKJ/

**Comment by Fyrd** [comment]
Thanks, added as note.

**Comment by ShikiSuen** [comment]
Then I am wondering when will Safari finally introduce this update...
