### ISSUE TITLE
Add data for link rel="alternate"

### ISSUE THREAD

**Issue by jhgarrison** [Fyrd/caniuse#2169]
See https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types

`<link rel="alternate" media="... media query ...">`

Used to specify alternate content to be loaded based on a media query

**Comment by anarcat** [comment]
i would suggest to not limit yourselves to media queries. RSS feeds and alternate formats (e.g. PDF, languages and so on) use this as well...

**Comment by tannerdolby** [comment]
Was hoping to find some data on `<link rel="alternate" hreflang="en" href="https://www.example.com/" />` but unfortunately doesn't seem to be supported. 

If this does become added to caniuse.com in the future that would be excellent! There aren't too many places to find the support for `<link rel="alternate">` paired with `hreflang` so this will be the single source of truth when updated.

**Comment by GPHemsley** [comment]
I think this is now covered by MDN data:
https://caniuse.com/mdn-html_elements_link_rel
https://caniuse.com/mdn-html_elements_link_media
https://caniuse.com/mdn-html_elements_link_hreflang

(via mdn/browser-compat-data#279, mdn/browser-compat-data#6423, mdn/browser-compat-data#5980, mdn/browser-compat-data#10544)
