### ISSUE TITLE
Add note "border-image needs to not override border-style"

### ISSUE THREAD

**Issue by yisibl** [Fyrd/caniuse#2172]
WebKit/Blink even if no definition of border-style will show border-image, that does not meet the specification.

* https://github.com/whatwg/compat/issues/17
* https://code.google.com/p/chromium/issues/detail?id=559258
* https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/J7rvFkcn8TU

**Comment by Fyrd** [comment]
Thanks, updated now.
