### ISSUE TITLE
Add a "Release Date" for the various browser versions

### ISSUE THREAD

**Issue by simonrcodrington** [Fyrd/caniuse#2175]
Hi there

Firstly, thanks for the great resource!, it's my first stop when I need to know if X browser supports Y feature. 

I'm wondering if it's possible to add the browser date of release onto each of the browser versions on the support page. For example if you search for 3D transforms and it tells you that IE9 and IE10 supports it, when you hover over the support for the browser version it tells you that X% of the population is currently using the browser, what would be nice is if it also told you what year and month that browser version came out I.e September 2006. 

Basically you would be able to quickly glace and see that X feature has been supported for the last 10 versions of Firefox but that first version that supported it was only 1 year ago. 

Right now I just check wikipedia to get the release dates of things; however if your website has that info already on it I wouldn't ever have to use anything else! 

If you wanted someone to collect the approximate dates of all the browsers I would be more than happy to do that for you (as I think this would help developers better understand how long-standing support it)

Have a good day!

Cheers

Simon

**Comment by Schweinepriester** [comment]
+1, great idea!

**Comment by rubenvincenten** [comment]
+1!

**Comment by pps** [comment]
+1!

**Comment by matheod** [comment]
+1, got the same issue (but it was about 2D transform) !

**Comment by ihuro** [comment]
+1

**Comment by craigkovatch** [comment]
+1

**Comment by AdamMerrifield** [comment]
+1

**Comment by YoussF** [comment]
+1

**Comment by lingtalfi** [comment]
+1

**Comment by Fyrd** [comment]
Now available on the site! See http://caniuse.com/feed/157 for details.

**Comment by lingtalfi** [comment]
Awesome. Could it also show the estimated release dates for upcoming browsers so that we can have all in one place?

The idea here is that we can estimate in one glance whether or not we would take the risk to implement a bleeding edge feature now, knowing that it will be standardized in a few months (for instance).

https://www.chromium.org/developers/calendar
https://wiki.mozilla.org/RapidRelease/Calendar
