### ISSUE TITLE
Incorrect usage count

### ISSUE THREAD

**Issue by larsenwork** [Fyrd/caniuse#2176]
Denmark should be displaying ~97% but displays 79% instead 

![screen shot 2015-12-26 at 19 27 20](https://cloud.githubusercontent.com/assets/3859425/12007481/dd048342-ac06-11e5-9121-97ecb7d99e27.png)

**Comment by spaceneenja** [comment]
Seeing same issue with US.

**Comment by Fyrd** [comment]
Yeah, looks like iOS 9.* isn't being included, sorry about that. Should have it fixed by tomorrow.

**Comment by larsenwork** [comment]
👍

**Comment by Fyrd** [comment]
Fixed now.
