### ISSUE TITLE
Add support stats for String.prototype.repeat()

### ISSUE THREAD

**Issue by bmccutchon** [Fyrd/caniuse#2177]
This string repeating method is part of ES6. More info can be found at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat

**Comment by cvrebert** [comment]
https://kangax.github.io/compat-table/es6/#test-String.prototype_methods_String.prototype.repeat

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_builtins_string_repeat
