### ISSUE TITLE
Trailing commas

### ISSUE THREAD

**Issue by BobStein** [Fyrd/caniuse#2182]
Suggestion:

```
 //caniuse.com/#feat=object-literal-trailing-comma
 //caniuse.com/#feat=array-literal-trailing-comma
 //caniuse.com/#feat=function-parameters-trailing-comma
```

...or something.

Trailing commas in JavaScript object or array literals have vague scary warnings against.
- http://stackoverflow.com/questions/5139205/javascript-can-a-comma-occur-after-the-last-set-of-values-in-an-array
- http://dontkry.com/posts/code/trailing-commas.html

The following resource identifies IE8,IE7,IE6... as the only browsers to worry about for trailing commas in object literals:
- http://rauschma.github.io/js-feature-matrix/

Is that true? Is it complete? What about array literals? JSON.parse? jQuery.parseJSON?

**Comment by tvler** [comment]
+1

**Comment by danielchasehooper** [comment]
+1

**Comment by smwa** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas mentions that JavaScript has allowed trailing commas in arrays since the very beginning, but I agree that it could be useful to have a feature "Trailing Commas In Objects"

**Comment by lane-snider** [comment]
Trailing commas in function parameter lists started in ES2017. I can't find any reference for which browsers support that.

**Comment by BobStein** [comment]
> ...in function parameter lists

Thanks Lane, a 3rd subgenre of dangling commas. I would like to assume function-**call** and function-**definition** don't need to be distinguished.

**Comment by Fyrd** [comment]
Various types of trailing commas can now be found at https://caniuse.com/#search=trailing%20commas

**Comment by BobStein** [comment]
A nice start, but if I'm reading correctly, none of them say anything about that perennial wacky hold-out, Opera-Mini.
