### ISSUE TITLE
support for Performance-Timeline & High-Resolution-Time

### ISSUE THREAD

**Issue by sojuker** [Fyrd/caniuse#2192]
- http://www.w3.org/TR/performance-timeline-2/
- http://www.w3.org/TR/hr-time-2/

I can see now `User Timing API` 、`Resource Timing API`、`Navigation Timing API` supported. 
ask for Performance-Timeline & High-Resolution-Time

**Comment by cvrebert** [comment]
* https://webkit.org/status/#specification-performance-observer

**Comment by alexkoffler** [comment]
+1

**Comment by kenharker** [comment]
+1

**Comment by nick11703** [comment]
+1

**Comment by Fyrd** [comment]
Available on various tables, including https://caniuse.com/#feat=mdn-api_performance & https://caniuse.com/#feat=high-resolution-time
