### ISSUE TITLE
ES6 Template Strings / Template Literals

### ISSUE THREAD

**Issue by a-r-d** [Fyrd/caniuse#2193]
Can we add ES6 template literals to caniuse? It is now supported in latest chrome and firefox but not IE. I think this feature may also be called multiline strings in some places. 

MDN Doc:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings

Spec:
http://www.ecma-international.org/ecma-262/6.0/#sec-template-literals

**Comment by ScratchOs** [comment]
+1

**Comment by cvrebert** [comment]
https://kangax.github.io/compat-table/es6/#test-template_strings

**Comment by jogibear9988** [comment]
+1

**Comment by nathanhleung** [comment]
+1

**Comment by shaheenery** [comment]
+1

**Comment by Ugoku** [comment]
Duplicate of #2070

**Comment by cpplearner** [comment]
+1

**Comment by puresick** [comment]
+1

**Comment by psimin** [comment]
+1

**Comment by cbraith** [comment]
+1

**Comment by jineeshjohn** [comment]
+1

**Comment by Jeddf** [comment]
+1

**Comment by gorsash** [comment]
+1

**Comment by oscarmorrison** [comment]
+1

**Comment by Connum** [comment]
+1

**Comment by pbogdan03** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=template-literals
