### ISSUE TITLE
Add background-position-x and background-position-y

### ISSUE THREAD

**Issue by dscafati** [Fyrd/caniuse#2195]
These sound very intuitive but don't work in latest firefox versions. I found these are not standard, rather, these where originally implemented by MSIE only

**Comment by cvrebert** [comment]
https://drafts.csswg.org/css-backgrounds-4/#background-position-longhands

**Comment by cvrebert** [comment]
[Firefox doesn't yet support them.](https://bugzilla.mozilla.org/show_bug.cgi?id=550426)
According to http://snook.ca/archives/html_and_css/background-position-x-y , they work in all the other major browsers, and don't work in Presto.

**Comment by yisibl** [comment]
:+1:

**Comment by Fyrd** [comment]
Duplicate of #989
