### ISSUE TITLE
 focusin , focusout events

### ISSUE THREAD

**Issue by rokyed** [Fyrd/caniuse#2199]
these ones:
http://www.w3.org/TR/DOM-Level-3-Events/#event-type-focusin,

Thanks

**Comment by cvrebert** [comment]
+1
Not supported in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=687787
It's allegedly supported in all the other major browsers.

**Comment by rokyed** [comment]
Thanks.

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=focusin-focusout-events Thanks @cvrebert!
