### ISSUE TITLE
Safari 9.1: <picture>, CSS Variables, font-variant-* and more! :)

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#2204]
Via <https://twitter.com/bram_stein/status/686678163993313280> and <https://twitter.com/smashingmag/status/686678828807286785>:

<https://developer.apple.com/library/prerelease/mac/releasenotes/General/WhatsNewInSafari/Articles/Safari_9_1.html#//apple_ref/doc/uid/TP40014305-CH10-SW1>

**Comment by yisibl** [comment]
It looks like in Safari 9.3.

**Comment by mkurz** [comment]
@yisibl You mean Safari in IOS 9.3?

**Comment by Ugoku** [comment]
+1

**Comment by yisibl** [comment]
@mkurz Yeah, https://twitter.com/webkit/status/686657179365945344

**Comment by Schweinepriester** [comment]
To summarize for @Fyrd:

- `<picture>` now supported
- `touch-action` now supported
- CSS Variables now supported
- CSS `all` property now supported
- CSS `unset` value now supported
- CSS `revert` value now supported (see #2039)
- `font-variant-ligatures`, `font-variant-caps`, `font-variant-numeric`, `font-variant-alternates`, `font-variant-east-asian` and `font-feature-settings` now supported
- CSS `will-change` property now supported
-  CSS Filters now without `-webkit-` (probably [http://caniuse.com/#feat=css-filters](CSS Filter Effects))

Additionally

> The `round` and `space` values are supported for the `border-image-repeat` property.

which probably needs more testing, since the only thing about being unsupported i could find was <https://css-tricks.com/understanding-border-image/> (2010):

> Right now, Safari and Chrome interpret round as repeat.

Which, if the case, probably should be reflected in <http://caniuse.com/#feat=border-image>.
Furthermore should <http://caniuse.com/#search=border-image-repeat> probably find <http://caniuse.com/#feat=border-image>.
Maybe this should be a seperate issue.

**Comment by Fyrd** [comment]
Thanks for the summary @Schweinepriester ! Much appreciated, have updated most of those accordingly. Will handle the border-image stuff separately, agreed that that should probably be a separate issue. Feel free to submit a PR on that too if you like.
