### ISSUE TITLE
CSS4 pseudo-class E:matches(s1, s2)

### ISSUE THREAD

**Issue by laukstein** [Fyrd/caniuse#2205]
Add data about CSS4 pseudo-class `:matches()`.
Spec https://drafts.csswg.org/selectors/#matches

Browser support mentioned in https://css-tricks.com/almanac/selectors/m/matches/ (might be outdated).

Chrome | Safari | Firefox | Opera | IE | Android | iOS
---------- | -------- | -------- | -------- | --- | ---------- | -----
12+ (-webkit-) | 5+ (-webkit-) | 4+ (-moz-) | 15+ (-webkit-) | Nope | ? | 5+ (-webkit-)

Chrome issue https://code.google.com/p/chromium/issues/detail?id=568705

**Comment by cvrebert** [comment]
Subfeature of #1058.

**Comment by cvrebert** [comment]
Gratuitous testcase: http://jsbin.com/lehina/edit?html,css,output

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-matches-pseudo

**Comment by cvrebert** [comment]
@Fyrd This data is no longer pending review.
