### ISSUE TITLE
vector-effect

### ISSUE THREAD

**Issue by geedix** [Fyrd/caniuse#2206]
which browsers support vector-effect? Specifically trying to use non-scaling-stroke which appears to work in Chrome and Safari but not FF

**Comment by danmarshall** [comment]
+1

**Comment by cvrebert** [comment]
https://www.w3.org/TR/SVGTiny12/painting.html#VectorEffectProperty

**Comment by mjesun** [comment]
👍

**Comment by asmockler** [comment]
:+1:

**Comment by tobireif** [comment]
+1

**Comment by Dakkaron** [comment]
Would be very much appreciated

**Comment by jcappell** [comment]
+1

**Comment by Herst** [comment]
+1

**Comment by rossjrw** [comment]
+1 also

**Comment by jopi98** [comment]
+1 again

**Comment by Solatrix** [comment]
+1, we're in 2021. This feature has been around and proposed in 2004. Might be time to fill up the details of its specs :)

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/vector-effect (non-scaling-stroke only)
