### ISSUE TITLE
Add border-image-repeat/Correct border-image?

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#2207]
From <https://github.com/Fyrd/caniuse/issues/2204#issuecomment-171112215>:

> Additionally

> > The round and space values are supported for the border-image-repeat property.

> which probably needs more testing, since the only thing about being unsupported i could find was <https://css-tricks.com/understanding-border-image/> (2010):

> > Right now, Safari and Chrome interpret round as repeat.

> Which, if the case, probably should be reflected in <http://caniuse.com/#feat=border-image>.
Furthermore should <http://caniuse.com/#search=border-image-repeat> probably find <http://caniuse.com/#feat=border-image>.
Maybe this should be a seperate issue.

Made an issue, not a PR, sorry :)

**Comment by Schweinepriester** [comment]
The [changelog for Safari 10.0 mentions](https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html#//apple_ref/doc/uid/TP40014305-CH11-DontLinkElementID_21):

> New Values for Border Image
The `round` and `space` values for the `border-image` CSS property are supported.

oO

**Comment by Fyrd** [comment]
This one took a good long while to investigate across browsers, but I believe it's taken care of.

And yeah, AFAICT they got it fixed with 9.1, not sure why it was repeated in the changelog for Safari 10.
