### ISSUE TITLE
Built-in PDF viewer support

### ISSUE THREAD

**Issue by sun** [Fyrd/caniuse#2212]
Most browsers ship with a built-in PDF viewer today.  Which?

A quick test of latest versions reveals:  Chrome, Firefox, Safari, iOS Safari, ...

IE apparently does not, Edge unknown.

There are varying claims that support was added in [Firefox 15](http://www.howtogeek.com/123617/how-to-enable-firefoxs-built-in-pdf-reader/) and [Chrome in 2010](http://www.makeuseof.com/tag/this-is-why-you-dont-need-adobe-reader/).

Apparently, it's very hard to find any info about built-in PDF viewer support on the web.  I naturally checked http://caniuse.com/#search=pdf first, but the feature is not listed yet.

**Comment by 304NotModified** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by moscartong** [comment]
+1

**Comment by JimSangwine** [comment]
+1

**Comment by voku** [comment]
+1

**Comment by Calico90** [comment]
+1

**Comment by codymikol** [comment]
+1

**Comment by thebarada** [comment]
+1

**Comment by jberends** [comment]
+1

**Comment by Malvoz** [comment]
+1

**Comment by jasonwoodland** [comment]
+1

**Comment by bestter** [comment]
+1

**Comment by stpetr** [comment]
+1

**Comment by ioxua-os** [comment]
Since this is a pretty old request is there any reason it's not implemented yet?

**Comment by swergas** [comment]
+1

**Comment by Malvoz** [comment]
@ioxua-os 

> is there any reason it's not implemented yet?

The CanIUse feature data is open-source and thus to some extent depends on contributors (such as you and me) to do the research and to provide the relevant documentation/sources for the data.

**Comment by ElleshaHackett** [comment]
+1

**Comment by solset-ccochran** [comment]
+1

Also, knowing which browsers support specific PDF features such as forms editing support, etc.

I often use this for testing that support: https://www.irs.gov/pub/irs-pdf/f1040.pdf

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=pdf-viewer
