### ISSUE TITLE
Add URLSearchParams

### ISSUE THREAD

**Issue by takenspc** [Fyrd/caniuse#2213]
Specification
https://url.spec.whatwg.org/#interface-urlsearchparams

MDN Document
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

- Firefox supports URLSearchParams since 29 ([Bug 887836](https://bugzilla.mozilla.org/show_bug.cgi?id=887836))
- Chromium will support URLSearchParams since 49 ([Issue 303152](https://code.google.com/p/chromium/issues/detail?id=303152))
- There is a bug for WebKit ([Bug 133276](https://bugs.webkit.org/show_bug.cgi?id=133276))
- [Edge is developing URL Standard API](https://dev.windows.com/en-us/microsoft-edge/platform/status/urlapi) which includes URLSeachParams

**Comment by Schweinepriester** [comment]
+1

**Comment by cvrebert** [comment]
Subfeature of #1312

**Comment by takenspc** [comment]
@cvrebert Thank you for your information!
I close this issue to reduce clutter of issues.
