### ISSUE TITLE
 HTML5 constraint validation API - setCustomValidity

### ISSUE THREAD

**Issue by menorless** [Fyrd/caniuse#2224]

**Comment by cvrebert** [comment]
Should be covered by http://caniuse.com/#feat=form-validation

**Comment by kevinSuttle** [comment]
Perhaps searching for `setCustomValidity` should match http://caniuse.com/#feat=form-validation.

**Comment by kevinSuttle** [comment]
Also, this isn't the same. `setCustomValidity` is about changing the browser's default field validation error message. 

<img width="910" alt="screen shot 2016-04-29 at 3 23 33 pm" src="https://cloud.githubusercontent.com/assets/95672/14927173/5fb7cd0c-0e1e-11e6-838e-36e66851a250.png">

**Comment by tkrotoff** [comment]
I think this should be listed in [HTML5 form features](http://caniuse.com/#feat=forms) Sub-features

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_htmlinputelement_setcustomvalidity
