### ISSUE TITLE
<iframe seamless> can be removed

### ISSUE THREAD

**Issue by annevk** [Fyrd/caniuse#2232]
See https://github.com/whatwg/html/commit/1490eba4dba5ab476f0981443a86c01acae01311.

**Comment by Fyrd** [comment]
Features generally aren't removed from caniuse, but I can mark it as "unofficial". Do you have a link to an explanation somewhere on why it was removed?

**Comment by annevk** [comment]
It'll be a little self-referential https://github.com/whatwg/html/issues/331. 😊

The main problem for us is that `caniuse.com` is pointing to the HTML Standard for this feature at the moment, which ends up generating an warning/error in our build script since we removed it.

**Comment by Fyrd** [comment]
Ha, okay. Have updated the feature and changed the link to an older (w3c) version of the spec, which I assume will solve your issue?

**Comment by zcorpan** [comment]
Heh, nope, our build script still picks it up I believe. But we should get rid of that and make sure that caniuse consistently links to whatwg for not-dropped features... Filed https://github.com/whatwg/wattsi/issues/14

**Comment by MichielBijl** [comment]
Related W3C HTML issue: https://github.com/w3c/html/issues/35

**Comment by AndySky21** [comment]
> changed the link to an older (w3c) version of the spec

I'm sorry, but the version of W3C spec referenced by that is *really* old. 
Besides, `<iframe seamless>` was still present [https://www.w3.org/TR/html51/semantics.html#attr-iframe-seamless](in the last W3.org-"hosted" version of the draft), and still is [http://w3c.github.io/html/semantics.html#seamless-iframe](in the version maintained on GitHub) (and as I asked in the related W3C HTML bug I don't know what's the destiny for the latter).

**Comment by Fyrd** [comment]
Yeah, I guess that spec was due to some lazy googling on my part. Have updated it now with the last one. 

Closing this issue now since it seems to have been resolved.
