### ISSUE TITLE
<lh> tag can be added

### ISSUE THREAD

**Issue by mayeenulislam** [Fyrd/caniuse#2235]
List Header tag is absent in the list
Can we add `<lh>` tag here?

**Usage:**
````
<ul>
	<lh>List Head Here</lh>
	<li>List Item 1</li>
	<li>List Item 2</li>
	<li>List Item 3</li>

	<lh>List Head 2 Here</lh>
	<li>List Item 1</li>
	<li>List Item 2</li>
	<li>List Item 3</li>
	<li>List Item 4</li>
</ul>
````

**Comment by MichielBijl** [comment]
Do you have a link to any specification that lists the `lh` element? It's not in the W3C or WHATWG version of HTML.

**Comment by mayeenulislam** [comment]
Please find the link:
https://www.w3.org/MarkUp/html3/listheader.html

Some more links:
https://www.google.com/search?q=list+header+lh

**Comment by Fyrd** [comment]
It's a really old tag that was deprecated in HTML4+ and is not supported in any browser. Unless there's some plan to add it in a future specification and/or browser it will not be listed on caniuse, so closing this issue.

**Comment by mayeenulislam** [comment]
![list header view](https://cloud.githubusercontent.com/assets/4551598/12572715/f1393fee-c419-11e5-83b7-4c1e0399427b.png)

Pardon me, if this **is** the desired look, then I found it's working on my latest Google Chrome (48.0.2564.82), Firefox (43.0.4), Firefox Developer Edition (45.0a2 (2016-01-24)), Safari (5.1.7 (7534.57.2)), Opera (34.0.2036.50) in Windows machine.

**Comment by MichielBijl** [comment]
@mayeenulislam still, it's a property that is not in any current version/draft of the specification; why would you want to add that?

**Comment by mayeenulislam** [comment]
>it's a property that is not in any current version/draft of the specification

Yes, that's a good reason of **not** adding the tag.

But as CIU is a platform, for browser support, if something supports the browser, I think we can add it, **if**, it's not contradicting with the CIU's vision or any motto. :) I'm not a diehard fan of the tag, I was just informed about the tag yesterday, and searched CIU about browser support, and after not finding the tag there, thought it could be added. That's why it's just a proposal, nothing else.

**Comment by Fyrd** [comment]
Your example works because that's the behavior of any unknown tag in a list, here's it working with a made up `<foo>` tag:
http://codepen.io/Fyrd/pen/pgLwvz so sure, you can use it, but only in the same way you can use any made up unspecified tag.

**Comment by mayeenulislam** [comment]
:+1: good point. Thanks.
