### ISSUE TITLE
HTML5 canvas.captureStream()

### ISSUE THREAD

**Issue by Mido22** [Fyrd/caniuse#2250]
- “Media Capture from DOM Elements” document by W3C defines captureStream() method that allows the capture of the <canvas> element in the form of a MediaStream.  
- This feature has been implemented in [Firefox](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/captureStream) version 43
- For chrome, the implementation is [in progress](https://code.google.com/p/chromium/issues/detail?id=524218)
- another linked method for capturing stream from any MediaElement( audio, video and canvas) might be `captureStreamUntilEnded()` but I was not able to find much documentation for that.

**Comment by varunFX** [comment]
+1

**Comment by cvrebert** [comment]
i.e. https://www.w3.org/TR/mediacapture-fromelement/

**Comment by brion** [comment]
+1

**Comment by swssqewe12** [comment]
+1

**Comment by lingtalfi** [comment]
+1

**Comment by miguelao** [comment]
Chrome implementation was landed last year in M51 for `<canvas>` (https://www.chromestatus.com/features/4817998447640576).

**Comment by cvrebert** [comment]
https://platform-status.mozilla.org/#canvas-media-capture

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=mediacapture-fromelement
