### ISSUE TITLE
Include the new image format: FLIF

### ISSUE THREAD

**Issue by jonastg** [Fyrd/caniuse#2254]
Include which (if any) browsers support FLIF (Free Lossless Image Format):

[http://flif.info/](http://flif.info/)

**Comment by JoshTumath** [comment]
Is there any interest in this from browser vendors?

**Comment by jonastg** [comment]
Native web browser support is included in the [todo list](http://flif.info/#todo-list). Maybe it's a bit early to include it because it's still in development but it's interesting watch it. Another format like BPG (Better Portable Graphics) released previously in 2014 don't have browser support yet (and it also has been requested).

**Comment by JoshTumath** [comment]
It does sound like a good feature. Hopefully we'll see it in browsers, but that's a long process. If I remember right, it took Mozilla a year of consideration to decide not to implement WebP.

**Comment by Ugoku** [comment]
+1

**Comment by Ugoku** [comment]
FWIW, Bruce Lawson from Opera [said the following](https://twitter.com/brucel/status/765566730924097536) when I asked him "any idea if Opera or other browser vendors are considering implementing this?"
> too early to tell; the format isn't ready yet

**Comment by MarieSchweiz** [comment]
I've been researching the issue recently and you can implement it today, and use it.
Every serious mobile designer would be happy to use it. I do get the idea that it can save you a lot of time today because of the javascript fallback.

Every project gets more attention if there is more visiblity and interest.
Adding it, can be exactly what the project needs.

**Comment by Fyrd** [comment]
Added FLIF as a search result some time back:
https://caniuse.com/#search=flif
Not seeing any new interest from browsers to implement, if they ever start I will re-open this issue for a proper support table.
