### ISSUE TITLE
Add URLSearchParams

### ISSUE THREAD

**Issue by medikoo** [Fyrd/caniuse#2268]
Today I learned about [URLSearchParams](https://developers.google.com/web/updates/2016/01/urlsearchparams) API, wanted to check its support in engines, and got 404

**Comment by cvrebert** [comment]
Exact duplicate of #2213. Did you search?

**Comment by medikoo** [comment]
@cvrebert yes, actually caniuse website linked me directly to search results with following link -> https://github.com/Fyrd/caniuse/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+URLSearchParams
and it didn't reference any issue.

It appears it shows only open issues, so maybe it'll be good to fix that :)

Closing as duplicate then
