### ISSUE TITLE
createImageBitmap

### ISSUE THREAD

**Issue by Prinzhorn** [Fyrd/caniuse#2277]
It allows you to explicitly decode an image (e.g. jpeg) from different sources without using an intermediary Image element. This makes high performance image stuff much faster. For example if you have a jpeg in memory as ArrayBuffer (i.e. from xhr) you can now decode it directly as a Blob created from the ArrayBuffer. The old way would be to use `createObjectURL(blob)` and then loading it using an Image element, which adds a ton of unnecessary latency (can be multiple ms). Another benefit is that it is available inside WebWorkers, which the Image element is not.

It's already shipped in Firefox and in Chrome Canary behind a flag.
- https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmapFactories/createImageBitmap
- https://aerotwist.com/blog/the-hack-is-back/

**Comment by rubenlg** [comment]
Same as https://github.com/Fyrd/caniuse/issues/2801

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=createimagebitmap
