### ISSUE TITLE
Add FontFace API

### ISSUE THREAD

**Issue by jpvincent** [Fyrd/caniuse#2279]
There a JS API that allows to load a FontFace and be warned when it's there. It's good for performance guys like me who want to display text even if the font file is not there yet.
https://developer.mozilla.org/en-US/docs/Web/API/FontFace

Chrome and Firefox (desktop and mobile)  support it

Provided the name of the API is FontFace, exactly like the @FontFace CSS declaration, maybe the unique key should be FontFace-API ?

**Comment by Fyrd** [comment]
The spec refers to this as "CSS Font Loading", which is already covered by http://caniuse.com/#feat=font-loading though I'll make sure "FontFace" is added as a search keyword.

**Comment by jpvincent** [comment]
an alias would be enough, that's true, I dit not thought to type "font loading"
Thanks for taking the time to review this issue
