### ISSUE TITLE
Eric Lopez

### ISSUE THREAD

**Issue by ebscohostericlopez** [Fyrd/caniuse#2280]
It was meant to communicate it was man for a world wide communication to establish freedom the speech and freedom of expression to expand knowledge beyond our imagination and share equally beyond our limits that is to be fair and equal let's not try to be better than anybody let's be equal to everybody.

**Comment by ebscohostericlopez** [comment]
Let's not hide anything from the people let's not be better than anybody else this show equalty amongst each other nobody is different we're all the same so should we all be treated the same amen.

**Comment by Fyrd** [comment]
oooookay
