### ISSUE TITLE
"inherit" keyword

### ISSUE THREAD

**Issue by cniklas** [Fyrd/caniuse#2281]
I typed in `inherit` and expected to find the browsers’ support for the CSS-value "inherit", like here: https://developer.mozilla.org/en-US/docs/Web/CSS/inherit
Instead of that there is "CSS initial value" and "text-emphasis styling" in the result list (and no result for "inherit")

**Comment by Fyrd** [comment]
The results aren't wrong, those are all the caniuse results with the word "inherit" in them.
