### ISSUE TITLE
writing-mode works without prefix in Chrome

### ISSUE THREAD

**Issue by pverbeek** [Fyrd/caniuse#2283]
`writing-mode` doesn't need to be prefixed in Chrome anymore, but I don't know from which version

**Comment by hiddewie** [comment]
This looks like version 48: https://www.chromestatus.com/feature/5707470202732544.

Design document: https://docs.google.com/document/d/1lGrcTSlKMDeOEKZbHqvdLnW_Soywn7oICci2ApBXB00/edit#heading=h.bb8nrgn84zv2.

**Comment by Fyrd** [comment]
Thanks, updated accordingly.
