### ISSUE TITLE
:placeholder-shown data for iOS is inaccurate (actually supported)

### ISSUE THREAD

**Issue by xtoq** [Fyrd/caniuse#2284]
The [page for `:placeholder-shown` pseudo-element](http://caniuse.com/#search=placeholder-shown) shows no support for iOS Safari. I've tested on iOS 9.2.1 with [this CodePen example](http://codepen.io/team/css-tricks/pen/NxdJgV) and it seems to work just fine, at least on that version of iOS.

Since 9.2.x is the most widely used version (6.82%), updating that information could be important.

If you need any additional information, please let me know.

**Comment by chasebank** [comment]
Confirmed on 9.2

**Comment by jeffclayton** [comment]
9.0+ recognized :placeholder-shown, but not 8 or below

**Comment by Schweinepriester** [comment]
+1, also confirmed on 9.2.1. Updating is important.

**Comment by Fyrd** [comment]
Fixed!
