### ISSUE TITLE
How can I get what you consider the current version for a browser from the data.json file

### ISSUE THREAD

**Issue by CaptainQuirk** [Fyrd/caniuse#2286]
Hi there,

How do you ... well, the title sums it up I think ;-). Been looking in the data.json file without being able to understand on what information you decide which browser is the current one !

Thanks !

**Comment by Fyrd** [comment]
I'd recommend using the 2.0 data at https://github.com/Fyrd/caniuse/blob/master/fulldata-json/data-2.0.json then you can simply pick the "current_version" value.

**Comment by CaptainQuirk** [comment]
Hi there,

Sorry that I overlooked it and thanks for your quick answer !
