### ISSUE TITLE
allowfullscreen attribute for iframes

### ISSUE THREAD

**Issue by mhartoft** [Fyrd/caniuse#2291]
The mere existence of mozallowfullscreen and webkitallowfullscreen suggests that allowfullscreen comes with compatibility issues. I blindly just use all 3, while also suppressing my inner fear that IE doesn't support any of it.

**Comment by Schweinepriester** [comment]
+1

- <https://webkit.org/blog/6969/release-notes-for-safari-technology-preview-release-14/>

  > Added support for `HTMLIFrameElement.allowFullscreen`

- <https://trac.webkit.org/changeset/205686>

  > Firefox and Chrome already support it, unprefixed.

- <https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/dev-guide/device/fullscreen-api/>

  > As of Microsoft Edge (build 10240+), this API is unprefixed. …

- MDN: <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#Browser_compatibility>
- Spec: <https://html.spec.whatwg.org/#attr-iframe-allowfullscreen>

**Comment by Malvoz** [comment]
Please note that [Feature-Policy](https://caniuse.com/#feat=feature-policy) introduced the [`allow`](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-allow) attribute. The attributes below (including the `allowfullscreen` as suggested here) are considered [legacy attributes](https://wicg.github.io/feature-policy/#legacy-attributes) and have equivalent `allow` directives. The legacy attributes will be ignored when `allow` is present.

- [`allowfullscreen`](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-allowfullscreen) is equivalent to feature-policy directive `allow="fullscreen"` instead.<br><br>
- [`allowpaymentrequest`](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-allowpaymentrequest) is equivalent to feature-policy directive `allow="payment"` instead.<br><br>
- [`allowusermedia`](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-allowusermedia) is equivalent to feature-policy directive `allow="camera microphone"` instead.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-html_elements_iframe_allowfullscreen
