### ISSUE TITLE
Edge and IE don't support IndexedDB in web workers

### ISSUE THREAD

**Issue by petkaantonov** [Fyrd/caniuse#2292]
https://connect.microsoft.com/IE/feedbackdetail/view/866495

Additionally, given how much IndexedDB blocks (despite being async), it can be unacceptable to run in main thread. So web worker support is not something that should be made so hard to find, it is as critical as any other additional api like multi column keys or whatever IMO.

**Comment by Schweinepriester** [comment]
I believe this issue for https://caniuse.com/indexeddb has been made obsolete by

- IE & Edge Legacy (using EdgeHTML) being marked partial already for various reasons
- Edge covered in known issues: "Microsoft Edge does not support IndexedDB inside blob web workers. [See issue](https://web.archive.org/web/20171213082727/https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5942817/)."
- IE & Edge Legacy being dead
- Time

Hence I believe this issue can be closed.

**Comment by Fyrd** [comment]
Closing as per last comment.
