### ISSUE TITLE
Add ES6 Spread operator

### ISSUE THREAD

**Issue by tjjfv** [Fyrd/caniuse#2293]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator

**Comment by TehShrike** [comment]
This is lumped under the "es6" feature right now

**Comment by tjjfv** [comment]
Closing as rather outdated.

**Comment by lk77** [comment]
I think this is an issue : https://caniuse.com/?search=spread
