### ISSUE TITLE
Support for window.scrollX and window.scrollY

### ISSUE THREAD

**Issue by driq** [Fyrd/caniuse#2294]
Hi, I'm not sure how to add requests for inclusion of availability of browser features, but I would love to see the status of the following feature across browsers:

https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollX
https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY

If you need additional information I'm willing to provide more.

**Comment by 304NotModified** [comment]
+1

**Comment by garrik** [comment]
+1

**Comment by hampelm** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by elviocb** [comment]
+1

**Comment by c43** [comment]
+1

**Comment by myrmecia** [comment]
+1

**Comment by ricokahler** [comment]
+1 I was just about to add this

**Comment by batista** [comment]
and also the aliases `window.pageYOffset` and `window.pageXOffset`

https://developer.mozilla.org/en-US/docs/Web/API/Window/pageYOffset
https://developer.mozilla.org/en-US/docs/Web/API/Window/pageXOffset

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_window_scrolly & https://caniuse.com/#feat=mdn-api_window_scrollx
