### ISSUE TITLE
Please add information about ImageData constructor

### ISSUE THREAD

**Issue by a-rodin** [Fyrd/caniuse#2298]
https://developer.mozilla.org/en-US/docs/Web/API/ImageData/ImageData

**Comment by cvrebert** [comment]
Subfeature of http://caniuse.com/#feat=canvas

**Comment by stianjensen** [comment]
Then Edge apparently does not have full support for the canvas feature?

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_imagedata_imagedata
