### ISSUE TITLE
Position:fixed mobile support wrongly green on Chrome mobile and IE mobile

### ISSUE THREAD

**Issue by virtman** [Fyrd/caniuse#2299]
On mobile devices by using Android mobile Chrome (actual version 48) or by using Microsoft Internet Explorer mobile 10 and upper
the position:fixed in zoomed state has undefined behaviour.
Please change it to "partial support" to not irritate users.

Chrome broke the proper support of position:fixed in zoomed state already in version 46
(according to Chrome the unexpected behaviour in zoom mode is the cause of behaviour replicating from IE mobile, and so causing to not anymore be bound on visible viewport. There is no workaround to reuse old style behaviour on Chrome mobile. For today Chrome broke additionally usage of window.innerWidth/Height and pageX(Y)Offsetl, so no way left anymore to recognize visible viewport on Mobile Chrome to simulate position:fixed via polyfill) So it is pretty unfair to state position:fixed on Mobile Chrome as green and fully supported. Just irritating.

**Comment by cvrebert** [comment]
Are there Chrome bug reports regarding either of those changes?

**Comment by virtman** [comment]
Hello,

yes.
1. http://www.quirksmode.org/blog/archives/2016/02/chrome_change_b.html
2. https://code.google.com/p/chromium/issues/detail?id=571297

**Comment by Fyrd** [comment]
Pretty old bugs at this point that seem to be fixed, so closing this issue.
