### ISSUE TITLE
Add <script type="module"> and module workers

### ISSUE THREAD

**Issue by domenic** [Fyrd/caniuse#2300]
We'd love to add one of those nice caniuse boxes in the margin of the HTML spec for `<script type="module">` and module workers. Nobody implements yet, but everyone is actively implementing!

**Comment by probins** [comment]
`<script type="module">` is available under http://caniuse.com/#feat=es6-module

**Comment by domenic** [comment]
Thanks! Unfortunately that section is not accurate. ES6 modules (specified in ECMA262) are a different feature than `<script type="module">` (specified in HTML).

**Comment by probins** [comment]
well, yes, but the two are interdependent. In practical terms, the answer to 'caniuse modules?' is 'yes, once module scripts are implemented'. @Fyrd, perhaps change the intro text to "Load ES modules as module scripts" or something similar, and add a link to the whatwg html spec as well? Also, Firefox needs adding to the list; its implementation recently landed in nightly behind a flag, and is scheduled for FF54 https://developer.mozilla.org/en-US/Firefox/Releases/54

**Comment by Fyrd** [comment]
This was added with #3594 ( where https://caniuse.com/#feat=es6-module was updated ) so closing this issue.
