### ISSUE TITLE
beforeprint / afterprint

### ISSUE THREAD

**Issue by the-wazz** [Fyrd/caniuse#2301]
not sure if these apply to caniuse. 

i read about them in a newsletter from webtoolsweekly.
http://webtoolsweekly.com/#archive

it will be in issue #134 which is not posted on his site at time of writing this, only in the e-mailed newsletter.

**Comment by cvrebert** [comment]
Duplicate of #1152.

**Comment by the-wazz** [comment]
sry bout that.
