### ISSUE TITLE
HTML DOM selectedIndex attribute (drop-down list)

### ISSUE THREAD

**Issue by TanguyP** [Fyrd/caniuse#2304]
http://www.w3schools.com/jsref/prop_select_selectedindex.asp

The `selectedIndex` attribute for drop-down lists is supported by all major browsers, according to w3schools, but I couldn't find it on caniuse.com

**Comment by Ugoku** [comment]
This is from the [DOM Level 1 spec](https://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/DOM.txt) from 1998, so this should be available everywhere like W3Schools says.

**Comment by TanguyP** [comment]
Just noticed the following in this repo's readme:
"Good/preferred pull requests for new features meet the following criteria:
[...]
- Feature is not already widely supported (e.g. since IE6+, Firefox 2+, Chrome 1+ etc). This is because caniuse is intended to answer questions about mixed support, not to provide complete information on all web technologies."

`selectedIndex` is, clearly, too widely supported to pass that criterion. Should I do a pull request anyway?

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_htmlselectelement_selectedindex
