### ISSUE TITLE
Opera 9.70 with Presto 2.3 rendering engine had partial support for CSS3 `transition`

### ISSUE THREAD

**Issue by Volker-E** [Fyrd/caniuse#2307]
Unlike the current table tells, partial CSS3 `transition`, specifically `-o-transition` support has been implemented in Presto 2.3, which was used in Opera 9.70. So at least the red flagged `10.1` should be flagged with partial support. 
http://www.opera.com/docs/specs/presto23/css/transitions/

**Comment by Fyrd** [comment]
Doesn't seem supported in my test. Do you have a demo that shows it working?
