### ISSUE TITLE
ES5 support is wrong about IE8

### ISSUE THREAD

**Issue by tjcrowder** [Fyrd/caniuse#2308]
At http://caniuse.com/#feat=es5, it says:

> (4) IE8 has virtually no ES5 support, but does support `Object.defineProperty`, `Object.getOwnPropertyDescriptor`, JSON parsing & Property access on strings

This is incorrect. IE8's support for `Object.defineProperty` and `Object.getOwnPropertyDescriptor` is (bizarrely) limited to DOM elements, not JavaScript objects. This is a big caveat that really can't be left off.

**Comment by Fyrd** [comment]
Thanks, updated accordingly.
