### ISSUE TITLE
autofocus attribute buggy in Firefox 44.0.x thru current

### ISSUE THREAD

**Issue by Soundvessel** [Fyrd/caniuse#2310]
We might want to consider Firefox's support of the `autofocus` attribute incomplete as there is an outstanding bug creating issues of users getting scrolled to wrong positions of the page https://bugzilla.mozilla.org/show_bug.cgi?id=712130

Firefox fires `autofocus` before the page is styled. Because the height of everything changes it results in users being put into the wrong position to see the field that is being focused. In the case of a current project I am working on because the navbar code is tall without styling this results in users ending up at the bottom of the page.

**Comment by Fyrd** [comment]
Thanks, added as a known issue.
