### ISSUE TITLE
stopImmediatePropagation,stopPropagation

### ISSUE THREAD

**Issue by wonkzhang** [Fyrd/caniuse#2312]
those should be added.

**Comment by cvrebert** [comment]
> stopImmediatePropagation

MDN has some compat data: https://developer.mozilla.org/en-US/docs/Web/API/Event/stopImmediatePropagation#Browser_compatibility

> stopPropagation

Was added in DOM Level 2, so it's likely "universally" supported. (DOM Level 1 didn't even have an event model.)

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_event_stoppropagation and https://caniuse.com/#feat=mdn-api_event_stopimmediatepropagation
