### ISSUE TITLE
input type password not included

### ISSUE THREAD

**Issue by vincentkupert** [Fyrd/caniuse#2316]
The input type password is not included

**Comment by Ugoku** [comment]
-1
This has been part of HTML since at least [HTML2](https://www.w3.org/MarkUp/html-spec/html-spec_8.html) so is supported everywhere for over 20 years. There's no need to include this.

**Comment by cassiodoroVicinetti** [comment]
-1
[Supported since Internet Explorer 2](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Browser_compatibility)!

**Comment by EndenDragon** [comment]
-1

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-html_elements_input_input-password
