### ISSUE TITLE
:has, :matches & :not with multiple selectors

### ISSUE THREAD

**Issue by matt3224** [Fyrd/caniuse#2325]
These are currently not searchable

**Comment by cvrebert** [comment]
`:has` doesn't have any entry yet: #1268
Neither does `:matches`: #2205

**Comment by cvrebert** [comment]
`:matches` is now at http://caniuse.com/#feat=css-matches-pseudo
`:not` with multiple selectors is part of #1058.

**Comment by Mouvedia** [comment]
Seems to me that this issue can be closed.
