### ISSUE TITLE
Support for the inert attribute

### ISSUE THREAD

**Issue by DAquilina** [Fyrd/caniuse#2332]
I realise that this has been brought up before, but I still think it's relevant since documentation for the attribute appears to be sparse at best.

http://www.quackit.com/html_5/tags/html_5_global_attributes.cfm
http://codepen.io/vasilisvg/pen/scowI

Note that this is *not* in reference to the inert subtrees described in the w3 specifications.

**Comment by cvrebert** [comment]
No such attribute exists. Quackit is in error.
See https://github.com/whatwg/html/pull/22

**Comment by Fyrd** [comment]
Closing as per @cvrebert's point.
