### ISSUE TITLE
Edge still doesn't support SVG filter effects on HTML - should not be marked "Supported"

### ISSUE THREAD

**Issue by Arnavion** [Fyrd/caniuse#2333]
(svg-html)

Specifically, SVG `<filter>` elements referenced using `filter: url("#filter_id")` are not supported. Only the inline CSS phrases like `filter: blur(10)` seem to be supported.

Corresponding Edge bug: ~~https://connect.microsoft.com/IE/feedback/details/2379118~~ https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/6618695/

**Comment by jtakalai** [comment]
That's two different things. IPhone browser doesn't support that either. Distinguish:
1) SVG filter as applied inside the SVG tag
2) SVG filter referenced from CSS filter property using url()

I'll add suggestion for the latter now.

**Comment by Arnavion** [comment]
There is no confusion. The topic is http://caniuse.com/#feat=svg-html "Method of using SVG transforms, filters, etc on HTML elements using either CSS or the foreignObject element"
