### ISSUE TITLE
Add support for CSS Display Module Level 3

### ISSUE THREAD

**Issue by bogdanb** [Fyrd/caniuse#2337]
See https://www.w3.org/TR/css-display-3/

This module describes how the CSS formatting box tree is generated from the document element tree and defines the `display` [actually, it adds values to it] and `box-suppress` properties that control it.

**Available on site now:**
* [display: contents](https://caniuse.com/#feat=css-display-contents)

**Not yet available:**
* [display: run-in](2638)
* [box-suppress](2711)

Votes should be made on individual features so they can be added to the site based on popularity.

**Comment by codynguyen1116** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by tomByrer** [comment]
+1

**Comment by chharvey** [comment]
+1

**Comment by gadtfly** [comment]
+1

**Comment by Ugoku** [comment]
+1

**Comment by gulbanana** [comment]
+1

**Comment by thany** [comment]
+1

**Comment by sabberworm** [comment]
+1

**Comment by rctneil** [comment]
+1  This has been going for over a year now. Can display: contents support please be added? Now that Grid is shipping it would be extremely useful.

**Comment by htmlzengarden** [comment]
[About `display: contents`, MDN already has a support chart available](https://developer.mozilla.org/en-US/docs/Web/CSS/display#Browser_compatibility). (Firefox supports it.)

Other browsers information: 

- [Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=657748),
- [Edge](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/10938981-implement-the-box-generation-keywords-from-css-dis),
- [Safari](https://bugs.webkit.org/show_bug.cgi?id=157477).

(Thanks to @rik for the links.)

**Comment by jensimmons** [comment]
We really need a page for `display: contents;`
We already have one for `display: flow-root;`

I don't have a strong opinion about a parent page for everything `display: *`. I just know we need a simple way to see what's up with `display: contents;` It's going to be a bigger and bigger thing, now that CSS Grid is here.

**Comment by rik** [comment]
With the information provided in https://github.com/Fyrd/caniuse/issues/2337#issuecomment-28853209, I think all we need is to create a JSON by following the instructions at https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md

**Comment by Fyrd** [comment]
Support for `display: contents` is now available at https://caniuse.com/#feat=css-display-contents

This issue will remain open for other properties from this module.

**Comment by chharvey** [comment]
*Unrelated, but not worthy of a separate issue:*

Searching for “display contents” yields no results, but “contents” does.

http://caniuse.com/#search=display%20contents
http://caniuse.com/#search=contents

**Comment by Fyrd** [comment]
Since box-suppress has its own issue and the other values are available on the site, I think it's safe to close this issue.
