### ISSUE TITLE
Add support info for `rel=noopener`

### ISSUE THREAD

**Issue by mathiasbynens** [Fyrd/caniuse#2342]
https://html.spec.whatwg.org/multipage/semantics.html#link-type-noopener

https://mathiasbynens.github.io/rel-noopener/

Supported in:

* Opera 36
* Chrome 49

Bug tickets to track:

* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1222516
* Safari: https://bugs.webkit.org/show_bug.cgi?id=155166
* Edge: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/12942405-implement-rel-noopener

**Comment by codynguyen1116** [comment]
+1

**Comment by mathiasbynens** [comment]
@Fyrd Let me know if there’s anything I can do to help make this go live soon. :)

**Comment by Fyrd** [comment]
@mathiasbynens Sorry, been a bit busy working on the caniuse backend code, but I should be able to get to it soon. If you could write a simple test to test support that would be much appreciated though. :)

**Comment by mathiasbynens** [comment]
Clicking the last highlighted link on https://mathiasbynens.github.io/rel-noopener/ is the simplest test case I can come up with.

**Comment by Schweinepriester** [comment]
+1 btw. :)

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=rel-noopener
