### ISSUE TITLE
HTMLElement.offsetTop

### ISSUE THREAD

**Issue by boric** [Fyrd/caniuse#2345]
Add support for HTMLElement.offsetTop in the DOM.

https://drafts.csswg.org/cssom-view/#dom-htmlelement-offsettop
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetTop
https://msdn.microsoft.com/en-us/library/ms534303(VS.85).aspx

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_htmlelement_offsettop
