### ISSUE TITLE
Which browsers adhere to ETag?

### ISSUE THREAD

**Issue by jnfsmile** [Fyrd/caniuse#2346]
Doesn't currently appear

**Comment by Ugoku** [comment]
Currently wondering this myself. According to [this SO question](http://stackoverflow.com/questions/6247761/browser-support-for-etags) it's well supported in IE5.5+ and other browsers, so in short "all browsers of the past 15 years"

**Comment by adrian7** [comment]
Although should be supported in all browsers, ETag/If-None-Match info would be useful.

**Comment by Schweinepriester** [comment]
Available via MDN:
- https://caniuse.com/mdn-http_headers_etag
- https://caniuse.com/mdn-http_headers_if-none-match
