### ISSUE TITLE
WebStorage (possible) bug

### ISSUE THREAD

**Issue by Havock94** [Fyrd/caniuse#2349]
At the 5th point in the WebStorage page [here](http://caniuse.com/#feat=namevalue-storage) you can read:

"In private browsing mode, Safari, iOS Safari and the Android browsers do not support setting sessionStorage or localStorage."

I've just tried with Google Chrome for Android and correctly managed to create/edit/delete/read values from localStorage in Incognito Mode.

Can anyone else confirm this? If so, that point should be corrected :)

**Comment by Ugoku** [comment]
Google Chrome for Android is not the same as the Android browser.

By "Android browsers" I think "multiple versions of the Android browser" is meant, not "all Android browsers"

**Comment by Fyrd** [comment]
Updated the note to specify that it does not include Chrome for Android.
