### ISSUE TITLE
Flexbox: Add known issue regarding Safari 9

### ISSUE THREAD

**Issue by ffxsam** [Fyrd/caniuse#2353]
I discovered a big problem in Safari 9, where simply doing `flex: 1` will not suffice where you also have a `min-width` set on the item, as the items will expand outside the container. This is the workaround:

    flex: 1 0 auto;

See this fiddle: https://jsfiddle.net/ffxsam/x96tx1y5/

Observe in Safari, resize the panes to shrink the container. Then change `flex: 1 0 auto;` to simply `flex: 1;` and hit run. Compare with Chrome.

**Comment by cvrebert** [comment]
Perhaps you're describing https://github.com/philipwalton/flexbugs#11-min-and-max-size-declarations-are-ignored-when-wrapping-flex-items ?

**Comment by ffxsam** [comment]
Yep, I believe that's it.

**Comment by Fyrd** [comment]
Added as known issue (though I'm thinking of replacing the whole list with a single bug pointing to the the flexbugs repo)...
