### ISSUE TITLE
Opera supports CSS Variables since version 36

### ISSUE THREAD

**Issue by mgol** [Fyrd/caniuse#2359]
Opera v36 (currently in beta) is based on Chromium 49 and hence supports CSS Variables.

BTW, could Opera n by default inherit the state of Chrome n+13? They keep their versions in sync, the engine is not tweaked too much compared to other Chromium clones so that would should give the best results.

**Comment by Fyrd** [comment]
Fixed.

Yeah, I have a tool that lets me compare the two to ensure they stay in sync most of the time, while still allowing for various exceptions. That's a manual process though, new versions always default to being the same as the previous version which seems safer (best to err on the side of "not supported"). And looks like this one just kind of fell through the cracks.
