### ISSUE TITLE
Rename CSS Variables to CSS Custom Properties

### ISSUE THREAD

**Issue by mgol** [Fyrd/caniuse#2360]
The name has changed from CSS Variables to CSS Custom Properties some time ago (see [the spec](https://drafts.csswg.org/css-variables/)).

**Comment by mgol** [comment]
I linked to the Editor's Draft but even the latest Candidate Recommendation uses this name: https://www.w3.org/TR/css-variables-1/

**Comment by Fyrd** [comment]
Done. I've left it as "CSS Variables (Custom Properties)" for now though since they're still basically a type of variable and many people are still used to the older name. May change that in the future.

**Comment by mgol** [comment]
Thanks! I was looking for CSS Properties on the site & couldn't find it
before I reminded myself they may still be named variables. Including both
names solves that problem.

-- 
Michał Gołębiowski
