### ISSUE TITLE
Add KeyboardEvent.repeat compatibility info

### ISSUE THREAD

**Issue by kit-tolma** [Fyrd/caniuse#2367]

**Comment by cvrebert** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

From <https://webkit.org/blog/6987/release-notes-for-safari-technology-preview-15/>:

> Implemented KeyboardEvent.prototype.repeat from the UI Event spec

**Comment by Schweinepriester** [comment]
Available via MDN now: <https://caniuse.com/mdn-api_keyboardevent_repeat>
