### ISSUE TITLE
Email Client Compatibility

### ISSUE THREAD

**Issue by mattisherwood** [Fyrd/caniuse#2376]
Feature request: Could you also have (perhaps grouped or tabbed together, another set of pages, or even on a sister site) the same search functionality as for browser support, but for email client support? (Such as [this info](https://www.campaignmonitor.com/css/))
Email client compatibility is obviously a **big** issue with designing/coding for email, and so this would be **hugely** helpful, I'm guessing to others as well as myself!

**Comment by cvrebert** [comment]
Duplicate of #2017.

**Comment by mattisherwood** [comment]
Ah cheers, hadn't spotted that. Not to worry.
