### ISSUE TITLE
form:valid doesn't work in IE11

### ISSUE THREAD

**Issue by in-in** [Fyrd/caniuse#2384]
But the article does not mention about it.
http://caniuse.com/#search=valid

**Comment by cvrebert** [comment]
Confirmed.
Testcase: http://output.jsbin.com/yunijih/quiet
Screenshot (background would be green if `:valid` worked properly):
<img width="803" alt="ie11-form-valid-pseudo" src="https://cloud.githubusercontent.com/assets/419884/14090331/7f89516c-f4ee-11e5-8838-ab4dac569a42.png">

**Comment by rebolyte** [comment]
Also doesn't work in Edge 13.

**Comment by Fyrd** [comment]
Added known issue for this. Seems Firefox has a similar problem, though in some cases it will recognize it.
