### ISSUE TITLE
Can not search hasAttribute

### ISSUE THREAD

**Issue by yubaoquan** [Fyrd/caniuse#2385]
Is this api deprecated?

**Comment by cvrebert** [comment]
Supported in IE8+ and basically all other browsers: http://quirksmode.org/dom/core/#t125

**Comment by J3QQ4** [comment]
Doesn't look like it's supported in IE9. 

Can we add hasAttribute into the website please?

**Comment by cvrebert** [comment]
@J3QQ4 Looks like it's supported in IE9: https://saucelabs.com/beta/tests/bbd6ac3085e341d4afd248007199c469/watch
(Testcase: http://jsbin.com/xajuwam/edit?html,js )

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_element_hasattribute
