### ISSUE TITLE
Support httpS://caniuse.com

### ISSUE THREAD

**Issue by relaxnow** [Fyrd/caniuse#2387]
You  used to support embeding on HTTPS, but no longer do which breaks my blog post: https://www.ibuildings.nl/blog/2013/03/4-http-security-headers-you-should-always-be-using

Any chance that is coming back?

**Comment by pepelsbey** [comment]
It’s even worse: [HTTPS links](https://caniuse.com/#feat=css-variables) couldn’t be opened: `https://caniuse.com/#feat=css-variables`

**Comment by Schweinepriester** [comment]
Kinda dub of #885. But yeah, with Let's Encrypt around it really should be HTTPS already…

**Comment by Fyrd** [comment]
Yeah, duplicate of #885.

The caniuse embed system is basically deprecated anyway, there's some others out there like http://caniuse.bitsofco.de/ which you can try instead.
