### ISSUE TITLE
Add stale-while-revalidate HTTP header support indication

### ISSUE THREAD

**Issue by derekdata** [Fyrd/caniuse#2391]
stale-while-revalidate is a HTTP header that has been proposed as in [RFC 5861](http://tools.ietf.org/html/rfc5861).  It has limited, but hopefully growing, browser support.

**Comment by orzage** [comment]
+1

Would love to see this gain support.

**Comment by DareBoost** [comment]
+1

**Comment by justinfagnani** [comment]
+1

**Comment by medfx** [comment]
+1

**Comment by chrisblakley** [comment]
+1

**Comment by baryluk** [comment]
+1

Some extra material:

https://tools.ietf.org/html/rfc5861  proposed in 2010.

https://www.fastly.com/blog/stale-while-revalidate-stale-if-error-available-today suggest it was used already in 2014, and probably a bit before that.

No idea what was the client support tho.

Implemented and enabled by default in current Chromium. Probably in 75+ - https://www.chromestatus.com/feature/5050913014153216

Not sure about Firefox.

MDN website is a bit stale in their matrix : https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Browser_compatibility - it says no for all brower.

**Comment by mnot** [comment]
Swr and sie were first implemented in squid in the late 2000’s (sponsored by yahoo).

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-http_headers_cache-control_stale-while-revalidate
