### ISSUE TITLE
Add UIR - Upgrade Insecure Requests - partial support already

### ISSUE THREAD

**Issue by tantek** [Fyrd/caniuse#2392]
Add caniuse.com/UIR - Upgrade Insecure Requests - https://www.w3.org/TR/upgrade-insecure-requests/

Already supported in latest Firefox and Chrome.
Not yet in latest Safari and Edge.

Helpful for sites transitioning to HTTPS-only with lots of legacy links to HTTP resources (both in legacy content and externally).

**Comment by cvrebert** [comment]
Already exists: http://caniuse.com/#feat=upgradeinsecurerequests
