### ISSUE TITLE
Prefixed Grid Layout implementation in WebKit & Safari TP

### ISSUE THREAD

**Issue by pepelsbey** [Fyrd/caniuse#2394]
There’s a lack of data regarding prefixed [Grid Layout](http://caniuse.com/#search=grid) implementation in WebKit nightlies and Sarari TP. According to @ai it’s the only thing that stops Autoprefixer from prefixing Grid Layout.

Since Safari TP reports itself as 9.1.1 (stable on is 9.1) it could be added as next version of Safari.

So this task might be related to #2393 then.

**Comment by Fyrd** [comment]
Safari TP has now been added, so closing this issue.
