### ISSUE TITLE
Update currentVersion of Opera

### ISSUE THREAD

**Issue by pepelsbey** [Fyrd/caniuse#2395]
Current versions of Opera browsers are out of date and unfortunately I couldn’t find a place in JSON to fix it and send a PR. Opera for desktop is [36 for a 15 days](https://dev.opera.com/blog/opera-36/) alredy and Opera for Android [became 36 today](http://www.opera.com/blogs/mobile/2016/03/brand-new-tab-switcher-web-app-discovery-opera-36-android/).

I’ll be glad to keep those numbers up to date myself (as Opera representative) if only I could find a proper place to edit `currentVersion`. Could you please help me?

**Comment by Fyrd** [comment]
That's not something others can update, but if you can let me know when caniuse is behind in the future I'll be happy to update asap. Just did the update for both. Thanks!
