### ISSUE TITLE
Promise is available in IE11

### ISSUE THREAD

**Issue by zcyzcy88** [Fyrd/caniuse#2396]
Test on Windows 7:
![image](https://cloud.githubusercontent.com/assets/15178410/14200333/b361c9d4-f81c-11e5-8e95-14902c7a27a4.png)
![image](https://cloud.githubusercontent.com/assets/15178410/14200465/b820e85a-f81d-11e5-9d11-43656efcc783.png)

**Comment by Ugoku** [comment]
According to [kangax' ES6 site](https://kangax.github.io/compat-table/es6/) this should not be available in IE11. [Microsoft](https://msdn.microsoft.com/nl-nl/library/dn802826(v=vs.94).aspx) also says it doesn't work in IE11.

**Comment by Fyrd** [comment]
Right, pretty sure that's Edge you're showing a screenshot of with support, not IE11.
