### ISSUE TITLE
Can we use GitHub's reaction feature for issue voting?

### ISSUE THREAD

**Issue by enterprisey** [Fyrd/caniuse#2408]
[Recently](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments), GitHub implemented a "reactions" feature, allowing users to +1 issues without commenting.

I think it should be possible to have the issue "leaderboard" also read +1's left via this feature, in addition to the regular +1 comments.

This would help with, among other things, notification overload from issues that a given user has already commented on.

**Comment by codynguyen1116** [comment]
we can and should! in fact i gave yours a +1 ;)

**Comment by Fyrd** [comment]
I'd love to, but currently this data doesn't seem to be exposed yet by the GitHub API.

**Comment by Schweinepriester** [comment]
I'd like to emphasize the addition for when its exposed by the API:

> I think it should be possible to have the issue "leaderboard" also read +1's left via this feature, **in addition to the regular +1 comments**.

**Comment by jimmywarting** [comment]
There is a good way to sort on reactions ;)
is:issue is:open sort:reactions-+1-desc

**Comment by APerson241** [comment]
So can this be done with HTML scraping, since it's presumably still inaccessible via the API?

**Comment by jimmywarting** [comment]
I think it is accessible via the api...

**Comment by APerson241** [comment]
@Fyrd I can't seem to track down the code that generates http://caniuse.com/issue-list; is it accessible on GitHub, so I could possibly submit a patch?

**Comment by Fyrd** [comment]
Looks like using the new api is the way to go, will look into it a week from now when I'm back from vacation.

@APerson241 Nope, that code's not on github.

**Comment by gagern** [comment]
The FAQ item which states “Feel free to add/vote for your feature there” might benefit from some more explicit formulation once this is in place. Something like “Feel free to add a 👍 reaction via the “+😀”  button to already requested features, or add a new request if there is no matching one.”

**Comment by calvinjuarez** [comment]
Any updates here?

**Comment by APerson241** [comment]
@Fyrd any way to either open-source the feature suggestion list code or otherwise make progress on using the Reactions API for this?

**Comment by Fyrd** [comment]
I still plan on doing this, but would really rather wait until the Reactions API is out of Preview. In the mean time I do actually occasionally check the issues in order by most thumbs up votes and have been adding the highest rated ones as well.

**Comment by Flimm** [comment]
It looks like GitHub's reactions API is still in preview, sadly.

**Comment by Fyrd** [comment]
Using the latest version of GitHub's API, https://caniuse.com/issue-list is now based on thumbs up reactions instead of comments! I think there's a large overlap in comment votes and reactions and most people have switched to reactions for the past few years so for now I don't think I'll bother including the comment votes.

**Comment by aozq** [comment]
@Fyrd et al.. I am interested in creating a tool to easily create a page like https://caniuse.com/issue-list  on GitHub Pages for anyones repo. Ive started a project repo here: https://github.com/aozq/GitHubSortByVotes to kick off discussion until I can dig into the coding (which actually shouldnt be too hard).

Here's what I propose:
1) ask Fryd for tips on accessing the API and her script to automatically update her site every hour
2) consider using the stock Jekyll GH Pages template
3) consider how to update the Jekyll using a script likely hosted on GCP, possibly a simple Cloud Function
4) understand the API calls to retrieve the number of likes per issue, and sort the issues in an HTML scriptable (JS?) table or iframe. 
5) likely sort using Cloud Function to create an http linkable iframe to use in a static GitHub Page.
6) write up the instructions and template script in the repo above

Anyone who would like to see this as a standardized tool for easily visualizing GH issue based on their userbase's demand, by all means please jump in! Thanks!

And thanks Fyrd for bringing this new functionality to my attention.. have been waiting quite a while to be able to sort GH issues in a more readable format than using sort on GH.
