### ISSUE TITLE
CSS Paint API

### ISSUE THREAD

**Issue by nkronlage** [Fyrd/caniuse#2415]
Spec: https://drafts.css-houdini.org/css-paint-api/

Chrome: https://www.chromestatus.com/features/5685444318593024
Edge: ?
FireFox: 
WebKit: https://webkit.org/status/#specification-css-painting-api-level-1

**Comment by orzage** [comment]
+1

**Comment by nkronlage** [comment]
Here are some useful links:

* https://github.com/GoogleChrome/houdini-samples
* https://developers.google.com/web/updates/2016/05/houdini

**Comment by dkrnl** [comment]
CSS Paint API available in Chrome 65!
https://developers.google.com/web/updates/2018/01/paintapi

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=css-paint-api
