### ISSUE TITLE
findIndex Array method doesn't added to caniuse.com DB

### ISSUE THREAD

**Issue by m0sk1t** [Fyrd/caniuse#2416]
For more info go to [https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex](url)

**Comment by lifenstein** [comment]
[Link to English version of Mozilla Dev Docs](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex)

[Reference in ECMAScript 2015 (6th Edition, ECMA-262)](http://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.findIndex).

**Comment by catcher-in-the-try** [comment]
The request has been pending for almost two years. 

Can someone please add it to caniuse.com?

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=array-find-index
