### ISSUE TITLE
Data for HTML figure/figcaption elements

### ISSUE THREAD

**Issue by LjWatson** [Fyrd/caniuse#2418]
Would be useful. Thanks.

**Comment by Ugoku** [comment]
Already exists: http://caniuse.com/#search=figure

**Comment by LjWatson** [comment]
@Ugoku
Thanks! Was fooled because it doesn't seem to be included in the list of elements on the homepage?

**Comment by Fyrd** [comment]
Yeah, browsers started supporting `figure` & `figcaption` together with a bunch of other semantic HTML5 elements so they're grouped together at http://caniuse.com/#feat=html5semantic
