### ISSUE TITLE
Network Service Discovery

### ISSUE THREAD

**Issue by digitalreb** [Fyrd/caniuse#2420]
Spec: https://www.w3.org/TR/discovery-api/ (Working Draft)

Seems only Opera supports it for now (experimentally): https://dev.opera.com/articles/network-service-discovery-api/

Other browsers have it in consideration:
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/HT0KZKuTLxM
https://bugzilla.mozilla.org/show_bug.cgi?id=914579

**Comment by orzage** [comment]
+1

**Comment by Schweinepriester** [comment]
<https://www.w3.org/TR/discovery-api/>:

> W3C Working Group Note 12 January 2017

> Work on this document has been discontinued and it should not be referenced or used as a basis for implementation. The [Presentation API](https://www.w3.org/TR/presentation-api/) and the [Remote Playback API](https://www.w3.org/TR/remote-playback/) address a subset of the use cases this API attempted to address.

**Comment by Fyrd** [comment]
Closing as per above.
