### ISSUE TITLE
Web Authentication (webauthn)

### ISSUE THREAD

**Issue by richardszalay** [Fyrd/caniuse#2423]
Spec: http://w3c.github.io/webauthn/

Edge: Supports an early revision - vendor prefixed and currently restricted to Windows Hello (https://blogs.windows.com/msedgedev/2016/04/12/a-world-without-passwords-windows-hello-in-microsoft-edge/)
Chrome: ?
Firefox: ?

**Comment by xtian** [comment]
+1

**Comment by williambanks** [comment]
*bump*

**Comment by equalsJeffH** [comment]
WebAuthn 5th working draft revision (WD-05) is an informal "implementors draft" 
http://identitymeme.org/archives/2017/05/07/web-authentication-working-draft-rev-5-wd-05/

FYI: Intent to implement and ship: Web Authentication (Mozilla, 14 Nov 2016)
https://lists.w3.org/Archives/Public/public-webauthn/2016Nov/0177.html

Edge is implementing WD-05 
https://lists.w3.org/Archives/Public/public-webauthn/2016Nov/0177.html

Intent to Implement: Web Authentication API for Chrome 
https://groups.google.com/a/chromium.org/forum/#!searchin/blink-dev/authentication/blink-dev/qCJhuuZH5p0/le6l1t37AQAJ

**Comment by Calico90** [comment]
+1 (and please add it in the Security category, not Other).

**Comment by oskarer** [comment]
Enabled by default in FIrefox 60; https://hacks.mozilla.org/2018/01/using-hardware-token-based-2fa-with-the-webauthn-api/

**Comment by dsanders11** [comment]
+1

**Comment by 304NotModified** [comment]
It's now a W3C Candidate Recommendation

https://www.w3.org/TR/webauthn/

**Comment by eitan101** [comment]
https://www.theverge.com/2018/4/10/17215406/webauthn-support-chrome-firefox-edge-fido-password-free

**Comment by dstorey** [comment]
This should probably replace FIDO1 that is currently on CanIUse… (WebAuth was originally FIDO2)

**Comment by mkurz** [comment]
+1

**Comment by abergs** [comment]
Yes we need to get webauthn up there. Here's the json from the repo: https://github.com/w3c/webauthn/blob/b0cae5e2fb2b6e0d7f25a2153768e137a01423f1/.spec-data/caniuse.json

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=webauthn

**Comment by dstorey** [comment]
@fryd This isn't correct. Edge supports WebAuth since EdgeHTML13, just with an earlier draft syntax.

**Comment by dstorey** [comment]
…while EdgeHTML18 has just been updated to support the final syntax and remove the old one.

**Comment by Fyrd** [comment]
@dstorey Thanks, will update. Do you expect it to no longer be behind a flag for EdgeHTML18?

**Comment by dstorey** [comment]
The final version won't be behind a flag in 18. The current  version using Navigator.authentication et al isn't behind a flag already (which is why HTML5test picks it up)

**Comment by chris-morgan** [comment]
For completeness: it’s been available in Firefox via the security.webauth.webauthn flag since 57. (It was there in 56, but comparatively useless as U2F support hadn’t landed yet, so it was soft tokens only, if I recall correctly.)

**Comment by dstorey** [comment]
This should also probably cover if U2F and/or biometrics too. Not sure what the other browsers support.

**Comment by equalsJeffH** [comment]
I would not _**replace**_ https://caniuse.com/#feat=u2f with [webauthn](https://www.w3.org/TR/webauthn/) -- rather keep them both.  at some point chrome and firefox will deprecate u2f but that will not be occurring right away.

It would really be nice to get webauthn aka "Web Authentication" to be listed on CanIUse, pretty please :)

**Comment by 304NotModified** [comment]
> It would really be nice to get webauthn aka "Web Authentication" to be listed on CanIUse, pretty please :)

It's already online? https://github.com/Fyrd/caniuse/issues/2423#issuecomment-387959421

**Comment by equalsJeffH** [comment]
Thanks all for getting it up there!!
