### ISSUE TITLE
Offscreen Canvas

### ISSUE THREAD

**Issue by nkronlage** [Fyrd/caniuse#2424]
Spec: https://wiki.whatwg.org/wiki/OffscreenCanvas

Chrome: https://www.chromestatus.com/features/5424182347169792
Edge: ?
FireFox: https://platform-status.mozilla.org#offscreencanvas
Safari: ?

**Comment by giorgiobeggiora** [comment]
+1

**Comment by Kitanga** [comment]
Please show the data for this

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=offscreencanvas

**Comment by Kitanga** [comment]
Thanks @Fyrd
