### ISSUE TITLE
MediaCapture Screen Share

### ISSUE THREAD

**Issue by RataDP** [Fyrd/caniuse#2426]
**Title**: getDisplayMedia

**Spec**: [MediaCapture Screen Share](https://w3c.github.io/mediacapture-screen-share) _(Editor's Draft)_ by Martin Thomson, Mozilla & Keith Griffin, Cisco

Seems like any browser support this feature at now. It is a good feature to know when the browsers implement it and we can use it

**Comment by frederikbosch** [comment]
As of yesterday, [Blink announced the intent to support it](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/j7k2nI_9nng).

**Comment by frederikbosch** [comment]
And this is [the tracking bug](https://bugs.chromium.org/p/chromium/issues/detail?id=326740) for the implementation.

**Comment by frederikbosch** [comment]
This is [already support on Edge](https://blogs.windows.com/msedgedev/2018/05/02/bringing-screen-capture-to-microsoft-edge-media-capture-api/).

**Comment by frederikbosch** [comment]
The [tracking bug for Firefox is to found here](https://bugzilla.mozilla.org/show_bug.cgi?id=1321221).

**Comment by frederikbosch** [comment]
For Safari I am not able to find the current status or roadmap, but I have found [the source code of Webkit containing the `getDisplayMedia` method](https://github.com/WebKit/webkit/blob/master/Source/WebCore/Modules/mediastream/MediaDevices.cpp). I have no idea of its status or intent.

**Comment by frederikbosch** [comment]
The current master of WebKit does contain [actual code to show screens, applications, windows and browsers](https://github.com/WebKit/webkit/blob/master/Source/WebCore/platform/mediastream/RealtimeMediaSourceCenter.cpp#L264).

**Comment by thijstriemstra** [comment]
This example worked fine for me on OSX Firefox 62.0.2 and Chrome 70.0.3538.35 (Official Build) beta (64-bit): https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/

I'll see if I can make a pull request..

**Comment by okayawright** [comment]
> 
> 
> This example worked fine for me on OSX Firefox 62.0.2 and Chrome 70.0.3538.35 (Official Build) beta (64-bit): https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/
> 
> I'll see if I can make a pull request..

This is not supported yet in Firefox, the WebRTC demo relies on adapter.js which plays with MediaDevices.getUserMedia() behind the curtains for 62.0.x

**Comment by thijstriemstra** [comment]
> This is not supported yet in Firefox

I recorded a webm clip of my screen in firefox using `getDisplayMedia`, not sure if that counts but 😉 If the API works it works, no? Not sure what you mean.

**Comment by frederikbosch** [comment]
@thijstriemstra You are using a shim/polyfill for the standard API. See the [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1321221) and the [intent to ship message](https://groups.google.com/forum/#!topic/mozilla.dev.platform/20EhEy_ahKg) here.

> Do other browser engines implement this?
>   • Edge: Yes [1]
>   • Chrome Canary: Behind pref [2]
>   • Safari TP: behind pref [3]
>   • Firefox: Only through shim (either fullscreen or windows) [4]
>   • Chrome: Only through shim and plugin [4] 

Firefox now supports it through a shim, a wrapper library that converts the Firefox method to the standard method. This means you can use it already, but not *directly* through the standard only via the wrapper through their own implementation of screen sharing. They do, however, indicate that they will start supporting the standard, and support it on a short notice.

**Comment by thijstriemstra** [comment]
thanks for the detailed feedback! I'm shipping it in my lib anyway ;)

**Comment by julian-alarcon** [comment]
Chrome 72 support it by default  since yesterday: https://addpipe.com/blog/standards-compliant-screen-capture-in-chrome-72/

Also Firefox 66 support this too: https://bugzilla.mozilla.org/show_bug.cgi?id=1321221

Documentation: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia
Examples: https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture

**Comment by udta** [comment]
Safari preview 75 supports this feature : https://webkit.org/blog/8594/release-notes-for-safari-technology-preview-75/?__s=pwtudzbyw565tnd71paw
To test this feature, you need to check: Develop -> Experimental Features -> ScreenCapture

**Comment by julian-alarcon** [comment]
This should be added. Still waiting.

**Comment by silviapfeiffer** [comment]
By the release of Edge based on blink, all major browsers (Chrome, Firefox, Safari and Edge) will support this - I think it's time this feature got added.

**Comment by Utopiah** [comment]
So, who wants to do the PR? :smile:

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_mediadevices
