### ISSUE TITLE
adding information about the window.error

### ISSUE THREAD

**Issue by valtido** [Fyrd/caniuse#2428]
I was looking at the following page/table, although this is really good information, this isn't what I was interested in.

http://caniuse.com/#search=error

I think you may want to add `window.error` into the table.

As a side note: http://caniuse.com/feed/156 you have mentioned that github does not have a voting system, I think that github has incorporated that, so that text might need chaning :)

**Comment by cvrebert** [comment]
Do you mean `window.onerror` (#1199)?

**Comment by Fyrd** [comment]
Closing in favor of #1199 since there's no window.error

**Comment by valtido** [comment]
It's been a long time, since this to remember what I was talking about but maybe `window.onerror` or `window.Error` could be something I would think of as of now.
