### ISSUE TITLE
String.prototype.toLowerCase and String.prototype.toUpperCase

### ISSUE THREAD

**Issue by mbplautz** [Fyrd/caniuse#2431]
toLowerCase and toUpperCase do not appear to be listed in CanIUse, and if they are, they are not easy to search.

**Comment by nkronlage** [comment]
These have been around since ECMAScript 1.0 and should be supported everywhere.

http://www.ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-262,%201st%20edition,%20June%201997.pdf

**Comment by Fyrd** [comment]
Now has search result:
http://caniuse.com/#search=tolowercase
