### ISSUE TITLE
IE10 missing from table

### ISSUE THREAD

**Issue by tobireif** [Fyrd/caniuse#2436]
On eg http://caniuse.com/#feat=css3-colors there's IE8, IE9, and IE11, but not IE10.

**Comment by Fyrd** [comment]
It's just hidden by default because global usage has fallen below 0.5%. You can change that threshold under Settings.

**Comment by tobireif** [comment]
Thanks for the info!

In Settings I set "Min. browser usage: 0.4%:" - now IE10 is listed.

This page
https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0
reports 2.84% for IE10 .

This one
http://gs.statcounter.com/#browser_version_partially_combined-ww-monthly-201503-201603
reports 0.8% .

Perhaps the data used for caniuse.com could include these sources?

**Comment by Fyrd** [comment]
@tobireif The Caniuse data uses the statcounter data, but the percentage is based on desktop + mobile which is why it appears less than the number you see there.

**Comment by tobireif** [comment]
Thanks for the info!
