### ISSUE TITLE
"once" event listeners

### ISSUE THREAD

**Issue by cvrebert** [Fyrd/caniuse#2438]
Basically, native support in `.addEventListener()` for one-time event callbacks, like you get with jQuery's `$.one()`.
* https://dom.spec.whatwg.org/#dom-addeventlisteneroptions-once
* https://github.com/whatwg/dom/pull/207

**Comment by jimmywarting** [comment]
Wow, that is something i have wanted for a long time!
Would rather want node's version `.on()` `.off()` & `.once()` but hey, this is better then nothing

**Comment by cvrebert** [comment]
Implemented in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1287706

**Comment by cvrebert** [comment]
Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=615384

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=once-event-listener

**Comment by jimmywarting** [comment]
is it possible to polyfill?

**Comment by cvrebert** [comment]
Most likely yes.

**Comment by jimmywarting** [comment]
```javascript
;(function(){
	let x = document.createElement('x')
	let i = 0
	let event = new CustomEvent('x')

	x.addEventListener('x', () => {i++})
	x.dispatchEvent(event)
	x.dispatchEvent(event)

	if (i != 2) return

	for (let obj of [Window, Element]) {
		let orig = obj.prototype.addEventListener
		function addEventListener(type, callback, opts) {
			let args = Array.from(arguments)
			if(opts && opts.once) {
				function handler(e) {
					callback.call(this, e)
					this.removeEventListener(type, handler)
				}
				args[1] = handler
			}
			orig.apply(this, args)
		}
		
		obj.prototype.addEventListener = addEventListener
	}
}())

window.addEventListener('resize', console.log, {once: true})
```
