### ISSUE TITLE
Browser Support by Age rather than Version

### ISSUE THREAD

**Issue by manngo** [Fyrd/caniuse#2463]
Browser such as Firefox and Chrome have very short release cycles while Safari and IE/Edge have much longer cycles. As such, whether a feature was supported, say, two versions ago, has a different meaning for these browsers.

It may be helpful to display this information by relative release date. So for example, a feature which was implemented in versions, say, 1 year ago, would be be safer to use than features implemented 2 versions ago.

**Comment by cvrebert** [comment]
Duplicate of #202?

**Comment by manngo** [comment]
Agreed. I’ll add comments to that instead. Thanks
