### ISSUE TITLE
Object.hasOwnProperty

### ISSUE THREAD

**Issue by amn** [Fyrd/caniuse#2464]
I could not find support entry for above browser API function. What are the chances of adding its support stats?

**Comment by cvrebert** [comment]
[It's part of ES3](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty#Specifications), so it's most likely "universally" supported.
Although there is 1 wrinkle in IE<9: http://stackoverflow.com/a/8159434

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_builtins_object_hasownproperty
