### ISSUE TITLE
preventDefault

### ISSUE THREAD

**Issue by englishextra** [Fyrd/caniuse#2466]
is not supported by IE8

The polyfill (not mine) is there 

https://gist.github.com/chriswrightdesign/7573368

**Comment by cvrebert** [comment]
Could be integrated into http://caniuse.com/#feat=addeventlistener , since it seems to be shorthand for the W3C DOM event model in general.

**Comment by Horray** [comment]
I tried searching http://caniuse.com/#search=preventDefault, and nothing came up. I then came up with this page.
Is addeventlistener supported the same amount as preventDefault?

**Comment by mediaformat** [comment]
+1

**Comment by Fyrd** [comment]
Added to http://caniuse.com/#feat=addeventlistener as per @cvrebert's suggestion (yes, support is the same).
