### ISSUE TITLE
ActiveX

### ISSUE THREAD

**Issue by mingtsay** [Fyrd/caniuse#2467]
I hope ActiveX goes into caniuse. Don't blame me 😜

**Comment by berry120** [comment]
Doesn't seem a great deal of point - it was only ever supported in IE, and since Edge dropped support it (realistically) won't be implemented in any browser going forward.

**Comment by Schweinepriester** [comment]
With the demise of IE11 sealed, I think this can take the same fate as Silverlight, getting a search result linking to to Wikipedia (=> https://en.wikipedia.org/wiki/ActiveX) and then this issue can be closed 0:-)

**Comment by Fyrd** [comment]
Search result now available: https://caniuse.com/?search=activex
