### ISSUE TITLE
CSS Property caption-side is missing?

### ISSUE THREAD

**Issue by Laffer73** [Fyrd/caniuse#2477]
I wonder why i cannot found it:

http://www.w3schools.com/cssref/pr_tab_caption-side.asp

**Comment by Schweinepriester** [comment]
+1
(according to w3schools its 'well supported', as in IE8+)

**Comment by StevenTew** [comment]
+1
https://developer.mozilla.org/en-US/docs/Web/CSS/caption-side

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-css_properties_caption-side
