### ISSUE TITLE
CSS @apply Rule

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#2480]
Searched, found no issue yet.

Via https://twitter.com/razvancaliman/status/721402036609224704 "CSS @​apply in Chrome Canary."
=> https://tabatkins.github.io/specs/css-apply-rule/

Not sure if this belongs to CSS Custom Properties, but since support apparently differs…

**Comment by cvrebert** [comment]
+1

**Comment by Ugoku** [comment]
+1

**Comment by alinnert** [comment]
+1

**Comment by Schweinepriester** [comment]
Another link:
https://css-tricks.com/css-from-the-future/
=> http://zeke.sikelianos.com/css-from-the-future/

**Comment by DanielVoogsgerd** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-apply-rule
