### ISSUE TITLE
Add EU to region-usage-json

### ISSUE THREAD

**Issue by DaSchTour** [Fyrd/caniuse#2485]
On caniuse.com there are EU usage data, but they are not available from the region-usage-json. As region-usage-json is accessed by autoprefixer I it would be great to have EU available as a region json.

**Comment by Fyrd** [comment]
It's there...the non-nation data just starts with "alt_":
https://github.com/Fyrd/caniuse/blob/master/region-usage-json/alt-eu.json

**Comment by DaSchTour** [comment]
Oh okay, haven't sean that. But using alt-eu doesn't work with browserlist :( alt-eu isn't accepted as a parameter.
