### ISSUE TITLE
Service Worker support in Opera

### ISSUE THREAD

**Issue by philnash** [Fyrd/caniuse#2486]
The current data suggests that Opera supported the Service Worker API since version 24. However, [Opera announced support for Service Workers when they launched Opera 27](https://dev.opera.com/blog/opera-27/) based on Chromium 40, the first version of Chromium with Service Worker support.

How can I help to correct this?

**Comment by Fyrd** [comment]
Thanks, have fixed this. In the future see https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md on how to contribute, I generally suggest submitting a pull request. :)

**Comment by philnash** [comment]
Thanks!
