### ISSUE TITLE
DOM methods prepend(), append(), before(), after(), replaceWith()

### ISSUE THREAD

**Issue by tobireif** [Fyrd/caniuse#2489]
Please see
https://twitter.com/html5/status/724816231136661504
and
https://dom.spec.whatwg.org/

**Comment by Ugoku** [comment]
+1

**Comment by tobireif** [comment]
@Ugoku Just as a tip for the future: Instead of posting "+1" you can alternatively click on "Add your reaction" (or click on an existing reaction).

**Comment by Ugoku** [comment]
I know, but @Fyrd recently said that GitHub doesn't support that in its API yet, so "+1" comments are prefered for the time being.

**Comment by cvrebert** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=dom-manip-convenience
