### ISSUE TITLE
include Samsung Internet

### ISSUE THREAD

**Issue by loominade** [Fyrd/caniuse#2493]
According to the [Browsers not included on site list](http://caniuse.com/usage-table), the _Samsung Internet_ is the only browser with over one percent market share (actually it has a market share 10x bigger then the next mobile browser on the list)

Due to its market share (and overall quality) I often run into problems with this browser and having it in the regular feature charts would be very helpful.

**Comment by Fyrd** [comment]
Yeah...that once kind of came out of nowhere, didn't have any usage share a few months ago (possibly due to how statcounter has tracked it). Will look into it.

**Comment by holtjohnson** [comment]
+1

**Comment by tedw** [comment]
According to StatCounter, Samsung Internet is up to 9% in Europe and 7% in North America 😱 
http://gs.statcounter.com/#mobile_browser-eu-daily-20160430-20160529-bar
http://gs.statcounter.com/#mobile_browser-na-daily-20160430-20160529-bar

**Comment by Gurtak** [comment]
+1 It's a much more significant player now. Accounts for 3% of the 3.8% of the "Mobile browsers not included on site". And dwarfs Android, Blackberry, Opera Mobile, Firefox Mobile and IE Mobile COMBINED!

Is the data already there but not shown because it failed to meet the cut?

**Comment by Fyrd** [comment]
Samsung Internet has now been added! Only data that still needs to be updated is the regional usage data, will add that some time tomorrow.
