### ISSUE TITLE
oncontextmenu

### ISSUE THREAD

**Issue by Vovan3000FL** [Fyrd/caniuse#2502]
Oncontextmenu - what display context menu?

Example:
`<div oncontextmenu="return false">some content no context menu</div>
<body oncontextmenu="return false"><div>No <p>context </p><br><p>menu </p></div><hr><p>in</p><img src='example.jpg' />ALL BODY!</body>`

**Comment by theSdev** [comment]
+1
Per my testing of the current versions, latest version of Chrome, Firefox, Chrome Android and Firefox on Android support `contextmenu` event but iOS Safari sadly does not.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_element_contextmenu_event
