### ISSUE TITLE
Geolocation on non-secure sites

### ISSUE THREAD

**Issue by Ugoku** [Fyrd/caniuse#2504]
[Geolocation on non-secure sites is deprecated in Chromium](https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins) (and therefore in Chrome, Opera, Vivaldi too). Chrome 50 (and Opera 37) have disabled it since about 2 weeks ago: https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only

I think it would be useful to mention this under Notes.

**Comment by maddesigns** [comment]
seems that Safari 10 also need HTTPS now http://stackoverflow.com/a/39666878
