### ISSUE TITLE
background-repeat: space

### ISSUE THREAD

**Issue by wujekbogdan** [Fyrd/caniuse#2513]
`background-repeat: space` is missing. I didn't even know that such a property exists. Until today :)

**Comment by Ugoku** [comment]
+1
Cool, didn't know this existed either!
Blog post including demo: http://www.impressivewebs.com/space-round-css3-background/

Works in Chrome 50/Opera 37, doesn't work in Firefox 46.

**Comment by kostaldavid8** [comment]
+1

**Comment by Schweinepriester** [comment]
+1
What about `background-repeat: round;` mentioned in the link by @Ugoku, though? Shouldn't this be included here as well?

**Comment by kostaldavid8** [comment]
That's should also be definitly included.

Dne čt 2. 6. 2016 1:02 odpoledne uživatel Kai <notifications@github.com>
napsal:

**Comment by Schweinepriester** [comment]
From <https://developer.mozilla.org/de/Firefox/Releases/49>:

> Added support for the `round` and `space` keywords to background-repeat

**Comment by jardicc** [comment]
+1

**Comment by yukulele** [comment]
https://github.com/Fyrd/caniuse/pull/3230

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=background-repeat-round-space
