### ISSUE TITLE
Create browser scorecard

### ISSUE THREAD

**Issue by DanAtkinson** [Fyrd/caniuse#2517]
Given that htmltest is effectively dead (not updated since August 2015 as of writing), I think it would be really great if the compare mechanism could be updated to allow for a scoring mechanism of browser functionality.

It really provides nothing terribly useful to the user apart from the smug satisfaction that they're using a browser with a high score, but the ability to see 'at a glance' browser coverage would be very nice.

**Comment by Fyrd** [comment]
This was added for the main 4 desktop browsers on the homepage some time ago, which I feel is sufficient.

Also HTML5test actually came back and has been updating since July 2016, so there's that if you want something better. :)

**Comment by bencooper222** [comment]
I'd like to see mobile safari on that list. I actually think that might be the most important since mobile safari has a monopoly over browsers on iOS (all browsers must use the iOS WebKit engine)
