### ISSUE TITLE
Node.isSameNode() and Node.isEqualNode() isn't listed on caniuse

### ISSUE THREAD

**Issue by geoyws** [Fyrd/caniuse#2527]
https://developer.mozilla.org/en-US/docs/Web/API/Node/isSameNode
https://developer.mozilla.org/en-US/docs/Web/API/Node/isEqualNode

Love caniuse. Use it all the time. Appreciate the service.

**Comment by tlouth19** [comment]
Any chance of adding this soon? This would be a great addition 👍

**Comment by tlouth19** [comment]
Any chance of adding this soon? It would be a great addition 👍

**Comment by Fyrd** [comment]
Available at https://caniuse.com/mdn-api_node_issamenode and https://caniuse.com/mdn-api_node_isequalnode
