### ISSUE TITLE
Add fromCharCode

### ISSUE THREAD

**Issue by Horray** [Fyrd/caniuse#2530]
Can you add the compatibility for fromCharCode please?

**Comment by Ugoku** [comment]
According to [MDN](https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode), this was added in Javascript 1.2 so it has been available since the late 1990's.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_builtins_string_fromcharcode
