### ISSUE TITLE
Add Intersection Observer

### ISSUE THREAD

**Issue by gonzaloruizdevilla** [Fyrd/caniuse#2534]
An API that can be used to understand movement of DOM elements relative to another element or the browser top level viewport. Changes are delivered asynchronously and are useful for understanding the visibility of elements, managing pre-loading of DOM and data, as well as deferred loading of "below the fold" page content.

https://developers.google.com/web/updates/2016/04/intersectionobserver?hl=en
https://github.com/WICG/IntersectionObserver/blob/master/explainer.md

**Comment by cvrebert** [comment]
+1

**Comment by kostaldavid8** [comment]
+1

**Comment by jrstanley** [comment]
Duplicate of #2425
