### ISSUE TITLE
ontouchmove 

### ISSUE THREAD

**Issue by yeomann** [Fyrd/caniuse#2536]

**Comment by cvrebert** [comment]
Already covered by http://caniuse.com/#feat=touch

**Comment by yeomann** [comment]
@cvrebert i see but its not covering particularly "ontouchmove" property and there is very little information on site regarding touch property.

**Comment by cvrebert** [comment]
Do you have some reason to believe that `ontouchmove` compatibility differs from compatibility with Touch Events as a whole generally? Unless there's some known difference, caniuse doesn't normally go into that level of detail.

**Comment by Fyrd** [comment]
Agreed, already covered, no need to cover it separately.
