### ISSUE TITLE
Consider adding unhandledrejection/rejectionhandled

### ISSUE THREAD

**Issue by rapilabs** [Fyrd/caniuse#2541]
Chrome has added 2 new event types: `unhandledrejection` and `rejectionhandled`.  These are useful promise global rejection handlers, which I've personally used with Bluebird before and are now available with Chrome: https://googlechrome.github.io/samples/promise-rejection-events/

**Comment by freen** [comment]
+1 this would be really nice

**Comment by olane** [comment]
+1, I was looking for this earlier

**Comment by godchuanz** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=unhandledrejection
