### ISSUE TITLE
The <slot> element

### ISSUE THREAD

**Issue by edgerunner** [Fyrd/caniuse#2549]
It seems that the `<content>` element is being deprecated in favor of a new `<slot>` element in the Web components spec. Would be good to keep tabs on it.
- https://webkit.org/blog/4096/introducing-shadow-dom-api/
- https://hacks.mozilla.org/2015/06/the-state-of-web-components/

**Comment by Nevraeka** [comment]
👍 
Polyfills 
- [named-slots](https://github.com/skatejs/named-slots)
Related Article
- [Aurelia Shadow DOM v1 Slots Prerelease](http://blog.durandal.io/2016/05/23/aurelia-shadow-dom-v1-slots-prerelease/)

**Comment by freddialpad** [comment]
is the `<slot>` element related to the [slot attribute](https://developer.mozilla.org/en-US/docs/Web/API/Element/slot)  in any way or would that be a separate request? I'm not seeing it in caniuse, but it's possible I'm searching for the wrong thing OR that it's already widely supported and I am just out of touch...

**Comment by DaveEveritt** [comment]
> is the `<slot>` element related to the [slot attribute](https://developer.mozilla.org/en-US/docs/Web/API/Element/slot) in any way or would that be a separate request?

They're linked (see "[How to Use HTML <template> & <slot> With Shadow DOM](https://www.hongkiat.com/blog/html-template-slow-tag-shadow-dom/)"), but the [Shadow DOM has very poor (native) browser support](https://caniuse.com/#feat=shadowdom) so far.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-html_elements_slot & https://caniuse.com/#feat=mdn-api_htmlslotelement
