### ISSUE TITLE
Pseudo elements (+ colons :before vs. ::before)

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#2552]
Searched, found nothing.

I'd like to see `::before` and `::after` added, at least to the well supported properties, as the support can be assumed as complete (IE8+).

I searched to find from when two colons where supported. Turns out only IE8 used one colon, yet notation with one is still around (and supported).

- <https://css-tricks.com/almanac/selectors/a/after-and-before/>
- <http://www.w3schools.com/cssref/sel_before.asp>

**Comment by Fyrd** [comment]
Not terribly clear, but this is covered by note #1 at http://caniuse.com/#feat=css-gencontent
