### ISSUE TITLE
Flexbox height bug fixed in Chrome 51

### ISSUE THREAD

**Issue by bvisness** [Fyrd/caniuse#2561]
One of the known issues on http://caniuse.com/#search=flexbox is that Chrome and Safari do not respect the height of non-flex children whose heights are in percentages.

This bug has been fixed in Chrome 51: https://bugs.chromium.org/p/chromium/issues/detail?id=341310#c67

However, the bug has not yet been fixed in Webkit (Safari): https://bugs.webkit.org/show_bug.cgi?id=137730

I would suggest that the issue text be modified to reflect this.

**Comment by Fyrd** [comment]
Thanks, fixed!
