### ISSUE TITLE
:active-drop-target

### ISSUE THREAD

**Issue by jwicksnin** [Fyrd/caniuse#2562]
Also, `:valid-drop-target`, `:invalid-drop-target`.  See https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes
Any Drag N Drop support is appreciated!

**Comment by cvrebert** [comment]
These don't exist anymore.
They've been consolidated into `:drop()`: https://drafts.csswg.org/selectors-4/#changes

**Comment by Fyrd** [comment]
Since this was removed and doesn't have a lot of folks searching for it I'm closing this issue.
