### ISSUE TITLE
Add Safari Pin Icon

### ISSUE THREAD

**Issue by matt3224** [Fyrd/caniuse#2563]
![screen shot 2016-06-09 at 21 17 55](https://cloud.githubusercontent.com/assets/2401925/15944908/aad4ae16-2e87-11e6-924e-0077b29877c6.png)

I dont want caniuse to be a little 'c' any longer, please add a nice icon for the safari pin feature

**Comment by thany** [comment]
How to: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html

**Comment by AidanHak** [comment]
[Favicon Generator](https://realfavicongenerator.net/) should make it easy to implement.

**Comment by thany** [comment]
Safari *should*, of course, use the favicon that is undoubtedly already included.
Maybe file a bug at Apple and see it absolutely never fixed :D

**Comment by AidanHak** [comment]
It would probably be way easier to just support all browsers through Favicon Generator. It would be much more quickly resolved that way.

**Comment by matt3224** [comment]
Yup I agree, favicon generator is a decent tool and it's a shame more sites don't use it

**Comment by Schweinepriester** [comment]
<https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs#safari-pinned-icon>

> Safari used to have a separate requirement to display an icon in [pinned tabs](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html). However, since Safari 12, we can use a regular favicon for pinned tabs. Even [apple.com](https://www.apple.com/) doesn't use the `mask-icon` anymore.

==>

<img width="281" alt="Bildschirmfoto 2021-04-03 um 06 55 20" src="https://user-images.githubusercontent.com/2644614/113468923-a1064c00-9449-11eb-8709-88451213a560.png">

I think this issue can be closed? 0:-)
