### ISSUE TITLE
Safari 10.0

### ISSUE THREAD

**Issue by cvrebert** [Fyrd/caniuse#2572]
See https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html

**Comment by Schweinepriester** [comment]
+1 (I might do an easy list if i have time)

**Comment by Schweinepriester** [comment]
Only listing if there is a delta to Safari TP:
- IndexedDB ('now fully supports the recommended standard')
  - Check if its still buggy, @cfjedimaster? :)
- [Shadow DOM](http://caniuse.com/#feat=shadowdom) now supported?
- [WOFF 2.0](http://caniuse.com/#feat=woff2) now supported
- [CSS Font Loading](http://caniuse.com/#feat=font-loading) now supported
- CSS Shapes Level 2 now supported
  - There is no ticket yet for lvl 2?
  - Check [lvl 1](http://caniuse.com/#feat=css-shapes) if `-webkit` is still needed?
- `round` and `space` values for the `border-image` ([AGAIN!?](https://github.com/Fyrd/caniuse/issues/2207))
- `image-rendering` now without `-webkit`; `pixelated` supported as well
- Media Query for Wide Color Gamut (see <https://github.com/Fyrd/caniuse/issues/1069>)
- CSS `break-after`, `break-before`, and `break-inside` now supported
- Now without `-webkit`
  - `filter`
  - `cross-fade`
- Proper support of [unicode-range](http://caniuse.com/#feat=font-unicode-range)?

**Comment by Fyrd** [comment]
Safari 10 added, think I got most of the things from your list @Schweinepriester, except need to investigate the round & space & break-* props a bit further still.

**Comment by Fyrd** [comment]
Closing this issue since Safari 10 got added. If you feel I missed anything (aside from #2207) let me know.
