### ISSUE TITLE
Adobe Flash

### ISSUE THREAD

**Issue by emilv** [Fyrd/caniuse#2574]
I wanted to know how dead Flash is. I think it would fit well in the CanIUse format!

**Comment by peterdd** [comment]
Do you mean the swf file format, the original ideas and technology behind, or the interpreters / flash plugins?

Really sad no other or open source implementation of swf interpreters are vital today e.g. http://savannah.gnu.org/projects/gnash/ . So users are grounded on constantly insecure Adobe flash plugin (when wanting to have some fun based on flash tech.)

Compared to flash technology, HTML5, CSS3 and stuff around is such a huge pile of standard bloat and feels 15 years behind. (for making games or animations for instance)

**Comment by emilv** [comment]
Realistically it should probably be based on having the Adobe Flash plugin installed.

**Comment by YaManicKill** [comment]
You can't know whether a browser will have flash installed. Some browsers have it embedded, but most don't, so it's not really the same thing as everything else on caniuse.

**Comment by Fyrd** [comment]
Yup, as @YaManicKill this is not something that can be tracked as a "yes" or "no" for most browsers, so there's no plan to add it.

**Comment by iBobik** [comment]
It will not be impossible if this feature will not be about browsers, but OS/browser and their default configuration. For some browsers it is simpler - Chrome will block it in some date on all OS, Safari is only on macOS (not installed by default) and iOS (not possible to install).

**Comment by b9chris** [comment]
I agree that Flash support should be tracked on caniuse based on whether one could easily install a Flash plugin and that browser would allow it to be installed and run. This is not very complicated - IE6 yes, IE11 yes, Chrome 76 partial support, and someday, there will be a version of Chrome that explicitly does not allow Flash at all.

**Comment by mingtsay** [comment]
Safari 14 is dropping out the support of Adobe Flash
ref: https://developer.apple.com/documentation/safari-release-notes/safari-14-beta-release-notes
