### ISSUE TITLE
position:sticky data is wrong for Chrome

### ISSUE THREAD

**Issue by cvrebert** [Fyrd/caniuse#2579]
The data currently claims it's supported without any flags in Chrome 52+, but based on testing with http://html5-demos.appspot.com/static/css/sticky.html , Chrome Canary 53 only supports it when the "Experimental Web Platform features" flag is enabled. I would guess the same to be true for Chrome Beta 52. 
Furthermore, the status of https://bugs.chromium.org/p/chromium/issues/detail?id=231752 is still Open, rather than Fixed as would be expected if the feature really had been shipped.

**Comment by Fyrd** [comment]
Thanks, fixed.
