### ISSUE TITLE
CSS Backdrop Filter support in Opera

### ISSUE THREAD

**Issue by pepelsbey** [Fyrd/caniuse#2582]
It should be the same in Opera as in Chrome: 1 footnote + flag, [but it’s not](http://caniuse.com/#feat=css-backdrop-filter).

![image](https://cloud.githubusercontent.com/assets/105274/16154707/5bfce95e-34ac-11e6-82e6-723540487d9e.png)

**Comment by Ugoku** [comment]
+1

**Comment by Fyrd** [comment]
Thanks, fixed.
