### ISSUE TITLE
Opera versions bump

### ISSUE THREAD

**Issue by pepelsbey** [Fyrd/caniuse#2583]
Opera for Android aka Opera Mobile is 37, [as of June 15](http://www.opera.com/blogs/mobile/2016/06/ad-blocking-push-notifications-opera-android/)
Opera for Desktop aka Opera is 38, [as of June 8](http://www.opera.com/blogs/desktop/2016/06/battery-saver-opera-browser-for-windows-mac/)

**Comment by Fyrd** [comment]
Thanks, updated!
