### ISSUE TITLE
audio / video .canPlayType(MIMEtype)

### ISSUE THREAD

**Issue by rbosneag** [Fyrd/caniuse#2593]
The `HTMLMediaElement.canPlayType()` method determines whether the specified media type can be played back.

Can be used like this: `[audio | video].canPlayType('video/mp4')` 

Some MIME types would be:
  `audio/mpeg`
  `audio/mp4`
  `audio/ogg`
  `audio/ogg`
  `audio/webm`
  `audio/wav`

link to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canPlayType) here

**Comment by Fyrd** [comment]
Pretty sure this is supported by all audio & video supporting browsers.

**Comment by GPHemsley** [comment]
Looks like this is now covered by MDN data:
https://caniuse.com/mdn-api_htmlmediaelement_canplaytype

(via mdn/browser-compat-data#1166)

**Comment by Fyrd** [comment]
Closing per last comment.
