### ISSUE TITLE
Combined support results

### ISSUE THREAD

**Issue by joelamos** [Fyrd/caniuse#2595]
Sometimes it would be useful to know the usage percentage across multiple features. For example, I'd like to know what percent of users' browsers are able to support the WOFF font type or the TTF type.

**Comment by Tobl4** [comment]
+1

**Comment by Tobl4** [comment]
I see there's a 'thumbs up' button. Do we still vote on issues via comment?

Back to the topic: Would also really like to see this; though I first thought about AND, not OR for the combined results. 
In a perfect world, I'd like to see something that allows queries like 
    css font-stretch AND (woff OR ttf)
resulting in a chart that describes full or partial support of the features for the different browsers.

Alternatively, there could be an option like "Add to collection" on features to build those feature sets. Seems harder to implent, but more user-friendly if we assume the user doesn't know the precise names for all the required features.

**Comment by Fyrd** [comment]
This functionality is now partially available on the beta site (https://beta.caniuse.com). You can add any feature to a "saved" list via the star button, then see the results which has a summary table with multiple views on the combination of features.
One thing still missing however is calculations on the usage %.

**Comment by Fyrd** [comment]
This is now available on the main site.
