### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by monajalal** [Fyrd/caniuse#2603]
I wonder if Font Awesome is supported by all browsers (or basically not supported by which browsers as I am using things like fa fa-instagram fa-lg for icon stuff in my website) as someone pointed out today that he can't see the icons in Firefox. It would be great to know so!

**Comment by cvrebert** [comment]
Font Awesome isn't a browser feature, and caniuse generally doesn't cover specific products. But caniuse already has compatibility data on the underlying font file formats and web fonts in general, which you can use to figure out Font Awesome's compatibility:
* http://caniuse.com/#feat=fontface
* http://caniuse.com/#feat=ttf
* http://caniuse.com/#feat=svg-fonts
* http://caniuse.com/#feat=eot
* http://caniuse.com/#feat=woff
* http://caniuse.com/#feat=woff2

**Comment by Fyrd** [comment]
Yup, @cvrebert is correct, not a native browser feature in itself, so will not be added.
