### ISSUE TITLE
HTML5 form validation: Firefox does not support validity.tooShort

### ISSUE THREAD

**Issue by atk** [Fyrd/caniuse#2612]
There should be a mention that Firefox still fails to support minlength validation, which should result in a validityState.tooShort; bugtracker entry: https://bugzilla.mozilla.org/show_bug.cgi?id=932755

**Comment by cvrebert** [comment]
Already linked in the Resources tab of http://caniuse.com/#feat=input-minlength

**Comment by atk** [comment]
Thank you for the information. Redundant information might still be helpful in this case.

**Comment by Fyrd** [comment]
Now also available at https://caniuse.com/#feat=mdn-api_validitystate_tooshort
