### ISSUE TITLE
:any() CSS Pseudo Class

### ISSUE THREAD

**Issue by knod** [Fyrd/caniuse#2614]

**Comment by Ugoku** [comment]
`:any` is [deprecated](https://developer.mozilla.org/en-US/docs/Web/CSS/:any) in favour of `:matches`, which is [already present on caniuse](http://caniuse.com/#feat=css-matches-pseudo)

**Comment by knod** [comment]
@Ugoku: The link you provided to the MDN for the deprecation of `:any` doesn't say it's deprecated and I'm having trouble finding any official documentation on `:matches`. Could you point me to a resource on that?

Also, even if `:matches` is now the specification, was `:any` never used? Does it have support that's different from `:matches`? If so, that would still be good information to know.

Regardless, thank you for bringing it up.

**Comment by knod** [comment]
Many thanks to whoever linked the `:any` search to a result!

**Comment by Ugoku** [comment]
> Note : This pseudo-class is in progress to be standardized in [CSS Selectors Level 4](https://drafts.csswg.org/selectors-4/#matches) under the name :matches(). It is likely that the syntax and name of :-vendor-any() will be changed to reflect it in the near future.

The spec link to `:matches` is in the note :)

`:any` is still in use as `:-moz-any` and `:-webkit:any`, but they behave a little bit different from `:matches`. More info can be found in the bug trackers under the Resources tab on caniuse.

**Comment by Fyrd** [comment]
Added a mention of `:any()` in the description too so it's a bit more obvious.
