### ISSUE TITLE
KeyboardEvent.shiftKey 

### ISSUE THREAD

**Issue by jayseeare** [Fyrd/caniuse#2615]
Could I suggest that this be added please? Lots of the KeyboardEvent properties are already included, but it would be great to know about this one...

http://www.w3schools.com/jsref/event_key_shiftkey.asp

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/shiftKey

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_keyboardevent_shiftkey
