### ISSUE TITLE
[data suggestion] same-site cookie attribute

### ISSUE THREAD

**Issue by patrick-mcdougle** [Fyrd/caniuse#2618]
https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site-00

http://www.sjoerdlangkemper.nl/2016/04/14/preventing-csrf-with-samesite-cookie-attribute/

**Comment by cvrebert** [comment]
Already present in the data, just not shown on the website:
https://github.com/Fyrd/caniuse/blob/master/features-json/same-site-cookie-attribute.json

**Comment by patrick-mcdougle** [comment]
I see and shown is false. Sorry about that, I should have read the contributing doc a little harder. Do you know how long the vetting of this feature will be until it's shown?

**Comment by cvrebert** [comment]
That's up to @Fyrd.

**Comment by Fyrd** [comment]
@patrick-mcdougle It varies...when it's a feature that has little to no votes on http://caniuse.com/issue-list/ (like this one) it can become pretty low priority as sometimes it means spending a lot of time on additional testing, which I'd rather not spend on a feature that has little interest.

However, your adding it as an issue is good as it shows more interest and increases its priority. So re-opening the issue for that purpose.

**Comment by Flimm** [comment]
+1

**Comment by GregMartyn** [comment]
Looks like this is a duplicate of #1613

**Comment by ShimShamSam** [comment]
+1

**Comment by rsteinwand** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=same-site-cookie-attribute

**Comment by Calico90** [comment]
For a recent update on Firefox see:
https://bugzilla.mozilla.org/show_bug.cgi?id=795346
https://bugzilla.mozilla.org/show_bug.cgi?id=1351663

Since four days the status of implementing SameSite into Firefox is: 
"Whiteboard: [design-decision-needed] triaged"
