### ISSUE TITLE
Header: X-Frame-Options

### ISSUE THREAD

**Issue by kaystrobach** [Fyrd/caniuse#2619]
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
* https://tools.ietf.org/html/rfc7034

Most important values
```
DENY
The page cannot be displayed in a frame, regardless of the site attempting to do so.

SAMEORIGIN
The page can only be displayed in a frame on the same origin as the page itself.

ALLOW-FROM uri
The page can only be displayed in a frame on the specified origin.
```

**Comment by cvrebert** [comment]
Duplicate of #1138. Try searching more in the future?

**Comment by kaystrobach** [comment]
Mhmm maybe i had a typo during the search, thanks for pointing out
