### ISSUE TITLE
background-attachment Safari/iOS should be No

### ISSUE THREAD

**Issue by pp-koch** [Fyrd/caniuse#2620]
I did some testing of the CSS Backgrpunds and Borders module in all mobile browsers, and found that Safari on iOS basically does not support background-attachment. Caniuse currently says it does; I would argue that it has to be changed into a No.

Documentation: http://quirksmode.org/css/backgrounds-borders/mobile.html
Test case: http://quirksmode.org/css/backgrounds-borders/attachment.html

background-attachment: fixed: Safari/iOS positions the background image correctly on page load, but does not update it when the user pans the document. In other words, the element with background-attachment: fixed does not serve as a "window" onto the background image, but instead always shows the same.

background-attachment: local: Safari/iOS supports it, but ONLY if you do NOT add -webkit-overflow-scrolling: touch. If you do, the background image does not scroll with the element. I suspect that most web developers who want to use local also want smooth scrolling, so I would say that in practice local is not supported.

These are the reasons why I think Safari/iOS's support for background-attachment should be changed to No.

Thanks - ppk

**Comment by Fyrd** [comment]
Thanks PPK! You're right, I can confirm that issue. Have changed support to partial with an added note on the "-webkit-overflow-scrolling: touch" issue. Will leave that up to developers to decide whether or not that means they can use the feature.
