### ISSUE TITLE
background-attachment Chrome 50 for Android should be No

### ISSUE THREAD

**Issue by pp-koch** [Fyrd/caniuse#2621]
I did some testing of the CSS Backgrpunds and Borders module in all mobile browsers, and found that Chrome 51 for Android does not support background-attachment. Caniuse currently says it does.

Documentation: http://quirksmode.org/css/backgrounds-borders/mobile.html
Test case: http://quirksmode.org/css/backgrounds-borders/attachment.html

Try the test case in Chrome for Android (or, in fact, any Chromium-based browser on Android); local is just not supported, and neither is fixed. (Only the Dolphin and Ubuntu browsers support fixed partially, but even they don't support local.)

**Comment by Fyrd** [comment]
Interesting, the test case I was using here:
http://people.opera.com/pepelsbey/experiments/bga/
shows  `local` working fine in Chrome 51 for Android. Did a little bit of experimenting but so far it's not obvious why it works there but not in your test. Any idea?

**Comment by pp-koch** [comment]
Wow. That's really odd. I ascertained that it's NOT a simple case of adding

- background-repeat: no-repeat;
- background-position
- position: absolute;
- an image that's much bigger than the box

I'm totally stumped for now. I hope I'll get some inspiration later.

**Comment by pp-koch** [comment]
... and the solution: add a border-radius. Then it works. This is obviously a bug.
https://bugs.chromium.org/p/chromium/issues/detail?id=627037

**Comment by Fyrd** [comment]
Wow, that's a weird one. Thanks for finding that out! Have updated the note and included link to bug.
