### ISSUE TITLE
Wake Lock API

### ISSUE THREAD

**Issue by leolux** [Fyrd/caniuse#2623]
https://w3c.github.io/wake-lock/#requesting-wake-locks

**Comment by barklund** [comment]
+1

**Comment by dmonizer** [comment]
+1

**Comment by oising** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

Relation to #2069? Both issues seem to request the same thing. If so, I'd argue for closing #2069 as duplicate even though its older, because this one has way more votes.

**Comment by mleaning** [comment]
+1

**Comment by Harvzor** [comment]
Wake Lock API is now available as an 'origin trial' in Chrome: https://developers.google.com/web/updates/2019/12/nic79#wake-lock

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=wake-lock

**Comment by Schweinepriester** [comment]
Noice! 🎉

@Fyrd: #2069 can probably be closed as well, per [my comment above](https://github.com/Fyrd/caniuse/issues/2623#issuecomment-493086821)?

**Comment by Fyrd** [comment]
@Schweinepriester Yup! Was just about to :D
