### ISSUE TITLE
Add navigator.mediaDevices

### ISSUE THREAD

**Issue by schoettler** [Fyrd/caniuse#2628]
Part of: https://w3c.github.io/mediacapture-main/#mediadevices
Documented by MDN: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices

Currently available for Chrome and Firefox latest versions, but who else's got it? \o/

**Comment by owlsir** [comment]
+1

**Comment by xudihui** [comment]
+1

**Comment by hejiajun107** [comment]
+1

**Comment by Calico90** [comment]
+1

**Comment by buckhorn-foxpert** [comment]
+1

**Comment by Quanyails** [comment]
+1

**Comment by chrisblakley** [comment]
+1

**Comment by matiaslopezd** [comment]
+1

**Comment by matiaslopezd** [comment]
Today is fully compatible with all browsers, obviously not with IE :satisfied:

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices#Browser_compatibility

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_mediadevices
