### ISSUE TITLE
pointer-events works in Chrome

### ISSUE THREAD

**Issue by setek** [Fyrd/caniuse#2631]
http://caniuse.com/#feat=pointer says pointer-events doesn't work in any Chrome.

I'm on Google Chrome "51.0.2704.106 m" on Windows 8 and pointer-events does work.

Also, on Firefox 47.0.1 (same OS) pointer-events works too, even though I haven't enabled feature specifically as the text says. And Opera 29 (same OS) also works.

**Comment by cvrebert** [comment]
Quoting from the feature's description:

> **Not to be mistaken with the unrelated "pointer-events" CSS property.**

Presumably you want http://caniuse.com/#feat=pointer-events instead.

**Comment by setek** [comment]
Oh haha crap my mistake, thanks :)
