### ISSUE TITLE
What does support look like for GIFV? 

### ISSUE THREAD

**Issue by mattwojo** [Fyrd/caniuse#2633]
GIFV seems to be an improved format for posting animated GIFs that fall back to mp4 or webm, but I can't find much information about them... would be great to have support posted here.

Blog post by Imgur about introduction of GIFV in 2014: http://blog.imgur.com/2014/10/09/introducing-gifv/

Reddit post from one of the guys who worked on it addressing some FAQs: https://np.reddit.com/r/HighQualityGifs/comments/4qxl6o/are_you_ready/d4x5xj1?context=3

**Comment by cvrebert** [comment]
> GIFV is not actually a distinct file format, but it is an MP4 or WebM video that is presented via a HTML5 `<video>` element or an Adobe Flash element with options set so as to make it work similarly to an animated GIF (i.e. endless loop with no video controls visible).

– http://fileformats.archiveteam.org/wiki/GIFV

**Comment by mattwojo** [comment]
Super helpful! Thank you @cvrebert ! ...closing this issue.

**Comment by mirraj2** [comment]
I think this should be re-opened.  The following gif video does not work on chrome, but works on safari.  http://i.imgur.com/Kpy8R9B.gifv

**Comment by Llbe** [comment]
@mirraj2: I see no issue on Chrome 54.

**Comment by mirraj2** [comment]
Nevermind, I realized it didn't work because of a plugin I have on my chrome.
