### ISSUE TITLE
Add print-color-adjust

### ISSUE THREAD

**Issue by WhiteWind** [Fyrd/caniuse#2634]
Add print-color-adjust css property

**Comment by cvrebert** [comment]
* https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-print-color-adjust
* https://drafts.csswg.org/css-color-4/#color-adjust

**Comment by tech4him1** [comment]
Can we go ahead and add this as `color-adjust`, since that is in the [CSSWG Color 4 draft](https://drafts.csswg.org/css-color-4/#color-adjust)?

**Comment by zspitzer** [comment]
Edge and IE don't support this yet
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12399195/

**Comment by thomasfrobieter** [comment]
"Edge and IE don't support this yet"

Why is this a blocker for adding it to caniuse?

**Comment by zspitzer** [comment]
It isn't, I only added that information as it would be a useful footnote!

**Comment by codler** [comment]
Firefox has this. https://stackoverflow.com/questions/35004690/force-background-color-printing-on-firefox

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=css-color-adjust
