### ISSUE TITLE
Numbers for africa appears to be wrong

### ISSUE THREAD

**Issue by larsenwork** [Fyrd/caniuse#2637]
E.g. for svg it shows around 60% when in reality it should be maybe 95% (at least based on the graph)

![screen shot 21](https://cloud.githubusercontent.com/assets/3859425/16757481/a7238f14-480c-11e6-96b6-19f0020985e0.png)

**Comment by Fyrd** [comment]
Looks like due to a recent change Opera Mini data was not being considered (which has 29.55% usage in Africa). Has now been fixed, thanks for letting me know!
