### ISSUE TITLE
display: run-in

### ISSUE THREAD

**Issue by denvers** [Fyrd/caniuse#2638]
Is this spec available in caniuse.com?
Source: https://css-tricks.com/run-in/

**Comment by cvrebert** [comment]
Subfeature of #2337.
https://drafts.csswg.org/css-display/#valdef-display-run-in

**Comment by jensimmons** [comment]
+1

**Comment by meyerweb** [comment]
Simple test here: http://meyerweb.com/eric/css/tests/css3/show.php?p=display#i05

A quick test showed only Opera supported it on MacOS.  Edge might, since IE8 did, but since it was removed from some browsers it may have been removed from the Explorer/Edge line as well.

**Comment by jensimmons** [comment]
dbaron has a test here: https://dbaron.org/css/test/sec090204

Actually, it seems both Eric and dbaron's tests fail in Opera for Mac (v45). MDN reports that it should work in Opera, but I don't see that as the current situation. 

Have not tested Edge or IE.

**Comment by Fyrd** [comment]
Just noticed this is a duplicate of #1369
