### ISSUE TITLE
toLocaleString('pt-BR',{style: 'currency', currency:'BRL'})

### ISSUE THREAD

**Issue by juliomac** [Fyrd/caniuse#2641]
Could not find any reference to toLocaleString().

This ECMA6 function is referenced here: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString#Browser_compatibility

**Comment by cvrebert** [comment]
Should fall under http://caniuse.com/#feat=internationalization

**Comment by Fyrd** [comment]
Also available at https://caniuse.com/#feat=mdn-javascript_builtins_number_tolocalestring
