### ISSUE TITLE
Add `navigator.doNotTrack` and DNT support tables

### ISSUE THREAD

**Issue by ndorfin** [Fyrd/caniuse#2642]
Please can we have DNT and `doNotTrack` support added to caniuse.com

The 'Do Not Track' privacy initiative is implemented first at an HTTP Header level, e.g. `DNT:1` and then exposed on the `window` and `navigator` objects in the DOM as `doNotTrack` depending on the User Agent.

Current implementations:
- `navigator.doNotTrack`
- `navigator.msDoNotTrack` (IE 9-10)
- `window.doNotTrack` (IE 11+, Safari 7+)

See:
- W3.org spec (Working Draft): https://www.w3.org/TR/tracking-dnt/
- MDN Guide on the Do Not Track initiative: https://developer.mozilla.org/en-US/docs/Web/Security/Do_not_track_field_guide
- MDN Article on `navigator.doNotTrack`: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack

As a web developer, I'm interested in a JS polyfill that would check the User Agent for the user's Do Not Track setting. If `doNotTrack` is set, then I'd, for instance, not load up any client-side analytics.

Thanks!

**Comment by cvrebert** [comment]
+1

**Comment by grinfax** [comment]
+1

**Comment by dmdabbs** [comment]
+1 And please include storeSiteSpecificTrackingException, etc. With the EU GDPR looming there's likely to be interest in this.

**Comment by donohoe** [comment]
+1 on @dmdabbs regarding _GDPR_. We're working on this now and we're not the only ones.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=do-not-track
