### ISSUE TITLE
Is it possible a share icon for caniuse?

### ISSUE THREAD

**Issue by dawncold** [Fyrd/caniuse#2644]
I have read some css/js/html5 feature articles, these articles will write "This feature is not support on IE6-8", "This feature is only support for Chrome", etc.

Is it possible to create a caniuse js widget, it will dynamically display some feature's status on your current browser and other browsers, even I read some old articles I would find that feature is now supported by all browsers.

**Comment by Fyrd** [comment]
Yeah, what you're probably looking for is available at https://caniuse.bitsofco.de/
