### ISSUE TITLE
While I choose a category, the keyword of search is clear, While I enter a keyword, the categories are reset.

### ISSUE THREAD

**Issue by Gpia** [Fyrd/caniuse#2645]
While I choose a category, the keyword of search is clear, While I enter a keyword, the categories are reset. How can I use the website http://caniuse.com to check useage of array function filter of javascript?

**Comment by Fyrd** [comment]
Yeah, the categories just let you see the list of features in that category. The "filter" function doesn't have its own table, but is part of the ES5 support one at http://caniuse.com/#feat=es5 (which can be found when searching for "filter")
