### ISSUE TITLE
Add Web Payments

### ISSUE THREAD

**Issue by digitalreb** [Fyrd/caniuse#2647]
https://www.w3.org/TR/payment-request/
https://www.w3.org/TR/payment-method-id/
https://www.w3.org/TR/payment-method-basic-card/

**Comment by Ugoku** [comment]
+1

Added in Chrome 53 for Android, now in beta: http://blog.chromium.org/2016/08/chrome-53-beta-shadow-dom.html "with support for more platforms coming soon"

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=payment-request
