### ISSUE TITLE
Add CSS viewport-percentage length units 'vi' and 'vb'

### ISSUE THREAD

**Issue by SebastianZ** [Fyrd/caniuse#2649]
Logical direction versions of the CSS viewport-percentage length units 'vw' and 'vh' called 'vi' and 'vb' were added to the [CSS Values and Units Module Level 3](https://drafts.csswg.org/css-values-3/#viewport-relative-lengths) recently.
Once a new Working Draft of that spec. is released, those two units should be added to the ['viewport-units' feature](http://caniuse.com/#feat=viewport-units).

I've also filed according enhancement requests for [Gecko](https://bugzilla.mozilla.org/show_bug.cgi?id=1287034), [Blink](https://bugs.chromium.org/p/chromium/issues/detail?id=628497) and [WebKit](https://bugs.webkit.org/show_bug.cgi?id=159801).

Sebastian

**Comment by Delapouite** [comment]
I can't find any mention of `vi` and `vb` in the linked draft anymore. Have they been removed ?

**Comment by cpplearner** [comment]
They are in [Level 4](https://drafts.csswg.org/css-values-4/#viewport-relative-lengths).

**Comment by chharvey** [comment]
@SebastianZ These are now on CanIUse:

- `vi`: https://caniuse.com/#feat=mdn-css_types_length_vi
- `vb`: https://caniuse.com/#feat=mdn-css_types_length_vb

**Comment by Fyrd** [comment]
Yup, thanks for the links @chharvey !

**Comment by SebastianZ** [comment]
Great! Thank you!

Sebastian
