### ISSUE TITLE
Move security items from other to own category and support additional security features

### ISSUE THREAD

**Issue by Calico90** [Fyrd/caniuse#2650]
I noticed the following security related items exist already and are all part of the category other:
- http://caniuse.com/#feat=publickeypinning
- http://caniuse.com/#feat=stricttransportsecurity
- http://caniuse.com/#feat=subresource-integrity
- http://caniuse.com/#feat=u2f
- http://caniuse.com/#feat=chacha20-poly1305
- http://caniuse.com/#feat=tls1-2
- http://caniuse.com/#feat=tls1-1
- http://caniuse.com/#feat=subresource-integrity
- http://caniuse.com/#feat=upgradeinsecurerequests
- http://caniuse.com/#feat=contentsecuritypolicy2
- http://caniuse.com/#feat=contentsecuritypolicy

Since they are all closely related to security, please move them into a own category instead of in the category other.

Also, please add support information about HTTP Security headers like:
- X-Content-Type-Options: nosniff
- #1556 X-XSS-Protection: 1; mode=block
- #1138 X-Frame-Options 

And support information about security features like:
- DNSSEC
- #2055 DANE

**Comment by Schweinepriester** [comment]
- X-XSS-Protection (#1556)
- X-Frame-Options (#1138)
- DANE (#2055)

are already requested.

**Comment by Calico90** [comment]
@Schweinepriester Thanks, I changed the question a bit.

**Comment by Calico90** [comment]
Any support for moving the above list from Other to a Security category?

**Comment by Schweinepriester** [comment]
I'm fine with the Security category. Don't think its urgent, though.

As Fyrd added the "Misc. site/data request" label, this issue isn't appearing in the <https://caniuse.com/issue-list> and can be voted for, which I wanted to do for DNSSEC.
~~Therefore there probably should be individual issues for the remaining features, `X-Content-Type-Options: nosniff` as well as DNSSEC.~~

~~Do you want to create those, Calico90, or shall I?~~

There is an issue for `X-Content-Type-Options: nosniff`: #2758

Do you want the honor for creating the issue for DNSSEC, @Calico90?

**Comment by Calico90** [comment]
@Schweinepriester consider it done! https://github.com/Fyrd/caniuse/issues/3380

**Comment by Calico90** [comment]
@Schweinepriester How can we create a security category? I have some more suggestions related to browser compatibility.

**Comment by Calico90** [comment]
This one can be added to a security category too: https://caniuse.com/#feat=same-site-cookie-attribute
Also I will request support for HttpOnly and Secure cookies.

**Comment by Calico90** [comment]
Here: https://github.com/Fyrd/caniuse/issues/3382 and https://github.com/Fyrd/caniuse/issues/3381

**Comment by Calico90** [comment]
This one can also be in a security category: https://caniuse.com/#feat=referrer-policy

**Comment by Calico90** [comment]
And https://github.com/Fyrd/caniuse/issues/3383

**Comment by Calico90** [comment]
and https://github.com/Fyrd/caniuse/issues/1161 and https://github.com/Fyrd/caniuse/issues/1197 and https://github.com/Fyrd/caniuse/issues/1396

**Comment by Calico90** [comment]
and https://github.com/Fyrd/caniuse/issues/2122 and https://github.com/Fyrd/caniuse/issues/2225

**Comment by Calico90** [comment]
and https://github.com/Fyrd/caniuse/issues/1716

**Comment by Calico90** [comment]
and https://github.com/Fyrd/caniuse/issues/2884

**Comment by Calico90** [comment]
and https://github.com/Fyrd/caniuse/issues/3104

**Comment by Fyrd** [comment]
Done! "Security" is now its own category:
https://caniuse.com/#cats=Security

**Comment by Calico90** [comment]
Great! :) Now let's hope one of the above suggestions might get more info soon to be added.
Here two more suggestions that would possibly fit into that category: https://github.com/Fyrd/caniuse/issues/3388 and https://github.com/Fyrd/caniuse/issues/3387.

**Comment by Calico90** [comment]
As you can see confirmed here again: https://www.keycdn.com/blog/http-security-headers/ the caniuse websites perfectly first for browser-related security features too. :)

**Comment by biergaizi** [comment]
also https://github.com/Fyrd/caniuse/issues/3157

**Comment by Calico90** [comment]
And https://github.com/Fyrd/caniuse/pull/3426 / https://github.com/Fyrd/caniuse/issues/2083
