### ISSUE TITLE
Show or mention 'animationend'

### ISSUE THREAD

**Issue by knod** [Fyrd/caniuse#2657]
Searching for 'animationend' leads to a result that says CSS Animation, but doesn't say anything about 'animationend'. Is this the correct information for the 'animationend' event?

**Comment by Schweinepriester** [comment]
Indirectly fixed by information via MDN: 
https://caniuse.com/?search=animationend now shows 4 entries for different ~contexts of `animationend`.

**Comment by Fyrd** [comment]
Yup, covered by https://caniuse.com/mdn-api_element_animationend_event
