### ISSUE TITLE
Add Shadow DOM v1 entry

### ISSUE THREAD

**Issue by TakayoshiKochi** [Fyrd/caniuse#2666]
We already have an entry http://caniuse.com/#feat=shadowdom, but what Chrome implements
until M52 is based on pre-v1 spec.

V0 and V1 has considerable API difference and no backward compatibility, so we would like to
have separate entries for each, to avoid any confusion or false expectation.
FYI http://hayato.io/2016/shadowdomv1/ describes the difference.

Safari 10+ and Chrome M53+ will support Shadow DOM v1, and having the separate entry would
avoid confusion and clarifies since when Shadow DOM v1 support started on browsers.

Meanwhile we also rename the old Shadow DOM entry as "Shadow DOM v0" and add notes
about what it is.

**Comment by Fyrd** [comment]
Has now been added at http://caniuse.com/#feat=shadowdomv1
