### ISSUE TITLE
Add :host/:host-context pseudo class

### ISSUE THREAD

**Issue by TakayoshiKochi** [Fyrd/caniuse#2667]
As a part of Shadow DOM, `:host` / `:host-context()` pseudo classes are introduced to CSS
scoping spec.
https://drafts.csswg.org/css-scoping/

Chrome implements this, and the semantics doesn't change for V0 and V1.
Safari implements :host from Safari 10, but does not have intention to implement :host-context().

Having this entry would be informative to know the difference, if a note like "Safari doesn't have
`:host-context()`" is added.

**Comment by Schweinepriester** [comment]
+1

https://webkit.org/blog/6928/release-notes-for-safari-technology-preview-release-12/

> Enabled the `:host` pseudo-class to style elements in the shadow tree

**Comment by dhniels** [comment]
+1

also shadow piercing descendent combinators

:host
/deep/
>>>

**Comment by marosca** [comment]
+1

**Comment by bzkny** [comment]
+1 also ::part and ::theme

**Comment by mrtnmgs** [comment]
+1

**Comment by lvzhenbang** [comment]
+1

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-css_selectors_host and https://caniuse.com/#feat=mdn-css_selectors_host-context
