### ISSUE TITLE
Add Background Sync

### ISSUE THREAD

**Issue by sdgluck** [Fyrd/caniuse#2677]
AFAIK it is supported only by Chrome (and Chrome Canary) at the moment.

I guess this would be added as `feat=backgroundsync`.

**Comment by cvrebert** [comment]
https://github.com/WICG/BackgroundSync

**Comment by NOtherDev** [comment]
It's in development in [Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/backgroundsyncapi/) and [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1217544) now.

**Comment by cvrebert** [comment]
Shipped in Edge 15 per https://docs.microsoft.com/en-us/microsoft-edge/dev-guide#new-apis-in-edgehtml-15

**Comment by awebdeveloper** [comment]
@cvrebert as per this it's still in development

https://developer.microsoft.com/en-us/microsoft-edge/platform/status/backgroundsyncapi/?q=sync

**Comment by cvrebert** [comment]
https://platform-status.mozilla.org/#background-sync

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=background-sync
