### ISSUE TITLE
Slash-separated color functions

### ISSUE THREAD

**Issue by ZachSaucier** [Fyrd/caniuse#2679]
Can the [CSS Color page](http://caniuse.com/#feat=css3-colors) be edited to include the new [slash-separated alpha value syntax](https://github.com/w3c/csswg-drafts/blob/a54f8b2089d16eca696690fe7ffc3c11d4db9861/css-color/Overview.bs#L78)? It also includes leaving out commas. Or a new page created specifically for it.

**Comment by chharvey** [comment]
Here's the spec: https://drafts.csswg.org/css-color/#rgb-functions

It allows for space-separated values for the red, green, and blue channels, with an optional alpha value followed by a slash.

**Comment by chharvey** [comment]
Here are some reports:

- **Chrome 65+** supports [`rgb()` & `rgba()`](https://bugs.chromium.org/p/chromium/issues/detail?id=788707) and [`hsl()` & `hsla()`](https://bugs.chromium.org/p/chromium/issues/detail?id=786139) space-separated values.
- **Firefox 52+** also [supports the same](https://bugzilla.mozilla.org/show_bug.cgi?id=1295456).
- According to [Browser Compatibility on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color#Browser_compatibility), **Chrome 65+**, **Firefox 52+**, and **Opera 52+** offer support. There is no verdict on **IE**, **Edge**, or **Safari** yet.

**Comment by mathiasbynens** [comment]
> There is no verdict on [...] Safari yet.

For Safari, the relevant bug was <https://bugs.webkit.org/show_bug.cgi?id=192321>.

It seems this is now covered on caniuse here: https://caniuse.com/#feat=mdn-css_types_color_space_separated_functional_notation

**Comment by chharvey** [comment]
@mathiasbynens That looks good! Can we include these resources?

- https://www.w3.org/TR/css-color-4/#rgb-functions
- https://developer.mozilla.org/en-US/docs/Web/CSS/color_value

**Comment by mathiasbynens** [comment]
For specs, we should always link to the working drafts, since that's what browsers strive to implement: https://drafts.csswg.org/css-color/#rgb-functions

**Comment by Fyrd** [comment]
As mentioned, this is available at https://caniuse.com/#feat=mdn-css_types_color_space_separated_functional_notation

For now it's not possible to add resources to MDN-generated support tables, though I plan on making that an option in the future.
