### ISSUE TITLE
Support Tables for Gesture Events

### ISSUE THREAD

**Issue by MauriceConrad** [Fyrd/caniuse#2680]
Please add support for the new gesture events in iOS Safari 9 and OS X Safari 10. On iOS a gesture event uses the multi touch screen and on desktop it uses the trackpad. https://developer.apple.com/library/mac/documentation/UserExperience/Reference/GestureEventClassReference/index.html#//apple_ref/doc/uid/TP40009353

**Comment by cvrebert** [comment]
MDN has some data: https://developer.mozilla.org/en-US/docs/Web/API/GestureEvent#Browser_compatibility
(These events are completely nonstandard, BTW.)

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#search=gestureevent etc
