### ISSUE TITLE
Add maxTouchPoints

### ISSUE THREAD

**Issue by vasimi** [Fyrd/caniuse#2681]
navigator.maxTouchPoints is important for websites which need to know if user's device have touchscreen

**Comment by cvrebert** [comment]
`maxTouchPoints` is part of Pointer Events, which already has an entry:
http://caniuse.com/#feat=pointer

**Comment by Fyrd** [comment]
Also now available at https://caniuse.com/#feat=mdn-api_navigator_maxtouchpoints
