### ISSUE TITLE
Add CSS resize style.

### ISSUE THREAD

**Issue by jsgao0** [Fyrd/caniuse#2683]
I was thinking how disable resizable property of **textarea** and I got [this](https://developer.mozilla.org/en-US/docs/Web/CSS/resize) from MDN.

**Comment by Schweinepriester** [comment]
Probably already present: http://caniuse.com/#feat=css-resize

**Comment by Fyrd** [comment]
Yup, already available.

**Comment by peterdd** [comment]
If I search 'resize'  on caniuse.com, this is not found.
Only if I search 'css-resize'  or 'css-r' ...
