### ISSUE TITLE
video/audio events like loadedemetadata

### ISSUE THREAD

**Issue by rokyed** [Fyrd/caniuse#2689]
video/audio events like loadedemetadata

**Comment by cvrebert** [comment]
https://developer.mozilla.org/en-US/docs/Web/Events/loadedmetadata

**Comment by Fyrd** [comment]
Similar to #1003. Need to do the research, but I'm pretty sure these events are all supported by the browsers that already support video/audio.

**Comment by Fyrd** [comment]
Should all be available now, e.g. https://caniuse.com/#feat=mdn-api_htmlmediaelement_loadedmetadata_event
