### ISSUE TITLE
Add Element.insertAdjacentElement, Element.insertAdjacentText

### ISSUE THREAD

**Issue by CaitlinWeb** [Fyrd/caniuse#2694]
Not sure if these DOM functions are supported in all browsers.

See: 
https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentElement
https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentText

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=insert-adjacent
