### ISSUE TITLE
Add PerformanceObserver

### ISSUE THREAD

**Issue by G-Bro** [Fyrd/caniuse#2698]
https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver 

Used for monitoring performance. Currently seems to work only in Firefox 49 and Chrome 52

**Comment by cvrebert** [comment]
* https://platform-status.mozilla.org/#performance-observer
* https://www.chromestatus.com/feature/5945504202489856

**Comment by nathanbower** [comment]
https://w3c.github.io/performance-timeline/#the-performanceobserver-interface

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_performanceobserver
