### ISSUE TITLE
Latest stable version of Opera is wrong

### ISSUE THREAD

**Issue by beaufortfrancois** [Fyrd/caniuse#2710]
Hey @Fyrd,

According to http://www.opera.com/docs/history/, Opera 37 is the latest stable version while http://caniuse.com/#feat=web-bluetooth shows for instance Opera 39.

Can we fix that?

**Comment by Fyrd** [comment]
That page seems to be out of date (note: "Last update: 2016-05-04"). They announced 39 as the latest version here: http://www.opera.com/blogs/desktop/2016/08/personalized-newsreader-improved-video-popout-in-opera39/
