### ISSUE TITLE
attachEvent event handler missing from CanIUse

### ISSUE THREAD

**Issue by bhatyogesh94** [Fyrd/caniuse#2712]

**Comment by cvrebert** [comment]
`attachEvent` is an old IE-ism. [`addEventListener`](http://caniuse.com/#feat=addeventlistener) is the standard equivalent.
Cursory testing suggests that none of the current modern browsers (including IE11) support `attachEvent`.

**Comment by Fyrd** [comment]
Search result now available: https://caniuse.com/?search=attachevent
