### ISSUE TITLE
Update Edge support data

### ISSUE THREAD

**Issue by Studio384** [Fyrd/caniuse#2719]
In the latest preview Edge 14.14901 (which I'll guess is going to become Edge 15) Edge now supports WebRTC, Service Workers and Push API all behind flags.

**Comment by ElPumpo** [comment]
What's the hold up for?

**Comment by Studio384** [comment]
Build 14986 contains some major updates to the EdgeHTML engine. When is this finally going to be listed?

**Comment by jdalton** [comment]
@Studio384 Are you up for creating a pull request?

**Comment by Fyrd** [comment]
I'll try to get it added by end of day,  thanks for the reminder

**Comment by Studio384** [comment]
@jdalton We're not allowed to add a new browser version if I'm not mistaken.

**Comment by chicoxyzzy** [comment]
Sorry for asking here but we can't find anyone with Edge 15 and Edge 15 VMs from developers website are install Edge 14 for some reason... 😞 

Can some help us to add Edge test results?
https://github.com/kangax/compat-table/issues/980

Thank you and sorry again

**Comment by Fyrd** [comment]
Now added!
