### ISSUE TITLE
Feed does not work anymore

### ISSUE THREAD

**Issue by valtlai** [Fyrd/caniuse#2728]
RSS feed has stuck in 05/2015. Any news after that are not included.

**Comment by Fyrd** [comment]
Technically the feed still works...I just recently included an automated way for newly-added features to retroactively appear in the site's news list. This is currently done via JS so does not affect the feed. 

I'll leave this issue open and consider it a request to include newly added features in the RSS feed too.

**Comment by soluml** [comment]
I'd like to +1 this issue. RSS Feeds are an essential part of me being able to stay informed on web development. Are you comfortable with us creating our own feeds from the `get_news.php` JSON blob or is there some PR we can work on to restore the original feed?

**Comment by wcjr** [comment]
I just add the the feed and noticed it's way behind what shows up on https://caniuse.com/#info_news.  Is there any possibility of this getting fixed?

**Comment by VagrantAI-c** [comment]
up, https://caniuse.com/feed.php is still broken

**Comment by Fyrd** [comment]
Feed is now [back up](https://caniuse.com/feed) _and_ now automatically includes any new features added to the site, matching what's on https://caniuse.com/#info_news

Apologies for the inconvenience, all!

**Comment by soluml** [comment]
Didn't see this thread but noticed today that CanIUse data was showing back up in my RSS Reader.  Thanks a bunch @Fyrd!
