### ISSUE TITLE
Improve explanation about Edge version number

### ISSUE THREAD

**Issue by SaschaNaz** [Fyrd/caniuse#2731]
Currently caniuse says:

>Version number used for Edge is based on the number used in the user agent string, not the Edge "About" page. This is because the UA version number represents the version with changes in the browser's engine

but there is no "About" page, and the "Settings" page shows correct UA version. 

```
About this app: 

Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393
(c) 2016 Microsoft
```

I would say that:

>Version number used for Edge is based on the number of EdgeHTML rather than Edge itself. This is because EdgeHTML is the engine for Edge that is related to feature support change.

**Comment by Fyrd** [comment]
Ah, excellent point, thanks. Yeah that note was based on Edge 12's behavior which only showed the other version.

**Comment by Fyrd** [comment]
Has been updated, used your suggested text. :) Thanks!
