### ISSUE TITLE
MathML support shaky in Safari

### ISSUE THREAD

**Issue by Xyene** [Fyrd/caniuse#2734]
caniuse data says MathML has been supported in Safari since 5.1, but support &mdash; even in 9.0 &mdash; seems to be closer to "partial support" than "full support" due to the large number of rendering issues making it hard to use for professional uses.

Some screenshots of the [MathML Torture Test](https://developer.mozilla.org/en-US/docs/Mozilla/MathML_Project/MathML_Torture_Test) from Safari 9.0 using Latin Modern Math fonts:

![image](https://cloud.githubusercontent.com/assets/1403503/17744792/3ec6e736-6477-11e6-9bc8-d91be9f49cbd.png)

![image](https://cloud.githubusercontent.com/assets/1403503/17744809/4c2159d4-6477-11e6-86a1-9260ca683e55.png)

![image](https://cloud.githubusercontent.com/assets/1403503/17744835/73fe4b60-6477-11e6-8ded-4cdf351305eb.png)

![image](https://cloud.githubusercontent.com/assets/1403503/17744938/df02f4c4-6477-11e6-9a48-fe353128a1ed.png)

The WebKit codebase recently received a bunch of improvements in its MathML support that resolved the above issues, among others (a very nice post on this can be found [here](http://frederic-wang.fr/mathml-improvements-in-webkit.html)), but as it stands I think at least the addition of a note mentioning rendering pitfalls would be appropriate.

**Comment by atjn** [comment]
Seems like this should be closed

**Comment by Xyene** [comment]
Yep :)
