### ISSUE TITLE
Firefox supports CSS Containment behind preference

### ISSUE THREAD

**Issue by lxender** [Fyrd/caniuse#2736]
Firefox supports CSS Containment behind "css.layout.contain.enabled" true or false since Firefox 47. 
I tried to edit it, but I guess it failed because I am not authenticated to do that. (I'm new to Github tho, so something else could be the error.)
When I edited it, I put:

<pre>
      "47":"n d #2",
      "48":"n d #2",
      "49":"n d #2",
      "50":"n d #2",
</pre>

and created a note:

<pre>
"2":"Can be enabled through the \"layout.css.contain.enabled\" preference in about:config"
</pre>

**Comment by Schweinepriester** [comment]
I believe this issue is obsolete, given the age but also because https://caniuse.com/css-containment by now shows what you requested:

![image](https://user-images.githubusercontent.com/2644614/177873893-972f1e81-89af-4be6-9a85-e932c487e22a.png)

**Comment by Fyrd** [comment]
Closing as per above.
