### ISSUE TITLE
chromestatus.com/feature vs. chromestatus.com/features

### ISSUE THREAD

**Issue by dandv** [Fyrd/caniuse#2737]
Should the Chrome status link be to the individual feature (focuses, loads much faster), or to feature<b>s</b>?

Example: at http://caniuse.com/#feat=ambient-light, click "[in development](http://www.chromestatus.com/features/5298357018820608)", vs. without the 's': http://www.chromestatus.com/feature/5298357018820608.

**Comment by Fyrd** [comment]
Good idea, has now been changed to the `/feature/` link. Thanks!
