### ISSUE TITLE
window.scroll

### ISSUE THREAD

**Issue by CathyMacars** [Fyrd/caniuse#2740]
https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll

**Comment by vincentonderwaater** [comment]
bump

**Comment by jhbsk** [comment]
+1

**Comment by jhbsk** [comment]
Although I think it's covered here: https://caniuse.com/#feat=css-scroll-behavior, but most would search this under the keyword "window.scroll"

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_window_scroll
