### ISSUE TITLE
Filtering for `text-align` doesn't show the CSS Logical Properties item, but should

### ISSUE THREAD

**Issue by alanhogan** [Fyrd/caniuse#2744]
CSS Logical Properties includes  the status of `text-align: start` and `text-align: end`, users searching for `text-align start` won't see the desired information. (Instead, they can search for Logical.)

**Comment by Fyrd** [comment]
I believe the results are now as expected: https://caniuse.com/?search=text-align%20start now shows the support table for "CSS property: text-align: Flow-relative values start and end"
