### ISSUE TITLE
CSS Logical Properties support chart is out-of-date

### ISSUE THREAD

**Issue by alanhogan** [Fyrd/caniuse#2745]
[CSS Logical Properties](http://caniuse.com/#feat=css-logical-props) is out of date. 

**Firefox**

It indicates that current and future Firefox versions do _not_ support the `text-align: start` and `text-align: end` values (note 1), but in fact I just confirmed that Firefox does support this in version 47.0.1.

Here is my test page: https://codepen.io/alanhogan/pen/jARkXG

![screen shot 2016-08-22 at 2 25 41 pm](https://cloud.githubusercontent.com/assets/6808/17872312/54b0ca7a-6874-11e6-9941-afb572d123ce.png)

The above screen shot is of the Firefox 47.0.1 (on Mac OS X 10.11) rendering, which is totally correct and matches Chrome et al.

In fact, the MDN page suggests that `text-align: end` has been supported since Firefox 3.6! https://developer.mozilla.org/en-US/docs/Web/CSS/text-align#Browser_compatibility

⁂

**Multiple Browsers**

The chart indicates that vendor prefixes are needed, but my [test page](https://codepen.io/alanhogan/pen/jARkXG) works unprefixed in all tested browsers (except MSIE/Edge where there is no support). I tested unprefixed `text-align: start` Firefox, Chrome, and Safari. 

I’m not sure if other logical properties need a prefix, but the chart is at best misleading on this point, as it stands today.

Thank you.

**Comment by Fyrd** [comment]
This was updated some time ago, so closing ticket.
