### ISSUE TITLE
Same column for IE & Edge?

### ISSUE THREAD

**Issue by remino** [Fyrd/caniuse#2746]
I was wondering why IE & Edge aren't under one “IE/Edge” column.

I don't know how most people feel about this, but I view Edge as the successor of IE, with a different name and a different engine. The version numbers are also lined up to suggest that.

Putting both names in the same column could save a bit of screen real estate too.

Mind you, I haven't used IE in a long time, so maybe I'm missing something.

**Comment by Schweinepriester** [comment]
> Edge as the successor of IE, with a different name and a different engine.

This and that the engine is way less bad than IE justifies the treatment as separate browser, and not just another newer version of IE. (Also, Edge has a more regular update cycle, wherefore devs can assume Edge is being used as 'latest', whereas each version of IE needs its own treatment.)

**Comment by remino** [comment]
I see. Like I said, never tried Edge and didn't use IE for years. Guess I'm missing out.

**Comment by Fyrd** [comment]
When Edge was released, both were indeed put in the same column for the reasons you described. However it was requested to split the two up, which I think helps save on confusion. So no plans no revert back to the previous behavior.
