### ISSUE TITLE
Add vCard to caniuse.com ?

### ISSUE THREAD

**Issue by shivanraptor** [Fyrd/caniuse#2751]
Can the site add "vCard" browser compatibility list ?

**Comment by cvrebert** [comment]
Browsers themselves don't generally include address book functionality, so how is vCard applicable to browsers?

**Comment by shivanraptor** [comment]
Not exactly true.  Most browsers will launch default software (such as Outlook in Windows, or Contacts in Mac) associated with vCard (*.vcf) format.

**Comment by cvrebert** [comment]
Browsers normally do that by invoking a generic OS "open" operation on the downloaded file, and the OS uses whichever program has relevant file type associations setup to open the file. So the browser itself has no vCard-specific logic.

**Comment by Fyrd** [comment]
Right, what @cvrebert said. Not something that needs to be tracked on caniuse.
