### ISSUE TITLE
X-Content-Type-Options: nosniff

### ISSUE THREAD

**Issue by cvrebert** [Fyrd/caniuse#2758]
- Spec: https://fetch.spec.whatwg.org/#x-content-type-options-header
- https://blog.mozilla.org/security/2016/08/26/mitigating-mime-confusion-attacks-in-firefox/
- https://www.owasp.org/index.php/OWASP_Secure_Headers_Project#X-Content-Type-Options
- https://msdn.microsoft.com/en-us/library/gg622941(v=vs.85).aspx

**Comment by claudepache** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by Schweinepriester** [comment]
[FF50](https://developer.mozilla.org/de/Firefox/Releases/50):

> Support for X-Content-Type-Options has been added

<https://bugzilla.mozilla.org/show_bug.cgi?id=471020>

**Comment by Calico90** [comment]
+1

**Comment by cvrebert** [comment]
Supported in Safari Technology Preview 30:
https://webkit.org/blog/7614/release-notes-for-safari-technology-preview-30/

**Comment by cvrebert** [comment]
Presumably supported in Chrome since before the Blink fork, judging by https://trac.webkit.org/changeset/142683/webkit

**Comment by Calico90** [comment]
Supported in Chrome >=1.0
IE >= 8.0
Edge
Firefox >= 50
Opera >= 13

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options

Add in the security category.

**Comment by afx2000** [comment]
+1

**Comment by BreakfastSerial** [comment]
**+1**

**Comment by mik-laj** [comment]
+1

**Comment by Malvoz** [comment]
+1

**Comment by JoseRoman** [comment]
+1

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-http_headers_x-content-type-options
