### ISSUE TITLE
Opening up a little aka. add @cvrebert as collaborator?

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#2759]
As @cvrebert does evidently a good job ([#1](https://github.com/Fyrd/caniuse/pulls?q=is%3Apr+author%3Acvrebert+is%3Aclosed), [#2](https://github.com/Fyrd/caniuse/graphs/contributors)), how about adding him as collaborator to this repo, to increase efficiency, since most pull requests are accepted without objection and duplicate issues are correctly marked, etc.

I hope i make myself not unpopular with this suggestion, just want to help improve caniuse even further :)

**Comment by Fyrd** [comment]
Currently on vacation, but I'll be happy to consider this a bit more when I get back in two weeks... @cvrebert is this something you'd be interested in?

**Comment by cvrebert** [comment]
Sure.

**Comment by Schweinepriester** [comment]
Reminder 😇
