### ISSUE TITLE
Canvas context getTransform() function.

### ISSUE THREAD

**Issue by ericrini** [Fyrd/caniuse#2762]
Here's a link to the specification for the function.

https://html.spec.whatwg.org/multipage/scripting.html#dom-context-2d-gettransform

Right now, it looks like only Firefox has it, and it has a moz vendor prefix on it. Might be nice to start tracking it?

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_canvasrenderingcontext2d_gettransform
