### ISSUE TITLE
Can I Use reports CSS Grid Layout will work in Safari 10 — and that's wrong

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#2763]
Safari 10 beta does not support CSS Grid. 
Safari Technical Preview currently does. 
Presumably when Safari 10 ships this fall, it will not support CSS Grid.

This is the closest thing to an official word from Apple on when Grid will ship:
> "CSS Grid is not enabled in macOS Sierra and iOS 10 Safari. It is enabled in the Safari Technology Preview." — https://twitter.com/grorgwork/status/766392584679755777

I've seen people presenting on conference stages telling folks that Grid will ship in Safari 10. This is wrong. They are saying this because they are looking at Can I Use. Could we please fix the data to be accurate by removing the green box for Safari 10 at http://caniuse.com/#feat=css-grid?

While Safari TP has a version number, and while it's easy to assume that anything in Safari TP v10 will be in Safari v10, that's not how it works. Much like Firefox Nightly, things may or may not make it to the shipping version. Firefox Nightly is at v51, and currently supports Grid. Nightly v50 also supported Grid without a flag, but Grid will not ship in FF50. It might make it into FF51, but no one knows quite yet. Might be FF52 or later. It depends on when Grid is 100%, stable, bug-free-enough, etc. And we aren't far along yet to be able to predict when all those conditions will be true. Seeing a feature land unflagged in the experimental browser doesn't map to when it will ship in release. 

Thanks! I just hate to see people teaching wrong information.

**Comment by Fyrd** [comment]
Thanks Jen! Have updated it to appear as "unknown" for now. Sorry about the mistake and the trouble it's caused you. Not sure how it happened.
