### ISSUE TITLE
CSS.escape()

### ISSUE THREAD

**Issue by cvrebert** [Fyrd/caniuse#2764]
- Spec: https://drafts.csswg.org/cssom/#the-css.escape()-method
- MDN: https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape
- WebKit Nightly: https://bugs.webkit.org/show_bug.cgi?id=126337

**Comment by Ugoku** [comment]
+1

**Comment by mathiasbynens** [comment]
Polyfill: https://github.com/mathiasbynens/CSS.escape

**Comment by mathiasbynens** [comment]
Available since:

- [Chrome 46 & Opera 33](https://dev.opera.com/blog/opera-33/#cssescapestring)
- Firefox 31
- Safari: not sure when it shipped exactly, but the implementation [landed in trunk]()https://trac.webkit.org/changeset/204952) over a year ago.

**Comment by Slapbox** [comment]
@Fyrd is it possible to include this on the site?

Mozilla.org has some basic information on compatibility by browser [here](https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape).

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_css_escape
