### ISSUE TITLE
FLAC doesn't show up in the search nor in the diagram

### ISSUE THREAD

**Issue by est31** [Fyrd/caniuse#2766]
There appears to be support for flac, as you can see here: https://github.com/Fyrd/caniuse/blob/HEAD/features-json/flac.json

See also #2185 which has added support for FLAC.

But flac does not show up in the main website.

Neither with a search: http://caniuse.com/#search=flac
Nor with an attempt to get a direct link: http://caniuse.com/#feat=flac

**Comment by smatric** [comment]
Firefox 51 is adding support for FLAC:
https://bugzilla.mozilla.org/show_bug.cgi?id=1195723
It would be good to start keeping track of this feature.

**Comment by Fyrd** [comment]
The data's currently still incomplete and pending review, which is why it isn't on the site yet (and until now there hadn't been any requests to show it)

**Comment by Schweinepriester** [comment]
+1

**Comment by est31** [comment]
Its coming to chrom{e,ium} as well: https://bugs.chromium.org/p/chromium/issues/detail?id=93887

**Comment by Schweinepriester** [comment]
As now mentioned in <https://bugs.chromium.org/p/chromium/issues/detail?id=93887>, Chrome 56+ will support FLAC.
For the record: <https://9to5google.com/2017/01/12/chrome-56-flac-playback/>

**Comment by Schweinepriester** [comment]
Firefox 51 with support for FLAC is now stable: <https://www.mozilla.org/en-US/firefox/51.0/releasenotes/>

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=flac
