### ISSUE TITLE
New filesystem api?

### ISSUE THREAD

**Issue by jimmywarting** [Fyrd/caniuse#2781]
Do the feature hold a new promesified filesystem api?
http://w3c.github.io/filesystem-api/

**Comment by donmccurdy** [comment]
I assume [this entry](http://caniuse.com/#feat=filesystem) refers to the new API now?

The FileSystem API (new? old? [it's confusing](https://github.com/w3c/filesystem-api/issues/8)) has been implemented in Firefox 50 and Edge, which is not yet reflected in caniuse.

https://developer.mozilla.org/en-US/docs/Web/API/FileSystem

**Comment by Fyrd** [comment]
Yeah, it's been at https://caniuse.com/#feat=filesystem for a while now.
