### ISSUE TITLE
Feature suggestion: add browsers release date on hover

### ISSUE THREAD

**Issue by lingtalfi** [Fyrd/caniuse#2786]
I wanted to see WHEN the css grid layout module would be available
(i.e. I could use it if it would be on firefox and chromes's main releases in less than 6 months).
So I go to this page:
http://caniuse.com/#feat=css-grid

I know that it's not planned (without flags) in firefox at least before version 51, or in chrome before
version 55.
That's fine, but then WHEN are those releases going out? Is it weekly, monthly, yearly?

So I hover over the red boxes (51 for firefox) on the caniuse website, and there is some information, but not the crucial information: WHEN is this release going to be out.

So I could google that here:
https://wiki.mozilla.org/RapidRelease/Calendar
https://www.chromium.org/developers/calendar

But I believe it would be a great feature to have it baked in in the caniuse website.

**Comment by cvrebert** [comment]
Duplicate of #2175 ?

**Comment by lingtalfi** [comment]
indeed, thanks.
