### ISSUE TITLE
about cssText

### ISSUE THREAD

**Issue by fengyinchao** [Fyrd/caniuse#2800]
cssText

**Comment by Schweinepriester** [comment]
@fengyinchao what exactly do you mean?

<https://developer.mozilla.org/en-US/docs/Web/API/CSSRule/cssText> or maybe <https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/cssText>? Or which browser implemented the changes from 2013: <https://www.w3.org/TR/cssom-1/#changes-from-5-december-2013>?

- Spec: <https://www.w3.org/TR/DOM-Level-2-Style/> ==> <https://www.w3.org/TR/DOM-Level-2-Style/css.html#CSS-CSSRule>
- Most likely anywhere available: <http://www.w3schools.com/jsref/prop_style_csstext.asp>

**Comment by Fyrd** [comment]
Various tables available now for https://caniuse.com/#search=cssText so closing this.
