### ISSUE TITLE
Add createImageBitmap

### ISSUE THREAD

**Issue by castillobgr** [Fyrd/caniuse#2801]
[createImageBitmap](https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmapFactories/createImageBitmap) isn't currently available. It'd be cool if it was :)

**Comment by dman777** [comment]
Vote +1

**Comment by salarelv** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

<https://webkit.org/blog/8035/release-notes-for-safari-technology-preview-44/>

> Implemented createImageBitmap() with HTMLCanvasElement

Technically this issue is a duplicate of #2277, as already mentioned there, but this one here has more votes.

Additionally: Subfeature of #2676?

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=createimagebitmap
