### ISSUE TITLE
iOS 10 is stable & Safari 10 soon

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#2802]
You probably would have thought of it yourself, but:

- [iOS 10 is stable](http://www.macrumors.com/2016/09/13/apple-releases-ios-10/)
- [Safari 10 will be soon, on 2016-09-20](http://www.macrumors.com/2016/09/07/macos-sierra-golden-master/)

For the record the changelog again https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html, but we probably handled everything in #2572.

**Comment by Fyrd** [comment]
iOS 10 has been added.

**Comment by Schweinepriester** [comment]
Now available: <http://www.macrumors.com/2016/09/20/safari-10-os-x-el-capitan-yosemite-released/>
