### ISSUE TITLE
Add window.onresize event

### ISSUE THREAD

**Issue by ghost** [Fyrd/caniuse#2803]
I cannot seem to find the DOM onresize event. This is a WHATWG living standard (I presume)

W3C Proof: https://www.w3.org/TR/DOM-Level-2-Events/events.html#Events-eventgroupings-htmlevents
(scroll down a bit)

It is supported in all major browsers with no version information according to w3schools (http://www.w3schools.com/jsref//event_onresize.asp)

EDIT: Also here's a link from MDN: https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onresize

Thanks in advance,
matemate01

**Comment by cvrebert** [comment]
* https://developer.mozilla.org/en-US/docs/Web/Events/resize
* http://www.w3.org/TR/cssom-view-1/#resizing-viewports

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_window_resize_event
