### ISSUE TITLE
There is no entry showing support for !important

### ISSUE THREAD

**Issue by rowbot-weisguy** [Fyrd/caniuse#2805]
`!important` is a contentious feature of CSS that not everybody can agree on supporting.

![image](https://cloud.githubusercontent.com/assets/4230333/18495680/c68fa55a-79d4-11e6-9a18-89fe3b9ebd3b.png)

Having an objective source of truth for `!important` support would be useful for many developers.

**Comment by calderonroberto** [comment]
This sounds !important to me.

**Comment by cvrebert** [comment]
Duplicate of #1388. Searching existing issues before opening new ones is important.

**Comment by rowbot-weisguy** [comment]
Very important. Thanks for the pointer @cvrebert.
