### ISSUE TITLE
Support Element.attachShadow

### ISSUE THREAD

**Issue by larsrc-google** [Fyrd/caniuse#2806]
Spec: https://www.w3.org/TR/shadow-dom/#widl-Element-attachShadow-ShadowRoot-ShadowRootInit-shadowRootInitDict

This method is less supported than general Shadow DOM. We could have prevented an internal outage if this had been supported (and we had remembered to look).

**Comment by Fyrd** [comment]
Now added as part of http://caniuse.com/#feat=shadowdomv1
