### ISSUE TITLE
Support setCapture and releaseCapture for mouse

### ISSUE THREAD

**Issue by gagern** [Fyrd/caniuse#2807]
Please support checks for the mouse capturing interface `Element.setCapture` and `Document.releaseCapture`.

See [`setCapture`](https://developer.mozilla.org/en-US/docs/Web/API/Element/setCapture) and [`releaseCapture`](https://developer.mozilla.org/en-US/docs/Web/API/Document/releaseCapture) at MDN, as well as the entry under [the WHATWG API ToDo list](https://wiki.whatwg.org/wiki/Specs/todo#APIs) ([versioned link](https://wiki.whatwg.org/index.php?title=Specs/todo&oldid=10052#APIs)) which refers to [this mailing list post](http://lists.w3.org/Archives/Public/public-webapps/2008OctDec/0308.html).

**Comment by cvrebert** [comment]
(According to https://bugs.chromium.org/p/chromium/issues/detail?id=246536#c7 , these methods are superseded by Pointer Events' `setPointerCapture()`/`releasePointerCapture()` APIs.)
These might still be interesting for historical reasons though.
