### ISSUE TITLE
flex-shrink to be added for use review

### ISSUE THREAD

**Issue by Unradelic** [Fyrd/caniuse#2809]
Here I leave some information about this CSS parameter for flex works,
https://developer.mozilla.org/en-US/docs/Web/CSS/flex-shrink

As listed from #778 (October 2014), the flex family is yet to be listed on the portal

**Comment by cvrebert** [comment]
From http://caniuse.com/#feat=flexbox : 
> Support includes the support for the all properties prefixed with `flex` as well as [...]

**Comment by Fyrd** [comment]
Yup, already covered.
