### ISSUE TITLE
<video> `playsinline` attribute

### ISSUE THREAD

**Issue by calvinjuarez** [Fyrd/caniuse#2811]
Searching for `playsinline` doesn't return results.  It'd be nice if it had its own page or brought up info through the `<video>` entry.

**Comment by cvrebert** [comment]
Refs https://github.com/whatwg/html/pull/1444
Refs https://html.spec.whatwg.org/multipage/#attr-video-playsinline

**Comment by Schweinepriester** [comment]
Available via MDN: <https://caniuse.com/mdn-api_htmlvideoelement_playsinline>
