### ISSUE TITLE
Variable Open Type Fonts

### ISSUE THREAD

**Issue by matt7621** [Fyrd/caniuse#2812]
Would love to follow the progress on this. https://medium.com/@tiro/https-medium-com-tiro-introducing-opentype-variable-fonts-12ba6cd2369#.4asds3ayo

**Comment by Schweinepriester** [comment]
+1

https://twitter.com/bram_stein/status/782135926147411968

> Variation Fonts "In Development" in WebKit.

**Comment by aaronbarker** [comment]
+1

**Comment by jensimmons** [comment]
+100

**Comment by jpamental** [comment]
Yes - would be hugely helpful!

**Comment by Calico90** [comment]
+1

**Comment by PeterConstable** [comment]
+1

**Comment by thlinard** [comment]
+1

**Comment by zachleat** [comment]
Looks like they’re in Safari 11, which is stable now I think?

**Comment by thlinard** [comment]
Safari 11 on iOS 11 and macOS 10.13 (High Sierra), not Safari 11 on macOS 10.12 (Sierra).

**Comment by jrrdnx** [comment]
+1

**Comment by richardbruskowski** [comment]
+1

**Comment by jpamental** [comment]
Variable Font support is now live in both Safari (desktop 10.13 and iOS 11) and Chrome, and in development in Edge - would be SUPER helpful to have this!

**Comment by jensimmons** [comment]
Yes, we really need this one. @jpamental you should create a pull request. It's not too hard. Directions are here: https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md Grab a copy of the template and fill out the info. Having one of us do so will make this happen much sooner.

**Comment by jpamental** [comment]
Thanks @jensimmons I'll give it a shot!

**Comment by jensimmons** [comment]
@jpamental It’s incredibly satisfying. :) I was quite proud when a page I made was launched. Let me know if you get stuck, I’m happy to help.

**Comment by jpamental** [comment]
PR opened @jensimmons ! Thanks for the nudge :)

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=variable-fonts

**Comment by jpamental** [comment]
That’s awesome - thanks!

Jason
