### ISSUE TITLE
InputDeviceCapabilities API

### ISSUE THREAD

**Issue by jwoos** [Fyrd/caniuse#2813]
https://developer.mozilla.org/en-US/docs/Web/API/InputDeviceCapabilities_API

**Comment by Herst** [comment]
+1

**Comment by cvrebert** [comment]
https://wicg.github.io/InputDeviceCapabilities/

**Comment by GPHemsley** [comment]
Looks like this is now covered by MDN data:
https://caniuse.com/mdn-api_inputdevicecapabilities

(via mdn/browser-compat-data#2078)
