### ISSUE TITLE
Add -webkit-touch-callout?

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#2820]
- https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariCSSRef/Articles/StandardCSSProperties.html#//apple_ref/doc/uid/TP30001266-_webkit_touch_callout
- https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-touch-callout
- https://davidwalsh.name/webkit-css

> The `-webkit-touch-callout` property allows you to dictate what does or doesn't happen when a user taps and holds on a link on iOS. The default value is `default` and tap-holding on a link brings up the link bubble dialog; by using the value of `none`, that bubble never comes up.

EDIT:

Kinda related to <https://caniuse.com/#feat=user-select-none>.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-css_properties_-webkit-touch-callout
