### ISSUE TITLE
Add background-clip: text

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#2821]
Spec: https://drafts.csswg.org/css-backgrounds-4/#background-clip

From https://developer.mozilla.org/de/Firefox/Releases/49:

> On `background-clip`, the keyword `text` is now activated by default

`background-clip: text;` appears to have evolved from the `-webkit-background-clip: text;` mentioned on '[CSS3 Background-image options](http://caniuse.com/#feat=background-img-opts)' and in the [apple docs](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariCSSRef/Articles/StandardCSSProperties.html#//apple_ref/doc/uid/TP30001266--webkit-background-clip).

As support is different from the existing property, this probably should have its own entry.

https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip#Browser_compatibility has some overview:
- Chrome, Opera, Safari as `-webkit-background-clip: text;`
- Firefox 49+ as `background-clip: text;`

EDIT:

Apparently supported in Edge: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/10945389-background-clip-text

**Comment by cvrebert** [comment]
https://compat.spec.whatwg.org/#the-webkit-background-clip-property

**Comment by xtian** [comment]
+1

**Comment by jmmarco** [comment]
+1

**Comment by bencergazda** [comment]
When searching for `background-clip: text`, Caniuse currently redirects to https://caniuse.com/#feat=background-img-opts, which also suggests like IE11 supports `background-clip: text` (or `-moz-background-clip: text`), but in fact, IE11 does not.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-css_properties_background-clip_text

**Comment by Fyrd** [comment]
MDN entry is no longer available, caniuse entry now at https://caniuse.com/background-clip-text

**Comment by yisibl** [comment]
Update background-clip: text data and standardize it https://github.com/Fyrd/caniuse/pull/6898
