### ISSUE TITLE
Add `q` (quarter-millimeters) length unit

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#2822]
- Spec: https://drafts.csswg.org/css-values-3/#q
- https://developer.mozilla.org/de/Firefox/Releases/49
  
  > Added the `q` length unit 
- https://developer.mozilla.org/en-US/docs/Web/CSS/length#q, also see browser compatibility

**Comment by 1jj** [comment]
Chrome Intent to Implement and Ship: CSS: Support 'q' length unit:
https://github.com/login?return_to=%2FFyrd%2Fcaniuse%2Fissues%2F2822

**Comment by Schweinepriester** [comment]
I'm afraid you didn't post the correct link?

- <https://www.chromestatus.com/feature/5983903483428864>: In development
- <https://bugs.chromium.org/p/chromium/issues/detail?id=421907>

Nice :)

**Comment by 1jj** [comment]
Chrome Intent to Implement and Ship: CSS: Support 'q' length unit, correct link now:
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/RRUYxYvsRCk

**Comment by tgraham-antenna** [comment]
+1

**Comment by Schweinepriester** [comment]
<https://webkit.org/blog/9672/release-notes-for-safari-technology-preview-97/>

> Added support for the Q unit ([r251662](https://trac.webkit.org/changeset/251662/webkit/))

**Comment by Schweinepriester** [comment]
Safari 13.1+/iOS 13.4+: <https://webkit.org/blog/10247/new-webkit-features-in-safari-13-1/>

Also meanwhile via MDN on caniuse, though kinda duplicate…?
- <https://caniuse.com/#feat=mdn-css_types_length_q>
- <https://caniuse.com/#feat=mdn-css_types_length-percentage_q>

**Comment by adjenks** [comment]
It's a capital Q. Please update your link and title.

**Comment by GPHemsley** [comment]
Looks like this is now covered by MDN data:
https://caniuse.com/mdn-css_types_length_q
https://caniuse.com/mdn-css_types_length-percentage_q

(via mdn/browser-compat-data#838, mdn/browser-compat-data#981, mdn/browser-compat-data#3353)
