### ISSUE TITLE
Add browser support info for the HTTP Cache-Control header "immutable" flag

### ISSUE THREAD

**Issue by scunliffe** [Fyrd/caniuse#2828]
Browsers that support the **immutable** flag on the HTTP Cache-Control header won't send useless (If-None-Match or If-Modified-Since) requests just to get 304s on static content.

This was just added to Firefox 49: https://developer.mozilla.org/en-US/Firefox/Releases/49
Details about why this is important: http://bitsup.blogspot.ca/2016/05/cache-control-immutable.html?m=1

**Comment by Schweinepriester** [comment]
+1

**Comment by slorber** [comment]
+1 this is a really useful flag.

I have a S3 bucket with CloudFront on top of it, I never erase any file here and would like to serve immutable content to the user but don't know the support :(

**Comment by temoto** [comment]
Chrome bug so far says "we don't force revalidation since 54 anyway, so this flag would have no effect". So that probably means that in caniuse, Chrome 54+ should display as something like "supports same behavior via different syntax".

**Comment by anthonyryan1** [comment]
I'd argue the opposite. I think that's Chrome saying they feel this spec is superfluous and they don't intend to implement it.

**Comment by scunliffe** [comment]
There was a big write up on this and their work with Facebook.  While the
new header would prove useful, where developers updated their code, the
Chrome team decided that by changing the way their browser deals with
re-validation... so that "technically speaking" all users of all sites
would benefit from the changes they made.

Article: https://code.facebook.com/posts/557147474482256

While true, if all other browsers do not follow suit (or use their own
algorithm that differs from what Chrome is doing) then we end up in a
pickle with unclear specifications as to when a browser should/should not
re-validate.

If "all other browsers" indicate they plan to follow the same
path/algorithm to determine when a re-validation should occur, so be it,
but until they all come to the table on this with a plan to adopt, I'd
rather (as a web app developer) have the ability to explicitly indicate
which resources they can safely cache "forever" vs. have them "guess" which
ones. (my $0.02)

**Comment by temoto** [comment]
I hope we don't fall into useless chat here, but the immutabe syntax is in fact superflous. The behavior was already present with `cache-control: public, max-age=large`, but browsers interpreted it in "wrong" way, doing useless revalidation in presence of etag.

I hope we agree that behavior of avoiding excess validation is what's really important, developers need to know how to make their pages fast. And then they find advice to use this syntax for this browser, that syntax for that browser, as long as syntaxes don't conflict, add everything and be happy.

**Comment by mathiasbynens** [comment]
WebKit has it too: https://bugs.webkit.org/show_bug.cgi?id=167497 And they’re now looking to implement Chrome’s behavior, where the HTTP header opt-in is not even needed anymore.

**Comment by mkurz** [comment]
**Microsoft Edge 15 also shipped `cache-control:immutable` with the Creator Update! :tada:**

They just updated the uservoice ticket:
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/17168363-support-chrome-s-improved-reload-behavior-or-cache

**Comment by mkurz** [comment]
The Microsoft team also updated it's official status just now: https://github.com/MicrosoftEdge/Status/pull/514 :tada:

**Comment by Calico90** [comment]
+1

**Comment by Quezler** [comment]
+1

**Comment by Malvoz** [comment]
+1

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-http_headers_cache-control_immutable
