### ISSUE TITLE
Please add iFrame element contentWindow property

### ISSUE THREAD

**Issue by david-schopf** [Fyrd/caniuse#2850]
Please add iFrame element contentWindow property

**Comment by Ugoku** [comment]
From [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#Scripting):

> From the DOM iframe element, scripts can get access to the window object of the included HTML page via the contentWindow property. The contentDocument property refers to the document element inside the iframe (this is equivalent to contentWindow.document), but is not supported by Internet Explorer versions before IE8.

**Comment by gfox1984** [comment]
And also contentDocument please :)

**Comment by GPHemsley** [comment]
Looks like this is now covered by MDN data:
https://caniuse.com/mdn-api_htmliframeelement_contentwindow
https://caniuse.com/mdn-api_htmliframeelement_contentdocument

(via mdn/browser-compat-data#2017)

**Comment by david-schopf** [comment]
Thank you. I close the issue.
