### ISSUE TITLE
KeyboardEvent.isComposing

### ISSUE THREAD

**Issue by cvrebert** [Fyrd/caniuse#2863]
- https://www.w3.org/TR/uievents/#dom-keyboardevent-iscomposing
- https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/isComposing
- https://bugs.webkit.org/show_bug.cgi?id=162921

**Comment by Schweinepriester** [comment]
+1

From <https://webkit.org/blog/6987/release-notes-for-safari-technology-preview-15/>:

> Implemented KeyboardEvent.prototype.isComposing from the UI Event spec

[WebKit Bug 162921 is closed](https://bugs.webkit.org/show_bug.cgi?id=162921).

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_keyboardevent_iscomposing
