### ISSUE TITLE
Show global support per browser

### ISSUE THREAD

**Issue by bogas04** [Fyrd/caniuse#2866]
It's helpful to know global usage support but sometimes we really want to know how much support is there globally per browser. 61% support for Arrow Functions isn't helpful information if say you're making a Chrome Extension which would otherwise have 98% support. (Don't quote me for percentages).

In those cases it'll be great if we could just show net support for each browser in usage view. 
Like `Chrome (98%) IE (0%)` and so on.

If that's too complicated to show then at least a "Since version X" would be helpful. Inspector-hacking snippet for the same:

```js
document.querySelectorAll('.support-list').forEach(e => {
  let sinceVersion = (e.querySelector('ol li.y') || { textContent: null }).textContent;
  let $append = document.createElement('span');
  $append.textContent = sinceVersion ? `Since v${sinceVersion}` : `Not yet`;
  e.appendChild($append);
});
```

**Comment by Ugoku** [comment]
You can easily see this by using "Usage relative", right? For arrow functions in Chrome, it shows a tiny red bar at the top and completely green below that. It might not give exact percentages, but should give you an idea of support per browser.

**Comment by bogas04** [comment]
Yeah my point is to extend it a tad bit more ho give absolute figures instead of visual clue.

**Comment by bogas04** [comment]
Recent Data Relative view takes care of the use case, so I guess this is fixed.
