### ISSUE TITLE
Add the visibilitychange event

### ISSUE THREAD

**Issue by xovel** [Fyrd/caniuse#2872]
- [visibilitychange](https://developer.mozilla.org/en-US/docs/Web/Events/visibilitychange)
- [page-visibility](https://www.w3.org/TR/page-visibility/#sec-visibilitychange-event)

**Comment by cvrebert** [comment]
Already covered: http://caniuse.com/#feat=pagevisibility

**Comment by Fyrd** [comment]
Have added "visibilitychange" as keyword.
