### ISSUE TITLE
Entries API

### ISSUE THREAD

**Issue by feross** [Fyrd/caniuse#2885]
https://wicg.github.io/entries-api/

This is a subset of the Filesystem API (which is already on the site). But supposedly, this subset of the spec, dubbed the Entries API, is actually supported in Chrome, Firefox, and Edge.

More info here: https://github.com/w3c/filesystem-api/issues/8

**Comment by Schweinepriester** [comment]
+1

**Comment by theSdev** [comment]
+1

**Comment by theSdev** [comment]
Why did you close this issue @feross?

**Comment by feross** [comment]
It's been over 1 year and a half and I don't care about this anymore. Feel free to open a new issue if you want.
