### ISSUE TITLE
Why UC browser changed from 9.9 to 11?

### ISSUE THREAD

**Issue by yisibl** [Fyrd/caniuse#2888]
https://github.com/Fyrd/caniuse/blob/master/features-json/apng.json#L272

```json
    "and_uc":{
      "11":"n"
    },
```

**Comment by Schweinepriester** [comment]
See #2857.

**Comment by Fyrd** [comment]
I updated it to the latest version, that's all.

**Comment by yisibl** [comment]
@Fyrd In autoprefixer if the configuration of the `"uc": "9.9"` will lead to the error, because this version does not exist in caniuse.

**Comment by Fyrd** [comment]
Multiple mobile browsers only have the latest version listed on caniuse,
always been this way so I'm not sure why autoprefixer shouldn't be able to
deal with it.

**Comment by ai** [comment]
@yisibl ` last uc version` should work in browserslist
