### ISSUE TITLE
Add font-variation-settings?

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#2893]
From https://webkit.org/blog/6987/release-notes-for-safari-technology-preview-15/:

> - Implemented rendering of `font-variation-settings` and enabled it by default 
> - Implemented animation of `font-variation-settings`

Spec: https://drafts.csswg.org/css-fonts-4/#low-level-font-variation-settings-control-the-font-variation-settings-property

I hesitated, because I guessed it could be covered by any of http://caniuse.com/#search=font-var or be a (partial) duplicate of #2812. If so, please close.

**Comment by cvrebert** [comment]
* https://platform-status.mozilla.org/#css-font-variation-settings
* https://developer.microsoft.com/en-us/microsoft-edge/platform/status/fontvariationproperties/
* https://www.chromestatus.com/feature/4708676673732608
* https://webkit.org/status/#feature-variation-fonts

**Comment by Schweinepriester** [comment]
<https://twitter.com/abrax5/status/894490014549250048>:

> #variablefonts CSS Fonts Lvl 4 font-stretch/style/weight integration & font-variation-settings now default-enabled in @googlechrome Canary.

Chrome status hasn't been updated yet, but from the launch bug (<https://bugs.chromium.org/p/chromium/issues/detail?id=669453>):

> Enable OpenType Variable Fonts by default

> Labels: Launch-M-Target-62-Dev Launch-M-Target-62-Beta Launch-M-Target-62-Stable-Exp Launch-M-Target-62-Stable
Status: Fixed

So, Chrome 62+.

**Comment by awebdeveloper** [comment]
this already has all the needed data. Are we waiting for a PR here @Fyrd

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=variable-fonts
