### ISSUE TITLE
calc() not fully supported in IE10

### ISSUE THREAD

**Issue by tobireif** [Fyrd/caniuse#2899]
I had a line which looked something like this:

```
margin-left: calc(0px - (350px  - 50%));
```

It didn't work in IE10 (after resizing), so I had to implement the calculation using matchMedia().

And there are other issues:

https://encrypted.google.com/search?q=ie10+calc

The calc() page on caniuse.com should at least state that there can be severe issues with calc() in IE10.

**Comment by cvrebert** [comment]
> It didn't work in IE10 (after resizing)

Could you be more precise? How did it behave?
Perhaps this is the

> * IE11 is reported to have trouble with calc() with nested expressions, e.g. width: calc((100% - 10px) / 3); (i.e. it rounds differently)

entry in the "Known issues" in http://caniuse.com/#feat=calc and it applies to IE10 also?

**Comment by tobireif** [comment]
I implemented it using JS because the CSS calc() line didn't work in IE10. I don't have the CSS line anymore. It didn't work in IE10: it didn't have the intended effect, the margin was not affected (or not affected as intended) during resize. But it worked in IE11 etc.

Perhaps add "In IE10 there can be other issues as well."

The line might have looked something like this:
```
margin-left: calc(0px - (386.55px - 50%));
```

**Comment by Fyrd** [comment]
Closing as no longer relevant.
