### ISSUE TITLE
Flex box not working well in RTL direction layout

### ISSUE THREAD

**Issue by elkebirmed** [Fyrd/caniuse#2904]
Firefox is working, but the latest Chrome version is not!

The example will hide the third (red) column and this is the purpose, but when you try to resize the output window width, the third (red) column will be shown, this's just an RTL problem. if you change the layout to ltr, everything will be nice

this's the example: http://jsbin.com/gobisimiyo/edit?output

Any ideas?!

**Comment by cvrebert** [comment]
Consider filing a Chrome bug: https://crbug.com/new

**Comment by elkebirmed** [comment]
I will @cvrebert

Anyway, i found a way to fix this bug in Chrome by adding `overflow-x: hidden;` to the flex container. and for more details, this Chrome bug is occurring just in `flex-wrap: nowrap`

**Comment by Fyrd** [comment]
This isn't really the place for finding solutions for bugs, I'd recommend stackoverflow.com for that. If you can come up with a simple statement describing the issue it can be added to the flexbox issues list.
