### ISSUE TITLE
-webkit-backdrop-filter

### ISSUE THREAD

**Issue by alexduncan** [Fyrd/caniuse#2909]
Add `-webkit-backdrop-filter`.
https://webkit.org/blog/3632/introducing-backdrop-filters/

**Comment by Schweinepriester** [comment]
Dup of #1798, covered by <http://caniuse.com/#feat=css-backdrop-filter>?

**Comment by Fyrd** [comment]
http://caniuse.com/#search=-webkit-backdrop-filter already shows the feature, so I'm not sure why this was filed.
