### ISSUE TITLE
What does the red asterisk mean?

### ISSUE THREAD

**Issue by tonytonyjan** [Fyrd/caniuse#2914]
For example, we can see only Edge, iOS Safari, Opera Mini and Android Browser got a red asterisk symbol:
http://caniuse.com/#feat=object-fit
![](http://imgur.com/ZXItSzl.jpg)

I found there is a legend at the right-bottom corner telling meanings of each color without explaination of the red asterisk.

Did I miss anything?

**Comment by PascalReintjens** [comment]
I guess it means that you can click on the browser name to get additional information

**Comment by tonytonyjan** [comment]
@PascalReintjens Thanks, I didn't know browser names are clickable...
