### ISSUE TITLE
system-ui value for font-family

### ISSUE THREAD

**Issue by cvrebert** [Fyrd/caniuse#2918]
- Spec: https://drafts.csswg.org/css-fonts-4/#valdef-font-family-system-ui
- https://webkit.org/blog/3709/using-the-system-font-in-web-content/
- https://www.chromestatus.com/feature/5640395337760768
- https://bugs.webkit.org/show_bug.cgi?id=151493
- https://bugzilla.mozilla.org/show_bug.cgi?id=1226042

**Comment by Schweinepriester** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=font-family-system-ui

**Comment by Malvoz** [comment]
Looking at [https://caniuse.com/#feat=font-family-system-ui](https://caniuse.com/#feat=font-family-system-ui), notes says:
> 1. Supported as the -apple-ui value (only on Mac)

Is this a typo? I am aware of the `-apple-system` value, but not `apple-ui`.
