### ISSUE TITLE
permalink support for 'show all'

### ISSUE THREAD

**Issue by carpii** [Fyrd/caniuse#2920]
Sometimes its useful to refer people to caniuse.com, as a support site for users

In my case, I link to it to show users the entire range of browsers support which websockets

But this only links to the condensed view..
http://caniuse.com/#search=websocket

Given that my users aren't very technical, it would be very useful to be able to craft a permalink which automatically shows the 'View All' mode
The alternative is having to explain how to click the View All button, which is trivial but as we know most non-technical users just don't read stuff :-(

**Comment by Ugoku** [comment]
+1

**Comment by Fyrd** [comment]
Currently there's a bit of a hacky way to do this...
caniuse.com/#feat=websocket&agents=ie,edge,firefox,chrome,safari,opera,ios_saf,op_mini,android,bb,op_mob,and_chr,and_ff,ie_mob,and_uc,samsung
should get you what you want.

But that's not ideal of course.

**Comment by carpii** [comment]
@Fyrd thanks for the reply. 

A link like this would be good enough for my needs... but unfortunately it doesn't seem to jump to the 'websocket' feature, and just shows all features paginated

**Comment by Fyrd** [comment]
@carpii Ah yes, typo, should have been "websockets", not "websocket" in that URL. Have updated it now.

**Comment by carpii** [comment]
Thanks @Fyrd 

Really appreciate the help, but even the amended link still doesn't take me to the 'View All' mode
It now just redirects to http://caniuse.com/#feat=websockets (ie, condensed mode)

**Comment by Fyrd** [comment]
Yeah, the extra params will be removed from the URL once the page has loaded, but it should still show all the browsers...works for me anyway.

**Comment by carpii** [comment]
Ok I'll dig into it. Still just shows most recent browsers here. Maybe Chrome is doing its usual HTTP redirect caching or something :-)
Im seeing same on Fx and Opera though

**Comment by Fyrd** [comment]
Ooh, I see now, I misunderstood. The link will show any additional browsers not shown by default, but it won't show all the old versions hidden by default. Don't think I currently have a trick for that...

**Comment by carpii** [comment]
@Fyrd Ok no probs. Thanks for confirming its not currently possible anyway. Its always a bit of a pain trying to passing client side toggles via urls, especially when they're clean ones

Am I right in thinking the caniuse website is not open source? Its just the source JSON?

**Comment by Fyrd** [comment]
This is now possible by setting up a browser set (under Settings) and using the link the Import/Export button. That'll let you determine the exact browsers visible when you share. See https://caniuse.com/feed/159 for details and let me know if that works for you!
