### ISSUE TITLE
Resource Timing - Add missing features

### ISSUE THREAD

**Issue by gitgrimbo** [Fyrd/caniuse#2922]
https://w3c.github.io/resource-timing/

---

E.g. for Edge:

https://developer.microsoft.com/en-us/microsoft-edge/platform/catalog/?q=specName%3Aresource-timing

Missing

**Performance**
- onresourcetimingbufferfull

**PerformanceResourceTiming**
- decodedBodySize
- encodedBodySize
- nextHopProtocol
- secureConnectionStart
- toJSON
- transferSize
- workerStart

---

Chrome 54 supports at least these properties that Edge does not:
- decodedBodySize
- encodedBodySize
- secureConnectionStart
- transferSize
- workerStart

---

Firefox 46 supports at least these properties that Edge does not:
- decodedBodySize
- encodedBodySize
- nextHopProtocol
- secureConnectionStart
- transferSize

**Comment by Krinkle** [comment]
We can catalog this as "Resource Timing Level 2" (or `resource-timing-2`).

<https://www.w3.org/TR/resource-timing-2/>

**Comment by jtibble** [comment]
encodedBodySize, decodedBodySize, and transferSize are all available in Edge 76.0.172.0 (canary build) on OSX

**Comment by alexkoffler** [comment]
+1

**Comment by kenharker** [comment]
+1

**Comment by nick11703** [comment]
+1

**Comment by Fyrd** [comment]
All missing features should now be available via MDN BCD data. I've also updated https://caniuse.com/resource-timing to specify it refers to basic support and a note on where to find support for the newer APIs.
