### ISSUE TITLE
status abreviation

### ISSUE THREAD

**Issue by yukulele** [Fyrd/caniuse#2930]
On each feature there is abbreviation for status (REC, PR, CR, WD, LS, other, unoff) but there is no full description.

You should add `<attr>` tag with `title` or better, give directly full names.

**Comment by Fyrd** [comment]
Hmm, I thought I had this, guess not. Thanks for pointing it out.

**Comment by Fyrd** [comment]
Now using an `abbr` element with `title` for the spec status
