### ISSUE TITLE
Object.entries feature?

### ISSUE THREAD

**Issue by drakedevel** [Fyrd/caniuse#2936]
Apparently ES2017, MDN has some usability information: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries

**Comment by Schweinepriester** [comment]
<https://kangax.github.io/compat-table/es2016plus/#test-Object.entries>

**Comment by andyfry01** [comment]
+1

**Comment by sam-s4s** [comment]
+1

**Comment by metame** [comment]
+1

**Comment by nfanta** [comment]
+1

**Comment by kigiri** [comment]
+1

**Comment by lavenderlens** [comment]
Just stumbled across this issue, seems like the two-year anniversary of last comment is coming up soon, I know it's a complicated feature returning two arrays / a 2D array, but enough people must be using it by now to merit including? Almost hesitant to comment and love caniuse.

**Comment by ChrisBrownie55** [comment]
Definitely should be included by now, it's a very useful feature and it would be nice to know that I'm not about to break my code on a bunch of browsers before I use it.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=object-entries
