### ISSUE TITLE
apple-touch-icon

### ISSUE THREAD

**Issue by chr-bakk** [Fyrd/caniuse#2938]
Hopefully other browsers and web standards also pick up this trend, but I guess it won't be called apple :p

**Comment by Schweinepriester** [comment]
Maybe dup of #1304, thus covered http://caniuse.com/#feat=link-icon-svg (see note 3)?

**Comment by Fyrd** [comment]
Hmm, a closer look would reveal that #1304 actually covered both SVG icons as well as the "bookmark" icon, and only one of those is covered by `link-icon-svg`. So will leave this open.

**Comment by Schweinepriester** [comment]
Only 5 years later:
Definitely a duplicate of #1381 though :D

As a note to myself, `apple-touch-icon` is still relevant in 2021: <https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs>
