### ISSUE TITLE
Optimized All display

### ISSUE THREAD

**Issue by PRR24** [Fyrd/caniuse#2943]
As more and more browser versions become available, the screen displaying all browser versions is pretty full.
I would recommend to implement smart collapse of "all" browser versions, only showing version that have any change in support.
For example: search "calc" and browser "Chrome" would show:
4 - not supported
19 - supported with prefix webkit
26 - supported
The blocks could optionally show also ending number like 4-18, 19-25, 26-57, release date of smallest version and total usage % of the whole block.

I hope you got the idea.

**Comment by Fyrd** [comment]
Something very close to this idea has now been implemented in the "Show all" view. Thank you!
