### ISSUE TITLE
IndexedDB and Private Browsing Mode

### ISSUE THREAD

**Issue by indolering** [Fyrd/caniuse#2944]
IndexedDB is available in private/incognito mode in both Chrome and (soon) Firefox.  I would like to indicate the lack of support in older versions as well as Edge and Safari.

I personally would prefer to switch everything to partial support along with a note tag.  Is this the preferred way to go or should I just add a note tag?  I'm also worried about adding a note tag to virtually every browser/version combo....

**Comment by jimmywarting** [comment]
#2505

**Comment by indolering** [comment]
Closing as dupe.
