### ISSUE TITLE
Color input, Safari

### ISSUE THREAD

**Issue by JosefWN** [Fyrd/caniuse#2953]
Safari 10+ is listed as supporting color input, but when I'm testing in my own browser it doesn't.

**Comment by devoto13** [comment]
Doesn't work for me either. [MDN says](https://developer.mozilla.org/en/docs/Web/HTML/Element/input#Browser_compatibility) that Safari doesn't support it either.

**Comment by jhpratt** [comment]
I just submitted a pull request updating this, as I have had the same experience. I marked Safari TP as unknown.

**Comment by devoto13** [comment]
@Puffton @Fyrd It was [fixed](http://caniuse.com/#feat=input-color). So this issue can be closed. I've tested and it works in Safari TP.
