### ISSUE TITLE
Add nextElementSibling

### ISSUE THREAD

**Issue by jarcodallo** [Fyrd/caniuse#2956]
Example: el.nextElementSibling

**Comment by anikets** [comment]
For reference: https://developer.mozilla.org/en-US/docs/Web/API/NonDocumentTypeChildNode/nextElementSibling

**Comment by mikekavouras** [comment]
ping

**Comment by cvrebert** [comment]
Mike: Pinging doesn't do anything. You can comment "+1" to vote for the request.

**Comment by cvrebert** [comment]
+1

**Comment by mikekavouras** [comment]
+1

**Comment by andrewmu** [comment]
+1

**Comment by SimBioT1954** [comment]
+1

**Comment by shezzor** [comment]
+1

**Comment by mik-laj** [comment]
+1

**Comment by Snowbell92** [comment]
+1

**Comment by friederjanmoerman** [comment]
+1

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_nondocumenttypechildnode_nextelementsibling
