### ISSUE TITLE
ex unit

### ISSUE THREAD

**Issue by cvrebert** [Fyrd/caniuse#2968]
* https://drafts.csswg.org/css-values/#ex
* https://developer.mozilla.org/en-US/docs/Web/CSS/length#Browser_compatibility

Probably supported "everywhere", in which case a search result would be nice.

**Comment by Schweinepriester** [comment]
+1

**Comment by lpd-au** [comment]
+1

**Comment by shadaxv** [comment]
+1

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-css_types_length_ex
