### ISSUE TITLE
Encoding API compatibility table

### ISSUE THREAD

**Issue by artwis** [Fyrd/caniuse#2974]
https://encoding.spec.whatwg.org/

Current browser compatibility tables:
https://developer.mozilla.org/pl/docs/Web/API/TextDecoder#Browser_compatibility

**Comment by cvrebert** [comment]
There's already an entry for that:
http://caniuse.com/#feat=textencoder

**Comment by jimmywarting** [comment]
Well, can we add a new one for `TextEncoderStream` and `TextDecoderStream`?

**Comment by Fyrd** [comment]
Available at http://caniuse.com/#feat=textencoder
and also:
https://caniuse.com/#feat=mdn-api_textencoderstream
https://caniuse.com/#feat=mdn-api_textdecoderstream
