### ISSUE TITLE
Update link to Exponention operator

### ISSUE THREAD

**Issue by mikaturk** [Fyrd/caniuse#2985]
[Exponention operator](http://caniuse.com/#search=Exponentiation%20operator) has a link that doesn't go to the proper row, the link is now: http://kangax.github.io/compat-table/es7/#test-Exponentiation_operator
which should be: http://kangax.github.io/compat-table/es2016plus/#test-exponentiation_(**)_operator

**Comment by Schweinepriester** [comment]
As <https://caniuse.com/?search=Exponentiation> now only shows two entries from MDN and a search result for ES2016

- https://caniuse.com/mdn-javascript_operators_exponentiation
- https://caniuse.com/mdn-javascript_operators_exponentiation_assignment
- https://caniuse.com/sr_es7

i.e. the link isn't present anymore, I believe this issue can be closed :P

**Comment by mikaturk** [comment]
I see, the current links all look good, closed :smile:
