### ISSUE TITLE
Add support for the WebUSB API

### ISSUE THREAD

**Issue by aran112000** [Fyrd/caniuse#2987]
https://www.chromestatus.com/feature/5651917954875392

**Comment by larsgk** [comment]
As Chrome has WebUSB working for Linux, Mac and (with a little tweaking for now - but soon fixed) Windows and seeing how useful and stable it is, I'd really love to see it get the attention it deserves on caniuse.com

**Comment by cvrebert** [comment]
* https://webkit.org/status/#feature-webusb ("Not Considering")

**Comment by Keavon** [comment]
This is already out in Chrome for Android and it will be arriving in full release in Chrome 61. It currently works behind a flag. This should definitely have a page.

**Comment by Lenon95x** [comment]
WebUSB is released in Chrome 61.

**Comment by awebdeveloper** [comment]
Include webusb 

https://blog.chromium.org/2017/08/chrome-61-beta-javascript-modules.html

https://developers.google.com/web/updates/2016/03/access-usb-devices-on-the-web

https://www.chromestatus.com/features/5651917954875392

https://webkit.org/status/#feature-webusb

**Comment by larsgk** [comment]
...and it also works on mobile - quite cool and opens a huge range of possibilities for the industry
https://twitter.com/denladeside/status/905882314835668992

**Comment by reillyeon** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=webusb
