### ISSUE TITLE
Add `isContentEditable` as an alias to `contenteditable`

### ISSUE THREAD

**Issue by xovel** [Fyrd/caniuse#2988]
- <https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/isContentEditable>
- <https://html.spec.whatwg.org/multipage/interaction.html#dom-iscontenteditable>
- <http://caniuse.com/#search=designmode>
- <http://caniuse.com/#feat=contenteditable>

**Comment by Fyrd** [comment]
Added.
