### ISSUE TITLE
Add support for 'inert' HTML 5.1 attribute

### ISSUE THREAD

**Issue by CharlieHawker** [Fyrd/caniuse#2991]
https://www.w3.org/TR/html/editing.html#inert-subtrees

**Comment by Schweinepriester** [comment]
> This section does not define or create any content attribute named "inert". This section merely defines an abstract concept of inertness.

**Comment by cvrebert** [comment]
Although if you want such a feature, you can argue in favor of it at https://github.com/whatwg/html/pull/1474
