### ISSUE TITLE
Misleading info about an IE10 flexbox bug?

### ISSUE THREAD

**Issue by olach** [Fyrd/caniuse#2992]
On the Flexbox bug list there is this description:

> In IE 10, setting `-ms-flex-flow: row wrap` will not wrap unless `display: inline-block` is set on child elements.

I can't find any info about this specifically to back this statement up. But I did find out that [IE10 does not apply flexbox on inline elements](http://stackoverflow.com/questions/22008135/internet-explorer-10-does-not-apply-flexbox-on-inline-elements).

The bug is also documented [on this page which says that both IE10 and IE11 is affected](https://github.com/philipwalton/flexbugs#12-inline-elements-are-not-treated-as-flex-items).

It seems that if a child element to a flexbox container is of the type ´inline´, it will not work at all in IE10-11. It's not only the wrap feature that doesn't work. Any flexbox feature won't work. The child element must be converted to a ´block´or ´inline-block´ element for flexbox to start working.

So I suggest that this description must be rewritten.

Suggestion for an updated bug description:

> IE10 and IE11 does not treat inline elements as flex items. [See description and workaround](https://github.com/philipwalton/flexbugs#12-inline-elements-are-not-treated-as-flex-items).

Or maybe a long description (copied from the Flexbugs repo):

> Inline elements, including `::before` and `::after` pseudo-elements, are not treated as flex items in IE 10. IE 11 fixed this bug with regular inline element, but it still affects the `::before` and `::after` pseudo-elements. [See description and workaround](https://github.com/philipwalton/flexbugs#12-inline-elements-are-not-treated-as-flex-items).

**Comment by cvrebert** [comment]
Maybe just delete that entry, since there's already a link to Flexbugs in the Flexbox entry?

**Comment by olach** [comment]
Yes maybe that is even better. It's ok for me to delete that entry. And even better to also move the entry with the link to Flexbugs to the top of the list.
