### ISSUE TITLE
How is a feature that is known for some browsers not known for others?

### ISSUE THREAD

**Issue by paulehoffman** [Fyrd/caniuse#2997]
Greetings. This may be more of a newbie question than an actual issue. I wanted to know if `<link rel="dns-prefetch">` is supported on all browsers. As of 2016-11-21, http://caniuse.com/#search=dns-prefetch shows that it is implemented on some browsers, not implemented on one, and unknown for iOS Safari and Android Browser.

If all this testing is automated, how is this feature unknown on those two browsers?

**Comment by cvrebert** [comment]
To my knowledge, the testing isn't automated.

**Comment by paulehoffman** [comment]
Ahhh, my mistake. On the FAQ, I saw "I use a hand-crafted test suite to test features, which tests for basic support of each feature" and I assumed that meant automated.
