### ISSUE TITLE
CSS display: flow-root

### ISSUE THREAD

**Issue by jhpratt** [Fyrd/caniuse#2999]
Spec (editor's draft): [link](https://drafts.csswg.org/css-display-3/#valdef-display-flow-root)

AFAIK not yet implemented by any browser vendor.

**Comment by jhpratt** [comment]
Added in #3069.

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=flow-root

**Comment by jhpratt** [comment]
Awesome!
