### ISSUE TITLE
ResizeObserver

### ISSUE THREAD

**Issue by cvrebert** [Fyrd/caniuse#3006]
* Spec Draft: https://github.com/WICG/ResizeObserver
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=612962
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1272409
* Article: https://developers.google.com/web/updates/2016/10/resizeobserver

**Comment by ausi** [comment]
+1
I created pull request #3500 for this feature.

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=resizeobserver
