### ISSUE TITLE
Pointer: coarse

### ISSUE THREAD

**Issue by iGadget73** [Fyrd/caniuse#3007]
Useful for detecting touch devices.
Example: 

`@media (pointer: coarse) { … }`

**Comment by cvrebert** [comment]
Already covered by http://caniuse.com/#feat=css-media-interaction

**Comment by Schweinepriester** [comment]
⇒ Add keyword? :)

**Comment by iGadget73** [comment]
Yes, adding a keyword, because that is what you do when you type in something in the search field; searching for keywords.

And how should anybody know that its covered by the css media interaction? It's not mentioned.

**Comment by cvrebert** [comment]
`coarse` is not mentioned, but `pointer` is:

> [...] This includes the **pointer**, any-pointer, hover, and any-hover media features.

**Comment by iGadget73** [comment]
> coarse is not mentioned, but pointer is

Thats why it should be in there. Even if I search for pointer, it doesn't appear.

**Comment by Schweinepriester** [comment]
Technically it does appear when searching for 'pointer', just not on top (which is fine imho): <http://caniuse.com/#search=pointer>

But it probably should also be found when searching for 'css pointer', which it currently does not: <http://caniuse.com/#search=css%20pointer>

**Comment by Fyrd** [comment]
Have added keywords for `coarse` & `fine` as well as made `css pointer` work.
