### ISSUE TITLE
Switch hosting to HTTPS

### ISSUE THREAD

**Issue by lgarron** [Fyrd/caniuse#3024]
https://hstspreload.org/ has several external links, and http://caniuse.com/#feat=stricttransportsecurity is the only one that doesn't support HTTPS.
(In fact, because I disable Javascript on HTTP, the page doesn't even show me the data.)

caniuse.com is a great canonical reference for browser compatibility, but I'm very reluctant to link to it at the moment. Is there any chance the server could be updated to use a valid HTTPS certificate?
Projects like [Let's Encrypt](https://letsencrypt.org/) can make it free to get such a certificate.

**Comment by Schweinepriester** [comment]
+1000, though duplicate of #885.

**Comment by lgarron** [comment]
Oop, I searched but didn't find an existing issue.
