### ISSUE TITLE
Missing a check for msConvertURL() on DragEvent

### ISSUE THREAD

**Issue by jayarjo** [Fyrd/caniuse#3047]
[msConvertURL](https://msdn.microsoft.com/en-us/library/dn254951(v=vs.85).aspx) is kind of a very handy method from IE11. But I'm not sure which IEs support it and if it is still supported in Microsoft Edge.

**Comment by mattwojo** [comment]
*Just a note that this is still supported in Microsoft Edge. We've been moving all the docs over to MDN, so you can find the ref here now: https://developer.mozilla.org/en-US/docs/Web/API/msConvertURL

**Comment by GPHemsley** [comment]
The MDN link now redirects here and makes no mention of `msConvertURL()`:
https://developer.mozilla.org/en-US/docs/Web/API/Event

The docs on `DragEvent` also do not mention it:
https://developer.mozilla.org/en-US/docs/Web/API/DragEvent

Nor do the docs on `Event.srcElement`, `Event.target`, or `DataTransfer.files`:
https://developer.mozilla.org/en-US/docs/Web/API/Event/srcElement
https://developer.mozilla.org/en-US/docs/Web/API/Event/target
https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/files

There also does not appear to be any effort to document support in the MDN browser compat data.

**Comment by Fyrd** [comment]
Agree there's no need to include this at this point.
