### ISSUE TITLE
Edge 12 and 14 release date incorrect

### ISSUE THREAD

**Issue by Studio384** [Fyrd/caniuse#3050]
The release dates for both Edge 12 and Edge 14 are incorrect:

Edge 12 was released on 29 July 2015, not 30 March 2015
Edge 14 was released on 2 August 2016, not 4 August 2016

**Comment by cvrebert** [comment]
Link to source of release date data?

**Comment by Studio384** [comment]
The releasedates for the respective Windows versions:
Windows 10 with Edge 12 was released on 29 July 2015
Windows 10 Anniversary Update with Edge 14 on 2 August 2016

https://en.wikipedia.org/wiki/Windows_10
https://en.wikipedia.org/wiki/Microsoft_Edge#Release_history

**Comment by Fyrd** [comment]
Fixed! Thanks for providing the sources. Not sure where I got the dates from there or why they were different...
