### ISSUE TITLE
Please add the CSS logical properties spec

### ISSUE THREAD

**Issue by cbiesinger** [Fyrd/caniuse#3051]
Please add https://drafts.csswg.org/css-logical-props/, thanks!

**Comment by cvrebert** [comment]
Already present: http://caniuse.com/#feat=css-logical-props

**Comment by cbiesinger** [comment]
But http://caniuse.com/min-block-size or http://caniuse.com/block-size doesn't work. Shouldn't it?

(By the way -- Firefox supports the properties unprefixed, so I think that's wrong on the site)
