### ISSUE TITLE
Object.values and Object.entries

### ISSUE THREAD

**Issue by godmar** [Fyrd/caniuse#3053]
I just failed a create-react-app on Chrome 51 with "Object.values" undefined. It was added somewhere along the 51->55 release.  

[Chrome Platform Status](https://www.chromestatus.com/feature/5710160244768768)

**Comment by cvrebert** [comment]
Corresponding Kangax entries:
* http://kangax.github.io/compat-table/es2016plus/#test-Object.values
* http://kangax.github.io/compat-table/es2016plus/#test-Object.entries

**Comment by KaelWD** [comment]
+1

**Comment by catcher-in-the-try** [comment]
Thanks for adding `Object.values`, how about `Object.entries`?

**Comment by Fyrd** [comment]
Object.values is now available at https://caniuse.com/#feat=object-values, for Object.entries please vote at #2936
