### ISSUE TITLE
Add form reportValidity() method

### ISSUE THREAD

**Issue by aeischeid** [Fyrd/caniuse#3056]
Learned about this API today, but not up to date docs at https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reportValidity and doesn't seem to be covered by http://caniuse.com/#feat=form-validation

[demo here](http://codepen.io/chriscoyier/pen/mOzgBZ/). Appears to work in desktop Chorme and Firefox.

**Comment by Schweinepriester** [comment]
I'd say this should be covered by #1068?

**Comment by Fyrd** [comment]
Yup, covered by #1068. I have also updated the title there for clarity.
