### ISSUE TITLE
Add support for "draggable" attribute

### ISSUE THREAD

**Issue by filipefmelo** [Fyrd/caniuse#3059]
Hi, I was looking for help regarding the "draggable" attribute but did not find it in the website.
It can be found here: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable

**Comment by Schweinepriester** [comment]
Covered by http://caniuse.com/#feat=dragndrop and/or duplicate of #1807 or #2673?

**Comment by Fyrd** [comment]
Yeah, I'll say duplicate of #1807, probably warrants at least investigation of the attribute.
