### ISSUE TITLE
Please add: x3dom (inline 3D objects for HTML)

### ISSUE THREAD

**Issue by peter-conalgo** [Fyrd/caniuse#3067]
Love your site, and it's the first place I come when I find new stuff like this:

<https://www.x3dom.org/>

But X3DOM isn't in your list. I have no idea myself what it's uptake is like.

**Comment by peter-conalgo** [comment]
Hmm... just notice their own page with browser support summary:

[browser support](https://www.x3dom.org/contact/)

**Comment by Schweinepriester** [comment]
I'd say 'Needs search result', see e.g. <http://caniuse.com/#search=angularjs>:

> **AngularJS**
This framework is not part of any web browser, so support is not listed here.

**Comment by Fyrd** [comment]
Added as search result at https://caniuse.com/#search=x3dom
