### ISSUE TITLE
Ambiguity prefix for text-stroke

### ISSUE THREAD

**Issue by BramVanroy** [Fyrd/caniuse#3072]
In the notes of the [can I use page](http://caniuse.com/#feat=text-stroke), it is said that 

> Firefox & Edge specifically support the -webkit-text-stroke property without having support with their own prefix.

However, when you hover Edge or Firefox's supported version numbers you'll see that it says 

> Supported with prefix `-ms-` (or `-moz-`)

I don't know which of these is the correct statement (I'm guessing the first one) but as it is written now it is contradictory.

**Comment by jhpratt** [comment]
My guess is that the second part you mentioned is automatically generated for each one, whereas the first part is specific, and the one you'd want to use.

**Comment by BramVanroy** [comment]
@jhpratt What do you mean by 'automatically generated'? Generated by what?

**Comment by jhpratt** [comment]
It's likely a generic mouseover that is shown any time `prefix` is set.

**Comment by BramVanroy** [comment]
@jhpratt I thought so too, but it's very confusing and should be avoided. Or at least it should be possible to override it when a foot note claims otherwise.

**Comment by Fyrd** [comment]
Yeah, I agree this should be fixed to avoid confusion. Originally there weren't any browsers that supported a different prefix so the current solution just worked...

**Comment by Fyrd** [comment]
Issue has now been fixed, prefix will show up as "webkit".
