### ISSUE TITLE
mouseover

### ISSUE THREAD

**Issue by bappygolder** [Fyrd/caniuse#3074]
The [`mouseover`](https://developer.mozilla.org/en-US/docs/Web/Events/mouseover) event is not part of the library. It'll be great if you added it.

**Comment by jhpratt** [comment]
Are there any browsers that don't support this?

**Comment by bappygolder** [comment]
Well I wasn't sure of that for a problem I was trying to fix. But thankfully it's all resolved now and wasn't anything to do with the `mouseover`. 

It seems `mouseover` has strong browser support so feel free to leave this out.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_element_mouseover_event
