### ISSUE TITLE
Number.prototype.toLocaleString() has no data

### ISSUE THREAD

**Issue by danielthegray** [Fyrd/caniuse#3085]
Number.prototype.toLocaleString() information should be included on the site.

**Comment by tommcc** [comment]
+1

**Comment by jgpATs2w** [comment]
+1

**Comment by tristanbes** [comment]
+1

**Comment by aschumahua** [comment]
+1

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_builtins_number_tolocalestring
