### ISSUE TITLE
Headings on small screens

### ISSUE THREAD

**Issue by thany** [Fyrd/caniuse#3087]
As you can see in the screenshot below, the headings are a tad mixed up because of width restrictions:
![tmp_23098-20170104_085511-4509067](https://cloud.githubusercontent.com/assets/152227/21635041/997b3a0e-d25b-11e6-8fd7-463329b69063.png)
This is Firefox on Android, and I'm sure other browsers will show a similar view.

Perhaps it's a good idea to rotate the headings, so that they're still readable, but without them overlapping.

**Comment by Fyrd** [comment]
Yeah, they used to be rotated...recent change broke it. Thanks for pointing this out.

**Comment by Fyrd** [comment]
This got fixed some time ago, there's a min-width set now with the tables being scrollable.
