### ISSUE TITLE
video js filesystem api is not working in android phone

### ISSUE THREAD

**Issue by Abdurraheem** [Fyrd/caniuse#3088]
<video id=example-video width=600 height=300 class="video-js vjs-default-skin" controls>
  <source
     src="api/drm/index.m3u8"
     type="application/x-mpegURL">
</video>
<script src="video.js"></script>
<script src="videojs-contrib-hls.min.js"></script>
<script>
var player = videojs('example-video');
player.play();
</script>

**Comment by Abdurraheem** [comment]
http://videojs.github.io/videojs-contrib-hls/
this demo page is not working in android 's chrome

 is it some support issue with vidoe js at android chrome browsers after resfreshing page in chrome-android its not working..
sorry for bad english

Thanks in advance

**Comment by Ugoku** [comment]
Works fine on my Android (Samsung Galaxy S3 Neo, Android 4.4.2, tested in both the default Samsung browser and in Chrome 55)

**Comment by Fyrd** [comment]
Sounds like an issue with video.js if anything. If it's a known issue for video support please be more specific and it it can be added as such.
