### ISSUE TITLE
Inert property for objects that should currently not be focused

### ISSUE THREAD

**Issue by IchordeDionysos** [Fyrd/caniuse#3090]
There is an Inert polyfill with all the information: https://github.com/GoogleChrome/inert-polyfill

**Comment by cvrebert** [comment]
The feature doesn't yet have a specification and hasn't been implemented in any browser.
See #2991.

**Comment by robdodson** [comment]
Quick update on this. We (Chrome) are now shipping `inert` behind a flag. We're taking the standard through the web platform incubation group process over at https://github.com/WICG/inert

**Comment by Malvoz** [comment]
+1

**Comment by Malvoz** [comment]
Tracking bugs:
- https://www.chromestatus.com/feature/5703266176335872
- https://bugs.webkit.org/show_bug.cgi?id=165279
- https://bugzilla.mozilla.org/show_bug.cgi?id=921504
- https://developer.microsoft.com/en-us/microsoft-edge/platform/status/inertattribute/

**Comment by ledenis** [comment]
+1
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=921504
* Webkit: https://bugs.webkit.org/show_bug.cgi?id=165279

**Comment by Fyrd** [comment]
Available at https://caniuse.com/mdn-api_htmlelement_inert
