### ISSUE TITLE
Interested in Collaborating

### ISSUE THREAD

**Issue by amilajack** [Fyrd/caniuse#3091]
Hi @Fyrd. I'm interested in serving as a long term collaborator for this project. There seems like a lot of work needed to keep this project up to date. Also recently I've been working on an [eslint plugin](https://github.com/amilajack/eslint-plugin-compat) that uses caniuse extensively. Would be great if you could point me in the right direction.

**Comment by Fyrd** [comment]
Hi Amila! Sounds great; you're definitely right that the caniuse project needs all the help it can get. :)

Right now I believe the best way you can help is by either adding highly voted features from http://caniuse.com/issue-list/ and/or reviewing submitted features from this list:
https://github.com/Fyrd/caniuse/pulls?utf8=%E2%9C%93&q=is%3Apr%20label%3A%22Data%20pending%20review%22%20 (ideally in order of votes received from the afore-mentioned [issue list](http://caniuse.com/issue-list/), though it takes a little work to figure that out)

See the [CONTRIBUTING](https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md) docs for details on how to add features.

If browser support testing itself isn't your thing, another thing you can do is simply browse caniuse.com and look for information that may be out of date, text that may be better written, etc. Then just submit a PR on any of that. There's probably some other things too, I'll add them to this issue if I can think of 'em.

Hope that helps, if you have any questions just let me know! Thanks again for your willingness to help out.

**Comment by Fyrd** [comment]
Closing this issue as per the info provided in my last comment.
