### ISSUE TITLE
Browser Support for Decimal Places

### ISSUE THREAD

**Issue by Mr-Alexander** [Fyrd/caniuse#3095]
Hello,

What is the browser support for decimal places?

Would be great to have as a reference.

Mr Alexader

**Comment by cvrebert** [comment]
> What is the browser support for decimal places?

In what context? `<input type="number">`, or CSS number values, or ...?

**Comment by Mr-Alexander** [comment]
CSS number values. For font-size, width, height, position (top,right,bottom,left), etc.

**Comment by Fyrd** [comment]
All browsers support decimal places in those properties, perhaps your question is mostly about sub pixel rendering?

**Comment by Fyrd** [comment]
Closing this issue, if support is mixed for a particular property a new issue can be opened.
