### ISSUE TITLE
Flex in Safari 10.x is massively broken

### ISSUE THREAD

**Issue by intellix** [Fyrd/caniuse#3098]
For the past few days I've been fighting issues with flex in Safari 10

flex-wrap works in 10.1 but not 10.0: http://codepen.io/intellix/pen/egpOqK
It struggles to calculate heights in both 10.0 and 10.1: http://codepen.io/intellix/pen/egNEJN

After spending a multitude of hours on issues with Flex in Safari this weekend, I'd go as far as to say it's only "Partially supported" although I'm not sure how that's defined here.

**Comment by Schweinepriester** [comment]
Are those maybe covered by <https://github.com/philipwalton/flexbugs>?

**Comment by inooid** [comment]
@intellix It is broken because you're using the short-hand syntax for `flex-grow`. In safari you either have to use the full syntax: `flex: 1 1 auto;` or specifically set `flex-grow: 1`.

**Comment by Zefling** [comment]
`flex-direction:column`  is also broken before Safari 11.0. 
On my project, all `flex-direction:column`  are replace by `display:block` only for Safari  (but we lost `order`).

**Comment by BenjaminHoegh** [comment]
Try to test the browsers support of the CSS3 Flexbox here: http://css3test.com/

**Comment by Fyrd** [comment]
Since this info mostly refers to older versions of Safari and is covered by https://github.com/philipwalton/flexbugs I'm closing this issue.
