### ISSUE TITLE
Permalinks to no-JS version

### ISSUE THREAD

**Issue by tigt** [Fyrd/caniuse#3106]
Right now, each chart's `#` permalink uses the hash, like this: `http://caniuse.com/#feat=svg-html`

I noticed you can get a no-JS version of each chart which progressively enhances into the full experience if you remove the `#feat=`, so when linking to CNI I do that manually.

It would be cool if the permalinks pointed that way by default, like so: `http://caniuse.com/svg-html`

**Comment by Fyrd** [comment]
This is now the behavior on the beta site (https://beta.caniuse.com), e.g. https://beta.caniuse.com/svg-html (works with & without JS)
Will close this issue once it's on the main site.

**Comment by Fyrd** [comment]
This is now available on the main site.
