### ISSUE TITLE
Support for iOS 10.2 Not Listed

### ISSUE THREAD

**Issue by zsteiner** [Fyrd/caniuse#3117]
Upon importing my site's data, I noticed a huge drop of audience that support for a few properties (~90% to ~40%). After a few moments of panic, I realized that iOS 10.2, which roughly 38% of our audience runs, is not listed and not imported from Google Analytics. Are there plans to add 10.2 support so that current iOS users are captured in caniuse data?

**Comment by Fyrd** [comment]
Thanks for reporting this, should be fixed now.

**Comment by zsteiner** [comment]
Confirmed it is fixed! Thanks for the quick turn around!
