### ISSUE TITLE
Android Webview Not Recognized

### ISSUE THREAD

**Issue by zsteiner** [Fyrd/caniuse#3119]
Did an import from Google analytics and about 12% of traffic was untracked. Noticed that the vast majority are Android Webview browsers of various versions (Android Webview 55.0.2883.91 alone accounting for 7% of our traffic). Should Android Webview fit into Android Browser or Chrome for Android or neither?

**Comment by Schweinepriester** [comment]
Afaik Android Browser.

**Comment by Fyrd** [comment]
Last I checked the Android WebView user agent string is identical to that of Chrome of Android. As a result it's tracked as such.

**Comment by jangarcia** [comment]
I have noticed the same doing imports of our GA data: For the last few months up to 9% of our traffic didn't get categorized. The list of unrecognized browsers consists nearly entirely of entries labeled as "Android Webview 56.0.2924.87", etc., including many entries with the same label.

**Comment by zsteiner** [comment]
Any update on this? Still almost 10% of our traffic isn't being inclduded from GA, which really skews the percentages displayed. The list is entirely multiple versions of Android Webview. Interestingly, data from October 2016 is almost fully included. Something changed in November 2016.

Last 30 days (Jun 20 to Jul 20, 2017) 
<img width="645" alt="screen shot 2017-07-20 at 8 56 21 am" src="https://user-images.githubusercontent.com/4006336/28418363-62fbedde-6d29-11e7-86b8-f4d47f39de92.png">

October 2016: 
<img width="651" alt="screen shot 2017-07-20 at 8 57 15 am" src="https://user-images.githubusercontent.com/4006336/28418381-77db127a-6d29-11e7-90bb-1a1356b1bac5.png">

**Comment by Fyrd** [comment]
Just spent some time on this, should be working as expected now!

**Comment by zsteiner** [comment]
Works great. Thank you so much!
