### ISSUE TITLE
Menu element "well-supported in all browsers effectively"

### ISSUE THREAD

**Issue by rudijuri** [Fyrd/caniuse#3121]
Hi,
you consider `menu` element "well-supported in all browsers effectively" here: http://caniuse.com/#search=HTML4%20elements%20(well-supported%20subset
and "very-bad" here:
http://caniuse.com/#feat=menu

I asked (with no luck) why on stackoverflow (http://stackoverflow.com/q/41741360/7208844) and someone recommended me to write here.

Thanks.

**Comment by Ugoku** [comment]
> HTML 4 supported a `<menu>` element but it had a different purpose than the HTML 5.1 `<menu>` element. In HTML 4, the `<menu>` element was designed to be used for single column menu lists. The `<menu>` element was deprecated in HTML 4 (although it has returned, with a different purpose).

[Source](http://www.quackit.com/html/tags/html_menu_tag.cfm)

So the menu tag from your first link is a different menu tag than in your second link.

**Comment by rudijuri** [comment]
@Ugoku, many thanks
