### ISSUE TITLE
Add Cache Storage API / Cache API

### ISSUE THREAD

**Issue by addyosmani** [Fyrd/caniuse#3122]
> The Cache API allow authors to fully and conveniently manage their content caches for offline use. An origin can have multiple, named Cache objects which are accessible via workers and document scripts. 

As of Chrome 43 (and Opera 30) this has been available globally and outside of the Service Worker context (meaning you can use it standalone). The feature was implemented back in Firefox 39, but IIRC not yet exposed to the global context. Afaik, it's in development for Edge.

I might suggest treating it as a top-level storage item in a similar way to how IDB is treated today: http://caniuse.com/#feat=indexeddb. Over on Chrome our storage team are recommending developers use the Cache API for URL addressable resources and IDB for everything else atm. Can has? :)

Docs + samples:
https://googlechrome.github.io/samples/service-worker/window-caches/index.html
https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage
https://developer.mozilla.org/en-US/docs/Web/API/Cache

**Comment by Schweinepriester** [comment]
+1

<https://developer.mozilla.org/en-US/Firefox/Releases/55>:

> - The StorageManager.persist() and StorageManager.persisted() methods of the Storage API have been implemented and exposed to Window contexts
> - The Storage API is now available only to secure contexts

**Comment by rivsc** [comment]
+1 :)

**Comment by jimmywarting** [comment]
[cache-polyfill](https://www.npmjs.com/package/cache-polyfill)

**Comment by iandunn** [comment]
[Looks like it's been added](https://caniuse.com/#search=cachestorage), should this be closed?

**Comment by Fyrd** [comment]
Yup, available at https://caniuse.com/#feat=mdn-api_cachestorage
