### ISSUE TITLE
ClassList and ECMAScript 5 strict mode and other fatures in Opera Mini

### ISSUE THREAD

**Issue by Yaffle** [Fyrd/caniuse#3123]
It seems, Opera Mini supports some features:

- classList (DOMTokenList)
- input placeholder attribute
- progress element
- meter element
- Typed Arrays
- matchmedia
- ECMAScript 5 Strict Mode

Doesn't it?

**Comment by Fyrd** [comment]
Well spotted! Just tested each of those and you're correct. Not sure how these fell through the cracks. Data has been updated. Thanks much!

**Comment by Yaffle** [comment]
Thank you!
