### ISSUE TITLE
Can Google Analytics integration be supported with a paid account?

### ISSUE THREAD

**Issue by NewAlexandria** [Fyrd/caniuse#3132]
caniuse is a great resource.  It would be even more awesome if we could get a paid account that integrates securely with our GA account.  I understand that the data is all CC licensed, so we could do that on our own — but I'd really rather pay someone who focuses on services like these.

It looks like this feature was supported once.  Why was it dropped?  Can we do a paid beta?

**Comment by Fyrd** [comment]
The feature's still there (for free), just look under Settings.
