### ISSUE TITLE
Safari 10.1 / iOS 10.3

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#3133]
<https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_1.html>

Most likely very much like the latest TP or a version not too far behind.
If anyone has confirmation for that or can show the delta between TP and 10.1 please do :)

**Comment by Fyrd** [comment]
10.1 has been added. Currently just copied over from TP, curious about that delta too! Seems likely a few things won't make it but unable to test just yet.

**Comment by cvrebert** [comment]
Safari 11.0: https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Safari_11_0/Safari_11_0.html

**Comment by Fyrd** [comment]
Oh ha I never closed this one. Well iOS 10.3, iOS 11 and Safari 11 have all now been added.
