### ISSUE TITLE
CSS4 - Specifying profiled colors: the color() function

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#3134]
Found no data or issue when searching for this.
Afaik this differs from #2864, which primarily requests `color-mod()`.

This is intended for 'CSS Color Module Level 4' `color()`, allowing to specify profiled colors.

Spec: <https://drafts.csswg.org/css-color/#color-function>

Example:
```css
em {
  color: color(p3 50 250 100);
}
```

Shamelessly stolen from <https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_1.html>

Safari 10.1 (& TP) / iOS 10.3 support this, apparently.

**Comment by alexguichet** [comment]
+1

This is supported in Safari out of the box (not hidden behind development switches) and is, therefore, able to be used on the web. It's real and represents new wide-gamut color functionality on the web not previously available.

As one notable example, Panic shared stories using this in this tweet thread: https://twitter.com/panic/status/1106633444157607936. It's also in use on their marketing websites, like https://panic.com/nova/ and https://play.date. 

I've made a color picker for the P3 color space, at https://p3colorpicker.cool, as another example of it in-use, with the ultimate goal of increasing wide-gamut color adoption.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=css-color-function
