### ISSUE TITLE
display: flow-root 

### ISSUE THREAD

**Issue by fabbiatti** [Fyrd/caniuse#3138]
Want to know browser support for the new display property "flow-root".
https://drafts.csswg.org/css-display/#valdef-display-flow-root

**Comment by jhpratt** [comment]
I did this a couple weeks ago with an issue and PR. It's just pending data review.

**Comment by fabbiatti** [comment]
Great! Thanks!

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=flow-root
