### ISSUE TITLE
CSSKeyframesRule

### ISSUE THREAD

**Issue by Mensae** [Fyrd/caniuse#3139]
Could you please add support for the CSSKeyframesRule interface.

It describes an object representing a complete set of keyframes for a CSS animation, taken from [Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/API/CSSKeyframesRule)

spec - [W3C Working Draft](https://drafts.csswg.org/css-animations-1/#interface-csskeyframesrule)

Thanks!

**Comment by sn-sweet-stack** [comment]
+1

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_csskeyframesrule
