### ISSUE TITLE
animateMotion for SVG

### ISSUE THREAD

**Issue by infinitegarg** [Fyrd/caniuse#3141]
The current status of the animateMotion property of SVG is quite unknown.
( Ref - https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateMotion ).

I found a lag (not proper support) in firefox but works pretty well in Chrome, Safari, Android.
Looking for more browser compatibility information.

Thanks ! 😊

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-svg_elements_animatemotion
