### ISSUE TITLE
Analytics totals don't add up

### ISSUE THREAD

**Issue by bradkemper** [Fyrd/caniuse#3149]
The total percentage of support based on Google Analytics for a feature is not adding up from the amounts shown in the graph. For instance, for "rem (root em) units" support, the only partial support is from IE9-10. For a site I manage, it says 0.55% are using IE9, and 0.62% are using IE10 (totaling 1.17). But in the total support numbers, it says partial support is 1.22%. Where is the other 0.05% coming from?

This is maybe a tiny difference, but the green numbers (fully supported) seem off too, by a wider margin. By my math, the red (not supported) should only add up to 0.26%. Add that to 1.17 = 1.43. So the green number should be 98.57%, shouldn't it (100% - 1.43%)? Or something pretty close to that?But the total shown is 91.22%.

<img width="642" alt="pastedgraphic-2" src="https://cloud.githubusercontent.com/assets/10453818/22525922/22eb73d4-e87e-11e6-94fc-3d24aef82da4.png">

**Comment by Fyrd** [comment]
If you click on "Current aligned" then "Show all" you'll see there's a few more versions out there with no or partial support (specifically iOS Safari 5.1), perhaps that's where the missing % is?

Additionally, the numbers likely won't add up to 100% as there's some browsers not tracked on caniuse which are not accounted for. If you hover over the 92.44% the tooltip will mention the % unaccounted. Additionally after importing data it will show you the same percentage and which browsers are not accounted for.

**Comment by SebastianZ** [comment]
> Additionally, the numbers likely won't add up to 100% as there's some browsers not tracked on caniuse which are not accounted for. If you hover over the 92.44% the tooltip will mention the % unaccounted. Additionally after importing data it will show you the same percentage and which browsers are not accounted for.

I didn't realize until now, though instead of the tooltip you now have the option to select the source the percentage refers to, so to see the percentage relative to the tracked user agents you just have to select "all tracked" from the list.

Sebastian

**Comment by Fyrd** [comment]
Closing as per my last comment.
