### ISSUE TITLE
add hexadecimal RGBA notation (css hex with opacity)

### ISSUE THREAD

**Issue by Rhinni** [Fyrd/caniuse#3154]
https://drafts.csswg.org/css-color/#hex-notation

**Comment by ben-eb** [comment]
It's already listed: http://caniuse.com/#feat=css-rrggbbaa

😄

**Comment by Rhinni** [comment]
Ahh thanks, great!

**Comment by Fyrd** [comment]
Thanks to #3160 it'll now appear for a search for rgba too.
