### ISSUE TITLE
Can anyone help me understand the JSON data for different features?

### ISSUE THREAD

**Issue by 9itish** [Fyrd/caniuse#3155]
Let's say I am looking at the data for the [background-attachment](https://raw.githubusercontent.com/Fyrd/caniuse/master/features-json/background-attachment.json) property.
What do the following keys stand for : `ucprefix`, `parent`, `keywords`, `ie_id`, `chrome_id`, `firefox_id`, `webkit_id`, `shown`.  I understand the rest of the values but I am having a hard time understanding the significance of the keys I listed here. Can anyone please clear it up for me?

Thanks.

**Comment by ben-eb** [comment]
@9itish There's a complete list describing these at https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md.
