### ISSUE TITLE
Mapping keywords to Features

### ISSUE THREAD

**Issue by marquesarthur** [Fyrd/caniuse#3156]
I'm planning to use Can I Use in an undergrad course project and I am trying to understand how keywords are mapped to features.

For instance, if I query the keyword 'before' like this: http://caniuse.com/#search=before
I get 13 features. Then, if I query the keyword '::before' like this, I get only one feature, which is located in the json file: https://github.com/Fyrd/caniuse/blob/master/features-json/css-gencontent.json

Although, when I looked at the keywords in this specific json file, the before has no colons on it. 
How Can I Use was able to correctly map ::before to this specific feature?

I would appreciate if you could describe how the mapping was done in this specific scenarios.
All the appropriate acknowledgement will be provided in the course project.

Thanks in advance,
Arthur

ps.: I looked at the contribution file, but I could not figure this scenario there
https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md

**Comment by Fyrd** [comment]
Pretty simple really, the search looks through the feature's title, description, id and keywords. Basically keywords is just to cover anything not already in the other fields.

**Comment by marquesarthur** [comment]
Perfect. Then, it seems like a full-text search based system. Anyway, the answer solves the problem and we can figure it out based on the provided fields. Thank you @Fyrd.
