### ISSUE TITLE
Add mediaSession API 

### ISSUE THREAD

**Issue by entonbiba** [Fyrd/caniuse#3158]
Currently only supported in chrome v 57 for android. #3171 
https://developers.google.com/web/updates/2017/02/media-session

Edge is under construction.
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/mediasession/?q=media%20session
![image](https://cloud.githubusercontent.com/assets/5193884/22662847/7080685e-ec78-11e6-9201-fd74fb57b500.png)

Also I created a sample with wavesurfer.js library and the API here:
https://github.com/entonbiba/Media-Session-API-wavesurfer-js

**Comment by Schweinepriester** [comment]
Available via MDN: <https://caniuse.com/?search=mediaSession>
