### ISSUE TITLE
WebKit support for CustomElements

### ISSUE THREAD

**Issue by ctolkien** [Fyrd/caniuse#3164]
I'd suggest this be downgraded to partial support. The spec defines two types of custom elements:

* Autonomous custom element
* Customized built-in element

https://html.spec.whatwg.org/multipage/scripting.html#custom-elements

WebKit supports the former only, and they are opposed to implementing the latter:

https://github.com/w3c/webcomponents/issues/509#issuecomment-222860736
https://github.com/w3c/webcomponents/issues/509#issuecomment-224212371
https://github.com/w3c/webcomponents/issues/509#issuecomment-230700060
https://github.com/w3c/webcomponents/issues/509#issuecomment-233222085

**Comment by ctolkien** [comment]
FWIW, I can PR this but wanted to open this up for discussion first.

We've just had to revisit a bunch of our code after thinking WebKit had full `CustomElement` support, when it doesn't.

**Comment by hax** [comment]
Maybe `is=` (Customized built-in element) could be list as a separate feature?

**Comment by TCotton** [comment]
I'm writing a series of blog articles on the current state of web components. It's a misconception that Chrome have fully implemented custom elements. If you look at their bug tracker [here](https://bugs.chromium.org/p/chromium/issues/list?can=2&q=component%3ABlink%3EHTML%3ECustomElements+&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids), you will see two threads that are open :
Implement Customized Builtin Elements: https://bugs.chromium.org/p/chromium/issues/detail?id=652579
Launch customized built-in elements: https://bugs.chromium.org/p/chromium/issues/detail?id=648828
The last post is on January 24.
On January 23 there is a comment which states: ["Yes, it is still being worked on"](https://bugs.chromium.org/p/chromium/issues/detail?id=652579#c11)
Without customized built-in elements I would state that the spec has not been fully implemented.
The spec, as it currently is, clearly states the that there are two different types of v1 custom elements, autonomous and customised builtin, and is promoted as such by Google themselves in this article: https://developers.google.com/web/fundamentals/getting-started/primers/customelements

**Comment by ctolkien** [comment]
Both browser should be downgraded then in your opinion @TCotton ? I signalled out WebKit here as I know they are actively opposed to implementing the full spec.

**Comment by TCotton** [comment]
@ctolkien you are right in that WebKit have repeatedly stated that they will not implement this feature. 

I found it really confusing why it wouldn't work in Chrome until I looked at their tracker

**Comment by ctolkien** [comment]
Have updated the PR to also change Chrome to partial support.
