### ISSUE TITLE
feature: track ReadableStream

### ISSUE THREAD

**Issue by kumavis** [Fyrd/caniuse#3173]
as used by the Fetch API

https://developer.mozilla.org/en-US/docs/ReadableStream
https://developer.mozilla.org/en-US/docs/ReadableStream#Browser_compatibility

**Comment by ajhamwood** [comment]
+1

**Comment by gruns** [comment]
+1

**Comment by mkurz** [comment]
+1

**Comment by dstorey** [comment]
If this is added then https://caniuse.com/#feat=streams should be converted to writablestreams (or more likely the other way around as readable streams have better browser support)

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_readablestream
