### ISSUE TITLE
IndexedDB 2.0

### ISSUE THREAD

**Issue by pwnall** [Fyrd/caniuse#3193]
Documentation: https://hacks.mozilla.org/2016/10/whats-new-in-indexeddb-2-0/

This is implemented in Chrome 58, Firefox 51, Safari 10.1, and Opera 45.

Source: https://www.chromestatus.com/feature/5812621622116352

**Comment by pwnall** [comment]
@Fyrd would you be willing to review a PR for this issue?

Thank you very much in advance!

**Comment by cvrebert** [comment]
* https://webkit.org/status/#specification-indexed-database-2.0

**Comment by cvrebert** [comment]
Fixed by #3444.

**Comment by inexorabletash** [comment]
Thanks! Any idea when this is likely to show up? I gather it's waiting on the conditions in https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md - additional verification or upvoting, so... could be a while.

**Comment by chicoxyzzy** [comment]
It's pending review according to #3444

**Comment by chicoxyzzy** [comment]
Can we help somehow to add results for IDB 2?

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=indexeddb2

**Comment by inexorabletash** [comment]
Awesome, thanks!
