### ISSUE TITLE
Presentation API

### ISSUE THREAD

**Issue by isantolin** [Fyrd/caniuse#3194]
There is a Web Presentation API ( https://developer.mozilla.org/en-US/docs/Web/API/Presentation_API ) which is already supported by Chrome (seems to be for Chromecast) with an experimental Polyfill which should work without Chromecast ( https://mediascape.github.io/presentation-api-polyfill/ ). What about add that feature?

**Comment by sandrobilbeisi** [comment]
I second the request ... the presentation API is coming soon to WebKit based Chrome, Chromium , Opera and Safari and also Gecko-based FireFox.

Second Screen Community Group ( https://www.w3.org/community/webscreens/ )

**Comment by jhpratt** [comment]
@Fyrd any plans for this? MDN has Chrome listed as support since 48, and Firefox behind a flag since 51.

**Comment by isantolin** [comment]
Was Added https://caniuse.com/#feat=mdn-api_presentation
