### ISSUE TITLE
Is HKPK a good support data suggestion? 

### ISSUE THREAD

**Issue by Pablohn26** [Fyrd/caniuse#3197]
I met this project when I reach [HTTP2](http://caniuse.com/#feat=http2)

Then I tried with HKPK, a security technology in browsers to increase SSL certificate reliability. You have more information [here](https://wiki.mozilla.org/SecurityEngineering/Public_Key_Pinning)

I am wondering if this kind of technologies are out of the scope of this project or HKPK is a good item to add. I am not sure if I could add **with good sources** all the compatibility list. From [here](http://www.shdon.com/blog/2016/02/13/http-public-key-pinning) I get 

> HPKP is supported by Mozilla Firefox since version 35, Google Chrome since version 46, and Opera since version 33 (as it is based on Chromium 46). Internet Explorer, Edge and Safari at the time of writing, do not support public key pinning. For Edge, the feature is under consideration.

and from [here](https://www.chromestatus.com/feature/4669935557017600) I can get also information.

I would like to know if HKPK is a good support data suggestion or not. Would it?

**Comment by Schweinepriester** [comment]
Isnt this feature called HPKP and thus already covered by <http://caniuse.com/#feat=publickeypinning>?

**Comment by Pablohn26** [comment]
Yes, it is the same. 

Thanks @Schweinepriester
