### ISSUE TITLE
window.navigator.language, .languages

### ISSUE THREAD

**Issue by thomasingalls** [Fyrd/caniuse#3214]
There seems to be a standard few implementations around this idea now, but there are still some inconsistencies between browsers

cf
http://gu.illau.me/posts/the-problem-of-user-language-lists-in-javascript/
https://www.w3schools.com/jsref/prop_nav_language.asp

**Comment by M22an** [comment]
When will this feature get added. I can get details on a high level about some limitations but would like more info.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_navigatorlanguage
