### ISSUE TITLE
Overlapping of sticky header

### ISSUE THREAD

**Issue by eko24ive** [Fyrd/caniuse#3239]
I was discovering `:focus-within` feature at this url: http://caniuse.com/#search=%3Afocus-within
And when I clicked `Show All` I've seen this z-index issue:
![image](https://cloud.githubusercontent.com/assets/25591824/23850290/7304e6d8-07e7-11e7-8ceb-4cf86dca791c.png)

Using Chrome v56.0.2924.87 on Win10

**Comment by Fyrd** [comment]
This issue no longer exists due to sticky headers having been removed.
