### ISSUE TITLE
CSS: overflow-anchor

### ISSUE THREAD

**Issue by alexey-bass** [Fyrd/caniuse#3242]
Missing support for "overflow-anchor" property.
That cause some noise with scrolling default behavior since Google Chrome v56.

**Details**
https://www.chromestatus.com/feature/5700102471548928
https://developers.google.com/web/updates/2016/04/scroll-anchoring

**Issues**
https://stackoverflow.com/questions/42308209/chrome-browser-automatically-scrolling-down-the-content-when-nobody-asked-it-to/42562623
http://stackoverflow.com/questions/42100246/angular-ui-grid-scroll-error

**Comment by yisibl** [comment]
Spec: https://wicg.github.io/ScrollAnchoring/

**Comment by Fyrd** [comment]
Added some time ago at https://caniuse.com/#feat=css-overflow-anchor
