### ISSUE TITLE
webshareapi

### ISSUE THREAD

**Issue by kcassam** [Fyrd/caniuse#3254]
Feature suggest : can I use web share api ? http://caniuse.com/#search=web-share-api

https://developers.google.com/web/updates/2016/10/navigator-share

**Comment by awebdeveloper** [comment]
duplicate : https://github.com/Fyrd/caniuse/issues/3162

**Comment by awebdeveloper** [comment]
kindly close this issue since my pr is merged

https://github.com/Fyrd/caniuse/pull/3368#issuecomment-301329488

**Comment by kcassam** [comment]
here https://caniuse.com/#feat=web-share 👏🏼
