### ISSUE TITLE
Add prefers-reduced-motion

### ISSUE THREAD

**Issue by leefloyd** [Fyrd/caniuse#3257]
The reduced motion media query has been implemented in Safari. https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_1.html#//apple_ref/doc/uid/TP40014305-CH12-DontLinkElementID_60

**Comment by MarcusJT** [comment]
See also https://webkit.org/blog/7551/responsive-design-for-motion/

**Comment by rosebrt** [comment]
"prefers-reduced-motion" is in the W3 editors draft
https://drafts.csswg.org/mediaqueries-5/#prefers-reduced-motion
And according to Chris Coyier at CSS-Tricks it is planned long-term for other browsers to support it. Definetly seems like a good thing to add to the site.

**Comment by rosebrt** [comment]
https://css-tricks.com/introduction-reduced-motion-media-query/
here is the CSS-Tricks article on it, as well

**Comment by rosebrt** [comment]
+1

**Comment by Linrstudio** [comment]
+1

**Comment by evaferreira** [comment]
+1

**Comment by Malvoz** [comment]
+1

**Comment by vadim-kovalyov** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=prefers-reduced-motion
