### ISSUE TITLE
add "document.contentType"

### ISSUE THREAD

**Issue by kumavis** [Fyrd/caniuse#3258]
> Returns the MIME type that the document is being rendered as.  This may come from HTTP headers or other sources of MIME information, and might be affected by automatic type conversions performed by either the browser or extensions.

https://developer.mozilla.org/en-US/docs/Web/API/Document/contentType

**Comment by Ugoku** [comment]
MDN says "only supported by Gecko" but it also works in latest Chrome & Opera. Doesn't work in Edge (so I assume it doesn't work in IE either)

**Comment by GPHemsley** [comment]
Looks like this is covered by MDN data:
https://caniuse.com/mdn-api_document_contenttype
