### ISSUE TITLE
Show a range for supported version (instead of all).

### ISSUE THREAD

**Issue by Tigger-oN** [Fyrd/caniuse#3260]
It might make for a cleaner design to show a range for supported browser versions. This would be of most benefit to when selecting the "Show All" option.

For example, SVG support for Chrome (after selecting "Show All") started in version 4 and you have a version number box for each version all the way up to 60. That is 56 boxes, a huge list and a lot to scroll on a phone!

Instead, you could have had a version box for "4" then a "down arrow" then a "60".  That is just 3 boxes, clean, neat and easy to scan.

Alternatively you keep the current layout and only show the ranges when the "Show All" is selected.

**Comment by Fyrd** [comment]
Something very close to this idea has now been implemented. :)
