### ISSUE TITLE
String.fromCharCode

### ISSUE THREAD

**Issue by shireefkhatab** [Fyrd/caniuse#3264]
Hi there Why not add JS String.fromCharCode() method? please. thanks

**Comment by Ugoku** [comment]
This was implemented in [the first edition of ECMAScript](http://www.ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-262,%201st%20edition,%20June%201997.pdf) back in 1997 (JavaScript 1.2). It's supported everywhere, you can safely use it.

**Comment by shireefkhatab** [comment]
Ok, Thank you very much.  i just wrote a small piece of code and it is not working on phone browsers.  so wanted to check about 3 functions.


if u please can help that would be great and ill be highly appreciated.

my code is simply this:

 /**********************************************************************/

var showoriginal = document.getElementById('showoriginal');
 showoriginal.addEventListener("click",solution);

 function solution(){
  var str = document.getElementById('Encoded').value
  var original = document.getElementById('original');
  original.innerHTML = rot13(str);
}

function rot13(str) {
  var code = [];
  for (var i = 0; i < str.length; i++) {
    code.push(str.charCodeAt(i));
  }
  code = code.map(function(item){
    if(item == 32 || item == 33 || item == 46 || item == 63) {
      return item;
    } else if (item > 77){
      return item - 13
    } else{
      return item + 13;
    }
  });

  var result = String.fromCharCode.apply(null, code)
  return result;
}
/*************************************************************************/

 Thank you in advance!
________________________________

**Comment by Fyrd** [comment]
@shireefkhatab I suggest asking this question on StackOverflow or a similar site, this isn't the best place to find help with code issues. If you do find an inconsistency between browsers feel free to share it here.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_builtins_string_fromcharcode
