### ISSUE TITLE
Support for :focus-ring

### ISSUE THREAD

**Issue by ItsEren** [Fyrd/caniuse#3267]
https://drafts.csswg.org/selectors-4/#the-focusring-pseudo

**Comment by kloh-fr** [comment]
I don't know why this issue was closed because `:focus-ring` is missing indeed.
It is related to #1058.

**Comment by kimflournoy** [comment]
+1 - I was hoping this would be added.

**Comment by cvrebert** [comment]
Superseded by #3453

**Comment by Zenuka** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=css-focus-ring
