### ISSUE TITLE
CSS Grid in Chrome on Android 

### ISSUE THREAD

**Issue by tobireif** [Fyrd/caniuse#3307]
Currently, http://caniuse.com/#feat=css-grid  says that Chrome on Android does not support Grid.

Paul Kinlan says that Chrome on Android does support Grid:

https://twitter.com/ChromiumDev/status/846643491220459520

**Comment by daytonlowell** [comment]
Yeah, it was added in Chrome 57 and caniuse still shows 56 as the current version. See issue: https://github.com/Fyrd/caniuse/issues/3308

**Comment by Schweinepriester** [comment]
The commit will probably not work per <https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md#unsupported-changes>:

> Add a new browser or browser version

Best way would probably implicit via #3308

**Comment by Fyrd** [comment]
Chrome for Android has now been updated.
