### ISSUE TITLE
Chrome for Android is up to version 57

### ISSUE THREAD

**Issue by daytonlowell** [Fyrd/caniuse#3308]
Caniuse.com shows 56 as the current version.

**Comment by Schweinepriester** [comment]
+1, Android browser/WebView most likely as well (see <https://play.google.com/store/apps/details?id=com.google.android.webview> in the actual play store app to view the version number).

**Comment by Fyrd** [comment]
Done! Looks like the WebView is at 56 now, will get to it shortly.
