### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by awebdeveloper** [Fyrd/caniuse#3311]
Notice the missing labels when I uncheck all desktop browsers

<img width="1440" alt="screen shot 2017-03-30 at 10 19 25 pm" src="https://cloud.githubusercontent.com/assets/1593429/24516065/10b52480-1597-11e7-958c-659802c4b577.png">

<img width="1440" alt="screen shot 2017-03-30 at 10 20 40 pm" src="https://cloud.githubusercontent.com/assets/1593429/24516231/8844ca6e-1597-11e7-99fb-86b0a42ceaff.png">

**Comment by corvae** [comment]
I think this is related to what I found:
![caniuseissue](https://cloud.githubusercontent.com/assets/7141060/24728098/317da242-1a1e-11e7-83ef-bef3f45cb8cf.PNG)

The browser names are at the top of the screen after selecting "Date relative" then scrolling.  I'm using Chrome 57, Win7.

**Comment by Fyrd** [comment]
This issue was fixed some time ago.
