### ISSUE TITLE
Samsung Internet v5

### ISSUE THREAD

**Issue by poshaughnessy** [Fyrd/caniuse#3320]
Hello. Thank you for [adding Samsung Internet v4](https://github.com/Fyrd/caniuse/issues/2493)! 

A few weeks back we (I'm a dev advocate at Samsung Internet) released v5. Our major versions are based on the same version of Chromium; v5.0 ([released](https://medium.com/samsung-internet-dev/announcing-samsung-internet-5-0-1ac2bfc14b78)), v5.2 (stable launching with S8) and v5.4 (currently in [beta](https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser.beta&hl=en_GB)) are all based on M51.

It would be great to get v5 added to caniuse. What was the process to add v4? What's the best way to proceed?

Given there should be minimal engine differences, I'm thinking that hopefully it should be OK to stick with one entry per major version. (The differences between e.g. 5.0, 5.2, 5.4 are more things like UI changes and extensions).

**Comment by awebdeveloper** [comment]
@poshaughnessy all major versions need to be separate coz on android ppl don't upgrade

**Comment by Fyrd** [comment]
Version 5 is now on the site!
