### ISSUE TITLE
Safari 7.1/8 and Edge 13/14 only has partial support of HTML templates

### ISSUE THREAD

**Issue by manubb** [Fyrd/caniuse#3323]
More precisely, in those browsers (and maybe others), cloneNode calls on nested templates produce incorrect results. Support can be checked by using the tests used in [webcomponents/template](https://github.com/webcomponents/template) polyfill.

**Comment by manubb** [comment]
Support is also partial in iOS<9.

**Comment by englishextra** [comment]
Edge 13 doesnt support template as MDN and caniuse say. It crashes as soon as you manipulate with it, whereas IE 11 survives, but it needs ccs display none for template tag. It needs polyfill loadded before body tag. The other thing is that it' about reusing markup in tepmplate tag instead of creating that markup and then appending new nodes.

**Comment by manubb** [comment]
A more precise support table:

|                |Chrome       |Firefox        |IE/Edge    |Opera         | Safari    |
|----------------|-------------|---------------|-----------|--------------|-----------|
|Flawless native |&ge;35       |&ge;22         |-          |&ge;22        |&ge;9      |
|Buggy native    |26-34 (i)    |-              |13-15 (c,i)|15-21  (i)    |6.2-8 (c,i)|

On line "Buggy native", c denotes problems when cloning templates or nodes that contain templates; i denotes problems when importing templates or nodes that contain templates. 

Note that Safari 6.1 and 7 do not have native `<template>` whereas Safari 6.2 and 7.1 do have (buggy) implementations.

See [manubb/template](https://github.com/manubb/template) for polyfill details and test suite. (Do not load the polyfill in test/basic.html to test native support. Results are displayed in the console.)
