### ISSUE TITLE
Add classList.replace()

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Fyrd/caniuse#3326]
In the [compatibility table](https://developer.mozilla.org/en/docs/Web/API/Element/classList#Browser_compatibility) of the MDN article on the `classList` property, there is mention of a `replace()` method. A (very!) brief search hasn't turned up any more information on this method, the MDN article itself doesn't even make mention of it. But, Firefox has supported it since v49 so, hopefully, other browsers may soon follow suit.

**Comment by cvrebert** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/replace#Browser_compatibility

**Comment by Schweinepriester** [comment]
+1

<https://www.chromestatus.com/feature/5691753315172352>: Chrome 61+, Opera 48+

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_element_classlist_replace
