### ISSUE TITLE
Add Expect-CT header

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#3327]
- <https://www.smashingmagazine.com/2017/04/web-development-reading-list-177/>

    > There’s a new security header called Expect-CT. Scott Helme explains when and how you should use it.

- <https://scotthelme.co.uk/a-new-security-header-expect-ct/>
- Spec: <https://datatracker.ietf.org/doc/draft-stark-expect-ct/?include_text=1>
- Chrome 
  - <https://www.chromestatus.com/feature/5677171733430272>: Chrome 61+, Opera 48+
  - <https://bugs.chromium.org/p/chromium/issues/detail?id=679012>
- MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT

**Comment by Calico90** [comment]
+1

**Comment by Malvoz** [comment]
+1

**Comment by karunkamal** [comment]
+1
Specs/Draft: https://tools.ietf.org/html/draft-ietf-httpbis-expect-ct-07

**Comment by jodosha** [comment]
+1

**Comment by Zamony** [comment]
+1

**Comment by nickmalcolm** [comment]
+1

**Comment by atjn** [comment]
There is no reason to add this anymore, is there?

**Comment by Malvoz** [comment]
@atjn is referring to the fact that data is available, pulled from MDN:
https://caniuse.com/#feat=mdn-http_headers_expect-ct

**Comment by atjn** [comment]
@Malvoz actually i wasn't, but now that you mention it, that seems like an even better reason to close it, so let's go with that! 😅

**Comment by Schweinepriester** [comment]
If @Fyrd wills it, this issue shall vanish :'-(

… ;) :P

**Comment by Fyrd** [comment]
Yeah, seems covered by the MDN table. :)
