### ISSUE TITLE
Add transform-box

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#3330]
- <https://developer.mozilla.org/en-US/Firefox/Releases/55>

    > Exposed the transform-box property by default 

- Spec: <https://drafts.csswg.org/css-transforms/#transform-box>
- MDN: <https://developer.mozilla.org/en-US/docs/Web/CSS/transform-box>

**Comment by Schweinepriester** [comment]
According to <https://twitter.com/smfr/status/872660114192322560> supported in Safari TP 32, probably implying Safari 11 as well.

**Comment by davidgilbertson** [comment]
And added in Chrome 64 https://chromium-review.googlesource.com/#/c/759040/

**Comment by davidgilbertson** [comment]
+1

**Comment by Schweinepriester** [comment]
Via MDN on caniuse: <https://caniuse.com/#feat=mdn-css_properties_transform-box>
