### ISSUE TITLE
Navigator.getGamepads()

### ISSUE THREAD

**Issue by YorkChan94** [Fyrd/caniuse#3336]
The Navigator.getGamepads() method returns an array: the first value is null, and the others are all Gamepad objects, one for each gamepad connected to the device. So if no gamepads are connected, the method will just return null.

### Syntax
```
 var arrayGP = navigator.getGamepads();
```

**Comment by cvrebert** [comment]
Covered by http://caniuse.com/#feat=gamepad

**Comment by Fyrd** [comment]
Yup. Have added navigator.getGamepads to keywords
