### ISSUE TITLE
The site is very slow at the moment

### ISSUE THREAD

**Issue by tobireif** [Fyrd/caniuse#3341]
The site is very slow at the moment. Can you reproduce that?

**Comment by tobireif** [comment]
Sometimes I even get "This site can’t be reached", "caniuse.com took too long to respond" from Chrome.

**Comment by tobireif** [comment]
The site is slow/down:
http://isitdownorjust.me/caniuse-com/
"Currently Down"
http://www.isitdownrightnow.com/caniuse.com.html
"down for everyone"

**Comment by Fyrd** [comment]
Ugh. It seems to be the result of using https by default. Have turned that off until I've figured out the problem. Thanks for letting me know!

**Comment by Fyrd** [comment]
It actually appears to be fast when you visit it now, even with https. Unfortunately heavy site traffic is what's causing it to slow down. But I'll investigate.

Closing this issue for now since the main problem has been taken care of.

**Comment by tobireif** [comment]
It has been taken care of?

**Comment by Fyrd** [comment]
Is it still slow for you? Seems to load fine here.

**Comment by tobireif** [comment]
Yes, currently it's fast, but that doesn't mean that the issue has been taken care of, right?

As soon as the circumstances from earlier today come back the issue will probably make the site severely slow again.

Perhaps there needs to be some protection agains DOS attacks?

**Comment by Fyrd** [comment]
It's been taken care of by reverting the change I'd made last night, I'd say that's good enough. Just need to be more careful when I try that again. But that seems like a separate issue.

**Comment by tobireif** [comment]
You meant HTTP-by-default, right? It would be very surprising to me if http->https rewriting or/and HSTS would cause the extreme slowdown.

In any case, I hope you can ensure HTTPS-by-default and reliable load perf - good luck! 😀

**Comment by tobireif** [comment]
Perhaps http->https rewriting is slow (when there's a high request frequency load), and setting HSTS solves the issue?

https://tobireif.com/posts/switching_to_https/
-> "HSTS" etc

**Comment by szarouski** [comment]
+1 from me. Website was very slow for past few weeks and still is - I'm on a cable 330mbps connection and it takes more than a minute to load.
