### ISSUE TITLE
Mobile Firefox not listed

### ISSUE THREAD

**Issue by tobireif** [Fyrd/caniuse#3342]
For example on the page
https://caniuse.com/#feat=css-grid
Firefox Mobile is currently not listed, even when I set the threshold to 0%.

**Comment by Ugoku** [comment]
+1

**Comment by Fyrd** [comment]
Several lesser-used browsers like Mobile Firefox are hidden by default, you can enable them under Settings -> Browsers. (or you will see them when selecting "Show all" on a browser table).
