### ISSUE TITLE
ssllabs.com/ssltest/analyze.html?d=caniuse.com

### ISSUE THREAD

**Issue by tobireif** [Fyrd/caniuse#3343]
This page
https://www.ssllabs.com/ssltest/analyze.html?d=caniuse.com
currently brings "Assessment failed: No secure protocols supported".

**Comment by Fyrd** [comment]
Seems to be working now. Not a good grade I see, but one step at a time.

**Comment by jrchamp** [comment]
@Fyrd I love this website, but now some libraries are dropping support for old versions of TLS, I can't get to your site anymore. 😢 Please enable support for TLS 1.2 (ECDHE AES-GCM is faster and more secure than DHE AES-CBC). Thank you for all that you do!
