### ISSUE TITLE
Add CSS display:contents

### ISSUE THREAD

**Issue by frivoal** [Fyrd/caniuse#3353]
Spec: https://drafts.csswg.org/css-display/#valdef-display-contents
MDN: 

Ships since Firefox 37: https://developer.mozilla.org/en-US/docs/Web/CSS/display
Chrome status: in development https://www.chromestatus.com/features/5663606012116992

**Comment by cvrebert** [comment]
Subfeature of #2337

**Comment by cvrebert** [comment]
Apparently this was added: http://caniuse.com/#feat=css-display-contents

**Comment by chharvey** [comment]
could be a search bug. see https://github.com/Fyrd/caniuse/issues/2337#issuecomment-323909364

**Comment by tobireif** [comment]
Some news:
https://twitter.com/regocas/status/971402883462811648
https://blogs.igalia.com/mrego/2018/01/11/display-contents-is-coming/

**Comment by tobireif** [comment]
Related: https://github.com/Fyrd/caniuse/issues/3584

**Comment by mgol** [comment]
Should this be closed? This is available at https://caniuse.com/#feat=css-display-contents
