### ISSUE TITLE
Support thumbs up reaction and +1 comments for issue voting

### ISSUE THREAD

**Issue by hovissimo** [Fyrd/caniuse#3357]
Please see #1995 for an example where modern reaction usage is clashing with the automated issue voting taking place at http://caniuse.com/issue-list/

It would be best I think if the prioritized issue-list used both thumbs up reactions and +1 comments.

**Comment by APerson241** [comment]
See #2408.

**Comment by hovissimo** [comment]
This is a total duplicate of #2408 for sure.
