### ISSUE TITLE
FormData support is missing/misleading

### ISSUE THREAD

**Issue by spoike** [Fyrd/caniuse#3370]
FormData support from the XHR spec is only partial for some browsers. The entry for XHR (which shows up when searching for FormData) is misleading. IE, Edge, and Safari currently only has basic support for FormData.

* [Browser support info for FormData in MDN](https://developer.mozilla.org/en/docs/Web/API/FormData)
* [XHR Spec - FormData.get](https://xhr.spec.whatwg.org/#dom-formdata-get)

**Comment by Fyrd** [comment]
Have made a few updates here:
- https://caniuse.com/xhr2 is no longer the first result when searching for `FormData` which now points at the MDN BCD table for the FormData API.
- Updated https://caniuse.com/xhr2 description and support to reduce support to partial when older APIs (e.g. FormData.get) were not available.
