### ISSUE TITLE
Add DNSSEC support

### ISSUE THREAD

**Issue by ElleshaHackett** [Fyrd/caniuse#3380]
Add DNSSEC support

**Comment by Calico90** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by Calico90** [comment]
Info regarding Google Chrome:
https://bugs.chromium.org/p/chromium/issues/detail?id=50874

**Comment by Calico90** [comment]
Info regarding Opera:
http://forums.opera.com/discussion/1867855/web-ssl-certificates-verified-by-dnssec-protected-dns-records-dane-tlsa/p1

**Comment by ElleshaHackett** [comment]
@Fyrd, any chance we can implement this?

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=dnssec
