### ISSUE TITLE
Add support for the HTTP header Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by Calico90** [Fyrd/caniuse#3389]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#Browser_compatibility

And to be added in the Security category https://github.com/Fyrd/caniuse/issues/2650

**Comment by cvrebert** [comment]
Overlaps with http://caniuse.com/#feat=cors

**Comment by Calico90** [comment]
Correct! Closed.
