### ISSUE TITLE
Add support for the svg paint-order property

### ISSUE THREAD

**Issue by JNaftali** [Fyrd/caniuse#3394]
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/paint-order#Browser_compatibility

**Comment by Ugoku** [comment]
+1

**Comment by Herst** [comment]
+1

**Comment by tobireif** [comment]
Firefox Nightly now supports paint-order for HTML text:
https://developer.mozilla.org/en-US/docs/Web/CSS/paint-order

**Comment by tobireif** [comment]
Chrome ticket: https://bugs.chromium.org/p/chromium/issues/detail?id=815111
WebKit ticket: https://bugs.webkit.org/show_bug.cgi?id=168601

**Comment by tobireif** [comment]
The latest WebKit from https://webkit.org/build-archives/ now also supports "paint-order: stroke fill" for HTML text (as Firefox Nightly does). Try eg the demo at https://developer.mozilla.org/en-US/docs/Web/CSS/paint-order .

**Comment by tobireif** [comment]
P.S. Even the latest Safari!

**Comment by tobireif** [comment]
Would be great to see this reflected on a caniuse page 😀

**Comment by tobireif** [comment]
(Browser support for paint-order used with SVG, and for paint-order used with HTML text.)

**Comment by Schweinepriester** [comment]
+1

**Comment by Herst** [comment]
+1

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-css_properties_paint-order

**Comment by tobireif** [comment]
Chrome doesn't support it for HTMl text, see the bug report link in https://github.com/Fyrd/caniuse/issues/3394#issuecomment-368128531

**Comment by tobireif** [comment]
(It should get checked for every listed browser, regarding `paint-order` applied to HTML text and also to SVG text.)
