### ISSUE TITLE
Add overscroll-action

### ISSUE THREAD

**Issue by pimmink** [Fyrd/caniuse#3398]
# overscroll-action
'overscroll-action' is a non-inherited CSS property which controls the permitted overscroll actions by the browser. It is currently spec'ed to only cover overscroll actions on viewport and can be used to disable gesture navigation actions such as pull-to-refresh and swipe to back/forward.

## In Development
**Launch bug**
#651214
**Owner(s)**
[Email](majidvp@chromium.org)
**Chrome Platform Status**
[https://www.chromestatus.com/features/5743621387059200](https://www.chromestatus.com/features/5743621387059200)
**Public Discussion**
[https://wicg.github.io/user-gesture-nav/](https://wicg.github.io/user-gesture-nav/)
**Documentation/samples:**
[https://discourse.wicg.io/t/proposal-api-to-control-user-gesture-navigation/1536](https://discourse.wicg.io/t/proposal-api-to-control-user-gesture-navigation/1536)

**Comments**
The current spec uses general CSS property but this may potentially be modified to a viewport meta value instead. See: [https://github.com/WICG/user-gesture-nav/issues/1](https://github.com/WICG/user-gesture-nav/issues/1)

**Comment by cvrebert** [comment]
@pimmink The links in your post don't work when clicked. Markdown errors probably?

**Comment by pimmink** [comment]
@cvrebert fixed

**Comment by jonjohnjohnson** [comment]
Does this spec/feature still have steam after chrome's support behind `overscroll-behavior`, which seems to cover any/all possible use cases?
 -> https://github.com/Fyrd/caniuse/issues/3725

**Comment by majido** [comment]
`overscroll-action` is non longer an active proposal and it is being fully replaced by `overscroll-behavior`. So I suggest closing this issue.
