### ISSUE TITLE
Google Analytics auth only works on http://caniuse.com (with http)

### ISSUE THREAD

**Issue by jelmerdemaat** [Fyrd/caniuse#3412]
I get Google authentication errors when trying to connect to Analytics user either of these domains:

- https://www.caniuse.com
- https://caniuse.com
- http://www.caniuse.com

Authentication only works successfully on http://caniuse.com. The problem would be probably solved by redirecting all traffic to https://caniuse.com and allowing scripts from this source in the Google tool thing.

The error is:

```
400. That’s an error.

Error: origin_mismatch

Request Details
client_id=347274306104.apps.googleusercontent.com
scope=https://www.googleapis.com/auth/analytics.readonly
immediate=false
include_granted_scopes=true
proxy=oauth2relay284421879
redirect_uri=postmessage
origin=http://www.caniuse.com
response_type=token
gsiwebsdk=1
state=1742612295|0.3570177786
jsh=m;/_/scs/apps-static/_/js/k=oz.gapi.en_GB.milSO2fxg1Q.O/m=__features__/am=AQ/rt=j/d=1/rs=AGLTcCPu0SXco63J2ohp7c2yDxFfe-0bNQ
That’s all we know.
```

I appreciate your work on Can I Use! 👍

**Comment by Fyrd** [comment]
Ah yes, forgot about this when I added https support. Should be fixed now, all the URLs you listed have been given access. While I'd like to do the https redirect thing I ran into issues with it before, so will get around to that another time. Thanks for reporting this!
