### ISSUE TITLE
Add transitionstart event

### ISSUE THREAD

**Issue by bennlich** [Fyrd/caniuse#3418]
https://developer.mozilla.org/en-US/docs/Web/Events/transitionstart#Browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/Events/transitionend#Browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/API/TransitionEvent#Browser_compatibility

According to MDN, transitionend is more widely support than any of the other events.

**Comment by Fyrd** [comment]
`transitionend` is already covered at http://caniuse.com/#feat=css-transitions as it was part of the original transitions specification. `transitionstart` is a new event.

**Comment by lpd-au** [comment]
+1

**Comment by GPHemsley** [comment]
Looks like this is now covered by MDN data:
https://caniuse.com/mdn-api_htmlelement_transitionstart_event

(via mdn/browser-compat-data#3563)
