### ISSUE TITLE
Does the support table take browser updates into account?

### ISSUE THREAD

**Issue by jfrank14** [Fyrd/caniuse#3438]
For instance, [the page for CSS-Grid](http://caniuse.com/#feat=css-grid) lists IE 11 support as partial, but it also lists IE 11 as being released on October 16, 2013. Yet the copy of IE 11 that I'm actually running has a copyright date of 2015 and the executable has a timestamp of March 4, 2017. Clearly I have an updated version that's much newer than late 2013.

So I realized that it's kind of critical to know whether the support tables show the support that the original release had, or subsequent updates, and, ideally, which updates. Is there any documentation that addresses this question?

**Comment by Fyrd** [comment]
In general browsers will change their major version number whenever they update their browser engine so it's not much of a concern. Minor updates tend to just be security updates. In the case of rare exceptions I make sure there's a note added to the feature to indicate that support got added in a later update of the same browser version.

**Comment by jfrank14** [comment]
This is good to know, thanks.
