### ISSUE TITLE
display: -webkit-box

### ISSUE THREAD

**Issue by brandonbradley** [Fyrd/caniuse#3442]
Not currently supported/listed.
http://blog.ricardofilipe.com/post/multi-line-overflow-ellipsis
http://hackingui.com/front-end/a-pure-css-solution-for-multiline-text-truncation/

**Comment by Fyrd** [comment]
The key is the `webkit-line-clamp`property which is [covered here](http://caniuse.com/#feat=css-line-clamp)., not `-webkit-box` which itself is just from an old version of Flexbox.

**Comment by brandonbradley** [comment]
However the display: -WebKit-box rule actually has other results than
flexbox, esp in regards to truncating multi line text with ellipses.
It may be the 'old version', but for those looking to use it, knowing what
browsers support it would be useful.
