### ISSUE TITLE
Safari TP appears to support CSS font-stretch

### ISSUE THREAD

**Issue by pixelthing** [Fyrd/caniuse#3447]
Caniuse currently lists CSS font-stretch as unavailable in Safari TP:
http://caniuse.com/#feat=css-font-stretch
...but (unless I have misunderstood it), release notes for TP30 list a minor behaviour update to font-stretch:
https://webkit.org/blog/7614/release-notes-for-safari-technology-preview-30/

(you do brilliant work, thanks for your continued blood, sweat and tears).

**Comment by Fyrd** [comment]
Yup, confirmed that it's supported in TP. Have updated the data. Thanks and thanks for the kind words!
