### ISSUE TITLE
Add Clear Site Data header

### ISSUE THREAD

**Issue by augbog** [Fyrd/caniuse#3450]
Show browser support for Clear Site Data header as specified in the W3C spec:
https://w3c.github.io/webappsec-clear-site-data/

It looks like a few places have already started implementing or supporting this but it isn't very clear what the status of browser support is? Related links:

https://bugs.chromium.org/p/chromium/issues/detail?id=607897
https://bugzilla.mozilla.org/show_bug.cgi?id=1268889

**Comment by mkurz** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

- https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/63
    > The Clear-Site-Data header is implemented and no longer behind a preference (bug 1470111).
- https://www.chromestatus.com/feature/4713262029471744:
    Chrome 61+, Opera 48+
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data

**Comment by conanite** [comment]
+1

**Comment by redeye86** [comment]
+1

**Comment by augbog** [comment]
PR merged behind flag I think only outstanding work is maybe tests :) gonna go ahead and close.
