### ISSUE TITLE
Caniuse.com site triggering Chrome bug?

### ISSUE THREAD

**Issue by matthew-dean** [Fyrd/caniuse#3454]
I'm not exactly sure what's going on, but I've been seeing rendering of the CanIUse.com site like this for weeks now: 
<img width="1052" alt="screen shot 2017-05-22 at 2 27 17 pm" src="https://cloud.githubusercontent.com/assets/414752/26329208/002038e8-3efb-11e7-8282-d48e1911eb5f.png">

The background will sometimes flash black / white, sometimes it will flash other colors before defaulting to a soft, low-contrast brown that I assume is the intended result. Sometimes it does this on first load, often it does this when switching from another tab.

I realize this is likely a Chrome rendering issue, but just a heads up that you may want to consider an alternative to the SVG bg you have in place now, while Chrome is f-ing up.

Chrome version is 58.0.3029.110.

**Comment by matthew-dean** [comment]
Another screenshot:
<img width="1047" alt="screen shot 2017-05-22 at 2 36 34 pm" src="https://cloud.githubusercontent.com/assets/414752/26329441/1dc12302-3efc-11e7-88f8-1cd2ed0738d4.png">

**Comment by matthew-dean** [comment]
After switching tabs back from posting that just now:
<img width="1056" alt="screen shot 2017-05-22 at 2 37 19 pm" src="https://cloud.githubusercontent.com/assets/414752/26329455/3817ee7a-3efc-11e7-9c96-ffac96c47cba.png">

**Comment by Fyrd** [comment]
Thanks, yeah this has been reported by a few others too...guess it's common enough to fix, so I've replaced it with a PNG for now. Thanks!
