### ISSUE TITLE
CSS :read-write

### ISSUE THREAD

**Issue by brookjordan** [Fyrd/caniuse#3462]
Is this the right place to request this be added to caniuse?

https://html.spec.whatwg.org/multipage/scripting.html#selector-read-write

> :read-write
The :read-write pseudo-class must match any element falling into one of the following categories, which for the purposes of Selectors are thus considered user-alterable: [SELECTORS]

**Comment by cvrebert** [comment]
Duplicate of #1976.

**Comment by brookjordan** [comment]
Oops. Thanks.
