### ISSUE TITLE
caretPositionFromPoint

### ISSUE THREAD

**Issue by ribrdb** [Fyrd/caniuse#3473]
Can you add support for document.caretPositionFromPoint

**Comment by officialpsoul** [comment]
It's not yet supported...???

**Comment by miketaylr** [comment]
> It's not yet supported...???

It's supported in Gecko: https://searchfox.org/mozilla-central/source/dom/base/Document.h#3658

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_documentorshadowroot_caretpositionfrompoint
