### ISSUE TITLE
JavaScript Symbol

### ISSUE THREAD

**Issue by inoyakaigor** [Fyrd/caniuse#3475]
On site no info about it.
Info on [MDN](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Symbol)

**Comment by cvrebert** [comment]
https://kangax.github.io/compat-table/es6/#test-Symbol

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_builtins_symbol
