### ISSUE TITLE
WebVR will be enabled by default for Windows users in Firefox 55

### ISSUE THREAD

**Issue by chicoxyzzy** [Fyrd/caniuse#3480]
current note
> Available only in Firefox nightly & Firefox Developer Edition, **not yet on track to be enabled for stable & beta builds** and supports only the Oculus Rift and the HTC vive on Windows VR-ready computers.

revfeference: https://blog.mozilla.org/blog/2017/06/01/mozilla-brings-virtual-reality-to-all-firefox-users/
so mentioned note should be changed or another note for Firefox >=55 should be added

**Comment by Utopiah** [comment]
Firefox 55 out today (August 8 2017) does support WebVR 1.1 and enables it by default on Windows.

**Comment by chicoxyzzy** [comment]
Closed in #3647 👌
