### ISSUE TITLE
Firefox, <input type="date">

### ISSUE THREAD

**Issue by tobireif** [Fyrd/caniuse#3483]
Just in case it's news:

https://twitter.com/hsinyi71/status/870436875214782464

**Comment by Calico90** [comment]
+1

**Comment by tobireif** [comment]
Right now it's still only in Nightly, I think.

**Comment by slokhorst** [comment]
Right now it's [marked](http://caniuse.com/#feat=input-datetime) as "on by default" (non-Nightly) for FF 56+, but in the [Mozilla wiki](https://wiki.mozilla.org/TPE_DOM/Date_time_input_types), it says 57+.

**Comment by slokhorst** [comment]
This just landed in the stable [Firefox 57](https://developer.mozilla.org/nl/Firefox/Releases/57), so I think this issue can be closed.
