### ISSUE TITLE
Support suggestion: Web notifications

### ISSUE THREAD

**Issue by jamestinman** [Fyrd/caniuse#3486]
if (!('serviceWorker' in navigator)) { // Service Worker isn't supported on this browser, disable or hide UI. return; }

if (!('PushManager' in window)) { // Push isn't supported on this browser, disable or hide UI. return; }

See https://developers.google.com/web/fundamentals/engage-and-retain/push-notifications/

**Comment by Fyrd** [comment]
Already covered by http://caniuse.com/#feat=push-api
