### ISSUE TITLE
HEIF image format

### ISSUE THREAD

**Issue by daxim** [Fyrd/caniuse#3490]
label: Support data suggestion

<https://nokiatech.github.io/heif/>
<https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format>
<https://news.ycombinator.com/item?id=14489987>

This is relevant for browsers now because of Apple's recent adoption.

also see: #2254

**Comment by Schweinepriester** [comment]
+1

**Comment by slavakrampetz** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=heif
