### ISSUE TITLE
Add Edge 16 (?)

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#3501]
<https://blogs.windows.com/windowsexperience/2017/06/08/announcing-windows-10-insider-preview-build-16215-pc-build-15222-mobile/> or rather <https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/desktop/16215/?compareWith=15063>

New features at least:

> - Added support for advanced Event Listeners (“once” and “passive”)
> - Added support for CSS object-fit/object-position
> - Added support for CSS position: sticky

Probably this version of Edge reports as 16, but I didn't yet check, therefore the question mark in the title. But in the past they incremented and matched the first two digits of the build version (16215).

**Comment by ctolkien** [comment]
Would be good to get this in

**Comment by Fyrd** [comment]
Added, thanks @Schweinepriester! I think it's safe to assume it'll be 16 too. :)

**Comment by Schweinepriester** [comment]
@Fyrd, <https://caniuse.com/#feat=passive-event-listener> didn't seem to have gotten the treat? 0:-)

**Comment by Fyrd** [comment]
@Schweinepriester Missed it somehow, thanks for the reminder!
