### ISSUE TITLE
dash-array

### ISSUE THREAD

**Issue by DerkJanSpeelman** [Fyrd/caniuse#3504]

**Comment by Schweinepriester** [comment]
Link? What is exactly meant? The similar property used in SVG?

**Comment by DerkJanSpeelman** [comment]
The CSS value or XML+SVG attribute dash-array

2017-06-09 17:20 GMT+02:00 Kai <notifications@github.com>:

**Comment by Schweinepriester** [comment]
Probably same as https://github.com/Fyrd/caniuse/issues/3505#issuecomment-307425458.

**Comment by Fyrd** [comment]
Closed for same reason as #3505.
