### ISSUE TITLE
Update Payment Request API support

### ISSUE THREAD

**Issue by Ugoku** [Fyrd/caniuse#3511]
* Chrome 60 will support this on desktop: https://blog.chromium.org/2017/06/chrome-60-beta-paint-timing-api-css.html
* Edge is currently listed as "preliminary implementation". According to an Edge developer, that is incorrect, but I'm not sure (yet) what the current status is in Edge: https://twitter.com/kylealden/status/874875091934470144

If the second point is cleared up, I'd be happy to submit a PR :)

**Comment by Schweinepriester** [comment]
(Just for the record, PR for Edge: #3513 - I know you know about this)

**Comment by Fyrd** [comment]
Thanks, this has been updated thanks to several recent PRs. :)
