### ISSUE TITLE
HEIF - High Efficiency Image File Format

### ISSUE THREAD

**Issue by tomidotomicode** [Fyrd/caniuse#3523]
HEIF is a new image file format, related to HEVC video coding. There is already some industry support from Apple, and Nokia. HEIF file can store single, or multiple images including their thumbnails, burst photos - and provide up to 2x compression to JPEG images.

More information on HEIF
https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format
http://nokiatech.github.io/heif/index.html

**Comment by Schweinepriester** [comment]
Duplicate #3490.

**Comment by ruchern** [comment]
#3506 
http://caniuse.com/#search=HEIF

It has just gone live now.

**Comment by tomidotomicode** [comment]
Thanks!
