### ISSUE TITLE
Date.prototype.toLocaleDateString

### ISSUE THREAD

**Issue by richardtallent** [Fyrd/caniuse#3527]
Just wanted to suggest adding this method to the list... I had to go to developer.mozilla.org... oh, the humanity...

**Comment by ghartsho** [comment]
+1 (not sure how the `+`s are counted on [Caniuse Feature Suggestion List](http://caniuse.com/issue-list))

**Comment by melinath** [comment]
Also developer.mozilla.org doesn't even specify the earliest version of ie that supports this method.

**Comment by djwashburn** [comment]
+1 . As others mentioned, it's only ond developer.mozilla.org, and they don't mention which version of IE is the first to support it.

**Comment by ongmin** [comment]
+1. Not sure how it's added to the list too? There's only 2 counts on the list.

**Comment by ongmin** [comment]
+1

**Comment by laurentpayot** [comment]
Any news?

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=date-tolocaledatestring
