### ISSUE TITLE
min/max-device-width/height

### ISSUE THREAD

**Issue by tisdall** [Fyrd/caniuse#3530]
I can't seem to find any details on [min|max]-device-[width|height].  It matches the javascript values of `screen.width` and `screen.height`.

Here's some information on the CSS media query: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#device-width

And here's some compatibility data for `screen.width` and `screen.height` which appears to match the CSS media values:  https://www.quirksmode.org/mobile/tableViewport.html#t00

W3C info:  https://www.w3.org/TR/mediaqueries-4/#mf-deprecated

I was looking into it because `max-device-width` in Android's built in web view seems to match physical pixels while in Chrome it matches CSS pixels.

**Comment by GPHemsley** [comment]
MDN docs for these deprecated features are now at:
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/device-width
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/device-height

Looks like this is now covered by MDN data:
https://caniuse.com/mdn-css_at-rules_media_device-width
https://caniuse.com/mdn-css_at-rules_media_device-height

(via mdn/browser-compat-data#2217)
