### ISSUE TITLE
Please add navigator.share

### ISSUE THREAD

**Issue by fdenzer** [Fyrd/caniuse#3538]
AFAICT at the end of 2016 it was announced. only chrome will probably support it for now.

**Comment by cvrebert** [comment]
i.e. the [Web Share API](https://wicg.github.io/web-share/)

**Comment by cvrebert** [comment]
* https://www.chromestatus.com/feature/5668769141620736
* https://webkit.org/status/#feature-web-share
* https://bugzilla.mozilla.org/show_bug.cgi?id=1312422
* https://bugs.webkit.org/show_bug.cgi?id=171100

**Comment by Ugoku** [comment]
+1

**Comment by King2500** [comment]
+1

Feature with Share UI was added in Chrome 61 for Android:
https://blog.chromium.org/2017/08/chrome-61-beta-javascript-modules.html

**Comment by Peter42** [comment]
+1

**Comment by awebdeveloper** [comment]
I already have a PR that's merged 
https://github.com/Fyrd/caniuse/blob/1be885f9cffc6e4d2944847ef537de890709bbf2/features-json/web-share.json

Don't know why this ain't showing up

**Comment by cvrebert** [comment]
The data is still pending review by Fyrd, per the label on your PR.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=web-share
