### ISSUE TITLE
Lookbehind in JavaScript regex

### ISSUE THREAD

**Issue by GustvandeWal** [Fyrd/caniuse#3540]
The title speaks for itself. I'd like to be able to track whether or when `lookbehind` is supported in JavaScript regular expressions.
All I know for now is that you can enable it in Chrome with the 'Experimental JavaScript' flag.

**Comment by vshesh** [comment]
+1

**Comment by damianobarbati** [comment]
+1

**Comment by damianobarbati** [comment]
and positive lookahead too now that we have it

**Comment by joelcuevas** [comment]
+1

**Comment by andfaulkner** [comment]
+1

**Comment by amadanmath** [comment]
Works natively on some now, not even experimental; +1 to this feature

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=js-regexp-lookbehind
