### ISSUE TITLE
Default function parameters

### ISSUE THREAD

**Issue by ocian** [Fyrd/caniuse#3544]
no info about it on [https://caniuse.com/](https://caniuse.com/)

[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters)

**Comment by Schweinepriester** [comment]
<https://caniuse.com/#search=default%20function> shows "

**Comment by jleaders** [comment]
It should also show up for "default parameters"

**Comment by Schweinepriester** [comment]
Seems to be covered now: <https://caniuse.com/?search=Default%20function%20parameters>

Esp.
- https://caniuse.com/mdn-javascript_functions_default_parameters
- https://caniuse.com/es6
