### ISSUE TITLE
Geography setting intermittently broken

### ISSUE THREAD

**Issue by Krinkle** [Fyrd/caniuse#3564]
I've not been able to get data successfully for any given country. When looking at the network panel, I notice that the AJAX requests to `process/request_region_data.php` respond with invalid content. A mixture of HTML error messages and (eventually...) JSON content.

For example at <http://caniuse.com/process/request_region_data.php?id=US>
```
ERROR: Failed to get expected ratio values, trying again...<br>
ERROR: Failed to get expected ratio values, trying again...<br>
{"id":"US","name":"United States of America","month":"2017-05","access_date":"2017-06-04","data":{ /* .. */ },"total":98.5836481239}
```

It also appears as if it isn't cached. It's taking a rather long time, every time. Is this script in source control somewhere?

**Comment by Fyrd** [comment]
Thanks for reporting this! Seems something went wrong with the latest usage data import. Have added a temporary fix for now until I get a chance to investigate further.
