### ISSUE TITLE
Feature Policy

### ISSUE THREAD

**Issue by cvrebert** [Fyrd/caniuse#3570]
* Spec: https://wicg.github.io/feature-policy/
* Chrome platform status: https://www.chromestatus.com/feature/5694225681219584

**Comment by cvrebert** [comment]
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1390801

**Comment by Malvoz** [comment]
+1

This recently [shipped in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=623682&desc=2).

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=feature-policy

**Comment by miclf** [comment]
Hello there :)

According to the [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1390801) and to the [MDN compatibility table](https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy#Browser_compatibility), this is available behind a flag in Firefox 65+. (`dom.security.featurePolicy.header.enabled` needs to be set to `true` in `about:config`)

caniuse currently indicates no support at all in Firefox nor Firefox for Android.
