### ISSUE TITLE
Update usage statistics

### ISSUE THREAD

**Issue by chicoxyzzy** [Fyrd/caniuse#3573]
Current usage statistics is a bit outdated. For example Edge 15 still have 0% usage.

**Comment by Fyrd** [comment]
Yeah, StatCounter started rate limiting requests so I haven't been able to properly do the June stats. Currently on vacation but I hope to deal with this next week.

**Comment by chicoxyzzy** [comment]
It seems like usage data was updated but Edge 15 still have 0% being released in April while Safari 11 has 0.01% not even being released, so I suppose Edge data wasn't updated yet?

**Comment by chicoxyzzy** [comment]
Also, Safari 11 is stable now

**Comment by chicoxyzzy** [comment]
I think this is fixed now
