### ISSUE TITLE
Grid-auto-flow

### ISSUE THREAD

**Issue by king-koen** [Fyrd/caniuse#3581]
Css grid is now supporter in All majoor browsers however Edge and ie10 only support a previous Version.It is hard to vind out what part of grid  i can use and have alike support in ie10 and edge. For grid expliciet positioning Both versions give support. For auto positioning the Old Version Does not has an alternative. I like to Read such on your great site.

**Comment by GreatFireWall** [comment]
About 2 years, still no reply..

**Comment by Schweinepriester** [comment]
Available via MDN now: <https://caniuse.com/mdn-css_properties_grid-auto-flow>
