### ISSUE TITLE
CanvasRenderingContext2D.ellipse()

### ISSUE THREAD

**Issue by xiaoxiyao** [Fyrd/caniuse#3585]
[https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/ellipse](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/ellipse)

**Comment by GPHemsley** [comment]
Looks like this is now covered by MDN data:
https://caniuse.com/mdn-api_canvasrenderingcontext2d_ellipse

(via mdn/browser-compat-data#851)
