### ISSUE TITLE
add css property aspect-ratio

### ISSUE THREAD

**Issue by xaddict** [Fyrd/caniuse#3595]
To maybe get this picked up fast:
https://tomhodgins.github.io/aspect-ratio-spec/aspect-ratio.html

**Comment by Ugoku** [comment]
You realize that's not an official spec but just someone with a cool idea, right?

**Comment by xaddict** [comment]
yes. but sometimes putting things on here, or at least talking about it, speeds up the process of actual spec writing and implementation :)

**Comment by cvrebert** [comment]
Relevant: https://github.com/w3c/csswg-drafts/issues/1173

**Comment by Schweinepriester** [comment]
On caniuse via MDN: <https://caniuse.com/#feat=mdn-css_properties_aspect-ratio>

In Chrome Canary 84.0.4145.0: <https://twitter.com/Una/status/1260980901934137345>

**Comment by mahboubii** [comment]
@Fyrd should `aspect-ratio` be added to this repo features since tools like `doiuse` relies on this? any automated script to pull info from MDN or should it be manual?
