### ISSUE TITLE
CSS `:has()` will only be implemented in JS selectors

### ISSUE THREAD

**Issue by jhpratt** [Fyrd/caniuse#3599]
I think this is something worth noting. CSS will not support selectors such as `section:has(a)` due to performance and cascading issues.

**Comment by jhpratt** [comment]
Just coming back to this ─ I dug up [the spec](https://drafts.csswg.org/selectors/#dynamic-profile) that defines this.

[MDN states it in plainer language](https://developer.mozilla.org/en-US/docs/Web/CSS/:has).

> `:has` is not marked as part of the dynamic selector profile, which means it can not be used within stylesheets; only with functions like `document.querySelector()`.

**Comment by Schweinepriester** [comment]
I think this issue has (luckily 😎) been made obsolete - <https://developer.mozilla.org/en-US/docs/Web/CSS/:has> now states

> The `:has()` pseudo-class takes a relative selector list as an argument. In earlier revisions of the CSS Selectors Level 4 specification, `:has` had a limitation that it couldn't be used within stylesheets. Instead, it could only be used with functions like [`document.querySelector()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector); this was due to performance concerns. *This limitation has been removed* because no browser implemented it that way. Instead, browsers currently only support the use of `:has()` within stylesheets.

=> https://caniuse.com/css-has

0:-)

**Comment by Fyrd** [comment]
Agreed, closing as per above
