### ISSUE TITLE
Search doesn't work: website errors

### ISSUE THREAD

**Issue by Daniel-Hug** [Fyrd/caniuse#3601]
When the [homepage](http://caniuse.com/) loads console gets:
> Cannot read property 'addEventListener' of null

When I enter anything into search bar console gets:
> Cannot read property 'set' of undefined

Both errors come from this JS file: http://caniuse.com/js.php?1500355497

Chrome 59 on Windows 10

**Comment by Fyrd** [comment]
Thanks, sorry about that. Should be fixed now.
