### ISSUE TITLE
Support Request for: JavaScript `in` operator

### ISSUE THREAD

**Issue by uhrohraggy** [Fyrd/caniuse#3606]
I've seen uses of `for` loops with `in`: `for(var i in fooCollection) { ... }` but had not seen it until today in this form:

`let disableFeature = 'disable-feature' in params;`

According to 
https://stackoverflow.com/questions/2920765/javascript-in-operator-compatibility this is part of ECMA 3 and been around for awhile, but could be worth having as an operator for JavaScript.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_operators_in
