### ISSUE TITLE
Consider add 'getRootNode'?

### ISSUE THREAD

**Issue by maicss** [Fyrd/caniuse#3609]
MDN page: [node.getRootNode](https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode)

**Comment by cvrebert** [comment]
Presumably a subfeature of http://caniuse.com/#feat=shadowdomv1

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_node_getrootnode
