### ISSUE TITLE
Count "Reactions" as votes for [Support data suggestion]

### ISSUE THREAD

**Issue by michaelblyons** [Fyrd/caniuse#3615]
Rather than encouraging a flood of "+1" posts on issues with the [Support data suggestion] label, please support the GitHub reactions (thumb-up/-down on the first post, etc.) as a way to indicate support for an issue.

Ideally de-dup reaction voting from comments so that no one can double-vote.

**Comment by Schweinepriester** [comment]
Duplicate of #2408?

**Comment by michaelblyons** [comment]
Yes.
