### ISSUE TITLE
CSS cubic-bezier

### ISSUE THREAD

**Issue by smartdub** [Fyrd/caniuse#3618]
I found « cubic-bezier() » by reading on [Google's Material Design](https://material.io/guidelines/motion/duration-easing.html#duration-easing-natural-easing-curves) site. So I was a bite desapointed to not found information about it's cross-browser support here.

**Comment by Schweinepriester** [comment]
Strictly speaking, duplicate of #2217.

@Fyrd: Seems reasonable though to add cubic-bezier as keyword to CSS3 Transitions?

**Comment by Fyrd** [comment]
@Schweinepriester Good idea. Yup, has been added to CSS transitions as well as CSS animations as the value's supported for both timing function properties.
