### ISSUE TITLE
Meta : the web site : add a remainder to ask for disabling adblockers.

### ISSUE THREAD

**Issue by fabm22** [Fyrd/caniuse#3621]
Seriously, I only now realized I have been using caniuse.com with AdBlock on... Realized this when I saw a Patreon mention somewhere in here.

This might be one of the purest case where I DON'T want the web site to be ad blocked so I can "pay" a bit (as little as it can be, still) to the maintainers of the plaftorm. I'm sure I'm not alone in this case. 

I think that would help the maintainers and this amazing project as a whole !

**Comment by Fyrd** [comment]
Your sentiment is much appreciated! In all honestly though, I don't terribly mind people using AdBlock on the site. :) That said I do recommend contributing via Patreon if you want a guilt-free way to block ads (for $1/mo).

**Comment by fabm22** [comment]
I will indeed consider it so I can avoid my growing guilt haha. Thanks.
