### ISSUE TITLE
Missing core JS functions

### ISSUE THREAD

**Issue by SinBirb** [Fyrd/caniuse#3624]
Hi, the following two core JS functions are missing:

- createDocumentFragment()
- isEqualNode()

Reference:
https://quirksmode.org/dom/core/#miscellaneous

**Comment by cvrebert** [comment]
The `isEqualNode` portion duplicates #2527.
`createDocumentFragment` was defined in [DOM Level 2](https://www.w3.org/TR/DOM-Level-2-Core/core.html#ID-35CB04B5), so it's likely to be pretty darn universal.
