### ISSUE TITLE
Add <data> element

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#3631]
- Spec: <https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-data-element>
- <https://www.chromestatus.com/feature/5701891585474560>: Chrome 62+, Opera 49+
- <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/data>

If this is a duplicate or even exists already, `<data>` or at least `data element` should find this I believe :)

**Comment by Schweinepriester** [comment]
Exists now via MDN <https://caniuse.com/#feat=mdn-html_elements_data> but is still not that easy findable.

**Comment by GPHemsley** [comment]
Seems to be easily findable now:
https://caniuse.com/?search=data
https://caniuse.com/?search=%3Cdata%3E
https://caniuse.com/?search=data%20element

(MDN data via mdn/browser-compat-data#358)

**Comment by Fyrd** [comment]
Closing as per above.
