### ISSUE TITLE
Can I use WebGL in Chrome in cloud desktop without GPU?

### ISSUE THREAD

**Issue by yangguangface** [Fyrd/caniuse#3634]
Can I use WebGL in Chrome in cloud desktop without GPU? For my PC is cloud desktop, it hasn't GPU at all. Once I can  create THREE.WebGLRenderer() with Chrome 46. But after the Chorme updated to 56, the WebGLRenderer can't be created.

**Comment by Fyrd** [comment]
This seems like more of a question for stackoverflow.
