### ISSUE TITLE
Visual Viewport API

### ISSUE THREAD

**Issue by cvrebert** [Fyrd/caniuse#3638]
Which adds `window.visualViewport`

* Spec: https://wicg.github.io/visual-viewport/
* Chrome: https://www.chromestatus.com/feature/5737866978131968
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1357785
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=170982

**Comment by Herst** [comment]
+1

**Comment by cvrebert** [comment]
https://webkit.org/status/#feature-visual-viewport-api

**Comment by MorrisJohns** [comment]
Supported in released version of Chrome since last year (Chrome 61):

https://developers.google.com/web/updates/2017/09/visual-viewport-api

**Comment by Herst** [comment]
+1

**Comment by Schweinepriester** [comment]
<https://webkit.org/blog/8566/release-notes-for-safari-technology-preview-74/>

> Enabled visual viewport API by default

MDN: <https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport>

**Comment by mmzoo** [comment]
I think this is as simple as checking for `window.visualViewport` the way [this polyfill](https://github.com/WICG/visual-viewport/blob/9a9af3cd6d78b643ecb1b4a1a91b4ebc7a5165f7/polyfill/visualViewport.js#L89) does it.

**Comment by bartnv** [comment]
+1

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_visualviewport
