### ISSUE TITLE
erro Unexpected end of input

### ISSUE THREAD

**Issue by Foreinyel** [Fyrd/caniuse#3646]
npm install caniuse-db

npm ERR! Unexpected end of input at 1:180331
npm ERR! b/-/caniuse-db-1.0.30000647.tgz"},"_hasShrinkwrap":false},"1.0.300006
npm ERR!                                                                      ^

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shihao/.npm/_logs/2017-08-08T08_55_16_395Z-debug.log

**Comment by Fyrd** [comment]
This is probably not a problem with caniuse-db. There is likely additional logging output in that log.

Probably the .tgz file didn't finish downloading.

**Comment by Foreinyel** [comment]
I can download any other packages except caniuse-db, maybe something is wrong with npm. I downgrade version of npm to 4.6.1. Fixed.
