### ISSUE TITLE
CSS minmax()

### ISSUE THREAD

**Issue by fgeierst** [Fyrd/caniuse#3662]
https://developer.mozilla.org/en-US/docs/Web/CSS/minmax
Part of CSS grid: https://drafts.csswg.org/css-grid/#valdef-grid-template-columns-minmax

**Comment by calvinjuarez** [comment]
+1

**Comment by Bilge** [comment]
+1

**Comment by mrleblanc101** [comment]
+1

**Comment by brentonstrine** [comment]
+1

**Comment by freimuth82** [comment]
+1

**Comment by lydenyardley** [comment]
Already implemented: https://caniuse.com/#feat=mdn-css_properties_grid-template-columns_minmax

**Comment by supersimplenet** [comment]
It does work, apart from `auto` value, on Internet Explorer 11: https://jsfiddle.net/z2gf75ry/

More info:
* [CSS Grid in IE: Debunking Common IE Grid Misconceptions](https://css-tricks.com/css-grid-in-ie-debunking-common-ie-grid-misconceptions/#article-header-id-2)
* [About: CSS Grid for IE11
](https://gist.github.com/pagelab/23455c37347696c8cdf28eecacb0a7e2#user-content-about-css-grid-for-ie11)

**Comment by Fyrd** [comment]
Two tables for this available at https://caniuse.com/#search=minmax()

**Comment by supersimplenet** [comment]
Sorry, what i meant is that `minmax` does work (apart from`auto`) on Internet Explorer 11, so IMHO it should appear as partially supported, I am right?

**Comment by fgeierst** [comment]
The dataset on minmax comes from MDN, so I guess any update must be requested here: https://github.com/mdn/browser-compat-data/issues
