### ISSUE TITLE
Add Samsung Internet 6

### ISSUE THREAD

**Issue by wojtekmaj** [Fyrd/caniuse#3664]
Samsung Internet Browser version 6.x has been recently released as a public beta. We should probably add it to the list, especially since there's a lot of new things (SI 5.x was based on Chromium 51, version 6.x is based on Chromium 56).

**Comment by DaSchTour** [comment]
I was searching for the Chromium Version that Samsung Internet 6 will be based upon. It's really annoying to see they will release a new version that will not support css grid 😞

**Comment by leolux** [comment]
Regarding statscounter [1] Samsung Internet has a bigger market share than Edge. This should be enough reason to add it to the list. Moreover the browser can now be installed on other devices as well, not only on Samsung.

[1] http://gs.statcounter.com/browser-market-share/all/europe

**Comment by poshaughnessy** [comment]
@DaSchTour It does include CSS Grid. v6 is based on M56 but we backported CSS Grid.

Would be great to get v6 added soon! Let me know how we can help!

**Comment by torgo** [comment]
It's too bad that this data is so far out of date, considering Version 6.2 launched over a month ago. Is there any way we can help?

**Comment by Fyrd** [comment]
Samsung 6.2 is now on the site! The delay was mostly due to a misunderstanding on my part, thought it was still in beta and must have missed @poshaughnessy's comment. Sorry about that!
