### ISSUE TITLE
Fix statistics of Samsung Internet browser

### ISSUE THREAD

**Issue by wojtekmaj** [Fyrd/caniuse#3665]
I find it highly unlikely that literally no one is using Samsung Internet version 5.x. There's clearly something wrong with the statistics, and it's not just the fact the stats are out of date, they are not - SI 5.x is the newest version on release channel, out in the wild since December 2016.

**Comment by Fyrd** [comment]
Unfortunately neither StatCounter nor NetMarketShare provide usage data for the different Samsung browser versions so right now it's all just going into version 4 as it was before 5 was added. Will probably switch that at some point.

**Comment by nuxodin** [comment]
Statcounter provides ussage data for different samsung browsers:
This is for switzerland:
![image](https://user-images.githubusercontent.com/16326/29485017-ebe7c1be-84ca-11e7-81f5-53a0ebe61d33.png)

**Comment by Fyrd** [comment]
@nuxodin Ah you're right! Thanks for sharing that. Seems that only appears when selecting "All platforms" but not just for "Mobile" where I was expecting it. That's okay though, I can extract the data from there.

**Comment by nuxodin** [comment]
I am looking forward to an update

**Comment by Fyrd** [comment]
Just started on it...hope to have it included within the next few days.

**Comment by poshaughnessy** [comment]
@Fyrd I think this is fixed and can be closed, right? :)

NB. Looking at their data from the last couple of months, StatCounter includes our recent v6.x. So if it's possible to add v6 now https://github.com/Fyrd/caniuse/issues/3664, that would be extra awesome!

![screenshot from 2017-11-22 10-24-33](https://user-images.githubusercontent.com/151207/33123945-7de385f6-cf73-11e7-9552-e57f53c5219b.png)

**Comment by Fyrd** [comment]
There was still one issue where StatCounter wasn't including data in the source I was using for regional data (see #3889) but that's been resolved now, so closing this issue.
