### ISSUE TITLE
Add Ability to Name Google Analytics Sources

### ISSUE THREAD

**Issue by duvallg** [Fyrd/caniuse#3666]
I deal with 30+ GA accounts on a daily basis; importing them into CanIUse gives me "All Web Site Data" with no ability to discern one client's GA account from the other for proper contextualization. Thanks!

**Comment by duvallg** [comment]
Ping pong.

**Comment by chris13524** [comment]
This would be really nice for me as well. My GA view is named "Global" and that makes it confusing to discern between the Google Analytics view and caniuse's "Global" dataset.

**Comment by chris13524** [comment]
As a workaround, I was able to edit the local storage value `usage-data-by-id` and change the name of the dataset that way.

**Comment by Fyrd** [comment]
The beta site (https://beta.caniuse.com) now has an option to rename the analytics source name. Will close this issue once it's on the main site.

**Comment by Fyrd** [comment]
This is now available on the main site.
