### ISSUE TITLE
Add <time> element

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#3670]
- Spec: https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-time-element
- <https://www.chromestatus.com/feature/5633937149788160>: Chrome 62+, Opera 49+
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time

`<time>` and/or `time element` should find this.

**Comment by Ugoku** [comment]
+1
Interesting, I had no idea this wasn't supported in Blink!

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-html_elements_time
