### ISSUE TITLE
Add support for CSS rule @document

### ISSUE THREAD

**Issue by velara3** [Fyrd/caniuse#3671]
Searching for the CSS rule "@document" comes up blank. 

https://www.quackit.com/css/at-rules/css_document_at-rule.cfm
https://www.w3.org/TR/2012/WD-css3-conditional-20120911/#at-document
https://www.w3.org/TR/2012/WD-css3-conditional-20121213/#changes

**Comment by Fyrd** [comment]
Duplicate of #2588
