### ISSUE TITLE
parseInt() browser compatibility

### ISSUE THREAD

**Issue by rpuspana** [Fyrd/caniuse#3673]
Hi guys !

Amazing work on the site, I use it almost everyday. Can you please do a research about parseInt() function ? Like parseInt(' 0xF', 16); ? This is the function on MDN https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/parseInt

Thank you so much !

Kind regards,
Radu

**Comment by rpuspana** [comment]
And you can tell me for sure which desktop version, mobile version, platform version is this function supported ? And you're just assuming that everyone is born with all the frontend + backend developer knowledge ? I find your fronting rather noobish and ignorant. To say the least.

**Comment by Ugoku** [comment]
Haha wow...

> And you're just assuming that everyone is born with all the frontend + backend developer knowledge ?

No, I don't. But in the link you posted **yourself**, it says it was defined in ECMAScript 1st Edition (ECMA-262). If you had clicked that, you would see that this is from **1997**. Also, the table on MDN clearly specifies that all browsers support this.

This does not belong on caniuse.

**Comment by superMDguy** [comment]
It would be kind of nice to know which browsers support it without parsing strings that start with "0" as octal.  That would help developers know whether they can use it safely without the `radix` parameter.  I don't know if that would fit on caniuse, though.

**Comment by claudepache** [comment]
> It would be kind of nice to know which browsers support it without parsing strings that start with "0" as octal.

See #1686 (modern browsers no longer parse as octal).

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_builtins_parseint and https://caniuse.com/#feat=mdn-javascript_builtins_parseint_leading_zero_strings_as_decimal
