### ISSUE TITLE
Server Timing

### ISSUE THREAD

**Issue by cvrebert** [Fyrd/caniuse#3674]
* https://w3c.github.io/server-timing/
* https://www.chromestatus.com/feature/5695708376072192

**Comment by mkurz** [comment]
+1

**Comment by mkurz** [comment]
Shipped with Chrome 65
Shipped with Opera 52

Will ship with Firefox 59:
https://bugzilla.mozilla.org/show_bug.cgi?id=1413999

**Comment by cvazac** [comment]
+1

**Comment by msolnit** [comment]
+1

**Comment by yoavweiss** [comment]
+1

**Comment by ananner** [comment]
+1

**Comment by nicjansma** [comment]
+1

**Comment by bripkens** [comment]
Data for this is already integrated within the repository, but it is currently not shown. Any chance that we could enable data presentation?

https://github.com/Fyrd/caniuse/blob/7ce80d957d62e8d09e07e17e550f60fe110c37e0/features-json/server-timing.json#L350

**Comment by cvazac** [comment]
I opened https://github.com/Fyrd/caniuse/pull/4792 to flip the flag.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=server-timing
