### ISSUE TITLE
Add previousSibling and previousElementSibling

### ISSUE THREAD

**Issue by 1dent1ty** [Fyrd/caniuse#3676]
Hi,I can't find previousSibling and previousElementSibling in caniuse,could you?

**Comment by cvrebert** [comment]
* https://dom.spec.whatwg.org/#dom-node-previoussibling
* https://dom.spec.whatwg.org/#dom-nondocumenttypechildnode-previouselementsibling

**Comment by Schweinepriester** [comment]
Available via MDN now:

- https://caniuse.com/?search=previousSibling
- https://caniuse.com/?search=previousElementSibling

Probably primarily:

- https://caniuse.com/mdn-api_node_previoussibling
- https://caniuse.com/mdn-api_element_previouselementsibling
