### ISSUE TITLE
<menuitem> element

### ISSUE THREAD

**Issue by MacaylaMarvelous81** [Fyrd/caniuse#3687]
I want to know if I can use this element!

**Comment by Schweinepriester** [comment]
MDN: <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menuitem#Browser_compatibility>

**Comment by cpplearner** [comment]
http://caniuse.com/#feat=menu ?

**Comment by MacaylaMarvelous81** [comment]
Ok I can use this element now I turned it on with chrome flags

**Comment by cpplearner** [comment]
The data needs update though. \<menuitem> and context menu was removed from Chrome and the HTML specification in June 😢. See https://github.com/whatwg/html/issues/2730

**Comment by Fyrd** [comment]
Have added `<menuitem>` as search result and updated the entry with the spec status changes.
