### ISSUE TITLE
input setRangeText

### ISSUE THREAD

**Issue by ribrdb** [Fyrd/caniuse#3692]
https://www.w3.org/TR/html5/forms.html#dom-textarea/input-setrangetext

**Comment by cvrebert** [comment]
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#dom-textarea/input-setrangetext-2

**Comment by wstaelens** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setRangeText

Please add: 
`HTMLInputElement.setRangeText()`

This does work in FireFox Quantum 68.0.1 (64-bit).
Does **not** work in Microsoft Edge (Edge 44.18364.1.0 - EdgeHTML 18.18362)

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_htmlinputelement_setrangetext
