### ISSUE TITLE
Add object / method name to schema to for detection in source code

### ISSUE THREAD

**Issue by julian-craske-p4l** [Fyrd/caniuse#3694]
I would like to add more information to the JSON schema of each feature about how to detect that the feature is being used when parsing javascript.

eslint-plugin-compat has a very small mapping list like this at the moment: https://github.com/amilajack/eslint-plugin-compat/blob/master/src/providers/CanIUseProvider.js#L133     
```
    ASTNodeType: 'MemberExpression',
    object: 'navigator',
    property: 'serviceWorker',
```

Other libraries might find this information useful as well.

**Comment by julian-craske-p4l** [comment]
@Fyrd Would you accept this improvement if I did some work on it?

**Comment by Fyrd** [comment]
@julian-craske-p4l Sorry, I feel the features on caniuse can be too broad and varied for this to be useful. Additionally I really don't want to add more information to have to maintain and include in the future. If you do want to attempt this kind of mapping I suggest it be done externally.
