### ISSUE TITLE
Keyboard Lock

### ISSUE THREAD

**Issue by cvrebert** [Fyrd/caniuse#3703]
* Spec: https://w3c.github.io/keyboard-lock/
* Chrome: https://www.chromestatus.com/feature/5642959835889664
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=700123

**Comment by Schweinepriester** [comment]
Probably covered via [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Keyboard) now:
- https://caniuse.com/mdn-api_keyboard
- https://caniuse.com/mdn-api_keyboard_lock
- https://caniuse.com/mdn-api_keyboard_unlock
- https://caniuse.com/mdn-api_keyboard_getlayoutmap

The first entry is not well discoverable though it seems, but the other three are: https://caniuse.com/?search=Keyboard%20Lock
But oh well, jumping over to MDN the general entry is only one click away, so…
