### ISSUE TITLE
Text-overflow level 4

### ISSUE THREAD

**Issue by MartinMuzatko** [Fyrd/caniuse#3708]
Hey there! I would like to add a new feature as PR. But after reading the CONTRIBUTING.md, I have no idea if I should create a new feature.json or extend the existing text-overflow.json and rename it to level 4.

https://drafts.csswg.org/css-ui-4/#funcdef-text-overflow-fade

Any ideas?
thank you in advance!

**Comment by Fyrd** [comment]
Yeah, the answer to that can vary...I would lean towards a separate feature. Is any browser supporting/working on this yet though?

**Comment by MartinMuzatko** [comment]
According to MDN no: https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow#Browser_compatibility

**Comment by Fyrd** [comment]
These are available now at https://caniuse.com/#feat=mdn-css_properties_text-overflow_fade_value etc
