### ISSUE TITLE
Add data for AV1 supported browser?

### ISSUE THREAD

**Issue by kuma** [Fyrd/caniuse#3715]
Maybe it's to early to add, but I'll suggest anyway.
AV1 is a new encoder which specified by Alliance for Open Media.
AV1 stand for AOMedia Video 1.
Google, Microsoft and Mozilla are the member of the alliance, so probably their browser will be available with AV1.

Here is the spec:
https://aomedia.googlesource.com/av1-spec/

**Comment by EwoutH** [comment]
I would love to see it added, we can't have a open alternative to HEVC soon enough and every bit of awareness helps.

**Comment by Schweinepriester** [comment]
+1

**Comment by Ugoku** [comment]
Apple just joined the AV1 alliance, making it likely Safari will support this in the future

**Comment by EwoutH** [comment]
[AV1 Open Source Video Codec Update at FOSDEM 2018 (Video)](https://www.cnx-software.com/2018/02/07/av1-open-source-video-codec-update-at-fosdem-2018-video/)

So it's almost done. Time to add support!

**Comment by EwoutH** [comment]
Support in [VLC 3.0.0](https://www.videolan.org/developers/vlc-branch/NEWS)
> Decoders: Support for experimental AV1 video
> Demuxers: Support for VP8/VP9/VP10/AV1 in MP4

Support in [GStreamer 1.14](https://gstreamer.freedesktop.org/releases/1.14/)
> Experimental support for the next-gen royalty-free AV1 video codec

**Comment by maugre** [comment]
I came looking for this information so consider this another vote for support!

**Comment by EwoutH** [comment]
[It's time](https://aomedia.org/the-alliance-for-open-media-kickstarts-video-innovation-era-with-av1-release/).

**Comment by rubenrua** [comment]
+1

**Comment by breezertwo** [comment]
+1

Facebook made their first test using it.

**Comment by ILOVEPIE** [comment]
+1
Please add.

**Comment by est31** [comment]
+1 (realized now that you actually need to say +1 and that voting on the top is not enough for the [suggestion list](https://caniuse.com/issue-list/))

Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1452683
Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=783519

**Comment by EwoutH** [comment]
+1 
in that case

**Comment by EwoutH** [comment]
+1

**Comment by foguetes** [comment]
I would love to see this added

**Comment by est31** [comment]
@Slapbox note that the two AV1 copies are of different versions and thus incompatible to each other as the bitstream changed over history. There still hasn't been a hard freeze of the format yet, only a soft freeze.

**Comment by EwoutH** [comment]
[Vimeo joins the Alliance for Open Media](https://medium.com/vimeo-engineering-blog/vimeo-joins-the-alliance-for-open-media-51065720e030)

**Comment by EwoutH** [comment]
Bitmovin has a [new AV1 demo](https://bitmovin.com/demos/av1) for Google [Chrome Canary](https://www.google.com/chrome/browser/canary.html).

**Comment by rkarroll** [comment]
Facebook just released AV1 support in some use cases:

https://code.facebook.com/posts/612340875779169/facebook-video-adds-av1-support/

**Comment by Ugoku** [comment]
To sumarise:
- Firefox has it enabled behind a flag (https://developer.mozilla.org/en-US/Firefox/Experimental_features)
- Chrome supports it starting with version 67? Maybe Canary only?
- Can't find if it's supported in Safari or Edge yet, so I think the answer to that is "no"

**Comment by Fyrd** [comment]
Thanks for all the information, everyone!
Now available at https://caniuse.com/#feat=av1
