### ISSUE TITLE
window.top & window.parent

### ISSUE THREAD

**Issue by jakenewby** [Fyrd/caniuse#3723]
title says it all. listings for:

`window.top`
https://developer.mozilla.org/en-US/docs/Web/API/Window/top

`window.parent`
https://developer.mozilla.org/en-US/docs/Web/API/Window/parent

Thanks for making this awesome project.

**Comment by Fyrd** [comment]
These have been around since ancient time browsers, FYI.

**Comment by jakenewby** [comment]
I figured that they have been around for a very long time, just was not sure if nested windows were supported pre-IE8.  I saw that `window.location` has a similar description of "supported in effectively all browsers": http://caniuse.com/#search=window.location

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_window_top and https://caniuse.com/#feat=mdn-api_window_parent
