### ISSUE TITLE
Add overscroll-behavior (previously known as scroll-boundary-behavior)

### ISSUE THREAD

**Issue by JayGeorge** [Fyrd/caniuse#3725]
As per https://twitter.com/malyw/status/906866463381884933

**Comment by Schweinepriester** [comment]
+1000

- <https://wicg.github.io/scroll-boundary-behavior/>
- <https://www.chromestatus.com/feature/5734614437986304>

**Comment by Malvoz** [comment]
+1

**Comment by Schweinepriester** [comment]
<https://bugzilla.mozilla.org/show_bug.cgi?id=951793#c33>

> In the latest version of the spec, the property name has been changed to '`overscroll-behavior`'.

While the URL didnt change, its indeed renamed in <https://wicg.github.io/scroll-boundary-behavior/>.

**Comment by skeggse** [comment]
See also https://github.com/w3c/csswg-drafts/issues/769, [WICG/overscroll-behavior](https://github.com/WICG/overscroll-behavior), and https://bugs.chromium.org/p/chromium/issues/detail?id=672921.

**Comment by Malvoz** [comment]
+1

**Comment by micate** [comment]
+1
https://developers.google.com/web/updates/2017/11/overscroll-behavior

**Comment by tobireif** [comment]
Currently, (for example) this works in Chrome Canary:
```
body {
  overscroll-behavior: none;
}
```

**Comment by tobireif** [comment]
And it's coming to Firefox:
https://github.com/Fyrd/caniuse/issues/3725

The WebKit ticket:
https://bugs.webkit.org/show_bug.cgi?id=176454

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=css-overscroll-behavior

**Comment by tobireif** [comment]
Great! Thanks!

Related: The table says that Chrome 63 supports it, but it doesn't. For example this works in Canary but not in Chrome stable 63:
```
body {
  overscroll-behavior: none;
}
```

**Comment by Fyrd** [comment]
@tobireif Ah, thanks for the reminder. Have updated the entry accordingly.

**Comment by SebConejo** [comment]
You can check this post here. It's in french? It explains how to use overscroll behavior to fix scroll on ly in a modal Dialog : [https://blog.buddyweb.fr/css-overscroll-behavior-contr%C3%B4lez-le-scroll-de-vos-interfaces-d8754f0e68a6](https://blog.buddyweb.fr/css-overscroll-behavior-contr%C3%B4lez-le-scroll-de-vos-interfaces-d8754f0e68a6).

And this pen shows how the case : [https://codepen.io/sebconejo/pen/VEqprj
](https://codepen.io/sebconejo/pen/VEqprj).
)
