### ISSUE TITLE
FLAC audio format in Edge

### ISSUE THREAD

**Issue by slokhorst** [Fyrd/caniuse#3727]
According to [this page](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/15601752-support-flac), `#feat=flac` is supported by Edge 16+.

Tested it myself, and it works: https://imgur.com/a/M95C1

**Comment by Schweinepriester** [comment]
Hurray \o/

I've created #3728 :)

For the record, the demo: <http://hpr.dogphilosophy.net/test/>
