### ISSUE TITLE
Add shadow DOM method attachShadow()

### ISSUE THREAD

**Issue by KiltedViking** [Fyrd/caniuse#3733]
I could not find the shadow DOM method .attachShadow().

I was watching a video mentioning that Safari 10 supported web components, but my old example using method .createShadowRoot() didn't work in Safari 10. ;-(

https://www.w3.org/TR/shadow-dom/#interface-shadowroot

Thanks for a great website! ;-)

**Comment by Fyrd** [comment]
Covered by https://caniuse.com/#feat=shadowdomv1, have added `attachShadow` as keyword.

**Comment by cvrebert** [comment]
attachShadow should fall under http://caniuse.com/#feat=shadowdomv1
