### ISSUE TITLE
Abortable fetch()

### ISSUE THREAD

**Issue by taralx** [Fyrd/caniuse#3740]
https://github.com/whatwg/fetch/pull/523

Firefox 57: https://bugzilla.mozilla.org/show_bug.cgi?id=1378342
Edge done but not shipped: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13009916/
Chrome not started yet: https://bugs.chromium.org/p/chromium/issues/detail?id=750599

**Comment by jymbob** [comment]
NB: while `fetch()` is the poster child for this, AbortController is broader than that: https://developer.mozilla.org/en-US/docs/Web/API/AbortController

Also for completeness:
Safari not started yet: https://bugs.webkit.org/show_bug.cgi?id=174980

**Comment by Schweinepriester** [comment]
Related to #3879, maybe subfeature or even duplicate.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=abortcontroller
