### ISSUE TITLE
Add the X-Frame-Options header

### ISSUE THREAD

**Issue by tnorthcutt** [Fyrd/caniuse#3741]
The `X-Frame-Options` header controls whether, and where, a site's content can be embedded (e.g. in an `iframe`).

This is fully supported by Firefox & IE, but Chrome does not support the `ALLOW-FROM` directive: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options#Browser_compatibility

**Comment by Schweinepriester** [comment]
Already available at <https://caniuse.com/#feat=x-frame-options>, also mentioning `ALLOW-FROM`, or am I missing something?

**Comment by tnorthcutt** [comment]
@Schweinepriester ah, so sorry – I searched for `iframe` and didn't find any mention of this. My mistake!
