### ISSUE TITLE
(function () {}).toSource()

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [Fyrd/caniuse#3746]
(function () {}).toSource()

Show which browsers use this.

**Comment by cvrebert** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/toSource
Seems non-standard and Firefox-only.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_builtins_function_tosource
