### ISSUE TITLE
grid-template-columns

### ISSUE THREAD

**Issue by jessekanner** [Fyrd/caniuse#3750]
as described here:
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns

**Comment by strider72** [comment]
Also important because it (along with grid-template-rows) handles Subgrids

**Comment by freimuth82** [comment]
+1

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-css_properties_grid-template-columns
