### ISSUE TITLE
Add new SVG filter effects

### ISSUE THREAD

**Issue by smalllong** [Fyrd/caniuse#3751]
Such as feDropShadow.
See https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feDropShadow

**Comment by GPHemsley** [comment]
Looks like `feDropShadow` is now covered by MDN data:
https://caniuse.com/mdn-svg_elements_fedropshadow

(via mdn/browser-compat-data#1435)

I haven't gone through the full list of "new" SVG filter effects (presumably referring to those defined in [Filter Effects Module Level 1](https://drafts.fxtf.org/filter-effects-1/)), but a number of them appear to be similarly covered.

(https://github.com/mdn/browser-compat-data/commits/97a233222e0d5fa83f8ab563c8f32a06b5e9a2b5?after=97a233222e0d5fa83f8ab563c8f32a06b5e9a2b5+34&branch=97a233222e0d5fa83f8ab563c8f32a06b5e9a2b5&path%5B%5D=svg&path%5B%5D=elements)

**Comment by Fyrd** [comment]
Yup, any specific filter effects can be requested separately.
