### ISSUE TITLE
EventTarget constructor

### ISSUE THREAD

**Issue by mysticatea** [Fyrd/caniuse#3761]
In the WHATWG spec, [`EventTarget` has constructor](https://dom.spec.whatwg.org/#interface-eventtarget), so we can use `new EventTarget()`. (https://github.com/whatwg/dom/commit/c4c1c8b47340a1e5ecc1a07670927b831f240586)

At least, I confirmed that it's not supported in IE 11, Chrome 62, Firefox 56.

I'm happy if I can check the support with `caniuse`.

**Comment by mysticatea** [comment]
Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=740576
Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1379688

**Comment by mysticatea** [comment]
Edge: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/20015521-eventtarget-constructor

**Comment by Buzut** [comment]
There is the [current status](https://mdn-compat-data-explorer.herokuapp.com/features/api-eventtarget-eventtarget), sourced from [MDN compatibility table](https://github.com/mdn/browser-compat-data).

Also here's [link to the whatwg spec](https://dom.spec.whatwg.org/#dom-eventtarget-eventtarget) and [MDN doc](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/EventTarget).

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_eventtarget_eventtarget
