### ISSUE TITLE
ResizeObserver

### ISSUE THREAD

**Issue by tobireif** [Fyrd/caniuse#3762]
https://twitter.com/umaar/status/914960745338634240
> ResizeObserver has landed in Chrome Canary! Get notified in JavaScript when an element resizes.

**Comment by tobireif** [comment]
(There's a page for that feature
http://caniuse.com/#search=ResizeObserver
but perhaps the info from the tweet is of use.)

**Comment by tobireif** [comment]
related: https://twitter.com/sl007/status/915201248957222912

**Comment by Fyrd** [comment]
Hm, just updated my Canary to 63.0.3235.0 and still not enabled by default.

**Comment by tobireif** [comment]
Yeah, perhaps it still is behind a flag ...

https://www.chromestatus.com/feature/5705346022637568

https://bugs.chromium.org/p/chromium/issues/detail?id=612962

**Comment by Fyrd** [comment]
Still not enabled in Canary 64, so gonna go ahead and close this.
