### ISSUE TITLE
Support data suggestion: `Intl.PluralRules`

### ISSUE THREAD

**Issue by mathiasbynens** [Fyrd/caniuse#3763]
Chrome 63 has it. Firefox has an implementation that is [currently](https://bugzilla.mozilla.org/show_bug.cgi?id=1403318) behind a flag.

**Comment by spookylukey** [comment]
+1

**Comment by spookylukey** [comment]
@Schweinepriester @matiasm15 @dartess @hogart @JakoD  - you need to actually add a "+1" comment for your vote to count, it seems, thumbs up doesn't do anything.

**Comment by JakoD** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=intl-pluralrules
