### ISSUE TITLE
Safari 11 and Mobile Safari 11 don't actually support HEIF

### ISSUE THREAD

**Issue by joppuyo** [Fyrd/caniuse#3767]
Currently both Safari 11 and Mobile Safari 11 have marked as having HEIF support. However, while both MacOS High Sierra and iOS 11 operating systems support HEIF in camera, gallery and other native applications, in my testing the support does not extend to Safari on either of these systems.

Here's the HEIF test page on desktop Safari 11 on Mac OS High Sierra

![screen shot 2017-10-07 at 2 38 25](https://user-images.githubusercontent.com/1595438/31302378-0842d564-ab0a-11e7-9c40-9e015d1eda48.png)
<img width="698" alt="screen shot 2017-10-07 at 2 38 42" src="https://user-images.githubusercontent.com/1595438/31302384-134f0fea-ab0a-11e7-9939-4503d80816b6.png">

The picture is broken and does not render. It also doesn't seem that Safari would send the HEIF type in HTTP Accept header for content negitiation.

<img width="300" alt="screen shot 2017-10-07 at 2 57 53" src="https://user-images.githubusercontent.com/1595438/31302590-8613d58c-ab0b-11e7-8a65-3fba6bbd5d25.png">

And here's mobile Safari on iOS 11
![img_0417 copy](https://user-images.githubusercontent.com/1595438/31302509-f5d96676-ab0a-11e7-9795-cfc9457d1969.png)

Likewise, it's not displaying.

Note that if you save the file to the disk, it's viewable both in iOS and MacOS.

So I would say it would make sense to remove support both for iOS and MacOS until Apple actually implements HEIF support in its browsers.

**Comment by Fyrd** [comment]
Thanks for the detailed info! I was under the impression someone had confirmed it working before and it seemed logical, so that's why it was set to Supported. Has been fixed now.
