### ISSUE TITLE
Redirecting old urls on website

### ISSUE THREAD

**Issue by marko-stimac** [Fyrd/caniuse#3776]
When I search "text-stroke caniuse" on Google the first result page links to the page which doesn't work
https://www.google.hr/search?q=text-stroke+caniuse&oq=text-stroke+caniuse
All similar links could be redirected to new url pattern https://caniuse.com/#feat=text-stroke

**Comment by Fyrd** [comment]
Thanks for pointing this out, should be fixed now!
