### ISSUE TITLE
Support XMLDocument

### ISSUE THREAD

**Issue by jpaugh** [Fyrd/caniuse#3780]
https://developer.mozilla.org/en-US/docs/Web/API/XMLDocument

As seen in the link, XMLDocument is an experimental "subtype" of Document, which add no new properties or methods, but can be treated differently by an algorithm. Interestingly, the [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/XMLDocument#Browser_compatibility) chart on MDN is out-of-date, as the latest Chrome is definitely supported.

**Comment by GPHemsley** [comment]
Looks like this is now covered by MDN data:
https://caniuse.com/mdn-api_xmldocument

(via mdn/browser-compat-data#1206)
