### ISSUE TITLE
Support Object.values

### ISSUE THREAD

**Issue by nottoseethesun** [Fyrd/caniuse#3781]
`Object.keys` is supported by caniuse, but not `Object.values`.  See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values

**Comment by cvrebert** [comment]
Already fixed by #3053.

**Comment by nottoseethesun** [comment]
Ok just a question then: How come it does not appear on caniuse.com ?

**Comment by cvrebert** [comment]
The data from #3686 is pending review/verification by Fyrd, per the label on the pull request.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=object-values
