### ISSUE TITLE
Regenerate data.json?

### ISSUE THREAD

**Issue by sideshowbarker** [Fyrd/caniuse#3782]
Would much appreciate if the `data.json` file in the repo could be regenerated some time soon. (The problem fixed in https://github.com/Fyrd/caniuse/pull/3778 is continuing in the meantime to cause an error in the HTML spec build.)

**Comment by Fyrd** [comment]
Sorry about that oversight. Done now!

**Comment by sideshowbarker** [comment]
Yup, got it — cheers & thanks
