### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by arothweiler** [Fyrd/caniuse#3788]
I'm learning CSS3 now. Can't find this one, " column-rule-style" please add it to your great site.
Thank you! Keep the good work going mate :)

**Comment by cpplearner** [comment]
http://caniuse.com/#feat=multicolumn ?

**Comment by andre019** [comment]
Yes, I know that, but if you put "column-rule-style" in search box, you cannot find it. 
Anyway great site you have!
