### ISSUE TITLE
writing-mode, Safari 11

### ISSUE THREAD

**Issue by AleshaOleg** [Fyrd/caniuse#3794]
Hey, I I [found](https://codepen.io/anon/pen/VMRgvR) out that a `writing-mode` property working perfectly in Safari 11 (it render same as Chrome 61). And in caniuse website marked `writing-mode` as should be prefixed to work properly. Am I right, or this property consist any details which I don't know? If, it's sounds good for you, I can make PR to fix this issue.

**Comment by Fyrd** [comment]
Confirmed and updated. Thanks!
