### ISSUE TITLE
font-min/max-size

### ISSUE THREAD

**Issue by Malvoz** [Fyrd/caniuse#3796]
https://www.w3.org/TR/css-fonts-4/#font-min-max-size-prop

**Comment by tonytopper** [comment]
+1 

It would be great to review the entire css-font-4 working draft and make sure all the properties are there.  https://www.w3.org/TR/css-fonts-4/

**Comment by Malvoz** [comment]
Duplicate of [#3097](https://github.com/Fyrd/caniuse/issues/3097).

**Comment by Fyrd** [comment]
Looks like these were removed from the specification, probably because math functions let you accomplish the same: https://caniuse.com/css-math-functions
See https://css-tricks.com/how-do-you-do-max-font-size-in-css/ for examples
