### ISSUE TITLE
APNG: note for edge

### ISSUE THREAD

**Issue by Veratyr** [Fyrd/caniuse#3798]
Could you add into Edge's note for APNG info about proposal in their feedback center?

Something like this:
![apng](https://user-images.githubusercontent.com/2811248/31894177-4f759ce6-b816-11e7-877c-4162181fd6e9.png)

```
Suggestion for impementation is registered in MS Developer Feedback center. You can <a href="https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6513393-apng-animated-png-images-support-firefox-and-sa">vote for this suggestion</a>
```

**Comment by Schweinepriester** [comment]
The link already is in the resources tab:

![image](https://user-images.githubusercontent.com/2644614/31933567-c2bc914e-b8a9-11e7-97b1-419e2e8fa9e2.png)

And since its already "under review", I don't think its necessary to place the link in a more prominent place…

**Comment by Veratyr** [comment]
1. Thanks, did not noticed it in resources, and still think notes is much better place for this.
2. It's "under review" since **2015**. In this case that status means "we'll not implement it in this century unless it will become most popular suggestion in our dev feedback center", sadly.
