### ISSUE TITLE
FR units

### ISSUE THREAD

**Issue by baaxee** [Fyrd/caniuse#3800]
I wanted to suggest the inclusion of FR units as seen in these articles:

https://css-tricks.com/introduction-fr-css-unit/

I know they were included with the css grid spec but it would be good to know the support for it or if it's identical at least mention it in the grid entry or associate searches with fr units with that entry (I don't know if that's possible)

**Comment by Schweinepriester** [comment]
#1041

> This is part of the grid spec, so already covered by http://caniuse.com/#feat=css-grid

But a search result for "fr unit" could be nice.

**Comment by Fyrd** [comment]
Agreed, have now added it in description and as keywords.
