### ISSUE TITLE
navigator.language and navigator.languages

### ISSUE THREAD

**Issue by smalllong** [Fyrd/caniuse#3801]
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/languages

**Comment by smalllong** [comment]
sorry, it's duplicated.

**Comment by OndrejSpanel** [comment]
Is the duplicated request still somewhere? I have searched for it but I wound only low quality #3423 

I would also like to know about `navigator.languages` and `navigator.language` browser support.

**Comment by smalllong** [comment]
@OndrejSpanel  Duplicate of #3214
