### ISSUE TITLE
Add nomodule (<script> tag attribute)

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#3804]
Via <https://philipwalton.com/articles/deploying-es2015-code-in-production-today/>:

```html
<!-- Browsers with ES module support load this file. -->
<script type="module" src="main.js"></script>

<!-- Older browsers load this file (and module-supporting -->
<!-- browsers know *not* to load this file). -->
<script nomodule src="main-legacy.js"></script>
```

> **Warning!** The only gotcha here is Safari 10 doesn’t support the `nomodule` attribute, but you can solve this by inlining a JavaScript snippet in your HTML prior to using any `<script nomodule>` tags. (Note: this has been fixed in Safari 11).

But Browser support seems to be less than the article states: <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#Browser_compatibility>

Spec: <https://html.spec.whatwg.org/multipage/scripting.html#attr-script-nomodule>

If this is covered by or equal to <https://caniuse.com/#feat=es6-module>, I'd like at least a search result for `nomodule` :) But the quote and MDN seem to indicate that there is a gap between module and nomodule support.

EDIT:

Apparently supported in Edge 16+: <https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/32930128-add-nomodule-script-tag-attribute>

**Comment by Fyrd** [comment]
After some testing it does seem there's only one version of Safari & iOS Safari that are lacking support, so have updated https://caniuse.com/#feat=es6-module to include `nomodule` with a note for that browser.
