### ISSUE TITLE
Update scroll-behavior for recent Chrome

### ISSUE THREAD

**Issue by Ugoku** [Fyrd/caniuse#3806]
Smooth scrolling has been enabled for everyone in Chrome 61, though there was a bug that prevented it from working properly in some cases ([see bug here](https://bugs.chromium.org/p/chromium/issues/detail?id=243871))

I'd update the data myself, but I have no idea what "pinch viewport" in note 1 means (`Partial support refers to support everything except of Element.scrollIntoView() and not together with pinch viewport.`)

Since this works in Chrome 61, it should also work in Opera 48 with the same caveats.

**Comment by landsman** [comment]
Same as #3725

**Comment by Schweinepriester** [comment]
Since #3725 is closed, https://caniuse.com/css-scroll-behavior seems up to date and the bug in note 1 appears to be still open, I believe this issue can be closed, right? :)
