### ISSUE TITLE
http-equiv

### ISSUE THREAD

**Issue by burlev** [Fyrd/caniuse#3807]
I'm considering using: meta http-equiv="refresh" content=
As explained here: https://www.w3schools.com/tags/att_meta_http_equiv.asp

Other developers aren't sure that it's well supported.

**Comment by Fyrd** [comment]
It's HTML4 functionality and has been supported in browsers for a long time, here's one source for that:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#Browser_compatibility

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-html_elements_meta_http-equiv
