### ISSUE TITLE
[website] loading very slow (only me ?)

### ISSUE THREAD

**Issue by yukulele** [Fyrd/caniuse#3809]
since few days, https://caniuse.com loading is very slow (about 20s) and sometime fail.
Status bar indicate : 

> Performing a TLS handshake to caniuse.com...

**Comment by Schweinepriester** [comment]
+1

Observed this in the past days and just wanted to create an ticket too.

=>
![image](https://user-images.githubusercontent.com/2644614/32001146-2ecdae3c-b999-11e7-850d-1aa587104ca9.png)

**Comment by Fyrd** [comment]
Yeah, I wish I knew what's causing this...have contacted my web host about it, will see what that leads to. Guess the workaround is to use the http version for now.

**Comment by tobireif** [comment]
> Guess the workaround is to use the http version for now.

The HTTP version also is extremely slow, to the point where it sometimes doesn't load at all.

**Comment by tobireif** [comment]
When I switched my site https://tobireif.com/ to HTTPS using https://tobireif.com/posts/switching_to_https/ it didn't become slow. I hope caniuse.com can be made HTTPs and fast as well ... 😀

Related:
https://github.com/Fyrd/caniuse/issues/885#issuecomment-293303334

**Comment by tobireif** [comment]
Currently the load time of http://caniuse.com is eg 60 seconds:
https://tools.pingdom.com/#!/qmwQm/http://caniuse.com

**Comment by yukulele** [comment]
seem fixed
