### ISSUE TITLE
Stack trace being emitted on error parsing.

### ISSUE THREAD

**Issue by RyanMicThompson** [Fyrd/caniuse#3814]
Steps to reproduce:
- Navigate to site
- Enter a string into the search box.   (tried classes, and grid)

Results:
`<br />
<b>Fatal error</b>:  Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /home/canius6/public_html/php-closure.php:412
Stack trace:
#0 /home/canius6/public_html/php-closure.php(412): SimpleXMLElement-&gt;__construct('')
#1 /home/canius6/public_html/php-closure.php(258): PhpClosure-&gt;_parseXml(false)
#2 /home/canius6/public_html/php-closure.php(212): PhpClosure-&gt;_compile()
#3 /home/canius6/public_html/js.php(27): PhpClosure-&gt;write()
#4 {main}
  thrown in <b>/home/canius6/public_html/php-closure.php</b> on line <b>412</b><br />
`
Reproducible with: 
Chromium - Version 61.0.3163.100 (Developer Build) (64-bit)
    - Plugins: LastPass
Firefox - 56.0.1 (64-bit)
    - Plugins: None

OS - Arch Linux

**Comment by Fyrd** [comment]
Fixed now. Thanks for reporting!
