### ISSUE TITLE
window.prompt, window.alert, window.confirm

### ISSUE THREAD

**Issue by ohadschn** [Fyrd/caniuse#3818]
The MDN pages don't have compatibility matrices for them: 
https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt
https://developer.mozilla.org/en-US/docs/Web/API/Window/alert
https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm

**Comment by cvrebert** [comment]
The `prompt` portion is #3235.

**Comment by Fyrd** [comment]
Available at: 
https://caniuse.com/#feat=mdn-api_window_prompt
https://caniuse.com/#feat=mdn-api_window_alert
https://caniuse.com/#feat=mdn-api_window_confirm
