### ISSUE TITLE
focusNode

### ISSUE THREAD

**Issue by lborgman** [Fyrd/caniuse#3823]
MDN says it is experimental.

**Comment by cvrebert** [comment]
Presumably you're referring to `Selection.focusNode`: https://developer.mozilla.org/en-US/docs/Web/API/Selection/focusNode

**Comment by lborgman** [comment]
Yes, thanks.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_selection_focusnode
