### ISSUE TITLE
Add setting to choose browser versions always displayed 

### ISSUE THREAD

**Issue by burtek** [Fyrd/caniuse#3831]
I'd love to see a setting to choose browser versions that are always displayed. In my company we create solutions for specific browser versions (IE>=9, Edge (all versions), Chrome(newest), etc) and I'd love to be able to set them to always appear.

**Comment by Fyrd** [comment]
Working on this one. :)

**Comment by Fyrd** [comment]
This feature is now available, see https://caniuse.com/feed/159 for details!

**Comment by burtek** [comment]
Love it! Thanks a lot
