### ISSUE TITLE
maxlength behaviour in Chrome Mobile 61 needs a note

### ISSUE THREAD

**Issue by HerrBertling** [Fyrd/caniuse#3842]
Hi 👋

While working on an internal project, @systemboogie and me noticed that the `maxlength` attribute for inputs behaves in Chrome Mobile 61 like it [is noted](https://github.com/Fyrd/caniuse/blob/master/features-json/maxlength.json#L306) for Opera Mobile and UC Browser for Android:

> Allows text beyond maxlength to be entered at first, but removes all characters past the maxlength when focus is lost.

From what we were able to observe, this is the exact behaviour for Chrome Mobile 61. The table states that this feature works for that browser. But apparently, the behaviour described above is applied to inputs with a `maxlength`.

Maybe we are missing something here. If not, I'd like to open a pull request adding the already present note also to Chrome Mobile 61.

**Comment by Fyrd** [comment]
Confirmed, thanks! Have updated the data and noticed the same behavior on a few other browsers so updated there as well.

**Comment by HerrBertling** [comment]
Awesome, thanks! 🚀
