### ISSUE TITLE
Support for CSS grid's subgrid

### ISSUE THREAD

**Issue by alecf** [Fyrd/caniuse#3843]
this is vital for proper CSS grid support, I think not supported by any browsers yet..

**Comment by sandrosc** [comment]
Subgrid's been [moved to "level 2"](https://rachelandrew.co.uk/archives/2017/03/16/subgrid-moved-to-level-2-of-the-css-grid-specification/) of the CSS grid spec, so maybe a new feature `CSS grid layout - level 2` could be added.

**Comment by cvrebert** [comment]
https://platform-status.mozilla.org/#css-subgrids

**Comment by damianobarbati** [comment]
+1

**Comment by jeffmagill** [comment]
+1

**Comment by strarsis** [comment]
+1

**Comment by etsisk** [comment]
+1

**Comment by katerlouis** [comment]
+1

**Comment by ainarela** [comment]
+1

**Comment by calvinjuarez** [comment]
The list shows a score of 7.  Is reaction voting not working?

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=css-subgrid
I decided to go for subgrid specifically for now since that's what people are most interested in. In the future may change it to Grid Level 2 if support for the spec's subfeatures doesn't get too complicated.
