### ISSUE TITLE
Paint Timing API

### ISSUE THREAD

**Issue by Krinkle** [Fyrd/caniuse#3858]
https://www.w3.org/TR/paint-timing/

Implemented by Chrome

IE via non-standard alternative (`performance.timing.msFirstPaint`).

Firefox behind a feature flag (`dom.performance.time_to_non_blank_paint.enabled`) as `performance.timing.timeToNonBlankPaint`.

MDN:
* <https://developer.mozilla.org/en-US/docs/Web/API/PerformancePaintTiming>
* <https://github.com/mdn/browser-compat-data/blob/ad7bce3f26/api/PerformancePaintTiming.json>

**Comment by cvazac** [comment]
+1

**Comment by msolnit** [comment]
+1

**Comment by bluesmoon** [comment]
+1

**Comment by nicjansma** [comment]
+1

**Comment by stefanesterer** [comment]
+1

**Comment by NateWarner** [comment]
+1

**Comment by nvaldes** [comment]
+1

**Comment by Schweinepriester** [comment]
Available via MDN: <https://caniuse.com/mdn-api_performancepainttiming>
