### ISSUE TITLE
CSS pitch and speech-rate

### ISSUE THREAD

**Issue by Pr0methean** [Fyrd/caniuse#3862]
Where the CSS properties `pitch` and `speech-rate` are properly supported (at least at the syllable level), the browser's TTS engine can be used as a poor man's Vocaloid to sing songs; thus, it'd be very useful to know what browsers had this functionality.

**Comment by cvrebert** [comment]
https://www.w3.org/TR/CSS22/aural.html#voice-char-props

Although it seems like https://www.w3.org/TR/css3-speech/#voice-char-props wants to supersede the CSS2.1 Aural appendix, and it renames the properties.

**Comment by Malvoz** [comment]
There is a new draft to the speech module:
**[https://drafts.csswg.org/css-speech-1/](https://drafts.csswg.org/css-speech-1/)**

Which "[is a re-work of the informative CSS2.1 Aural appendix](https://drafts.csswg.org/css-speech-1/#background)".

@cvrebert
