### ISSUE TITLE
JS object to an array

### ISSUE THREAD

**Issue by petersmax** [Fyrd/caniuse#3870]
Thought this might come in handy.

https://stackoverflow.com/a/43969192/3997521

Object.values is an ES2017 method that is not supported in Safari, IE, Node 6. – Phil Ricketts Jun 5, 2017 at 15:48

**Comment by cvrebert** [comment]
http://kangax.github.io/compat-table/es2016plus/#test-Object_static_methods

**Comment by Fyrd** [comment]
Object.values is now available at https://caniuse.com/#feat=object-values
