### ISSUE TITLE
Add AbortController 

### ISSUE THREAD

**Issue by AmitMY** [Fyrd/caniuse#3879]
Compatibility table in the bottom of: https://developer.mozilla.org/en-US/docs/Web/API/AbortController/AbortController

**Comment by cvrebert** [comment]
* https://platform-status.mozilla.org/#abort-api
* https://www.chromestatus.com/feature/5631483679080448

**Comment by wachunei** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by CharlesStover** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/AbortController#Browser_compatibility

+1

**Comment by slavikdenis** [comment]
+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=abortcontroller
