### ISSUE TITLE
Safari 11.1 Not Imported from GA

### ISSUE THREAD

**Issue by zsteiner** [Fyrd/caniuse#3880]
iOS Safari 11.1 is not included when imported from Google Analytics.

<img width="370" alt="screen shot 2017-11-27 at 10 23 06 am" src="https://user-images.githubusercontent.com/4006336/33274071-1533fbf6-d35d-11e7-9028-5e99cd849546.png">

**Comment by Fyrd** [comment]
Should be fixed now!

**Comment by zsteiner** [comment]
Confirmed fixed. Thank you!
