### ISSUE TITLE
CSS Variables do work in Opera Mini

### ISSUE THREAD

**Issue by tobireif** [Fyrd/caniuse#3883]
CSS Variables in Opera Mini are listed on

https://caniuse.com/#feat=css-variables

as red, but the do work nicely:

https://app.crossbrowsertesting.com/public/ib8393c20a124bac/livetests/9757932/snapshots/zf4425c7779642b027f7

(The page
https://tobireif.com/demos/css_pattern/css_pattern.html
doesn't use JS, but CSS Variables (pure CSS-code) do work.)

**Comment by Fyrd** [comment]
Note that "Opera Mini" as tracked on the site refers to its "extreme" data savings mode, which uses the server-based Presto rendering, as that accounts for the largest usage of Opera Mini. When using that mode all I get visiting that site is "Please use a modern browser, for example Microsoft Edge or Google Chrome".

**Comment by tobireif** [comment]
Thanks for the info.

Perhaps make that clear on the site?

**Comment by tobireif** [comment]
For anyone using https://crossbrowsertesting.com/ :

For example in the latest Opera Mini that's available on Nexus/Android:
test. then tap on the lower right "O" logo -> tap on Data Savings -> set it to Extreme, top left exit-arrow, reload the page, test.

**Comment by Fyrd** [comment]
Message for this was added some time back, here's what appears when clicking the "Opera Mini" header:
![Screen Shot 2020-05-07 at 9 01 56 PM](https://user-images.githubusercontent.com/432336/81369068-497b2700-90a6-11ea-84ee-58e87cc2ea8a.png)

**Comment by poyribn** [comment]
It’s been 6 Years since this Info was last updated.
The only Opera Mini Version listed [here](https://caniuse.com/css-variables) was released in the Year 2005
but the newest Opera Mini Version was released this Month (May 2026).
