### ISSUE TITLE
Web Share API no longer requires Origin Trial

### ISSUE THREAD

**Issue by brianchirls** [Fyrd/caniuse#3887]
caniuse [reports](https://caniuse.com/#feat=web-share) that Web Share API has "partial support" in Chrome through version 65, for only being available with an origin trial.

This is no longer correct. As of version 61, Chrome supports the feature without the origin trial. Though it still requires HTTPS and only works on Android.
Source: https://github.com/mgiuca/web-share#implementation-status

**Comment by Schweinepriester** [comment]
> As of version 61, Chrome supports the feature without the origin trial. Though it still requires HTTPS and only works on Android.

Isn't what caniuse shows correct then at the moment?

![caniuse com_](https://user-images.githubusercontent.com/2644614/33553471-368decde-d8f9-11e7-8725-3349b74f83af.png)

One could even argue Chrome for Android should be partial:

1. https://github.com/mgiuca/web-share#implementation-status
    > The API is shipping in Google Chrome 61 on Android (**images are not supported**).
2.  > Though it still requires HTTPS

**Comment by ewilligers** [comment]
This issue can be closed. Chrome for Android is correctly shown as having full support.

The new spec link is https://wicg.github.io/web-share/
 
Images support has been moved to [Level 2](https://wicg.github.io/web-share/level-2/) of the API, which can have a separate caniuse entry.

The feature requires HTTPS - see the [spec requirement](https://wicg.github.io/web-share/#api-definition) that `navigator.share` is only available in secure contexts.
