### ISSUE TITLE
Skewed statistics?

### ISSUE THREAD

**Issue by ameenross** [Fyrd/caniuse#3889]
I'm really surprised that the percentage supported for i18n has nosedived from close to 90% to 78%. Looking at the usage statistics, I have no idea how the few red blocks in the chart can possibly add up to even 10% not supported, let alone more than 20%. True, if I manually add (most of) the green blocks, I arrive at some 75%, but the red blocks combined are no more than a few (5 at most) percentage points. Where did the other ~15% go?

![image](https://user-images.githubusercontent.com/859737/33431852-33fa7ec2-d5d6-11e7-9696-ab2568796b34.png)

**Comment by Malvoz** [comment]
I would assume it is just a matter of your filter settings, a quick look at the chart shows the UC Browser for Android alone makes up for 8.1% without support.

**Comment by ameenross** [comment]
No it is not. If you check my screenshot again, you'll see that it's showing data for the Netherlands. And UC browser is only 0.44% here.

**Comment by Fyrd** [comment]
The issue was due to iOS 11.1 not being tracked in last month's regional data, so it was missing altogether. Should be fixed now!

**Comment by ameenross** [comment]
Alright, so I wasn't crazy after all :smile:

**Comment by ameenross** [comment]
I was still bothered by this. I added up every usage statistic for supported and unsupported browsers visible (using show all). I arrived at 87.xx % supported (close to the 88.85% reported) but only 4.3% unsupported. That still adds up to only about 93%. Where is the remaining 7%?

**Comment by Fyrd** [comment]
@ameenross If you hover over the total % usage you'll see the "untracked" % in the tooltip. For the Netherlands that appears to be 6.9% right now. That's pretty high since globally it's only 2%. So I looked into it a little deeper and it seems all Samsung Internet versions (possibly some others too) are being reported as 0% in the SC data that caniuse imports. You can see this in their CSV file at http://gs.statcounter.com/download/browserversion-country/

I'll contact StatCounter to see if they can resolve the issue. Thanks for reporting!

**Comment by ameenross** [comment]
Hmm, I hadn't seen that untracked bit, glad it's fixable.

However now I wonder about untracked w.r.t. the supported count. Maybe it's fairer to say `xx% supported of tracked browsers`? It's possible (seems pretty likely) the untracked browsers are not even relevant to web developers.

**Comment by Fyrd** [comment]
Agreed! I'm actually working on a feature that'll let you both be more specific about the browsers you care about together with the ability to change what the total % is to solve just that problem.

Also StatCounter got back to me and said they've corrected the numbers (they weren't including mobile in that data) so I should have that updated within a day or so.

**Comment by Fyrd** [comment]
Data appears correct now, so closing this issue.

**Comment by ameenross** [comment]
Great! Looking forward to it. It already looks much better now, thanks.

**Comment by ameenross** [comment]
Again something is off, this time for US only.

![screenshot from 2018-12-12 14-00-02](https://user-images.githubusercontent.com/859737/49871350-3fec8180-fe16-11e8-8531-7e36ecc64268.png)
