### ISSUE TITLE
add exitFullScreen API to caniuse.com

### ISSUE THREAD

**Issue by WickedDogg** [Fyrd/caniuse#3899]
I found that there is no information about `document.exitFullScreen` API for web control. Can you guys add this to caniuse.com? this is not a commonly used API, but when it comes, somebody really needs to know it's usage in browsers.

**Comment by cvrebert** [comment]
Subfeature of https://caniuse.com/#feat=fullscreen

**Comment by WickedDogg** [comment]
@cvrebert many thx
