### ISSUE TITLE
img.decode() and decoding attribute

### ISSUE THREAD

**Issue by Malvoz** [Fyrd/caniuse#3902]
Data suggestion for [`img.decode()`](https://html.spec.whatwg.org/multipage/embedded-content.html#dom-img-decode) and &lt;img&gt; [`decoding` attribute](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-decoding).

**Comment by Schweinepriester** [comment]
+1

<https://webkit.org/blog/8042/release-notes-for-safari-technology-preview-46/>

> Added support for the `decoding="sync"` or `decoding="async"` attribute on images

Chrome: https://www.chromestatus.com/feature/5637156160667648 (at least `img.decode()`, maybe the attribute too)

**Comment by Malvoz** [comment]
MS Edge suggestion: 
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/32541025-img-decoding-attribute

**Comment by jefffoxx** [comment]
Safari 11.1 release notes: https://webkit.org/blog/8216/new-webkit-features-in-safari-11-1/

**Comment by Schweinepriester** [comment]
Coming with Firefox 63: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/63

> Support for the <img> element's decoding attribute has been added (bug 1416328); see also HTMLImageElement.decoding.

- https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/decoding#Browser_compatibility
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Browser_compatibility

**Comment by djkrishnasty** [comment]
Supported in latest opera browsers as well. Tested in versions 55 and 56.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_htmlimageelement_decoding
