### ISSUE TITLE
Data not correct

### ISSUE THREAD

**Issue by IamManchanda** [Fyrd/caniuse#3904]
I think India data is showing not correctly!
https://caniuse.com/#feat=css-featurequeries

![97-87](https://user-images.githubusercontent.com/4970624/33706865-811fb30e-db5b-11e7-8045-047096d95f59.png)

I think it would be 97 not 87

PS: Indians don't use IE and my calculation says it's surely not 87 in any case

**Comment by Fyrd** [comment]
Agreed, there's something weird going on. Currently 11.4% of India's data is "untracked", a month ago it was only 5.1%. I suspect it relates to a recent change in the StatCounter data, though curiously data from other countries appears to be correct. Will let you know if I figure anything out.

**Comment by IamManchanda** [comment]
Thanks man @Fyrd ... let me know 
Feature queries are the one which I am really interested #India #PWA

**Comment by IamManchanda** [comment]
Wait this might be because of this phone, https://www.jio.com/en-in/book-jio-phone
This phone has got popular from last 1-2 due to it's very cheap price

It's using KaiOS => http://www.kaiostech.com/

**Comment by IamManchanda** [comment]
More researching made me found it's actually forked from one and only FirefoxOS

Yes that discontinued FirefoxOS ... but it's still alive
The Boot 2 Gecko community is maintaining this open source operating system now!
https://wiki.mozilla.org/B2G

WOW!

**Comment by IamManchanda** [comment]
Any updates @Fyrd

**Comment by IamManchanda** [comment]
Thanks @Fyrd for the tracked update... Really thankfull!

**Comment by inopinatus** [comment]
Seeing some incorrect browser statistics:

<img width="1281" alt="Screen Shot 2019-07-08 at 12 29 36 pm" src="https://user-images.githubusercontent.com/938619/60778900-2200b880-a17c-11e9-9c05-1d4b25ac9c26.png">

Flexbox definitely has broader applicability that 60% of browsers, and I'm certain that we have more than 0% use of iOS 12.2/12.3 in the US and Australia.

**Comment by Fyrd** [comment]
@inopinatus Thanks for pointing that out, have fixed it now! May need to reload your browser.
