### ISSUE TITLE
-fx-vbar-policy

### ISSUE THREAD

**Issue by VictorMerino** [Fyrd/caniuse#3905]

**Comment by Malvoz** [comment]
[The CSS property you are suggesting](https://docs.oracle.com/javase/9/docs/api/javafx/scene/doc-files/cssref.html#scrollpane) is specific to JavaFX. I know nothing about Java, but I'm sure this is the wrong place for it.

**Comment by Fyrd** [comment]
Yup.

**Comment by VictorMerino** [comment]
well, ok in this case. I've been using it in a non-Java webpage, and it
works at least in Chrome.

Thanks for your reply ;)

2017-12-13 6:17 GMT+01:00 Alexis Deveria <notifications@github.com>:
