### ISSUE TITLE
JavaScript Promises.prototype.finally()

### ISSUE THREAD

**Issue by inoyakaigor** [Fyrd/caniuse#3908]
TC-39: stage-4
firefox: 58
chrome: 63
opera: 50
IE: no
Edge: no
Safari: no
[MDN](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally)

**Comment by chicoxyzzy** [comment]
We have more info in [compat-table](https://github.com/kangax/compat-table/blob/gh-pages/data-esnext.js#L2691-L2701):
- it was available in Chrome 61-62 with `--js-flags="--harmony-promise-finally"` 
- It's enabled in Safari TP since version 37

Also it's Promise.**prototype**.finally 😉

**Comment by Schweinepriester** [comment]
+1

**Comment by thecodingdude** [comment]
@Fyrd this has now landed in Chrome 63 :)

**Comment by cpplearner** [comment]
+1

It has reached stage 4, and is included in the latest draft: https://tc39.github.io/ecma262/#sec-promise.prototype.finally .

https://github.com/kangax/compat-table/blob/9e23953/data-es2016plus.js#L2236-L2247

**Comment by jsilvermist** [comment]
How come this still isn't being tracked?

**Comment by inoyakaigor** [comment]
Because current method of adding data to Caniuse is too programmers-way: you must do fork repo, manual fill data and make PR. Many peoples too lazy for do it.
I think Caniuse should have web interface for that.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=promise-finally
