### ISSUE TITLE
Strange global usage percent (as seen on localStorage)

### ISSUE THREAD

**Issue by Rogach** [Fyrd/caniuse#3915]
Example: https://caniuse.com/#search=localStorage

Even if I expand the visualization using "Show all", I see only 5 red nodes with total `0.02 + 0.01 + 0 + 0.01 + 2.84 = 2.88%`. However, in top right global usage shows `95.31%` - while expected is `100% - 2.88% = 97.12%`. Where does the difference come from?

**Comment by PeterShaggyNoble** [comment]
Possibly related to #3889.

**Comment by Rogach** [comment]
@PeterShaggyNoble Yes, adding untracked 1.8% to the value gives exactly expected result. Thanks!
