### ISSUE TITLE
Feature Request: Email Client Support

### ISSUE THREAD

**Issue by acornforth** [Fyrd/caniuse#3926]
It would be very useful to use this fantastic system you've built for email clients, both in the browser and native apps, that support the various css features on the site. I realise that [caniuse.email](https://caniuse.email/) already exists, but a more complete list, including vendor specific properties (such as mso-table-lspace,  mso-table-rspace etc), would be very handy.

**Comment by Fyrd** [comment]
Sorry, no plans to include email clients.

**Comment by YakovL** [comment]
@Fyrd to you think it's worthy to add www.caniemail.com to the project readme? Looks like they are doing this rather nicely, but I haven't found them quickly, only after googling some property (base64 images, to be precise).
