### ISSUE TITLE
css- media-query max-scroll-y

### ISSUE THREAD

**Issue by kristoffernolgren** [Fyrd/caniuse#3937]
This works atleast in chrome, but I have a hard time finding any documentaiton on this anywhere.

https://codepen.io/tomhodgins/pen/beEdpZ

**Comment by cpplearner** [comment]
This appears to be a feature of [EQCSS](http://elementqueries.com/).

**Comment by kristoffernolgren** [comment]
Very helpful, thanks!

**Comment by cvrebert** [comment]
@Fyrd So, not actually a browser feature, just a JS library. Seems like this can be closed?
