### ISSUE TITLE
Box-ordinal-group:

### ISSUE THREAD

**Issue by Emptycz** [Fyrd/caniuse#3944]
Hello, can you add this CSS3 feature please? I'd like to compare to what version of browser it is supported. Default version of this is:` box-ordinal-group: [number] `and you can also modify it like this:` -webkit-box-ordinal-group: [number]` or `-moz-box-ordinal-group: [number]` etc.

What does it do? It's really simple and amazing. When you need change ordinal of HTML elements but you don't want to change the HTML code, you can use this. Basicly the element with lowest number will be loaded first, element with highest number will be loaded last (even shown, it changes positions of elements, it actually swap places between them, it doesn't matter how HTML is written).

You have to create container around as well and set this divs or elements to "display:block" too. 

Thank you,
student John

**Comment by Fyrd** [comment]
The `box-ordinal-group` property was part of the old flexbox specification and should no longer be used. It's been replaced by the new flexbox spec's `order` property, which has support tracked at https://caniuse.com/#feat=flexbox

For more information see https://developer.mozilla.org/en-US/docs/Web/CSS/box-ordinal-group
