### ISSUE TITLE
classList does not work in edge

### ISSUE THREAD

**Issue by srkchandru** [Fyrd/caniuse#3949]
Unable to add or remove class using classList in Microsoft Edge 16

**Comment by PeterShaggyNoble** [comment]
`classList.add()` and `classList.remove()` work just fine in Edge 16, as you can see [here](https://codepen.io/anon/pen/PEjevj).

**Comment by slokhorst** [comment]
Just tested in Edge 16, works fine. [screenshot](https://user-images.githubusercontent.com/8083666/34487701-c6a037f8-efd5-11e7-9856-17abbb8cd426.png)
