### ISSUE TITLE
ExtendableEvent.waitUntil()

### ISSUE THREAD

**Issue by giffeler** [Fyrd/caniuse#3981]
The extendableEvent.waitUntil() method tells the event dispatcher that work is ongoing. It can also be used to detect whether that work was successful. In service workers, waitUntil() tells the browser that work is ongoing until the promise settles, and it shouldn't terminate the service worker if it wants that work to complete.

https://developer.mozilla.org/en-US/docs/Web/API/ExtendableEvent/waitUntil

**Comment by cvrebert** [comment]
Subfeature of https://caniuse.com/#feat=serviceworkers

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_extendableevent_waituntil
