### ISSUE TITLE
Add Media Queries Ranges

### ISSUE THREAD

**Issue by jonathantneal** [Fyrd/caniuse#3984]
### Media Queries Ranges

> A syntax for defining media query ranges using ordinary mathematical comparison operators

**Example code**:
```css
@media (width < 480px) {}

@media (480px <= width < 768px) {}

@media (width >= 768px) {}
```

**Specification**: https://www.w3.org/TR/mediaqueries-4/#mq-ranges
**Resource**: PostCSS Polyfill (https://github.com/postcss/postcss-custom-media)
**Resource**: cssdb (https://jonathantneal.github.io/css-db/#mediaqueries-mq-ranges)

**Suggested ID**: `mq-ranges` or `mediaqueries-mq-ranges`

- Related to but not dependent on #1069

**Comment by cvrebert** [comment]
+1

**Comment by ethanresnick** [comment]
This would be very useful, because it's hard to polyfill the `<` and `>` operators (without the equals sign). See https://www.w3.org/TR/mediaqueries-4/#example-940c271b. Using fractional pixels, which would be the natural way to polyfill this, apparently causes some bugs: https://github.com/postcss/postcss-media-minmax/pull/14

**Comment by Malvoz** [comment]
+1

**Comment by JakoD** [comment]
Seems to be supported only by Firefox since Version 63 (tested with https://codepen.io/jakod/pen/rNaLjGq)

**Comment by Malvoz** [comment]
Chrome tracking bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=1034465

**Comment by Schweinepriester** [comment]
Available via MDN: <https://caniuse.com/mdn-css_at-rules_media_range_syntax>

**Comment by Schweinepriester** [comment]
Coming in Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1034465#c33

WebKit/Safari: https://bugs.webkit.org/show_bug.cgi?id=180234

**Comment by yisibl** [comment]
Ship in Chrome 98: https://chromiumdash.appspot.com/commit/a57094077b2b5504959e37bb192a6ac935c39920

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/css-media-range-syntax (MDN entry should be removed from search results at end of the week)
