### ISSUE TITLE
color-gamut media feature from Media Queries 4

### ISSUE THREAD

**Issue by cvrebert** [Fyrd/caniuse#3988]
* Spec: https://drafts.csswg.org/mediaqueries-4/#color-gamut
* MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/color-gamut
* Chrome: https://www.chromestatus.com/feature/5354410980933632
* Safari: ["WebKit now supports the (new to CSS Color Level 4) `color-gamut` media query."](https://webkit.org/blog/6682/improving-color-on-the-web/)

**Comment by Schweinepriester** [comment]
+1

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-css_at-rules_media_color-gamut
