### ISSUE TITLE
{row,column}-gap, applied to multicolumn, flex, and grid layouts

### ISSUE THREAD

**Issue by chharvey** [Fyrd/caniuse#3989]
[CSS Align 3](https://www.w3.org/TR/css-align-3/#column-row-gap) redefines the `row-gap` and `column-gap` properties, extending them to layouts other than multicolumn.

> # multi-column elements
> column-gap specifes the gutter between adjacent column boxes. See [CSS-MULTICOL-1] for details on how this affects the layout of multicol elements. row-gap does not currently apply.
> # flex containers
> When applied to the main axis (e.g. column-gap in a row flex container), indicates minimum spacing between items, as if a fixed-size margin were inserted between adjacent flex items in a single line.
> When applied to the cross axis (e.g. row-gap in a row flex container), indicates minimum spacing between adjacent flex lines.
> # grid containers
> The row-gap and column-gap properties, when specified on a grid container, define the gutters between grid rows and grid columns, respectively. See CSS Grid Layout 1 §10.1 Gutters: the grid-column-gap, grid-row-gap, and grid-gap properties for precise details.

Furthermore, the generic properties will override the `grid-row-gap` and `grid-column-gap` properties, respectively, which are specific to grid layout only.

And lastly, the [`gap` shorthand](https://www.w3.org/TR/css-align-3/#gap-shorthand) specifies row and column gaps at once, also overriding `grid-gap`.

**Comment by chharvey** [comment]
update: Chrome has enabled this feature in v66:
https://www.chromestatus.com/feature/4986266210795520

**Comment by jonathantneal** [comment]
Related: https://blogs.igalia.com/mrego/2018/04/04/getting-rid-of-grid-prefix-on-css-grid-layout-gutter-properties/#implementation

**Comment by benface** [comment]
`gap` properties for Flexbox are only supported in Firefox Nightly (version 63.0a1) AFAIK.

**Comment by dskoziol** [comment]
This doesn't seem to be supported yet in Chrome

**Comment by mikkorantalainen** [comment]
This needs to track gap support for flexbox, grid and multicolumn separately. It looks like no browser is going to immediately support gaps for all layouts.

**Comment by ExE-Boss** [comment]
**Mozilla&nbsp;Firefox** already [supports&nbsp;it&nbsp;in&nbsp;all&nbsp;layouts](https://developer.mozilla.org/en-US/docs/Web/CSS/gap#Browser_compatibility).

**Comment by OliverJAsh** [comment]
Chrome has renamed the CSS properties, but they do not yet work with flexbox.

Chrome's flexbox gutter support can be tracked here: https://bugs.chromium.org/p/chromium/issues/detail?id=762679.

There's no entry on https://www.chromestatus.com/ yet, so I've [filed a request](https://docs.google.com/document/d/1jrSlM4Yhae7XCJ8BuasWx71CvDEMMbSKbXwx7hoh1Co/edit?pli=1) to add it.

**Comment by OliverJAsh** [comment]
I raised a PR to add this: https://github.com/Fyrd/caniuse/pull/4961

Also, I'm trying to build some momentum on this, because it's really important but few browsers are picking it up: https://twitter.com/OliverJAsh/status/1139981721879928832. Please RT!

**Comment by Fyrd** [comment]
Support in flexbox added by @OliverJAsh now available at https://caniuse.com/#feat=flexbox-gap

**Comment by OliverJAsh** [comment]
Shall we close this now?

**Comment by chharvey** [comment]
@Fyrd , @OliverJAsh — Looks like all the cases covered in my OP are live. I’ll go ahead and close; feel free to reopen if there are any outstanding issues.
