### ISSUE TITLE
can we use semantic ui for multiple browsers and platforms??

### ISSUE THREAD

**Issue by SSheorain** [Fyrd/caniuse#4004]

**Comment by cpplearner** [comment]
This seems to be a framework that is not part of any web browser. So probably out of scope of caniuse.com?

**Comment by Fyrd** [comment]
Yeah, I'm not sure what this refers to. Can you clarify?

**Comment by SSheorain** [comment]
can i use semantic ui for linux platform

**Comment by Schweinepriester** [comment]
<https://semantic-ui.com> this?

If so, the answer would be <https://github.com/semantic-org/semantic-ui/#browser-support>.
And out of scope, maybe search result.
