### ISSUE TITLE
The current version of Opera is 49, not 48

### ISSUE THREAD

**Issue by agrimsrud** [Fyrd/caniuse#4007]
I'm not sure how you handle browser data, but the latest Opera browser with a set release date in the current Caniuse dataset is version 48. The current release of Opera for desktop is, however, version 49.

According to [the changelog](https://blogs.opera.com/desktop/changelog-for-49/#b2725.34), O49 was promoted to stable Nov 8th, 2017.

**Comment by Fyrd** [comment]
Thanks, has been fixed.
