### ISSUE TITLE
SameSite data is not accurate for Firefox

### ISSUE THREAD

**Issue by alex** [Fyrd/caniuse#4013]
https://caniuse.com/#feat=same-site-cookie-attribute

indicates that Firefox supports SameSite cookies starting with Firefox 58. This is not correct. Work on this is tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=795346 and as you can see the bug is still open.

**Comment by Fyrd** [comment]
Fixed!

**Comment by silverlyra** [comment]
caniuse is currently showing that this landed in Firefox 59, but this is also not correct. [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1286861) indicates that it's landing in 60.
