### ISSUE TITLE
Add support for Element.localName

### ISSUE THREAD

**Issue by xovel** [Fyrd/caniuse#4016]
<https://developer.mozilla.org/en-US/docs/Web/API/Element/localName>

************
I found it in this place: <https://github.com/GoogleChrome/dialog-polyfill/blob/master/dialog-polyfill.js#L49>.

**Comment by cvrebert** [comment]
This one dates all the way back to [DOM Level 2](https://www.w3.org/TR/2000/REC-DOM-Level-2-Core-20001113/core.html#ID-NodeNSLocalN).

**Comment by xovel** [comment]
Gotcha.

Anyway, this API was moved to the Element and Attr APIs according to the DOM4 standard.
