### ISSUE TITLE
IE11 doesn't actually support 'const'.

### ISSUE THREAD

**Issue by wmill** [Fyrd/caniuse#4018]
Officially it does, but there are breaking bugs. For instance, calling 'eval' on code with 'const' will throw a 'cont not defined' error.

**Comment by Ugoku** [comment]
```
const foo = 'test';
console.log(foo);
```

Results in `'foo' is undefined` in IE11. But

```
var test = function() {
    const foo = 'alert("test")';
    eval(foo);
}
test();
```

Works fine. It seems IE11 doesn't support this in the global namespace or something?

**Comment by wmill** [comment]
My bad, I was missreading minified code.
