### ISSUE TITLE
status.modern.IE seems to have changed

### ISSUE THREAD

**Issue by Eonasdan** [Fyrd/caniuse#4024]
The first time I used the link `http://status.modern.ie/fetchapi` I got a 404 error. Second attempt to redirects to `https://developer.microsoft.com/en-us/microsoft-edge/platform/status/`.

Looks like MS has done a terrible job at the redirection. Might want to redo the links as `https://developer.microsoft.com/en-us/microsoft-edge/platform/status/fetchapi`

**Comment by dstorey** [comment]
cc @molant

**Comment by molant** [comment]
Unfortunately that's the way the global redirect service works 😔
Better update all the links.

**Comment by Fyrd** [comment]
Links have now been redone and seem to be working properly. Thanks for reporting!
