### ISSUE TITLE
Suggestion: overflow(-[xy])? with 'overlay' value

### ISSUE THREAD

**Issue by sheershoff** [Fyrd/caniuse#4027]
Just found that at least Chrome and Safari of 2016 supported this undocumented value, which is not listed in W3C documents.
Not sure if support is dropped, but Chrome dev mode suggests the 'overlay' value for overflow-y.

Can't find it at the caniuse.com, please add. TY in advance )

**Comment by Malvoz** [comment]
I assume you mean the [scrollbar-gutter](https://www.w3.org/TR/css-overflow-4/#scollbar-gutter-property) property.

**Comment by sheershoff** [comment]
That's another property. Thank you.

What I meant was overflow: overlay. From what I've googled it is only supported by -Webkit browsers, is non-standardized, and allows the content to extend beneath the scrollbar.

**Comment by Malvoz** [comment]
From skimming through [this csswg draft issue](https://github.com/w3c/csswg-drafts/issues/92) it seems indeed webkit's `overflow: overlay` was standardized and the property renamed to [**`scrollbar-gutter`** as defined in CSS overflow module level 4](https://www.w3.org/TR/css-overflow-4/#scollbar-gutter-property).

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/css-overflow-overlay
