### ISSUE TITLE
Asynchronous Clipboard API (replaces document.execCommand)

### ISSUE THREAD

**Issue by mrvik** [Fyrd/caniuse#4031]
Currently it's not supported as it's experimental, but it's intended to replace the `document.execCommand` method to manage the clipboard. The return value is a Promise.
Here is the draft from [W3C](https://w3c.github.io/clipboard-apis/)
Here is the docs from the [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API)

**Comment by cvrebert** [comment]
Already present: https://caniuse.com/#feat=clipboard

**Comment by cpplearner** [comment]
I think OP is referring to the "Asynchronous Clipboard API" (https://w3c.github.io/clipboard-apis/#async-clipboard-api), which does not seem to be covered in https://caniuse.com/#feat=clipboard .

**Comment by mrvik** [comment]
@cpplearner yes, forgot the Async:sweat_smile:

**Comment by Schweinepriester** [comment]
+1

- <https://developers.google.com/web/updates/2018/03/clipboardapi>
- <https://www.chromestatus.com/feature/5861289330999296>: Chrome 66+, Opera 53+

**Comment by oliverdunk** [comment]
+1

**Comment by danielcompton** [comment]
I've made a PR for this at #4302, feedback on it is welcome there, particularly around splitting the feature support in two, one for legacy sync, and one for the new async.
