### ISSUE TITLE
Add pls pipeline-operator

### ISSUE THREAD

**Issue by chrom** [Fyrd/caniuse#4032]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Pipeline_operator

**Comment by igabesz** [comment]
Here's the TC39 proposal.
https://github.com/tc39/proposal-pipeline-operator.

First CanIUse may only support the minimal porposal, not the currently competing 2 advanced ones. Later on the advanced szintaxis may be added to CanIUse.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_operators_pipeline
