### ISSUE TITLE
CSS page property (for printing)

### ISSUE THREAD

**Issue by saturdaywalkers** [Fyrd/caniuse#4036]
hi

please add the page property (i.e.  not the same as @page)
e.g.

```
@page wide {size: A4 landscape}
table { page: wide } /* this property  */
```

cheers
andrew

**Comment by cvrebert** [comment]
i.e. https://drafts.csswg.org/css-page-3/#using-named-pages
> The `page` property is used to specify a particular type of page (called a *named page*) on which an element must be displayed.

Though they are both from the same spec.

**Comment by Schweinepriester** [comment]
Firefox/Gecko has issued Intent to prototype
* https://twitter.com/intenttoship/status/1602468085210005510
* https://groups.google.com/a/mozilla.org/g/dev-platform/c/w-ddRvzGiTI/m/aoNSGNxDBQAJ
* https://bugzilla.mozilla.org/show_bug.cgi?id=1723234

**Comment by skyfaller** [comment]
"Firefox now supports CSS named pages, allowing web pages to perform per-page layout and add page-breaks in a declarative manner when printing." https://www.mozilla.org/en-US/firefox/110.0/releasenotes/

It seems MDN has not documented this yet, but it appears they are working on it: https://github.com/mdn/content/issues/23682

**Comment by dletorey** [comment]
I have now finished the docs for this, associated PRs:
[content](https://github.com/mdn/content/pull/24485)
[BCD](https://github.com/mdn/browser-compat-data/pull/18922)

**Comment by Fyrd** [comment]
Available at https://caniuse.com/mdn-css_properties_page (thanks @dletorey!)
