### ISSUE TITLE
Feature suggestion: requestFullScreen(), exitFullScreen()

### ISSUE THREAD

**Issue by jaepage** [Fyrd/caniuse#4038]
MDN documents: 

https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen. 

https://developer.mozilla.org/en-US/docs/Web/API/Document/exitFullscreen

**Comment by cpplearner** [comment]
https://caniuse.com/#feat=fullscreen

needs search result?

**Comment by jaepage** [comment]
Thank you for providing that link. I was searching `requestfullscreen` and `exitfullscreen`, as those are the functions named by MDN's docs as linked above. Is it possible to redirect those function names' searches to the result you provided?

**Comment by Fyrd** [comment]
Added to keywords, thanks for pointing that out.
