### ISSUE TITLE
IANA time zone names in timeZone option

### ISSUE THREAD

**Issue by benmccann** [Fyrd/caniuse#4046]
I'm wondering what browsers support IANA time zone names

For more details, please see:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat#Browser_compatibility

You can test by seeing if the following causes an error:
```
new Intl.DateTimeFormat('en-US', { timeZone: 'America/Cancun' }).format()
```

**Comment by benmccann** [comment]
I found which browsers support this by expanding DateTimeFormat in the table here: http://kangax.github.io/compat-table/esintl/

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_builtins_date_tolocalestring_iana_time_zone_names
