### ISSUE TITLE
@document

### ISSUE THREAD

**Issue by fexell** [Fyrd/caniuse#4050]
Tried searching for this on the caniuse website, but didn't get any results at all, so thought I would add it as a suggestion.
(This is in reference to the CSS(3) rule (@ rule)).

Example:
`@document url("https://caniuse.com/")`

MDN: [https://developer.mozilla.org/en-US/docs/Web/CSS/@document](https://developer.mozilla.org/en-US/docs/Web/CSS/@document)

**Comment by myfonj** [comment]
This (sadly) never worked outside Firefox and even there as it seems from newly added note at the MDN page it will stop working outside the userContent.css soon :(

**Comment by fexell** [comment]
@myfonj Yeah, I know. While it's not something I would personally recommend using, it's kind of a "cool" feature - if it was usable in other browsers as well. But since it doesn't, it's better to juse stick to inlining styles if you need specific CSS rules for that underside(?).

What I do like about it, though, is that you can use regex's for the `@document` rule. Wish this would be implemented to CSS in general, example: `input[name=/(fa-)?(github)/i]` or something like that.

**Comment by Fyrd** [comment]
Duplicate of #2588
