### ISSUE TITLE
Grid is now supported in UC 12

### ISSUE THREAD

**Issue by pantharshit00** [Fyrd/caniuse#4053]
Great News. 

UC browser recently rolled out UC 12 which supports CSS Grid. Your db only shows till 11.4 might wanna add this. This will boost CSS grid supports quite a lot!

I also have read somewhere that UC 12 is based on chrome 57 or 58 it is not partial it is a full support!

**Comment by IamManchanda** [comment]
Very awesome news!

**Comment by IamManchanda** [comment]
Yes UC12 is forked from Chromium

**Comment by Fyrd** [comment]
Has now been updated! The version I saw was 11.8 which is indeed based on Chrome 57.

**Comment by Sungodragon** [comment]
Can anyone provide link for change log , it a great news .
