### ISSUE TITLE
Reflect object

### ISSUE THREAD

**Issue by relax94** [Fyrd/caniuse#4055]
Many of users start using Reflect object in projects and I think they should know about restrictions of that object between browsers. 
Can you add compatibility table?

**Comment by cvrebert** [comment]
https://kangax.github.io/compat-table/es6/#test-Reflect

**Comment by adjenks** [comment]
https://caniuse.com/#feat=mdn-javascript_builtins_reflect_get
https://caniuse.com/#feat=mdn-javascript_builtins_reflect_has
