### ISSUE TITLE
IE6 does not support TLS 1.0

### ISSUE THREAD

**Issue by matjon** [Fyrd/caniuse#4057]
Hello,
This website incorrectly claims that Internet Explorer 6 supports Transport Layer Security 1.0 [2]. This is AFAIK incorrect: TLS 1.0 was supported from Internet Explorer 7 onwards and wasn't supported in IE6[1].

[1] https://www.ssllabs.com/ssltest/viewClient.html?name=IE&version=6&platform=XP&key=100
[2] https://caniuse.com/#search=tls

**Comment by Schweinepriester** [comment]
I believe this issue has been made obsolete since <https://caniuse.com/sr_tls1> no longer shows a support table given the deprecation.
