### ISSUE TITLE
Changing the CC license

### ISSUE THREAD

**Issue by JackuB** [Fyrd/caniuse#4062]
[Creative commons advise against using CC license for software.](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) Would you be open to changing it? Could create a PR with a change to MIT or some other more common license.

(Related issue https://github.com/ben-eb/caniuse-lite/issues/14)

**Comment by Fyrd** [comment]
This repo is just data though, not software. As the link you share states, a CC license can be used for databases.

**Comment by JackuB** [comment]
True<sup>1</sup>, issue is that license then spreads (see https://github.com/ben-eb/caniuse-lite/issues/14 - and [caniuse-lite is used in plenty of other projects](https://www.npmjs.com/browse/depended/caniuse-lite)). There is a dual licensing option, but that is pretty hazy if you ask me, because you have to consider each use case and check under which license you fall. Even tho intent is clear in this case, I'm getting a hell from our legal and I have to agree with them to some extent.

So my question stands: would you be open to changing it?

---

<sup>1</sup> Not a lawyer, but not sure if you are going after this:
> The most recent version (4.0) may be used to license databases subject to copyright and, where applicable, sui generis database rights. Sui generis database rights prevent copying and reusing of substantial parts of a database
- [Can databases be released under CC licenses?](https://wiki.creativecommons.org/wiki/Data#Can_databases_be_released_under_CC_licenses.3F)

**Comment by cvrebert** [comment]
Given the large number of contributors, modifying the licensing is unlikely to be feasible.

**Comment by Fyrd** [comment]
@cvrebert makes a very good point and as mentioned the CC license seems most appropriate, so no, I don't believe it would be a good idea to change it. Also, of all the organizations that use this data so far it's never been brought up as a problem before now...so I'm a bit surprised your lawyers find there to be an issue with it.
