### ISSUE TITLE
aria-label

### ISSUE THREAD

**Issue by hasiev-elchin** [Fyrd/caniuse#4083]
Why you don't add aria-label attribute to your site - caniuse?
Thank you!

Sorry, for my English.
Yours faithfully, Elchin Khasiev from Ukraine.
hasiev.elchin98@gmail.com

**Comment by Malvoz** [comment]
`aria-label` is a [global ARIA property](https://www.w3.org/TR/wai-aria/#global_states) among the many [roles, properties & states](https://www.w3.org/TR/html-aria/#allowed-aria-roles-states-and-properties). 

Sub-feature of [WAI-ARIA](https://caniuse.com/#feat=wai-aria)?

**Comment by hasiev-elchin** [comment]
Perhaps, thanks!

**Comment by ming-codes** [comment]
We need an umbrella tracking issue to cover all of these aria attributes.

I think the right question to ask is that do we want to keep aria attribute support together on caniuse.com or as a separate website? aria attribute support works somewhat differently than what caniuse.com currently support. It's less tied to the browser and more to the specific screen reader. It's a support grid of screen reader x browsers x os

**Comment by Malvoz** [comment]
@ming-codes see the related issue https://github.com/Fyrd/caniuse/issues/4274.

https://a11ysupport.io/ is a great resource!
