### ISSUE TITLE
Picture-in-picture API

### ISSUE THREAD

**Issue by martinsuchan** [Fyrd/caniuse#4085]
This specification intends to provide APIs to allow websites to create a floating video window always on top of other windows so that users may continue consuming media while they interact with other content sites, or applications on their device.

https://github.com/WICG/picture-in-picture
https://wicg.github.io/picture-in-picture/

**Comment by BenjaminHoegh** [comment]
https://stackoverflow.com/questions/39430331/safari-picture-in-picture-custom-html5-video-controller

**Comment by Schweinepriester** [comment]
+1

<https://www.chromestatus.com/feature/5729206566649856>

**Comment by beaufortfrancois** [comment]
I think we can close this issue with https://github.com/Fyrd/caniuse/pull/4568

**Comment by Maxou44** [comment]
I updated information in #4576

**Comment by beaufortfrancois** [comment]
@Fyrd I think we can close this issue with #4568, #4576 and #4641

**Comment by Fyrd** [comment]
Yup, thanks @Maxou44 & @beaufortfrancois 
Now available at https://caniuse.com/#feat=picture-in-picture

**Comment by vitaliylag** [comment]
Firefox 71 enabled it by default but caniuse tell only Firefox 72 enabled it by default.
