### ISSUE TITLE
CSS Values and Units Module Level 4 ("CSS 4 length"):  vi, vb, ic, lh, and rlh

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#4087]
<https://developer.mozilla.org/en-US/docs/Web/CSS/length#Specifications>

> Adds the `vi`, `vb`, `ic`, `lh`, and `rlh` units.

Spec: <https://drafts.csswg.org/css-values/>

`cap` is technically part of this too, but already requested in #3287.

Maybe this could get split in sub-issues depending on if and when the browsers implement those units…

---

> `lh` 
> Equal to the computed value of the `line-height` property of the element on which it is used, converted to an absolute length.

<3

**Comment by Malvoz** [comment]
+1

**Comment by chharvey** [comment]
`vi` and `vb` have already been requested in #2649

**Comment by Schweinepriester** [comment]
<https://webkit.org/blog/10428/release-notes-for-safari-technology-preview-105/>

> Added support for `font-relative` `lh` and `rlh` unit frp, CSS Values Level 4 specification ([r259703](https://trac.webkit.org/changeset/259703/webkit/))

Chrome:

- <https://bugs.chromium.org/p/chromium/issues/detail?id=778495>
- <https://bugs.chromium.org/p/chromium/issues/detail?id=937104>

Every unit mentioned here is by now via MDN on caniuse, for example: <https://caniuse.com/#search=lh%20unit>

**Comment by chharvey** [comment]
The table on MDN can be found here:
https://developer.mozilla.org/en-US/docs/Web/CSS/length#Browser_compatibility

**Comment by Ugoku** [comment]
Bugzilla link for `lh`/`rlh`: https://bugzilla.mozilla.org/show_bug.cgi?id=1310170

**Comment by Fyrd** [comment]
Closing now these are available under https://caniuse.com/#search=css%20length
