### ISSUE TITLE
for ... of support data

### ISSUE THREAD

**Issue by xrisk** [Fyrd/caniuse#4097]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of

Even if it exists, I could not find it by either searching for "for" and "of" individually as well as "for ... of". It it does exist on the site, it's search visibility should be improved.

**Comment by Simonwep** [comment]
Is `for of` not accomplished with symbol-iterator? Wouldn't it make more sense if caniuse would add ES6 Symbols? There's already an issue #3475 which would cover it!?

**Comment by YakovL** [comment]
it is also not found by "for of loop" which is not nice

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_statements_for_of
though it would be nice if it was found searching for "for of" so will leave this open

**Comment by GPHemsley** [comment]
This appears to be working now:
https://caniuse.com/?search=for%20of

**Comment by Fyrd** [comment]
Ah yes, I did fix that.
