### ISSUE TITLE
Wrong data about Brotli Compression for Firefox

### ISSUE THREAD

**Issue by thegulshankumar** [Fyrd/caniuse#4101]
Hello,

The [Caniuse ](https://caniuse.com/#feat=brotli)shows that Firefox started supported Brotli since version 57.
![image](https://user-images.githubusercontent.com/23408127/36727713-4bbfe034-1be4-11e8-82d1-a081e799b67e.png)

However, [Firefox ](https://www.mozilla.org/en-US/firefox/44.0/releasenotes/)page says starting from 44.0
![image](https://user-images.githubusercontent.com/23408127/36727747-68d3ae3a-1be4-11e8-8432-f016e1a9a951.png)

Which one is correct?

Thanks & Regards,
Gulshan

**Comment by Malvoz** [comment]
@thegulshankumar 
If you have an implementors release note stating a feature is supported, you should trust it 🤣 

With that said, [caniuse](https://caniuse.com/#feat=brotli) does state Brotli is supported in FireFox v. 44 aswell. 
If you go to **settings** > **Usage data**, and lower the **Min. browser usage** you will see browser versions with lower usage appear.

**Comment by Fyrd** [comment]
By default caniuse shows whether or not a feature is supported for a specific set of browser versions, rather than indicate what version support started.
