### ISSUE TITLE
ifind this in an existing code am working on

### ISSUE THREAD

**Issue by realsbd** [Fyrd/caniuse#4102]
I  don't know if this code line can work, but i found it in an existing code am working on.

.paginationjs.paginationjs-big .paginationjs-go-input>input[type=text] {
    height: 36px\9;
    line-height: 36px\9;
}

**Comment by Fyrd** [comment]
Assuming you're referring to the `\9` part in the units, that's a hack to target IE6-8. See http://browserhacks.com/#hack-69e3a6b66e01ffc5d9ef77c0ff65aa1d

Since it's basically a bug, it's not something that'd be on caniuse.
