### ISSUE TITLE
[HTTP Header] Accept-CH-Lifetime

### ISSUE THREAD

**Issue by Malvoz** [Fyrd/caniuse#4121]
Data support suggestion for the [`Accept-CH-Lifetime`](http://httpwg.org/http-extensions/client-hints.html#accept-ch-lifetime) HTTP header.

Related: https://caniuse.com/#feat=client-hints-dpr-width-viewport

**Comment by Schweinepriester** [comment]
Available via MDN now: <https://caniuse.com/?search=Accept-CH-Lifetime> => <https://caniuse.com/mdn-http_headers_accept-ch-lifetime>

But also

> This experimental feature is deprecated/obsolete and should not be used.
