### ISSUE TITLE
add support for PerformanceLongTaskTiming

### ISSUE THREAD

**Issue by nathanbower** [Fyrd/caniuse#4122]
Which browsers are supporting PerformanceLongTaskTiming ?

It would be great to add this to the browser matrix.

https://w3c.github.io/longtasks/#sec-PerformanceLongTaskTiming

Cheers,
Nathan

**Comment by greglockwood** [comment]
+1

**Comment by Schweinepriester** [comment]
Available via MDN now: <https://caniuse.com/?search=PerformanceLongTaskTiming>
