### ISSUE TITLE
Add encodeURI

### ISSUE THREAD

**Issue by Vilsafur** [Fyrd/caniuse#4127]
[https://www.w3schools.com/jsref/jsref_encodeURI.asp](https://www.w3schools.com/jsref/jsref_encodeURI.asp)

**Comment by Ugoku** [comment]
`encodeURI` has been supported everywhere since 1999....

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_builtins_encodeuri
