### ISSUE TITLE
Add support for env() and the safe-area-* environment variables

### ISSUE THREAD

**Issue by ithinkihaveacat** [Fyrd/caniuse#4128]
That is, the CSS support for the variables `safe-area-inset-left`, `safe-area-inset-right`, `safe-area-inset-top`, and `safe-area-inset-bottom` that support notches/cutouts/safe areas as described at https://github.com/w3c/csswg-drafts/pull/1819 ([more info](https://webkit.org/blog/7929/designing-websites-for-iphone-x/)).

**Comment by Malvoz** [comment]
I believe `env()` is to be defined in CSS Variables Level 2, but isn't drafted yet. 

The `safe-area-inset-*` properties belongs in CSS Round Display as [suggested here](https://github.com/Fyrd/caniuse/issues/4088).

**Comment by kiding** [comment]
Possible duplicate of #3787.
