### ISSUE TITLE
MDN/browser-compat-data interoperability

### ISSUE THREAD

**Issue by myfonj** [Fyrd/caniuse#4136]
From distant point of view Caniuse and BCD [1] seems quite similar.

Cross-linking mdn/browser-compat-data#1192 for reference for other fellow devs lurking around. 

Statement about differences in [comment by BCD maintainer](https://github.com/mdn/browser-compat-data/issues/1192#issuecomment-371099386).

[1] ~Mozilla Developer ~Center~ _Network_~ _MDN_ Browser Compatibility Data

**Comment by Elchi3** [comment]
Both projects are collaborating now: https://hacks.mozilla.org/2019/09/caniuse-and-mdn-compat-data-collaboration/ :tada: 

If anyone's interested in data structures, I have compared both here: https://github.com/mdn/browser-compat-data/issues/4051

**Comment by knksmith57** [comment]
this is really awesome! huge congratulations on the collab! 🎉 👏 💯

**Comment by Fyrd** [comment]
Seems safe to close this issue now. 🎉
