### ISSUE TITLE
Safari on iOS supports EME

### ISSUE THREAD

**Issue by jjauch** [Fyrd/caniuse#4147]
Safari supports Encrypted Media Extensions (EME) as of iOS 11.2.

Currently caniuse site states that EME is not supported.

**Comment by xlc** [comment]
EME is supported in iOS Safari 11.1. Can someone update it?

https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_11_1.html

**Comment by awakenedguy** [comment]
Indeed, Encrypted Media Extensions are now supported on iOS. It is been longtime actually. Why didn't you still update it? Currently it reflects false info:
https://caniuse.com/#feat=eme
