### ISSUE TITLE
[CSS] suggest feature to be added: max-inline-size

### ISSUE THREAD

**Issue by undefined-bob** [Fyrd/caniuse#4148]
Hi,
I would just suggest to add the CSS feature "max-inline-size" to caniuse.com

thanks for your time
kind regards, Bob

**Comment by cvrebert** [comment]
* https://developer.mozilla.org/en-US/docs/Web/CSS/max-inline-size

This should theoretically fall under https://caniuse.com/#feat=css-logical-props

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-css_properties_max-inline-size
