### ISSUE TITLE
Add controlsList property

### ISSUE THREAD

**Issue by CrisMVP3200** [Fyrd/caniuse#4150]
I noted there's no entry for the controlsList property. It would be nice if this property is added. 

[https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/controlsList](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/controlsList)

**Comment by Malvoz** [comment]
@Fyrd Do you want to close this since there's MDN data available?
https://caniuse.com/#feat=mdn-api_htmlmediaelement_controlslist

**Comment by Fyrd** [comment]
Yup!
