### ISSUE TITLE
TLS 1.3 in Firefox 52 ESR

### ISSUE THREAD

**Issue by Forkest** [Fyrd/caniuse#4151]
TLS 1.3 is not enabled by default (left behind a flag) in Firefox 52 ESR. See https://groups.google.com/forum/#!topic/mozilla.dev.platform/sfeqeMkyxCI for the reference.

Currently the site shows it as "Supported", this is true for the 52 version, but not for the ESR release channel. Most of current 52 users are on ESR (dropped XP and Vista users were moved there), so the ESR feature status feels more important. I'm not sure what would be the site policy for this situation.

**Comment by Fyrd** [comment]
Feature has been updated with this information (as long as Firefox 52 is visible)

**Comment by Forkest** [comment]
There's a typo in the note, it says 53 instead of 52.
