### ISSUE TITLE
TLS 1.3 support per draft version / final spec

### ISSUE THREAD

**Issue by Majkl578** [Fyrd/caniuse#4153]
Hi, TLS 1.3 is currently shown as aggregate result. This doesn't make sense at all since browsers and servers implement different draft versions - those are incompatible with each other (i.e. nginx implements draft 19 while Firefox implements draft 18 -> cannot be used).

Also note that TLS 1.3 has been approved by IETF as a draft 28: 
https://www.bleepingcomputer.com/news/security/ietf-approves-tls-13-as-internet-standard/

**Comment by dubek** [comment]
PR #4432 updates the TLS 1.3 spec to the official RFC.

**Comment by daytonlowell** [comment]
I think this can be closed now that TLS 1.3 is final?
