### ISSUE TITLE
SVG SMIL Chrome deprecation is "suspended" since 2016-08-17

### ISSUE THREAD

**Issue by myfonj** [Fyrd/caniuse#4167]
https://github.com/Fyrd/caniuse/blob/a4c14a75ba8a2588d46e463a7031f86ac611ac78/features-json/svg-smil.json#L330

It is mentioned at (already referenced) [MDN page](https://developer.mozilla.org/en-US/docs/Web/SVG/SVG_animation_with_SMIL):

> Although Chrome 45 deprecated SMIL in favor of CSS animations and Web animations, the Chrome developers have since [suspended](https://groups.google.com/a/chromium.org/d/msg/blink-dev/5o0yiO440LM/YGEJBsjUAwAJ) that deprecation.

**Comment by Fyrd** [comment]
Thanks, has been updated.
