### ISSUE TITLE
::shadow

### ISSUE THREAD

**Issue by oswee** [Fyrd/caniuse#4173]
Please include this pseudo-element selector to select Shadow DOM

**Comment by cvrebert** [comment]
https://www.w3.org/TR/2014/WD-css-scoping-1-20140403/#shadow-pseudoelement

**Comment by cvrebert** [comment]
Seems to have been removed(/replaced?) in the current spec in https://github.com/w3c/csswg-drafts/commit/9617cdd5e117b4674e89b799fa437441f7fd80e4

**Comment by Fyrd** [comment]
Closing since this was removed, https://caniuse.com/#feat=mdn-css_selectors_part is an alternative
