### ISSUE TITLE
Browser Set using browserl.ist

### ISSUE THREAD

**Issue by patelmitul** [Fyrd/caniuse#4176]
Allow us to define browser set using browserl.ist instead of painstaking check boxes.

**Comment by Fyrd** [comment]
This is already possible. On the browser set screen click the "Import / export" button and you can import browserslist data. Let me know if you have any problems with it.

**Comment by patelmitul** [comment]
I just tried it. Well it does not produce the same result as https://browserl.ist In my case I am using lots of NOT queries
Here is my list:
>\>= 0.05%
last 2 versions
not ie <= 9
not chrome <= 47
not firefox <= 43
not android <= 4.1
edge >= 12
not bb <= 9
not safari <= 8
not ios_saf <= 8.9
not opera <= 35

Which produces: [CanIUse](https://caniuse.com/?browserset=%3E%3D%200.05%25%2Clast%202%20versions%2Cnot%20last%203%20ie%20versions%2Clast%203%20edge%20versions%2Cnot%20last%203%20firefox%20versions%2Cnot%20last%203%20chrome%20versions%2Cnot%20last%203%20safari%20versions%2Cnot%20last%203%20opera%20versions%2Cnot%20last%203%20ios_saf%20versions%2Cnot%20last%203%20android%20versions%2Cnot%20last%203%20bb%20versions)


And here what it should be: [BrowserL.ist](http://browserl.ist/?q=%3E%3D+0.05%25%2C+last+2+versions%2C+not+ie+%3C%3D+9%2C+not+chrome+%3C%3D+47%2C+not+firefox+%3C%3D+43%2C+not+android+%3C%3D+4.1%2C+edge+%3E%3D+12%2C+not+bb+%3C%3D+9%2C+not+safari+%3C%3D+8%2C+not+ios_saf+%3C%3D+8.9%2C+not+opera+%3C%3D+35)

It produces complete opposite of what I want. For example my query says not ie <=9 but the result is that it only uses ie < 9

I wish the functionality should be:
I can copy paste the parameters from browserl.ist web site's main input box OR the link generated by the site and CanIUse produce the same result as browser list.

**Comment by Fyrd** [comment]
Ah yes, originally I had disabled "not" support because my code had some issues with it...just spent some time working all that out and I believe it should be mostly working as expected now. Can you try again?

One issue that I haven't fixed yet is the "Error 406" one...may take a bit longer to figure out.

**Comment by Fyrd** [comment]
The "Error 406" issue has now been fixed, as well as support for "not" queries, so closing this issue.
