### ISSUE TITLE
WebView does support APNG

### ISSUE THREAD

**Issue by rctgamer3** [Fyrd/caniuse#4177]
https://caniuse.com/#feat=apng reports that Android WebView doesn't support APNG.

I just tested it with a couple of APNG images in WebView opened by a third-party app, and they all display just fine.

"Android 5-6-.x WebView" should be supporting it but is currently red. Can anyone verify?

STR:
![](https://user-images.githubusercontent.com/607379/38487741-7d94ad84-3be1-11e8-9513-3c7a0251d089.png)

**Comment by Fyrd** [comment]
Confirmed & updated. Thanks!

**Comment by rctgamer3** [comment]
Aaand it's back to red.
