### ISSUE TITLE
History operations in Chrome and Firefox

### ISSUE THREAD

**Issue by kogutenko** [Fyrd/caniuse#4180]
Why `history.*` operations in Chrome and Firefox aren't "partially supported"? [Link](https://caniuse.com/#search=history)
It seems, there are some [issues](https://stackoverflow.com/questions/13955520/page-title-is-not-changed-by-history-pushstate) with them in Chrome and Firefox. In particular, second parameter of `history.pushState()` and `history.replaceState()` not records to the history.

**Comment by cvrebert** [comment]
Ignoring the title is allowed by the spec. Might be worth a numbered support note though.

https://html.spec.whatwg.org/multipage/#the-history-interface:current-entry-13

> Note: The title is **purely advisory**. User agents *might* use the title in the user interface.

(Emphases added)

**Comment by kogutenko** [comment]
@cvrebert, you're right. Sorry to bother.
