### ISSUE TITLE
UC Browser only shows 11.8

### ISSUE THREAD

**Issue by realalexhomer** [Fyrd/caniuse#4193]
Hi, sorry if this is the wrong place to ask this but it I'm only seeing data for one UC Browser version, 11.8, and can't figure out why this is.

Is there anywhere I can find caniuse data for older or newer versions? It would be a massive help if you could point me in the right direction.

Thanks.

**Comment by Fyrd** [comment]
Similar to other mobile browsers versions, right now only the latest version of UC browser is tracked on caniuse.
