### ISSUE TITLE
add for...of loops

### ISSUE THREAD

**Issue by charsi** [Fyrd/caniuse#4194]
Can't see a page for [for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) loops. 

These are new in ES6. Firefox supported them [early](https://hacks.mozilla.org/2015/04/es6-in-depth-iterators-and-the-for-of-loop/). Would be useful to know which browsers have this feature now.

**Comment by cvrebert** [comment]
Duplicate of #4097

**Comment by YakovL** [comment]
why not close the duplicate?

**Comment by vojta001** [comment]
This is implemented as far as I can tell: https://caniuse.com/?search=for%20of
