### ISSUE TITLE
caniuse.com only supports TLS 1.0, unsafe RC4, only supports weak cipher suites

### ISSUE THREAD

**Issue by ATI-RV350** [Fyrd/caniuse#4198]
The Can I Use webserver only support TLS 1.0, allows RC4 cipher suites, and only supports extremely weak cipher suites.

TLS 1.0 and even 1.1 are being deprecated at this point, and RC4 cipher suites have been known unsafe for years and the IETF themselves proposed their prohitibition in 2015.

Please at the minimum support TLS 1.2/1.1 and disable RC4 suites.

Recommend only allowing TLS 1.2, and AEAD cipher suites.

**Comment by franklinyu** [comment]
Any news? Anything we can help?

**Comment by 304NotModified** [comment]
Still C rating unfortunately   

Summary: 

![image](https://user-images.githubusercontent.com/5808377/44114625-0c261ca2-a00c-11e8-913d-9da3a83cc415.png)

![image](https://user-images.githubusercontent.com/5808377/44114669-2cb66c88-a00c-11e8-8b05-fd4adaf4f85e.png)

![image](https://user-images.githubusercontent.com/5808377/44114689-371acaac-a00c-11e8-99c9-678ca3064b08.png)

**Comment by kroeckx** [comment]
Any update on this? There really is no excuse not to have TLS 1.2 enabled at this point. There is already an IETF draft to disable TLS 1.0. Please enable TLS 1.2.

**Comment by dbaron** [comment]
Four browser engines announced a schedule for removal of TLS 1.0 and 1.1:
https://blog.mozilla.org/security/2018/10/15/removing-old-versions-of-tls/
https://security.googleblog.com/2018/10/modernizing-transport-security.html
https://blogs.windows.com/msedgedev/2018/10/15/modernizing-tls-edge-ie11/
https://webkit.org/blog/8462/deprecation-of-legacy-tls-1-0-and-1-1-versions/

**Comment by 304NotModified** [comment]
bump @Fyrd

**Comment by Fyrd** [comment]
Working on it. Hope to have it updated by the end of the month.

**Comment by Fyrd** [comment]
Alright folks, TLS 1.2 supported and up to an "A" on SSL Labs now ☺️

**Comment by franklinyu** [comment]
Can confirm.

- [x] 4096-bit certificate (default of certbot is 2048-bit)
- [x] 4096-bit Diffie-Hellman (anything equal to or higher than 2048 is good)
- [x] No RSA as key-exchange algorithm, so all ciphers support Perfect Forward Secrecy.
- [x] EDCHE (to save computation for both browser and server)
- [x] No TLS 1.0 (PCI Compliance)

This is outstanding.

**Comment by 304NotModified** [comment]
Funny, SSL labs crashes on me. Not sure if this is an issue of SSL labs:

try 1:

![image](https://user-images.githubusercontent.com/5808377/47351055-7e3baf00-d6b7-11e8-8350-0aaf1356c875.png)


try 2:

![image](https://user-images.githubusercontent.com/5808377/47351065-83006300-d6b7-11e8-8c87-46e7b493aa1e.png)
