### ISSUE TITLE
Custom Elements

### ISSUE THREAD

**Issue by rg-net** [Fyrd/caniuse#4200]
We are missing `window.customElements` which is an instance of the `CustomElementRegistry` object. This is also colloquially referred to as _Web Components_ or  _Custom Tags_.

customElements.define is used to define custom tag elements in Chrome and Webkit now. Firefox Support is in Beta/Alpha. Edge development is on the roadmap as high priority.

**Comment by cpplearner** [comment]
https://caniuse.com/#feat=custom-elementsv1
