### ISSUE TITLE
badInput

### ISSUE THREAD

**Issue by o-t-w** [Fyrd/caniuse#4202]
The read-only property ValidityState.badInput indicates if the user has provided input that the browser is unable to convert

MDN has a bunch of question marks for this in its browser support table. 
https://developer.mozilla.org/en-US/docs/Web/API/ValidityState/badInput

**Comment by cvrebert** [comment]
This falls under https://caniuse.com/#feat=constraint-validation
Perhaps more search terms should be added to that entry.

**Comment by Fyrd** [comment]
Added search results to https://caniuse.com/#feat=constraint-validation
