### ISSUE TITLE
not found popper

### ISSUE THREAD

**Issue by ishwy** [Fyrd/caniuse#4216]
popper

**Comment by cpplearner** [comment]
I have never heard of that. Is it a library or framework that is not part of any web browser (and is thus out of scope for caniuse)?

**Comment by Ugoku** [comment]
Probably https://popper.js.org/

**Comment by ishwy** [comment]
Probably https://popper.js.org/ +1 @cpplearner

**Comment by Fyrd** [comment]
@cpplearner is correct, libraries and frameworks aren't tracked on caniuse.
