### ISSUE TITLE
Safari reference link for Console is dead

### ISSUE THREAD

**Issue by thw0rted** [Fyrd/caniuse#4220]
I tried to view the [feature page for the browser console](https://caniuse.com/#feat=console-basic) and under Resources, it links to [this missing page about Safari](https://developer.apple.com/library/content/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/Console/Console.html).

Also, would it make sense to file an issue for separate feature entries for newer methods on the Console API (dir/dirxml, table, etc)?  For some reason the performance-specific methods got their own first class entry -- should each method or logical grouping of methods have a different support entry?

**Comment by Fyrd** [comment]
Have removed the Safari link, thanks.

Yeah, if support is different for the other methods they should have their own tables, feel free to create new issues if they don't exist yet.
