### ISSUE TITLE
Support Audio Worklet

### ISSUE THREAD

**Issue by cristiano-belloni** [Fyrd/caniuse#4222]
Part of the [Web Audio API](https://webaudio.github.io/web-audio-api/#AudioWorklet).

Currently supported in [Chrome 64/65 with a flag and Chrome 66 by default](https://developers.google.com/web/updates/2017/12/audio-worklet).

Chrome 64 / 65 don't expose an `onProcessorError` function on the AudioWorkletNode.

**Comment by BillyWM** [comment]
Duplicate of #4178 just FYI

**Comment by cristiano-belloni** [comment]
@BillyWM thanks, closing.
