### ISSUE TITLE
Support CSS property: speak

### ISSUE THREAD

**Issue by tommai78101** [Fyrd/caniuse#4223]
I've seen others mentioning how CSS property, speak, is used for voice speakers and TTS-related applications.

But I haven't been able to see this on caniuse.com. Can this be added?

**Comment by cvrebert** [comment]
Duplicate of #1240
https://www.w3.org/TR/css3-speech/#speaking-props-speak

**Comment by tommai78101** [comment]
Thanks, closing this issue.
