### ISSUE TITLE
Support Web Authentication (WebAuthN)

### ISSUE THREAD

**Issue by dbaron** [Fyrd/caniuse#4224]
[Web Authentication](https://w3c.github.io/webauthn/) is the W3C-standardized successor to FIDO U2F, which is [already listed](https://caniuse.com/#feat=u2f) in caniuse.  It [will be supported by Firefox 60](https://hacks.mozilla.org/2018/01/using-hardware-token-based-2fa-with-the-webauthn-api/) and [will be supported in Chrome 67](https://www.chromestatus.com/feature/5669923372138496) (at least assuming these sources are still accurate).

Given that it's the successor to an already-included feature, and is likely to soon be more widely supported than that feature, it seems worth listing.

**Comment by cvrebert** [comment]
Duplicate of #2423.

**Comment by dbaron** [comment]
Right.  Not sure why github issue search didn't find that yesterday...
