### ISSUE TITLE
Add text-decoration-skip-ink

### ISSUE THREAD

**Issue by bronzehedwick** [Fyrd/caniuse#4232]
CSS property that controls how under/overlines are drawn around glyphs. Can be used to break the lin e so it doesn't run through lower elements of the glyph, such at the bottom of a "j".

Spec: https://drafts.csswg.org/css-text-decor-4/#text-decoration-skip-ink-property
Chrome bug: https://www.chromestatus.com/feature/5631679087509504
MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip-ink

Safari supports this property by default and via a `-webkit` prefix. See: https://css-tricks.com/almanac/properties/t/text-decoration-skip/#article-header-id-1

**Comment by cpplearner** [comment]
Duplicate of #3979

**Comment by bronzehedwick** [comment]
Oops, my bad. Thanks.
