### ISSUE TITLE
add ::theme and ::part selectors

### ISSUE THREAD

**Issue by zackarychapple** [Fyrd/caniuse#4234]
It would be awesome to know the support for these. 

https://css-tricks.com/part-theme-explainer/

**Comment by intcreator** [comment]
I'm looking forward to this as well, although it might be a bit before we need the tables.  I don't think they're implemented anywhere yet since [it's still a draft](https://tabatkins.github.io/specs/css-shadow-parts/).

**Comment by LeeBurton** [comment]
> I'm looking forward to this as well, although it might be a bit before we need the tables. I don't think they're implemented anywhere yet since [it's still a draft](https://tabatkins.github.io/specs/css-shadow-parts/).

That link is now deprecated and replaced by this one:

    https://drafts.csswg.org/css-shadow-parts/

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-css_selectors_part
