### ISSUE TITLE
Payment Request API status is Candidate Recommendation

### ISSUE THREAD

**Issue by ascott18** [Fyrd/caniuse#4241]
Looks like this was already changed once before (https://github.com/Fyrd/caniuse/commit/3a913554f866d30b6a7fb86ce5583f877fb87e74#diff-1dac94777b6f163d29aa447b79105f5f), but was reverted by the periodic data imports. Is the expected turnaround time described at https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md#how-it-works expected to be nearly a month, or is there something else going on here?

**Comment by Fyrd** [comment]
Every once in a while I do things in the wrong order and merged changes get overridden, that's what happened there. Thanks for pointing it out, have just ensured all reverts there got undone, including the Payment Request API status.
