### ISSUE TITLE
input type="url" usability not shown

### ISSUE THREAD

**Issue by SanjayKtm** [Fyrd/caniuse#4247]
input type="url" is a supported feature of HTML5 but its usability feature is not available
https://caniuse.com/#search=input%20type%3D%22url%22
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url

**Comment by Fyrd** [comment]
It's found at https://caniuse.com/#feat=input-email-tel-url , have added `input type="url"` as search keyword.
