### ISSUE TITLE
Suggestion Features: Code scanner

### ISSUE THREAD

**Issue by BenjaminHoegh** [Fyrd/caniuse#4248]
### Suggestion

Could be nice and useful to have a file upload/text field to paste/upload your file to make it scan your code and then return what browser you support and what versions, and maybe even come with a suggestion to make even better support for more browsers/versions

**Comment by Fyrd** [comment]
Something like this already exists (for CSS) at https://doiuse.herokuapp.com/

No plans on adding such a feature to caniuse.com though.
