### ISSUE TITLE
add Element.scroll、scrollTo、scrollBy methods support data.

### ISSUE THREAD

**Issue by LeuisKen** [Fyrd/caniuse#4251]
According to https://www.w3.org/TR/cssom-view-1/#extension-to-the-element-interface , these methods has added to the `Element.prototype`. I test these methods on Chrome 66 which support these methods and Chrome 48 which not. So I think it will be nice if can i use provides these data.

**Comment by The-Code-Monkey** [comment]
Can this be added please need to find out if this works in ie

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=element-scroll-methods
