### ISSUE TITLE
Update Firefox for Android version and info

### ISSUE THREAD

**Issue by andreasbovens** [Fyrd/caniuse#4253]
Firefox for Android is now at version 60, while the version and info included on caniuse is still stuck on 57.

**Comment by HM100** [comment]
WebView Android version is also stuck at version 62 and Android Opera also stuck at version 37

**Comment by Fyrd** [comment]
Firefox for Android has now been updated, will get on the others soon.

**Comment by HM100** [comment]
Desktop Opera is also stuck at V50 where it should be 53

**Comment by cpeterso** [comment]
@Fyrd, are the new Firefox 60 for Android results live on caniuse.com? Neither Firefox for Android or desktop support the Battery Status API, but the [browser comparison table](https://caniuse.com/#compare=firefox+60,and_ff+60,and_chr+66,chrome+66) says that Firefox for Android does support it.

**Comment by Fyrd** [comment]
@cpeterso Yeah, looks like that didn't get updated when support was removed. Has been fixed now, thanks for pointing it out.

**Comment by Fyrd** [comment]
All versions should be up to date now.
