### ISSUE TITLE
add ime-mode

### ISSUE THREAD

**Issue by mfkvfn** [Fyrd/caniuse#4254]
add the "ime-mode" css feature

**Comment by Malvoz** [comment]
I don't think caniuse actively adds deprecated features (?)

> User agents should not support the ime-mode property.
> 
> Authors must not use the ime-mode property.

_https://www.w3.org/TR/css-ui/#input-method-editor_

**Comment by Fyrd** [comment]
Available via MDN BCD data: https://caniuse.com/mdn-css_properties_ime-mode
