### ISSUE TITLE
DOMParser.parseFromString is supported since Chrome 31, not Chrome 30

### ISSUE THREAD

**Issue by edg2s** [Fyrd/caniuse#4267]
Call
```javascript
new DOMParser().parseFromString(
  '<!doctype html><html><head></head><body><p></p></body></html>',
  'text/html'
);
```
in Chrome 30 and 31. According to the table, parseFromString support was added in 30, but it returns null, instead of a document object, which is returned in 31.

**Comment by Fyrd** [comment]
Confirmed & fixed, thanks!
