### ISSUE TITLE
Web Manifest support is incorrect

### ISSUE THREAD

**Issue by andreasbovens** [Fyrd/caniuse#4268]
https://caniuse.com/#feat=web-app-manifest lists that Firefox for Android doesn't support Web Manifest: that's incorrect. It does support web manifest since version 58 (through a badging mechanism).

However, that brings up the bigger question why Opera, Chrome, Safari are all listed as supporting Web Manifest: if I'm correct, Web Manifest is thus far only supported in the mobile versions of these browsers, and this should be reflected as such.

**Comment by Fyrd** [comment]
Good questions. Looks like I didn't re-test support for Firefox for Android when updating. Chrome & Opera support was added initially with #2867 presumably based on the chrome status info at https://www.chromestatus.com/feature/6488656873259008 which suggests it's on desktop too, though yeah I don't see how. Safari support was set with #4029 based on early ambiguous changelog description, but I don't see it there either.

Have updated the data now based on these findings. Thanks!
