### ISSUE TITLE
CSS3 Variable

### ISSUE THREAD

**Issue by anyotherway** [Fyrd/caniuse#4269]
https://www.w3schools.com/cssref/css_functions.asp
https://www.w3schools.com/css/css3_variables.asp
https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables
https://caniuse.com/#search=var _[opens topic "Variable Fonts" with 7 tangled isues]_

**CSS3 Variable provides a very useful styling syntax**, or rather, allows very easy construction of useful style properties and values. W3 Schools clearly defines 'variable' as 'custom property' and as 'value. In example below, I fail to see how the var '--function' is not a 'property', and how its 'var(--value)' is not also a value. So 'var()' should be included at caniuse.com as CSS code. Perhaps, with a subtopic for '--value'. At caniuse.com both 'var()' and '--value' are not present, and should be added.

Example style sheet with assigned _named colors_. W3Schools.com writes, "Variables in CSS should be declared within a CSS selector that defines its scope. For a global scope you can use either the :root or the body selector.
The variable name must begin with two dashes (--) and is case sensitive!
The syntax of the var() function is as follows..." 
Here we have slightly adapted w3schools.com somewhat circular scope (likely adopted from MDN), to demonstrate a popular design interest, forward-motion color naming (inspired by adapting [Chirac Mehta](http://chir.ag/projects/name-that-color/#FF8000) to noscript) :

`:root { --greenelm: #009900; --mohican: #cc0099; --sky: #0099ff; }`
`h1 { color: var(--greenelm); } p { color: var(--mohican); } nav { color: var(--sky); }`
`<h1> Hello! </h1> <p> Wake UP! </p> <nav> You are lost :-( </nav>`

Presently, caniuse.com search lists "**var**" as "variable fonts", _unrelated_. CSS3 Varible as linked in W3Schools.com and Mozilla.com works fine in Safari and FireFox, to mention a few that support **_var(--)_**, or **var()**. However caniuse will place it, eventually. 

But how to add "**var**" to the currrent Can I Use search schema. As noted above, search term 'var' opens only 'font variable', with 7 ? or more tangled issues. Perhaps W3 Schools term **var()** can replace or compliment the current caniuse.com search result, as that would encompass a more useful search result. That 'font variable' hole needs to stop hogging the search index for **var**. CSS Variables could adopt W3Schools var() syntax as a search index and topic. Branch out from there as best fit. Onto other uses for CSS functions that are here to stay, supported by most or all, and presently lacking at caniuse.com 2018, May.

**Comment by Fyrd** [comment]
If you scroll down on https://caniuse.com/#search=var you'll noticed CSS Variables is the second result (of 14 results). I think that's reasonable. 

Or just search for CSS variables directly: https://caniuse.com/#search=css%20variables
The feature-specific link is https://caniuse.com/#feat=css-variables, FYI

**Comment by anyotherway** [comment]
Hi caniuse support, Alexis
Safari search for “CSS Variables” site:caniuse.com gets nothing. I was incredulous, ot fding anything but font variable. So problem is Safari and caniuse.com incompatible? 

CSS variables needs more focus. Unless you market only microsoft-chrome and openly attack deny any other Internet access. That’s okay, if special needs is your thing. 

IE issues (3) are MINOR. 

Please add “var()" to formal page topics, not page bottom trash, inaccessible to Safari and Google. LOL!
Respectfully,
Mark Stewart

**Comment by anyotherway** [comment]
ERRATA

On 2018 May 21, at 21:45, Mark <notifications@github.com> wrote:

Hi caniuse support, Alexis
Safari search for “CSS Variables” site:caniuse.com gets nothing. I was incredulous, ot fding anything but font variable. So problem is Safari and caniuse.com incompatible? 

CSS variables needs more focus. Unless you market only microsoft-chrome and openly attack deny any other Internet access. That’s okay, if special needs is your thing. 

IE issues (3) are MINOR. 

Please add “var()" to formal page topics, not UNLINKED page bottom trash, inaccessible to Safari and Google. LOL!
Respectfully,
Mark Stewart
