### ISSUE TITLE
Array.prototype.findIndex

### ISSUE THREAD

**Issue by idododu** [Fyrd/caniuse#4271]
[MDN - Array.prototype.findIndex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex)
The findIndex() method returns the index of the first element in the array that satisfies the provided testing function. Otherwise -1 is returned.

![image](https://user-images.githubusercontent.com/7663884/40347398-bb29cc8e-5dd2-11e8-996d-e84404e4efc3.png)

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=array-find-index
