### ISSUE TITLE
Is Safari having issues with caniuse?

### ISSUE THREAD

**Issue by ghost** [Fyrd/caniuse#4272]
I got really confused looking for CSS Variables. Search for 'CSS Variables' found nothing. 'var' only "Variable Fonts" topic with no scroll then increasing items.

Fyrd got interested in my misplaced wailing. Alexis sent me a link and after that the issue went away.

Fresh macOS install here, 8-core 64 macPro Airport on Shaw Cable at 180mbps. 

Thread is here (edited 1,000 times in an hour as things devolved).
https://github.com/Fyrd/caniuse/issues/4269#issuecomment-390862029

**Comment by Fyrd** [comment]
Works for me...what version of Safari are you using?
![screen shot 2018-05-23 at 9 28 15 pm](https://user-images.githubusercontent.com/432336/40464474-522ee030-5ed0-11e8-9a9d-1a615423ed88.png)
