### ISSUE TITLE
CSS3 var() Please

### ISSUE THREAD

**Issue by anyotherway** [Fyrd/caniuse#4273]
Fyrd advised me elsewhere that unlinked sub-topic under "variable Fonts (unrelated) was all that caniuse is offering for now.

Please prioritize var() as search-indexed main topic in caniuse. In that respect, I hope caniuse will fix to apparent incompatibility with Safari and Firefox too.

https://www.w3schools.com/cssref/css_functions.asp
https://www.w3schools.com/css/css3_variables.asp
https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables
https://caniuse.com/#search=var 
[caniuse seems to need some major housekeeping... Hope that goes well :-)]

**Comment by Ugoku** [comment]
What are you talking about? If you search for "var", CSS variables is the second result in the list. Tested it here, works fine in both Safari and Firefox.

Also, searching on google [works just fine](https://www.google.nl/search?q=css+variables+site%3Acaniuse.com&oq=css+variables+site%3Acaniuse.com&aqs=chrome..69i57.4951j0j4&sourceid=chrome&ie=UTF-8)

**Comment by myfonj** [comment]
I believe OP was talking about the case one enters exact **`var()`** query:
https://caniuse.com/#search=var()
what, at this point, shows
```
» $$('h3.feature-title').map(e=>e.innerHTML).join(', ')
« "Variable fonts, CSS @apply rule, URL API, Element.scrollIntoViewIfNeeded(), let, Summary"
```
i.e. **not** the [CSS Variables (Custom Properties)](https://caniuse.com/#feat=css-variables).

**Comment by Fyrd** [comment]
Added `var()` to keywords so now https://caniuse.com/#search=var() gives the expected result.
