### ISSUE TITLE
[bug] -webkit-text-stroke for ::first-letter

### ISSUE THREAD

**Issue by strarsis** [Fyrd/caniuse#4276]
`-webkit-text-stroke` doesn't work in `::first-letter` selector/pseudo-element, see this test case: https://codepen.io/strarsis/pen/aGrOdJ

As a workaround I am currently using [sass-text-stroke](https://github.com/hudochenkov/sass-text-stroke) which visually emulates the effect using text shadow.

**Comment by HM100** [comment]
Which browser are you using. I'm using MS Edge 17 and it works on ::first-letter selector

**Comment by strarsis** [comment]
@HM100: For me the pen works correctly in Firefox (recent and dev edition) and 
Microsoft Edge, but not in Chrome and Internet Explorer.

**Comment by HM100** [comment]
IE at first place doesn't support `-webkit-text-stroke` and that's why I didn't included it in my past comment. Note that Opera is also chromium so `-webkit-text-stroke` indeed doesn't work on `::first-letter`

**Comment by Fyrd** [comment]
Added as known issue at https://caniuse.com/#search=text-stroke
