### ISSUE TITLE
Web App Manifest - not in Chrome?

### ISSUE THREAD

**Issue by branditodesign** [Fyrd/caniuse#4279]
I thought they were supported on the Chrome desktop version because if you set the page title in the manifest, then add to desktop, it'll use what's in the manifest instead of what is in the page's <title>.
What part am I misunderstanding here?
https://caniuse.com/#feat=web-app-manifest

**Comment by Fyrd** [comment]
Ah, I wasn't familiar with that functionality. Doesn't seem to exist on Mac, but I see it now on Windows Chrome. I think that can count as partial support at least.

**Comment by branditodesign** [comment]
I think that would be due to operating system restrictions seeing how
Chrome on macOS/iOS is mostly a shell of Safari.
The Windows Store itself supports progressive web applications whereas the
'App Store' doesn't and from memory macOS didn't even support any sort of
add to desktop function. But can't complain about it being labelled with
partial support atleast.

**Comment by Fyrd** [comment]
Updated now.

FYI Chrome on macOS is proper Chrome, unlike Chrome on iOS, which as you mention is indeed mostly a shell.

**Comment by branditodesign** [comment]
Yep, you're right, the iOS is mostly a shell although I feel Chrome on both iOS and macOS is missing some functionality compared to the Windows version.

I feel I was just having a safari-powered rant after testing a few websites on an iMac.
