### ISSUE TITLE
Firefox 61 supports Variable fonts

### ISSUE THREAD

**Issue by HM100** [Fyrd/caniuse#4280]
https://developer.mozilla.org/en-US/docs/Web/CSS/font-variation-settings
Check all system supports (Win/Mac/Linux) before changing it.

**Comment by Fyrd** [comment]
I believe that page is incorrect, https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1302685 suggests they're still working on it.

**Comment by jensimmons** [comment]
We are still working on it. We had hoped to ship in FF61, but did not. We now hope to ship in FF62, but it remains to be seen. It's very likely, but not 100% yet. We'll know soon.

**Comment by Fyrd** [comment]
Thanks Jen!
