### ISSUE TITLE
Issue with Singapore data source - UC Browser over represented

### ISSUE THREAD

**Issue by ben-richardson-moneysmart** [Fyrd/caniuse#4285]
Hello,

I am in Singapore, and overlook the analytics of a large blog site with over 1 million sessions per month, mostly from mobile traffic sources. While looking at caniuse.com data there is a large anomaly with the users shown from UC Browser for the 'Singapore' country, vs the traffic we get reported by Google Analytics.

Here is an example:

'Promises' for Singapore
<img width="1024" alt="" src="https://user-images.githubusercontent.com/35677833/40871053-24743890-6667-11e8-923b-03958c326cc0.png">

'Promises' for our blog traffic (99% Singapore based, mostly mobile users)
<img width="1022" alt="" src="https://user-images.githubusercontent.com/35677833/40871054-26fa9f14-6667-11e8-9d71-60663371f978.png">

Could there be any explanation for this? Does UC have some build in blocking tool for GA? 

Could the Singapore data be getting combined with the data from another region?

For now, I am just going to look at my own analytics for browser sources, but it does still play on the back on my mind if we are losing a large chunk of our users to some black hole, or is the seed data for caniuse.com just wrong for Singapore.

Thanks for looking at this, and happy to hear from anyone who suffers similar kinds of issues or can offer any potential answers to the 'why' question.

**Comment by Fyrd** [comment]
When you first import the GA data, does UC Browser appear under the "Browsers not included" column at all? Or do your analytics seem to match what caniuse shows?

The regional data comes from statCounter, see http://gs.statcounter.com/browser-market-share/all/singapore/#monthly-201804-201805-bar for example. If you think there may be something wrong there you may want to contact them instead.

**Comment by Fyrd** [comment]
Closing due to lack of info.
