### ISSUE TITLE
Add hwb() CSS function

### ISSUE THREAD

**Issue by chriscalo** [Fyrd/caniuse#4286]
Details from the [CSS Color Module Level 4](https://drafts.csswg.org/css-color/):
https://drafts.csswg.org/css-color/#the-hwb-notation

**Comment by Schweinepriester** [comment]
Should be coming via MDN once that PR is merged: https://github.com/mdn/browser-compat-data/pull/10898/files#diff-2125922a521f439f749d97ac7aa3ceb461ff83f1494daa3dc8a687a98ea8705bR463
