### ISSUE TITLE
Safari TP 58 supports SameSite cookie attribute

### ISSUE THREAD

**Issue by srudolph-credera** [Fyrd/caniuse#4293]
See https://developer.apple.com/safari/whats-new/ and https://webkit.org/blog/8327/safari-technology-preview-58-with-safari-12-features-is-now-available/

**Comment by Fyrd** [comment]
Neither of those links seem to mention SameSite cookie attribute. Am I missing something?

**Comment by danielcompton** [comment]
The WebKit bug has been fixed here: https://bugs.webkit.org/show_bug.cgi?id=159464.

**Comment by srudolph-credera** [comment]
Thanks for finding the ground truth on this @danielcompton - now I'll know where to look in the future!
