### ISSUE TITLE
Add Array.prototype.flat

### ISSUE THREAD

**Issue by joshklod** [Fyrd/caniuse#4294]
Add support for [`Array.prototype.flat()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat)

**Comment by Schweinepriester** [comment]
+1

- <https://developer.mozilla.org/en-US/Firefox/Releases/62>

  > The Array.prototype.flat() and Array.prototype.flatMap() methods are now enabled by default (bug 1435813).

- <https://bugzilla.mozilla.org/show_bug.cgi?id=1435813>
- <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat>

**Comment by milky2028** [comment]
+1 mostly for flatMap

**Comment by HM100** [comment]
Please 😛

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=array-flat
