### ISSUE TITLE
Add isSecureContext feature to list

### ISSUE THREAD

**Issue by Eva-Rosalene** [Fyrd/caniuse#4304]
MDN link to this feature: https://developer.mozilla.org/en-US/docs/Web/API/Window/isSecureContext

**Comment by Schweinepriester** [comment]
+1

**Comment by GPHemsley** [comment]
Looks like this is now covered by MDN data:
https://caniuse.com/mdn-api_issecurecontext

(via mdn/browser-compat-data#2044)

Though it was recently moved out from under `Window`:
https://developer.mozilla.org/en-US/docs/Web/API/isSecureContext

(via mdn/browser-compat-data#11518)
