### ISSUE TITLE
Chrome full Referrer Policy support

### ISSUE THREAD

**Issue by roycewilliams** [Fyrd/caniuse#4306]
I'm not 100% sure, but from the status of [this Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=627968#c14), it looks like `same-origin`, `strict-origin`, and `strict-origin-when-cross-origin` are now supported for [Referrer Policy](https://caniuse.com/#feat=referrer-policy).

**Comment by Fyrd** [comment]
That note only refers to older versions of Chrome (you can tell by hovering over that note or finding the cell with the "2", though I can see how it's easy to miss that. Have removed the word "Chrome" so it doesn't appear like it refers to all versions.

**Comment by roycewilliams** [comment]
Ah, totally understood (and **thank you** for the UX tweak!)
