### ISSUE TITLE
Add `import.meta`

### ISSUE THREAD

**Issue by mathiasbynens** [Fyrd/caniuse#4309]
At least Chrome 64 has it: https://www.chromestatus.com/feature/5637509807603712

**Comment by Schweinepriester** [comment]
+1

- <https://developer.mozilla.org/en-US/Firefox/Releases/62>

  > The import.meta property has been implemented to expose context-specific metadata to a JavaScript module (bug 1427610).

- <https://bugzilla.mozilla.org/show_bug.cgi?id=1427610>

**Comment by Schweinepriester** [comment]
Available via MDN: https://caniuse.com/mdn-javascript_statements_import_meta :)
