### ISSUE TITLE
Add support for the __Host- and __Secure-

### ISSUE THREAD

**Issue by newmediadev** [Fyrd/caniuse#4311]
As per the subject. Cookie prefixes are useful tools to help secure the privacy of a users session.

**Comment by claudepache** [comment]
+1

**Comment by brodock** [comment]
some data from mozilla: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Browser_compatibility

**Comment by GPHemsley** [comment]
Looks like this is now covered by MDN data:
https://caniuse.com/mdn-http_headers_set-cookie_cookie_prefixes

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#cookie_prefixes
