### ISSUE TITLE
Updates to lazyload

### ISSUE THREAD

**Issue by Malvoz** [Fyrd/caniuse#4315]
Update the resource reference in https://caniuse.com/#feat=lazyload which points to https://msdn.microsoft.com/en-us/library/dn369270(v=vs.85).aspx (refers to unrelated page at developer.mozilla.org), replace with: https://msdn.microsoft.com/en-us/ie/dn369270(v=vs.94)

Also, not sure if you want to mention standardized lazy loading is being discussed in:
github.com/whatwg/html/issues/2806

**Comment by Fyrd** [comment]
Thanks, feature has been updated.
