### ISSUE TITLE
Variable Fonts will ship in Firefox 62

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#4318]
I'd love to see Firefox's info on https://caniuse.com/#feat=variable-fonts updated.

Note 4 is definitely not true anymore. ("Does not support the font-weight and font-stretch properties.")

I'm not sure about Note 2 or Note 5. Or when Note 4 became not-true (in FF61 cycle? Or 62?)

Let me ping folks who do know, and they can fill in this issue with the details. 

I know web developers and designers are excited about  Variable Fonts, and we want them to see that yes, it is in fact coming to Firefox in September. 

Thanks.

**Comment by jfkthame** [comment]
Note 2 is no longer accurate; as of Firefox 59, there's support (if the relevant prefs are turned on) for Windows 10 (Fall Creators Update or later) and Linux (with FreeType 2.7.1 or later), and as of Firefox 60 there is also support on Android.

Note 5 also became obsolete with the FF60 cycle.

Also, a further adjustment to note 2: the macOS system version requirement is now 10.13 or later (matching Safari); we no longer attempt to support variable fonts on 10.12.

Note 4 became obsolete in the FF61 cycle.

**Comment by Fyrd** [comment]
Thanks for all the details! I believe the data's been appropriately updated now.

**Comment by HM100** [comment]
They haven't. The past comment before Fyrd's ones say that also supported on Win10 Fall Creators Update and Linux with Freetype 2.7.1 or newer so it needs fixing.
