### ISSUE TITLE
Add asyncIterator

### ISSUE THREAD

**Issue by itayronen** [Fyrd/caniuse#4319]
https://github.com/tc39/proposal-async-iteration
Copying the from the above link:
### Native implementations
Chakra: outstanding issue
JavaScriptCore: shipping in Safari Tech Preview 40
SpiderMonkey: shipping in Firefox 57; launch bug
V8: shipping in Chrome 63; launch bug

I personally have Chrome 66 and I can confirm:
* It has the asyncIterator symbol (Symbol.asyncIterator).
* async generator syntax works: "async function* myFunction()...".
* Not sure about "for await (...)".

**Comment by Schweinepriester** [comment]
Duplicate of #3690?

**Comment by Fyrd** [comment]
Yup, duplicate. Data's available and pending review, may add this one soon.
