### ISSUE TITLE
Add @element queries

### ISSUE THREAD

**Issue by mrvik** [Fyrd/caniuse#4325]
The `@element` queries are hypothetical at this moment. Useful links can be found on this answer: [StackOverflow](https://stackoverflow.com/questions/35067662/css-media-detect-overflow#answer-35071420)
For the moment, AFAIK no browser has support for it, but can be used with a polyfill (written with JS)

**Comment by Fyrd** [comment]
Until there's a specification and interest from browser vendors to implement this isn't something that will be added.
