### ISSUE TITLE
Add place-content, place-items, place-self

### ISSUE THREAD

**Issue by raphaelgoetter** [Fyrd/caniuse#4330]
The spec for those 3 shorthands : https://www.w3.org/TR/css-align-3/

Support : Chrome 59+ , Firefox 45, Samsung Internet 7.0 + ? 

Source : https://developer.mozilla.org/en-US/docs/Web/CSS/place-items

**Comment by web2033** [comment]
Good point. I was looking for "place-items" too.

**Comment by angel-luis** [comment]
+1

But, at this moment, it's experimental, it's better to use the full grid expressions.

**Comment by Fyrd** [comment]
All available now, see https://caniuse.com/#search=place-content etc
