### ISSUE TITLE
Add Samsung Internet v7

### ISSUE THREAD

**Issue by poshaughnessy** [Fyrd/caniuse#4331]
Hi. Thanks for your continuing support! (Since [v6 last time](https://github.com/Fyrd/caniuse/issues/3664)), Samsung Internet v7 has now been recently [released as our current stable version](https://medium.com/samsung-internet-dev/7-2-stable-is-here-81fdbfca75b4), based on Chromium M59. Please would it be possible to add our new version? :)

**Comment by Fyrd** [comment]
Thanks for pointing that out, @poshaughnessy, added now!
