### ISSUE TITLE
Titles that tell you what's on the page

### ISSUE THREAD

**Issue by GustvandeWal** [Fyrd/caniuse#4340]
It might be by design that the title of each page is the same because it makes it obvious for people where they are heading when the website is shared somewhere else.
However, with Open Graph tags, the title of a shared link is customizable separately from the title that's visible in the browser's tab.
I'd be nice to see what feature is being viewed in the browsertab.
I'm thinking something along the lines of:

    https://caniuse.com/
      Can I use. Support tables for (new) web features

    https://caniuse.com/#search=flexbox
      S: flexbox

    https://caniuse.com/#feat=flexbox
      F: CSS Flexible Box Layout Module

Like this, you can still see at least the first few letters of the feature.

**Comment by Schweinepriester** [comment]
Inspired by not being able to differentiate in the history

![image](https://user-images.githubusercontent.com/2644614/121763632-f80d5900-cb3d-11eb-9045-6b0d9c145df7.png)

and <https://developer.apple.com/videos/play/wwdc2021/10029/> starting at 7:50 suggesting

```html
<title>Content title | Site Name</title>
```

a little push maybe, @Fyrd? 0:-)

Picking up the suggestion, I don't think for features the `F: ` prefix is needed. For others a good solution, e.g. search or the categories. But any form of mentioning the feature would be helpful already, be it in the way suggested by Apple or another, e.g.

```html
<!-- https://caniuse.com/flexbox -->
<title>CSS Flexible Box Layout Module | Can I use... Support tables for HTML5, CSS3, etc</title>
```

**Comment by Fyrd** [comment]
Yeah, agreed. I think it actually used to work similar to this but may have gotten broken in the last major update.

**Comment by Fyrd** [comment]
Okay, went ahead and implemented this, let me know what you think!
