### ISSUE TITLE
font-weight: lighter

### ISSUE THREAD

**Issue by luisangellopez9731** [Fyrd/caniuse#4343]
I'm curious about the compatibility of this value-attribute in an Ipad, so i will be grateful if you keep record about this.

**Comment by Ugoku** [comment]
This is part of [CSS Level 1](https://www.w3.org/TR/CSS1/#font-weight) and has been supported everywhere for ages

**Comment by Nemo64** [comment]
@luisangellopez9731 If it doesn't work than your font probably does not support it.

**Comment by Fyrd** [comment]
Search for `font-weight: lighter` now links to `font-weight` property via MDN BCD:
https://caniuse.com/?search=font-weight%3A%20lighter
