### ISSUE TITLE
preload Support on Firefox is incorrect

### ISSUE THREAD

**Issue by zachleat** [Fyrd/caniuse#4344]
Per this discussion: https://twitter.com/yoavweiss/status/1012383874838646784

Not sure if it was supported in a stable release or not, but it’s definitely not in there now.

**Comment by HM100** [comment]
Confirmed on Android, Does not work on FF Android and Desktop. The `network.preload` flag is still required to use it. I'll file a PR for fix.

**Comment by zachleat** [comment]
Yay!
