### ISSUE TITLE
Add Opera 54

### ISSUE THREAD

**Issue by HM100** [Fyrd/caniuse#4348]
Recently today, I found Opera Internet Browser being upgraded to V54 so please add it. See [this](https://www.opera.com/client/upgraded) for more

**Comment by HM100** [comment]
Any updates for this?
Seems other browsers be stuck oon old versions. Opera Android must be v47 which is based on M66 of chromium.

**Comment by SunburnedGoose** [comment]
We're having issues with users with opera v54 and 55.  They are being reported as opera 53.

**Comment by Fyrd** [comment]
Opera versions 54 & 55 have now been added.

**Comment by bhollis** [comment]
Thank you!
