### ISSUE TITLE
[HTTP header] Cross-Origin-Resource-Policy

### ISSUE THREAD

**Issue by Malvoz** [Fyrd/caniuse#4355]
- https://fetch.spec.whatwg.org/#cross-origin-resource-policy-header
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Resource-Policy
(&plus; https://developer.mozilla.org/en-US/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP))

The `Cross-Origin-Resource-Policy` (CORP) header enables authors to prevent other domains from loading resources by restricting any kind of cross-origin load to protect themselves against Spectre attacks (essentially a standardized method of [hotlink protection](https://perishablepress.com/creating-the-ultimate-htaccess-anti-hotlinking-strategy/)).

Available in [Safari 12](https://webkit.org/blog/8332/release-notes-for-safari-technology-preview-59/).

Tracking bugs:

- https://www.chromestatus.com/feature/4647328103268352
- https://bugzilla.mozilla.org/show_bug.cgi?id=1459573
- https://bugs.webkit.org/show_bug.cgi?id=186761
- https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17934554/

Note, this header was initially proposed as [`From-Origin`](https://github.com/whatwg/fetch/issues/687), can include it in `keywords` for developers to find the latest version.

**Comment by Malvoz** [comment]
If this is added, then we might want to mention the issue (Chrome v73) with regards to downloads of resources that responds with the header: https://bugs.chromium.org/p/chromium/issues/detail?id=952834

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-http_headers_cross-origin-resource-policy
