### ISSUE TITLE
HPKP pending removal in chrome

### ISSUE THREAD

**Issue by eelkefierstra** [Fyrd/caniuse#4359]
HPKP is pending removal in [chrome 69](https://www.chromestatus.com/feature/5903385005916160)  
This is not yet reflected in the current compatibility view.

https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/he9tr7p3rZ8/eNMwKPmUBAAJ

**Comment by Fyrd** [comment]
Updated now, thanks!
