### ISSUE TITLE
Add support for checking fonts

### ISSUE THREAD

**Issue by chriscarruthers** [Fyrd/caniuse#4361]
It would be great to be able to enter a font name and check what support it has. I guess it's more of an OS thing than the individual browser (?) but is important in when choosing non-custom fonts to use on a site (if you don't want to or can't package the font with your site).

**Comment by ashadixon** [comment]
You're correct in saying it depends much more on the client's system than the actual browser. Some fonts you can almost guarantee are going to be available on all systems, however if you really want to use a non-standard font and don't want to deliver it via your server, best deliver the file to the client via a third-party CDN. Google has one, along with instructions on how to embed it into your site's source: https://fonts.google.com/.

A good rule to remember is that if you're not sure if a font will be available on all systems with a browser, then it's probably not.

**Comment by Fyrd** [comment]
Caniuse is only for existing specifications and/or browser support, not for web tech proposals, so closing this issue.
