### ISSUE TITLE
[HTTP Header] Cross-Origin-Opener-Policy

### ISSUE THREAD

**Issue by Malvoz** [Fyrd/caniuse#4366]
The `Cross-Origin-Opener-Policy` (COOP) header prevents third-parties from opening/controlling a window.

Explainers:  
https://docs.google.com/document/d/1eQEdjHDaJHJ5SFyRKjcqohS7x8XSpF8xmajXimAKcHc  
https://docs.google.com/document/d/1Ey3MXcLzwR1T7aarkpBXEwP7jKdd2NvQdgYvF8_8scI

Initial definition:  
https://gist.github.com/annevk/6f2dd8c79c77123f39797f6bdac43f3e

Google I/O 2019 explainer video:  
https://www.youtube.com/watch?v=DDtM9caQ97I&t=2264

Chrome status:  
https://www.chromestatus.com/feature/5432089535053824

<hr>

**Edit**:
This header was [implemented in Safari 12](https://webkit.org/blog/8332/release-notes-for-safari-technology-preview-59/) and renamed from `Cross-Origin-Options` to `Cross-Origin-Window-Policy` but support was dropped in release note 67.

This header was also at some point proposed as [`Cross-Origin-Isolate`](https://groups.google.com/a/chromium.org/forum/m/#!msg/isolation-policy).

I mention name changes mainly because we should preferably include those as `keywords` so developers can find the latest version of the header if they stumble upon old documentation.

**Comment by Malvoz** [comment]
Safari actually dropped support for this header in the same release note where they mentioned renaming `Cross-Origin-Options` to `Cross-Origin-Window-Policy`.

I'm keeping this issue open, monitoring eventual resolution in https://github.com/whatwg/html/issues/3740.

**Comment by Malvoz** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=cowp

**Comment by cmthornton** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1521808

**Comment by empijei** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=922191

**Comment by valtlai** [comment]
The `Cross-Origin-Opener-Policy` header is now [implemented](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/67#HTTP) in Firefox 67.

**Comment by Malvoz** [comment]
Available at https://caniuse.com/mdn-http_headers_cross-origin-opener-policy.
