### ISSUE TITLE
Node.contains

### ISSUE THREAD

**Issue by extempl** [Fyrd/caniuse#4371]
https://developer.mozilla.org/en-US/docs/Web/API/Node/contains

**Comment by Fyrd** [comment]
Data was added with #2875, still pending review.

**Comment by jak-kal** [comment]
Nice to see it was added. Any update on its review?

**Comment by GPHemsley** [comment]
The "Data pending review" label was recently removed from #2875 (which had long been closed).

In addition, it looks like this is now covered by MDN data:
https://caniuse.com/mdn-api_node_contains

(via mdn/browser-compat-data#2603)
