### ISSUE TITLE
Search fails any request that starts with "display: ___"

### ISSUE THREAD

**Issue by Psithief** [Fyrd/caniuse#4382]
### Works
https://caniuse.com/#search=display%3A

### Incorrect results
https://caniuse.com/#search=display%3A%20f (Expected: `display: flow-root`)
https://caniuse.com/#search=display%3A%20c (Expected: `display: contents`)
https://caniuse.com/#search=display%3A%20r (Expected: `display: run-in`)

Including a colon breaks the search for unknown reasons. Can the search not decode more than one encoded literal from a URL?

**Comment by Fyrd** [comment]
Thanks for pointing this out, fixed now!
