### ISSUE TITLE
webkitGetAsEntry

### ISSUE THREAD

**Issue by beechertrouble** [Fyrd/caniuse#4385]
https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/webkitGetAsEntry

please and thank you,

**Comment by 3cp** [comment]
The safari support is incorrect. safari got it since 2017.

https://trac.webkit.org/changeset/221177/webkit

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_datatransferitem_webkitgetasentry
