### ISSUE TITLE
jsonp.php?callback not working anymore?

### ISSUE THREAD

**Issue by rejas** [Fyrd/caniuse#4386]
Modernizr tries to use the `http://caniuse.com/jsonp.php?callback=caniusecb` for accessing some data during testing of its code: 
https://github.com/Modernizr/Modernizr/blob/c2e5e48dbf12f975e89127143dc222ef43d0f9d4/test/browser/integration.jade#L38
Seems like the switch to https left this URL behind or is the Modernizr call wrong (calling it via https isnt working neither)
Or is this access dead for good / are there any plans to revive it?

**Comment by rejas** [comment]
Sorry to bother, but could I get a feedback on this @Fyrd ?

**Comment by Fyrd** [comment]
While I'd recommend you used the data from this repo instead, I'll see how hard it'll be to revive the jsonp functionality. Give me a day or so.

**Comment by rejas** [comment]
Dont put too much thought in it, working on a branch that uses the data from github directly. Since nobody else seems to miss the api besides us, it shouldnt be necessary to keep the old api just for us.

**Comment by rejas** [comment]
Dont put too much thought in it, working on a branch that uses the data from github directly. Since nobody else seems to miss the api besides us, it shouldnt be necessary to keep the old api just for us. Just wanted to know what youre thoughts were on this.

**Comment by rejas** [comment]
Made the move to using the caniuse-github-data mentioned in my previous comment. No need for any php apis anymore :-)
