### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by 1977744311** [Fyrd/caniuse#4391]
npm install caniuse-db
npm http fetch GET 200 https://registry.npmjs.org/caniuse-db 12ms (from cache)
npm ERR! Unexpected end of JSON input while parsing near '...iuse-db/-/caniuse-db-'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/guochengzhe/.npm/_logs/2018-07-22T01_37_54_787Z-debug.log

**Comment by Fyrd** [comment]
All I can suggest is to delete and try re-installing, don't think anyone else is having this issue.
