### ISSUE TITLE
The "show all" button does not work after the first click

### ISSUE THREAD

**Issue by bevverik** [Fyrd/caniuse#4393]
If you press the "show all" button, then you can not press it again. So to hide the display of the entire table is necessary to change the view mode
![image](https://user-images.githubusercontent.com/26362936/43067451-d8596100-8e80-11e8-8e26-9278c8e3cc77.png)

**Comment by Fyrd** [comment]
The "show all" functionality has now been changed to where it can be toggled on & off by switching between it and the "filtered" view, so closing this issue.
