### ISSUE TITLE
Firefox is shipping `prefers-reduced-motion` (CSS)

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#4403]
Estimated release, according to the Intent to Ship email: 
> For Windows in Firefox 63
> For MacOSX it might be delayed in Firefox 64 
> I don't have a plan for Android at this moment

Intent to ship:
https://groups.google.com/forum/#!topic/mozilla.dev.platform/faQvST2piv4

Bugs:
For Windows: https://bugzilla.mozilla.org/show_bug.cgi?id=1365045 
For Mac OSX: https://bugzilla.mozilla.org/show_bug.cgi?id=1475462

**Comment by Fyrd** [comment]
Thanks, updated!
