### ISSUE TITLE
TextMetrics API

### ISSUE THREAD

**Issue by 1valdis** [Fyrd/caniuse#4408]
> The TextMetrics interface represents the dimension of a text in the canvas, as created by the CanvasRenderingContext2D.measureText() method.

https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics

There are a ton of new (as of 2014) advanced text metrics properties such as heights, baselines, bounding box. These properties are supported only in Chrome for now, behind the ExperimentalCanvasFeatures flag.

Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1102584

I haven't found the API on the site so I'd suggest to add it.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_textmetrics (see also sub-features)
