### ISSUE TITLE
User-Agent Strings

### ISSUE THREAD

**Issue by acornforth** [Fyrd/caniuse#4410]
It would be super handy in the various compatibility charts if the on-hover popup could contain the User-Agent strings that exist for that version of the browser, or at least the parts of the UA string that all versions of that browser have in common, and don't share with any other browsers.
This would provide us with a one-stop shop for browser compatibility _and_ a reference for what substring to search in the UA when deciding which content to serve...

**Comment by Fyrd** [comment]
Browser-sniffing is generally a bad idea, I'd rather not have caniuse take a part in encouraging it.

**Comment by acornforth** [comment]
I would tend to agree that browser-sniffing as a de-facto approach does the web as a whole more harm than good, and i try to avoid it wherever possible. However, inspecting UA string is a useful step with certain approaches to feature-detection, which is what I (and others) are usually trying to do. This is how the googlefonts api determines which formats of font to include in their css.
Even if the primary use is to figure out what others on the web are doing.... are you still saying no?
At the end of the day, it's just information, used for reference... is that not the purpose of caniuse?
