### ISSUE TITLE
support for HTMLTableElement.createTBody

### ISSUE THREAD

**Issue by GeraldNDA** [Fyrd/caniuse#4411]
it seems to not be well documented but it appears in https://www.w3.org/TR/html50/tabular-data.html#the-table-element and https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableElement#Specifications (includes browser support)

It'd be nice to be included in caniuse.

**Comment by GPHemsley** [comment]
Looks like this is now covered by MDN data:
https://caniuse.com/mdn-api_htmltableelement_createtbody

(via mdn/browser-compat-data#2215)
