### ISSUE TITLE
ReportingObserver support

### ISSUE THREAD

**Issue by laukstein** [Fyrd/caniuse#4417]
Chrome 69 will land ReportingObserver support that can be used to report used deprecated APIs.

> ReportingObserver has only shipped in Chrome 69. It is being considered by other browsers.

Announcement https://developers.google.com/web/updates/2018/07/reportingobserver
Spec https://w3c.github.io/reporting/#observers

**Comment by chrisblakley** [comment]
+1

**Comment by staabm** [comment]
very related to `ReportingObserver` is the `Report-To` (Reporting API) header
https://developers.google.com/web/updates/2018/09/reportingapi

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_reportingobserver
