### ISSUE TITLE
Add CSS.registerProperty to caniuse

### ISSUE THREAD

**Issue by scottkellum** [Fyrd/caniuse#4420]
I want to identify what browsers support registering CSS custom properties.

**Comment by tobireif** [comment]
Yes that would be useful!

And the spec could be tracked: https://www.w3.org/TR/css-properties-values-api-1/

**Comment by jimratliff** [comment]
This is critical for being able to animate CSS variables.

**Comment by cxcorp** [comment]
As for Chrome, `CSS.registerProperty` [was added in Chrome 78](https://web.dev/css-props-and-vals/) and the new CSS `@property` syntax for registering properties has just been [introduced into Chrome 85](https://web.dev/at-property/).

**Comment by Fyrd** [comment]
Available at https://caniuse.com/mdn-api_css_registerproperty
