### ISSUE TITLE
Add information about CSS pseudo selector :defined

### ISSUE THREAD

**Issue by franktopel** [Fyrd/caniuse#4427]
caniuse.com seemingly has no information on the compatibility of the CSS pseudo selector

`:defined` (which matches custom elements that have been defined).

**Comment by franktopel** [comment]
According to [mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/:defined), this is the current support for `:defined`:

![image](https://user-images.githubusercontent.com/10668603/43954769-f8fa3ab2-9c9d-11e8-8ae3-0248095c07e2.png)

**Comment by HM100** [comment]
Is Chrome, Opera and safari support correct? Because it is marked as yes, meaning that all versions of chrome/safari/Opera support it

**Comment by franktopel** [comment]
How would I know? That's why I tried to consult caniuse in the first place.

**Comment by Schweinepriester** [comment]
Available via MDN now: <https://caniuse.com/mdn-css_selectors_defined>

(Also support has been marked more granular now: https://developer.mozilla.org/en-US/docs/Web/CSS/:defined#browser_compatibility)
