### ISSUE TITLE
'imagesizes' & 'imagesrcset' for <link rel="preload">

### ISSUE THREAD

**Issue by Malvoz** [Fyrd/caniuse#4436]
This (sub-)feature of [Preload](https://caniuse.com/#feat=link-rel-preload) introduces `imagesizes` and `imagesrcset` for `<link rel="preload">` allowing browsers to selectively preload `<img>`'s based on the corresponding `imagesizes` and `imagesrcset`.

Chrome implementation status:
https://www.chromestatus.com/feature/5164259990306816

**Comment by Schweinepriester** [comment]
+1, now released with Chrome 73.

**Comment by mrienstra** [comment]
Some relevant links (in addition to the "Chrome Platform Status" link posted by @Malvoz):

1. [WHATWG HTML Standard / link element / imagesrcset attribute](https://html.spec.whatwg.org/multipage/semantics.html#attr-link-imagesrcset)

2. [WHATWG HTML Standard / link element / imagesizes attribute](https://html.spec.whatwg.org/multipage/semantics.html#attr-link-imagesizes)

3. [web-platform-tests dashboard / preload / imagesrcset or imagesizes](https://wpt.fyi/results/preload?label=master&label=experimental&q=imagesrcset%20or%20imagesizes)

4. [WebKit Bugzilla / Bug 192950 / Implement imagesrcset and imagesizes attributes on link rel=preload](https://bugs.webkit.org/show_bug.cgi?id=192950)

5. [Mozilla Bugzilla / Bug 1515760 / Implement imagesrcset and imagesizes attributes on link rel=preload](https://bugzilla.mozilla.org/show_bug.cgi?id=1515760)

6. [Contributing to the caniuse data / Adding a feature](https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md#adding-a-feature)

**Comment by Malvoz** [comment]
Available at:
- https://caniuse.com/mdn-api_htmllinkelement_imagesizes
- https://caniuse.com/mdn-api_htmllinkelement_imagesrcset
