### ISSUE TITLE
Array.prototype.includes and String.prototype.includes exists in IE 11

### ISSUE THREAD

**Issue by aifrim** [Fyrd/caniuse#4448]
Found `IE 11.547.16299.0`

```
Array.prototype.includes and
String.prototype.includes evaluates to 
function includes() { [native code] }
```

https://github.com/mdn/browser-compat-data/issues/2634

**Comment by Fyrd** [comment]
As mentioned on the browser-compat-data thread there doesn't seem to be any evidence of real support, so closing this issue.
