### ISSUE TITLE
Cannot find cancelBubble

### ISSUE THREAD

**Issue by SeLiNnnn** [Fyrd/caniuse#4454]
caniuse.com seemingly has no result of cancelBubble, and I want to know the compatibility of the other browsers except IE.

Thanks!

**Comment by cvrebert** [comment]
The data in https://developer.mozilla.org/en-US/docs/Web/API/Event/cancelBubble is correct (it's supported by the current versions of all major browsers, modulo [one bug](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10266390/) in Edge's implementation relative to the current DOM spec), but lacks historical info on when exactly the support was added to Safari and Chrome. (I would guess it's ancient.)

**Comment by GPHemsley** [comment]
Looks like this is now covered by MDN data:
https://caniuse.com/mdn-api_event_cancelbubble

(via mdn/browser-compat-data#1264)
