### ISSUE TITLE
Please include `:blank` pseudo-class

### ISSUE THREAD

**Issue by mahdiyazdani** [Fyrd/caniuse#4459]
`:blank` is part of the CSS Selectors Level 4 draft

```
p:blank {
  display: none;
}
```

**Comment by Schweinepriester** [comment]
Already requested in #1058, but might be useful to have a separate issue.

**Comment by GreLI** [comment]
`:blank` for the empty elements with space now is just extended `:empty` in CSS Selectors level 4. It was (re-)added for empty inputs, but its status is at-risk.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-css_selectors_blank
