### ISSUE TITLE
Move a few items to the security category

### ISSUE THREAD

**Issue by ElleshaHackett** [Fyrd/caniuse#4460]
Move this items to the security category:
- Link type "noreferrer"
- Referrer Policy
- Feature Policy
- 'SameSite' cookie attribute

**Comment by Malvoz** [comment]
They already are:

https://github.com/Fyrd/caniuse/blob/4de7632c34c4531a13eee6044e3f4d421339d83d/features-json/rel-noreferrer.json#L15-L19

https://github.com/Fyrd/caniuse/blob/4de7632c34c4531a13eee6044e3f4d421339d83d/features-json/referrer-policy.json#L19-L21

https://github.com/Fyrd/caniuse/blob/4de7632c34c4531a13eee6044e3f4d421339d83d/features-json/feature-policy.json#L23-L26

https://github.com/Fyrd/caniuse/blob/4de7632c34c4531a13eee6044e3f4d421339d83d/features-json/same-site-cookie-attribute.json#L35-L37

**Comment by ElleshaHackett** [comment]
Hm, strange. Indeed. I double checked https://caniuse.com/#cats=Security. The only thing that is not showing there is the feature-policy. Any thoughts on that?

**Comment by Malvoz** [comment]
@ElleshaHackett do you want to close this? :)
