### ISSUE TITLE
Broken link / hijacked domain

### ISSUE THREAD

**Issue by bjxrn** [Fyrd/caniuse#4474]
In the list of [CSS Masks](https://caniuse.com/#feat=css-masks) resources, the link "Detailed blog post [thenittygritty.co]" no longer goes to a detailed blog post. The domain has been taken over by some malware peddling person or group.

Archive.org has a snapshot that seems to display everything nicely:
https://web.archive.org/web/20160505054016/http://thenittygritty.co/css-masking

**Comment by Malvoz** [comment]
The blog post is detailed and is indeed useful, I updated the link to the web archive link you provided. Will have to wait for PR to merge.

**Comment by bjxrn** [comment]
@Malvoz Oh, I didn't realize the links lived inside the Github repo as well. Thanks for making the pull request for me!
