### ISSUE TITLE
Add information about JavaScript's "instanceof"

### ISSUE THREAD

**Issue by marcusparsons** [Fyrd/caniuse#4479]
I noticed that caniuse does not have any information about JavaScript's "instanceof" operator that tests whether a variable is an instance of a particular JavaScript type.  

I could not find a reliable resource that lists browser compatibility; however, "instanceof" has been a part of JavaScript since ECMAScript Edition 3, according to the official ECMAScript documentation: https://www-archive.mozilla.org/js/language/E262-3.pdf

**Comment by HM100** [comment]
That’s supported on all known browsers (IE5.6+, Chrome 3+, FX2+, Opera 9+)?

**Comment by Schweinepriester** [comment]
- <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#Browser_compatibility>
- 

Imho: "Needs search result" & "Fully supported"

**Comment by marcusparsons** [comment]
Thank you for those labels!

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_operators_instanceof
