### ISSUE TITLE
Feature addition: navigator.mediaCapabilities.decodingInfo()

### ISSUE THREAD

**Issue by chcunningham** [Fyrd/caniuse#4480]
MediaCapabilities "decodingInfo()" API builds on HTMLMediaElement.canPlayType() to better surface what types of media the UA can play. The APIs responses describe when a given resolution, framerate, codec, etc... will perform well (smoothly) on the device and when the playback is power efficient (either hw accelerated decoding or a resolution low enough that sw is also comparably considered efficient).

The MediaCapabilities spec is being incubated [here](https://wicg.github.io/media-capabilities/). The spec describes more than just the decodingInfo() API, but at this time only decodingInfo() is live in Chrome. 
 
navigator.mediaCapabilities.decodingInfo() was first released in Chrome 66. 
https://www.chromestatus.com/feature/5869632707624960

Coding samples:
https://googlechrome.github.io/samples/media-capabilities/decoding-info.html
https://beaufortfrancois.github.io/sandbox/media-capabilities/decoding-info-2.html

**Comment by Schweinepriester** [comment]
+1

<https://developer.apple.com/documentation/safari_release_notes/safari_13_beta_release_notes>

> Added support for the `decodingInfo()` method of the Media Capabilities API for checking supported codecs, efficiently supported codecs, and optional codec features including alpha.

**Comment by Schweinepriester** [comment]
Available via MDN: <https://caniuse.com/mdn-api_mediacapabilities_decodinginfo>
