### ISSUE TITLE
Feature addition: Element.toggleAttribute

### ISSUE THREAD

**Issue by LorenzKahl** [Fyrd/caniuse#4481]
Implemented in Chrome 69:
https://www.chromestatus.com/feature/5676852374929408

**Comment by Malvoz** [comment]
+1

**Comment by maxgaurav** [comment]
Added in Firefox 63
[https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/63](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/63)

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_element_toggleattribute
