### ISSUE TITLE
Names consistency

### ISSUE THREAD

**Issue by AurelioDeRosa** [Fyrd/caniuse#449]
In the section JS API, some of the entries have the "API" word at the end of the name and some don't. I think the names should be consistent. In addition, it'd be nice to add a note to the Contribution.md file to keep the name consistent in future as well.

The question is: the "API" word should be removed or added?

**Comment by Fyrd** [comment]
This doesn't feel worthwhile to me...sometimes a title sounds better with "API" at the end, sometimes it feels unnecessary.
