### ISSUE TITLE
Incorrect Blend Mode support for Safari

### ISSUE THREAD

**Issue by HM100** [Fyrd/caniuse#4490]
According to what I checked before on iOS Safari in test cases of blend modes on MDN, the last four are also supported as well (Hue, Color, Saturation, Lumiosity) but IDK what version of safari is for full support. iOS 11+ and Safari 11+ should be full support of blend modes but IDK for some older ones unless someone else tests it.

**Comment by Fyrd** [comment]
Has been corrected.
