### ISSUE TITLE
scss support

### ISSUE THREAD

**Issue by khoda81** [Fyrd/caniuse#4494]
There is not anything about scss.
Asking you to add scss support.

Thanks.

**Comment by myfonj** [comment]
Sass (and its syntactic variant SCSS) is not browser feature.  It is special language compiled to CSS (or "_CSS preprocessor_").  So it it out of scope of this project, I assume.

**Comment by Fyrd** [comment]
Yeah, browsers aren't expected to have direct support for scss files so makes no sense to track support.
