### ISSUE TITLE
CSS drop-shadow spread-radius

### ISSUE THREAD

**Issue by GustvandeWal** [Fyrd/caniuse#4497]
Just like `box-shadow`, `filter: drop-shadow()` should be able to take a 4th parameter that spreads the shadow, spread-radius.
In Webkit, however, this still isn't possible.
I'd like to be able to track whether and when this is possible in all browsers.

**Comment by HM100** [comment]
If no browser supports it unless experimental implementation exists, then it mustn’t be listed

**Comment by GustvandeWal** [comment]
I thought this should be possible after reading it on [this website](http://thenewcode.com/598/boxshadow-property-vs-dropshadow-filter-a-complete-comparison):
![should](https://user-images.githubusercontent.com/15628812/45778457-ee8a8700-bc58-11e8-8ea8-432e9a753966.png)

Turns out the spec says otherwise:
![shouldn t](https://user-images.githubusercontent.com/15628812/45778458-ef231d80-bc58-11e8-890e-b2f44ba1ef10.png)

I've tested on Chrome, FF and Opera. None of them support the 4th parameter.

**Comment by HM100** [comment]
Edge also does neither but both IE and Edge seem to allow spread radius value on text-shadow
