### ISSUE TITLE
:focus-visible actually work on chrome

### ISSUE THREAD

**Issue by hugobqd** [Fyrd/caniuse#4507]
I can use **:focus-visible** on my chrome (69.0.3497.100 mac) although that's red on https://caniuse.com/#feat=css-focus-visible

**Comment by HM100** [comment]
Disable the required flag and send us a screenshot. Are you sure you have disabled the needed flag before you send this?

**Comment by HM100** [comment]
According to [chrome status](https://www.chromestatus.com/feature/5823526732824576), it is still under flag.

**Comment by hugobqd** [comment]
You're right, thanks and sorry
