### ISSUE TITLE
Track CSS `scroll-snap-stop`

### ISSUE THREAD

**Issue by aldendaniels** [Fyrd/caniuse#4509]
See [the spec](https://www.w3.org/TR/css-scroll-snap-1/#scroll-snap-stop).

> When scrolling with an intended direction, the scroll container can “pass over” several possible snap positions (that would be valid to snap to, if the scrolling operation used the same direction but a lesser distance) before reaching the natural endpoint of the scroll operation and selecting its final scroll position. The scroll-snap-stop property allows such a possible snap position to “trap” the scrolling operation, forcing the scroll container to stop before the scrolling operation would naturally end.

Useful for developing a swipe-able carousel. 

As of `August 15, 2018`, per CSS Tricks, this was [not supported by any browser](https://css-tricks.com/practical-css-scroll-snapping/#article-header-id-8).

There's [a bug](https://bugs.chromium.org/p/chromium/issues/detail?id=823998) tracking Chrome support. Status is "started".

**Comment by Schweinepriester** [comment]
+1

<https://chromestatus.com/feature/5439846480871424>: Chrome 75+

**Comment by Schweinepriester** [comment]
Available via MDN: <https://caniuse.com/mdn-css_properties_scroll-snap-stop>
