### ISSUE TITLE
Add compat data for CSS scrollbars spec

### ISSUE THREAD

**Issue by nt1m** [Fyrd/caniuse#4511]
https://drafts.csswg.org/css-scrollbars-1/

The current data on caniuse.com is outdated, and only has the non-standard webkit and MS properties.

Firefox supports the official specification.

**Comment by Schweinepriester** [comment]
+1

- https://www.smashingmagazine.com/2018/10/tpac-css-working-group-new/#css-scrollbars
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars

**Comment by Fyrd** [comment]
https://caniuse.com/#feat=css-scrollbar includes official support, though there's also https://caniuse.com/#feat=mdn-css_properties_scrollbar-color etc. for individual properties.
