### ISSUE TITLE
grid-auto-rows is not listed?

### ISSUE THREAD

**Issue by BenRacicot** [Fyrd/caniuse#4513]
grid-auto-rows is not listed?
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-auto-rows

**Comment by Schweinepriester** [comment]
Seems to be nearly identical to grid (https://developer.mozilla.org/en-US/docs/Web/CSS/grid-auto-rows#Browser_Compatibility versus https://developer.mozilla.org/en-US/docs/Web/CSS/grid#Browser_compatibility), thus "needs search result" leading to <https://caniuse.com/#feat=css-grid>?

**Comment by BenRacicot** [comment]
Hey @Schweinepriester I'm not sure I fully understand but `grid-auto-rows` does not have edge compatibility from what I'm reading.

**Comment by Fyrd** [comment]
Just tested and it seems supported in Edge 15+ just like other grid properties.

**Comment by Fyrd** [comment]
Have added grid-auto-rows as search keyword.
