### ISSUE TITLE
prefers-dark-interface

### ISSUE THREAD

**Issue by fazalmajid** [Fyrd/caniuse#4523]
A proposed media query to support things like macOS 10.14 Mojave’s dark mode

**Comment by Schweinepriester** [comment]
I'd argue that if at all `prefers-dark-interface` should be covered by #4514, as WebKit/Safari is going for that standard and have not exposed it:

https://github.com/w3c/csswg-drafts/issues/2735, esp.
- https://github.com/w3c/csswg-drafts/issues/2735#issuecomment-397881738
- https://github.com/w3c/csswg-drafts/issues/2735#issuecomment-423704374
