### ISSUE TITLE
WebP now in preview in IE Edge

### ISSUE THREAD

**Issue by csuhta** [Fyrd/caniuse#4524]
I'm unsure if this means the v18 cell should be turned fully green yet
https://caniuse.com/#feat=webp
https://github.com/MicrosoftEdge/Status/pull/636

**Comment by Schweinepriester** [comment]
Just checked https://tests.caniuse.com/ & https://www.gstatic.com/webp/gallery/4.webp:

![image](https://user-images.githubusercontent.com/2644614/46531614-2c64ed80-c89e-11e8-9245-c591633a42d7.png)

Really seems to work! I'll create a PR.

**Comment by HM100** [comment]
I would see that update but I’m sick to do it so because I may lose some of my files.
