### ISSUE TITLE
CSS my-sec-counter property is not added

### ISSUE THREAD

**Issue by matiaslopezd** [Fyrd/caniuse#4526]
Add [my-sec-counter](https://www.w3schools.com/cssref/pr_gen_counter-increment.asp)

![image](https://user-images.githubusercontent.com/23618492/46446904-4646e900-c755-11e8-8c89-771fbf196b8e.png)

**Comment by cpplearner** [comment]
It's not a property, but the name of a counter. The info of CSS counters is already available in https://caniuse.com/#feat=css-counters .

And it has nothing to do with hyphens.

**Comment by matiaslopezd** [comment]
Nice! 

@cpplearner sorry i take bad screenshot hahaha :)
