### ISSUE TITLE
Uncited/wrong claim about optimizeLegibility in "High-quality kerning pairs & ligatures" description

### ISSUE THREAD

**Issue by jacecotton** [Fyrd/caniuse#4545]
Not sure if this is the correct place for this, but the description for [High-quality kerning pairs & ligatures (`text-rendering`)](https://github.com/Fyrd/caniuse/blob/master/features-json/kerning-pairs-ligatures.json) erroneously claims that "Newer browsers have this behavior [`optimizeLegibility`] enabled by default." This doesn't appear to be the case: Chrome and Safari both use `auto` as the default, while only Firefox intelligently swaps between them (@ 20px font-size threshold). (In fact, Chrome & Safari treat `auto` as `optimizeSpeed`, see [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-rendering).)

Edit: see also https://stackoverflow.com/questions/52731988/is-it-valid-to-optimize-speed-for-text-rendering-and-then-asynchronously-optimi

**Comment by Fyrd** [comment]
This was added by @FremyCompany in #4324. @FremyCompany care to comment?

**Comment by FremyCompany** [comment]
That was the conclusion we came up with by looking at the Chromium source code at the time. As far as we understood, the property didn't do anything anymore as all browsers now enabled kerning and ligatures by default in all their codepaths in the last two years, and no "optimized" codepath remain in those browsers. 

Let me see if I can find any reference to the property in Google source code, but I think it's dead for all purposes at this point, but maybe we missed some specific thing when we looked at this.

**Comment by jacecotton** [comment]
So... basically, the _effect_ of `optimizeLegibility` is the algorithmic default, but `text-rendering: optimizeLegibility` itself is effectively worthless.

I wonder if this means that explicitly declaring `text-rendering: optimizeSpeed` would improve performance. 🤔A question for a separate forum I suppose.

Thanks for the clarification Fremy!

**Comment by FremyCompany** [comment]
@jacecotton As far as I know you cannot save time by declaring `optimizeSpeed` at this point, as all browsers removed the fast path they previously used. If you disable kerning and ligatures entirely on a page, you might be able to save memory by requiring less font data to be loaded in memory to compute the text layout, but I wouldn't expect any significant cpu improvement. The memory improvement only work if you never use kerning and ligature for a font at all, as a single instance that would will require loading the font data anyway.
