### ISSUE TITLE
ERROR: Failed to get expected ratio values, skipping country when trying to add geographic data

### ISSUE THREAD

**Issue by csnover** [Fyrd/caniuse#4548]
1. Open Settings
2. Enter “Europe” or “North America” in “From geography” box
3. Click “Import”

Expected: Geographic data added
Actual: Alert box “Sorry, no data currently available for this region”

The affected script, request_region_data.php, returns this extra HTML output prior to the JSON data:

```html
<br>Memory used : 0.75MB<br><br>Memory used : 132.50MB<br><br>Memory used : 132.50MB<br><b>Ratio: </b><br>
Console: 0%<br>
Tablet: 0%<br>
ERROR: Failed to get expected ratio values, skipping country<br>
```

This seems related to #3564. Not all regions cause the script to fail; for example, “United States of America” is fine.

**Comment by Fyrd** [comment]
This was fixed some time ago.
