### ISSUE TITLE
View mode doesn't remember settings

### ISSUE THREAD

**Issue by web2033** [Fyrd/caniuse#4557]
The recent update on the site seems changed something in settings.

Previously, I was shown only chosen browsers.
Now, the list is not aligned with what I see in settings.

If toggle one of the settings, it works for a moment, but after page update, it shows a full list of browsers again.

![2018-10-16_220310](https://user-images.githubusercontent.com/11320080/47040862-0a1d7a80-d190-11e8-832e-d6df54b6e9a1.jpg)
![2018-10-16_220245](https://user-images.githubusercontent.com/11320080/47040863-0a1d7a80-d190-11e8-9d69-2891ea160c9c.jpg)

**Comment by Fyrd** [comment]
Right, you'll need to change it to **Show: Filtered** under "Default display settings" to change the default.

**Comment by web2033** [comment]
Ok. There was "All", though I didn't touch it for years.
Now it is saved for future visits.
