### ISSUE TITLE
childElementCount JS property

### ISSUE THREAD

**Issue by matiaslopezd** [Fyrd/caniuse#4558]
![image](https://user-images.githubusercontent.com/23618492/47063380-2a116600-d1b1-11e8-8aaa-1d2bbe21fc53.png)

![image](https://user-images.githubusercontent.com/23618492/47063401-3ac1dc00-d1b1-11e8-8ad3-e72f6d3148a1.png)

**Sorry for not give JSON format, but soon, if I have time can contribute with JSON feature** 👍

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_parentnode_childelementcount
