### ISSUE TITLE
Add support data for window.location.reload()

### ISSUE THREAD

**Issue by StevenWolfe** [Fyrd/caniuse#4560]
`window.location.reload()` appears to be a standardized method to programmatically reload the current URL.  Some browsers also support passing it a boolean parameter, when true it indicates the reload should bypass the browser cache.

Here's a couple links with some notes on the function and parameter:
 -  https://www.w3schools.com/jsref/met_loc_reload.asp
- https://stackoverflow.com/questions/10876244/browser-support-for-window-location-reloadtrue
 - https://developer.mozilla.org/en-US/docs/Web/API/Location/reload

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_location_reload
