### ISSUE TITLE
Not all notes shown in "Show all" mode

### ISSUE THREAD

**Issue by Schnark** [Fyrd/caniuse#4564]
The "Notes" section below the support table does not show all notes in the new "Show all" mode. E.g. https://caniuse.com/#feat=flexbox has only note 4 in that section. The other notes can actually be seen when you hover over the entries that reference them, but that's not very accessible.
As far as I can see, only those notes are shown, that are referenced by an entry for a current browser version, all others are missing.

**Comment by Fyrd** [comment]
Has now been fixed. Thanks for pointing that out!
