### ISSUE TITLE
Uncombined browser versions in "Show all" mode for CSS Grid

### ISSUE THREAD

**Issue by Schnark** [Fyrd/caniuse#4565]
See https://caniuse.com/#feat=css-grid. There are several entries where I don't understand why they are not combined into a single entry: IE 6-8 has one entry, but IE 9 is separate, though I can't see any difference. The same is true for Firefox 2-18/19-39 Chrome 4-24/25-28, etc.
I haven't found any other occurrence of this issue in other tables, so I suspect that there's rather something wrong with the data than with the "Show all" mode.

**Comment by Schnark** [comment]
I found two other instances: https://caniuse.com/#feat=custom-elements and https://caniuse.com/#feat=custom-elementsv1

**Comment by Fyrd** [comment]
Thanks, should be fixed now. The issue was that occasionally the support value is set as "no support but has polyfill" though this isn't visible in the UI. Until that changes I've ensured these are combined with "no support".
