### ISSUE TITLE
Add checking for DataTransfer

### ISSUE THREAD

**Issue by m93a** [Fyrd/caniuse#4569]
When working with drag&drop and the clipboard, one needs to know the support for various methods in the DataTransfer interface, which is currently not checked by *caniuse*.

Documentation on MDN: https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer

**Comment by GPHemsley** [comment]
Looks like this is now covered by MDN data:
https://caniuse.com/mdn-api_datatransfer

(via mdn/browser-compat-data#1762)
