### ISSUE TITLE
Build is throwing error with css-loader as Module build failed: SyntaxError: /app/mint/node_modules/caniuse-db/data.json: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by vijaybarnwal** [Fyrd/caniuse#4572]
Hi team,

in previous versions(<1.0.30000887) data.json is showing as json object file but in newer version it shows as html file due to this change I got below error:
ERROR in ./~/css-loader!./~/react-sugar-ui/lib/style.css
build	23-Oct-2018 06:16:52	Module build failed: SyntaxError: /app/mint/node_modules/caniuse-db/data.json: Unexpected token < in JSON at position 0
build	23-Oct-2018 06:16:52	    at Object.parse (native)
build	23-Oct-2018 06:16:52	    at Object.Module._extensions..json (module.js:558:27)
build	23-Oct-2018 06:16:52	    at Module.load (module.js:458:32)
build	23-Oct-2018 06:16:52	    at tryModuleLoad (module.js:417:12)
build	23-Oct-2018 06:16:52	    at Function.Module._load (module.js:409:3)
build	23-Oct-2018 06:16:52	    at Module.require (module.js:468:17)
build	23-Oct-2018 06:16:52	    at require (internal/module.js:20:19)
build	23-Oct-2018 06:16:52	    at Object.<anonymous> (/app/mint/node_modules/browserslist/index.js:5:15)
build	23-Oct-2018 06:16:52	    at Module._compile (module.js:541:32)
build	23-Oct-2018 06:16:52	    at Object.Module._extensions..js (module.js:550:10)
build	23-Oct-2018 06:16:52	    at Module.load (module.js:458:32)
build	23-Oct-2018 06:16:52	    at tryModuleLoad (module.js:417:12)
build	23-Oct-2018 06:16:52	    at Function.Module._load (module.js:409:3)
build	23-Oct-2018 06:16:52	    at Module.require (module.js:468:17)
build	23-Oct-2018 06:16:52	    at require (internal/module.js:20:19)
build	23-Oct-2018 06:16:52	    at Object.<anonymous> (/app/mint/node_modules/autoprefixer/lib/autoprefixer.js:5:18)
build	23-Oct-2018 06:16:52	    at Object.<anonymous> (/app/mint/node_modules/autoprefixer/lib/autoprefixer.js:92:4)
build	23-Oct-2018 06:16:52	    at Module._compile (module.js:541:32)
build	23-Oct-2018 06:16:52	    at Object.Module._extensions..js (module.js:550:10)
build	23-Oct-2018 06:16:52	    at Module.load (module.js:458:32)
build	23-Oct-2018 06:16:52	    at tryModuleLoad (module.js:417:12)
build	23-Oct-2018 06:16:52	    at Function.Module._load (module.js:409:3)
build	23-Oct-2018 06:16:52	    at Module.require (module.js:468:17)
build	23-Oct-2018 06:16:52	    at require (internal/module.js:20:19)
build	23-Oct-2018 06:16:52	    at Object.<anonymous> (/app/mint/node_modules/cssnano/dist/index.js:45:21)
build	23-Oct-2018 06:16:52	    at Module._compile (module.js:541:32)
build	23-Oct-2018 06:16:52	    at Object.Module._extensions..js (module.js:550:10)
build	23-Oct-2018 06:16:52	    at Module.load (module.js:458:32)
build	23-Oct-2018 06:16:52	    at tryModuleLoad (module.js:417:12)
build	23-Oct-2018 06:16:52	    at Function.Module._load (module.js:409:3)
build	23-Oct-2018 06:16:52	 @ ./~/react-sugar-ui/lib/style.css 4:14-64
build	23-Oct-2018 06:16:52	 @ ./~/react-sugar-ui/lib/Style.js
build	23-Oct-2018 06:16:52	 @ ./~/react-sugar-ui/lib/index.js
build	23-Oct-2018 06:16:52	 @ multi react-sugar-ui

Can someone please help for this issue because we are developing so many applications based on this and all builds are failing?

Please guide me what to do for this issue?
I will appreciate in advance for resolving this issue.

Thanks,
Vijay B

**Comment by vijaybarnwal** [comment]
I am not able to update my package with newer version. After running below command it is installing older one only. How to install latest version?

>> npm install caniuse-db@latest
 caniuse-db@1.0.30000894(Wrong version).

Please guide me how to update with newer version?

Thanks,
Vijay B

**Comment by vijaybarnwal** [comment]
is it published on npm? I am not able to update my package with newer version.

Thanks,
Vijay B

**Comment by carlostxm** [comment]
I'm having the same problem in my project. In my case, caniuse-db is a transitive dependency but last release it's breaking the production build.

**Comment by Fyrd** [comment]
The issue should be fixed in the latest version...try just removing `caniuse-db` and reinstalling.
