### ISSUE TITLE
Intl.RelativeTimeFormat support

### ISSUE THREAD

**Issue by renchap** [Fyrd/caniuse#4587]
TC39 proposal: https://github.com/tc39/proposal-intl-relative-time
Current stage: stage 3
Currently implemented in: Chrome 71

Usage example: https://developers.google.com/web/updates/2018/10/intl-relativetimeformat

**Comment by Schweinepriester** [comment]
+1

<https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/65>

> Intl.RelativeTimeFormat is now supported (bug 1504334).

**Comment by Razican** [comment]
It seems that this is now supported in many browsers: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat#Browser_compatibility

**Comment by Schweinepriester** [comment]
… and even covered on caniuse via MDN: <https://caniuse.com/#search=RelativeTimeFormat>

**Comment by Razican** [comment]
True! I was unable to find it. Thanks! I guess this can be closed, right?

**Comment by Fyrd** [comment]
Yup, available at https://caniuse.com/#feat=mdn-javascript_builtins_intl_relativetimeformat
