### ISSUE TITLE
I cant find figure or mark tags

### ISSUE THREAD

**Issue by shareefhiasat** [Fyrd/caniuse#4588]
Am trying to search for 

> https://caniuse.com/#search=%3Cfigure%3E

`<figure>` but its not found why?! same for `<mark>`

**Comment by cpplearner** [comment]
https://caniuse.com/#feat=html5semantic

needs search result?

**Comment by shareefhiasat** [comment]
I get it now, try <figure> --> no result try figure alone there is result why !?

another example   <section> --> no result try section alone there is result

got it

Regards

**Comment by Ugoku** [comment]
Both are found if you search for `figure` instead of `<figure>`
