### ISSUE TITLE
Ambient Light API Support

### ISSUE THREAD

**Issue by prof3ssorSt3v3** [Fyrd/caniuse#4589]
Available in Firefox currently behind flags
https://developer.mozilla.org/en-US/docs/Web/API/Ambient_Light_Events
and in MS Edge preview
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/ambientlightsensorapi/?q=ambient%20light

**Comment by Fyrd** [comment]
Already exists at https://caniuse.com/#feat=ambient-light

**Comment by prof3ssorSt3v3** [comment]
👍 thx
