### ISSUE TITLE
RadioNodeList

### ISSUE THREAD

**Issue by Yopai** [Fyrd/caniuse#4591]
Hi,

I didn't find access to form.elements[name] as a RadioNodeList.

I learnt about it here : https://stackoverflow.com/a/26236365/2955802
http://jsfiddle.net/vjop5xtq/

The reference docs :
https://developer.mozilla.org/en-US/docs/Web/API/RadioNodeList
https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#radionodelist

It seems it works in all browsers, except (all) IE :
https://stackoverflow.com/q/26677674/2955802

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_radionodelist
