### ISSUE TITLE
PouchDB browser support

### ISSUE THREAD

**Issue by uwajacques** [Fyrd/caniuse#4592]
Would be great to be able to see which versions of which browsers that support PouchDB

**Comment by cpplearner** [comment]
It seems to be a library and is not part of browser, so likely out of scope for caniuse.

**Comment by Malvoz** [comment]
@uwajacques 
https://pouchdb.com/adapters.html#pouchdb_in_the_browser

**Comment by Fyrd** [comment]
Yup, out of scope.

**Comment by uwajacques** [comment]
Got you! Thanks all
