### ISSUE TITLE
VTTRegion is not found in caniuse

### ISSUE THREAD

**Issue by dannyharding10** [Fyrd/caniuse#4600]
I can see WebVTT, but this doesn't necessarily include all of the WebVTT features.  For example in my environment (Electron App) I am able to create a new VTTCue using `new VTTCue()`, but when attempting to create a new VTTRegion using `new VTTRegion()` I get `VTTRegion is not defined`. It would be good if these features were separated in caniuse.

**Comment by Schweinepriester** [comment]
Available via MDN now: <https://caniuse.com/?search=VTTRegion>
