### ISSUE TITLE
Samsung Internet version 8

### ISSUE THREAD

**Issue by poshaughnessy** [Fyrd/caniuse#4602]
Hi again. Thanks for helping us to add new Samsung Internet versions previously, [like last time](https://github.com/Fyrd/caniuse/issues/4331)! 

I thought I should mention that [we now have version 8.x](https://medium.com/samsung-internet-dev/hello-samsung-internet-8-2-beta-521e4b215fb3) (v8.0 is out there already on the Note 9s and v8.2 is in public beta). It's based on Chromium 63.

Please would it be possible to add it to the site when there's a chance? :)

**Comment by HM100** [comment]
Em why are you basing chromium versions that are older than a year. M63 is way old IMO

**Comment by Ugoku** [comment]
Related: right now, caniuse has 7.2 as latest version, but our Analytics show a large number of 7.4 users. @poshaughnessy can you list what has changed between 7.2 and 7.4 ?

**Comment by poshaughnessy** [comment]
@Ugoku Hi, I don't work at Samsung anymore, so not the best person to give updates going forwards, but yes 7.4 is a newer minor version compared to v7.2. It uses the same underlying Chromium engine (M59), so the support data for 7.2 and 7.4 should be the same*. [Here is more info on what was introduced in v7.4](https://medium.com/samsung-internet-dev/samsung-internet-7-4-is-stable-lets-check-out-what-s-new-d5c7b56897de) if you're interested - it's new browser features rather than browser engine / dev updates. This issue is for the major update v8 which has a newer Chromium engine (M63) than v7.x.

*Or essentially the same - I am not aware of / cannot recall specific support differences, but you could direct questions to the [Samsung Internet team](https://twitter.com/samsunginternet) if you need to double-check something.

**Comment by Fyrd** [comment]
8.2 has now been added. Additionally 7.2 now appears as 7.2-7.4.
