### ISSUE TITLE
Nested position sticky on Edge

### ISSUE THREAD

**Issue by IlCallo** [Fyrd/caniuse#4604]
It's broken.

[Related issue](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18940617/)

**Comment by Schweinepriester** [comment]
Sadly the linked issue isn't available anymore ([neither in the archive](https://web.archive.org/web/*/https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18940617/)). Given the obsoleteness of EdgeHTML and that it's marked at most partial anyway
https://github.com/Fyrd/caniuse/blob/d829111f2169f8a5623e3221385c1d893d83b16b/features-json/css-sticky.json#L54-L60
maybe this issue can be closed? 0:-)

**Comment by IlCallo** [comment]
I guess it's a good thing it doesn't exist anymore :)
