### ISSUE TITLE
webp Firefox Nightly needs a config setting

### ISSUE THREAD

**Issue by Djfe** [Fyrd/caniuse#4608]
Someone could add a bit of info to this page:
https://caniuse.com/#feat=webp
image.webp.enabled needs to be set to true for webp to be decoded in Firefox 65 atm.

Regards :)

**Comment by Ugoku** [comment]
It seems Firefox 65 will enable this by default:
* https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/65#Other
* https://twitter.com/jensimmons/status/1086275808740679680

**Comment by Mikaela** [comment]
Firefox 65 was released yesterday and has it enabled by default. However the website doesn't seem to be aware of that yet.

**Comment by XhmikosR** [comment]
This can be closed AFAICT.

**Comment by Djfe** [comment]
true that
