### ISSUE TITLE
Support for RegExp Named Capture Groups

### ISSUE THREAD

**Issue by maple3142** [Fyrd/caniuse#4609]
https://github.com/tc39/proposal-regexp-named-groups is a stage-4 javascript proposal, and it has been implemented in chromium. (But not firefox and else...)

**Comment by dlinch** [comment]
I second this. I just shipped a feature using named capture groups and it worked in Chrome but broke in Firefox so I had to roll it back.

**Comment by nrhoffmann** [comment]
This has been added. https://caniuse.com/?search=RegExp%20named%20groups

**Comment by Fyrd** [comment]
Closing as per last comment
