### ISSUE TITLE
mobile IE does not support font face

### ISSUE THREAD

**Issue by evantill** [Fyrd/caniuse#462]
## font faces are note supported on Windows phone 7.x and 8.0.

see `stackoverflow` question on [font-face-not-working-in-internet-explorer-mobile](http://stackoverflow.com/questions/11522480/font-face-not-working-in-internet-explorer-mobile)

extract from [msdn.microsoft.com](http://msdn.microsoft.com/en-us/library/windowsphone/develop/ff462082)

### Unsupported Features in Internet Explorer Mobile

The following features are supported in the desktop version of Internet Explorer 9, and not in Internet Explorer Mobile.

- …
- Downloadable fonts such as EOT, TTF/OTF and WOFF fonts
- …

**Comment by pkuczynski** [comment]
@Fyrd, I looked at this issue, but version 9 is not listed in "ie_mob" section. Shall this be added or ignored (closing this issue)? I feel that it should be added as there are still quite a few people with WP7 devices...

**Comment by Fyrd** [comment]
Have added a note on this for now. Don't have access to a phone with IE Mobile 9 so until I do I don't intend to add it. Also usage is pretty slim, so I can't imagine anyone not using @font-face just because of this.
