### ISSUE TITLE
Add composedPath()

### ISSUE THREAD

**Issue by moezzie** [Fyrd/caniuse#4622]
When working with shadowDom event.composedPath() is a pretty commonly used method.
According to MDN all major browsers except for Edge currently have support.

[https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath](https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath)

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_event_composedpath
