### ISSUE TITLE
Add Array.prototype.flatMap

### ISSUE THREAD

**Issue by shuch** [Fyrd/caniuse#4639]
add support for [Array.prototype.flatMap()
](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap)

**Comment by cpplearner** [comment]
duplicate of #4294?

**Comment by shuch** [comment]
the same with [#4294](https://github.com/Fyrd/caniuse/issues/4294)
