### ISSUE TITLE
CSS max-lines

### ISSUE THREAD

**Issue by thany** [Fyrd/caniuse#4661]
Add a feature entry for [max-lines](https://www.w3.org/TR/css-overflow-3/#max-lines).

Currently not supported by any living browser, afaik. It seems like this will be the standards version of line-clamping in WebKit, so the `max-lines` keyword could also be added to `line-clamp` with a note to it not being supported anywhere yet, and an extra resource link: https://www.w3.org/TR/css-overflow-3/#max-lines

**Comment by Fyrd** [comment]
Search result now added at https://caniuse.com/sr_css-max-lines. If browsers actually start work on supporting the property I'll replace that with a real support table.
