### ISSUE TITLE
Add Waterfox to browser list

### ISSUE THREAD

**Issue by hook54321** [Fyrd/caniuse#4666]
https://www.waterfoxproject.org/

**Comment by HM100** [comment]
Also based on Gecko

**Comment by hook54321** [comment]
As development continues there will probably be some things that aren't supported due to privacy, security, etc concerns (there might be some already).

**Comment by Fyrd** [comment]
As with seamonkey, not different enough from Firefox nor enough usage to warrant including.

**Comment by a8nJ** [comment]
https://github.com/Fyrd/caniuse/issues/5675

**Comment by IzzySoft** [comment]
@Fyrd certainly huge differences to Firefox, and certainly well used – just take a look into the issue trackers of GitLab or Stack Exchange concerning Waterfox Classic (both responded to the issues and deemed it warranting adjustment). And depending on what flavors are used, there are even huge differences between Waterfox Classic (still supporting XUL Extensions aka "legacy") and G4 (based on the latest Firefox ESR). So please reconsider, as this also affects users of Nextcloud (addressbook, see https://github.com/nextcloud/contacts/issues/2833).

For identification:

* Classic: `Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0 Waterfox/56.6.2022.06`
* G4: `Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0 Waterfox/91.11.0`

So it would probably be something like `useragent.contains('Waterfox/56')` to match Classic, which is the crucial one here (G4 might be close enough to Firefox as it's based on the latest ESR, but I'm not 100% sure with that).

**Comment by BillFleming** [comment]
This should be reconsidered to include Waterfox. The latest version 6.6.x now by default supports HEVC video and JPEG XL has been supported OOTB for a long time already (several years). I tested a homemade 6.6.2 build for Aarch64 even and a Main10 profile HDR10 3840x2160 test video ran with full HW acceleration 60fps with no dropped frames, no special configuration or tweaking to the web browser's build configuration or settings. No problem opening 30+MP JPEG XL photos either. However, 10-bit 4096x2160x60 from a Sony Cinema camera will probably still not work, and isn't supported on most GPU's HW acceleration properly yet.
