### ISSUE TITLE
Add Background Fetch

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#4669]
- Spec: <https://wicg.github.io/background-fetch/>
- <https://github.com/WICG/background-fetch>
- <https://www.chromestatus.com/feature/5712608971718656>
- <https://developers.google.com/web/updates/2018/12/background-fetch>

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_backgroundfetchevent
