### ISSUE TITLE
Add Object.fromEntries

### ISSUE THREAD

**Issue by garycourt** [Fyrd/caniuse#4671]
Requesting support for `Object.fromEntries`. It is, at the time of filing this issue, in Stage 3, and Firefox currently has support for it.

https://github.com/tc39/proposal-object-from-entries
https://tc39.github.io/proposal-object-from-entries/
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries

**Comment by Schweinepriester** [comment]
<https://kangax.github.io/compat-table/esnext/#test-Object.fromEntries>

**Comment by wordgame** [comment]
Object.fromEntries() his has been added to Chrome 73/v8 7.3 as of February 7th.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_builtins_object_fromentries
