### ISSUE TITLE
TLS 1.3 can be enabled in Safari

### ISSUE THREAD

**Issue by SharkMachine** [Fyrd/caniuse#4677]
According to multiple sources, TLS 1.3 can be enabled in Safari with the following command

```sh
sudo defaults write /Library/Preferences/com.apple.networkd tcp_connect_enable_tls13 1
```

It can be enabled in iOS version as well (more info in the sources at the end)

That is not shown @ caniuse.com

![image](https://user-images.githubusercontent.com/7488694/49967113-98ad3e80-ff2a-11e8-8ccb-e8a4b1a00d3e.png)

https://superuser.com/questions/1217220/how-do-i-enable-tls-1-3-in-ios-and-macos
https://geekflare.com/enable-tls-1-3-in-browsers/
https://www.ietf.org/mail-archive/web/tls/current/msg23599.html

**Comment by daytonlowell** [comment]
@SharkMachine Do you know what versions of macOS is this supported in? Is it Mojave-only?

@Fyrd Do we consider a `defaults write` to be a flag? It's not a traditional browser flag.

**Comment by reaperhulk** [comment]
TLS 1.3 is enabled by default in Safari 12.1 on macOS 10.14.4. I don't have access to any machines to test on 10.13 or 10.12 though.

**Comment by daytonlowell** [comment]
Do you have a source link? I looked through release notes and such and didn’t see anything related to TLS 1.3

**Comment by reaperhulk** [comment]
Yeah it's not in the release notes 🤷‍♂️ but it's easily confirmed via https://www.ssllabs.com/ssltest/viewMyClient.html or https://tls13.akamai.io or a wireshark capture. Of course, none of those are useful if you're not running on a mac. Maybe others can chime in or find a resource that actually documents this.

**Comment by daytonlowell** [comment]
Oh cool. I just went to that page in iOS 12.2 and it’s got TLS 1.3 as well. I’ll make a PR on this.
