### ISSUE TITLE
<virtual-scroller>

### ISSUE THREAD

**Issue by Malvoz** [Fyrd/caniuse#4678]
Tracking progress/implementations of HTML element `<virtual-scroller>` (or [`<virtual-content>`](https://github.com/valdrinkoshi/virtual-scroller/blob/master/README.md#virtual-content)):

Explainer:
https://github.com/valdrinkoshi/virtual-scroller/blob/master/README.md

Chrome dev summit explainer video:
https://www.youtube.com/watch?v=UtD41bn6kJ0

Chrome status:
https://www.chromestatus.com/feature/5673195159945216

**Comment by Schweinepriester** [comment]
<https://github.com/WICG/virtual-scroller#current-status>:

> This project is no longer being actively developed. Instead we are pursuing primitives [here](https://github.com/WICG/display-locking).

<https://chromestatus.com/feature/5673195159945216>:

> Implementation status: No longer pursuing ([tracking bug](https://bugs.chromium.org/p/chromium/issues/detail?id=979108))
