### ISSUE TITLE
<portal> & Portals API

### ISSUE THREAD

**Issue by Malvoz** [Fyrd/caniuse#4679]
Explainer for the `<portal>` HTML element:
https://github.com/WICG/portals/blob/master/explainer.md

Specification:
https://wicg.github.io/portals/

Chrome dev summit explainer video:
https://www.youtube.com/watch?v=Ai4aZ9Jbsys&t=17m00s

Chrome status:
https://www.chromestatus.com/feature/4828882419056640

**Comment by Naismith** [comment]
Chrome Canary now supports Portals behind a feature flag. I feel this should be added.

https://web.dev/hands-on-portals/

**Comment by Schweinepriester** [comment]
+1

**Comment by yareckon** [comment]
+1

**Comment by ofekshmuely** [comment]
https://www.youtube.com/watch?v=X2zqwMBBvIs

**Comment by boaz-amit** [comment]
This is currently a proprietary Chrome feature. It's not a standard or even a standard in the making: https://wicg.github.io/portals/

> It is not a W3C Standard nor is it on the W3C Standards Track

**Comment by Malvoz** [comment]
@boaz-amit while I don't know [W3C Process](https://www.w3.org/2019/Process-20190301/) by heart, usually (if not all) proposals start off as non-standard. However, that is irrelevant, as browsers are free to implement non-standard features.

**Comment by herohamp** [comment]
I feel this should be added as while it is not a web standard it is a feature that will be used by developers

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=portals
