### ISSUE TITLE
Tracking of the asynchronous cliboard API

### ISSUE THREAD

**Issue by stof** [Fyrd/caniuse#4680]
The asynchronous clipboard API is not available on caniuse.com while it looks like #4302 added data for it.
It would be great if this data could come online.

**Comment by jimwe** [comment]
This is a great feature and hopefully it will gain acceptance and be fully implemented by major browser vendors. Maybe exposing it on caniuse will help give it a boost.

**Comment by stof** [comment]
@Fyrd this is not a support data suggestion. The data is already available in this repo since 1 year (it might need an update now though). the issue is that it is not rendered on the website.

**Comment by Fyrd** [comment]
Data has been reviewed and updated (sorry for the delay) and is now available at https://caniuse.com/async-clipboard
