### ISSUE TITLE
List of supported browsers and its shortcuts in stats key

### ISSUE THREAD

**Issue by darkowic** [Fyrd/caniuse#4681]
Would be great to have a list of supported browsers and its shortcuts under 'stats' keys in data.

I use browserslist to generate a list of supported browser and I have to map the data to another format. Example output is
```
and_chr 64
chrome 65
chrome 64
edge 16
firefox 59
firefox 58
ios_saf 11.3
ios_saf 11.0-11.2
ios_saf 10.3
ios_saf 10.0-10.2
safari 11.1
safari 11
safari 10.1
safari 10
samsung 6.2
```

**Comment by Fyrd** [comment]
Since this can already be programmatically deduced I don't see a need to include it in the data.
