### ISSUE TITLE
Add .avif (AV1 Image File Format) support

### ISSUE THREAD

**Issue by EwoutH** [Fyrd/caniuse#4684]
The AV1 Image File Format (AVIF) is a new image format based on the AV1 video codec. It would be great if support for this format could be added.

The AVIF spec can be found here: https://aomediacodec.github.io/av1-avif/

Netflix published a bunch of test images: http://download.opencontent.netflix.com/?prefix=AV1/Chimera/AVIF/

**Comment by EwoutH** [comment]
Mozilla is planning to support it in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1443863

**Comment by EwoutH** [comment]
Microsoft is also going to [support AVIF](https://www.reddit.com/r/AV1/comments/a9r657/windows_10_19h1_preview_release_supports_avif_in/) in Windows 10 (and so probably Edge).

**Comment by o-l-a-v** [comment]
Avif 1.0 is released, so it's definitly a thing now.
* https://aomediacodec.github.io/av1-avif/
* https://www.phoronix.com/scan.php?page=news_item&px=AV1-Image-Format-v1.0

**Comment by Schweinepriester** [comment]
+1

Polyfill: <https://github.com/Kagami/avif.js> (via https://twitter.com/smashingmag/status/1108116434197069825)

**Comment by EwoutH** [comment]
[libavif](https://github.com/joedrago/avif) tagged a new release, [0.1.3](https://github.com/joedrago/avif/releases/tag/v0.1.3). See [Colorist](https://github.com/joedrago/colorist) for an example [implementation](https://github.com/joedrago/colorist/blob/master/lib/src/format_avif.c).

**Comment by jensimmons** [comment]
+1

**Comment by Mithgol** [comment]
+1

**Comment by est31** [comment]
+1

**Comment by cesarchefinho** [comment]
+1

**Comment by PrOOnOOb** [comment]
+1

**Comment by EwoutH** [comment]
There's active work on supporting AVIF in Chromium!

- [1707404: Add support for decoding the AV1 image format (AVIF).](https://chromium-review.googlesource.com/c/chromium/src/+/1707404)
- [2101317: A copy of Dale Curtis's AVIF prototype.](https://chromium-review.googlesource.com/c/chromium/src/+/2101317)

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/#feat=avif
Thanks for the info, folks!

**Comment by ve3** [comment]
It seems that not all type of AVIF images are supported and be able to display on all major browsers (tested on Firefox, Edge, Chrome).

Here is a link for [sample images](https://github.com/link-u/avif-sample-images). Here is [an issue](https://github.com/link-u/avif-sample-images/issues/2) about render image on browser.

Maybe change from support to be partial support?
