### ISSUE TITLE
input-pattern no longer seems to be valid

### ISSUE THREAD

**Issue by pimlottc-gov** [Fyrd/caniuse#4685]
The `pattern` attribute for `<input>` no longer seems to be supported.  It is no longer included in the [MDN docs page for <input>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-pattern) and does not seem to work in Chrome, Firefox or Safari on my computer. 

Test case: 
https://jsfiddle.net/yyvrz84v/

Browsers tested:
* Chrome 70.0.3538.110 (Official Build) (64-bit)
* Firefox 64.0 (64-bit)
* Safari 11.1.1 (13605.2.8)

https://caniuse.com/#feat=input-pattern

**Comment by cpplearner** [comment]
AFAICS browsers (tested Chrome 71.0.3578.98 and Firefox 66.0a1) do recognize this attribute, in the sense that when I type an invalid value,
- a message is displayed when I hover over the input
- the input matches the `:invalid` CSS selector
- Firefox also displays red shadow around the input when the input loses focus

and the constraint validation API works just as expected.

They just don't stop me when I am typing.

Also the MDN doc for `pattern` isn't removed. It's just moved to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text#pattern.

**Comment by Fyrd** [comment]
Yup, @cpplearner is correct. I believe it just doesn't work the way you may expect it to.

**Comment by pimlottc-gov** [comment]
Okay, thanks for pointing this out.  The StackOverflow post that informed me about the `pattern` attribute led me to believe it operated automatically, actively preventing invalid characters from being entered, but I guess I read too much into it.
