### ISSUE TITLE
edge is switching to blink

### ISSUE THREAD

**Issue by jimmywarting** [Fyrd/caniuse#4703]
...many feature will become available but some stuff will also be removed when they switch to blink.
Some question i have is

- Will Microsoft change the name & logo to something else... again?
- Will there ever be a Edge v19 and will it be blink or same old engine?
- When (or in which version) will they switch to blink?

**Comment by Fyrd** [comment]
These are some good questions that I have too (I don't think Microsoft's answered them yet), but I don't think this is the right place to be asking them. :)
