### ISSUE TITLE
Named Capture Groups

### ISSUE THREAD

**Issue by Lonniebiz** [Fyrd/caniuse#4704]
The 2018 Ecmascript specification specifies support for [named capture groups](https://flaviocopes.com/javascript-regular-expressions/#named-capturing-groups) in regular expressions.

I can't find browser-coverage for this feature on caniuse.com:

https://caniuse.com/#search=namedcapturegroups

I also posted a [question on stackoverflow.com](https://stackoverflow.com/questions/54004717/test-browser-compatibility-for-new-regular-expression-features) asking about the best practice for testing for these new regEx features. Maybe someone will offer a non-obvious suggestion.

**Comment by daytonlowell** [comment]
I would maybe bring up an issue with https://github.com/kangax/compat-table which is what caniuse usually references for such specific es features.

**Comment by tomByrer** [comment]
Almost the end of 2019, & Firefox still doesn't have this:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp

Ah well, maybe time to switch to Brave....

**Comment by Lonniebiz** [comment]
@tomByrer Do like me and post a disgusted comment here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1225665

**Comment by tomByrer** [comment]
Seems there is auto-imports from MDN compat tables, so the info does show up:
https://caniuse.com/#search=named%20capture
(TBH, I think this is the best way to go; have 1 source of truth.)
I'm fine if @Fyrd closes this issue.

@Lonniebiz No point in 'making noise', they already said "[We're working on this](https://bugzilla.mozilla.org/show_bug.cgi?id=1367105)."  I prefer not to bug them, & I'm already 1/2 switched to Vivaldi for dev work.

**Comment by Fyrd** [comment]
As mentioned above, now available at https://caniuse.com/#feat=mdn-javascript_builtins_regexp_named_capture_groups
