### ISSUE TITLE
Case-sensitive CSS attribute selectors

### ISSUE THREAD

**Issue by chharvey** [Fyrd/caniuse#4710]
Recommending to add data for case-*sensitive* matching of CSS attribute selectors along with [**Case-insensitive CSS attribute selectors**](https://caniuse.com/#feat=css-case-insensitive).

By default, case-sensitivity depends on document language, so in cases (no pun intended) where the document language specifies a case-insensitive attribute, such as `ol[type]`, the case-sensitivity of the CSS attribute selector may be enabled with the `s` identifier.

In other words, `s` has the opposite effect of `i`.

From the [CSS Selectors 4](https://www.w3.org/TR/selectors-4/#attribute-case) spec:

> The attribute selector may include the identifier `s` before the closing bracket (`]`); in this case the UA must match the value case-sensitively (if possible) regardless of document language rules.
> …
> Example 23: The following rule will style lists with `type="a"` attributes differently than `type="A"` even though [HTML defines the `type` attribute to be case-insensitive](https://www.w3.org/TR/html52/matching-html-elements-using-selectors.html#matching-html-elements-using-selectors).
> ```
> [type="a" s] { list-style: lower-alpha; }
> [type="A" s] { list-style: upper-alpha; }
> ```

This may be merged into #1058 if necessary.

**Comment by Malvoz** [comment]
+1

**Comment by HM100** [comment]
Later FX prerelease versions have it added so support

**Comment by HM100** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

<https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/66>

> Implemented the case-sensitive attribute selector modifier (bug 1512386).

**Comment by ExE-Boss** [comment]
needinfo?(@jpmedley): What is Chrome’s status on supporting this?

**Comment by jpmedley** [comment]
I can't get s or i to work in Chrome. I'd have to say, not supported.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-css_selectors_attribute_case_sensitive_modifier
