### ISSUE TITLE
Add page for HEIC image format

### ISSUE THREAD

**Issue by mirraj2** [Fyrd/caniuse#4721]
HEIC is the default format when downloading photos from Google Photos.

**Comment by HM100** [comment]
Is it supported by any browser?

**Comment by Ugoku** [comment]
HEIC = HEIF, which is on the site: https://caniuse.com/#search=HEIF

Maybe HEIF can get HEIC as search alias?

**Comment by Fyrd** [comment]
Added as alias to HEIF as per suggestion.
