### ISSUE TITLE
Add `console.table`

### ISSUE THREAD

**Issue by yemartin** [Fyrd/caniuse#4725]
I just discovered `console.table` thanks to this blog post:

https://dev.to/denisepen/consoletable-25l8

and it just blew my mind! It has been around for over 4 years now (since Firefox 34?). Details:

https://developer.mozilla.org/en-US/docs/Web/API/Console/table

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_console_table
