### ISSUE TITLE
Object.isnt isn't real

### ISSUE THREAD

**Issue by Gerrit0** [Fyrd/caniuse#4728]
This came up while I was searching for another object method, it gave me a good laugh, but I'm pretty sure it shouldn't be there.

There's no builtin entry, but it points to the ES6 table which doesn't list the method, it also has no entry on MDN.

https://caniuse.com/#search=object.isnt
http://kangax.github.io/compat-table/es6/#test-Object.isnt

**Comment by Ugoku** [comment]
`Object.isnt` was discussed in 2012, but not added in 2013: https://bugzilla.mozilla.org/show_bug.cgi?id=839979

**Comment by Fyrd** [comment]
Yeah, was based on old data. Thanks, has been removed!
