### ISSUE TITLE
Include / support Cordova and webViews

### ISSUE THREAD

**Issue by cdcv** [Fyrd/caniuse#4730]
Many apps these days use cordova / webviews within them - basically a browser within the mobile app.  It would be very helpful to many people to know which browser functionality is supported within these contexts, both on Android and on iOS.  Thanks!

**Comment by Fyrd** [comment]
Currently the "Android Browser" and "iOS Safari" columns cover webviews as well, when there's differences between the browsers and the webviews they're mentioned in the notes.
