### ISSUE TITLE
Imported from Google Analytics: Samsung browsers missing

### ISSUE THREAD

**Issue by jamespamplin** [Fyrd/caniuse#4742]
All stats from any Samsung browser are missing when importing from Google analytics. Is it possible to add some support for this? Our usage for Samsung Internet 8.2 are at 3.8% which makes it relevant.

I tend to use this data for both the https://caniuse.com website, and using the browserslist tool. Originally noticed this issue when using the `browserslist-ga` tool, see: browserslist/browserslist-ga#8

In addition, would be great to get support in for Samsung Internet v8: Fyrd/caniuse#4602

Thanks so much for all your hard work on this wonderful tool!

![caniuse-import-from-ga-2019-01-28](https://user-images.githubusercontent.com/2298529/51818740-e0fca200-22c7-11e9-9eee-8d527bb491d6.png)

**Comment by Ugoku** [comment]
I will second this. Unimported browsers account for nearly 10% of a certain website I manage, which is mostly Samsung browser.

**Comment by Fyrd** [comment]
Thanks for reporting this. Should now be fixed!

**Comment by jamespamplin** [comment]
Thanks so much @Fyrd, all working now, showing ~98% total including Samsung 8.2 😄 

![image](https://user-images.githubusercontent.com/2298529/52288771-b4e6be00-2964-11e9-9feb-fb5a20623813.png)
