### ISSUE TITLE
W3 DOM2

### ISSUE THREAD

**Issue by jeandcr** [Fyrd/caniuse#4747]
Dear caniuse,

I have a request to maybe add the [W3 DOM Level 2](https://www.w3.org/TR/2003/REC-DOM-Level-2-HTML-20030109/DOM2-HTML.html) and it's browser support.

I found some use cases and examples where it has been mentioned to be working from **IE7+**.

The main use case is when you're trying to access an HTMLElement, or trying to validate the type of HTMLElement. I myself use it for validating form submissions, and thereby checking the element i pass to my validating script.

Thanks in advance, and keep up the good work !

**Comment by Fyrd** [comment]
I suspect everything in this old spec is supported in effectively all browsers tracked on caniuse. Is there a particular API you've noticed that doesn't work somewhere?

**Comment by Fyrd** [comment]
Especially with MDN data I'm fairly certain all of DOM2 is covered, so closing this issue.
