### ISSUE TITLE
Update HEIF support

### ISSUE THREAD

**Issue by marzn** [Fyrd/caniuse#4749]
Actually https://caniuse.com/#feat=heif states, that HEIF is not supported by any browser. At least Firefox and Chrome support HEIF. I will provide a PR later.

**Comment by marzn** [comment]
May my tests were not correct, cause I tested it with https://compare.rokka.io/_compare/ which draws the HEIF images via a canvas element and therefor it is no native support by the browser.

**Comment by Fyrd** [comment]
Alright, thanks for confirming.
