### ISSUE TITLE
Add scroll-padding

### ISSUE THREAD

**Issue by hunboy** [Fyrd/caniuse#4767]
https://drafts.csswg.org/css-scroll-snap-1/#scroll-padding

Add new feature to caniuse. it is supported by chrome, safari perhaps already

**Comment by Dantemss** [comment]
Somewhat supported on Safari, as I mentioned here: https://github.com/mdn/browser-compat-data/issues/4497
Firefox 68 also adds (some?) support.

**Comment by Schweinepriester** [comment]
Available via MDN now: https://caniuse.com/?search=scroll-padding
