### ISSUE TITLE
Show WebComponents v1 before WebComponents v0

### ISSUE THREAD

**Issue by ExE-Boss** [Fyrd/caniuse#4770]
Right now, searching for “[custom&nbsp;elements](https://caniuse.com/#search=custom%20elements)” or&nbsp;“[shadow&nbsp;dom](https://caniuse.com/#search=shadow%20dom)” shows support for the obsolete WebComponents&nbsp;v0 before the standard WebComponents&nbsp;v1, which is&nbsp;unhelpful, given that WebComponents&nbsp;v0 is&nbsp;obsolete and will soon be&nbsp;fully removed from all&nbsp;browsers.

**Comment by Fyrd** [comment]
Good call out, thanks. Made a few updates to ensure the order is reversed and made it clearer that the V0 ones are deprecated.
