### ISSUE TITLE
Array.prototype.indexOf()

### ISSUE THREAD

**Issue by nikitahl** [Fyrd/caniuse#4775]
Currently indexOf query returns 5 results but none of them is Array.prototype.indexOf()

[MDN Array.prototype.indexOf()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf)
> The indexOf() method returns the first index at which a given element can be found in the array, or -1 if it is not present.

![screenshot 2019-02-17 at 23 17 22](https://user-images.githubusercontent.com/12826823/52919353-44e41a80-330a-11e9-9cc8-a4ca6d192c3c.png)

**Comment by HM100** [comment]
Seems for IE it is at version 9 and firefox at least supported in all versions (1.5+). Unsure about opera, safari and chrome

**Comment by HM100** [comment]
Unfortunately not fully since MDN suggests that IE8- does not appear to support it

**Comment by Fyrd** [comment]
You're right, jumped the gun a bit there

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_builtins_array_indexof
