### ISSUE TITLE
Are continents data gone forever?

### ISSUE THREAD

**Issue by meduzen** [Fyrd/caniuse#4796]
Hi! Since data update 6d740c2, the only non-country data (e.g. Europe, Asia, Worldwide) I can find is Antartica (`alt-an.json`). Others are gone from the repository.

Is there any explanation or things to know about these disappeared `alt-stuff`? Is that on purpose?

Thanks to the contributors for their work! I’ll share my side-project that uses caniuse data somewhere this year. :)

**Comment by Fyrd** [comment]
I believe around that time I had to switch the method in which I was gathering data from StatCounter and the new API only provides data for countries, not continents. There may be something to be done about it but it hasn't been a priority.

Look forward to hearing about your side-project. :)

**Comment by meduzen** [comment]
I think this is solved since a while. At least it does on [_Can I Stop_](https://canistop.net/?regions=alt-af,alt-an,alt-as,alt-eu,alt-na,alt-oc,alt-sa,alt-ww) ✌️.
