### ISSUE TITLE
Canvas HitRegions API

### ISSUE THREAD

**Issue by fr0** [Fyrd/caniuse#4800]
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/addHitRegion
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/removeHitRegion
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/clearHitRegions

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_canvasrenderingcontext2d_addhitregion etc
