### ISSUE TITLE
Add CSS Nesting

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#4803]
Spec: <https://drafts.csswg.org/css-nesting-1/>

<https://cssdb.org/#nesting-rules>

<https://twitter.com/Fyrd/status/1103820945758674944> B-)

Chrome bug: <https://bugs.chromium.org/p/chromium/issues/detail?id=1095675>

Firefox bug: <https://bugzilla.mozilla.org/show_bug.cgi?id=1648037>

Safari bug: <https://bugs.webkit.org/show_bug.cgi?id=223497>

**Comment by edouard-lopez** [comment]
I was looking for info about this and can't find any on CanIUse despite the fact the proposal being [merged ~2 years ago](The https://github.com/w3c/csswg-drafts/pull/2878). 

The process on adding information is foreign to me, but should this be added under `other` or `unoff` status?

**Comment by Pomax** [comment]
As update to this, https://www.w3.org/TR/css-nesting-1 is now a public working draft.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/css-nesting

**Comment by BenjaminAster** [comment]
CSS Nesting [is now available](https://bugs.chromium.org/p/chromium/issues/detail?id=1095675#c13) in Chromium 109.0.5368.0 with the experimental web platform features flag enabled.

**Comment by Schweinepriester** [comment]
@BenjaminAster PR is ready https://github.com/Fyrd/caniuse/pull/6500

**Comment by BenjaminAster** [comment]
@Schweinepriester Oh, didn't see that, thanks!
