### ISSUE TITLE
CSS :is()

### ISSUE THREAD

**Issue by calvinjuarez** [Fyrd/caniuse#4805]
Apparently `:matches()` was renamed to `:is()`.  `:is()` should get its own feature entry tracking adoption of the latest spec.

See:
* https://github.com/w3c/csswg-drafts/issues/3258, especially https://github.com/w3c/csswg-drafts/issues/3258#issuecomment-438742190
* https://developer.mozilla.org/en-US/docs/Web/CSS/:is

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-css_selectors_is
