### ISSUE TITLE
Import maps

### ISSUE THREAD

**Issue by kevinkassimo** [Fyrd/caniuse#4810]
> Import maps are essentially a mechanism by which developers can alias import identifiers to one or more alternate identifiers.

[WICG import-maps proposal information](https://github.com/WICG/import-maps)
[Progress of implementation in Chrome](https://www.chromestatus.com/feature/5315286962012160)
Also mentioned in [KV Storage builtin module post](https://developers.google.com/web/updates/2019/03/kv-storage)

**Comment by joeldenning** [comment]
Any update on this?

**Comment by mudgen** [comment]
Can import maps be added?

**Comment by achenwei-chwy** [comment]
just curious the reason that this is ignored for so long? really useful info if its made avaialble.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/import-maps
