### ISSUE TITLE
CSS Shadow Parts

### ISSUE THREAD

**Issue by fgirardey** [Fyrd/caniuse#4811]
It has just land into Chrome 73 so it might be good to add it to caniuse ^^

> This specification defines the ::part() pseudo-element on shadow hosts, allowing shadow hosts to selectively expose chosen elements from their shadow tree to the outside page for styling purposes.

https://www.w3.org/TR/css-shadow-parts-1/

**Comment by sghoweri** [comment]
+1 this -- looks like Safari 13.1 (which _just_ shipped in iOS 13.4 + MacOS 10.15.4) added support for CSS Shadow Parts! 🎉

https://developer.apple.com/documentation/safari_release_notes/safari_13_1_beta_release_notes#3544471

**Comment by fgirardey** [comment]
It seems to be supported through MDN browser-compat-data now : https://caniuse.com/#feat=mdn-css_selectors_part
