### ISSUE TITLE
Safari 12 doesn't support SameSite cookie attribute properly

### ISSUE THREAD

**Issue by fjsj** [Fyrd/caniuse#4813]
There's a [iOS Safari 12 issue](https://bugs.webkit.org/show_bug.cgi?id=188165) that prevents common flows (sequences of requests) to work properly if there's `SameSite=lax` on cookies. This issue was [confirmed by Daniel Bates, from Apple](https://bugs.webkit.org/show_bug.cgi?id=188165#c27) and it's still open.

Therefore, in my opinion, Safari 12 support of 'SameSite' cookie attribute should be `Partial`.

**Comment by fjsj** [comment]
Issue confirmed again by WebKit team: https://bugs.webkit.org/show_bug.cgi?id=196375

**Comment by Sora2455** [comment]
Safari 12 also treats `SameSite=None` as `SameSite=Strict` ([bug](https://bugs.webkit.org/show_bug.cgi?id=198181)), which is going to make Chrome's plan to [make SameSite cookies lax by default](https://www.chromestatus.com/feature/5088147346030592) rather painful...
