### ISSUE TITLE
WebGPU support

### ISSUE THREAD

**Issue by josephg** [Fyrd/caniuse#4815]
> The WebGPU API is the successor to the WebGL and WebGL 2 graphics APIs for the Web. It will provide modern features such as “GPU compute” as well as lower overhead access to GPU hardware and better, more predictable performance. WebGPU is being developed by the “GPU for the Web” W3C community group.

https://www.chromestatus.com/feature/6213121689518080

**Comment by guidorice** [comment]
Couple of announcements last week
https://www.youtube.com/watch?v=K2JzIUIHIhc
https://medium.com/@babylonjs/webgpu-is-coming-to-babylon-js-c44f8065ac05

**Comment by adamjcook** [comment]
Microsoft Edge (Chromium-based) Team just added their WebGPU implementation behind an experimental flag a couple of weeks ago: https://twitter.com/msedgedev/status/1207045142709846016

**Comment by tglines** [comment]
👍 for adding WebGPU status.  Went to the website for can I use hoping to find the current state of implementation.  Even if something's not implemented in any browser I'd like to see a nice row of red for the feature being available in modern browsers.
