### ISSUE TITLE
Feature request: Email client html, css and image support

### ISSUE THREAD

**Issue by luanlucho** [Fyrd/caniuse#4817]
I would like to propuse a new version of the can i use web app, this one directed to email client support.

Everyone that has worked with email templating, knows the pain of trying to figure it out what resources are supported by each email client. (Primarily speaking CSS)

It would be awesome if you guys create a sub web app like can i use directed to email client support specifically.

Hope to here from you.

**Comment by Malvoz** [comment]
- https://www.campaignmonitor.com/css/
- https://templates.mailchimp.com/resources/email-client-css-support/
- https://caniuse.email/

**Comment by Fyrd** [comment]
No plans to include email clients, the sites mentioned above are indeed good sources for email client compatibility.
