### ISSUE TITLE
Support `globalThis`

### ISSUE THREAD

**Issue by nottoseethesun** [Fyrd/caniuse#4822]
Works at least in the latest Chrome: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

**Comment by Schweinepriester** [comment]
+1

<https://kangax.github.io/compat-table/esnext/#test-globalThis> (that URL will probably change once `globalThis` moves up from stage 3)

**Comment by Ugoku** [comment]
Polyfill available: https://mathiasbynens.be/notes/globalthis

**Comment by AndrewDavis** [comment]
> Polyfill available: https://mathiasbynens.be/notes/globalthis

I don't even know how to **begin** parsing that article.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_builtins_globalthis
