### ISSUE TITLE
input list attribute

### ISSUE THREAD

**Issue by crucifyer** [Fyrd/caniuse#4830]
[https://www.w3schools.com/tags/att_input_list.asp](url)
```html
<input list="browsers">

<datalist id="browsers">
  <option value="Internet Explorer">
  <option value="Firefox">
  <option value="Google Chrome">
  <option value="Opera">
  <option value="Safari">
</datalist>```

**Comment by Ugoku** [comment]
Already present: https://caniuse.com/#search=datalist

**Comment by Fyrd** [comment]
Added the word input as search result so https://caniuse.com/#search=input%20list%20attribute should bring up datalist as expected now.
