### ISSUE TITLE
Support String.prototype.matchAll

### ISSUE THREAD

**Issue by Simonwep** [Fyrd/caniuse#4845]
`String.prototype.matchAll` returns a `RegExpStringIterator` which can be used to iterate over each match (And some other perks). Introduced in Chrome 73.

Article: [Better match results with String.prototype.matchAll()](https://developers.google.com/web/updates/2019/02/string-matchall)

**Comment by Lonniebiz** [comment]
I too just searched for matchAll on caniuse and the search came up empty. Here's another link about it:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll

**Comment by bsene** [comment]
+1

**Comment by BenjaminBrandtner** [comment]
+1

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_builtins_string_matchall
