### ISSUE TITLE
<input type=file>: ability to modify the selected files via JS

### ISSUE THREAD

**Issue by claudepache** [Fyrd/caniuse#4851]
In short, given:

```html
<input type="file" id="foo">
```
 I want to do:
```js
document.getElementById('foo').files = someDropEvent.dataTransfer.files
```

Last versions of Firefox (66), Chrome (73) and Safari (12.1) support this feature, but Edge 17 does not.

See https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement, property "files".
As of time of writing, the browser compatibility table on that page does not track correctly browser versions for which the "files" property is still readonly.

**Comment by HM100** [comment]
Could you send a bug to MDN compat data as well?

**Comment by GPHemsley** [comment]
Looks like this is now covered by MDN data:
https://caniuse.com/mdn-api_htmlinputelement_files

(via mdn/browser-compat-data#2884)

Information about IE treating `HTMLInputElement.files` as read-only is listed (via mdn/browser-compat-data#3418), but there are no such caveats for Edge. If this is incorrect, I suspect raising the issue at the MDN repo might be more effective.
