### ISSUE TITLE
“Loading” attribute on <img> and <iframe>

### ISSUE THREAD

**Issue by mickymcq** [Fyrd/caniuse#4857]
Chrome just introduced native lazy loading in 75. It’d be great to know when other browsers support as well. 

https://groups.google.com/a/chromium.org/forum/m/#!topic/blink-dev/jxiJvQc-gVg

https://addyosmani.com/blog/lazy-loading/

**Comment by MattSidor** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

- <https://chromestatus.com/feature/5645767347798016>
- <https://github.com/scott-little/lazyload>
- Specification PR: <https://github.com/whatwg/html/pull/3752>
- Demo: <https://mathiasbynens.be/demo/img-loading-lazy>

**Comment by Malvoz** [comment]
I presume [Feature-Policy's `lazyload` policy](https://github.com/w3c/webappsec-feature-policy/blob/master/policies/lazyload.md) is best to be a sub-feature of [Feature-Policy](https://caniuse.com/#search=feature-policy). But this should probably at least mention that policy delivery method.

**Comment by yoavweiss** [comment]
> Chrome just introduced native lazy loading in 75. It’d be great to know when other browsers support as well.
> 
> https://groups.google.com/a/chromium.org/forum/m/#!topic/blink-dev/jxiJvQc-gVg

This is an intent to ship. That doesn't mean that the feature has shipped, and we don't know yet if and when it actually would.

**Comment by nottoseethesun** [comment]
Apparently, it's in Canary: https://techcrunch.com/2019/05/07/google-tests-faster-image-loading-in-chrome-canary/

**Comment by kiding** [comment]
The standard effort can be tracked at https://github.com/whatwg/html/pull/3752. Webkit's implementation is [currently underway.](https://webkit.org/b/196698) Mozilla's bug can be found [here.](https://bugzilla.mozilla.org/show_bug.cgi?id=1542784)

**Comment by Fyrd** [comment]
Thanks for all resources, folks!
Now available at https://caniuse.com/#feat=loading-lazy-attr
