### ISSUE TITLE
Html Video tag on Opera Mini

### ISSUE THREAD

**Issue by rtarnaud** [Fyrd/caniuse#4860]
The current data says that the <video> tag is not available on all Opera Mini versions which is not true (I have just checked). I believe it needs an update?

**Comment by HM100** [comment]
> The current data says that the  tag is not available on all Opera Mini versions which is not true (I have just checked). I believe it needs an update?
Are you using the Standards mode or the Mini mode. Support for Opera mini is based on the Mini Mode, not standards one. Give me screenshot for evidence.

**Comment by Fyrd** [comment]
Just checked the Android app and it's currently called "Extreme data savings" mode. That mode matches the Opera Mini as it is used on feature phones in regions like Africa where it's the most common. 
I'll update the info on the site to be more clear about this.

**Comment by rtarnaud** [comment]
Ok, thanks for the clarification!
