### ISSUE TITLE
Integrate Chromium Edge (by listing ahead like Chrome?)

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#4861]
As Chromium Edge is now available (as preview)

- <https://blogs.windows.com/msedgedev/2019/04/08/microsoft-edge-preview-channel-details/>
- <https://www.theverge.com/2019/4/8/18300077/microsoft-edge-chromium-canary-development-release-download>
- <https://www.microsoftedgeinsider.com/en-us/>

it would probably be nice to have entries for those versions, e.g. by listing ahead like Chrome.

Currently Dev reports as 74

![image](https://user-images.githubusercontent.com/2644614/55787194-0cfd8600-5ab6-11e9-9670-a88c3bbdf90e.png)

and Canary as 75

![image](https://user-images.githubusercontent.com/2644614/55787249-26063700-5ab6-11e9-97b5-289c3f9a552f.png)

The corresponding version of Chrome is probably most accurate as base for the support data?

**Comment by Fyrd** [comment]
Has now been added (currently based on Chromium 75)

**Comment by Schweinepriester** [comment]
Very noice, thanks!
