### ISSUE TITLE
Add support for CSS clip property

### ISSUE THREAD

**Issue by PathogenDavid** [Fyrd/caniuse#4875]
Despite being deprecated, [`clip`](https://developer.mozilla.org/en-US/docs/Web/CSS/clip) has much wider support compared to [`clip-path`](https://caniuse.com/#search=clip-path). It'd be nice if caniuse listed this property as well.

**Comment by HM100** [comment]
All of the browsers that Caniuse has do support the Clip property. No need to.

**Comment by PathogenDavid** [comment]
MDN already doesn't have data on most of the mobile browsers, so between caniuse and it there isn't any reliable source that states that.

Additionally, I've already run into an issue where `canvas` elements aren't clipped by it correctly on iOS Safari. (Strangely enough, `-webkit-clip-path` works fine.) It'd be nice to see this quirk documented somewhere.

**Comment by HM100** [comment]
> MDN already doesn't have data on most of the mobile browsers, so between caniuse and it there isn't any reliable source that states that.
> Additionally, I've already run into an issue where canvas elements aren't clipped by it correctly on iOS/macOS Safari. (Strangely enough, -webkit-clip-path works fine.) It'd be nice to see this quirk documented somewhere.

Ιf something is fully supported across mobile borwsers and desktop browsers, then it won't be listed. Strangely, some data on MDN can be incorrect or missing, bro!!! 😉

**Comment by PathogenDavid** [comment]
> Ιf something is fully supported across mobile borwsers and desktop browsers, then it won't be listed. 

Sure, and I get why caniuse does that. It's not worth having a page about whether or not `font-size` is supported.

Maybe I'm wrong, but my impression is that `clip` is not used super often. It isn't one I'd make assumptions about what the browser support is.

Additionally it *isn't* fully supported, if I had seen a disclaimer telling me that it has weird behavior when clipping a `<canvas>` element, I would've investigated workarounds or other solutions sooner. (Thankfully `clip-path` works as expected, so I just take out `clip` when `-webkit-clip-path` is supported.)

> Strangely, some data on MDN can be incorrect or missing, bro!!!

Sure, there's probably stuff that's wrong on caniuse too. As someone who doesn't do web development on a frequent basis anymore (but still remembers the trauma of having to support IE6), I rely on websites like MDN and caniuse to tell me whether or not a feature I am looking at is actually safe to use. If there's a website that's better than MDN, I'd be more than happy to start using it.

**Comment by HM100** [comment]
> > Ιf something is fully supported across mobile borwsers and desktop browsers, then it won't be listed.
> 
> Sure, and I get why caniuse does that. It's not worth having a page about whether or not `font-size` is supported.
> 
> Maybe I'm wrong, but my impression is that `clip` is not used super often. It isn't one I'd make assumptions about what the browser support is.
> 
> Additionally it _isn't_ fully supported, if I had seen a disclaimer telling me that it has weird behavior when clipping a `<canvas>` element, I would've investigated workarounds or other solutions sooner. (Thankfully `clip-path` works as expected, so I just take out `clip` when `-webkit-clip-path` is supported.)
> 
> > Strangely, some data on MDN can be incorrect or missing, bro!!!
> 
> Sure, there's probably stuff that's wrong on caniuse too. As someone who doesn't do web development on a frequent basis anymore (but still remembers the trauma of having to support IE6), I rely on websites like MDN and caniuse to tell me whether or not a feature I am looking at is actually safe to use. If there's a website that's better than MDN, I'd be more than happy to start using it.

CSS ‘clip’ property only works on absolutely positioned elements, bro 😉

**Comment by Schweinepriester** [comment]
Available via MDN: <https://caniuse.com/mdn-css_properties_clip>
