### ISSUE TITLE
Support Data Suggestion: Clients API

### ISSUE THREAD

**Issue by ziyadElon** [Fyrd/caniuse#4895]
MDN: https://developer.mozilla.org/en-US/docs/Web/API/Clients

**Comment by paulirish** [comment]
This should be identical to support for Service Workers. https://caniuse.com/#feat=serviceworkers

**Comment by GPHemsley** [comment]
Looks like this is now covered by MDN data:
https://caniuse.com/mdn-api_clients

(via mdn/browser-compat-data#1005)
