### ISSUE TITLE
Add rendering date

### ISSUE THREAD

**Issue by abbr** [Fyrd/caniuse#4899]
I saw screenshots of caniuse in presentations that might be given years ago. Adding a rendering date to page informs the user the up-to-dateness in such context.

**Comment by Fyrd** [comment]
Seems like something that the person making the presentation may want to manually add, I don't see much value in making that part of how the support tables appear.

One way to estimate from when the screenshot was taken would be to look at the "current" browser version numbers and see when that browser came out.
