### ISSUE TITLE
screen reader accessibility of www.caniuse.com

### ISSUE THREAD

**Issue by electronicwoft** [Fyrd/caniuse#4903]
it'd be great if www.caniuse.com was accessible for screen reader users because knowing what is supported by browsers is an important part of providing solution recommendations for accessibility issues. Some suggestions include marking up the support tables using HTML table mark-up or suitable ARIA roles so that these can be navigated and understood effectively; providing accessible names for all interactive elements including text inputs, hyperlinks, and buttons; using HTML sectioning elements/ARIA landmark regions correctly and providing them with an accessible name.

**Comment by Fyrd** [comment]
I'd be happy to do what I can to improve screen reader accessibility, thanks for pointing this out. Previously I'd made changes and additions to this end, including making each support "cell" focusable with a `aria-describedby` attribute that in theory should make the tooltip info be read which provides more information on a browser version's support level. Admittedly I don't know how well that works in practice and I'm sure other parts of the site could use improvements. Definitely something I'd like to improve, if there's any more specifics you can suggest I'd be happy to hear them.

**Comment by electronicwoft** [comment]
yeah, sure. it'd need pretty major surgery to be WCAG conforming, but there's a bunch of things that can make it more accessible for a screen reader user .... I hadn't actually realised that each 'table cell' has an aria-describedby using a screen reader primarily because - contrary to common misconceptions - using the TAB key to navigate content is incredibly inefficient .. it would have taken me half the day to get to these items, and, without being focused using tab, the content of the aria-describedby isn't announced ... so what's the best way to provide specifics?
