### ISSUE TITLE
model-viewer HTML Component for 3D and AR

### ISSUE THREAD

**Issue by chrisblakley** [Fyrd/caniuse#4915]
Google spent a lot of time on the topic of augmented reality and mentioned the upcoming `<model-viewer>` HTML element. It does not appear to be supported in even Chrome Canary yet, but as it gains support it'd be nice to see where it can be used.

https://developers.google.com/web/updates/2019/02/model-viewer
https://developers.google.com/web/updates/2019/05/model-viewer-ar

**Comment by Fyrd** [comment]
As mentioned in that article, the model-viewer element is a custom element (you can tell based on the hyphen). So no native browser support, it requires support for [Custom Elements](https://caniuse.com/#feat=custom-elementsv1). Looks like it also requires a few other things listed here: https://googlewebcomponents.github.io/model-viewer/#section-browser-support

**Comment by chrisblakley** [comment]
TIL, thanks.
