### ISSUE TITLE
Add ECMAScript feature support data

### ISSUE THREAD

**Issue by jaydeepw** [Fyrd/caniuse#492]
Should add support data/files for new features and properties included in ECMAScript v6
Soon developers are going to need this in production and it would be good to have it here.

http://ejohn.org/blog/ecmascript-5-objects-and-properties/
https://people.mozilla.org/~jorendorff/es6-draft.html

**Comment by monolithed** [comment]
+1

**Comment by himynameisdave** [comment]
+1

**Comment by Fyrd** [comment]
ECMAScript 5 table is now available at http://caniuse.com/#feat=es5 as it's quite widely supported.

Currently ES6 / ES 2015 support is all over the place so I'm not going to give it its own table for a while. Popular individual features (like [Promises](http://caniuse.com/#feat=promises)) however may be added sooner.

**Comment by monolithed** [comment]
Unfortunately it's no so relevant for polyfill services.

**Comment by Fyrd** [comment]
Closing this issue as ES6 support is already being added in subsections, no need to have a specific issue for it.

**Comment by Fyrd** [comment]
Now "full" support has been around for a while, a new table has been added at https://caniuse.com/#feat=es6
