### ISSUE TITLE
Which browsers support Signed Exchanges

### ISSUE THREAD

**Issue by alankent** [Fyrd/caniuse#4920]
Chrome has support for signed exchanges, which allows caching of content by a third party, but browser can show URL of original site as the content was signed by that site. https://developers.google.com/web/updates/2018/11/signed-exchanges

This enables things like search engines to speed up user experiences using privacy preserving prefetch.

I could not see signed exchanges (or Web Packaging in general) listed.

**Comment by Malvoz** [comment]
https://github.com/Fyrd/caniuse/issues/4689

**Comment by Malvoz** [comment]
Chrome status (Origin-Signed HTTP Exchanges):
https://www.chromestatus.com/feature/5745285984681984
