### ISSUE TITLE
View Mode: First Supported Version

### ISSUE THREAD

**Issue by decherneyge** [Fyrd/caniuse#4932]
Since I know what browsers I support for my product it would save a bit of time if I could configure the compat tables to show me the first version the feature was partially or fully supported. 

As a developer I know that I support browsers X,Y,Z back to versions L,M,N respectively, when I visit a caniuse feature article I expect to see the first version of each browser that supported that feature so that I can quickly identify "Browser X supported this feature starting in version 9 and I support back to version 10 therefore I can use this feature" or "Browser X supported this feature starting in version 11 and I support back to version 10 therefore I can not use this feature"

**Comment by Fyrd** [comment]
First of all, is that not basically what's happening by default with "Current aligned"/"Show all" ? When I look at https://caniuse.com/#feat=flexbox for example I can see IE started having partial support with IE10, Firefox started having full support with 28 (first green block), Chrome with 21, etc.

Secondly, if you already have specific browser versions you support, you can create a custom view showing just these versions. Under **Settings** look under "Browser set" and click "Add new set". Once you're done setting up the versions, make sure you change the default "Show" value to "Filtered" and you'll only see the browsers and versions you defined. Not exactly what you asked for but maybe better?

**Comment by Fyrd** [comment]
Closing this issue as per my last comment
