### ISSUE TITLE
::-webkit-inner-spin-button ::-webkit-outer-spin-button 

### ISSUE THREAD

**Issue by ofek3103** [Fyrd/caniuse#4935]
::-webkit-inner-spin-button
::-webkit-outer-spin-button

**Comment by Schweinepriester** [comment]
- <https://trac.webkit.org/wiki/Styling%20Form%20Controls#inputelement>
- <https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-inner-spin-button>
- <https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-outer-spin-button>
- <https://css-tricks.com/snippets/css/turn-off-number-input-spinners/>

**Comment by Schweinepriester** [comment]
Available via MDN:
- https://caniuse.com/mdn-css_selectors_-webkit-inner-spin-button
- https://caniuse.com/mdn-css_selectors_-webkit-outer-spin-button
