### ISSUE TITLE
min-height not working properly on IE11

### ISSUE THREAD

**Issue by maxenceg** [Fyrd/caniuse#4936]
When setting `min-height: 500px;` on a div in IE, the height of the div looks 500px.

However, if we add:
```
display: flex;
flex-direction: column;
justify-content: space-between;
```
to this div, the children **won't** take all the 500px as expected.

Also, if you put `margin-top: auto;` to the last child of the div, it won't be aligned to the bottom of the div since the height is not defined.

It turns out the `min-height` property does not set the height to be at least the value given to `min-height`

**Comment by Schweinepriester** [comment]
That very much sounds like

> In IE10 and IE11, containers with `display: flex` and `flex-direction: column` will not properly calculate their flexed childrens' sizes if the container has `min-height` but no explicit `height` property. [See bug](https://connect.microsoft.com/IE/feedback/details/802625/min-height-and-flexbox-flex-direction-column-dont-work-together-in-ie-10-11-preview).

mentioned under Known issues at <https://caniuse.com/#feat=flexbox>.

Alternatively it might be covered by <https://github.com/philipwalton/flexbugs>?

=> Do you think this issue is properly covered?

**Comment by maxenceg** [comment]
It covers the flex case indeed.

However, the case where margin-top: auto is used still remains, doesn't it?

**Comment by Schweinepriester** [comment]
> However, the case where margin-top: auto is used still remains, doesn't it?

That might be a variation of <https://github.com/philipwalton/flexbugs#flexbug-15>?

> *Column flex items ignore `margin-auto` on the cross axis*

**Comment by maxenceg** [comment]
Indeed!

It looks like even without flex, the margin-top auto is ignored, though

**Comment by Fyrd** [comment]
Don't see a need to add more detailed bugs to the already long list (with the flexbugs link) so closing this.
