### ISSUE TITLE
Feature suggestion: add "scrollRestoration" for the History API

### ISSUE THREAD

**Issue by Aaron3219** [Fyrd/caniuse#4940]
A couple of weeks ago Google wrote a guide about the [`scrollRestoration`](https://developers.google.com/web/updates/2015/09/history-api-scroll-restoration) for the History API which allows to save the scroll position on (for example) SPAs. However, there is no info about the browser support on caniuse.

Maybe you can add it some time in the future.

**Comment by dantistus** [comment]
Still not on caniuse.com
