### ISSUE TITLE
Current Firefox version is now 67

### ISSUE THREAD

**Issue by tuxayo** [Fyrd/caniuse#4944]
caniuse.com still displays Firefox 66 as the current version, but 67 is now released.

https://en.wikipedia.org/wiki/Firefox_version_history#Current_supported_official_releases
https://en.wikipedia.org/wiki/Firefox_version_history#Firefox_67

**Comment by Fyrd** [comment]
Ah I thought I'd taken care of that one. Thanks for the reminder, updated now!
