### ISSUE TITLE
queue micro task

### ISSUE THREAD

**Issue by Nemo64** [Fyrd/caniuse#4945]
I found this feature mentioned in corejs. I have no real idea how the status of it it, but it seems to be implemented in chrome as supposed to setImmediate.

https://www.chromestatus.com/feature/5111086432911360
https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#microtask-queuing

**Comment by Schweinepriester** [comment]
+1

<https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/69>:

> The Microtask API ([`WindowOrWorkerGlobalScope.queueMicrotask()`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/queueMicrotask "The queueMicrotask() method of the WindowOrWorkerGlobalScope mixin queues a microtask.")) has been implemented ([bug 1480236](https://bugzilla.mozilla.org/show_bug.cgi?id=1480236 "FIXED: Implement queueMicrotask()")).

**Comment by Schweinepriester** [comment]
I'm afraid this issue is actually duplicate of #4700…

**Comment by Nemo64** [comment]
You are right. Duplicate of #4700
