### ISSUE TITLE
Add Safari & iOS Safari 13, consider Safari for iPad

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#4946]
Please add:

<https://developer.apple.com/documentation/safari_release_notes/safari_13_beta_release_notes>

> Safari 13 ships with iOS 13 and macOS 10.15. It’s also available for macOS 10.14.5 and 10.13.6.

TL;DR: <https://twitter.com/firt/status/1135635815252549632>

Once the versions exist, I would send PRs if needed.

---

One thing to consider with the whole "[The iPad is getting its own OS](https://www.engadget.com/2019/06/03/the-ipad-is-getting-its-own-os/)": Safari for iPad at the latest now isn't equal to Safari for iOS anymore. The imho two major points from [the changelog](https://developer.apple.com/documentation/safari_release_notes/safari_13_beta_release_notes):

> - Updated Safari for iPad to support Media Source Extensions.

Can't reflect that directly at <https://caniuse.com/#feat=mediasource>.

> - Disabled `-webkit-overflow-scrolling: touch` on iPad. All frames and scrollable overflow areas now use accelerated one-finger scrolling without changing stacking.

#1308.

Sure enough we could currently mark those differences with notes/partial support, but it might be sensible to consider to make Safari for iPad (aka. iPad Safari) its own entry…

**Comment by Fyrd** [comment]
Safari 13 & iOS 13 Safari now added! Not going to add iPadOS Safari just yet, but will definitely consider.

**Comment by kiding** [comment]
Looks like MSE support on iPadOS Safari is the "only" divergence, which could be significant or not, depending on the perspective. I think *partial support* should suffice for the time being.

**Comment by daytonlowell** [comment]
Fullscreen API has differences between iPadOS and iOS.

Also, Safari on iPadOS disables `-webkit-overflow-scrolling: touch`
