### ISSUE TITLE
Firefox supporting Subgrid isn't showing up

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#4955]
Last week I submitted a pull request to update the Subgrid page to reflect that Firefox 69 will ship Subgrid. https://github.com/Fyrd/caniuse/pull/4950

But it's not working.

<img width="526" alt="Can I use  Support tables for HTML5, CSS3, etc 2019-06-10 12-07-07" src="https://user-images.githubusercontent.com/108474/59217920-027e6c00-8b8d-11e9-8ebe-274c5fe56b16.png">

I don't know why. 

The [JSON file](https://github.com/Fyrd/caniuse/blob/master/features-json/css-subgrid.json) says: 
```
 "firefox":{
      "2":"n",
      "3":"n",
etc etc
      "68":"n",
      "69":"y"
    },
```

??????

**Comment by Fyrd** [comment]
Sorry about that, after PRs are merged I need to manually press a button to update the site's data which I forgot to do in this instance. Have updated it now, thanks for pointing that out!
