### ISSUE TITLE
Chrome for Android: Drag and Drop now supported

### ISSUE THREAD

**Issue by owen-m1** [Fyrd/caniuse#4958]
Chrome for Android now seems to support native HTML5 Drag and Drop: https://bugs.chromium.org/p/chromium/issues/detail?id=156390#c56

**Comment by owen-m1** [comment]
I made a PR for it: #4959

I'm just not 100% sure on the version number, I just went by the dates of the commit vs next release. Still more accurate than it was before.

**Comment by Fyrd** [comment]
PR has been merged, so closing.
