### ISSUE TITLE
Drag and Drop API events are not triggered on iPhone

### ISSUE THREAD

**Issue by artyomszasa** [Fyrd/caniuse#4970]
Despite Drag'n'Drop API is "supported" on iOS Safari events are not triggered on iPhones. Apple seems to do it on purpose: https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html#//apple_ref/doc/uid/TP40006511-SW19

(see drag =>  Generated = No)

So iOS may "have support" for drag'n'drop API, yet it is not functional thus the current support status is quite misleading...

**Comment by atjn** [comment]
Nice catch, thanks for adding some documentation!

This issue is resolved with #5320 as multiple sources were not able to use Drag & Drop in IOS Safari at all, and we decided to mark it `Unsupported`.
