### ISSUE TITLE
Feature suggestion: Top level `await`

### ISSUE THREAD

**Issue by Ferroin** [Fyrd/caniuse#4978]
In short, the ability to use `await` in JavaScript outside of a function context.  The official proposal (linked below) has some examples of why this is useful, but the big one is that it makes working with ES6 modules that need to handle things asynchronously exponentially simpler.

Official proposal: https://github.com/tc39/proposal-top-level-await

Chrome/Chromium (and in theory anything with an up-to-date V8-based JS engine) has a working implementation that appears to be compliant with the specification laid out in the proposal.

The proposal itself is at stage 3, and appears to be primarily waiting on implementation by something other than just V8.

**Comment by Schweinepriester** [comment]
Seems to be available via MDN: <https://caniuse.com/mdn-javascript_operators_await_top_level>
