### ISSUE TITLE
MediaTrackConstraints

### ISSUE THREAD

**Issue by matiaslopezd** [Fyrd/caniuse#4991]
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints

**Comment by matiaslopezd** [comment]
JSON File: https://github.com/mdn/browser-compat-data/blob/master/api/MediaTrackConstraints.json

**Comment by GPHemsley** [comment]
Looks like this is now covered by MDN data:
https://caniuse.com/mdn-api_mediatrackconstraints

(via mdn/browser-compat-data#2133)
