### ISSUE TITLE
Typo on CSS Filters support page

### ISSUE THREAD

**Issue by GustvandeWal** [Fyrd/caniuse#5007]
In the Known Issues section on https://caniuse.com/#feat=css-filters, there is `box-shadow` written in the first issue, where it should be `drop-shadow`.

Also, is there a place where I can just quickly drop comments like these? Feels kind of overkill to create an issue for such a small thing.

**Comment by Fyrd** [comment]
Thanks! Has been fixed. Submitting a PR would be ideal, but I don't mind opening issues for easy things to fix.
