### ISSUE TITLE
support for Promise.allSettled()

### ISSUE THREAD

**Issue by caesar** [Fyrd/caniuse#5017]
It would be great to add support for `Promise.allSettled()`.
Currently only supported in Chrome 76 so far as I am aware.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-javascript_builtins_promise_allsettled

**Comment by LexSwed** [comment]
@Fyrd can you hint how I could get this `allSettled` data (browser usage) from the repo data? I cannot find it in `features`, so I guess the data is stored somewhere else? Thanks 🙇
