### ISSUE TITLE
video.srcObject

### ISSUE THREAD

**Issue by shimondoodkin** [Fyrd/caniuse#5019]
video.srcObject

**Comment by shimondoodkin** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=387740

**Comment by shimondoodkin** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/srcObject

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_htmlmediaelement_srcobject
