### ISSUE TITLE
DOM nodeType constants

### ISSUE THREAD

**Issue by mossy2100** [Fyrd/caniuse#5020]
It would be good to know which browsers (probably all except IE) support the nodeType constants. https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType

**Comment by Ugoku** [comment]
Supported in IE11, can't test in earlier versions.

**Comment by mossy2100** [comment]
Good to know, thanks Ugoku :)

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-api_node_nodetype
