### ISSUE TITLE
can i use Backpage Ranges?

### ISSUE THREAD

**Issue by TheRook** [Fyrd/caniuse#5024]
I think it is only supported by Safari, Firefox and Chrome.

https://developer.mozilla.org/de/docs/Web/HTML/Using_HTML5_audio_and_video#Specifying_playback_range

**Comment by Fyrd** [comment]
Sounds like you're looking for media fragments?
https://caniuse.com/#feat=media-fragments

**Comment by TheRook** [comment]
Oh great, yeah that is what i'm looking for. Maybe we can add a synonym?
