### ISSUE TITLE
Lazy loading is currently enabled in all browsers based on chromium 76+

### ISSUE THREAD

**Issue by Veratyr** [Fyrd/caniuse#5030]
Support for "loading" attribute is enabled by default in chromium 76+, so [this description](https://caniuse.com/#feat=loading-lazy-attr) needs to be fixed.
More info: https://web.dev/native-lazy-loading

**Comment by Ugoku** [comment]
A PR for this already exists: #5025

**Comment by Veratyr** [comment]
Thanks, didn't saw it.
