### ISSUE TITLE
Serial API

### ISSUE THREAD

**Issue by matrix0123456789** [Fyrd/caniuse#5034]
New in chrome 77. Simmilar to WebUSB but for serial port
https://www.chromestatus.com/feature/6577673212002304

**Comment by panuhorsmalahti** [comment]
It would be nice to add this. It's already (at least partially) available in Chrome.

**Comment by CarltonHenderson** [comment]
Google's site says it's in Chrome 80 and later.

https://codelabs.developers.google.com/codelabs/web-serial/#0

**Comment by CarltonHenderson** [comment]
The Web Serial API is currently under [Origin Trial](https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md).

That is, you need to get a token to use the feature and its API methods are being added, tweaked, and will be disabled after 0.5% of all web page views use the feature.

**Comment by cltsang** [comment]
Web Serial has just been released in Chrome 89 stable. See [the release blog post](https://developer.chrome.com/blog/new-in-chrome-89/#hardware).
We no longer need users to enable "Experimental Web Platform features".

**Comment by jpmedley** [comment]
To be clear, features behind flags such as "Experimental Web Platform Features" are intended for web developers to try things out and hopefully find bugs that Chrome's testing missed before a feature reaches production. We actively discourage people from telling users to flip these flags.

**Comment by CarltonHenderson** [comment]
Web Serial was also enabled for any domain that had a Chrome Origin Trial
Token in the page <head> on earlier versions of Chrome.   It didn't require
end users to flip a flag in that case.

**Comment by jpmedley** [comment]
That's not considered production. It's so that things can be tested many users and not become a permanent part of the web platform. When an origin trial ends it's retroactive. If Chrome 90 ships a feature that was an origin trial in 89, you can't continue to use it, even if you still have 89 installed.
