### ISSUE TITLE
Settings - geography filter: no import button on Chrome

### ISSUE THREAD

**Issue by JohanHeyvaert** [Fyrd/caniuse#5037]
Hi,

Just noticed that in my chrome browser (v76.0.3809.100) the "import" button is missing next to the settings - geography input field. So I cannot filter on a region. In my firefox the button appears and works.

Screenshot chrome:
![image](https://user-images.githubusercontent.com/13747250/63177040-5f901580-c047-11e9-8443-a51778c9a803.png)

Screenshot firefox:
![image](https://user-images.githubusercontent.com/13747250/63177235-c6153380-c047-11e9-8908-da19810f8e06.png)

**Comment by JohanHeyvaert** [comment]
Just discovered that it's caused by the uBlock Origin extension! 
Now that is weird, isn't it?

**Comment by Fyrd** [comment]
Hmm, I just tried installing the extension and the button still appears for me. I see there's an "Element zapper mode" which can be used to hide an element...perhaps you accidentally had that on when you clicked the button?

**Comment by JohanHeyvaert** [comment]
Thanks for your response Fyrd.

No, I never used the zapper. 

I've now tested the following:
- installed the extension in Firefox --> still no problem
- removed and reinstalled the extension in Chrome --> problem solved
So I don't really know what was going on, but doesn't seem to be worth our time anymore!

**Comment by a-v-l** [comment]
I had the same problem. It was solved by disabling uBlock Origin for caniuse.com. After importing the geography source the extension can be enabled again – but of course it dosen't hurt to have a small ad displayed on this great and free resource for us!

**Comment by minig0d** [comment]
Stumbled across this thread on accident.  It's not actually necessarily something broken but rather from the EasyPrivacy list rule most likely.

Here are the two rules to whitelist the two scripts as of 12/26/19 if it saves anyone the trouble of trying to figure them out:
@@||caniuse.com/resources/statcounter-regions.json$xhr,1p
@@||ipinfo.io/?callback=getIpData$script,domain=caniuse.com

**Comment by Fyrd** [comment]
Closing this issue as I don't think it's something that needs fixing on the caniuse side.
