### ISSUE TITLE
Add text-decoration-thickness CSS Property

### ISSUE THREAD

**Issue by madebyfabian** [Fyrd/caniuse#5038]
There is a new CSS Property called "text-decoration-thickness", its for setting the weight/thickness of the line of underlined text.

See: https://twitter.com/jensimmons/status/1162360722598313984

According to Jen Simmons (CSS Worker at Mozilla), the feature is already shipped in Safari, Firefox Nightly, and will be shipped in stable Firefox 70.

**Comment by jensimmons** [comment]
I made a simplified demo for testing: https://codepen.io/jensimmons/pen/jONrVxa?editors=1100#0

**Comment by Spone** [comment]
See also https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-thickness

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-css_properties_text-decoration-thickness
