### ISSUE TITLE
Add `text-underline-offset` property

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#5039]
From The CSS Text Decoration Module Level 4
https://drafts.csswg.org/css-text-decor-4/#underline-offset

This works today in Safari. Will ship in Firefox 70.

**Comment by jensimmons** [comment]
I made a demo here that can be used for testing: https://codepen.io/jensimmons/pen/RwbRoMP?editors=1100#0

If you are curious as to what can be done with this, a bunch of examples are at:
https://codepen.io/jensimmons/pen/voYMPE?editors=1100

**Comment by kiding** [comment]
This feature will be shipped with [Chrome 87](https://blog.chromium.org/2020/10/chrome-87-beta-webauthn-in-devtools.html).

**Comment by Schweinepriester** [comment]
Available by now via MDN: <https://caniuse.com/?search=text-underline-offset>
