### ISSUE TITLE
Add JPEG-XL

### ISSUE THREAD

**Issue by LukeAI** [Fyrd/caniuse#5041]
Add JPEG-XL
https://tech.slashdot.org/story/19/08/17/1855214/can-jpeg-xl-become-the-next-free-and-open-image-format
https://www.slideshare.net/cloudinarymarketing/imagecon-2019-jon-sneyer

**Comment by Schweinepriester** [comment]
<https://en.wikipedia.org/wiki/Joint_Photographic_Experts_Group#JPEG_XL>:

> The current target publication date is October 2019.

Early but could be nice.

+1

**Comment by ayumi-cloud** [comment]
I'm using Google Canary v89 and I can view JPEG-XL files!

Sample image in browser: https://res.cloudinary.com/demo/image/fetch/f_png/https://res.cloudinary.com/demo/sample.jxl

https://cloudinary.com/blog/cloudinary_supports_jpeg_xl

Please can the team add JPEG-XL live now.

**Comment by Schweinepriester** [comment]
<https://res.cloudinary.com/demo/image/fetch/f_png/https://res.cloudinary.com/demo/sample.jxl>

is not a valid test as it returns a PNG, mentioned in the URL and accordingly are the response headers.

<https://res.cloudinary.com/demo/sample.jxl>

doesn't work for me in Chrome Canary 89.0.4333.0 nor Firefox Nightly 85.0a1

Issues:
- Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1056172
- Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=JPEG-XL

**Comment by ayumi-cloud** [comment]
@Schweinepriester 

Why can I save `.jxl` files in Google Canary?

![image](https://user-images.githubusercontent.com/57409060/100366719-1922b800-2ff9-11eb-980c-eb755fc893df.png)

**Comment by ayumi-cloud** [comment]
Also your Chrome tracking bug seems wrong.

Chrome Status: https://www.chromestatus.com/features/5678152091172864
Chrome Issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1109698

**Comment by ayumi-cloud** [comment]
That's rather childish adding a dislike when I added the correct links to the chrome tracking:

![image](https://user-images.githubusercontent.com/57409060/100370456-373ee700-2ffe-11eb-815f-4b0963a6b13a.png)

**Comment by jonsneyers** [comment]
> I'm using Google Canary v89 and Firefox Nightly v85, I can view JPEG-XL files in these browsers no problem!
> 
> Sample image in browser: https://res.cloudinary.com/demo/image/fetch/f_png/https://res.cloudinary.com/demo/sample.jxl
> 
> https://cloudinary.com/blog/cloudinary_supports_jpeg_xl
> 
> Please can the team add JPEG-XL live now.

Sorry for the confusion, but that url creates a PNG file (that's what the f_png does), even though the 'extension' at the end of the url is .jxl.

If at some point this url: https://res.cloudinary.com/demo/sample.jxl
can be displayed by your browser, your browser supports JPEG XL.

Chrome does not support jxl yet, not the subset that can be used as content-encoding for jpeg and also not the full format.

JPEG XL is currently at version 0.1, which is a "format release candidate". When version 0.2 is reached (which will be the "format release"), the codec will be stable enough to start talking about browser support, since at that point the bitstream is stable enough to guarantee that files will remain decodable. This should happen soonish (in a week or two, I hope).

**Comment by ayumi-cloud** [comment]
@jonsneyers Thank you, your comment makes sense.

**Comment by nathanielcwm** [comment]
https://gitlab.com/wg1/jpeg-xl/-/commit/31c71b0f61123a40789b0b8f54feb70e5995420e

**Comment by Malvoz** [comment]
- Recently published explainer: http://sneyers.info/jxl/
- Official site: https://jpeg.org/jpegxl/

**Comment by jonsneyers** [comment]
JPEG XL is in FDIS stage now in the ISO standardization process. The bitstream has been frozen for a month now. This is a good time to start talking about browser support.

**Comment by Neltulz** [comment]
I support the inclusion of JpegXL!

**Comment by Schweinepriester** [comment]
Chromium [merged issue 1056172](https://bugs.chromium.org/p/chromium/issues/detail?id=1056172#c20), so <https://bugs.chromium.org/p/chromium/issues/detail?id=1178058> appears to be the new tracking issue.

Currently there are now two chrome status entries:
- <https://www.chromestatus.com/feature/5678152091172864> (previously mentioned here)
- <https://www.chromestatus.com/feature/5188299478007808>

The [former](https://www.chromestatus.com/feature/5678152091172864) appears to be a sub-feature while the [latter](https://www.chromestatus.com/feature/5188299478007808) seems to be for displaying JPEG XL images.

**Comment by Orum** [comment]
At this rate browsers will support JPEG-XL before caniuse does.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/jpegxl

For the record, I generally see if browsers are actually interested in supporting a feature before adding it, especially in the case of new file formats. In this case it's still pretty early but it does seem like they're planning it for Chrome.

**Comment by EwoutH** [comment]
Chrome is preparing support

> [Add libjxl library and its dependencies.](https://chromium.googlesource.com/chromium/src/+/6980917f414387c968a94b4ee1feb4fdf654b157)
> 
> Make the new "libjxl" library available in gn build system and
> include its new dependencies (google/highway).
> 
> This library is now included in the build from the
> blink_platform_unittests_sources target so it is built in this
> commit. Since it is only in the unittest it won't be included in
> chrome binary with this commit.
> 
> This library will be conditionally included behind a flag in a
> follow up commit in preparation to support jxl Content-Encoding and
> image/jxl codec.
