### ISSUE TITLE
Chrome for Android - wrong values

### ISSUE THREAD

**Issue by photopea** [Fyrd/caniuse#5042]
According to this https://caniuse.com/#feat=dragndrop, Chrome for Android supports drag-and-drop.

However, when I check these demos in Chrome for Android, they do not work: https://www.w3schools.com/html/html5_draganddrop.asp

How exactly do you achieve these values? I think many of them may be incorrect.

*** It seems like it is not supported on iOS Safari either.

**Comment by LifeIsStrange** [comment]
Maybe it's only supported via external input devices such as mouse?
https://android.stackexchange.com/questions/116929/in-google-chrome-how-do-i-drag-things-around-on-a-touchscreen-android-device

**Comment by jpmedley** [comment]
This is a hypercorrection. Somebody probably added it without thinking. Android does not support drag and drop.

**Comment by Malvoz** [comment]
Waiting for @Fyrd to merge https://github.com/Fyrd/caniuse/pull/5056/commits/2ddfad4749b95a67f771e1102a9398a19a66b93b.

**Comment by photopea** [comment]
Hey guys, I received this link from Chrome developers: https://output.jsbin.com/rocilux/quiet  You should drag a textbox into a green area. The Chrome developer tells me, that it works on his phone.

It does not work on my phone, neither on my tablet (in the latest stable Chrome for Android). Does it work for you?

**Comment by LifeIsStrange** [comment]
@photopea
This does work for me:
Chrome 76 stable, latest Android on a Huawei mate 20 pro.

**Comment by Malvoz** [comment]
This https://github.com/Fyrd/caniuse/issues/4958 has a link to the drag and drop issue for implememtation which includes Android, and this https://support.google.com/chrome/thread/2831400?hl=en suggests there's been some support regression perhaps due to a bug?

**Comment by photopea** [comment]
Could the latest Chrome behave differently on each version of Android? I use Android 6.0

**Comment by atjn** [comment]
@photopea nice guessing there! I did some research:

All devices running Chrome 80, using https://output.jsbin.com/rocilux/quiet for testing.

Device | Android version | Drag & Drop supported? |
| --- | --- | --- |
Nexus 7 | 4.4 | ❌
Galaxy Note 4 | 4.4 | ❌
Nexus 6 | 5 | ❌
Moto G 2nd Gen | 5 | ❌
Nexus 9 | 5.1 | ❌
Xperia Z5 | 5.1 | ❌
Nexus 6 | 6 | ❌
Nexus 7 | 6 | ❌
LG G5 | 6 | ❌
Moto X2 2nd Gen | 6 | ❌
Nexus 6P | 7 | ✔️
Galaxy Tab S3 | 7 | ✔️
Pixel | 7.1 | ✔️
Galaxy Note 8 | 7.1 | ✔️
Galaxy S9+ | 8 | ✔️
Pixel | 8 | ✔️
Pixel 2 | 8 | ✔️
Galaxy Note 9 | 8.1 | ✔️
Galaxy S9+ | 9 | ✔️
Galaxy A10 | 9 | ✔️
Pixel 3a | 9 | ✔️
Moto G7 Play | 9 | ✔️
OnePlus 7 | 9 | ✔️
Pixel 3 | 10 | ✔️
OnePlus 7T | 10 | ✔️

I think we got ourselves an answer here.

Separately, i was also not able to make it work in IOS Safari.

**Comment by photopea** [comment]
@atjn  Wow, that is really great! You did an amazing job!

I will rename this tread, so that people with the same problem can find it through search engines.
