### ISSUE TITLE
Remote Playback API

### ISSUE THREAD

**Issue by Malvoz** [Fyrd/caniuse#5043]
Specification: https://www.w3.org/TR/remote-playback/

Implementation status:
https://www.chromestatus.com/feature/5778318691401728
https://bugs.webkit.org/show_bug.cgi?id=162971

**Comment by Schweinepriester** [comment]
+1

Safari 13.1+/iOS 13.4+ per <https://webkit.org/blog/10247/new-webkit-features-in-safari-13-1/>
