### ISSUE TITLE
Feature request: Can I use <font>

### ISSUE THREAD

**Issue by LadyAleena** [Fyrd/caniuse#5044]
There used to be a list of "web safe" fonts, however, that list is inaccurate these days. There are so many systems out there that do not have even half of the web safe fonts. For example, Helvetica is not on my desktop system nor on my phone. So, it is not web safe these days.

It would be nice if there were a place where I could find out what fonts work where. I know that Can I Use focuses on browsers, but operating systems impact web design too.

**Comment by TRayT** [comment]
Have you considered just using WebFonts? That way you can just _provide_ the font and it works?
https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts#Web_fonts

That has licensing/distribution issues, but it allows for consistency.

**Comment by Ugoku** [comment]
> It would be nice if there were a place where I could find out what fonts work where.

You can't though. Helvetica is present on Macs, but you can install it on Windows too, so how would that work?

**Comment by Fyrd** [comment]
While I agree it would be useful to know which default fonts appear in which OSes that seems outside of caniuse's scope, especially since it's OS dependent rather than based on browser.

**Comment by LadyAleena** [comment]
Ugoku, I can not install proprietary fonts on my Debian system. They are not in Debian's package manager. (Sorry for the delayed response.)
