### ISSUE TITLE
Option to `uncollapse` version ranges

### ISSUE THREAD

**Issue by pastelsky** [Fyrd/caniuse#5051]
Version ranges like `Safari 9.0-9.2` make sense when a user sees it on a website like caniuse.com. However, the use of the `caniuse` database has grown far beyond that purpose and it is now used by tools like `browserslist`, which need granular versions for accurate querying.

Is there a way one can uncollapse version ranges when querying? This would fix issues like this - https://github.com/browserslist/browserslist/issues/402

**Comment by Fyrd** [comment]
These version ranges are used whenever the browser engine is exactly the same across versions. I don't think it makes sense for caniuse to split these up as it would just result in duplicative data. Splitting `Safari 9.0-9.2` up downstream would seem to make more sense to me.

**Comment by pastelsky** [comment]
Let's talk about Safari for a second here – since they release new features even in minor version number upgrades. For eg. in Safari 10.1, Webkit added support for `fetch`. This means that the version range groups are themselves dynamic.

The issue is that caniuse isn't consistent about collapsing data into version ranges also – it doesn't collapse all chrome versions that have/don't have a feature together. So there is already a lot of duplication that exists in caniuse and a little more shouldn't hurt?

Also, as I mentioned, `caniuse` is now serving as a database (of features, or browsers, of browser versions) for a variety of other projects (even though it might not have been intended for so initially), and consistency in its data would only enhance its usefulness.

**Comment by Fyrd** [comment]
To be more specific about Safari, for MacOS as you say minor version number upgrades are indeed different and thus they are not combined (and Safari 10.1 has its own entry).

Only for iOS Safari, whose versions are based on the OS, rather than the browser itself, are ranges used because each OS update does not contain a browser update. If there's no browser update it makes no sense to use a separate entry. Ideally I'd be able to switch the OS version range to a single browser version number but I know at least in earlier versions that wasn't provided in the user agent string.

**Comment by Fyrd** [comment]
Closing this issue as per my last comment.

**Comment by ibeqiri-flexera** [comment]
> To be more specific about Safari, for MacOS as you say minor version number upgrades are indeed different and thus they are not combined (and Safari 10.1 has its own entry).
> 
> Only for iOS Safari, whose versions are based on the OS, rather than the browser itself, are ranges used because each OS update does not contain a browser update. If there's no browser update it makes no sense to use a separate entry. Ideally I'd be able to switch the OS version range to a single browser version number but I know at least in earlier versions that wasn't provided in the user agent string.

Is it possible for Safari 18.5-18.6 to be split and there to be standalone versions just like thee seems to be for Safari 10.1 @Fyrd 

@pastelsky how did you continued after that? you just removed ios safari query at all?
