### ISSUE TITLE
Searching for "flexbox" doesn't bring up "CSS Flexible Box Layout Module"

### ISSUE THREAD

**Issue by mirraj2** [Fyrd/caniuse#5061]

**Comment by Ugoku** [comment]
Yes it does, it's at position 2 in the search results

**Comment by Fyrd** [comment]
Yeah, I'll leave this issue open as I feel it should appear as the 1st result. This is the second time I've seen confusion since the gap property for flexbox feature was added.

**Comment by Fyrd** [comment]
This got fixed some time ago so closing this issue.
