### ISSUE TITLE
Add Text.wholeText property

### ISSUE THREAD

**Issue by nikitahl** [Fyrd/caniuse#5063]
Add `Text.wholeText` property to caniuse.
Currently not found.

https://developer.mozilla.org/en-US/docs/Web/API/Text/wholeText

![Screenshot 2019-08-30 at 15 21 01](https://user-images.githubusercontent.com/12826823/64023544-3ab89980-cb41-11e9-9b3a-ef7dba3c453a.png)

**Comment by GPHemsley** [comment]
Looks like this is now covered by MDN data:
https://caniuse.com/mdn-api_text_wholetext

(via mdn/browser-compat-data#1737)
