### ISSUE TITLE
Add Safari & iOS Safari 13.1

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#5068]
the obligatory issue 0:-)

found no changelog so far, but at the latest TP 91 suggests there is a delta to 13 (via #5067)…

**Comment by Fyrd** [comment]
Added!

**Comment by kiding** [comment]
Safari (for macOS) 13.1, unlike iOS Safari, does not exist yet. The latest version of Safari (for macOS) is [13.0.2 beta released in Sep 30,](https://developer.apple.com/download/more/?=Safari) and there is no presence of "Safari 13.1" in [WebKit's release trackers](https://trac.webkit.org/browser/webkit/releases/Apple) either. 

@Fyrd 9c7e28284550c51728f897340f830abe6487c586 needs to be partially reverted.

**Comment by Schweinepriester** [comment]
Safari TP 93 from yesterday still reports as 13.1 tho, just like 91…

![image](https://user-images.githubusercontent.com/2644614/66147568-6252c400-e60f-11e9-8450-9bec18f48c70.png)

(Changelog: https://webkit.org/blog/9600/release-notes-for-safari-technology-preview-93/)

**Comment by kiding** [comment]
I think it’d be better if we stick to the ‘official beta version strings’ for macOS Safari, just like iOS Safari, not only for consistency but also an issue I’ve stumbled upon while preparing a PR: Some features are dependent on the OS version. Although we know the current TP is only available on Mojave and Catalina, there is no assurance 13.1+ would not support High Sierra. 

For example, while [TP 84 started dropping the support for High Sierra,](https://web.archive.org/web/20190610011439/https://developer.apple.com/safari/download/), its eventual stable release ["Safari 13" supports High Sierra.](https://developer.apple.com/documentation/safari_release_notes/safari_13_beta_3_release_notes) `Info.plist` in [TP 88 says it's 13.0](https://web.archive.org/web/20190807151937/https://developer.apple.com/safari/download/) and [TP 90 says it's 13.1](https://web.archive.org/web/20190824103557/https://developer.apple.com/safari/download/), but we know [13.0.2 is currently in the beta stage.](https://developer.apple.com/download/more/?=Safari) TP 89 can't be both 13.0.1 and 13.0.2. The bottom line is, we can't really trust Safari version string in a TP.

On top of that, some recent changesets are frequently cherry-picked to be backported into the "old" version strings, which makes this more complicated. These uncertainties add guesswork or other patches to correct the record afterwards.
