### ISSUE TITLE
Safari Webauthn support

### ISSUE THREAD

**Issue by kirillDanshin** [Fyrd/caniuse#5072]
As stated https://webkit.org/status/#feature-web-authentication, safari supports Webauthn in the preview.

**Comment by Schweinepriester** [comment]
As it is shown at <https://caniuse.com/#feat=webauthn>:

![image](https://user-images.githubusercontent.com/2644614/64478718-953e9f00-d1ac-11e9-8761-2b93375f6aa0.png)

Does this cover your issue or is there something more?

**Comment by Fyrd** [comment]
Seems covered to me...

**Comment by kirillDanshin** [comment]
@Schweinepriester @Fyrd at the time of writing, Safari TP was red :)
