### ISSUE TITLE
Async functions in iOS 10.3 supported?

### ISSUE THREAD

**Issue by GitToTheHub** [Fyrd/caniuse#5073]
Hi,
when i search for the support of Async functions for iOS, it shows support in green starting with Version 11. But when i look in https://kangax.github.io/compat-table/es2016plus/ i see support for the await keyword for iOS 10.3
In "can i use" there is a note for 10.3, that async is not supported for arrow functions but 10.3 is completely shown in red (no support). So is async/await supported in 10.3 or not?

**Comment by Fyrd** [comment]
You're right, it should have been marked as partial support. Have fixed that now. Thanks!
