### ISSUE TITLE
Minimum Android Browser Version is displayed often higher as necessary

### ISSUE THREAD

**Issue by GitToTheHub** [Fyrd/caniuse#5074]
Hi,
when i search for example for the keyword "let" it shows me "Android Browser 67" but in the MDN-Docs it shows minimum 49 (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#Browser_compatibility). The Android Browser Version is often shown higher then in real is necessary. I tested "let" with a 55 Webview an it works.

**Comment by Schweinepriester** [comment]
the reason is that there is only one ~recent version of android browser tracked, unlike other browsers: https://github.com/Fyrd/caniuse/blob/master/features-json/let.json#L297

(arguably the version should be 76 not 67, like the most recent chrome version)

**Comment by GitToTheHub** [comment]
Ah ok, and do you know why only the recent version is maintained unlike other browsers? It's helpful to know, when not the most recent chrome version is needed to use some stuff.

**Comment by Schweinepriester** [comment]
Some insight might be at https://github.com/Fyrd/caniuse/issues/3518#issuecomment-308931205, but @Fyrd surely will react to this issue as well.

**Comment by GitToTheHub** [comment]
Hi, thank you for the other issue. I reallized, that i can see the first supported Android Browser Version, when i take the first supported Chrome version. I compared some searching between Desktop Chrome & Android Webview on MDN and the minimum Versions are always the same.
Examples: 
- let: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#Browser_compatibility
  Minimum Chrome: 49
  Minimum Android Webview: 49
- await: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#Browser_compatibility
  Minimum Chrome: 55
  Minimum Android Webview: 55
- Template literals: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Browser_compatibility
  Minimum Chrome: 41
  Minimum Android Webview: 41
So maybe the Android Browser could be replaced by the Chrome Version when its higher or equal then 37, because Android 5.0 was original shipped out with Android Webview 37 (see https://github.com/NoNameProvided/cordova-plugin-webview-checker#pre-installed-versions).

**Comment by Fyrd** [comment]
Thanks @Schweinepriester for linking to that comment! Yes, I need to update the Android Webview version, wow I didn't realize I'd let it fall behind so far. And yes, _most_ of the time Webview support matches Chrome for Android but there's a number of exceptions where the proper browser supports something but the webview does not which is why they're separate.

**Comment by jpmedley** [comment]
Here's the [list from our testing](https://cs.chromium.org/chromium/src/android_webview/tools/system_webview_shell/test/data/webexposed/not-webview-exposed.txt) off what is not in WebView. If you follow the link and look to the left, you'll see a sister file that tells what *is* in WebView.

**Comment by GitToTheHub** [comment]
@Fyrd Thank you for the explanation and @jpmedley for the link. I see there are some APIs which are not supported in the Android Webview, but i think for the basic functionality like checki!g ES6/7/8/etc. i can use the chrome version as minimal required version.
