### ISSUE TITLE
mdn/browser-compat-data version_removed is sometimes applied incorrectly

### ISSUE THREAD

**Issue by dlras2** [Fyrd/caniuse#5075]
Several features that pull their data from `mdn/browser-compat-data` apply the data's `version_removed` info incorrectly. Some examples:

- [Window API: `requestIdleCallback`](https://caniuse.com/#feat=mdn-api_window_requestidlecallback)'s Firefox data shows support only for only version 53 and 54, and shows the given note (applicable only to those versions) for all versions.
- [Window API: `blur` event](https://caniuse.com/#feat=mdn-api_window_blur_event)'s Firefox data shows the note (applicable only until version 23) for all versions. Additionally, support is shown to be only for the current and future versions, but I'm not sure if this is a separate bug.

This problem appears to occur whenever a feature has `version_removed` info that overlaps with other info. It's also important to note that [`version_removed` is exclusive](https://github.com/mdn/browser-compat-data/issues/4206).

**Comment by Fyrd** [comment]
Closing this issue as I believe it's resolved, feel free to open any new issues pertaining to the MDN BCD data translation.
