### ISSUE TITLE
Inline media queries

### ISSUE THREAD

**Issue by AeonFr** [Fyrd/caniuse#5091]
Requesting a caniuse page for inline media queries, that look like this:

```
<div style="color: red; @media (max-width: 200px) { color: green }">
```

Or like this:

```
<a href="#" 
    target="itunes_store" 
    style="
        display:inline-block;
        overflow:hidden;
        background:url(#.png) no-repeat;
        width:135px;
        height:40px;
        @media only screen{
            background-image:url(#);
        }
"></a>
```

This seems to be working in the latest versions of Chrome and Firefox.

Here is [a live demo](https://codepen.io/Grawl/pen/LbbEEW) (by @Grawl).

**Note:**  I came across this feature thanks to @Grawl and [this stackoverflow answer](https://stackoverflow.com/a/40650019/4217158)

**Note 2:** I don't seem to find this feature in the specks, is not a part of "Media queries level 4", nor "Media queries level 5"

**Comment by Grawl** [comment]
I never heard about spec for things like this

**Comment by cpplearner** [comment]
It's using JS behind the scene, so doesn't belong to caniuse AFAIK.

**Comment by AeonFr** [comment]
You are right @cpplearner , this is working using JavaScript. I didn't notice lol! 😭 🤣   Closing this issue.

It would be so nice if this was added to the specks, though  ✨ 
Thanks
