### ISSUE TITLE
CSP footnote specific to Firefox is wrong

### ISSUE THREAD

**Issue by jezen** [Fyrd/caniuse#5092]
In the caniuse page for [CSP](https://caniuse.com/#search=CSP), the footnotes show that Firefox versions 4 and above use the non-standard header name of `X-Content-Security-Policy`.

This is inconsistent with [Mozilla's own documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#Browser_compatibility). This lead me to serve up the old header name for requests from Firefox, and resulted in a downgraded security score on Mozilla Observatory.

cc @april

**Comment by april** [comment]
@jezen is correct, Firefox hasn't used `X-Content-Security-Policy` since Firefox 22.

This setting probably shouldn't even exist:
https://caniuse.com/#feat=mdn-http_headers_csp_content-security-policy

As the correct data is located at:
https://caniuse.com/#feat=contentsecuritypolicy

**Comment by antonjuulnaber** [comment]
Hmmm that's strange. That feature is supposed to sync with MDN's own `http/headers/content-security-policy.json`, but instead it synchronises with `http/headers/csp/content-security-policy.json` which doesnt exist.

@Fyrd  ?

**Comment by Fyrd** [comment]
Looks like https://caniuse.com/mdn-http_headers_csp_content-security-policy is gone and  the so I think this got cleaned up on the MDN BCD side since it was reported. https://caniuse.com/contentsecuritypolicy also appears correct, so closing this issue.
