### ISSUE TITLE
-webkit-flex-wrap: nowrap does not works with chrome 21 to 24

### ISSUE THREAD

**Issue by SuperPat45** [Fyrd/caniuse#5095]
I tested my site with the old chromium portable versions 21 and 24 and I found that the property:
-webkit-flex-wrap: nowrap;
does not work with these browsers, nowrap is not a valid value, however, it works fine if I add property:
-webkit-flex-wrap: none;
Starting from chrome 25, nowrap is recognized.

A note should be added on the flex-wrap page about this.

**Comment by Ugoku** [comment]
Chrome 24 is over 6 years old. Chrome has auto-update. Why are using such an old version?

**Comment by SuperPat45** [comment]
On an old linux powered laptop, Chromium does not have autoupdate.
Why do you keep informations of old chrome versions on caniuse?

**Comment by Fyrd** [comment]
Having support information on older versions is mostly useful for historical information and helps add confidence to developers to know that support has been around for a long time. I don't think it's useful however to add details like this to versions that are effectively no longer in use, that just adds noise to the information people seek on newer versions.
