### ISSUE TITLE
Add A2HS

### ISSUE THREAD

**Issue by Mlocik97-issues** [Fyrd/caniuse#5099]
Please add A2HS to caniuse

**Comment by Schweinepriester** [comment]
Is <https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen> meant?

Might be already covered by the individual pieces needed, not sure…

**Comment by antonjuulnaber** [comment]
It could be argued that it is already in the database as [web app manifest](https://caniuse.com/#feat=web-app-manifest), although it is not quite the same.
