### ISSUE TITLE
MediaRecorder API

### ISSUE THREAD

**Issue by nickdesaulniers** [Fyrd/caniuse#510]
An api that's been around since [Gecko 25](https://bugzilla.mozilla.org/show_bug.cgi?id=803414#c168), just [undocumented](https://bugzilla.mozilla.org/show_bug.cgi?id=891782).

Here's an [example usage](https://github.com/nickdesaulniers/MediaRecorderDemo/blob/master/record.js).

**Comment by Mark-L6n** [comment]
W3C MediaStream Recording API, with MediaRecorder object, is at: http://www.w3.org/TR/mediastream-recording/
