### ISSUE TITLE
http/3

### ISSUE THREAD

**Issue by georgfranz** [Fyrd/caniuse#5103]
Can I use http/3?

The latest Canary build of Chrome supports HTTP3 (crazy)

FF is still working on it:
https://bugzilla.mozilla.org/show_bug.cgi?id=1158011

Best wishes,
Georg.

**Comment by Danw33** [comment]
+1. I came looking for http/3+quic on caniuse earlier today, would love to see it implemented! 👍🏻

**Comment by Schweinepriester** [comment]
Duplicate of #4632.
