### ISSUE TITLE
OPTGROUP nesting level > 1

### ISSUE THREAD

**Issue by carlos-mora** [Fyrd/caniuse#5104]
Acording to [W3](http://www.w3.org/TR/html401/interact/forms.html#h-17.6) the specs states that only one level of nesting is allowed. But it also sugest that "Implementors are advised that future versions of HTML may extend the grouping mechanism to allow for nested groups (i.e., OPTGROUP elements may nest). This will allow authors to represent a richer hierarchy of choices."
It would be interesting to track the status of that features among different browsers.

**Comment by cpplearner** [comment]
That's HTML 4, afaik HTML 5 does not permit this extension.

**Comment by Fyrd** [comment]
Yeah, since HTML 5 doesn't allow it and has been out for a while now I don't think it's worth tracking.
