### ISSUE TITLE
Is <hgroup> obsolete?

### ISSUE THREAD

**Issue by BartolomeSintes** [Fyrd/caniuse#5105]
In https://caniuse.com/#search=hgroup it is said that &lt;hgroup&gt; is an obsolete/deprecated HTML element, but hgroup is not listed in the "Obsolete features" section of the HTML Living Standard (https://html.spec.whatwg.org/multipage/obsolete.html) and it has its own section https://html.spec.whatwg.org/multipage/sections.html#the-hgroup-element.

**Comment by Fyrd** [comment]
Yeah, I see it's in the WHATWG spec but not the W3C one, see the note at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup#Usage_notes

Agree that it should probably be removed from that list.

**Comment by BartolomeSintes** [comment]
I do not want to disscuss the MDN note as I do not know the details, but I would say that W3C did not remove hgroup (like frames), rather hgroup was not included in HTML 5 W3C.
Anyway, regarding the discrepancies between the WHATWG living standard and the W3C recommendation, after the `[Memorandum of Understanding Between W3C and WHATWG](https://www.w3.org/2019/04/WHATWG-W3C-MOU.html)`, announced in May, the W3C spec is becoming irrelevant, isn't it?
Of course, everything related with outline is not important nowadays. Keeping information updated is very difficult and I am sure there are a lot of things more important to do. I just wanted to made you aware of this detail.

**Comment by Fyrd** [comment]
Available at https://caniuse.com/#feat=mdn-html_elements_hgroup
