### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by GuttoSP** [Fyrd/caniuse#5106]
![table](https://user-images.githubusercontent.com/13170741/65834225-69946d80-e2af-11e9-8be2-68414e47aa94.png)
This should not be the appropriate place for this question, but you do not find it more appropriate. Caniuse.com displays the data in a table. Is this table a plugin? How can you display a similar table in another project?

**Comment by Fyrd** [comment]
While not exactly the same, I recommend the third party CanIUse Embed (
https://caniuse.bitsofco.de ) for that purpose.

**Comment by Fyrd** [comment]
Ah, I see. The tables you see are custom coded specifically for caniuse data so unfortunately not really portable to use for other purposes. Using the DOM inspector from a borwser's dev tools may help a bit.
