### ISSUE TITLE
Accessing pre html5 data

### ISSUE THREAD

**Issue by venpa** [Fyrd/caniuse#5107]
Hi,
  I do not see the data for pre-html5 elements support at https://github.com/Fyrd/caniuse; For example, there is no data available for `<div>` element support at https://github.com/Fyrd/caniuse. Is there a way to access those data?
 Thanks!!!

**Comment by HolgerJeromin** [comment]
The [inclusion of MDN Data](https://hacks.mozilla.org/2019/09/caniuse-and-mdn-compat-data-collaboration/) gives us that:
https://caniuse.com/#feat=mdn-html_elements_div

**Comment by venpa** [comment]
Thanks @HolgerJeromin

**Comment by LaySoe** [comment]
Thankfully.
