### ISSUE TITLE
Add iOS Safari 13.2

### ISSUE THREAD

**Issue by kiding** [Fyrd/caniuse#5112]
Same as #5068 but only for iOS Safari. There is no hint so far Safari (for macOS) 13.1/13.2 would be released any time soon.

**Comment by DaSchTour** [comment]
It look like missing iOS 13.2 breaks displaying of usage relative view. It looks like iOS only has a very small market share in comparison to Chrome Android. It was a lot higher some weeks ago.

**Comment by Fyrd** [comment]
Done!
