### ISSUE TITLE
QQ browser is not uptodate

### ISSUE THREAD

**Issue by stof** [Fyrd/caniuse#5114]
https://github.com/Fyrd/caniuse/issues/4463 reported this as part of the discussion, but it deserves its own issue to get feedback on that particular point.

CanIUse reports a 1.2 version for QQ browser. This does not match the latest Android version, which is at version 9.7 (https://sj.qq.com/myapp/detail.htm?apkName=com.tencent.mtt)

This does not match the Windows version either, which is at version 10.5 according to https://browser.qq.com/ (and probably based on Chromium 70).

This version number could be for the Mac version, which is at 1.2.9: https://apps.apple.com/app/qq%E6%B5%8F%E8%A7%88%E5%99%A8-lite-%E6%9E%81%E9%80%9F%E5%AE%89%E5%85%A8%E4%B8%8A%E7%BD%91%E6%B5%8F%E8%A7%88%E5%99%A8/id1178458919

And in any case, this question the relevance of the support data.

**Comment by Fyrd** [comment]
Yeah, it's been a while since I've updated QQ browser and as I recall it was hard to figure out the right version for it. Thanks for the reminder to update this.

**Comment by XVilka** [comment]
Current version is 10.5.3 and is indeed based on Chromium 70 - it's written in the main page

**Comment by Fyrd** [comment]
Have updated QQ browser now with the latest version (for Android it's 10.4, that's the browser that's tracked on caniuse)
