### ISSUE TITLE
Add :has-text() pseudo-class

### ISSUE THREAD

**Issue by ShaunDreclin** [Fyrd/caniuse#5115]
I'm not entirely sure if this is actually in the standard or not but I found it mentioned [here](https://superuser.com/questions/1285891/ublock-hide-any-element-that-contains-text-with-a-given-word) on superuser and it works in uBlock Origin

**Comment by Fyrd** [comment]
I don't believe this is in a specification or intended to be supported by any browser, in which case it shouldn't be tracked on caniuse.
