### ISSUE TITLE
Can you add the normal Opera Mini to the browser list?

### ISSUE THREAD

**Issue by ohyeaah** [Fyrd/caniuse#5118]
Currently there is Opera Mini with "extreme data savings enabled" in the browser list.
I have installed the latest Opera Mini and data saving was set to "automatic" by default.
It supported different features. For example woff2 is supported.

Maybe you can add the normal Opera Mini.

**Comment by Fyrd** [comment]
Regular Opera Mini however is not that popular a browser though and just uses the default OS browser engine (so will be different on iOS & Android). No intention on adding it for the same reason many other browsers using the default engine aren't added.
