### ISSUE TITLE
[text-stroke] data is not correct?

### ISSUE THREAD

**Issue by hacknug** [Fyrd/caniuse#5136]
According to [`text-stroke`](https://github.com/Fyrd/caniuse/blob/master/features-json/text-stroke.json#L216-L222), `safari` supports the property without prefixes but doesn't seem to be the case?

Any idea why this is happening or what is it that's supported without vendor prefixes? Am I missing something?

https://caniuse.com/#feat=text-stroke

**Comment by antonjuulnaber** [comment]
I'm not sure where you are seeing this. Safari is marked with a yellow box, indicating support only with a prefix.

**Comment by Fyrd** [comment]
I actually fixed this recently and forgot to update this issue.
