### ISSUE TITLE
scrolling causes site to break on macbook chrome

### ISSUE THREAD

**Issue by vishalbiswas** [Fyrd/caniuse#5138]
![Screenshot 2019-10-17 at 17 27 36](https://user-images.githubusercontent.com/7733255/67006703-731d3280-f103-11e9-8d1f-7ab2c85f33d0.png)

Searching for any feature and then scrolling gives the specified error in console.
Only the first result loads and nothing else.

Browser: Google Chrome Stable Version 77.0.3865.120 (Official Build) (64-bit)
OS: Mac OS Mojave 10.14.6 (18G103)
Page URL: https://caniuse.com/#search=%3Anot()

**Comment by Fyrd** [comment]
Sorry about, looks like a side-effect of removing Safari 3.1 recently. Do you have any regional or Google Analytics usage statistics imported? If so, re-importing should probably fix this. Alternatively may need to run `localStorage.clear()` from the console to reset saved data.

**Comment by vishalbiswas** [comment]
`localStorage.clear()` fixed it.

I have no idea about
> Do you have any regional or Google Analytics usage statistics imported?
