### ISSUE TITLE
Analytics import does not include iOS Safari 12.4

### ISSUE THREAD

**Issue by Ugoku** [Fyrd/caniuse#5142]
When importing statistics from Google Analytics, iOS Safari 12.4 is not included:

![2019-10-18 13 09 00 caniuse com b4dd40e39292](https://user-images.githubusercontent.com/3470653/67089668-8209f080-f1a8-11e9-89b8-d22cd8a3a79c.png)

Since this accounts for 10% of this particular website, it would be great if Safari 12.4 could be tracked. Thanks!

**Comment by Fyrd** [comment]
Should be fixed now!

**Comment by Ugoku** [comment]
Yup, thanks!
