### ISSUE TITLE
Website news sorted in wrong order

### ISSUE THREAD

**Issue by sandstrom** [Fyrd/caniuse#5156]
Thanks for an excellent tool!

I noticed that the news are sorted with the oldest entries first.

Perhaps this order could be inverted?
https://caniuse.com/#info_news

Tried to find the website source so I could PR a fix, but didn't find it.

**Comment by Fyrd** [comment]
Thanks for reporting, has now been fixed!

**Comment by sandstrom** [comment]
@Fyrd Awesome! 💯
