### ISSUE TITLE
Statistics skewed again

### ISSUE THREAD

**Issue by ameenross** [Fyrd/caniuse#5160]
Statistics are wrong again. I suppose it's statcounter data again. Maybe it's a good idea to have some kind of heuristic that checks if the percentages in a row actually add up to about 100%? That way you could alert statcounter of the mistake *before* it affects caniuse.com.

**Comment by Fyrd** [comment]
Can you be more specific on what statistics appeared incorrect?
The statistics were recently updated for October, which may have fixed things.

**Comment by ameenross** [comment]
It has indeed been fixed. [These statistics](https://caniuse.com/#feat=internationalization) had very low percentages and totals added up to like 60/70 not 100. The exact same thing has happened before.

I hoped that the issue could be prevented in the future, as people might look at statistics at the wrong moment and decide not to use a browser feature because of it. It also *seems* quite doable.

**Comment by ameenross** [comment]
This happened again. I added up all percentages of i18n for The Netherlands, and I end up with 89.94%. The total supported comes in at 89.12%. So about 10% is unaccounted for.

Also, if you divide 89.12 by 89.94, you end up with 99% (that's what I expect the supported percentage to be). But the `all tracked` statistic shows 93.43%. I have no idea where that number comes from.

**Comment by Fyrd** [comment]
I overhauled the way usage statistics are generated late last year which should prevent the issues described in this ticket.
