### ISSUE TITLE
CSS3 box-sizing: unable to verify a "Known issue" in Chrome

### ISSUE THREAD

**Issue by matjon** [Fyrd/caniuse#5162]
Hello,
The "Known issues" of "CSS3 box-sizing" currently specifies that:
"Chrome has problems selecting options from the select element when using box-sizing: border-box and browser zoom level is less than 100%."
This note was added in commit b48d2fc43f22753674e9b7e016519908ec9fac76 in April 2015.

I was unable to verify this issue nor check if it is still relevant. I have found no description of similar problems in the web and in Chromium bug reports (including closed ones). In quick testing I was unable to reproduce this issue.

Thank You for developing caniuse.com.

**Comment by Fyrd** [comment]
Yeah, that one was submitted anonymously back in 2015, have removed it now. Thanks for pointing that out!
