### ISSUE TITLE
MDN results show Edge 76 support incorrectly

### ISSUE THREAD

**Issue by theSdev** [Fyrd/caniuse#5169]
MDN results show Chromium Edge support the same as that for EdgeHTML Edge. Example: https://caniuse.com/#feat=mdn-css_properties_ruby-position suggests `ruby-position` is supported in Edge 76 but that's not the case.

**Comment by Fyrd** [comment]
For MDN data please see https://github.com/mdn/browser-compat-data/blob/master/docs/contributing.md or see the "What are we missing?" button at the browser compat table on
https://developer.mozilla.org/en-US/docs/Web/CSS/ruby-position
