### ISSUE TITLE
Invalid link for setForceDark in prefers-color-scheme

### ISSUE THREAD

**Issue by tdelmas** [Fyrd/caniuse#5171]
On https://caniuse.com/#feat=prefers-color-scheme the link "Needs to be enabled with this API) to use in Android WebView 76." is invalid as the ")" is supposed to be inside:
it points to `https://developer.android.com/reference/android/webkit/WebSettings#setForceDark(int` instead of `https://developer.android.com/reference/android/webkit/WebSettings#setForceDark(int)`

Generated by `enabled with [this API](https://developer.android.com/reference/android/webkit/WebSettings#setForceDark(int)) to use` in:

https://github.com/Fyrd/caniuse/blob/5169fedc4ba8269fddd0a1559e310367089e4261/features-json/prefers-color-scheme.json#L363

**Comment by Fyrd** [comment]
Looks like this note was removed since this was reported, so closing as no longer relevant.
