### ISSUE TITLE
Order browsers by use

### ISSUE THREAD

**Issue by lcswillems** [Fyrd/caniuse#5172]
This is the current view I have for the :focus-within table:

![image](https://user-images.githubusercontent.com/5437552/68597613-91294900-049d-11ea-9004-dc15404ecd66.png)

It is weird for me to display IE first because it is used very little. Will this current column order always be kept?

In 5 years, IE will be completely dead, and the column will always be completely red and useless, but it will be shown first.

I suggest, at least, an option to order the columns by browser use.

**Comment by Fyrd** [comment]
Yeah, I plan on at least adding an option for this with the rewrite of the site that's currently in progress.
In the mean time I recommend  you can configure the browsers shown under "Settings", you'll probably also want to change the default "Show" mode to "Filtered"

**Comment by lcswillems** [comment]
Okay, thank you for your answer! and the time you invest in this very helpful project!

**Comment by Fyrd** [comment]
The beta site (https://beta.caniuse.com) now has an option to change the order based on browser usage. Will close this issue once it's on the main site.

**Comment by lcswillems** [comment]
That's great!! Thank you for your work. It works perfectly!

**Comment by Fyrd** [comment]
This is now available on the main site.
