### ISSUE TITLE
Add iOS Safari 13.3

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#5175]
(Related #5112)

Separate because <https://www.macrumors.com/2019/11/12/ios-13-3-fido2-security-key-support-safari/> or from the changelog <https://developer.apple.com/documentation/ios_ipados_release_notes/ios_ipados_13_3_beta_2_release_notes>:

> Now supports NFC, USB, and Lightning FIDO2-compliant security keys in Safari, [`SFSafariViewController`](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller), and [`ASWebAuthenticationSession`](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) using the WebAuthn standard, on devices with the necessary hardware capabilities.

**Comment by Fyrd** [comment]
Has now been added, though haven't updated the features yet.
