### ISSUE TITLE
Add String.prototype.replaceAll()

### ISSUE THREAD

**Issue by TheLastZombie** [Fyrd/caniuse#5191]
Spec:
- https://tc39.es/proposal-string-replaceall/
- https://github.com/tc39/proposal-string-replaceall

replaceAll on v8.dev: https://v8.dev/features/string-replaceall

Tested on:
- IE 11.476.18362.0 (Stable) ❌
- Edge 44.18362.449.0 (Stable) ❌
- Edge 80.0.340.0 (Canary) ❌
- Firefox 70.0.1 (Stable) ❌
- Firefox 72.0a1 (2019-11-21) (Nightly) ✔️
- Chrome 78.0.3904.108 (Stable) ❌
- Chrome 80.0.3974.0 (Canary) ❌
- Opera 65.0.3467.48 (Stable) ❌
- Opera 66.0.3511.0 (Developer) ❌

**For updated/more detailed compatibility see #5204.**

Discussions:
- Chrome: https://bugs.chromium.org/p/v8/issues/detail?id=9801  
- Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1540021  
- Safari: https://bugs.webkit.org/show_bug.cgi?id=202471

Polyfills:
- core.js: https://github.com/zloirock/core-js#stringreplaceall
- es-shims: https://github.com/es-shims/String.prototype.replaceAll
- developit: https://gist.github.com/developit/1a40a6fee65361d1182aaa22ab8c334c

**Comment by Ugoku** [comment]
I'm not seeing this on caniuse.com yet, or on MDN for that matter. What happened to this?

**Comment by Ugoku** [comment]
I did some research:
- Chromium reverted adding this in December 2019 with the reason "Clusterfuzzed", which is the fuzzing infrastructure used on Chrome.
- Firefox added it in v72 in Nightly only because tests were missing. Bugzilla link to ship it in stable: https://bugzilla.mozilla.org/show_bug.cgi?id=1608168

Still, why does this not appear on caniuse ?

**Comment by TheLastZombie** [comment]
@Ugoku See [CONTRIBUTING.md](https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md#adding-a-feature):

> New additions will always start out with "shown": false (regardless of the initial value set in the PR). This is so the data can undergo a certain level of verification to guarantee the correctness of information shown on the site.

**Comment by Ugoku** [comment]
Ah, that makes sense. Thanks for the clarification!

**Comment by Ugoku** [comment]
Shipped in Firefox 77: https://bugzilla.mozilla.org/show_bug.cgi?id=1608168
