### ISSUE TITLE
Short empty tags

### ISSUE THREAD

**Issue by maximal** [Fyrd/caniuse#5192]
Short empty tags (like `<script />` or `<code />`) do not work in some browsers.

**Comment by Fyrd** [comment]
Not sure if that's necessarily valid HTML in the first place...can you give an example?

**Comment by Schnark** [comment]
Indeed, self-closing tags are not valid in HTML (see https://html.spec.whatwg.org/multipage/parsing.html#acknowledge-self-closing-flag), they are only valid for embedded XML (i.e. inside `<math>` and `<svg>`), ignored for empty tags (so `<br>` and `<br />` are identical), and a parser error in all other cases (which may or may not give the desired result), but all browsers that implement the HTML5 parser correctly (I can't find a support table for that, but it should be a bit but not much more green than https://caniuse.com/#feat=svg-html5) should behave the same.
If you want `<foo />` to be equivalent to `<foo></foo>` you have to serve the file as `application/xhtml+xml` and look at https://caniuse.com/#feat=xhtml.

**Comment by Fyrd** [comment]
Closing this issue as per @Schnark 's info.
