### ISSUE TITLE
Portals API

### ISSUE THREAD

**Issue by ThomasFeyrer** [Fyrd/caniuse#5195]
New API from Google:

https://web.dev/hands-on-portals/

https://www.zdnet.com/article/google-launches-portals-a-new-web-page-navigation-system-for-chrome/

In which we make loading disappear with 'portal' and friends (Chrome Dev Summit 2019)
https://www.youtube.com/watch?v=X2zqwMBBvIs

**Comment by Schweinepriester** [comment]
Duplicate of #4679.

That issue could use the string "Portals API" for better visibility as well as the second and third URL though.
