### ISSUE TITLE
Add `window.$`

### ISSUE THREAD

**Issue by sytana** [Fyrd/caniuse#5196]

**Comment by Fyrd** [comment]
Does this refer to jQuery or the `window.$` that's accessible in the console for some browsers?

**Comment by sytana** [comment]
Not jquery!

**Comment by kiding** [comment]
`$`, also known as ["Console Utilities API" is only available when DevTools/Web Inspector is opened,](https://developers.google.com/web/tools/chrome-devtools/console/utilities) which means JavaScript file itself can never use it.

**Comment by Fyrd** [comment]
I feel that since this is a developer tool specific feature it's out of scope for caniuse. Since it only matters if it works while you're using the console it's pretty easy to find out if it's working in the dev tools you're in and you shouldn't have to worry about cross-browser compatibility.
