### ISSUE TITLE
backdrop-filter duplicate

### ISSUE THREAD

**Issue by MattDiMu** [Fyrd/caniuse#5197]
The same feature (CSS backdrop-filter) seems to be listed twice:

https://caniuse.com/#feat=css-backdrop-filter
https://caniuse.com/#feat=mdn-css_properties_backdrop-filter

The former seems to have slightly more and better information. Is there any reason for keeping the latter featurebox (mdn-css_properties_backdrop-filter)?

**Comment by Schweinepriester** [comment]
`css-backdrop-filter` is from caniuse natively and `mdn-css_properties_backdrop-filter` is from MDN.

More details: <https://hacks.mozilla.org/2019/09/caniuse-and-mdn-compat-data-collaboration/>

**Comment by Fyrd** [comment]
At some point I intend to filter out MDN tables that have a better caniuse table, but until then this is intended behavior.
