### ISSUE TITLE
Consider adding Blazor Server and Blazor WebAssembly

### ISSUE THREAD

**Issue by jucchytil** [Fyrd/caniuse#5201]
Microsoft's newest web technology for the web is called Blazor. 

Blazor Server should work everywhere as it only downloads a small Javascript file and uses SignalR for all browser UI updates.

Blazor WebAssembly depends on the browser supporting webassembly. 
I see you already have an entry for webassembly https://caniuse.com/#feat=wasm

Just a thought. I think your community will eventually find this useful.

**Comment by Fyrd** [comment]
Seems like a framework rather than a web technology (it's not something browsers need to implement like web assembly support), so out of scope for caniuse.
