### ISSUE TITLE
html canvas.globalCompositeOperation

### ISSUE THREAD

**Issue by hikikomori82** [Fyrd/caniuse#5207]
Older safari (5.1.7 on windows) does not support globalCompositeOperation='destination-in'

<canvas id="a" width=100 height=100></canvas>
<script>
var c = a.getContext('2d');
c.fillStyle = 'red';
c.fillRect(0,0,100,100);
c.fillStyle = 'black';
c.globalCompositeOperation = 'destination-in';
c.fillRect(20, 20, 30, 10);
</script>

On normal browsers you see small 30x10 red rectangle. On safari it is one large 100x100 red box.

**Comment by Fyrd** [comment]
Already available at https://caniuse.com/#feat=mdn-api_canvasrenderingcontext2d_globalcompositeoperation though is missing some information. Out of curiosity, do you really need to support Safari 5.1 on Windows? That browser's 8 years old already.

**Comment by Fyrd** [comment]
Looks like that data's been updated, so closing this issue.
