### ISSUE TITLE
What does the dark row backing mean?

### ISSUE THREAD

**Issue by preagan** [Fyrd/caniuse#5210]
Caniuse is a great tool!  I'm curious though about the dark band that appears on every result (that I've seen).  The legend explains the color for each version of each browser, but they're all backed by a dark row at some level down from the top.  What's the significance of this?  Thanks!

![Screen Shot 2019-12-16 at 3 34 40 PM](https://user-images.githubusercontent.com/35608297/70952166-52e1f500-201a-11ea-9f0d-9109772a3f8a.png)

**Comment by PeterShaggyNoble** [comment]
Aligned as they are, it should be clear that that's the current version of each browser.

**Comment by preagan** [comment]
Of course!  Now it makes sense.  Thanks.

**Comment by Fyrd** [comment]
Closing this issue, though I am considering adding an indicator to make this clearer.
