### ISSUE TITLE
Browser Compat Data on MDN not the same as on 

### ISSUE THREAD

**Issue by GustvandeWal** [Fyrd/caniuse#5219]
On pages like that of [Symbol.description](https://caniuse.com/#feat=mdn-javascript_builtins_symbol_description), it says for every version of Safari that there's no support for undefined values. [The data displayed by MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/description#Browser_compatibility) says there is support from 12.1 onwards. Coincidentally, the fact that it is supported is hidden in the notes, so it might be an error in the way the table data is formatted:

![image](https://user-images.githubusercontent.com/15628812/71213272-60fe7280-22b3-11ea-9a5e-f0cedca9aa22.png)

I don't know where things go wrong here, but the issue seems urgent.

Tested on iOS Safari 12 and 12.2. The data as shown in the image is correct.

**Comment by Fyrd** [comment]
Good callout, thanks. Found the issue in the translation from MDN to caniuse data specific to cases of partial support and have now fixed it.
