### ISSUE TITLE
Remove "backward compatible" from SameSite=None breaking change

### ISSUE THREAD

**Issue by JessicaSachs** [Fyrd/caniuse#5222]
On [this](https://caniuse.com/#feat=same-site-cookie-attribute) support table page the first note is that the feature is backward compatible and _no_ changes are necessary. While this might be the case for a regular website, this is not the case for third-party vendors.

As a third-party vendor, you must implement user-agent sniffing and detection based on the bug report mentioned [here](https://bugs.webkit.org/show_bug.cgi?id=198181)

Deep in the linked thread, you can find the user agent sniffing regexp that the Webkit team advises you to do ([link](https://bugs.webkit.org/show_bug.cgi?id=198181#c24)) if you require legacy cookie behavior (e.g. SameSite=None) to work in iOS pre-13 and MacOS pre-Catalina

Please update the wording of the notes to make this breaking change more apparent, as `SameSite=None` is **not** backward compatible if you need to send your cookies cross-domain as a third party on iOS pre-13 and MacOS pre-Catalina

**Comment by Sora2455** [comment]
Chromium 51 to 66 also aren't backwards compatible, as well as UC Browser 12.13.2 and below: https://www.chromium.org/updates/same-site/incompatible-clients

**Comment by Fyrd** [comment]
Have removed that note entirely and added a link to the incompatible clients info. Thanks!
