### ISSUE TITLE
ExtendableEvent.waitUntil() is availible on Safari 12.1.2

### ISSUE THREAD

**Issue by i5heu** [Fyrd/caniuse#5240]
In https://caniuse.com/#feat=mdn-api_extendableevent_waituntil
Safari has falsely no Support for the waitUntil method.

CONSOLE  on Safari 12.1.2 (in the ServiceWorker):
```js
$ const foo = new ExtendableEvent({});
$ foo.waitUntil
   > function waitUntil() {[native code]}
```

**Comment by Fyrd** [comment]
As this comes from the MDN BCD data please go to https://developer.mozilla.org/en-US/docs/Web/API/ExtendableEvent/waitUntil#Browser_compatibility and click "What are we missing" to submit corrections.
