### ISSUE TITLE
Remove MS Edge status links

### ISSUE THREAD

**Issue by samspade** [Fyrd/caniuse#5246]
These links no longer work since the move to Chromium.

**Comment by mgol** [comment]
IMO it might be better to move them to Web Archive URLs instead. They provide info that may be valuable, it'd be shame to lose all that only because Microsoft scrapped the site.

**Comment by Fyrd** [comment]
Yeah, I agree with @mgol, will need to think about how best to handle these.

**Comment by Fyrd** [comment]
I actually discovered the URLs just needed some tweaking to work now, so they can continue to exist (for example: https://developer.microsoft.com/en-us/microsoft-edge/status/svgsmilanimation/ ) . Have also made the change to look at the Chromium status, not the EdgeHTML one.
