### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by Ugoku** [Fyrd/caniuse#5250]
https://caniuse.com/process/query.php?search=main (or any query) returns

```
Failed to run query: The used SELECT statements have a different number of columns
(SELECT * FROM wciu_textsearch) UNION (SELECT * FROM wciu_textsearch_mdn)""
```

**Comment by sevillaarvin** [comment]
<details>
<summary>
HAR:
</summary>
<pre>
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "Firefox",
      "version": "72.0.1"
    },
    "browser": {
      "name": "Firefox",
      "version": "72.0.1"
    },
    "pages": [
      {
        "startedDateTime": "2020-01-23T19:38:10.204+08:00",
        "id": "page_2",
        "pageTimings": {
          "onContentLoad": -1,
          "onLoad": -1
        }
      }
    ],
    "entries": [
      {
        "pageref": "page_2",
        "startedDateTime": "2020-01-23T19:38:10.204+08:00",
        "request": {
          "bodySize": 0,
          "method": "GET",
          "url": "https://caniuse.com/process/query.php?search=flexbox",
          "httpVersion": "HTTP/2",
          "headers": [
            {
              "name": "Host",
              "value": "caniuse.com"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
            },
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.5"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Referer",
              "value": "https://caniuse.com/"
            },
            {
              "name": "DNT",
              "value": "1"
            }
          ],
          "cookies": [],
          "queryString": [
            {
              "name": "search",
              "value": "flexbox"
            }
          ],
          "headersSize": 304
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/2",
          "headers": [
            {
              "name": "date",
              "value": "Thu, 23 Jan 2020 11:38:11 GMT"
            },
            {
              "name": "server",
              "value": "Apache"
            },
            {
              "name": "strict-transport-security",
              "value": "max-age=63072000; preload"
            },
            {
              "name": "vary",
              "value": "Accept-Encoding"
            },
            {
              "name": "content-encoding",
              "value": "gzip"
            },
            {
              "name": "content-length",
              "value": "145"
            },
            {
              "name": "content-type",
              "value": "text/html"
            },
            {
              "name": "X-Firefox-Spdy",
              "value": "h2"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "text/html",
            "size": 169,
            "text": "Failed to run query: The used SELECT statements have a different number of columns<br>(SELECT * FROM wciu_textsearch)\n\t\t\t\tUNION\n\t\t\t\t(SELECT * FROM wciu_textsearch_mdn)\"\""
          },
          "redirectURL": "",
          "headersSize": 237,
          "bodySize": 382
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": 0,
          "connect": 1169,
          "ssl": 285,
          "send": 0,
          "wait": 374,
          "receive": 0
        },
        "time": 1828,
        "_securityState": "secure",
        "serverIPAddress": "199.250.214.41",
        "connection": "443"
      }
    ]
  }
}
</pre>
</details>

**Comment by paulhayes** [comment]
I'm getting this too, not on all searches. Curl replay with:

```curl 'https://caniuse.com/process/query.php?search=Canvas' -H 'authority: caniuse.com' -H 'pragma: no-cache' -H 'cache-control: no-cache' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36' -H 'accept: */*' -H 'sec-fetch-site: same-origin' -H 'sec-fetch-mode: cors' -H 'referer: https://caniuse.com/' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' -H 'cookie: _ga=GA1.2.1252630305.1579622573; _gid=GA1.2.845969261.1579767283; _gat=1' --compressed```

**Comment by Fyrd** [comment]
Sorry about that, should be fixed now.
