### ISSUE TITLE
grid-row-gap and grid-column-gap

### ISSUE THREAD

**Issue by morojosa** [Fyrd/caniuse#5260]

**Comment by Schweinepriester** [comment]
<https://developer.mozilla.org/en-US/docs/Web/CSS/row-gap>

> [CSS Grid Layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) initially defined the `grid-row-gap` property. This prefixed property is being replaced by `row-gap`.

<https://developer.mozilla.org/en-US/docs/Web/CSS/column-gap>

> [CSS Grid Layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) initially defined the `grid-column-gap` property. This prefixed property is being replaced by `column-gap`.

So, arguably covered by <https://caniuse.com/#feat=mdn-css_properties_row-gap_grid_context> and <https://caniuse.com/#feat=mdn-css_properties_column-gap_grid_context>. 
Finding those when searching might be a consideration, though.

**Comment by Fyrd** [comment]
These appear when searching for the name:
https://caniuse.com/?search=grid-row-gap
https://caniuse.com/?search=grid-column-gap
, so closing this ticket.
