### ISSUE TITLE
Add caniuse data for Text Fragment spec

### ISSUE THREAD

**Issue by querkmachine** [Fyrd/caniuse#5265]
The [Text Fragment draft spec](https://wicg.github.io/ScrollToTextFragment/) was introduced by Google and shipped in Chrome 80 this week. caniuse currently doesn't have any information for this API.

**Comment by Schweinepriester** [comment]
Duplicate of #5102 and has been added by #5256, but not yet shown: <https://github.com/Fyrd/caniuse/blob/master/features-json/url-scroll-to-text-fragment.json#L377>

**Comment by querkmachine** [comment]
Cool. Must've missed it somehow when I tried searching for it. Will close.
