### ISSUE TITLE
Start tracking Geo URI scheme 

### ISSUE THREAD

**Issue by jameswilson** [Fyrd/caniuse#5268]
Would be useful to know which platforms/devices support links in the [Geo URI scheme](https://en.wikipedia.org/wiki/Geo_URI_scheme), eg:

```
<a href="geo:12.345,67.890?z=17">geo:12.345,67.890?z=17</a> 
```

"Support" in this case, would be defined as actually sending the user to a maps program, or a map website (eg google, or openstreetmaps). 

Note: there is an existing [custom protocol handling](https://caniuse.com/#feat=registerprotocolhandler) in caniuse, but it doesn't mention all of the [safelisted](https://html.spec.whatwg.org/multipage/system-state.html#custom-handlers) schemes, such as "tel" or "geo", so a search query or short turns up nothing.

### Examples

https://caniuse.com/#search=tel
https://caniuse.com/#search=telelphone <-- turns up only `<input type="telephone">`
https://caniuse.com/#search=geouri

### Resources

https://en.wikipedia.org/wiki/Geo_URI_scheme
https://html.spec.whatwg.org/multipage/system-state.html#custom-handlers
https://caniuse.com/#feat=registerprotocolhandler

**Comment by Schweinepriester** [comment]
Duplicate of #1192? 

If true, #1192 could use the contents of this issue, which are good!

**Comment by jameswilson** [comment]
oh, my apologies.  I totally forgot to search first :(   This is probably a duplicate, but I don't really have the power to clean up the other issue title (which is wrong, it is geo:uri not url) or add my content to the OP.

**Comment by Schweinepriester** [comment]
The content as comment would be enough i think, but the title could use some fixing indeed.

@Fyrd will surely do something once he sees this issue here :)

**Comment by Fyrd** [comment]
Have updated the title on #1192, @jameswilson want to add your comment's content there too? Then I'll close this issue. Thanks!

**Comment by jameswilson** [comment]
Good point. Thanks @Fyrd . I've copied the comment over and will close this.
