### ISSUE TITLE
add HTML 5 <dialog> tag

### ISSUE THREAD

**Issue by getsetgopi** [Fyrd/caniuse#5278]
More info. here https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

**Comment by Fyrd** [comment]
Already available at https://caniuse.com/#feat=dialog
Guess it could use `<dialog>` as a keyword

**Comment by getsetgopi** [comment]
Strange! yesterday when I searched with "dialog" and/or "<dialog>" it returned 0 result. Anyways, I can see it now, I will close the ticket.

Thanks for the link
