### ISSUE TITLE
Update Intl.PluralRules for Safari

### ISSUE THREAD

**Issue by JBYoshi** [Fyrd/caniuse#5285]
Based on the tests at tests.caniuse.com, [`Intl.PluralRules`](https://caniuse.com/#feat=intl-pluralrules) is supported in the latest versions of Safari for macOS (13) and iOS (13.3). However, I'm not sure how far back the implementation goes.

**Comment by JBYoshi** [comment]
It was first implemented in Safari TP 56 (May 2018): https://webkit.org/blog/8296/release-notes-for-safari-technology-preview-56. This appears to correspond to Safari 12.

**Comment by atjn** [comment]
Yep, seems like you are right. I tested it to work on Safari 13+ with no support on 12.1/12.4
Thanks for the hint!
For reference, tests used: https://caniuse.com/tests/?feat=intl-pluralrules
