### ISSUE TITLE
Placeholder attribute should be only partial support on Safari

### ISSUE THREAD

**Issue by KingSupernova31** [Fyrd/caniuse#5293]
The spec for the "placeholder" HTML attribute supports line breaks. Safari ignores them however and renders all the content on a single line. CanIUse says that recent Safari versions support placeholder, but due to the above issue I think it should show partial support.

**Comment by Fyrd** [comment]
Not sure if that quite warrants partial support, but have added it under known issues. Thanks for reporting!
