### ISSUE TITLE
Edge 18 is current

### ISSUE THREAD

**Issue by thany** [Fyrd/caniuse#5298]
The website appears to presume Edge 80 is the current/satble version. It's not. The latest mainstream version of Windows 10 comes with Edge 18, so Edge 18 should be considered the current/stable version. Edge >78 are future versions that can probably be installed separately, but that doesn't make them mainstream.

As long as Windows 10 comes with Edge 18, we should be taking that as the current latest version when it comes to web development.

In the same way, I can install Chrome Canary, which is currently at version 82, but that doesn't make Chrome 82 the current/stable version.

**Comment by atjn** [comment]
I'm not sure your comparison with Chrome is doing you any favors here:

1) [Edge has Canary, Dev and Beta versions](https://www.microsoftedgeinsider.com/en-us/download) just like Chrome, making Edge 80 the latest stable branch, according to your logic.
2) Edge 80 is downloaded as a stable browser from a website, just like Chrome.

You seem to mix "latest stable" and "mainstream" together. Caniuse is marking Edge 80 "latest stable". Not "mainstream". In fact, most of caniuse is based on usage statistics, making it irrelevant which browser is marked as "the latest stable". Edge 18 has more weight on the statistics than Edge 80, exactly because Edge 18 is the mainstream version of Edge.

**Comment by thany** [comment]
I'm not sure why you're mixing in the statistics, but the fact of the matter is that Edge 78 (and indeed 80) are not stable, because Microsoft is not replacing Edge 18 yet through Windows Update. 

You seem to be in disagreement with yourself by stating "Edge 18 has more weight on the statistics than Edge 80" anyway. And this makes sense: Edge 18 is not yet replaced, making it both latest stable *and* mainstream. I'm not surprized that most Edge users are on 18.

If you consider Edge 80 as a browser "downloaded as a stable browser from a website" then it should be considered separate from Edge 18. It might as well be pooled in with all the Chromium-like browsers, like Opera, Chrome, Vivaldi, and Brave, if you feel the need to compare it so seemingly closely to Chrome.

**Comment by atjn** [comment]
If you download Edge for Android or IOS through the official app store, you will recieve Chromium Edge. If you download Edge for MacOS, you will recieve Chromium Edge. If you go to [Wikipedia](https://en.wikipedia.org/wiki/Microsoft_Edge), Edge 80 is marked as "Current Stable". If you go to [Microsoft's own blog](https://blogs.windows.com/msedgedev/2020/01/15/upgrading-new-microsoft-edge-79-chromium/), they call Edge Chromium "stable". I'm sorry, but it's you against the whole world on this one.
It is definetely legitimate to also call Edge 18 "current stable", but that is current stable of the old version, while Edge 80 is current stable of the new version.

**Comment by thany** [comment]
Okay, I shall take back that Edge 80 is unstable. But I cannot take back the fact that Edge 18 is still mainstream and *on Windows* the latest version that everyone has. Most people that don't use Firefox or Chrome, will use whatever Windows comes with, and that is Edge 18.

Fact of the matter is that if you *don't* download Edge manually, you'll have 18. If you can convince me otherwise, I'd be massively impressed, because I've checked for updates just this morning, and there were none. And I'm on Edge 18.

So we can say Edge 18 is precisely as current and stable and mainstream as Edge 80 is on other platforms. The same rule already applies to IE11. If you're going to let Edge 18 sink away to the previous versions, so should IE11. Yes IE is a *totally* different browser from Edge. But Edge 80 is a *totally* different browser from 18 just as well.

**Comment by Fyrd** [comment]
Some good points made here, just looked for the word from Microsoft on the subject and found the [blog post](https://blogs.windows.com/msedgedev/2020/01/15/upgrading-new-microsoft-edge-79-chromium/) mentioned earlier by @atjn. For the upgrade it mentions a "measured roll-out approach over the next several months" which indicates that indeed some users (possibly most for now) will still be on Edge 18 while others should be upgraded and on Edge 80.

Perhaps it would be more accurate to separate the two but I don't feel this temporary ambiguity is really worth that, as stated Edge 80 is in fact the latest stable version. Ultimately, it don't really matter match as it matters much as long as caniuse acknowledges when browser versions still has plenty of users, which it does.

@kypflug do you have any comments on the matter?

**Comment by thany** [comment]
There's also the matter of Windows Enterprise editions, which (correct me if I'm wrong) are even less eeger to upgrade things than the regular mainstream Windows. This is perhaps kind of similar, as far as browsers go anyway, to Firefox ESR.

**Comment by Fyrd** [comment]
Closing this per my last comment.

**Comment by kypflug** [comment]
@Fyrd Sorry for missing your earlier tag here until now. For our part, it is correct to refer to Edge 80 as the current stable version. While we have not yet upgraded the full population of Edge <=18 users to Edge 80+, the rollout has begun and those versions are now considered "legacy." As noted in the blog post you linked, that rollout will begin accelerating in the coming months.

**Comment by Fyrd** [comment]
Thanks for the update @kypflug !

**Comment by thany** [comment]
> that rollout will begin accelerating in the coming months

So Edge 80 has essentially the same status as Chrome Canary or Firefox Nightly, and yet those are correctly displayed as being future versions.

**Comment by thany** [comment]
I'm not ne to say this easily, but: I told you so.

Edge 18 is *still* the mainstream version, even on Windows 10 2004.
I still think version 18 should (also) be considered the most recent one. Edge-based-on-Blink is simply a separate version, much like MSIE is different from Edge when it came out.

**Comment by atjn** [comment]
> Edge 18 is _still_ the mainstream version

Based on what information? As far as i can tell, Microsoft has pushed Chromium Edge to most installs. According to StatCounter, Chromium Edge accounts for ~2.3% of the market share while Edge 18 and earlier only accounts for ~0.6%.

**Comment by thany** [comment]
Based on my install, and everyone around me (coworkers mostly). None of us have got the Chromium version, and all of us are on v2004. I don't understand where this notion is coming from that v85 has been pushed through Windows Update, because it's just not. Even doing multiple manual update check per week, checking that optional updates is enabled, does not yield an update to Edge 85 (or any version over 18). This leads me to conclude that Edge 18 (on Windows 10) is mainstream, and Edge 85 is a voluntary install just like any other browser.

Marketshare has nothing to do with it being mainstream or not. Not in this context anyway. It just means a lot of people have manually upgraded Edge. But that doesn't mean that people who don't manually upgrade, like is oftenly the case in corporate situations, magically got that new version.

**Comment by atjn** [comment]
>  I don't understand where this notion is coming from that v85 has been pushed through Windows Update, because it's just not.

v85 has definitely been pushed through Windows Update. Here is a good article on it: https://www.theverge.com/21310611/microsoft-edge-browser-forced-update-chromium-editorial
Maybe you and your coworkers are using computers with company policies applied? Or maybe you're all using a specific model, that Microsoft has deemed unfit for the new update for now.

> Marketshare has nothing to do with it being mainstream or not.

Marketshare is exactly what defines mainstream. Mainstream is what most people use, and most people are using the new Edge. It doesn't matter how they got there. It matters that it is the thing most people use. The global usage for Edge 18 is already below 0.5% - the cutoff where most tools will no longer take it into consideration for interoperability issues.

**Comment by thany** [comment]
> > I don't understand where this notion is coming from that v85 has been pushed through Windows Update, because it's just not.
> 
> v85 has definitely been pushed through Windows Update. Here is a good article on it: https://www.theverge.com/21310611/microsoft-edge-browser-forced-update-chromium-editorial

It has not been been pushed at all. My personal pc and laptop haven't got it. My dad hasn't got it. My friends haven't got it. I don't know anyone who got it. I don't know anyone who knows anyone else, who got it.

Maybe Microsoft has pushed it only for Surface devices or something. Our devices are *quite* capable of running Edge 85.

> > Marketshare has nothing to do with it being mainstream or not. **Not in this context anyway**
> 
> Marketshare is exactly what defines mainstream. Mainstream is what most people use, and most people are using the new Edge. It doesn't matter how they got there. It matters that it is the thing most people use. The global usage for Edge 18 is already below 0.5% - the cutoff where most tools will no longer take it into consideration for interoperability issues.

Do you see what I bold-texted there? For any other browser, marketshare is indeed what defines mainstream. But for built-in browsers, you have to look at what is supplied by the vendor (Microsoft) to normal users (who don't voluntarily install a new version). Sure, the usage is below 0.5%, but that is separate from users on Windows 10 that haven't voluntarily updated Edge. In other words, "mainstream" is defined by what is supplied by Microsoft to its Windows 10 users.

Hypothetically, in macOS if there's a Safari 14 TP and everyone decides to install it, 13.1 is still mainstream in Catalina. That's what Apple provides, and that's what defines its mainstream-ness.

**Comment by atjn** [comment]
I don't see how continuing this discussion will result in anything constructive. You are denying a claim that i have documented with a public source.

**Comment by Fyrd** [comment]
Further official evidence:
https://support.microsoft.com/en-us/help/4576754/update-for-the-new-microsoft-edge

And do you really think 3/4 of Edge users installed the update manually? 

Not sure why you feel the need to argue against this so strongly, if you want to know what's supported in Edge 18 you can still find out.

**Comment by thany** [comment]
I'm sure the evidence is legitimate, and I'm sure Microsoft genuinely thinks it's true as well. But it's just not. If Edge were on WUP, we wouldn't be having this discussion.

How many times do I have to say it? Edge 18 is current because Edge-Chromium is not provided in Windows Update, on *any* machine I've seen updating. Be it a manual "go check for updates", or automatic. Be it with or without "optional updates".

It's great for all the macOS and Linux users that they cannot have any Edge *other than* the Chromium version, but every Windows user will have Edge 18, unless they updated voluntarily.

Or are you saying there's something wrong with every pc I have tried this on? Or that I'm not telling the truth? You can just ask literally any Windows 10 user: "have you updated Edge yourself?" -> if the answer is no -> "What version of Edge are you on?" -> the answer *will* be 18, promised.

I don't understand why you are arguing so strongly against this. Edge 18 is supplied with every Windows 10 install, it is not updated, it is still very much within support lifecycle, and very much not EOL. If nothing else, it is *at least* a different browser from Edge 85 that deserves a spot, just like Opera deserves a spot even if it's virtually identical to Chromium, and just like MSIE used to deserve a spot next to Edge when they were both mainstream.
