### ISSUE TITLE
FontFace API: display incorrect for Edge (Chromium)

### ISSUE THREAD

**Issue by Nooshu** [Fyrd/caniuse#5301]
Current data says it isn't supported: https://caniuse.com/#feat=mdn-api_fontface_display

But tests [here](https://www.webpagetest.org/video/compare.php?tests=200226_R2_d47a4449b35c9304f1b2cc9badc4d86f%2C200226_6X_01c6377112ad6db3543409f728162c6e%2C200226_EG_9a6eab6d3d230565dfc43de31233698a&thumbSize=300&ival=100&end=visual) and testing the [test page](view-source:https://keen-northcutt-3190bd.netlify.com/manually-added-font-swap.html) in Chromium 80 shows there is a `display` property in the `FontFace`.

Related tweets [here](https://twitter.com/TheRealNooshu/status/1232793818921144320) and [here](https://twitter.com/zachleat/status/1232796784717639686).

**Comment by vinyldarkscratch** [comment]
It appears that the data comes from MDN browser-compat-data (BCD) for that particular feature, and on the MDN web docs, support is properly marked (see https://wiki.developer.mozilla.org/en-US/docs/Web/API/FontFace).  We just recently performed a mass data mirroring of Chrome to Edge in BCD, so it's possible that the data has yet to update on CanIUse.  Either that, or maybe ranged values from BCD aren't implemented in CanIUse?

@Fyrd, can you comment on ranged value support for the BCD data?

**Comment by Fyrd** [comment]
Yup, looks like ranged value support wasn't properly implemented on the caniuse side. I did have some code specific to the "≤37" Android versions but that was pretty hard-coded. Have just pushed a change that hopefully supports version ranges more correctly, see https://caniuse.com/#feat=mdn-api_fontface_display

**Comment by Fyrd** [comment]
Thanks for discovering the cause of the discrepancy, @vinyldarkscratch !

**Comment by Nooshu** [comment]
<img width="572" alt="Screenshot 2020-02-27 at 09 02 21" src="https://user-images.githubusercontent.com/1223960/75428371-fa937180-593f-11ea-8a31-9b11fa982e34.png">

Can now see the fix. Thanks for the prompt response!
