### ISSUE TITLE
Suggestion: Telegram .TGS stickers (animated/nonanimated)

### ISSUE THREAD

**Issue by jasonkhanlar** [Fyrd/caniuse#5304]
See:

https://telegram.org/blog/animated-stickers

https://core.telegram.org/animated_stickers

As of yet, I don't see any web browsers that provide support for this yet, but other than SVG animations, it seems there are plenty of amazing .TGS animations designs already implemented, and it would be wonderful to see these to be useable in web browser in the future!

**Comment by Fyrd** [comment]
I don't believe this is a standard intended for browsers to be supported natively, so don't think it makes sense to add to caniuse. Can you provide any information to the contrary?

**Comment by Fyrd** [comment]
Closing for now.
