### ISSUE TITLE
Search filtering does not persist

### ISSUE THREAD

**Issue by nemoDreamer** [Fyrd/caniuse#5309]
It seems that issue #4557 is still around:
Even with "Default Display Settings > Show: Filtered" set, typing a search resets all filters, and changing a filter clears out the search.

On a related note, shouldn't "Show: Filtered" be the default behavior if you're opening a panel to filter results? If I hadn't hunted through your issue log, I would never have noticed that "Default Display Settings" category. Seems like wonky UX?

**Comment by Fyrd** [comment]
"Show: Filtered" refers to the browsers shown, not the features shown as result of a search.

Currently feature filtering applies to the entire set of caniuse features which acts separately from the search, which includes MDN BCD features. I agree this is rather confusing behavior and is more of an artifact of how the site used to work before it became more search-driven. Would like to improve that in the future, though.

**Comment by Fyrd** [comment]
Closing this issue per my last comment.
