### ISSUE TITLE
css-focus-visible(css-focus-visible.json) should be true for samsung >= 9

### ISSUE THREAD

**Issue by PavMel** [Fyrd/caniuse#5310]
Hi, there.     
I have tested `css-focus-visible` (caniuse), focuswithin (Modernizr)  with `Samsung Internet` on real devices with Modernizr .
1. 11.1.1.52 - is true
2. 9.0.01.80 - is true

**Comment by Fyrd** [comment]
Just tried this test case in Samsung Internet 11 with an attached keyboard and did not see the border when tabbed to, which does work in supporting browsers:
https://codepen.io/anon/pen/XeeJMo

**Comment by PavMel** [comment]
Hi, @Fird. Thank you for your test and for your help. I will report it to Modernizr in such case.
Have a nice day!
