### ISSUE TITLE
Intl.NumberFormat - notation (scientific, engineering, etc)

### ISSUE THREAD

**Issue by rafaelcastrocouto** [Fyrd/caniuse#5312]
Add the support for each notation supported by Intl.NumberFormat

Proposal: https://github.com/tc39/proposal-unified-intl-numberformat
Chrome: https://www.chromestatus.com/feature/5430420699086848
MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat

**Comment by GPHemsley** [comment]
Looks like this is now covered by MDN data:
https://caniuse.com/mdn-javascript_builtins_intl_numberformat

(via mdn/browser-compat-data#349)
