### ISSUE TITLE
Question: Missing css data like background-color?

### ISSUE THREAD

**Issue by B-Teague** [Fyrd/caniuse#5314]
I'm working on adding vendor prefixes to a library based on css property name and browser support, but it looks like some CSS properties are missing in the data.

For example: background-color has an entry on caniuse.com website, but has no occurrences in the data.

Am I missing something?

**Comment by Fyrd** [comment]
The caniuse repo does not contain features for every single CSS property, the entry you see on the website for background-color is from data provided by MDN. So that's probably the data you'll want instead for your library, available at https://github.com/mdn/browser-compat-data.
