### ISSUE TITLE
GA import: missing Samsung browser again

### ISSUE THREAD

**Issue by Ugoku** [Fyrd/caniuse#5316]
See also #4742, #4602, #4331, #3664, #3452, #3320

When I import Google Analytics, I'm missing ~5% of users because Samsung Internet 10.2 and 11.0 are not recognised.

Blog on version 10.2 : https://medium.com/samsung-internet-dev/samsung-internet-10-2-beta-d741ea15906d
Version 11 : https://www.sammobile.com/news/samsung-internet-v11-chromium-75-ui-changes/

**Comment by Fyrd** [comment]
Should be fixed now. I made a change to the importer where it'll just compare the major version of samsung browsers since they seem pretty consistent in having only the major version tied to the engine.

**Comment by Ugoku** [comment]
Thanks!
