### ISSUE TITLE
Inconsistent parsing of browser-compat-data

### ISSUE THREAD

**Issue by punkeel** [Fyrd/caniuse#5317]
Hello,

In the `browser-compat-data` dataset, some features are listed as `true`:
```
"support": {
            "chrome": {
              "version_added": true
            }
}
```

Which appears as _Full support_ on [Mozilla's developer website](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule, but unsupported on caniuse.com:
![Screenshot 2020-03-15 at 11 37 44 PM](https://user-images.githubusercontent.com/1859135/76713055-fcb64800-6715-11ea-88f4-c70b389a95f5.jpg)
![Screenshot 2020-03-15 at 11 38 34 PM](https://user-images.githubusercontent.com/1859135/76713086-1e173400-6716-11ea-8f06-e33f85fecdb4.jpg)

I've tried to track down when this exact feature was added in Chrome, and it turns out it was present in [Blink's initial commit](https://chromium.googlesource.com/chromium/blink/+/f6fe31f280bfc3df71c8d5ff9eb60ab239ca6fd9/WebCore/khtml/css/css_stylesheetimpl.h#102) - indeed compatible for _all Chrome releases_

If I understand correctly, caniuse handles the `true` values as *unknown*, because the data from browser-compat-data may be inconsistent with reality, listing `true` when it's only supported in the latest versions - but shouldn't we try to chase these exceptions and fix them?

**Comment by Fyrd** [comment]
I think you misunderstand what the "true" value means. It does not mean it's supported in every browser version, it means there's support, but it's [_unknown in which version support was added_ ](https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#version_added). This is why caniuse interprets it as supported in the current version, but unknown before that.

Ideally, yes, this would be fixed to start at version 1 in this case, but there are ~ 10,000 feature tables from MDN BCD and discovering and verifying such data takes time. I recommend submitting a PR for [the feature you mention](https://github.com/mdn/browser-compat-data/blob/master/api/CSSStyleSheet.json) if you'd like to see it corrected both on MDN and caniuse. Thanks!

**Comment by Fyrd** [comment]
Closing this issue as per my previous comment.
