### ISSUE TITLE
Importing from Google Analytics doesn't work

### ISSUE THREAD

**Issue by Finesse** [Fyrd/caniuse#5318]
Steps to reproduce:

1. Open a new clean incognito Google Chrome tab with no extensions
2. Go to https://caniuse.com/
3. Click «Settings», click «Import...» under «From Google Analytics:»
4. An import window appears and nothing happens further:

    ![image](https://user-images.githubusercontent.com/9006227/76812942-2a001480-6842-11ea-9e01-762baa06f894.png)

    Only an error appears in the browser console:

    ```
    Uncaught (in promise) Error: Cannot find module './retrieve_ga2'
        at webpackMissingModule (stats-import.module.js:62)
    ```

    When I click «Access Google Analytics», nothing happens too.

I tried to allow pop-ups for the website and to clear cache in the browser settings, it hasn't helped. I use no VPN and no ad blocker. Chrome version: 80.0.3987.132.

The same happens in Safari, but the console messages are different:

![image](https://user-images.githubusercontent.com/9006227/76813210-ef4aac00-6842-11ea-94a3-6475c8cf9383.png)

**Comment by Fyrd** [comment]
Ugh, looks like I broke something in my last update. Should be fixed now, thanks much for reporting!

**Comment by Finesse** [comment]
@Fyrd Thank you! It works now, I've checked in Chrome and Safari.

P.S. For googlers who experience broken import in Safari: try to change the website setting «Pop-up Windows» to «Block and Notify» and then, after you click «Import», click the pop-up icon in the browser address field.
