### ISSUE TITLE
SharedWorker API information for "Chrome on Android" _seems_ to be incorrect...

### ISSUE THREAD

**Issue by AubreyHewes** [Fyrd/caniuse#5322]
Hi, I figure this is the place to report this.. let me know if this should be reported elsewhere!

|Feature|Browser|Version|
|---|---|---|
|SharedWorker API|Chrome for Android|80.0.3987.132|

The [SharedWorker API](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker) information for "Chrome for Android" seems to be incorrect. The `window.SharedWorker` is `undefined` on "Chrome for Android" version `80.0.3987.132`

https://caniuse.com/#feat=mdn-api_sharedworker reports it as available from v80..

The referenced [MDN](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker) also says it should be supported but not which version.

(might possibly be a chrome bug as it works on the (desktop) Chrome `80.0.3987.149`)

> EDIT: https://github.com/mdn/browser-compat-data/issues/5850

**Comment by Fyrd** [comment]
The MDN BCD issue you opened is the right place (once it's fixed there the fix will eventually be on caniuse too) so closing this issue. Thanks!
