### ISSUE TITLE
How to handle Chromium skipping the M82 release?

### ISSUE THREAD

**Issue by JohnRiv** [Fyrd/caniuse#5325]
Per https://groups.google.com/a/chromium.org/forum/#!msg/chromium-dev/Vn7uzglqLz0/JItlSrZxBAAJ, Chromium (and therefore obviously Chrome & Edge) is going to be skipping M82 and going right from M81 to M83.

Should caniuse reflect the same? I'd assume it should, especially with tools like browserslist that use caniuse to determine what "last 2 versions" actually evaluates to.

Right now, Chrome Beta is at 81 and Chrome Canary is at 83.

**Comment by Fyrd** [comment]
Yeah, I think I'll keep an eye on this for now, but it shouldn't be a problem to skip a version on the caniuse side. Will remove 82 some time soon if this is the decision they stick with. Thanks for sharing!

**Comment by Fyrd** [comment]
Alright, Chrome 82 has now been removed.
