### ISSUE TITLE
CSS filter() function table isn't accurate.

### ISSUE THREAD

**Issue by beumsk** [Fyrd/caniuse#5328]
I was checking the support of the filter function from CSS and saw it is not accurate. 
It currently shows the feature available in Safari only while it should be available on most browsers. 
Cfr Mozilla documentation.
Thanks for updating !

**Comment by Fyrd** [comment]
You might be mistaking the CSS filter() function for the CSS filter property, which has support listed at https://caniuse.com/#feat=css-filters
Have updated the support table to make the difference a bit clearer.

**Comment by beumsk** [comment]
Indeed, thanks!
