### ISSUE TITLE
MNG support

### ISSUE THREAD

**Issue by TomasHubelbauer** [Fyrd/caniuse#5330]
CanIUse has a support page for APNG: https://caniuse.com/#feat=apng

Its support is surprisingly good compared to a decade ago.

I wonder what the support is like for MNG. My guess is: none. Still, would be cool to have a page for it.

**Comment by Schweinepriester** [comment]
Spec: <http://www.libpng.org/pub/mng/spec/>

<https://en.wikipedia.org/wiki/Multiple-image_Network_Graphics>:

> [Mozilla](https://en.wikipedia.org/wiki/Mozilla) browsers and [Netscape](https://en.wikipedia.org/wiki/Netscape_(web_browser) "Netscape (web browser)") 6.0, 6.01 and 7.0 included native support for MNG until the code was removed in 2003 due to code size and little actual usage,^[[3]](https://en.wikipedia.org/wiki/Multiple-image_Network_Graphics#cite_note-3)^ causing complaints on the Mozilla development site.^[[4]](https://en.wikipedia.org/wiki/Multiple-image_Network_Graphics#cite_note-4)^ Mozilla later added support for [APNG](https://en.wikipedia.org/wiki/APNG "APNG") as a simpler alternative.^[[5]](https://en.wikipedia.org/wiki/Multiple-image_Network_Graphics#cite_note-5)^ Similarly, early versions of the [Konqueror](https://en.wikipedia.org/wiki/Konqueror "Konqueror") browser included MNG support but it was later dropped. MNG support was never included in [Google Chrome](https://en.wikipedia.org/wiki/Google_Chrome "Google Chrome"), [Internet Explorer](https://en.wikipedia.org/wiki/Internet_Explorer "Internet Explorer"), [Opera](https://en.wikipedia.org/wiki/Opera_(web_browser) "Opera (web browser)"), or [Safari](https://en.wikipedia.org/wiki/Safari_(web_browser) "Safari (web browser)").

"Browsers with MNG Support": <http://www.libpng.org/pub/mng/mngapbr.html>

Given that MNG seems to have gained little support and appears to be basically dead, I'm leaning towards -1 to track it, but recognizing its existence as a search result could be considerate…

**Comment by TomasHubelbauer** [comment]
Can you explain the difference between tracking a feature and recognizing it as a search result? I think making it so that when you type MNG into the search bar and a table for MNG which is fully read and basically says "don't use it" appears would be sufficient. Is that what you have in mind?

**Comment by Schweinepriester** [comment]
The difference, for example:

TLS 1.1 at <https://caniuse.com/#feat=tls1-1> is tracked as a feature (as a file in this repo at <https://github.com/Fyrd/caniuse/blob/master/features-json/tls1-1.json>) versus TLS 1.0 which only has a search result at <https://caniuse.com/#search=TLS%201.0>.

So yeah, I have the latter in mind - but thats just my opinion 0:-)

**Comment by TomasHubelbauer** [comment]
Yeah, this looks good! The latter is definitely sufficient.

**Comment by RDKRACZ** [comment]
+1 for recognizing it. I was confused when the website said "0 results found".

**Comment by Fyrd** [comment]
Search result now available at https://caniuse.com/sr_mng
