### ISSUE TITLE
Add font keywords ui-serif, ui-sans-serif, ui-monospace and ui-rounded

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#5342]
<https://webkit.org/blog/10247/new-webkit-features-in-safari-13-1/>

> New font keywords are available for using platform-specific fonts including `ui-serif`, `ui-sans-serif`, `ui-monospace` and `ui-rounded`.

Spec: <https://drafts.csswg.org/css-fonts-4/#ui-serif-def> (CSS Fonts Module Level 4)

Firefox:
- <https://bugzilla.mozilla.org/show_bug.cgi?id=1598879>
- <https://bugzilla.mozilla.org/show_bug.cgi?id=1598880>
- <https://bugzilla.mozilla.org/show_bug.cgi?id=1598881>
- <https://bugzilla.mozilla.org/show_bug.cgi?id=1598883>

**Comment by Booligoosh** [comment]
+1

**Comment by Booligoosh** [comment]
Would it be best to have these as four separate features or one feature for all of them? If it was one feature for all of them, how would it work with Firefox IDs etc?

**Comment by Schweinepriester** [comment]
Now available at https://caniuse.com/#feat=extended-system-fonts.

Thanks @Booligoosh! :)

**Comment by Booligoosh** [comment]
Awesome!!

One thing I thought I'd double check — I set the status to WD, since the system-ui page links to the same document and its status is WD:
https://github.com/Fyrd/caniuse/blob/692d2141603fe98ccb77b2f5ef6795bfd84826c2/features-json/font-family-system-ui.json#L4

However, the actual document says Editor's Draft as opposed to Working Draft. I searched this repo for "ed" and couldn't find anything so I assume you don't differentiate between the two?

**Comment by Schweinepriester** [comment]
> (*EDIT:* Never mind --- it appears that they are in the [Working Draft](https://www.w3.org/TR/2019/WD-css-fonts-4-20191113/#valdef-font-family-ui-serif) as well. Should we be linking to that instead or is it better to link to the regularly updated Editor's Draft?)

was about to comment that 0:-)

Imho linking to the Editor's Draft is better, at least in this case, as for example `ui-sans-serif` is missing the example in the WD <https://www.w3.org/TR/css-fonts-4/#ui-sans-serif-def> but has it in the ED <https://drafts.csswg.org/css-fonts-4/#ui-sans-serif-def>.

@Fyrd, what do you think?

**Comment by Fyrd** [comment]
Yeah, generally I'd recommend to use the status of the most stable version but like to the latest version (usually editor's draft). If there's only an editor's draft it should be treated as "unofficial".
