### ISSUE TITLE
Add lab() and lch() from CSS Color Module Level 4

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#5348]
- Spec: <https://drafts.csswg.org/css-color-4/#specifying-lab-lch>
- @Ugoku [listed the browser bugs](https://github.com/Fyrd/caniuse/issues/4732#issuecomment-557457768):
  - Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1026287
  - Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1352757
  - Safari: https://bugs.webkit.org/show_bug.cgi?id=205675
- http://lea.verou.me/2020/04/lch-colors-in-css-what-why-and-how/

---

`lab()` and `lch()` have been mentioned before:

- https://github.com/Fyrd/caniuse/issues/2249#issuecomment-242984428
- https://github.com/Fyrd/caniuse/issues/4732#issuecomment-469640766

but since both issue authors requested a specific thing I've taken the liberty to create this one.

Alternatively #4732 could be elevated to cover `lab()` and `lch()` or even CSS Color Module Level 4 as a whole and this one closed as duplicate. Or something like that :)

**Comment by Schweinepriester** [comment]
More LCH greatness: [Dark mode in 5 minutes, with inverted lightness variables](https://lea.verou.me/2021/03/inverted-lightness-variables/)

As mentioned there, [shipped with Safari TP 120](https://webkit.org/blog/11548/release-notes-for-safari-technology-preview-120/#post-11548:~:text=Added%20support%20for%20lab()%2C%20lch()%2C%20and%20color(lab%20...)%20colors).

**Comment by Schweinepriester** [comment]
Should be coming via MDN once that PR is merged:
- lab: https://github.com/mdn/browser-compat-data/pull/10898/files#diff-2125922a521f439f749d97ac7aa3ceb461ff83f1494daa3dc8a687a98ea8705bR563
- lch: https://github.com/mdn/browser-compat-data/pull/10898/files#diff-2125922a521f439f749d97ac7aa3ceb461ff83f1494daa3dc8a687a98ea8705bR613

**Comment by Fyrd** [comment]
Indeed now available at https://caniuse.com/mdn-css_types_color_lab and https://caniuse.com/mdn-css_types_color_lch

@Schweinepriester That good enough for you on want to leave this open for a dedicated caniuse feature? (I'm good either way)

**Comment by Schweinepriester** [comment]
@Fyrd If I've got the choice, I'd leave it open - at least for now 0:-)

**Comment by Fyrd** [comment]
Now available as caniuse feature at https://caniuse.com/css-lch-lab
