### ISSUE TITLE
Data contains references to Chrome 82, which was never released

### ISSUE THREAD

**Issue by jpmedley** [Fyrd/caniuse#5356]
Information here: https://chromereleases.googleblog.com/2020/03/chrome-and-chrome-os-release-updates.html

**Comment by Schweinepriester** [comment]
Huh, I thought #5325 removed Chrome 82 :o 

A quick look via https://github.com/Fyrd/caniuse/search?q=82&unscoped_q=82 shows 82 seems to be still in the region-usage-json files, but other than that…

Can you elaborate on the references? :)

**Comment by jpmedley** [comment]
The way grep displays JSON makes it a hard to tell in some cases. For starters, 82 seems to be in all the files in `regions-usage-json/`.

**Comment by meduzen** [comment]
> 82 seems to be in all the files in `regions-usage-json/`.

It's normal I think: the monthly regions data update is late, so it’s likely be removed in the (coming? 🤞) update.

**Comment by Fyrd** [comment]
Yeah, was a bit behind on the usage data this month, should be up to date now. Don't think there's any more references now.

**Comment by meduzen** [comment]
I can confirm there ain’t.

![image](https://user-images.githubusercontent.com/9340937/79424202-17533980-7fc0-11ea-820f-d2423514eadb.png)

**Comment by Fyrd** [comment]
Seems safe to close now.
