### ISSUE TITLE
font-family: system-ui has two entries & different data

### ISSUE THREAD

**Issue by alinacsava** [Fyrd/caniuse#5358]
`system-ui` as `font-family` value has 2 entries showing different data. 

https://caniuse.com/#search=system-ui

The first entry ([system-ui value for font-family](https://caniuse.com/#feat=font-family-system-ui)) is correct.

**Comment by Sora2455** [comment]
One of those is the actual caniuse data, and the second one is the Mozilla data.

**Comment by Fyrd** [comment]
Yeah, the MDN one isn't supposed to appear since it has a caniuse equivalent. Should be removed soon.

**Comment by Fyrd** [comment]
Fixed now.
