### ISSUE TITLE
Incorrect data for CSS Shorthand Logical Properties

### ISSUE THREAD

**Issue by jonathantneal** [Fyrd/caniuse#5364]
The data for CSS Logical Properties was added incorrectly in https://github.com/Fyrd/caniuse/commit/78c2cefdecf520661fb3947768448c6f50ce33fd#diff-436b86c882efa2c7a1d765371f14226c on Oct 23, 2018.

At the time of this writing — April 17, 2020 — neither **Chrome** or **Safari** support `margin-block`, `padding-block`, `margin-inline`, `padding-inline`, or any `inset` property. **Chrome** supports these properties behind an experimental flag (`chrome://flags/#enable-experimental-web-platform-features`). **Firefox** supports these properties out of the box. 

- [CSS Logical Property Tests](https://codepen.io/embed/prefill?editable=true&default-tab=js,result&data=%7B%22js%22%3A%22document.write(%5Cn%60%3Cp%3E%3Ccode%3ECSS.supports('margin-block%3A0')%3A%20%24%7BCSS.supports('margin-block%3A0')%7D%3C%2Fcode%3E%60%20%2B%5Cn%60%3Cp%3E%3Ccode%3ECSS.supports('margin-inline%3A0')%3A%20%24%7BCSS.supports('margin-inline%3A0')%7D%3C%2Fcode%3E%60%20%2B%5Cn%60%3Cp%3E%3Ccode%3ECSS.supports('inset%3A0')%3A%20%24%7BCSS.supports('inset%3A0')%7D%3C%2Fcode%3E%60%20%2B%5Cn%60%3Cp%3E%3Ccode%3ECSS.supports('inset-block%3A0')%3A%20%24%7BCSS.supports('inset-block%3A0')%7D%3C%2Fcode%3E%60%20%2B%5Cn%60%3Cp%3E%3Ccode%3ECSS.supports('inset-inline%3A0')%3A%20%24%7BCSS.supports('inset-inline%3A0')%7D%3C%2Fcode%3E%60%20%2B%5Cn%60%3Cp%3E%3Ccode%3ECSS.supports('inset-block-start%3A0')%3A%20%24%7BCSS.supports('inset-block-start%3A0')%7D%3C%2Fcode%3E%60%20%2B%5Cn%60%3Cp%3E%3Ccode%3ECSS.supports('inset-block-end%3A0')%3A%20%24%7BCSS.supports('inset-block-end%3A0')%7D%3C%2Fcode%3E%60%20%2B%5Cn%60%3Cp%3E%3Ccode%3ECSS.supports('inset-inline-start%3A0')%3A%20%24%7BCSS.supports('inset-inline-start%3A0')%7D%3C%2Fcode%3E%60%20%2B%5Cn%60%3Cp%3E%3Ccode%3ECSS.supports('inset-inline-end%3A0')%3A%20%24%7BCSS.supports('inset-inline-end%3A0')%7D%3C%2Fcode%3E%60)%3B%22%7D)

_Note: These false positives also exist in [MDN Browser Compatibility Data](https://github.com/mdn/browser-compat-data/issues/5649)._

**Comment by Fyrd** [comment]
Thanks! Looks like the data was originally added in 2015, I suspect those properties weren't part of the spec back then. Anyway, have updated the data accordingly.
