### ISSUE TITLE
history.back()

### ISSUE THREAD

**Issue by codysmith287** [Fyrd/caniuse#5369]
Browser compatiability for `history.back()`.

https://developer.mozilla.org/en-US/docs/Web/API/History/back

**Comment by Schweinepriester** [comment]
Already there from MDN: <https://caniuse.com/#feat=mdn-api_history_back>

But finding that entry when searching for `history.back` would be an improvement…

**Comment by Fyrd** [comment]
Can now be found via https://caniuse.com/?search=history.back()
