### ISSUE TITLE
Add Chromium 81 browsers

### ISSUE THREAD

**Issue by atjn** [Fyrd/caniuse#5383]
Chrome for Android 81 is released:
https://chromereleases.googleblog.com/2020/04/chrome-for-android-update.html

Testing on my own phone seems to indicate that the Android Browser 81 is released as well.

Edge 81 is released:
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel

Opera 68 is released:
https://blogs.opera.com/desktop/2020/04/opera-68-is-here-with-built-in-instagram-in-the-sidebar/

When we start tracking these, i will finally be able to provide some reliable data on #5256 😅

**Comment by Fyrd** [comment]
Done!

**Comment by jpmedley** [comment]
Android WebView always releases at the same time as Chrome Android and Chrome desktop.
