### ISSUE TITLE
Add flow-into

### ISSUE THREAD

**Issue by minorandres** [Fyrd/caniuse#5385]
Diverts the selected element’s content into a named flow, used to thread content through different layout regions specified by flow-from.

Initial value
none
Applies to
Block elements, excluding pseudo-elements such as ::before or ::after.
Inherited
No
Media
visual
Computed value
as specified
Animatable
No
CSS Object Model Property
flowInto

**Comment by Fyrd** [comment]
Part of CSS Regions, available at https://caniuse.com/#feat=css-regions
Have added `flow-from` & `flow-into` as search keywords.
