### ISSUE TITLE
caniuse sharedworkers may be outdated

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [Fyrd/caniuse#5387]
https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker
shows more support then
https://caniuse.com/#feat=sharedworkers

**Comment by atjn** [comment]
Nice catch! Looks like Caniuse is correct though.

**Comment by Fyrd** [comment]
Thanks to @atjn 's research it looks like this issue can be closed.
