### ISSUE TITLE
DOMRect toJSON

### ISSUE THREAD

**Issue by TomasHubelbauer** [Fyrd/caniuse#5403]
It seems like the `toJSON` function is pretty lackluster. There is no common interface that defines it, it is just sort of there for many special objects which are not deconstructable/whose properties are not enumerable.

CanIUse already have definition for 13 instances of this method on various types.

One is lacking: `DOMRect`. I found out about it thanks to this: https://stackoverflow.com/a/48632087/2715716

So this is on FYI on missing information about `toJSON` support on DOMRect. I also wonder if there is a way to enumerate all objects which should have DOMRect so that all the missing toJSON support pages could be added.

**Comment by Fyrd** [comment]
All the `toJSON` methods on caniuse come from the MDN BCD data, so it seem most appropriate for DOMRect.toJSON to come from there too. You can file at issue there from here:
https://github.com/mdn/browser-compat-data/issues
