### ISSUE TITLE
BUG: Trusted types on news link broken

### ISSUE THREAD

**Issue by tomByrer** [Fyrd/caniuse#5414]
https://caniuse.com/#info_news

> Trusted Types for DOM manipulation: An API that forces the developer to be very explicit about their use of powerful DOM-injection APIs. Can greatly improve security against XSS attacks.

but this doesn't work
https://caniuse.com/#feat=trusted-types

Thanks for your great service!! :)

**Comment by Fyrd** [comment]
Thanks, fixed!
