### ISSUE TITLE
HTMLVideoElement.requestVideoFrameCallback()

### ISSUE THREAD

**Issue by kiding** [Fyrd/caniuse#5418]
It's `requestAnimationFrame` but for `<video>`.

* Specification: [WICG/video-rvfc](https://github.com/WICG/video-rvfc)
* Chrome: [Flagged since 84](https://www.chromestatus.com/feature/6335927192387584)
* Firefox: https://github.com/mozilla/standards-positions/issues/250

**Comment by Schweinepriester** [comment]
Available via MDN now: https://caniuse.com/?search=requestVideoFrameCallback
→ https://caniuse.com/mdn-api_htmlvideoelement_requestvideoframecallback

**Comment by Fyrd** [comment]
Closing as per above
