### ISSUE TITLE
Drop-down lists dont display properly in dark mode

### ISSUE THREAD

**Issue by atjn** [Fyrd/caniuse#5429]
When in dark mode on the beta site, drop-down lists dont display text correctly, making it pretty hard to use them.

![image](https://user-images.githubusercontent.com/20535393/81900252-bae23a80-95bc-11ea-83f7-4093968753ea.png)

**Comment by Fyrd** [comment]
Ah, looks like an issue specific to Chrome on Windows, thanks for reporting! Should be fixed now.

**Comment by atjn** [comment]
Oh, i didn't think to mention browser and OS. Thanks for doing a little detective work 🕵️‍♂️
