### ISSUE TITLE
Calc() Fix notes

### ISSUE THREAD

**Issue by tjameswhite** [Fyrd/caniuse#5442]
IE 11 has note `3` referring to Known Issues. The 5th bullet in Known Issues specifically mentions Edge not supporting `calc()` inside `flex`

Suggest adding `3` note to Edge 12 - 18.

**Comment by Fyrd** [comment]
The note is there to explain why IE's support is "partial". In general having some bugs is not enough to change support to partial but in IE's case it's pretty excessive. I don't think it's as serious for older Edge so I don't think this is necessary.
