### ISSUE TITLE
Rework Web App Manifest data

### ISSUE THREAD

**Issue by atjn** [Fyrd/caniuse#5448]
The support data for [WAM](https://caniuse.com/#feat=web-app-manifest) (the Web App Manifest) seems to mostly be tracking support for [A2HS](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen) (Add To Home Screen functionality).
I can see why this has happened, since WAM is pretty much only used for A2HS, but they are technically speaking two different things, and IMO it is really confusing for developers that the feature is not called A2HS when that is what it is tracking.

Another thing to note is that searching for things like `A2HS`, `add to home screen` and `progressive web app` does not return any data.

I suggest that we do one of two things about it:
1. Change the title, description and keywords of the existing WAM data to A2HS (i'm not sure how you would change the URL link without breaking existing links to the feature?)
2. Add a new feature for A2HS and migrate some of the notes from WAM to A2HS

I don't mind doing the legwork for these changes, but i felt we needed to discuss the best solution before i start making any code changes 😊

Related: #5099 https://github.com/Fyrd/caniuse/issues/1532#issuecomment-168075482

**Comment by Fyrd** [comment]
Hmm, good point. In general for caniuse features if the parts effectively refer to the same thing and support doesn't differ significantly it can just stay as one, so I'm slightly in favor of the first option. Leaving the id as "web-app-manifest" seems okay to me since it's not too misleading.

**Comment by atjn** [comment]
Allright, i will start working on it. One thing to note is that the [App Manifest Spec](https://www.w3.org/TR/appmanifest/) links to the caniuse table.
