### ISSUE TITLE
Safari support for OES_texture_half_float

### ISSUE THREAD

**Issue by pmer** [Fyrd/caniuse#5467]
I couldn't find where in the repo support for OES_texture_half_float is located, so I'll just say it here.

Desktop Safari 13 and lower do not support it, while TP does.

Can be seen at https://caniuse.com/#feat=mdn-api_oes_texture_half_float

**Comment by Schweinepriester** [comment]
Support data for this feature is provided by <https://github.com/mdn/browser-compat-data>, so the  data is at <https://github.com/mdn/browser-compat-data/blob/master/api/OES_texture_half_float.json> :)

**Comment by pmer** [comment]
Thank you! :)
