### ISSUE TITLE
Array.filter is not listed

### ISSUE THREAD

**Issue by crashuniverse** [Fyrd/caniuse#5478]
`Array.filter` or `Array.prototype.filter` is not found on caniuse. https://caniuse.com/#search=Array.filter Someday, we can list it.

**Comment by Schweinepriester** [comment]
<https://caniuse.com/#feat=mdn-javascript_builtins_array_filter>

**Comment by crashuniverse** [comment]
Thanks for sharing. I got here because Array.filter did not give me any results. Array filter with a whitespace does. I'll close this issue.

**Comment by Fyrd** [comment]
FWIW I've now added keywords to JS MDN items so entries like https://caniuse.com/#search=array.filter and https://caniuse.com/#search=array.prototype.filter now return the expected result.

**Comment by crashuniverse** [comment]
Amazing stuff, thank you. I am happy that we got something out of this conversation. For making caniuse, thank you from India 🇮🇳.
