### ISSUE TITLE
CSS :where() works in Chrome with "Experimental Web Platform Features" enabled.

### ISSUE THREAD

**Issue by VeeDoubleYuh** [Fyrd/caniuse#5481]
I just enabled this flag and :where() appears to be working. Chrome version 83.0.4103.106
![image](https://user-images.githubusercontent.com/11726968/85210963-7a7f8600-b2f9-11ea-90a5-aba9bb4282fc.png)

According to [this table](https://caniuse.com/#feat=mdn-css_selectors_where), Firefox is the only one with the option at all at the moment.
Perhaps add the same note as the one on the [:is()](https://caniuse.com/#feat=mdn-css_selectors_is) table: "Can be enabled by setting Experimental Web Platform Features to enabled"

Thanks!

**Comment by Schweinepriester** [comment]
Created a PR: https://github.com/mdn/browser-compat-data/pull/6318

**Comment by Schweinepriester** [comment]
PR has been merged and the changes made their way to caniuse: https://caniuse.com/#feat=mdn-css_selectors_where

I think this issue can be closed? :)

**Comment by Fyrd** [comment]
Great, thanks @Schweinepriester !
