### ISSUE TITLE
Three digit css shorthand for hex-values for color coding.

### ISSUE THREAD

**Issue by chr-bakk** [Fyrd/caniuse#5482]
Three digit css shorthand hex-values for color coding.

Some browsers have this worng, and renders my colors wrong.

`#963;` becomes _#936000_

**Comment by Fyrd** [comment]
Just did some checks across modern browsers, then tried going all the way back to IE6 and it was able to render the color `#963` correctly. Can you specify in which browser/circumstance you saw it be rendered wrong? Could it be another tool converting it incorrectly before applying it?

**Comment by Fyrd** [comment]
Closing for now, will re-open if a browser is proven to fail support here.

**Comment by chr-bakk** [comment]
Samsung internet android v 11.22.3

**Comment by Fyrd** [comment]
https://codepen.io/Fyrd/pen/VweMdXJ looks the same in Samsung internet 11.2 as in other browsers
