### ISSUE TITLE
Notes for IE9-11 on document.readyState are misleading

### ISSUE THREAD

**Issue by 36degrees** [Fyrd/caniuse#5489]
The notes for IE9-11 on document.readyState are misleading. The notes are:

> 1. Only supports 'complete'.
> 2. Internet Explorer 9 and 10 have bugs where the 'interactive' state can be fired too early before the document has finished parsing.

Note 1 is linked to IE8, IE9-10 and IE11 but as far as I can tell only applies to IE8.

Notes 2 is linked to IE9-10 and IE11 but as far as I can tell only applies to IE9-10. This one is less problematic as at least the note clarifies which browsers are affected.

This means that the popover for IE11 suggests that it doesn't support 'complete', and shows the unrelated IE9-10 issue:

<img width="516" alt="Screenshot 2020-06-23 at 17 01 15" src="https://user-images.githubusercontent.com/121939/85427067-2da6e400-b573-11ea-95a3-23871d94ed58.png">

The browser compatibility table on MDN makes it clearer:

<img width="1042" alt="Screenshot 2020-06-23 at 17 00 44" src="https://user-images.githubusercontent.com/121939/85427007-1e279b00-b573-11ea-9774-5d3ffd6f58c5.png">

I'm not sure if this is an issue with the source data in https://github.com/mdn/browser-compat-data or with the way caniuse interprets the notes, so apologies if this is in the wrong place – happy to raise the issue over there or raise a PR if someone can give me a pointer as to how to make the note only apply to IE8.

**Comment by Fyrd** [comment]
Thanks for finding this! I've looked into it a bit and I believe in this case the issue needs to be fixed from the source data side...the `Only supports 'complete'.` note is accompanied with `"version_added": "8"` which generally means it applies to that version and above. I'll write up a BCD PR with suggested fixes and see if folks there agree.

**Comment by 36degrees** [comment]
Ah that's ace, thank you! Can't believe that's your first PR on browser-compat-data 😄

I did wonder if that was the way to do it – will keep an eye on that PR and see how it resolves, and in the future if I spot similar things I might be able to help fix it myself!

**Comment by Fyrd** [comment]
The PR was merged, and the table has now been updated with correct info, so closing this issue.
