### ISSUE TITLE
Update test for registerProtocolHandler

### ISSUE THREAD

**Issue by atjn** [Fyrd/caniuse#5495]
I suggest rewriting the code that registers test handlers on [the test page](https://tests.caniuse.com/registerprotocolhandler) to:

```
navigator.registerProtocolHandler("caniusetest",
                                  "https://tests.caniuse.com/rph.html?val=%s",
                                  "Caniuse handler test");
```
and
```
navigator.registerProtocolHandler("web+caniusetest",
                                  "https://tests.caniuse.com/rph.html?val=%s",
                                  "Caniuse handler test");
```
The existing code uses insecure `http` in the url, and uses a dash in the protocol name. Those traits will fail the registration in modern browsers, even though the browser supports custom protocols.

**Comment by Fyrd** [comment]
Thanks, has now been updated!
