### ISSUE TITLE
Feature: Axios.js

### ISSUE THREAD

**Issue by OS-the-Person** [Fyrd/caniuse#5508]
Can I use Axios.js in browsers

**Comment by Schweinepriester** [comment]
<https://github.com/axios/axios#browser-support>

Though:

> [Caniuse only tracks browser features, not library/frameworks. Will leave this issue open to add a search result.](https://github.com/Fyrd/caniuse/issues/5465#issuecomment-640378688)

**Comment by Fyrd** [comment]
Added as search result at https://caniuse.com/#search=axios
