### ISSUE TITLE
Add navigator.share

### ISSUE THREAD

**Issue by aej11a** [Fyrd/caniuse#5509]
API used to show a native share-sheet

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

**Comment by Schweinepriester** [comment]
<https://caniuse.com/#feat=mdn-api_navigator_share>

**Comment by juner** [comment]
https://caniuse.com/web-share

**Comment by Fyrd** [comment]
Already available, as mentioned. https://caniuse.com/?search=navigator.share leads to https://caniuse.com/web-share
