### ISSUE TITLE
Two (conflicting) entries for <wbr/>

### ISSUE THREAD

**Issue by maffe** [Fyrd/caniuse#5510]
https://caniuse.com/#search=wbr shows two tables for the `wbr` element, with conflicting information (for example, IE 7, Edge 12–18 and Opera 10–11.5 have different support status).

**Comment by Fyrd** [comment]
Fixed now, looks like the code removing duplicate MDN tables wasn't working right. I also confirmed the caniuse data seems to be correct for IE & Edge, didn't check Opera since those are really old versions.
