### ISSUE TITLE
Add Sanitizer API

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#5517]
- <https://wicg.github.io/purification/>
- <https://chromestatus.com/feature/5786893650231296>
- <https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/MJxVZs1H5SY/6q0QxEFtBAAJ>
- "purification"

**Comment by jpmedley** [comment]
@Fyrd The plan for this is an origin trial, which is NOT considered part of the web platform. For the time being, we won't be adding this to MDN's compatibility data either.

**Comment by Malvoz** [comment]
> - https://wicg.github.io/purification/

New home: https://wicg.github.io/sanitizer-api/

**Comment by mozfreddyb** [comment]
It seems this can be closed, as it is already on caniuse? https://caniuse.com/mdn-api_sanitizer
Funnily, I couldn't find the pull request that added it. Looking at the link, it's probably from MDN data?

**Comment by Schweinepriester** [comment]
Probably, and indeed that entry is from MDN :)

(Tab "Feedback" => "[support data for this feature](https://github.com/mdn/browser-compat-data/blob/main/api/Sanitizer.json )." => from there it's only one step to the git history and such :))

**Comment by Schweinepriester** [comment]
Read https://css-tricks.com/html-sanitizer-api/ and can confirm again it's available via MDN now:  
<https://caniuse.com/?search=Sanitizer%20API>

**Comment by Schweinepriester** [comment]
MVP shipping with Chrome 105 soon: https://chromestatus.com/feature/5786893650231296

**Comment by Fyrd** [comment]
Closing as per above comments
