### ISSUE TITLE
Firefox version is behind

### ISSUE THREAD

**Issue by theSdev** [Fyrd/caniuse#5520]
Firefox is now at version 78, but caniuse shows it at 76.
Firefox changed their release schedule to release a new version every 4 weeks instead of 6, maybe that caused the issue?

**Comment by atjn** [comment]
Hmmm, caniuse does display 78 as the current version, and was at least displaying version 77 when you were looking at it.
I think you might be seeing stale information that has been cached in your browser, which has been a problem for other users as well.
For me, reloading the tab a few times, or clearing the application from devtools fixes the problem, at least temporarily.

Related: #5468  #5231 #4977

**Comment by Fyrd** [comment]
Yeah, pretty sure this is just a cache issue, keeping #5468 open for that. Should be taken care of on the updated version of the site which will be released...some day.
