### ISSUE TITLE
Chromium-based Edge usage is not counted

### ISSUE THREAD

**Issue by ylemkimon** [Fyrd/caniuse#5527]
![image](https://user-images.githubusercontent.com/888148/87258168-8f0c0400-c4dc-11ea-94ac-03053feb825a.png)
![image](https://user-images.githubusercontent.com/888148/87258215-cda1be80-c4dc-11ea-98a3-3fc9072e06b6.png)

The usage of Edge>=80 is shown as 0% and is included in "Browsers not included on site".

**Comment by Fyrd** [comment]
Thanks! Looks like StatCounter changed the way they format Edge versions recently which caused these versions to not be counted. The issue has now been corrected.
