### ISSUE TITLE
UC Browser info correct? E.g. for WebAssemly

### ISSUE THREAD

**Issue by PallHaraldsson** [Fyrd/caniuse#5528]
https://caniuse.com/#feat=wasm

I do see it's seems to be based on Chrome 57, and Chrome started supporting WebAssembly at that version (for desktops, I see news article also for Android, also stating WebAssembly, but not sure to trust those):

UC user agent:
Mozilla/5.0 (Linux; U; Android 9; en-US; SM-M105F Build/PPR1.180610.011) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 UCBrowser/12.12.8.1206 Mobile Safari/537.36

https://blog.chromium.org/2017/02/chrome-57-beta-css-grid-layout-improved.html
"Unless otherwise noted, changes described below apply to the newest Chrome Beta channel release for Android [..]
The WebAssembly API has been enabled by default, allowing developers to run near-native code in the browser without a plugin."

Even if applies to Chrome 57 (non-beta) may not apply to UC browser, there's possibly a way to disable by that vendor. But someone should be able to check if some WA code runs on that browser.

**Comment by atjn** [comment]
I just checked, and WebAssembly is indeed supported in Chrome for Android, but not in the UC browser. The support data on Caniuse is correct :)

The UC browser is based on chromium, but is pretty heavily modified, so it's not uncommon to find differences between it and other chromium-based browsers like Chrome. If you have other features where you think the support data might be incorrect, i am happy to give it a quick checkup to assure the data is correct 👍
