### ISSUE TITLE
Make the beta site work without cookies

### ISSUE THREAD

**Issue by valtlai** [Fyrd/caniuse#5536]
The current Can I Use site is working pretty well without cookies. It would be very nice if the [beta site](https://beta.caniuse.com/) wouldn’t require cookies either. Currently, without cookies, the all navigation items don’t load and the hover cards are not available, for example.

The Chrome dev tools console says:

> Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

So the `localStorage.setItem()` should be wrapped in a `try`–`catch` block, at least.

**Comment by Fyrd** [comment]
Ah, great reminder, will definitely take care of this. Thanks!

**Comment by Fyrd** [comment]
@valtlai Should be fixed now, can you try again?

**Comment by valtlai** [comment]
Yeah, it’s working now. Thank you!
