### ISSUE TITLE
Beta site a11y issue. Low contrast of link text in support tooltip.

### ISSUE THREAD

**Issue by craftedsystems** [Fyrd/caniuse#5538]
Anchor text needs higher contrast color.
Screenshot of **SVG Favicon** result page

![SVG_Favicon](https://user-images.githubusercontent.com/26137287/87770844-d289a980-c81f-11ea-8636-188323bd2e86.png)

Possible solution:
Set the a tag color to `currentColor` to match the Global link (as visible on the screenshot too).

**Comment by Fyrd** [comment]
Thanks, fixed!

Actually the underlined "Global" text isn't a link, the underline was marking the fact that "Global" is the primary usage source. I've changed that to be bold now to avoid confusion.
