### ISSUE TITLE
Link color not readable in the beta site 

### ISSUE THREAD

**Issue by awebdeveloper** [Fyrd/caniuse#5541]
Following link colour not readable 

<img width="823" alt="Screenshot 2020-07-18 at 5 56 30 PM" src="https://user-images.githubusercontent.com/1593429/87852497-064bf880-c920-11ea-855d-4f48b5be1d59.png">

But this is 
<img width="690" alt="Screenshot 2020-07-18 at 5 57 46 PM" src="https://user-images.githubusercontent.com/1593429/87852515-3398a680-c920-11ea-8fbc-5806f9b6ebe4.png">

Can we use the same color in both case.

**Comment by Fyrd** [comment]
Thanks, fixed!
