### ISSUE TITLE
caniuse search showing up all the time

### ISSUE THREAD

**Issue by SuperJumpBrosYT** [Fyrd/caniuse#5542]
how do I make caniuse search not appear and make me search here on google chrome when I say can in front of literally everything?
![Screenshot 2020-07-18 10 00 14](https://user-images.githubusercontent.com/54546501/87861289-df3afa00-c912-11ea-8b68-88d7dc30f763.png)

please help its hard to search stuff because caniuse just keeps showing up and yeah

**Comment by Fyrd** [comment]
Wow this is not something I've heard of before. My guess is you accidentally set up caniuse as a search engine at some point? What browser is this happening in?

**Comment by SuperJumpBrosYT** [comment]
its in google chrome and i have no idea what caniuse is so i made a github account just for this

**Comment by SuperJumpBrosYT** [comment]
ive never set it up as a search engine it just started showing up randomly

**Comment by Fyrd** [comment]
Very odd, I can't say it happens when I try it. Maybe try these instructions to remove caniuse as a search engine?
https://support.google.com/chrome/answer/95426

**Comment by ylemkimon** [comment]
Google Chrome automatically adds a search engine when it detects user input shown in the query. They can be deleted from chrome://settings/searchEngines.

**Comment by Fyrd** [comment]
@SuperJumpBrosYT Have you had any luck using the suggestions above?

**Comment by Fyrd** [comment]
Closing this issue as it's a Chrome issue rather than a caniuse one.
