### ISSUE TITLE
Update tests for Feature-, Permissions- and Document Policy

### ISSUE THREAD

**Issue by atjn** [Fyrd/caniuse#5544]
This issue follows #5543 

I'd like to propose some updates to [the Feature Policy test](https://tests.caniuse.com/feature-policy):

1. The test for `navigator.policy` should be updated to `document.featurePolicy`.
2. The `allow` attribute isn't unique to Feature Policy anymore, so i suggest adding a new interactive test that puts a "get geolocation" button inside an iframe with `allow="geolocation 'none'"` set. This query will only work with browsers that specifically support Feature Policy.

For Permissions Policy, the Feature Policy tests can be copied, with the following changes:
`Feature-Policy: geolocation 'none'` -> `Permissions-Policy: geolocation=()`
`allow="geolocation 'none'"` -> `allow="geolocation=()"`
`document.featurePolicy` -> `document.permissionsPolicy`

Document Policy really only needs a test for the `policy` attribute in an iframe.
Interactive tests would be nice, but aren't necessary.

**Comment by Fyrd** [comment]
Thanks! Think I have all changes made, let me know if I got anything wrong:

https://tests.caniuse.com/feature-policy
https://tests.caniuse.com/document-policy
https://tests.caniuse.com/permissions-policy

**Comment by atjn** [comment]
It looks awesome, thanks!

I forgot to mention that the Document Policy will need an HTTP header test, like the one for Permissions Policy, in order to test it properly. But since none of the policies have stabilized yet, you can't really make that test right now. I'll open an issue when it becomes relevant (guessing it'll stabilize with Chrome 86/87).
