### ISSUE TITLE
Please add ES3 support

### ISSUE THREAD

**Issue by DarthMikeSundays** [Fyrd/caniuse#5546]

**Comment by Fyrd** [comment]
ES5 is already widely supported across browsers, and most if not all ES3 features should already be covered via the MDN BCD data. Is there a particular reason you feel ES3 needs to be added as its own table?

**Comment by ProMikeCoder2020** [comment]
I just wasn't sure if ES3 was supported in all browsers

**Comment by Fyrd** [comment]
I'll leave this open for now, though I'm not sure how many people know which JS feature is specifically part of ES3 so not sure how valuable it is vs looking up the specific feature.

**Comment by Fyrd** [comment]
A search result was added for this at https://caniuse.com/sr_es3
