### ISSUE TITLE
Add CSS Units Level 4

### ISSUE THREAD

**Issue by jantimon** [Fyrd/caniuse#5549]
In 2017 and 2018 the following css units have been added to allow sizing based on various font metrics and are part of the official css spec now:

https://www.w3.org/TR/css-values-4/#relative-lengths

unit | relative to
-- | --
cap | cap height (the nominal height of capital letters) of the element’s font
ic | average character advance of a fullwidth glyph in the element’s font, as represented by the “水” (CJK water ideograph, U+6C34) glyph
lh | line height of the element
rlh | line height of the root element
vi | 1% of viewport’s size in the root element’s inline axis
vb | 1% of viewport’s size in the root element’s block axis

Could we please add them also to caniuse?

**Comment by Schweinepriester** [comment]
Duplicate of #4087 or rather [already available](https://github.com/Fyrd/caniuse/issues/4087#issuecomment-625629937): <https://caniuse.com/#search=css%20length>

**Comment by jantimon** [comment]
Thanks 👍
