### ISSUE TITLE
Please add News subscription

### ISSUE THREAD

**Issue by romankurnovskii** [Fyrd/caniuse#5550]

**Comment by atjn** [comment]
Hi there :)

I'm guessing this is a duplicate of one of these:
#869, #3774, #5249, #5406

If not, could you please elaborate?

**Comment by Fyrd** [comment]
There's also an existing RSS feed of the News section that can be subscribed to: https://caniuse.com/feed/

Closing this issue for now, will re-open if more info is provided.
