### ISSUE TITLE
Cannot open links in new tabs using ctrl / cmd + click

### ISSUE THREAD

**Issue by wesort** [Fyrd/caniuse#5556]
Typically links can be opened in a new tab or window by holding `ctrl` or `cmd` key and then clicking the link. Right-click > open in new tab functions as expected.

Tested on Chrome OS Beta v85

**Comment by Fyrd** [comment]
Good find! I've made sure this works on the [beta site](https://beta.caniuse.com) for now.

**Comment by Fyrd** [comment]
This is now available on the main site.
