### ISSUE TITLE
Add content-visibility?

### ISSUE THREAD

**Issue by oaustegard** [Fyrd/caniuse#5560]
New Chrome 85 feature: https://web.dev/content-visibility/ - direct dependence on https://caniuse.com/#search=css-contain so maybe a redirect instead?

**Comment by Schweinepriester** [comment]
Duplicate of #5559.

**Comment by devhelper** [comment]
add content-visibility please

**Comment by JofunLiang** [comment]
expect

**Comment by isaumya** [comment]
Yes please add this. Both the `content-visibility` and `contain-intrinsic-size`. I have just now tried it on my stage site and honestly, the result was mind-blowing. This reduced my rendering time by 63.5% on the heaviest page. This is truly a great tool for web perf.

**Comment by ramiy** [comment]
Chrome 85 added support for this CSS property.

See: https://developers.google.com/web/updates/2020/08/nic85#content-visibility

**Comment by scott8035** [comment]
+1

**Comment by BeliefRC** [comment]
+1

**Comment by PeterShershov** [comment]
🙏

**Comment by mintymatt** [comment]
🚀

**Comment by sungjoonlee** [comment]
please

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/css-content-visibility
