### ISSUE TITLE
Country/region widget in the "usage source" section is broken if adblockers are enabled.

### ISSUE THREAD

**Issue by MartijnCuppens** [Fyrd/caniuse#5564]
![image](https://user-images.githubusercontent.com/11559216/89733903-fd4ed280-da58-11ea-834b-8c8998aaad89.png)

Import button is gone when the widget is broken.

It seems adblockers block the `/resources/statcounter-regions.json` url (I guess because it contains the word `statcounter`). Renaming the file might resolve the issue.

**Comment by Fyrd** [comment]
Ah yes, this issue had come up before but never could figure out the cause. Sounds like a good theory, I've renamed the file on the beta site at beta.caniuse.com to `sc-regions.json` can you see if it works as expected there?

**Comment by MartijnCuppens** [comment]
Yup, that works:

![image](https://user-images.githubusercontent.com/11559216/89896738-3fede780-dbde-11ea-9cae-17a2f72705fa.png)

**Comment by Fyrd** [comment]
This update is now available on the main site.
