### ISSUE TITLE
error_log included in npm package

### ISSUE THREAD

**Issue by bragle** [Fyrd/caniuse#5570]
I recently discovered that there's a file in the "caniuse-db"-package named error_log which contains (you guessed it) an error log. It does not seem like there's anything in there that could compromise your system (I would not have created a public issue if that was the case), but exposing this kind of information probably isn't preferred, so I just wanted to let you know about it 😸

**Comment by Fyrd** [comment]
Yikes, that's not great. Should be removed in the latest version now, will take some precautions to prevent that from happening in the future. Thanks so much for reporting this!
