### ISSUE TITLE
Please add ::part()

### ISSUE THREAD

**Issue by ShaggyDude** [Fyrd/caniuse#5574]
Otherwise known as shadow parts.
Thanks,

**Comment by Fyrd** [comment]
Already available at https://caniuse.com/#feat=mdn-css_selectors_part
Would like to add keywords for it but don't yet have a way of adding those for data from MDN BCD.

**Comment by Fyrd** [comment]
Can now be found via https://caniuse.com/?search=shadow%20parts or https://caniuse.com/?search=::part()
