### ISSUE TITLE
Feature: Midas Editor

### ISSUE THREAD

**Issue by PlytonRexus** [Fyrd/caniuse#5575]
Specifications: [https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Midas](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Midas).

**Comment by Fyrd** [comment]
I believe this is already covered by https://caniuse.com/#feat=mdn-api_document_designmode Looks like "Midas" is just the code name for Gecko's implementation of this.

**Comment by PlytonRexus** [comment]
That's fair. Might, then, a small note in the `document.contentEditable` and `document.designMode` pages be appropriate?
