### ISSUE TITLE
What is the browser support for shaka player? 

### ISSUE THREAD

**Issue by TeamInsideSoftwares** [Fyrd/caniuse#5576]
Google shaka player used for streaming video should have some browser support. How can we find it?

**Comment by atjn** [comment]
Shaka Player is not a browser feature, so it is not on tracked on Caniuse, but they have made their own browser support table:
https://github.com/google/shaka-player#platform-and-browser-support-matrix

**Comment by Fyrd** [comment]
Closing as per @atjn's comment
