### ISSUE TITLE
Update Chrome stable to version 85

### ISSUE THREAD

**Issue by styfle** [Fyrd/caniuse#5581]
Chrome version 85 is the current stable but caniuse.com still shows Chrome 84: https://caniuse.com/#feat=avif

<img src="https://user-images.githubusercontent.com/229881/91239350-50897c00-e70d-11ea-88d4-d0ba32be2263.png" width=350/>

Version History: https://en.wikipedia.org/wiki/Google_Chrome_version_history

**Comment by Fyrd** [comment]
Done!
