### ISSUE TITLE
frame-ancestors CSP directive should be marked as incomplete or buggy for Firefox

### ISSUE THREAD

**Issue by ebickle** [Fyrd/caniuse#5583]
In the latest version of Firefox (80.0) there is an implementation flaw in the frame-ancestors directive that causes it to fail in certain scenarios - the most common being all use of Google reCAPTCHA. This should be documented in the table for frame-ancestors, since it's a significant issue with a component that nearly all websites use. 

The specific Mozilla bug is https://bugzilla.mozilla.org/show_bug.cgi?id=1404438

**Comment by atjn** [comment]
I agree, this should be documented on the [CSP Level 2 table](https://caniuse.com/#feat=contentsecuritypolicy2)
The [table for frame-ancestors](https://caniuse.com/#feat=mdn-http_headers_csp_content-security-policy_frame-ancestors) is provided by MDN, i suggest opening an issue [here](https://github.com/mdn/browser-compat-data/issues) to get that sorted.

Before i add this to the table, could you specify what you mean when you say "all use of reCAPTCHA is affected"?
Using the recaptcha on [this site](https://developers.google.com/speed/public-dns/cache) in Firefox 80 seems to work just fine.

**Comment by ebickle** [comment]
Despite all my attempts at making sure I was validating this correctly, I realized today it was a misconfiguration in my testing proxy. Wasn't able to reproduce the issue, so I'm going to close this :)
