### ISSUE TITLE
[Bug] Firefox for Android does _not_ support WebAuthn

### ISSUE THREAD

**Issue by sqrt-1764** [Fyrd/caniuse#5585]
https://caniuse.com/#search=webauthn states that WebAuthn is supported in Firefox for Android since version 68.
But apparently this is not true. There are open issues regarding this topic in Bugzilla that indicate that this feature is not working.

Also https://webauthn.io claims that Firefox for Android does not support Webauthn when browsing it whith this browser (Version 79.0.5).

**Comment by Fyrd** [comment]
Thanks, has been fixed.
