### ISSUE TITLE
iOS has only a partial support for Built-in PDF viewer

### ISSUE THREAD

**Issue by SuperPat45** [Fyrd/caniuse#5593]
The PDFObject polyfill say:

> (In iOS, Safari will only display an image preview of the first page of a PDF, and will not render other pages of the PDF.)
> Other iOS web browsers use Apple's native WebView to render pages, which leads to the same limitations as Safari. 

So, iOS has only a partial support for Built-in PDF viewer and should be marked as such.

**Comment by SuperPat45** [comment]
Or we just can add a note

**Comment by Fyrd** [comment]
Has been added as a note, thanks.
