### ISSUE TITLE
Hiding Opera Mini in browser set doesn't work

### ISSUE THREAD

**Issue by LMLB** [Fyrd/caniuse#5595]
All browsers can be hidden except Opera Mini:

![image](https://user-images.githubusercontent.com/6322603/92334071-d4872080-f08a-11ea-873e-ccac8faa653b.png)

**Comment by Fyrd** [comment]
Thanks for reporting! Should be fixed now.

**Comment by LMLB** [comment]
Confirmed fixed. Thanks!
