### ISSUE TITLE
Track support for navigator.getInstalledRelatedApps()

### ISSUE THREAD

**Issue by ChildishGiant** [Fyrd/caniuse#5596]
I'm not sure if this comes under https://caniuse.com/mdn-api_navigator or https://caniuse.com/web-app-manifest already

**Comment by Schweinepriester** [comment]
Available via MDN now:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator#browser_compatibility
→ https://caniuse.com/mdn-api_navigator_getinstalledrelatedapps
