### ISSUE TITLE
Data sourced from MDN browser-compat-data is outdated

### ISSUE THREAD

**Issue by stof** [Fyrd/caniuse#5599]
See https://caniuse.com/mdn-javascript_builtins_regexp_named_capture_groups for an example.

Here is how it looks like on caniuse: 
![image](https://user-images.githubusercontent.com/439401/92381172-a6492580-f10a-11ea-940e-eb95dad49447.png)

And here is the data [on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Browser_compatibility) (I removed many other lines of the table to allow seeing the headers and the relevant line close together in the screenshot): 
![image](https://user-images.githubusercontent.com/439401/92381393-10fa6100-f10b-11ea-98b6-41a9a6e67712.png)

Firefox supports the feature since version 78 and the browser-compat-data project reflects it.

**Comment by Fyrd** [comment]
Thanks! The data has now been updated.
