### ISSUE TITLE
Update Opera Mini entries

### ISSUE THREAD

**Issue by twifkak** [Fyrd/caniuse#5603]
When I run Opera Mini now, I see it reports a user-agent of `Chrome/85`, so I suspect some entries need to be updated to reflect the newest level of feature support. The one that I know is out-of-date is https://caniuse.com/sxg, but I wanted to file an issue in case there are others like it, and there is an automated way of updating support based on Chromium version. LMK how I can help; thanks!

**Comment by Fyrd** [comment]
As per the note on the site, the "Opera Mini" tracked on the site refers to the version used on feature phones. On smartphones it uses the default browser engine, which does not need to be tracked separately.

![Screen Shot 2020-09-12 at 10 10 01 PM](https://user-images.githubusercontent.com/432336/93010791-fed25580-f544-11ea-957e-1bf77ccb3f65.png)
