### ISSUE TITLE
WebHID inclusion

### ISSUE THREAD

**Issue by theLMGN** [Fyrd/caniuse#5606]
Requesting the addition of the Web Human Input Device API.

https://github.com/WICG/webhid
https://wicg.github.io/webhid/

https://chromestatus.com/features/5172464636133376

**Comment by theLMGN** [comment]
After closer inspection, it looks like this was added to the dataset by @Fyrd in bdef37519861ad615fb613b227ec89ac29337d41, but not shown on the site.

**Comment by atjn** [comment]
This was actually added in #5131. If Chrome is [beginning origin trials soon](https://bugs.chromium.org/p/chromium/issues/detail?id=890096#c56), it might be time to expose this table on caniuse. @Fyrd?

**Comment by Fyrd** [comment]
Yup, will get on this shortly.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/webhid
