### ISSUE TITLE
Newer Safari versions not recognized for iOS 13.6-7

### ISSUE THREAD

**Issue by andronocean** [Fyrd/caniuse#5607]
When I run a Google Analytics import, "Safari & Chrome for iOS 13.6" and "Safari & Chrome for iOS 13.7" show up in the _Browsers Not Included_ column. Right now that accounts for just under 30% of my 30-day traffic. Any way we can get these recognized?

**Comment by Fyrd** [comment]
Looks like I missed those versions being added. Should now be fixed.

**Comment by andronocean** [comment]
Yep! They import properly now. Thanks 😄
