### ISSUE TITLE
Global/national usage stats don't update correctly when filtering initial search results

### ISSUE THREAD

**Issue by mattdiamond** [Fyrd/caniuse#5610]
Steps to reproduce:

1) go to caniuse.com and type in "optional"
2) wait for the list to filter (the top result should be `:optional CSS pseudo-class`)
3) note the global/national usage stats in the upper right corner
4) type in " ch" (so the complete search is "optional ch" and the top result should be `JavaScript operator: Optional chaining operator (?.)`)
5) check the global/national usage stats again... they should be the same as the stats from step 3, even though the feature is different
6) refresh the page... the global/national usage stats should now be correct

**Comment by Fyrd** [comment]
Yikes, that's pretty bad. Just pushed a fix, should be working as expected now. Thanks so much for reporting!

**Comment by mattdiamond** [comment]
No problem, glad to help!
