### ISSUE TITLE
Swiper slider

### ISSUE THREAD

**Issue by tiendungdev** [Fyrd/caniuse#5611]

**Comment by atjn** [comment]
Swiper slider is not a browser feature, so it is not tracked on Caniuse. I would assume that they support all major browsers, but if you need to know, this quote is from their own [getting started guide](https://swiperjs.com/get-started/):
> If you have questions about Swiper ask them in [StackOverflow](http://stackoverflow.com/) and don't forget to tag your question with [swiper](https://stackoverflow.com/questions/tagged/swiper) tag.

**Comment by Fyrd** [comment]
Closing as per @atjn 's comment
