### ISSUE TITLE
video/quicktime 

### ISSUE THREAD

**Issue by henrik2311** [Fyrd/caniuse#5615]
I would like to know if I can use plugins like "video/quicktime" for displaying 360° pano videos of the file type "mov".
![Bildschirmfoto 2020-09-18 um 16 13 28](https://user-images.githubusercontent.com/10387904/93607679-f311e380-f9c9-11ea-8de2-1ec93b192ec1.png)
<img width="401" alt="Bildschirmfoto 2020-09-18 um 16 13 37" src="https://user-images.githubusercontent.com/10387904/93607764-0a50d100-f9ca-11ea-9bb0-6010687b5f54.png">

**Comment by atjn** [comment]
I'm sorry, but i think the glory days for something like that are way past.

[Chromium](https://blog.chromium.org/2013/09/saying-goodbye-to-our-old-friend-npapi.html) and [Firefox](https://support.mozilla.org/en-US/kb/npapi-plugins) have already completely removed support.
I'm not sure if it would work in Safari, but i seriously doubt it. It was [last updated 10 years ago](https://support.apple.com/downloads/quicktime).

I think your best bet is to use a form of embedded player, like [360player](https://360player.io/), but i am not an expert in that field.

**Comment by henrik2311** [comment]
Thank you for your reply, atjn.
I'm afraid you are right: the best times of quicktime vr have gone. I produced my last 360 degree image indeed ten, twelve or fifteen years ago. But I hoped that some player would automatically display this old video format.
Thank you for your hint. I will continue my current research for a solution using 360player.io as the next stepstone.
Have a nice day! Greetings from Germany, Henrik

**Comment by Fyrd** [comment]
Closing as per @atjn's comment
