### ISSUE TITLE
new URL() has problems in Safari.

### ISSUE THREAD

**Issue by dilyanpalauzov** [Fyrd/caniuse#5621]
Per https://github.com/zloirock/core-js/issues/656, https://github.com/zloirock/core-js/commit/8699b9a3024c1703d7b158ad3236288b38633af6 and https://bugs.webkit.org/show_bug.cgi?id=216841 in Safari 13 `new URL('http://x', undefined)` throws an error, but in Nodejs 14.9, Firefox 80 and Chromium 85 it does not.

Please reflect this at https://caniuse.com/url .

**Comment by Fyrd** [comment]
Thanks, has been added.
