### ISSUE TITLE
Please add attachInternals

### ISSUE THREAD

**Issue by chkch1** [Fyrd/caniuse#5627]
No info which browsers already support attachInternals yet.
see https://html.spec.whatwg.org/multipage/custom-elements.html

Would be nice if you could update the info. Thanks in advance.

**Comment by Schweinepriester** [comment]
Seems to be available via MDN now: <https://caniuse.com/mdn-api_htmlelement_attachinternals>

(On MDN it's on <https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement>)
