### ISSUE TITLE
RTCDataChannel.binaryType needs to list 'blob' and 'arraybuffer'

### ISSUE THREAD

**Issue by guest271314** [Fyrd/caniuse#5632]
Where https://caniuse.com/?search=binaryType. MDN browser-compat-data issue https://github.com/mdn/browser-compat-data/issues/6770.

Chromium, Chrome browsers does not support default `'blob'` https://bugs.chromium.org/p/webrtc/issues/detail?id=2276 which per the WebRTC specification is the default `RTCDataChannel` `binaryType` https://w3c.github.io/webrtc-pc/#dom-datachannel-binarytype 

> When an RTCDataChannel object is created, the binaryType attribute MUST be initialized to the string "blob".

**Comment by Fyrd** [comment]
As caniuse will automatically update once the change has been made on the BCD side I'll close this issue in favor of the BCD one you made. Thanks!
