### ISSUE TITLE
Add the ability to upload a .css file to the site and have it automatically generate a report of what browsers support what features.

### ISSUE THREAD

**Issue by Directory** [Fyrd/caniuse#5635]
I have thousands of lines of css and I need to make sure fallbacks are supported for a few older versions on major browsers. I can't paste every single feature that *may* have dodgy support to see. It would be cool if there was the ability for me to submit my compiled .css file to the site, and have it spit out a report of all the features with the least amount of browser support in order. That way I can decide what older browser versions I want to support fallbacks for.

This goes for all features, in my case clamp() wasn't working on safari 13 and when I checked the caniuse I saw that clamp() was only supported for 13.1 and above, but i still had to go digging to find it, who knows what other features aren't supported.

**Comment by atjn** [comment]
I think you are looking for [Doiuse](https://doiuse.herokuapp.com/)

It is linked on the front page of Caniuse under `Third Party Tools`.

**Comment by Directory** [comment]
That's very informative thank you
