### ISSUE TITLE
Update Chrome/Safari image-set to partial support

### ISSUE THREAD

**Issue by svivian** [Fyrd/caniuse#5636]
I sent this via feedback on the site but posting here for visibility, and adding more details. The info on the `image-set` CSS property is out of date. Chrome and Safari no longer have full support as per the spec:

- Chrome (v85.0) does not support the format `-webkit-image-set("image.jpg" 1x)`, only the form with `url("image.jpg")` - [bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=630597)
- Neither Chrome nor Safari (v14.0) support the MIME type parameter, like `-webkit-image-set(url("image.jpg") 1x type("image/jpeg"))`
- The note listed for Safari should link to [this bug report instead](https://bugs.webkit.org/show_bug.cgi?id=206142)
- There seems to be three separate entries for the same property: [1](https://caniuse.com/css-image-set), [2](https://caniuse.com/mdn-css_types_image_image-set), [3](https://caniuse.com/mdn-css_properties_background-image_image-set).

I can send a PR if desired, but I don't know how you approach reverting support when the spec changes. Do we go back and set all old versions to partial support?

**Comment by HM100** [comment]
For the forth point, it is intentional because caniuse also allows you to view compatibility support for anything found on MDN

**Comment by meliixo** [comment]
I dont understand what to do my parents have this imtrying to get it on them
