### ISSUE TITLE
Usage statistics are not up to date                                                          

### ISSUE THREAD

**Issue by atjn** [Fyrd/caniuse#5637]
I'm not sure exactly how your update process works, but according to the footer on Caniuse, the usage statistics have been updated to September 2020.

As far as i can tell, something must have gone wrong, since Chrome 85, iOS Safari 14.0 and Safari 14 should have much more usage than 0-1% in September.

I specifically care about this update, because it has an enormous effect on the overall statistics for [AVIF](https://caniuse.com/avif) and [WEBP](https://caniuse.com/webp) 😉️

**Comment by Fyrd** [comment]
Yeah, I tend to update it a few days into the new month, which means there's a few days in which that footer is wrong as it's just set to display the previous month. Something I should probably correct! Update should happen some time this weekend. :)

**Comment by Fyrd** [comment]
Went ahead and fixed the incorrect month, will now be based on the actual month the data was imported on so you can depend on it being correct.

**Comment by Fyrd** [comment]
Usage data updated too now.

**Comment by atjn** [comment]
Arh, awesome, thanks!
