### ISSUE TITLE
place-self working in Safari 14.0

### ISSUE THREAD

**Issue by janosh** [Fyrd/caniuse#5638]
According to https://caniuse.com/mdn-css_properties_place-self_flex_context, `place-self` is not supported in any version of Safari.

However, testing with Safari 14.0 on macOS 10.15.7, `place-self` is working just fine:

![place-self](https://user-images.githubusercontent.com/30958850/94992820-bed32100-058c-11eb-95da-43e4c7c8ecd5.png)

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body style="display: grid; height: 100vh">
    <div
      style="width: 100px; height: 100px; background: black; place-self: center"
    ></div>
  </body>
</html>
```

Note that inside inside a flexbox, the box is only centered vertically but that's the same behavior as in Chrome.

![place-self-flex-chrome](https://user-images.githubusercontent.com/30958850/94992989-0c03c280-058e-11eb-87e4-489de6b76287.png)

**Comment by Fyrd** [comment]
This data comes from the MDN BCD project, can you open an issue/PR there instead? https://github.com/mdn/browser-compat-data

**Comment by Fyrd** [comment]
I see the PR was made, so closing this issue. 👍
