### ISSUE TITLE
Add WebCodecs API

### ISSUE THREAD

**Issue by EwoutH** [Fyrd/caniuse#5641]
The WebCodecs API landed today in its first stable browser, Chrome 86. WebCodecs is an API that provides efficient, low-level access to built-in (software and hardware) media encoders and decoders.

- Spec: https://github.com/WICG/web-codecs
- Explainer: https://github.com/WICG/web-codecs/blob/master/explainer.md
- Website: https://wicg.github.io/web-codecs/

Chrome status: https://www.chromestatus.com/feature/5669293909868544

**Comment by EwoutH** [comment]
For Firefox: [Bugzilla issue list](https://bugzilla.mozilla.org/buglist.cgi?short_desc_type=allwordssubstr&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&classification=Graveyard&short_desc=WebCodecs&query_format=advanced&resolution=---&resolution=FIXED&resolution=INVALID&resolution=WONTFIX&resolution=INACTIVE&resolution=DUPLICATE&resolution=WORKSFORME&resolution=INCOMPLETE&resolution=SUPPORT&resolution=EXPIRED&resolution=MOVED)

**Comment by EwoutH** [comment]
WebCodecs is now adopted as a W3C Recommendation. The repo moved to https://github.com/w3c/webcodecs and the spec is now available on https://w3c.github.io/webcodecs/

**Comment by nathanbabcock** [comment]
Any ETA on adding this?

**Comment by Schweinepriester** [comment]
In addition to the [Bugzilla issue list](https://bugzilla.mozilla.org/buglist.cgi?short_desc_type=allwordssubstr&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&classification=Graveyard&short_desc=WebCodecs&query_format=advanced&resolution=---&resolution=FIXED&resolution=INVALID&resolution=WONTFIX&resolution=INACTIVE&resolution=DUPLICATE&resolution=WORKSFORME&resolution=INCOMPLETE&resolution=SUPPORT&resolution=EXPIRED&resolution=MOVED) above, singular tracking bug to follow for Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=WebCodecs

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/webcodecs though individual interfaces are also available via MDN, e.g. https://caniuse.com/mdn-api_audiodecoder
