### ISSUE TITLE
Add chrome stable 86 and Edge 86

### ISSUE THREAD

**Issue by Cyastis** [Fyrd/caniuse#5647]
Chrome 86 was released as stable 4 days ago, and yesterday Edge followed suit

**Comment by Schweinepriester** [comment]
They are (now?):

![image](https://user-images.githubusercontent.com/2644614/95687939-f3874e00-0c06-11eb-852e-512be5f2173d.png)

**Comment by Cyastis** [comment]
Yes this was added in a patch 14 hrs ago. Closing as fixed
