### ISSUE TITLE
Async Clipboard table disappears shortly after page load (Cannot read property 'sourceData' of null)

### ISSUE THREAD

**Issue by josephrocca** [Fyrd/caniuse#5653]
If I view this page on Chrome (v86) or Firefox: https://caniuse.com/async-clipboard then the compatibility table appears for a moment and then goes away. Here's the table if I stop the page loading before it gets a chance to disappear:

![image](https://user-images.githubusercontent.com/1167575/96326824-ceb82e00-107f-11eb-8854-fc512affbd4f.png)

And here's an error from the console:

![image](https://user-images.githubusercontent.com/1167575/96326842-f8715500-107f-11eb-977e-e88f62273085.png)

**Comment by Fyrd** [comment]
Yes, this feature was never officially published which is why it's not working as expected. Looks like it was added quite some time ago but fell off my radar as a feature to review. The issue #4680 exists for that. 

How did you run into the URL, is it linked to somewhere?

**Comment by josephrocca** [comment]
Yep, third result for me here https://www.google.com/search?q=can+i+use+async+clipboard

**Comment by Fyrd** [comment]
Curious... thankfully searches for other unpublished features don't show up so maybe that one was briefly there and got caught by the googlebot. Anyway, I've started researching the feature so hopefully will get it updated and appearing on the site properly soon. Thanks for reporting!

**Comment by Fyrd** [comment]
Alright, added now and should be working as expected.

**Comment by carnoxen** [comment]
https://caniuse.com/async-clipboard
It's not working

**Comment by carnoxen** [comment]
error message
```
ciu-option-tag.ts:66 Uncaught (in promise) TypeError: Cannot read property 'sourceData' of null
    at HTMLElement.getFeatTitle (ciu-option-tag.ts:66)
    at HTMLElement.makeTitle (ciu-option-tag.ts:79)
    at HTMLElement.render (ciu-option-tag.ts:89)
    at HTMLElement.update (lit-element.ts:293)
    at HTMLElement.performUpdate (updating-element.ts:774)
    at HTMLElement._enqueueUpdate (updating-element.ts:724)
```

**Comment by Fyrd** [comment]
Ugh, looks like I reverted the fix soon after I fixed it... fixed again _now_.

**Comment by carnoxen** [comment]
> Ugh, looks like I reverted the fix soon after I fixed it... fixed again _now_. Thanks for pointing that out @carnoxen.

Comfirmed. Thanks.
