### ISSUE TITLE
add ::unresolved css pseudo selector

### ISSUE THREAD

**Issue by wmanning** [Fyrd/caniuse#5655]

**Comment by Fyrd** [comment]
I believe this was considered for the v0 version of custom elements, but it no longer appears in specifications and was probably never implemented.

**Comment by wmanning** [comment]
It was implemented in Chrome (now depreciated).  The only reason I know is I was taking a course in plurasight on Web Components and it was covered and the instructor was using Chrome to demo it. The course was made in 2015.

I was trying to find out more info about it.
