### ISSUE TITLE
Issue parsing content-security policy data?

### ISSUE THREAD

**Issue by larowlan** [Fyrd/caniuse#5657]
I opened https://github.com/mdn/browser-compat-data/issues/6998 because https://caniuse.com/mdn-http_headers_csp_content-security-policy_meta-element-support was showing Unknown for Chrome, and manually testing found it was working.

But over there they pointed to https://github.com/mdn/browser-compat-data/blob/c31d61db5c146655ecb99fee28d367924b0f7329/http/headers/content-security-policy.json#L657-L663 i.e. their data already said it was supported.

So the question is, is there an issue parsing this data for Can I Use?

**Comment by Fyrd** [comment]
Yup, an obvious error that was easy to fix. Should be working as expected now. Thanks for reporting!

**Comment by larowlan** [comment]
😍 thanks!
