### ISSUE TITLE
Correction: WebAuthn is _not_ supported in Chrome for iOS 14

### ISSUE THREAD

**Issue by jingman** [Fyrd/caniuse#5672]
The tooltip indicates that WebAuthn is supported in Chrome for iOS 14, but it is not. You can visit [webauthn.io](webauthn.io) or any other WebAuthn test website to verify this.

<img width="419" alt="Screen Shot 2020-10-23 at 12 41 28 PM" src="https://user-images.githubusercontent.com/99067/97192627-158bdf00-1776-11eb-9d67-a63419979e86.png">

**Comment by kiding** [comment]
Possibly related to #5113.

**Comment by Fyrd** [comment]
Thanks, did some testing and it doesn't appear supported anymore... maybe it was only supported in the beta iOS versions when originally added. Have updated the data.

**Comment by kiding** [comment]
@Fyrd Just saw https://github.com/Fyrd/caniuse/commit/9f393066d48f4f388bf3267d8dbdccecd694ea86 pulled all WebAuthn support status for iOS, which isn’t right given [how much Apple pushed PR around it,](https://www.theverge.com/2020/6/24/21301509), and most importantly, https://webauthn.io does work on iOS **Safari**.

What this issue and #5113 indicate is that Experimental Features (whether enabled by default or not) on WKWebView/UIWebView do not behave the same way as iOS Safari. That includes Chrome, DuckDuckGo, and many other _browsers_ on iOS.

CanIUse says the support statuses apply to both **Safari & Chrome** for iOS. As the Experimental Features list grow and the feature sets diverge, this statement might need to be changed to simply “Safari for iOS.”

**Comment by Fyrd** [comment]
Ugh, you're absolutely right, I ran my tests on http only so that's why they were failing in every browser. 🤦‍♂️
Went ahead and updated manually, I feel since quite a few folks use Chrome on iOS support should be partial in addition to the note. 
Thanks!
