### ISSUE TITLE
CookieStore API missing

### ISSUE THREAD

**Issue by prof3ssorSt3v3** [Fyrd/caniuse#5673]
Available in Chrome as of version 87.

https://wicg.github.io/cookie-store/

Not on standards track yet but sorely needed as an async solution for dealing with cookies.

**Comment by Schweinepriester** [comment]
Duplicate of #5659. But as mentioned in https://github.com/Fyrd/caniuse/issues/5659#issuecomment-715689093 still not live on the site. Data is here: https://github.com/Fyrd/caniuse/blob/master/features-json/cookie-store-api.json

**Comment by Fyrd** [comment]
Closing as duplicate of #5659 .
