### ISSUE TITLE
Current stable version of Firefox Android is 82, but caniuse.com says 79 is the latest stable version.

### ISSUE THREAD

**Issue by makotokato** [Fyrd/caniuse#5683]
Actually, caniuse.com says that the latest stable version of Firefox for Android is 79. Example, https://caniuse.com/flexbox is that 79 is the latest version.

But Mozilla has already released 82 last month.  Why?

**Comment by Fyrd** [comment]
Firefox for Android for a long time was stuck on an older version so hadn't been keeping much of an eye on it. Fixed now, thanks!
