### ISSUE TITLE
Change wording and possibly information about TLS 1.0 & TLS 1.1

### ISSUE THREAD

**Issue by owlstead** [Fyrd/caniuse#5686]
Currently the site says, at link https://caniuse.com/sr_tls1:

While effectively supported in all older browsers, TLS 1.0 & 1.1 are deprecated in Chrome, Edge, Firefox, Internet Explorer 11, & Safari. **Support will be removed in March 2020.**

This text is obviously outdated. The site should be updated to indicate the current status. I'm not sure if that means simply updating the text or if it means adding / rerunning tests & stats.

**Comment by Ugoku** [comment]
Support for TLS 1.0/1.1 was removed in Chrome 84 (August): https://www.chromestatus.com/feature/5759116003770368

I can't find anything about when Firefox plans to remove it.

**Comment by Fyrd** [comment]
Thanks, have done a bit of research and updated the data.
