### ISSUE TITLE
CoffeeScript (2) support?

### ISSUE THREAD

**Issue by bkisdi** [Fyrd/caniuse#5696]
https://coffeescript.org/
“It’s just JavaScript.”
Files have .coffee extension.

Chrome 86 passes all current tests (https://coffeescript.org/test.html).
I wonder which browsers and from which version support CoffeeScript 1 and CoffeeScript 2.

I've searched for CoffeeScript, coffeeScript, coffeescript, 0 matches for all.
Thanks.

**Comment by Fyrd** [comment]
As mentioned on the site, CoffeeScript _compiles into JavaScript_. While JavaScript is supported across browsers (as shown in that test), no browser natively supports CoffeeScript.
