### ISSUE TITLE
Edge support data is invalid for dateStyle

### ISSUE THREAD

**Issue by martonx** [Fyrd/caniuse#5702]
Hi,

Check this site: https://caniuse.com/mdn-javascript_builtins_intl_datetimeformat_datetimeformat_datestyle

As Edge has the same Chromium engine as Chrome, I tried, and latest Edge support this feature.

**Comment by Fyrd** [comment]
As this is part of the MDN BCD data, you can [update the data](https://github.com/mdn/browser-compat-data/blob/master/javascript/builtins/intl/DateTimeFormat.json) there or [file an issue](https://github.com/mdn/browser-compat-data) there.
