### ISSUE TITLE
WebTransport

### ISSUE THREAD

**Issue by EyeOfMidas** [Fyrd/caniuse#5707]
https://w3c.github.io/webtransport/

> The WebTransport interface is based on the QuicTransport interface initially described in the W3C ORTC CG, and has been adapted for use in this specification.

**Comment by berkant** [comment]
WebTransport is now available as of Chrome 97 stable: https://developer.chrome.com/blog/new-in-chrome-97/

**Comment by wegylexy** [comment]
Moreover, Chrome 100 and Edge 100 support custom certificate hashes.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/webtransport
