### ISSUE TITLE
Conflicting information for CSS scroll-behavior property for Safari

### ISSUE THREAD

**Issue by Ryuno-Ki** [Fyrd/caniuse#5716]
Hey Fyrd,

first, thanks for providing Can I Use! It's super helpful!

Today, I had a short discussion with our tech lead regarding [CSS scroll-behavior property](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior#Browser_compatibility).

[According to Can I Use](https://caniuse.com/css-scroll-behavior), Safari does not support it.
However, [looking at BCD](https://github.com/mdn/browser-compat-data/blob/fc26e02c9f0247f5522d560242d6d47fc9ff4a36/css/properties/scroll-behavior.json#L32-L49) it seems to have been added in the latest version behind a flag.

Could you get in touch with @break-stuff who added it in https://github.com/mdn/browser-compat-data/pull/7364 ?

I have no Apple device at hand to check it for myself right now.

Thanks

André

**Comment by Ryuno-Ki** [comment]
Perhaps #3806 is related (even if it targets Chromium-based browsers).

**Comment by Fyrd** [comment]
Just tested and can confirm. Data has been updated, thanks!
