### ISSUE TITLE
notSent as input name

### ISSUE THREAD

**Issue by cicamaca123** [Fyrd/caniuse#5723]
https://stackoverflow.com/questions/3008035/stop-an-input-field-in-a-form-from-being-submitted/61648470#61648470
I was wondering whats the suport for notSent  when you put it in input like from this link ?
<input type="text" name="notSent" value="..." />

**Comment by Fyrd** [comment]
Looks like that example is pointing out that the input field inside the nested `<form>` element won't be sent. The "name" value can be anything and is defined there as "notSent" simply as an example.
