### ISSUE TITLE
device-pixel-content-box for ResizeObserver

### ISSUE THREAD

**Issue by greggman** [Fyrd/caniuse#5730]
This shipped in Chrome/Edge ~July 2020

https://web.dev/device-pixel-content-box/

There is currently no way other browsers to get the correct size of an element in device pixels in all cases without this API

See spec: https://drafts.csswg.org/resize-observer/#resize-observer-entry-interface

**Comment by Schweinepriester** [comment]
Appears to be available via MDN now: https://caniuse.com/?search=device-pixel-content-box
