### ISSUE TITLE
[DOM API] `signal` option on EventTarget.protoype.addEventListener

### ISSUE THREAD

**Issue by mysticatea** [Fyrd/caniuse#5732]
> https://github.com/whatwg/dom/pull/919

That has been merged into the standard recently.

```js
const ac = new AbortController()
const target = new EventTarget()

// register a listener with `signal` option
target.addEventListener("foo", () => {}, { signal: ac.signal })

// remove that listener
ac.abort()
```

Also, DOM elements support this feature because it inherits from `EventTarget`.

**Comment by kiding** [comment]
Some more references:
* [Chrome Platform Status](https://www.chromestatus.com/feature/5658622220566528): Shipped with Chrome 88
* [Mozilla Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1679204): To be shipped with Firefox 86
* [WebKit Bug](https://bugs.webkit.org/show_bug.cgi?id=218753): Unknown, should follow up

**Comment by warpr** [comment]
Seems to have been implemented in WebKit now, but it is unclear to me which Safari version will have these changes.

https://trac.webkit.org/changeset/271806/webkit

**Comment by Schweinepriester** [comment]
Available via MDN now:
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#browser_compatibility
→ https://caniuse.com/mdn-api_eventtarget_addeventlistener_options_parameter_options_signal_parameter
