### ISSUE TITLE
Is there some tool to automate CSS Browser support?

### ISSUE THREAD

**Issue by vorant94** [Fyrd/caniuse#5733]
Hi, can someone tell me if there is something like [caniuse.com](caniuse.com), but with the ability to just feed him the URL of the site and he would give that the CSS of this site (whether it is SPA or not) requires at least such and such browser versions for stable work? Or how are such compatibility checks automated at all?

**Comment by Fyrd** [comment]
I believe you're looking for this tool: http://doiuse.herokuapp.com/

**Comment by vorant94** [comment]
@Fyrd thanks, that exactly what I meant🙏
