### ISSUE TITLE
counter() and counters() - Broken MDN links

### ISSUE THREAD

**Issue by joshsalverda** [Fyrd/caniuse#5735]
Links to MDN for counter() and counters() aren't being parsed correctly:

<img width="301" alt="Screen Shot 2021-01-07 at 2 56 43 PM" src="https://user-images.githubusercontent.com/3029989/104022380-3321ef80-518e-11eb-9095-e224a2fd8f55.png">

The last `)` gets placed outside of the anchor link.

The links are correct in the source json:

https://github.com/mdn/browser-compat-data/blob/master/css/types/counter.json
and
https://github.com/mdn/browser-compat-data/blob/master/css/types/counters.json

**Comment by Fyrd** [comment]
Thanks for reporting! This has now been corrected.
