### ISSUE TITLE
Pointer Lock API: unadjustedMovement

### ISSUE THREAD

**Issue by kiding** [Fyrd/caniuse#5744]
An additional option for the Pointer Lock API to disable mouse acceleration. See https://github.com/w3c/pointerlock/pull/49 for (future) spec change.

### Implementation Status
* Chrome: 80+ ([approx](https://bugs.chromium.org/p/chromium/issues/detail?id=982379#c29)) flagged, 88+ by default
* Firefox: ?
* Safari: ?

### References
* [Chrome Platform Status](https://www.chromestatus.com/feature/5723553087356928)
* [Chromium Bug](https://bugs.chromium.org/p/chromium/issues/detail?id=982379)
* [web.dev - Disable mouse acceleration to provide a better FPS gaming experience](https://web.dev/disable-mouse-acceleration/)

**Comment by Schweinepriester** [comment]
Appears to be available via MDN now: https://caniuse.com/mdn-api_element_requestpointerlock_options_unadjustedmovement_parameter

Also: This issue currently has the wrong label - "Site functionality" instead of "Support data suggestion"

**Comment by Fyrd** [comment]
Closing as per last comment.
