### ISSUE TITLE
Chrome 88 supports aspect-ratio

### ISSUE THREAD

**Issue by tobireif** [Fyrd/caniuse#5746]
Chrome 88 supports aspect-ratio: https://css-tricks.com/new-in-chrome-88-aspect-ratio/ .

The page https://caniuse.com/mdn-css_properties_aspect-ratio currently doesn't reflect that.

**Comment by Fyrd** [comment]
Tracked by MDN BCD, so please submit a PR or file a ticket at https://github.com/mdn/browser-compat-data

**Comment by tobireif** [comment]
Found an existing ticket: https://github.com/mdn/browser-compat-data/issues/8797

**Comment by chingucoding** [comment]
The MDN issue is closed now, @Fyrd. Can this be closed now then?

**Comment by tobireif** [comment]
The page https://caniuse.com/mdn-css_properties_aspect-ratio now reflects the fact that Chrome 88 supports aspect-ratio.
