### ISSUE TITLE
Germany usage issue? (possibly tracked mobile only)

### ISSUE THREAD

**Issue by ezadoo** [Fyrd/caniuse#5747]
I‘m not sure but the usage statistics for Germany seems to be incorrect. 

I believe there are missing between 20% to 25% of nearly all features and I can’t figure out where this percentage of browsers not supporting nearly all features is coming from. The issue also seems to be related to „tracked mobile“, as everything seems to be normal for „tracked desktop“.

I think that the statistics can’t be correct as simple features like display: inline-block is affected too (I haven’t found any feature wich isn’t affected) which is supported by nearly 100% of all other countries.

**Comment by Fyrd** [comment]
Looks like there was an issue with the latest iOS Safari version number not being taken into account, as a result the latest version was appearing as 0 usage for Germany. If you delete and re-add it should be appearing correctly now. Still need to figure out why the issue occurred for Germany but not other regions...

Thanks for reporting!

**Comment by ezadoo** [comment]
Thanks for fixing this.
