### ISSUE TITLE
Feature Request：w3.css (all w3- etc, )

### ISSUE THREAD

**Issue by winniejo** [Fyrd/caniuse#5749]
Feature Request：for w3.css / w3.css library 
some beginning with w3-dropdown , w3-dropdown-content ,  etc, especially 
does not seem to work in older version of safari 6 and 7.
w3 in general is not supported at all. 
Its also the case for Bootstrap (  dropdown, dropdown-toggle  )

Thank you.
Winn

**Comment by Ugoku** [comment]
No idea what you're talking about, but Safari 7 is a 7 year old browser you should not be using anymore.

**Comment by winniejo** [comment]
w3.css is a CSS framework  (strictly html css).
Safari 7 is even older but that the whole oint of "Can I use"
With respect dont tell me what and what not to do. please.

Winn

**Comment by Fyrd** [comment]
Libraries and frameworks aren't tracked on caniuse, only technologies supported by browsers.
