### ISSUE TITLE
no firefox ver. 85

### ISSUE THREAD

**Issue by amazhukin** [Fyrd/caniuse#5752]
Asked before at [caniuse-lite](https://github.com/ben-eb/caniuse-lite/issues/59).

Firefox version 85 was released January 26, 2021
I have run updating browserslist db:
`npx browserslist@latest --update-db`
![image](https://user-images.githubusercontent.com/46565276/106101426-54f01000-6157-11eb-9e68-2294e258de91.png)
 but stll latet version of firefox is 84:
`npx browserslist@latest`
![image](https://user-images.githubusercontent.com/46565276/106101566-810b9100-6157-11eb-9462-41faaf388b50.png)

How I can get correct last version of firefox?

**Comment by Fyrd** [comment]
Sometimes it takes a few days before a version gets bumped to the latest. Have just pushed the update for Firefox.
