### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#5756]
Many companies and projects are renaming their master branches in Git — to `main`, or something similar — in a realization that the word master is problematic. Master, whitelist, blacklist, these are words rooted in racist structures. 

It would be great if Can I Use could do the same.

**Comment by Fyrd** [comment]
Yeah, it's been on my mental list of things to do, good to have an issue for it. Will need to do some investigation on any processes etc that depend on the branch name. Thanks for bringing this up!

**Comment by Fyrd** [comment]
Alright, I believe this work has been completed, `main` is now the default branch. :)

**Comment by jensimmons** [comment]
Thank you so much!!
