### ISSUE TITLE
Sync with BCD data for object-fit

### ISSUE THREAD

**Issue by foolip** [Fyrd/caniuse#5759]
I've just sent to fixes for `object-fit` in BCD:
https://github.com/mdn/browser-compat-data/pull/8960
https://github.com/mdn/browser-compat-data/pull/8961

This feature is [in caniuse](https://github.com/Fyrd/caniuse/blob/fba58f129ee0746aa35bf5e9a6a593a1eb9d6657/features-json/object-fit.json) was well, and I presume predates the integration with BCD.

I spot a few inaccuracies in the caniuse data:
- The same Chrome 31 vs. 32 error as in BCD
- The "op_mob" and "and_chr" support is much later than it could be

I'd be happy to just send PRs, but wonder if there are any scripts for updating caniuse data from BCD or vice versa?

**Comment by Fyrd** [comment]
Thanks! I've updated the caniuse data. Note that only the latest version of Opera Mobile & Chrome for Android are tracked on caniuse, so the information is actually correct there.

There isn't currently such a script to my knowledge, but I agree that would be useful to have at some point.

**Comment by foolip** [comment]
Thanks @Fyrd! I see the change was made in https://github.com/Fyrd/caniuse/commit/459b72ba0b62d869c03951eb146f5a0760baa529. Had I known that Opera Mobile & Chrome for Android were intentionally only tracking the latest version I could have sent the PR myself. I'll do that next time :)
