### ISSUE TITLE
getUserMedia on iOS 14.3 works in WebViews

### ISSUE THREAD

**Issue by rrelmy** [Fyrd/caniuse#5760]
The note regarding the limited support on WebView is no longer accurate.
On iOS 14.3 getUserMedia is fully supported within WebViews and other Browsers like chrome.

Relevant issues:
- https://bugs.webkit.org/show_bug.cgi?id=208667
- https://bugs.chromium.org/p/chromium/issues/detail?id=752458

**Comment by Fyrd** [comment]
Thanks! Have left the note since iOS 14 subversions are part of the same entry, but updated it accordingly.
