### ISSUE TITLE
WeakRefs

### ISSUE THREAD

**Issue by JamesGelok** [Fyrd/caniuse#5766]
[weakrefs tc39 proposal is implemented in chrome and firefox](https://github.com/tc39/proposal-weakrefs) and should be on caniuse

**Comment by Schweinepriester** [comment]
<https://caniuse.com/mdn-javascript_builtins_weakref> via MDN seems to be it, isn't it (singular vs. plural)?

also two more (sub-)entries exist: <https://caniuse.com/?search=WeakRef>

**Comment by JamesGelok** [comment]
Oh nevermind then. When I tried searching earlier no results came up.
Must’ve mistyped.
