### ISSUE TITLE
image-set is now supported in mozilla

### ISSUE THREAD

**Issue by georgringer** [Fyrd/caniuse#5785]
https://caniuse.com/?search=image-set should be green for firefox, see https://www.mozilla.org/en-US/firefox/86.0/releasenotes/ 

taken from https://twitter.com/stefanjudis/status/1366298661781577731 but didn't check myself

**Comment by Schweinepriester** [comment]
@mathiasbynens commented that as well in the chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=630597#c35

but I was testing it and as others pointed out (e.g. https://twitter.com/__jakub_g/status/1366336876450357248) it doesnt actually work in 86:

<https://tests.caniuse.com/css-image-set>:

![image](https://user-images.githubusercontent.com/2644614/109502388-32744e00-7a99-11eb-93ce-be078e70465e.png)

87 as well.
88 works, but seems like its nightly only for now...

<https://www.mozilla.org/en-US/firefox/86.0/releasenotes/> is currently not correct.

**Comment by Schweinepriester** [comment]
But at least its available behind a flag :)

Opened a PR for that: #5786

**Comment by Schweinepriester** [comment]
And now its coming for real: #5805

So this issue can be closed, I believe?
