### ISSUE TITLE
Track support for newly added spec: Dimensions (width/height) in <source> tags

### ISSUE THREAD

**Issue by patricknelson** [Fyrd/caniuse#5791]
Can we start tracking support for dimensions (width/height) in `<source>` tags? This was just recently added to the living HTML standard here: 
https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element

**Via:**
https://github.com/whatwg/html/issues/4968
https://github.com/whatwg/html/pull/5894

**Example:**

```
<picture>
  <source srcset="https://via.placeholder.com/600x279" media="(max-width: 599px)" width="600" height="279">
  <source srcset="https://via.placeholder.com/1500x300" media="(max-width: 991px)" width="1500" height="300">
  <img src="https://via.placeholder.com/1500x300" width="1500" height="300">
</picture>
```

**EDIT (May 6, 2022):** Looks like this is available now on caniuse.com under the following two separate entries:

* [HTMLSourceElement API: height](https://caniuse.com/mdn-api_htmlsourceelement_height)
* [HTMLSourceElement API: width](https://caniuse.com/mdn-api_htmlsourceelement_width)

**Comment by scott-thrillist** [comment]
I love how I randomly stumbled on this issue and got an 🤯 when I found out dimensions attributes are now supported in Chrome 90. Just waiting on Safari...

**Comment by strarsis** [comment]
@patricknelson, @scott-thrillist: Does Safari support it, too, now?

**Comment by patricknelson** [comment]
Not sure right at this moment, but one quick way to test this would be to load up the web platform test suite. Found this test which might make it easy to validate: https://github.com/web-platform-tests/wpt/blob/master/html/rendering/replaced-elements/attributes-for-embedded-content-and-images/picture-aspect-ratio.html

Docs on how to load it up in the browser: http://web-platform-tests.org/running-tests/from-local-system.html#via-the-browser

**Comment by hecktarzuli** [comment]
@strarsis - I tested this myself, and this seems to work in Safari 15.2, just waiting for more official confirmation and timing.

**Comment by patricknelson** [comment]
And once y'all find out, please cc that information here too. Ideally, this would be documented in the developer's Bible of Compatibility (caniuse.com) 😄

**Comment by hecktarzuli** [comment]
@patricknelson it looks like it went out in [Safari 15](https://webkit.org/blog/11989/new-webkit-features-in-safari-15/) which contained [Tech Preview 128](https://webkit.org/blog/11925/release-notes-for-safari-technology-preview-128/) (referenced at the bottom)

**Comment by hecktarzuli** [comment]
I feel like this is already documented, it just wasn't obvious it was for aspect-ratio..
https://caniuse.com/mdn-api_htmlsourceelement_height

**Comment by patricknelson** [comment]
Thanks @hecktarzuli! I'll update the issue description to link to both width/height. Thankfully it appears if you happen to look for `source` and `width` (or `height`), albeit that might not show up for most folks if they look instead for `dimensions` or include the word `element`.

I think it's probably fine but maybe there's a way to expand it so it is slightly easier to find? 🤔 Might close now though since at least it is visible now on the caniuse.com site.

**Comment by hecktarzuli** [comment]
@patricknelson i was just expecting something more like this
![image](https://user-images.githubusercontent.com/2112282/167203917-332eb599-1b6f-4891-ad3c-f52d21a5be9d.png)

It's the same new properties, for the same reason (auto aspect-ratio), just for the `<img>` tag instead of `<source>`

**Comment by patricknelson** [comment]
Same here @hecktarzuli, that's how I would have originally found this (i.e. searching something like `source width` which _works_ but also maybe `source dimensions`).

**Comment by Schweinepriester** [comment]
Positioned to ship in Firefox 106:

https://bugzilla.mozilla.org/show_bug.cgi?id=1694741#c23

> [status-firefox106](https://bugzilla.mozilla.org/buglist.cgi?f1=cf_status_firefox106&o1=isnotempty): --- → [fixed](https://bugzilla.mozilla.org/buglist.cgi?f1=cf_status_firefox106&o1=equals&v1=fixed)
Resolution: --- → FIXED
Target Milestone: --- → 106 Branch

**Comment by hecktarzuli** [comment]
@Schweinepriester it seems it's now 108.

**Comment by patricknelson** [comment]
Ok, looks like this is now documented 🚀. It's under `source: width` and `source: height` now (via https://github.com/mdn/browser-compat-data/pull/18081).

* https://caniuse.com/mdn-html_elements_source_width
* https://caniuse.com/mdn-html_elements_source_height
