### ISSUE TITLE
TP

### ISSUE THREAD

**Issue by pannous** [Fyrd/caniuse#5796]
it took some minutes for me to figure out that TP probably means technical preview.

please add a footnote to safari column

**Comment by Schweinepriester** [comment]
Its there in full on hover:

![image](https://user-images.githubusercontent.com/2644614/110116239-817ef380-7db7-11eb-9114-9e68b5047d60.png)

Where would you like to see the footnote?

**Comment by pannous** [comment]
How do you get the hover on mobile? Implementing tap to hover might be helpful. Anyways I figured it out, so it's just out of consideration for others (there is the 1:100 rule: if one person reports it there are at least a hundred with the same problem).

**Comment by Fyrd** [comment]
Tap to hover already works though...just tried it on Chrome and Firefox for Android. Can you confirm that doesn't work for you?

![Screenshot_20210305-221015](https://user-images.githubusercontent.com/432336/110197343-e2321e80-7dff-11eb-93b3-8389de7435ce.png)

**Comment by pannous** [comment]
I am sorry I must've been in a private session with JavaScript disabled
 so sorry for wasting your time
