### ISSUE TITLE
Android Browser has not been updated and now displays wrong information (at least for AVIF)

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#5807]
I've noticed following #5799 where you correctly updated Chrome for Android (to 89 plus support for AVIF), but also changed Android Browser:

https://github.com/Fyrd/caniuse/commit/74576a69380dde72ba8428a9096bd35ae5a9dd93#diff-1fa046bd784cf74400da6394067267ba81f1f508f91c655f12f30057e5ccd4d7

which leads to this:

![image](https://user-images.githubusercontent.com/2644614/111052859-3f148100-845f-11eb-93e3-d91472fe64f5.png)

which almost certainly is not correct, given that support for desktop started with 85 and Chrome for Android with 89.

I've titled the issue generic, because AVIF might not be the only case, since Android Browser hasn't been updated in a while?

Would be great if you could update Android Browser to 89, which is the current version: https://play.google.com/store/apps/details?id=com.google.android.webview&hl=de&gl=US

![image](https://user-images.githubusercontent.com/2644614/111052933-ef828500-845f-11eb-9483-b9f7915a8842.png)

If I can be of help with PRs or something, just let me know :)

**Comment by Fyrd** [comment]
It actually has been updated, unfortunately in my database I had the version hardcoded somewhere as 81 which was overriding the version I thought I was updating to. 🤦‍♂️ 
Should be fixed now, thanks for pointing that out!
