### ISSUE TITLE
Safari & Chrome for iOS 12.5 not recognized on import

### ISSUE THREAD

**Issue by andronocean** [Fyrd/caniuse#5808]
When importing from Google Analytics, "Safari & Chrome for iOS 12.5" doesn't match a tracked browser (probably because iOS 12.5 is a new security update from December).

From our data, though, the majority of our remaining iOS 12 users upgraded to it, so they're not getting counted anymore in CanIUse.

Thanks in advance for keeping all this stuff updated. Is there any way to help contribute new browser versions to the project? I looked around but didn't see anything.

**Comment by Fyrd** [comment]
Have updated the latest version range to include 12.5, thanks for pointing that out!

**Comment by andronocean** [comment]
Hey there @Fyrd, something must have regressed in a recent update — "Safari & Chrome for iOS 12.5" is back in the "Browsers not included" today on a new Google Analytics import.

Checked inside my GA for the iOS versions, and I'm seeing `12.5`, `12.5.1`, `12.5.3`, and `12.5.4`.
