### ISSUE TITLE
Update WebNFC test

### ISSUE THREAD

**Issue by atjn** [Fyrd/caniuse#5811]
The [WebNFC spec](https://w3c.github.io/web-nfc/#feature-support) has had [an update](https://github.com/w3c/web-nfc/commit/e50a81c2a232b8a42b6532e0196df8c5c5928e19) that consolidates the `NDEFReader` and `NDEFWriter` into a single `NDEFReader` object. The current [caniuse test](https://tests.caniuse.com/webnfc) checks for the presence of both objects, which makes it seem like devices don't fully support the spec, even though they do.

**Comment by Fyrd** [comment]
Has now been fixed, thanks!
