### ISSUE TITLE
Update name of Safari on iOS to reflect official name

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#5815]
@Fyrd We talked about this recently, but I thought it might be helpful for me to open an issue.

MDN is looking at the names for the mobile browsers as well: https://github.com/mdn/browser-compat-data/issues/7328

To be clear, for Safari, it's "Safari on iOS".

**Comment by Fyrd** [comment]
Ah yes, I'd updated it over the weekend but didn't get it quite right. Should be correct now. :)

**Comment by jensimmons** [comment]
We thank you!
