### ISSUE TITLE
Add `accent-color` property (CSS UI 4)

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#5820]
- Spec: https://www.w3.org/TR/css-ui-4/#widget-accent
- https://www.chromestatus.com/feature/4752739957473280 (=> `"chrome_id":"4752739957473280"`)
- In Chrome Canary 91 behind "Experimental Web Platform Features" flag: https://twitter.com/quicksave2k/status/1371782807148761091
- Demo: https://css-accent-color.glitch.me/ (also via [the tweet](https://twitter.com/quicksave2k/status/1371782807148761091))

**Comment by mrleblanc101** [comment]
For some reason Chrome devtools added support for autocompleting this, but it doesn't seem to be recognised.
It would be a great addition to Can I Use.
https://developer.chrome.com/blog/new-in-devtools-91/

**Comment by argyleink** [comment]
Also available in Firefox Nightly
Chromium is looking to ship this feature in 92 or 93, here's the [intent to ship](https://groups.google.com/a/chromium.org/g/blink-dev/c/WwYkLjbGhoA/m/wv6eA3seAwAJ)

**Comment by Schweinepriester** [comment]
Available via MDN: <https://caniuse.com/mdn-css_properties_accent-color>

<https://bugs.chromium.org/p/chromium/issues/detail?id=1092093#c31>:

> Enable accent-color by default

**Comment by Schweinepriester** [comment]
WebKit/Safari: https://bugs.webkit.org/show_bug.cgi?id=227587

https://webkit.org/blog/12040/release-notes-for-safari-technology-preview-135/:

> Enabled `accent-color` by default ([r284634](https://trac.webkit.org/changeset/284634/webkit/))

(Already reflected in https://caniuse.com/mdn-css_properties_accent-color)

**Comment by Fyrd** [comment]
Closing as per the above
