### ISSUE TITLE
Add CSS Properties and Values API

### ISSUE THREAD

**Issue by SebastianZ** [Fyrd/caniuse#5821]
One part of CSS Houdini is the [CSS Properties and Values API](https://www.w3.org/TR/css-properties-values-api-1/).

A big part of this specification is already supported by Chromium based browsers. See  and https://developer.mozilla.org/en-US/docs/Web/CSS/@property.

I suggest to either create a high-level entry for this specification (like [there is for the CSS Paint API](https://caniuse.com/css-paint-api)), or add a description to [`CSS.registerProperty()`](https://caniuse.com/mdn-api_css_registerproperty) and the [`@property` rule](https://caniuse.com/mdn-css_at-rules_property) so that there is a reference to the CSS Properties and Values API specification.

Sebastian

**Comment by GPHemsley** [comment]
Looks like this is now covered by MDN data:
https://caniuse.com/mdn-api_css_registerproperty
https://caniuse.com/mdn-css_at-rules_property

(via mdn/browser-compat-data#5065)
