### ISSUE TITLE
Navigator.vibrate()

### ISSUE THREAD

**Issue by JavascriptLearner815** [Fyrd/caniuse#5825]
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/vibrate

**Comment by Schweinepriester** [comment]
It's there, even when searching for `Navigator.vibrate`: <https://caniuse.com/?search=Navigator.vibrate>

Or…?

**Comment by JavascriptLearner815** [comment]
> It's there, even when searching for `Navigator.vibrate`: https://caniuse.com/?search=Navigator.vibrate
> 
> Or…?

"Navigator.vibrate()" didn't show it up.
