### ISSUE TITLE
[ADD BROWSER] Chrome on iOS

### ISSUE THREAD

**Issue by conradkirschner** [Fyrd/caniuse#5833]
More and more user use chrome on iOS + debugging it costs currently a hard effort.
https://apps.apple.com/de/app/google-chrome/id535886823

 (Only solution I found is building chromium from source, because of iOS restriction for debugging released apps)

**Comment by Schweinepriester** [comment]
Duplicate of #3519?

**Comment by conradkirschner** [comment]
closed because of dublicate of #3519
