### ISSUE TITLE
Change links to the browser-compat-data repo to point to branch `main`

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#5838]
For example <https://caniuse.com/mdn-css_types_image_image-set> in the Feedback tab

> For corrections/updates, see the browser-compat-data [Contributing docs](https://github.com/mdn/browser-compat-data/blob/master/docs/contributing.md) and the [support data for this feature](https://github.com/mdn/browser-compat-data/blob/master/css/types/image.json).

both links point to `…/master/…` which leads to the (imho distracting) notification that you've been redirected:

<img width="721" alt="Bildschirmfoto 2021-04-01 um 00 07 19" src="https://user-images.githubusercontent.com/2644614/113218884-95b3f480-9280-11eb-9305-9df42ef0fa27.png">

(Also linking to `main` would be more correct)

Therefore please change those and possible other links to the [browser-compat-data repo](https://github.com/mdn/browser-compat-data) to point to branch `main` :)

**Comment by Fyrd** [comment]
Done! Thanks for pointing that out.
