### ISSUE TITLE
Test for SVG favicons appears to be broken

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#5843]
<https://tests.caniuse.com/link-icon-svg>

That is, no link appears to be present

<img width="845" alt="Bildschirmfoto 2021-04-05 um 17 03 27" src="https://user-images.githubusercontent.com/2644614/113588841-ef297400-9630-11eb-9494-0ccb02a80b34.png">

(#3196 Fyrd pls 0:-))

**Comment by Fyrd** [comment]
Fixed!

**Comment by Schweinepriester** [comment]
Noice!
