### ISSUE TITLE
MediaDevices.selectAudioOutput

### ISSUE THREAD

**Issue by adjenks** [Fyrd/caniuse#5849]
See: https://w3c.github.io/mediacapture-output/

As far as I understand no browsers have this feature yet.

**Comment by abhijeetk** [comment]
It seems FF has added a support.

[1] https://wpt.fyi/results/audio-output?label=experimental&label=master&aligned

**Comment by adjenks** [comment]
@abhijeetk 
The particular function I mentioned in the title of this still seems to have no support. Firefox seems to support some other related things but not that function specifically. Maybe I'm reading it wrong, but in the tests I see you linked I see this:
> "TypeError: navigator.mediaDevices.selectAudioOutput is not a function"

**Comment by Schweinepriester** [comment]
Available via MDN now: https://caniuse.com/?search=selectAudioOutput
→ https://caniuse.com/mdn-api_mediadevices_selectaudiooutput

**Comment by Fyrd** [comment]
Closing as per above.
