### ISSUE TITLE
[WebCryptoAPI] randomUUID

### ISSUE THREAD

**Issue by mojoaxel** [Fyrd/caniuse#5851]
https://wicg.github.io/uuid/

**Comment by Schweinepriester** [comment]
- https://www.chromestatus.com/feature/5689159362543616
- https://bugs.chromium.org/p/chromium/issues/detail?id=1197594

**Comment by Schweinepriester** [comment]
It's coming, at least in Chrome: https://twitter.com/tomayac/status/1390584353596624897 🎉

**Comment by Schweinepriester** [comment]
Coming in WebKit:
- https://twitter.com/BenjaminCoe/status/1428099971371446277
- https://bugs.webkit.org/show_bug.cgi?id=229240

Firefox seems to be working on it: https://bugzilla.mozilla.org/show_bug.cgi?id=1723674

**Comment by mojoaxel** [comment]
I've created a draft pull requests for this: https://github.com/Fyrd/caniuse/pull/5998
Please feel free to comment to improve it!

**Comment by Schweinepriester** [comment]
Now in Safari TP 132 🎉

<https://webkit.org/blog/11971/release-notes-for-safari-technology-preview-132/>:

> Implemented `Crypto.randomUUID()` ([r281206](https://trac.webkit.org/changeset/281206/webkit/), [r281284](https://trac.webkit.org/changeset/281284/webkit/))

**Comment by mojoaxel** [comment]
It's available via MDN-BCD now: https://caniuse.com/mdn-api_crypto_randomuuid

**Comment by Fyrd** [comment]
Closing as per last comment.
