### ISSUE TITLE
Add Declarative Shadow DOM

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#5857]
- Spec: <https://github.com/mfreed7/declarative-shadow-dom>
- <https://www.chromestatus.com/feature/5191745052606464>
- Chrome 90: <https://developer.chrome.com/en/blog/new-in-chrome-90/#declarative>
- <https://web.dev/declarative-shadow-dom/>
- <https://css-tricks.com/platform-news-using-focus-visible-bbcs-new-typeface-declarative-shadow-doms-a11y-and-placeholders/#declarative-shadow-dom-could-help-popularize-style-encapsulation>

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/declarative-shadow-dom

**Comment by mfreed7** [comment]
Thank you! 🎉
