### ISSUE TITLE
Incorrect display of MDN browser compatibility

### ISSUE THREAD

**Issue by julianlambert** [Fyrd/caniuse#5860]
The caniuse page for [the html object tag](https://caniuse.com/mdn-html_elements_object) does not display the same data as [the MDN page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object) though they appear to use the same [JSON data](https://github.com/mdn/browser-compat-data/blob/main/html/elements/object.json).

I think the way caniuse is presenting the data is confusing and misleading. MDN is the only data source listed, but caniuse is presenting different data, so where is it coming from? Is it making it up? Or is it in caniuse's data.json?

**Comment by Schweinepriester** [comment]
It looks like `true` in the data is being mapped to supported only in current and future releases and previous releases as unknown, since the first version with support is not specified.

**Comment by Fyrd** [comment]
Indeed, as the `true` values don't indicate at what version support started there's no easy programmatic way to interpret it as anything but "supported in the current version, unknown support in previous versions".

I do agree it is a bit confusing, thankfully the MDN BCD folks are continuously working at replacing `true` values with the correct version number. This will result in better looking data on caniuse as well.

**Comment by Fyrd** [comment]
Closing this issue as per my last comment.
