### ISSUE TITLE
Add Safari 14.1

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#5867]
… since Safari on iOS 14.5 got its own entry and there appear to be differences to Safari 14 e.g.
- #5866
- #5775
- #5264

**Comment by natatkinson** [comment]
And safari now supports input=date! This is a big fucking deal!

**Comment by Schweinepriester** [comment]
@Fyrd has [added](https://github.com/Fyrd/caniuse/commit/499c067dc51b8141840847cc52ef365d92c05a73) 14.1, see e.g. <https://caniuse.com/input-datetime> 🎉

So I guess this can be closed? :)
