### ISSUE TITLE
Safari SpeechRecognition API

### ISSUE THREAD

**Issue by mishushakov** [Fyrd/caniuse#5879]
According to this bug, https://bugs.webkit.org/show_bug.cgi?id=225298#c3

> SpeechRecognition API is not available in SafariViewController and web apps added to Home Screen for now
> There are some implementation details we need to figure out before we can enable it.

please update the page to reflect that
https://caniuse.com/?search=speechrecognition

thanks

**Comment by Schweinepriester** [comment]
Most (49) of the entries found by <https://caniuse.com/?search=speechrecognition> are from MDN, so you'd have to open an issue over at <https://github.com/mdn/browser-compat-data> for those.

Then there's <https://caniuse.com/speech-recognition> where we could add a note I suppose (probably after #5873 is merged), but not sure how differences between Safari and the [Web Viewing Classes](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller#1845010) are handled generally. @Fyrd?
