### ISSUE TITLE
Microsoft Edge 91+ supports JPEG-XL

### ISSUE THREAD

**Issue by navjotjsingh** [Fyrd/caniuse#5880]
I couldn't find any official source but I have confirmed that Microsoft Edge Beta, Dev, and Canary (91+) support JPEG XL format. To enable it, you need to run the executable file with the parameter `--enable-features=JXL`.

https://caniuse.com/jpegxl

**Comment by atjn** [comment]
I have tested and can confirm that setting the runtime flag on Edge beta 91+ on Windows and Ubuntu works. Nice catch!
I guess it's easiest to just keep this issue open and have Fyrd add this note when he adds Edge 91 to the support table :)
