### ISSUE TITLE
missing data

### ISSUE THREAD

**Issue by hikeislife** [Fyrd/caniuse#5886]
There doesn't seem to be data for optional chaining in data.json file?!? it's there on the caniuse site, but not in the file

**Comment by Fyrd** [comment]
That feature, among many others, comes from the MDN browser compat data rather than the caniuse database. You can see the file at https://github.com/mdn/browser-compat-data/blob/main/javascript/operators/optional_chaining.json

**Comment by Fyrd** [comment]
Closing as per my last comment.
