### ISSUE TITLE
HLS HTTP Live Streaming info outdated?

### ISSUE THREAD

**Issue by Grovespaz** [Fyrd/caniuse#5905]
I'm opening an issue instead of a pull request because I want to be sure I'm not misunderstanding anything.
According to [caniuse](https://caniuse.com/?search=hls), HLS is not supported on Edge, Chrome and Firefox.

However, according to the linked [Wikipedia article](https://en.wikipedia.org/wiki/HTTP_Live_Streaming) to which it refers, HLS is supported with media source extensions on Chrome and FF (and presumable Edgium too?).
Almost every video platform, CDN, etc. seems to prefer to use HLS too, even for Chrome and Firefox clients.

Should that not warrant a "partial" indicator or a note?

**Comment by Fyrd** [comment]
Yes, using a library that utilizes media source extensions these browsers can support HLS. Lots of features could be considered supported using that logic however, plenty of JS libraries and polyfills exist that add support for technologies not supported natively.

I do agree that in this particular case support via a library is probably more acceptable than others, so we should definitely update the feature to note that the browsers with MSE support do have a way of supporting HLS as well. In fact we currently do this for [MPEG-DASH](https://caniuse.com/mpeg-dash) so we could re-use that same note.
