### ISSUE TITLE
Add 'spellcheck, autocorrect' attributes to website search input

### ISSUE THREAD

**Issue by gsteel** [Fyrd/caniuse#5922]
It would be great if the main search input on caniuse.com could have the attributes `autocorrect="off" autocapitalize="off" spellcheck="false"` appended.

I've noticed that Chrome checks spelling but does not auto-correct by default. Safari though, which I use a fair bit, autocorrects **all the goddamn time** and it's literally killing me 😭

Whilst I'm here… **thank you** to all those responsible for the excellent caniuse.com website!

**Comment by Fyrd** [comment]
Good idea. Have added the attributes, thanks for suggesting!
