### ISSUE TITLE
inset lists different compat data than MDN, despite claiming to fetch from MDN

### ISSUE THREAD

**Issue by LeaVerou** [Fyrd/caniuse#5930]
Safari 14.1 supports `inset`, MDN is correct: https://developer.mozilla.org/en-US/docs/Web/CSS/inset#browser_compatibility

However, caniuse does not include that: https://caniuse.com/mdn-css_properties_inset

Testcase: https://codepen.io/leaverou/pen/PopQWWp

I thought it may be a cache issue, but the MDN compat data has not been updated in over a month: https://github.com/mdn/browser-compat-data/blob/main/css/properties/inset.json

**Comment by Schweinepriester** [comment]
Hi @LeaVerou 🤩 

This is what I'm seeing:

![image](https://user-images.githubusercontent.com/2644614/120492296-3d04f300-c3ba-11eb-9907-2973201926c4.png)

Is that the correct state?

**Comment by LeaVerou** [comment]
Yes, it is. And now it looks correct to me too. Either I had a severe brain fart, or there was a temporary glitch. Either way, I'm closing this, thanks!
