### ISSUE TITLE
font-display?

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#5931]
I went to find the `font-display` table on Can I Use. And there isn't one. https://caniuse.com/?search=font-display

I started to think I should open an issue about adding it to Can I Use, but then realized oh, this is the kind of data that should now get pulled in from MDN. And MDN does have a compat table: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display

But somehow it doesn't render at Can I Use. Why is this data not migrating over?

**Comment by Schweinepriester** [comment]
> I went to find the `font-display` table on Can I Use. And there isn't one.

Technically there is one, from caniuse itself: <https://caniuse.com/css-font-rendering-controls>

Unfortunately only the description mentions `font-display`.
I'd be totally in favor of having `font-display` in the title as well. Could create a PR for that.

As for why the table from MDN is not showing up: I'm somewhat certain some tables from MDN are not shown if that feature is on caniuse already. But @Fyrd surely will clear that up 0:-)

**Comment by Fyrd** [comment]
Yes, that's correct. I think when `font-display` was originally introduced it was pretty experimental and it wasn't certain that property name would stay so I was a bit more cautious about the title. I'm fine renaming it at this point though.

**Comment by jensimmons** [comment]
Thanks!!
