### ISSUE TITLE
content-visibility duplicate?

### ISSUE THREAD

**Issue by Connum** [Fyrd/caniuse#5934]
There's currently "CSS content-visibility" https://caniuse.com/css-content-visibility
as well as "CSS property: content-visibility" https://caniuse.com/mdn-css_properties_content-visibility
They seem to share the same browser versions, except two differences in Opera Mobile and Samsung Internet.
If there is a difference, it should be made clear, otherwise, those two should be merged.

**Comment by Fyrd** [comment]
Thanks, have set the MDN one as a duplicate, should be removed in a few days.

**Comment by Fyrd** [comment]
Closing as per my last comment
