### ISSUE TITLE
two more duplicates: content-visibility and font-variant-numeric 

### ISSUE THREAD

**Issue by Connum** [Fyrd/caniuse#5936]
Hi,

I found two more duplicates that should be merged:

https://caniuse.com/font-variant-numeric / https://caniuse.com/mdn-css_properties_font-variant-numeric
https://caniuse.com/css-content-visibility / https://caniuse.com/mdn-css_properties_content-visibility

**Comment by Fyrd** [comment]
This has been fixed, only the caniuse one will show up in searches.
