### ISSUE TITLE
Add CSS module script/CSS modules

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#5944]
- https://github.com/WICG/webcomponents/blob/gh-pages/proposals/css-modules-v1-explainer.md
- https://github.com/whatwg/html/pull/4898/
- https://groups.google.com/a/chromium.org/g/blink-dev/c/iT0bQjzD04k/m/VkHPoOFLBAAJ
- Chrome 93: https://www.chromestatus.com/feature/5948572598009856
- https://bugs.chromium.org/p/chromium/issues/detail?id=992499
- https://github.com/mozilla/standards-positions/issues/541
- https://lists.webkit.org/pipermail/webkit-dev/2021-June/031901.html

**Comment by atjn** [comment]
Related: #5928

**Comment by o-t-w** [comment]
Chrome 123 added support for import attributes. Chrome already supported CSS module scripts but used a now deprecated syntax. Now that CSS module scripts work with the up-to-date syntax it seems like a good time to add this data to caniuse.
