### ISSUE TITLE
Enable inline code in the title of a feature or discourage backticks?

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#5947]
Looking at

- https://caniuse.com/css-font-rendering-controls
- https://caniuse.com/css-color-function

the backticks in the title aren't converted to inline code like in entries from MDN are, for example <https://caniuse.com/mdn-css_at-rules_media_range_syntax>.

Please consider enabling that or discouraging backticks in the title altogether.

Enabling might have to consider <https://caniuse.com/ciu/index> as well.
Currently not that nice:
![image](https://user-images.githubusercontent.com/2644614/121764042-fc874100-cb40-11eb-93fa-c07f992a586d.png)

---

If you're leaving this issue open for long term, please advise if I should remove the backticks from the two features for the time being :)

**Comment by Fyrd** [comment]
Yeah I meant to go back and remove them for css-font-rendering-controls as I also checked and realized they're not currently parsed as markdown. 
I think given that the the "title" values are probably used more in 3rd parties than other values like the description it should probably just be plaintext, so let's go with discouraging. Thanks for calling that out!

**Comment by Fyrd** [comment]
Went ahead and removed them for those two entries.

**Comment by Schweinepriester** [comment]
Alright, cool, closing as we're going with discouraging.
