### ISSUE TITLE
Do add Chromium to the list of browsers.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [Fyrd/caniuse#5949]
Please do add Chromium to the list of browsers, because I have experienced significant differences with Chrome and Chromium with their support of standards such as WebUSB, which are the exact type of differences that I visited your site for, but was not able to ascertain, because there is no option for pure Chromium.

![image](https://user-images.githubusercontent.com/42837531/121895062-59385680-cd0f-11eb-90fc-3829ef4a7f19.png)

**Comment by atjn** [comment]
Chromium supports WebUSB, which is why it is supported in Edge, Chrome, and Opera which are all based on Chromium.
I'm not sure I understand why it would be useful to track "pure Chromium" separately, since you cannot use Chromium directly, you have to build it and turn it into a browser first.

**Comment by Fyrd** [comment]
I agree with @atjn, if there's a particular browser using Chromium that does not support the API we can add a note, but don't see a need to add it as its own entry given the amount of Chromium browsers already tracked.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
http://github.com/Fyrd/caniuse/issues/5949#issuecomment-862733553

Although my example may have been rather poor, Chromium can be used as a browser. It is officially released nightly by its developers.

**Comment by atjn** [comment]
Alright, fair enough, but that is still a browser that has been build from Chromium, with certain options set while building. The final browser is just also called Chromium ;)
The page you link to, specifically mentions that it is mostly identical to Chrome releases, and that it should not be used for anything other than testing. If we were to track every niche browser (including the tens of different browsers out there called "Chromium"), we would need many more volunteers or much better funding, sorry :)
