### ISSUE TITLE
Add remaining predefined color spaces to CSS color() function test

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#5957]
Following #5956 I'd be nice to have the remaining predefined color spaces `srgb`, `a98-rgb`, `prophoto-rgb`, `rec2020`, and `xyz` from [the spec](https://drafts.csswg.org/css-color/#predefined) available to test at <https://tests.caniuse.com/css-color-function> in addition to the already present `display-p3` :)

Should only be copypasta. I'd do it myself… 0:-)

**Comment by Fyrd** [comment]
Good idea, done!
