### ISSUE TITLE
Chrome no longer supports plugin-types either

### ISSUE THREAD

**Issue by Sora2455** [Fyrd/caniuse#5960]
The Firefox support for https://caniuse.com/contentsecuritypolicy2 is listed as partial, because Firefox doesn't support plugin-types.

But support for plugin-types was removed from Chrome with the 90 release: https://www.chromestatus.com/feature/5742693948850176. Either Chrome's implementation needs to be marked as partial as well, or (my preference) Firefox's implementation needs to be marked as full.

**Comment by Fyrd** [comment]
Thanks! I agree, have updated accordingly.

**Comment by Sora2455** [comment]
Hi, this change seems to have been reverted? Firefox is again marked as partial for not supporting plugin-types.

**Comment by Sora2455** [comment]
@Fyrd Don't mean to necro or anything, but the fix for this bug was undone as per my last note.

**Comment by Fyrd** [comment]
@Sora2455 Sorry about that, fix is back in!
