### ISSUE TITLE
Add Entry for Temporal

### ISSUE THREAD

**Issue by Lonniebiz** [Fyrd/caniuse#5961]
Is it too early for caniuse to provide an entry for Temporal?

- https://tc39.es/proposal-temporal/docs/
- https://2ality.com/2021/06/temporal-api.html

**Comment by atjn** [comment]
It's a bit early, but for something as big as Temporal, I think it makes sense :)

**Comment by Lonniebiz** [comment]
Agreed. This isn't going away. The effort wouldn't be in vain. @atjn  Thanks.

**Comment by stevage** [comment]
Just came to caniuse.com to see what the status of Temporal was, so...yeah, there are users already. :)

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/temporal
