### ISSUE TITLE
Remove MDN entry for `:is()`

### ISSUE THREAD

**Issue by atjn** [Fyrd/caniuse#5963]
Caniuse seems to have duplicate entries for CSS `:is()`, so I'm thinking the MDN entry should be removed: https://caniuse.com/?search=%3Ais()

It just caused some confusion because the MDN table doesn't seem to be up to date: https://twitter.com/edwardakerboom/status/1411955740932251648

**Comment by Fyrd** [comment]
Have made the change, though it'll only take effect next time I update the MDN data. Thanks for pointing that out!

**Comment by atjn** [comment]
Seems like it has been removed on the site now 🥳
