### ISSUE TITLE
Display: shape

### ISSUE THREAD

**Issue by theanonymouskoder** [Fyrd/caniuse#5977]
when an element is rotated along the x and y axes, the depth is  0px by default. If display shape is used, then you would be able to set the depth. Other properties might also appear such as border-top-left-front-radius or border-top-left-color

**Comment by Ugoku** [comment]
Got a link of what you mean? `display: shape` [does not exist in the current spec](https://www.w3.org/TR/css-display-3/)

**Comment by theanonymouskoder** [comment]
@Ugoku  `display: shape` is the feature that I am suggesting. I am not saying that it exists.

**Comment by Fyrd** [comment]
@theanonymouskoder This repo is for existing technologies to have their support tracked on caniuse.com. If you'd like to propose a new CSS property to be added to browsers I recommend you look here:
https://www.w3.org/Style/CSS/current-work.en.html#contribute
