### ISSUE TITLE
PNG favicon support incorrect for Safari (for macOS) and Safari for iOS

### ISSUE THREAD

**Issue by jefferyto** [Fyrd/caniuse#5982]
Currently, the support table for [PNG favicons](https://caniuse.com/link-icon-png) says that all versions of (desktop) Safari support PNG favicons (always preferring ICO if available) and that all versions of Safari for iOS do not use favicons at all (but "may have alternative for bookmarks, etc.").

Safari 12 added a new "Show icons in tabs" option for both [macOS Mojave](https://www.macworld.com/article/231533/article-606.html) and [iOS 12](https://www.macworld.com/article/231560/ios-12-how-to-enable-favicons-site-icons-on-tabs-in-safari.html) so it appears both columns of the support table are incorrect.

(I would open a PR to fix this but I don't have the capacity right now to test ICO/PNG preference in Safari on both platforms.)

**Comment by atjn** [comment]
Thanks for the tip!
