### ISSUE TITLE
Opera Android gap property for Flexbox support

### ISSUE THREAD

**Issue by lukewarlow** [Fyrd/caniuse#5983]
Caniuse states that opera android doesn't support gap property for flexbox. But MDN shows it's been supported since version 60. https://developer.mozilla.org/en-US/docs/Web/CSS/gap#browser_compatibility

**Comment by Fyrd** [comment]
Yeah, there was some confusion for a bit since the Opera for Android version numbers used to match that on desktop, now it seems they're out of sync (64 on Android, 77 on desktop but both using Chromium 91). Has been corrected now.
