### ISSUE TITLE
Support for CSS Cascade Layers

### ISSUE THREAD

**Issue by mirisuzanne** [Fyrd/caniuse#6000]
It looks like both [Safari](https://bugs.webkit.org/attachment.cgi?id=436491&action=diff#a/Source/WTF/Scripts/Preferences/WebPreferencesExperimental.yaml_sec1) and [Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=1095765) are planning to release this [new feature](https://drafts.csswg.org/css-cascade-5/#layering) soon, behind experimental feature flags.

One Chrome caveat: 

> We will not implement the 'revert-layer' keyword due to its complexity and likely negative performance impact.

And one from Safari:

> This patch adds initial support for @layer rules, including both the block and the statement syntax. No support for @import or CSSOM yet but basic functionality mostly works.

The chrome issue seems to be intentional. The Safari issue looks temporary, so we'll have to see what lands.

**Comment by Schweinepriester** [comment]
Cool stuff, @mirisuzanne :)

<https://www.bram.us/2021/09/15/the-future-of-css-cascade-layers-css-at-layer/>

+1

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/css-cascade-layers
