### ISSUE TITLE
voice-* properties aren't listed

### ISSUE THREAD

**Issue by caluap** [Fyrd/caniuse#6003]
‘voice-family’, ‘voice-rate’, ‘voice-pitch’ etc.

**Comment by Malvoz** [comment]
The [Voice characteristic properties](https://drafts.csswg.org/css-speech-1/#voice-char-props) are defined in the CSS Speech Module, as such this issue is duplicate of https://github.com/Fyrd/caniuse/issues/1240.

**Comment by Fyrd** [comment]
Closing as per above.
