### ISSUE TITLE
Bug: Resources tab doesn't update correctly

### ISSUE THREAD

**Issue by AElmoznino** [Fyrd/caniuse#6005]
## Steps to reproduce:
1. Visit the start page (https://caniuse.com/)
2. Search for "container". Click Resources for the first result ("CSS Container Queries"). 6 resources for CSS Container queries show
3. Search for "grid". Click Resources. 9 resources (for Grid) show.
4. Search for "container" again. Click Resources for "CSS Container Queries".  It still shows the 9 resources for CSS Grid (the previous search's results).

## Expected behaviour: 
On step 4, the Resources for CSS Container Queries should show.

## Environment:
macOS Big Sur 11.4
Chrome 92.0.4515.159 (Official Build) (x86_64)

**Comment by Fyrd** [comment]
Thanks for catching! Found the issue and it should be fixed now. Can you confirm?

**Comment by AElmoznino** [comment]
Confirmed, works as expected now! 😄
