### ISSUE TITLE
Missing browser usage data for iOS in Switzerland

### ISSUE THREAD

**Issue by j-hoffmann** [Fyrd/caniuse#6009]
Usage data for Safari / Chrome on iOS devices seems to be missing. My screenshot below shows an example for browser versions 14.5 - 14.7, but all iOS versions are affected and are showing 0% for Switzerland. These numbers should be higher than global numbers since market share of iOS is generally higher in Switzerland. 

Numbers for other browsers, including Safari on macOS do not seem to be affected.

![caniuse-missing-usage-data-ios-switzerland](https://user-images.githubusercontent.com/20977786/131818889-210b2d2b-e1f7-44e5-a2a4-a97e15dc9820.png)

I cannot tell exactly when this started happening, but it must be at least a few days.

**Comment by Fyrd** [comment]
I believe this was recently fixed. Note that you may need to delete the current data then re-import.

**Comment by j-hoffmann** [comment]
Thank you. I thought I had done a reimport, but trying it now helped. Problem fixed.
