### ISSUE TITLE
add Large, Small, and Dynamic viewport units (lvh, lvw, svh, svw, dvh, dvw, etc...)

### ISSUE THREAD

**Issue by nstringham** [Fyrd/caniuse#6013]
I'm not super good at reading CSS drafts but it looks to me like this is something that is CSS level 4 and it would be cool if it was on caniuse
https://drafts.csswg.org/css-values-4/#viewport-variants

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/viewport-unit-variants

**Comment by nstringham** [comment]
Thanks
