### ISSUE TITLE
Web Locks API

### ISSUE THREAD

**Issue by ralphch0** [Fyrd/caniuse#6020]
See https://developer.mozilla.org/en-US/docs/Web/API/Web_Locks_API

**Comment by Schweinepriester** [comment]
Given the support tables on MDN, it's arguably already there albeit not that great to find:
- <https://caniuse.com/?search=LockManager>
- <https://caniuse.com/?search=Lock%20API> (disabling results from caniuse => first three results, matching <https://developer.mozilla.org/en-US/docs/Web/API/Lock#browser_compatibility>)

Previous issue: #4465

**Comment by ralphch0** [comment]
Oh I see. I searched for "web locks"

**Comment by Fyrd** [comment]
Added "web locks" as keyword now so https://caniuse.com/?search=web%20locks will return the appropriate results.
