### ISSUE TITLE
Add Eyedropper API to caniuse

### ISSUE THREAD

**Issue by mlabod** [Fyrd/caniuse#6049]
Chrome shipped the new Eyedropper API with Chrome version 95

Chrome status: https://chromestatus.com/feature/6304275594477568
Firefix status: https://github.com/mozilla/standards-positions/issues/557
Webkit (Safari) status:  https://lists.webkit.org/pipermail/webkit-dev/2021-July/031929.html

Official spec: https://wicg.github.io/eyedropper-api/

**Comment by Schweinepriester** [comment]
Available via MDN, <https://caniuse.com/?search=Eyedropper> esp. <https://caniuse.com/mdn-api_eyedropper>?

**Comment by Fyrd** [comment]
Closing as per last comment.
