### ISSUE TITLE
Add CSS @when/@else

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#6055]
- https://css-tricks.com/css-is-going-gosh-darned-hog-wild-i-tell-ya-what/#when
- https://tabatkins.github.io/specs/css-when-else/
- https://github.com/w3c/csswg-drafts/issues/112

**Comment by Schweinepriester** [comment]
Stolen from <https://www.bram.us/2021/12/27/css-in-2022/#experimental-support--when>:

> - Blink/Chromium: [Issue #1282896](https://bugs.chromium.org/p/chromium/issues/detail?id=1282896)
> - Gecko/Firefox: [Issue #1747727](https://bugzilla.mozilla.org/show_bug.cgi?id=1747727)
> - WebKit/Safari: [Issue #234701](https://bugs.webkit.org/show_bug.cgi?id=234701)

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/css-when-else

**Comment by Schweinepriester** [comment]
@Fyrd Great, thanks! :)

Just a heads up, it might be changed to `@if` instead of `@when`: https://github.com/w3c/csswg-drafts/issues/6684

And I know, normally you don't do that, but I really think if that were to happen we should rename the file 0:-)

**Comment by Fyrd** [comment]
@Schweinepriester Thanks! Yeah I saw there were discussions about it in another thread, but hadn't seen that one. Agree we can rename the file if it gets renamed later on.
