### ISSUE TITLE
Add Scoped Styles aka. CSS Scoping aka. @scope

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#6056]
- <https://css-tricks.com/css-is-going-gosh-darned-hog-wild-i-tell-ya-what/#scoping>
- <https://drafts.csswg.org/css-cascade-6/#scoped-styles>
- <https://css-tricks.com/early-days-for-css-scoping/>
- <https://css.oddbird.net/scope/syntax/>

(Not the same as <https://caniuse.com/style-scoped>)

**Comment by mirisuzanne** [comment]
I expect browsers to start prototyping this soon, but I don't think it's landed in any preview releases yet (if that's the criteria).

**Comment by keithjgrant** [comment]
Chrome has a demo of this behind a flag now and it seems like it might be making forward progress again

**Comment by matthew-dean** [comment]
Tracking bug is here: https://chromium-review.googlesource.com/c/chromium/src/+/4161741

**Comment by Eduruiz** [comment]
I'm using chromium-dev on linux and it's already there :)

**Comment by Schweinepriester** [comment]
- https://fullystacked.net/posts/scope-in-css/
- Shipping in Chrome 117: <https://chromestatus.com/feature/5100672734199808>
- Positive position for WebKit: <https://github.com/WebKit/standards-positions/issues/13>
- Firefox:
  - https://github.com/mozilla/standards-positions/issues/472
  - https://bugzilla.mozilla.org/show_bug.cgi?id=1830512

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/css-cascade-scope

**Comment by yisibl** [comment]
It is expected to ship in Chrome 118. https://chromium-review.googlesource.com/c/chromium/src/+/4790561

**Comment by bramus** [comment]
> It is expected to ship in Chrome 118. https://chromium-review.googlesource.com/c/chromium/src/+/4790561

That is correct, as per https://chromestatus.com/feature/5100672734199808
