### ISSUE TITLE
Add Object Chaining

### ISSUE THREAD

**Issue by PulapakuraBros** [Fyrd/caniuse#6059]
There is a thing in JS called object chaining. It looks like this:

```js
const person = {
    address: {
        street: 'Hello',
    },
};

console.log(person?.address?.street);
```

You can learn about it [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

**Comment by Fyrd** [comment]
Actually it's called "optional chaining" and is already on the site:
https://caniuse.com/?search=optional%20chaining :)
