### ISSUE TITLE
EXT_texture_compression_bptc support info not up-to-date

### ISSUE THREAD

**Issue by OptiStrat** [Fyrd/caniuse#6083]
EXT_texture_compression_bptc is reported to only be supported in Firefox, when it is apparently supported in Chrome as well.

To reproduce: visit [https://webglreport.com/?v=2](https://webglreport.com/?v=2) (or use gl.getSupportedExtensions())
=> EXT_texture_compression_bptc is listed as a supported extension in the environment below.

Environment:
- Chrome 95.0.4638.54
- OpenGL ES 3.1 Mesa 20.3.3
- CentOS 8.4.2105

**Comment by Schweinepriester** [comment]
I'm afraid that is a feature that comes from MDN, so the source is that repo: https://github.com/mdn/browser-compat-data/blob/main/api/EXT_texture_compression_bptc.json

**Comment by OptiStrat** [comment]
My bad! Thanks.
