### ISSUE TITLE
Safari 15.1 still not listed?

### ISSUE THREAD

**Issue by sylvaindubus** [Fyrd/caniuse#6085]
Hello there,

I work on a project where we heavily rely on caniuse (through browserslist) for particular features. Currently, using the latest version, Safari 15.1, which has been released two weeks ago is not listed yet.

I wonder how new versions are added to the list, and what is the average delay between a release and the support in caniuse.

Thanks!

**Comment by Schweinepriester** [comment]
> how new versions are added to the list

That part I can answer through <https://github.com/Fyrd/caniuse/blob/main/CONTRIBUTING.md#unsupported-changes>:

> Currently it is not possible to:
> 
> -   Add a new browser or browser version

=> Only @Fyrd can add new versions, either he just adds them or is reminded through issues like yours :)

Out of curiosity, can you go into detail how the missing Safari 15.1 is breaking/preventing you?

**Comment by sylvaindubus** [comment]
Oh right, I hope he will check this issue soon so!

> Out of curiosity, can you go into detail how the missing Safari 15.1 is breaking/preventing you?

In our app, we are using the browserslist to detect unsupported browsers and display an informative banner which kindly ask our users to update their browser. We rely on [caniuse-lite](https://www.npmjs.com/package/caniuse-lite) to get the corresponding detection regex. As Safari 15.1 is not listed yet, it is detected as an outdated browser. Probably that our solution is not optimal yet, but it seems convenient to have only one list to manage both Babel transpilation support and the display of this banner. Anyway we've found a workaround with `caniuse-lite` for now. :)

**Comment by Fyrd** [comment]
Safari 15.1 has now been added!
