### ISSUE TITLE
Text-based "deep links" of highlighted text

### ISSUE THREAD

**Issue by cmoog** [Fyrd/caniuse#6090]
This just landed in stable Chrome... what is the status of support in other browsers? Specifically, it allows linking directly to arbitrary page text using the url format demonstrated below. I haven't been able to find _anything_ suggesting this went through the normal proposal process, so I suppose the most reasonable thing to assume here is that it will remain Chrome-only for quite a while.

https://blog.google/products/chrome/more-helpful-chrome-throughout-your-workday/#:~:text=Link%20to%20your%20highlighted%20text

**Comment by Schweinepriester** [comment]
<https://caniuse.com/url-scroll-to-text-fragment>

Issue: #5102

**Comment by cmoog** [comment]
Oh whoops, my apologies. Closing this out. Thanks.
