### ISSUE TITLE
Add COLRv1

### ISSUE THREAD

**Issue by woody-li** [Fyrd/caniuse#6097]
OpenType 1.9 is available for public review for a two-week “beta” period, ending November 26, 2021. It contains COLR version 1.
https://docs.microsoft.com/en-us/typography/opentype/otspec190/ot190beta
https://github.com/googlefonts/colr-gradients-spec/

Chrome has implemented the feature in Chrome 98 Dev.
https://www.chromestatus.com/feature/5638148514119680

**Comment by yisibl** [comment]
I will do it.

**Comment by Schweinepriester** [comment]
https://docs.microsoft.com/en-us/typography/opentype/otspec190/ot190beta is 404 now
=> https://docs.microsoft.com/en-us/typography/opentype/spec/

https://developer.chrome.com/en/blog/colrv1-fonts/ is showing the greatness of COLRv1.

Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1740525
WebKit: https://bugs.webkit.org/show_bug.cgi?id=233496

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/colr-v1
