### ISSUE TITLE
About webgl2-compute?

### ISSUE THREAD

**Issue by engineer1109** [Fyrd/caniuse#6100]
No query for webgl2-compute?
deprecated?

**Comment by Schweinepriester** [comment]
Looks like it <https://www.khronos.org/registry/webgl/specs/latest/2.0-compute/>:

> The WebGL 2.0 Compute specification was a tremendous effort spearheaded by Intel to bring compute shader support to the web via the WebGL rendering context. During the development of this specification, the decision was made to halt further expansion of the WebGL API, and instead focus the contributors' efforts on the [WebGPU specification](https://gpuweb.github.io/gpuweb/).
>
> **For this reason, this specification should be considered obsolete.** The WebGL working group thanks all of the contributors to this specification for their tremendous efforts in specifying and implementing this significant potential addition to the WebGL API. **WebGPU will be the path forward for compute shaders on the web.**

=> <https://caniuse.com/webgpu>

**Comment by Fyrd** [comment]
Closing as per ^
