### ISSUE TITLE
Safari TP 136: `offset-path` and `contain` …maybe?

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#6102]
Not being able to test currently, therefore an issue and not a PR.

<https://webkit.org/blog/12137/release-notes-for-safari-technology-preview-136/>

> - Added support for `contain: paint` ([r285583](https://trac.webkit.org/changeset/285583/webkit/))
> …
> - Implemented parsing and animation support for `offset-path` ([r285343](https://trac.webkit.org/changeset/285343/webkit/))

So
- https://caniuse.com/css-containment => https://tests.caniuse.com/css-containment
- https://caniuse.com/css-motion-paths => https://tests.caniuse.com/css-motion-paths

`contain`:
Looking at https://bugs.webkit.org/show_bug.cgi?id=172026 more/all? values seem to have been implemented (before), but how to properly test that, e.g. on <https://wpt.fyi/results/>?

`offset-path`:
https://wpt.fyi/results/?label=master&label=experimental&aligned&q=offset-path

**Comment by Fyrd** [comment]
Thanks! Just tested and updated after confirming both. All values of CSS Containment _appear_ to be supported based on CSS.supports results but they're also still behind a flag.
