### ISSUE TITLE
background-clip: text is supported unprefixed in Safari 14 and later

### ISSUE THREAD

**Issue by devongovett** [Fyrd/caniuse#6106]
Related issue on MDN compat data: https://github.com/mdn/browser-compat-data/issues/13977

I tested in Safari 14.1 and Safari 15, and this value is supported unprefixed. Confirmed in Safari 13 that it was not supported.

**Comment by devongovett** [comment]
Example: https://codepen.io/devongovett/pen/OJxbQBZ

**Comment by Schweinepriester** [comment]
Confirmed using <https://tests.caniuse.com/background-clip-text>:

Safari 13:

![image](https://user-images.githubusercontent.com/2644614/145846896-c9aeb307-f7b4-4419-864b-c24b535a5b42.png)

Safari 14:

![image](https://user-images.githubusercontent.com/2644614/145846740-e0fe0a64-ad59-4806-b390-2535818e34a4.png)

I'll create the PR shortly, thanks!
