### ISSUE TITLE
Add Safari 15.2 and Safari on iOS 15.2

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#6107]
<https://webkit.org/blog/12140/new-webkit-features-in-safari-15-2/>

While the new features don't seem to be that many, it's still different enough from 15.1 to warrant it's own entry, right?

~~We also could wait for~~

> ~~For more on what's in Safari 15.2, including bug fixes, see the [Safari 15.2 Release Notes (coming soon.)](https://developer.apple.com/documentation/safari-release-notes/)~~

~~and decide then.~~

<https://developer.apple.com/documentation/safari-release-notes/safari-15_2-release-notes> is here, definitely it's own version, among others:

> Added support for the File System Access API for creating and iterating files in an origin-specific storage space.
> Added wide gamut support for canvas.
> Added support for COOP and COEP HTTP headers.
> Re-enabled `SharedArrayBuffer` for sites that use COOP and COEP securely to create an isolated environment.

---

Side note:
No changelog for 15.1 though oO :D
https://developer.apple.com/documentation/safari-release-notes/

**Comment by Fyrd** [comment]
Done!
