### ISSUE TITLE
Add oklab() and oklch()

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#6124]
- https://drafts.csswg.org/css-color-4/#specifying-oklab-oklch
- https://github.com/w3c/csswg-drafts/issues/6642
- https://bottosson.github.io/posts/oklab/
- Test: https://wpt.fyi/results/css/css-color?label=master&label=experimental&aligned&q=ok
- Safari:
   - Shipped in TP 137: https://webkit.org/blog/12156/release-notes-for-safari-technology-preview-137/
   - https://trac.webkit.org/changeset/286191/webkit/
   - https://bugs.webkit.org/show_bug.cgi?id=233507
- https://twitter.com/LeaVerou/status/1473319461218406400 🎉

**Comment by jensimmons** [comment]
I believe this shipped in Safari 15.4 beta. Getting confirmation.

**Comment by ai** [comment]
PostCSS Preset Env is planning to add `oklab` support and this data on Can I Use will be very helpful https://github.com/csstools/postcss-plugins/issues/225#issuecomment-1030597840

**Comment by verhovsky** [comment]
I'm able to use `oklab()` and `oklch()` on my Safari 15.4 on macOS 12.3.1

<img width="386" alt="Screen Shot 2022-04-21 at 10 38 14" src="https://user-images.githubusercontent.com/5687998/164518796-ab8dc91b-0f47-44cb-acfc-b5d7ebd427cb.png">

**Comment by LifeIsStrange** [comment]
some of the reason why this is useful: https://news.ycombinator.com/item?id=31107643

**Comment by Schweinepriester** [comment]
Almost certainly coming via MDN, thanks to @ai! 🎉 
- https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklab
- https://github.com/mdn/browser-compat-data/pull/16526
- https://github.com/mdn/content/pull/15033

**Comment by Schweinepriester** [comment]
Available now:
- https://caniuse.com/mdn-css_types_color_oklab
- https://caniuse.com/mdn-css_types_color_oklch

**Comment by jensimmons** [comment]
Why the warning labels? 
"This feature is experimental. Use caution before using in production."

I don't believe this should be said of either. The CSSWG has written the spec. It's in a shippable state. 

Of course web developers should take browser support into consideration. That's the whole purpose of Can I Use. They don't need to be told to think about browser support. 

Warnings like these make it sound like this is a temporary or dangerous technology that will most likely change over and over before it's useable. And that is not at all true.

**Comment by ai** [comment]
@jensimmons I send PR to MDN with `Experimental` tag removal https://github.com/mdn/content/pull/17502

If you have good reasons for removing Experimental warning, it will be a big help if you will write them there.

**Comment by Fyrd** [comment]
Closing as mentioned above, any further discussion necessary should happen on the MDN BCD side.
