### ISSUE TITLE
Bugs in data?

### ISSUE THREAD

**Issue by devongovett** [Fyrd/caniuse#6132]
When updating the data used by autoprefixer and `@parcel/css` some tests failed:

* `tab-size` - for some reason, Android Firefox 94 is marked as needing prefixes: https://caniuse.com/css3-tabsize. Looks like it happened in https://github.com/Fyrd/caniuse/commit/3440e6f9751fef46267bcbdf223fa7fe5845c9ee#diff-625786136c02808151987347b07b2cd2b4a83f32b841a0a52c5b60c1a2cb8c16. MDN says it has been supported since 91: https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size
* `:fullscreen` - Android Chrome 96 is marked as needing prefixes. According to MDN this has been supported since 71: https://developer.mozilla.org/en-US/docs/Web/CSS/:fullscreen

There could be more as well, but these were the ones caught by my tests. Perhaps something went wrong with the mobile equivalents of these browsers when updating the data?

**Comment by Fyrd** [comment]
Thanks, should be fixed now.

**Comment by devongovett** [comment]
Are you sure? For example looking at https://caniuse.com/es6-module shows that only the very latest version of Chrome for Android supports ES6 modules, which is definitely wrong. Same for Firefox and QQ. Something seems wrong with these mobile versions.

**Comment by devongovett** [comment]
Actually looking at that page, it seems caniuse thinks no version of Android Chrome even existed before 96?
