### ISSUE TITLE
Add font-palette

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#6137]
- Spec: https://www.w3.org/TR/css-fonts-4/#font-palette-prop
- Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1170794
- Safari TP 134: https://webkit.org/blog/12033/release-notes-for-safari-technology-preview-134/
- Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1461588

Closely related to `font-palette-values` (#4910) - could also elevate that one to cover `font-palette` as well (and then close this one).

**Comment by yisibl** [comment]
I will do it!

**Comment by jensimmons** [comment]
This is also supported in Safari 15.4: https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/css-font-palette
