### ISSUE TITLE
Redirect FLIF to JPEG XL

### ISSUE THREAD

**Issue by Crissov** [Fyrd/caniuse#6139]
FLIF had been proposed in #2254 and the "no support" notice is avialble at <https://caniuse.com/sr_flif>. However, the format has been subsumed by JPEG XL, support for which was requested in #5041 and is now available at <https://caniuse.com/jpegxl>.

Searching for FLIF (or FUIF or PIK) should redirect users to the JPEG XL entry.

**Comment by Schweinepriester** [comment]
<https://flif.info/#update>:

> FLIF development has stopped since FLIF is superseded by FUIF and then again by [JPEG XL](https://jpeg.org/jpegxl), which is based on a combination of [Pik](https://github.com/google/pik) and [FUIF](https://github.com/cloudinary/fuif). For more information, see [Jon's JXL info page](https://sneyers.info/jxl) or visit the [JPEG XL Discord server](https://discord.gg/DqkQgDRTFu).

+1 to adding a note to <https://caniuse.com/sr_flif> with a link to <https://caniuse.com/jpegxl>. Maybe also mentioning FUIF and PIK.

**Comment by Fyrd** [comment]
Thanks, have updated the entry as suggested!
