### ISSUE TITLE
Firefox 96 is being released + add Firefox 98

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#6142]
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/96

> Firefox 96 was released on January 11, 2022.

And please as usual add one more version of Firefox, 98, so #6141 can be merged 0:-)

**Comment by Fyrd** [comment]
Done!

**Comment by Schweinepriester** [comment]
@vanillajonathan 

Not for me:
![image](https://user-images.githubusercontent.com/2644614/161271890-9669015b-ba4d-43ca-bf62-ca114e5c0e01.png)

But you probably mean Firefox for Android, right?
