### ISSUE TITLE
README contact link points to "under construction" page

### ISSUE THREAD

**Issue by mshafer1** [Fyrd/caniuse#6155]
Hi, I've used caniuse.com a number of times and found it very helpful

 I was hoping to reach out about collaborating on a variant (probably using a sub-domain name), but the contact link in the README goes to an "Under construction" page on Deveria's site...
 
 Can this link be updated to a way to contact? (or the page be fixed...)

**Comment by Fyrd** [comment]
Ah, let me see what I can do about that

**Comment by Fyrd** [comment]
Should be working now!
