### ISSUE TITLE
Samsung Internet 16.0 not matching on Google Analytics import

### ISSUE THREAD

**Issue by andronocean** [Fyrd/caniuse#6156]
When I do a new Google Analytics import, `Samsung Internet 16` is under the list of browsers not included. Looks like it's a relatively new version, but it is pulling a little over 6% of my traffic currently.

I found [these release notes for it](https://medium.com/samsung-internet-dev/introducing-the-samsung-internet-16-0-beta-9ec45f1412c2) on the Samsung dev Medium blog, which say it includes the Chromium 92 web engine — so I expect feature support would match that.

Thank you as always — I don't see a way to add PRs for new browser versions, but if there is I'd be happy to help with that side of maintenance.

**Comment by Fyrd** [comment]
Thanks for the reminder! Have added Samsung Internet 16.
