### ISSUE TITLE
Add Safari & Safari on iOS 15.3 and 15.4 

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#6157]
@mkurz [triggered me](https://github.com/Fyrd/caniuse/pull/6148#issuecomment-1024089140) to check for Safari 15.3 and subsequently finding 15.4, so here is the old issue to add them both :)

I started to write there

> I only found https://support.apple.com/en-us/HT213058 so far regarding 15.3?
> I would assume Safari 15.3 is much as [iOS 15.3 more or less containing only fixes](https://support.apple.com/en-us/HT212788#153)…
> 
> Doesn't even have an entry on https://developer.apple.com/documentation/safari-release-notes (yet).
> 
> However, there's a juicy 15.4 beta there! 🤯🤩
> => https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes

So as of now I would suggest adding 15.3 as a combined entry to 15.2 and adding 15.4 as it's own version :)

---

Not sure what is better regarding 15.4 - adding it right now or waiting until it's released 🤔 
Maybe we'll be blessed with a post on webkit.org telling us which versions of TP are included [like 15](https://webkit.org/blog/11989/new-webkit-features-in-safari-15/) to deduce what should work.

> Changes in this release of Safari were included in the following Safari Technology Preview releases: [123](https://webkit.org/blog/11585/release-notes-for-safari-technology-preview-123/), [124](https://webkit.org/blog/11672/release-notes-for-safari-technology-preview-124/), [125](https://webkit.org/blog/11680/release-notes-for-safari-technology-preview-125/), [126](https://webkit.org/blog/11727/release-notes-for-safari-technology-preview-126-with-safari-15-features/), [127](https://webkit.org/blog/11736/release-notes-for-safari-technology-preview-127/), [128](https://webkit.org/blog/11925/release-notes-for-safari-technology-preview-128/), [129](https://webkit.org/blog/11951/release-notes-for-safari-technology-preview-129/).

Didn't get that for [15.2](https://webkit.org/blog/12140/new-webkit-features-in-safari-15-2/) and as of now don't have posts for 15.1 and 15.4.

But then again TP 139 really felt like a polishing release with all those [fixes in the changelog](https://webkit.org/blog/12193/release-notes-for-safari-technology-preview-139/), and I think was [reporting as 15.4](https://www.macrumors.com/2022/01/26/apple-releases-safari-technology-preview-139/).
Also 15.4 has `:focus-visible` enabled like [TP 138](https://webkit.org/blog/12176/release-notes-for-safari-technology-preview-138/) (🎉).

Sooo maybe it would be easiest to have the current state of TP be 15.4?
… I guess in the end testing is the way to go anyway :D

**Comment by Fyrd** [comment]
Done as suggested! For now it's just the support just copies 15.2, hopefully we'll find out soon which TP features make it in.

**Comment by Schweinepriester** [comment]
@Fyrd Ah, 15.4 is a copy of 15.2/15.3 currently?
Would most likely be easier if 15.4 were a copy of the current TP (before the next TP is released and changes applied), because I would be somewhat confident and optimistic that at the time of writing 15.4 pretty much matches TP (139)… 0:-)

**Comment by Fyrd** [comment]
@Schweinepriester I've been informed a PR from an official source is imminent, so given that I thought I'd avoid making any assumptions. If for whatever reason that doesn't happen in the next few days we'll go back to making assumptions. :)

**Comment by Schweinepriester** [comment]
Check, nice 📈! :) 

![](https://i.giphy.com/media/xT9DPr4VjeCgeiLoMo/giphy.gif)

**Comment by Schweinepriester** [comment]
Gets even juicer 👀 
- https://twitter.com/firt/status/1488060229921218561
- https://firt.dev/ios-15.4b
