### ISSUE TITLE
TouchEvent API: touches

### ISSUE THREAD

**Issue by strarsis** [Fyrd/caniuse#6169]
According to the [Apple Developer Documentation](https://developer.apple.com/documentation/webkitjs/touchevent/1632644-touches) the `touches` property of `TouchEvent`s are supported by 
- Safari Desktop 10.1+
- Safari Mobile 2.0+

[caniuse lists Safari (Desktop) as unsupporting](https://caniuse.com/mdn-api_touchevent_touches)

Is my interpretation correct? Webkit is the engine Safari Desktop/Mobile uses, so the documentation should apply.

The documentation also covers a lot of other features, so it could be used to populate caniuse with even more support information.

**Comment by Fyrd** [comment]
The data for that particular table comes from [MDN BCD](https://github.com/mdn/browser-compat-data/blob/main/api/TouchEvent.json) FYI, though my guess is the reason it's considered unsupported is because outside of iOS devices Safari only runs on non-touchscreen devices (Macs do not currently have touch screens). So no touch screen, no TouchEvent API.

**Comment by strarsis** [comment]
@Fyrd: Good point. But what if a a device with touchscreen capabilities is connected to a Mac?
Then the browser would indeed support touch. Touch screens can be bought for Macs (e.g. https://www.amazon.com/Mac-Compatible-Touchscreen-Monitor/s?k=Mac+Compatible+Touchscreen+Monitor).
Would this be reason enough to consider this feature supported? It is supported on browser-level - probably also on OS and hardware level - just the hardware is rare for it.

**Comment by Fyrd** [comment]
Ah, that's true. Not entirely convinced that guarantees the events would work as expected though, that still depends on whether the OS & browser pipe through the appropriate touch data in the first place.

Either way, can't fix that on the caniuse side so I'll close this issue, feel free to bring it up at the MDN browser-compat-data repo.
