### ISSUE TITLE
Safari 15.2 and 15.3 not recognized on Google Analytics import

### ISSUE THREAD

**Issue by andronocean** [Fyrd/caniuse#6190]
Howdy :)

Not a big deal, but it looks like these two versions of _desktop_ Safari aren't making it into the stats when I import from GA:

<img width="940" alt="Screen Shot 2022-03-02 at 9 31 20 AM" src="https://user-images.githubusercontent.com/26490481/156382280-f3140a68-9308-4f4a-a0d5-692ab9d270a8.png">

**Comment by Fyrd** [comment]
Thanks for reporting! Should be fixed now, can you try again?

**Comment by andronocean** [comment]
Works perfectly now! Many thanks 👍
