### ISSUE TITLE
Add CSS Custom Highlight API?

### ISSUE THREAD

**Issue by karlhorky** [Fyrd/caniuse#6193]
Hi there! First of all, thanks so much for caniuse, it's such an amazing resource! 🙌

The CSS Custom Highlight API seems to be absent from the data, could it be included?

- https://www.w3.org/TR/css-highlight-api-1/
- https://chromestatus.com/feature/5436441440026624
- https://css-tricks.com/css-custom-highlight-api-early-loo/

**Comment by Schweinepriester** [comment]
Duplicate of #6147.

https://css-tricks.com/css-custom-highlight-api-early-loo/ is missing there though, if you'd like to add that link :)

**Comment by karlhorky** [comment]
Ah I searched but somehow didn't find that one! Closing in favor of #6147. I've commented over there that the CSS Tricks URL can be added.
