### ISSUE TITLE
Add customizable select element, currently `<selectlist>` (previously `<selectmenu>`)

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#6194]
- https://css-tricks.com/the-selectmenu-element/
- https://open-ui.org/prototypes/selectmenu
- https://open-ui.org/components/select
- https://chromestatus.com/feature/5737365999976448

> Based on the [select](https://open-ui.org/components/select) proposal, the implementation of a new `<selectmenu>` control has started in [Chromium](https://chromestatus.com/feature/5737365999976448). This control is available in Chromium-based browsers by enabling the Experimental Web Platform features experiment in about:flags.

**Comment by Schweinepriester** [comment]
https://hidde.blog/custom-select-with-selectmenu/

**Comment by BellemareMederic** [comment]
look like im to mutch up-to-date ^^. but yes selectmenu will change that ugly custom dropdown with javascript implementation ! waiting for it.

**Comment by rodenacker** [comment]
https://microsoftedge.github.io/Demos/selectmenu/

**Comment by tomByrer** [comment]
Mentioned in GoogleI/O
https://youtu.be/buChHSdsF9A?t=761

**Comment by Ugoku** [comment]
> `selectmenu` will probably be renamed to something else. Discussion is ongoing here: [openui/open-ui#773](https://github.com/openui/open-ui/issues/773)

[It has been renamed](https://github.com/openui/open-ui/issues/773#issuecomment-1664421419) to `<selectlist>`

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/selectlist
