### ISSUE TITLE
[backlog] Safari technical preview 141

### ISSUE THREAD

**Issue by LifeIsStrange** [Fyrd/caniuse#6195]
https://developer.apple.com/safari/technology-preview/release-notes/
from a quick glance:
Enabled support for overflow: clip ([r288973](https://trac.webkit.org/changeset/288973/webkit/))
Implemented CSS overscroll-behavior for asynchronous scrolling on macOS ([r288777](https://trac.webkit.org/changeset/288777/webkit/))

Added support for the WASM branch hinting proposal ([r288758](https://trac.webkit.org/changeset/288758/webkit/), [r288761](https://trac.webkit.org/changeset/288761/webkit/))
Added support for the import assertion syntax behind a flag ([r288473](https://trac.webkit.org/changeset/288473/webkit/))

Implemented AbortSignal.timeout() ([r289058](https://trac.webkit.org/changeset/289058/webkit/))

Implemented wasm-unsafe-eval ([r289022](https://trac.webkit.org/changeset/289022/webkit/))

**Comment by Schweinepriester** [comment]
on my radar 0:-)

**Comment by Schweinepriester** [comment]
I've created #6198 for [`overscroll-behavior`](https://caniuse.com/css-overscroll-behavior), but unfortunately for caniuse nothing really changed yet (they put work in obviously, but it was experimental already and it remains behind a flag for a bit).

[`overflow: clip`](https://caniuse.com/css-overflow) was already changed in #6008, perhaps incorrectly, but it's already in the state it should be now (also didn't bleed over to other versions).

Checked https://webkit.org/blog/12434/release-notes-for-safari-technology-preview-141/ and your list again, but I think the rest isn't on caniuse - perhaps yet, in which case the changes would best be put in the respective issues - or comes via MDN, therefore I think this issue can be closed 0:-)

**Comment by jensimmons** [comment]
I agree that this can be closed, because everything from STP141 is already on Can I Use. (The current Safari Technology Preview is version 146).
