### ISSUE TITLE
Add Node.js into the support matrix

### ISSUE THREAD

**Issue by vicary** [Fyrd/caniuse#6203]
I don't know if `browser-compat-data` has it yet, but since MDN included Node.js in their [Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility) matrix for quite some time now. I find myself regularly looking up for Node.js related info.

Is it possible to add Node.js in caniuse.com too?

**Comment by Schweinepriester** [comment]
Duplicate of #2361. Feel free to add your vote there, though :)

You probably know already, but for time being there is:
- https://kangax.github.io/compat-table/es6/
- https://node.green/

**Comment by vicary** [comment]
Thanks, I am closing this for duplication. It's sad that the mindset of scope control halted a genuine user need for 6 whole years.
