### ISSUE TITLE
clip-path data incorrect for Safari?

### ISSUE THREAD

**Issue by devongovett** [Fyrd/caniuse#6209]
Data for the clip-path property indicates that prefixes are needed for Safari: https://caniuse.com/css-clip-path. However, this does not appear to be the case. The examples on MDN all appear to render fine, and MDN's browser support table shows that Safari has supported this unprefixed since version 9.1: https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path. Is there a reason why it is still marked as needing prefixes in caniuse?

**Comment by Fyrd** [comment]
Good point, according to my tests unprefixed support started in 13.1. Have updated the data accordingly. Thanks!
