### ISSUE TITLE
Add `::theme`

### ISSUE THREAD

**Issue by matthew-dean** [Fyrd/caniuse#6211]
**Explanation**: `::part` and `::theme` are defined together in the spec, but it looks like `::part` is the only one listed in CanIUse. I think this is somewhat complicated because IIRC, Chrome's initial implementation was of `::part` but _not_ `::theme`? (Unless someone can correct me?) If that's the case, it makes sense to separately list both.

See:
https://github.com/fergald/docs/blob/master/explainers/css-shadow-parts-1.md
https://developer.mozilla.org/en-US/docs/Web/CSS/::part

**Comment by Fyrd** [comment]
Looks like `::theme` was removed from the specification and isn't supported in any browser. See [here](https://github.com/fergald/docs/issues/4#issuecomment-620037154) for a bit more information.

**Comment by matthew-dean** [comment]
Oh! Weird. MDN still links to that explainer. Oh well, thanks!
