### ISSUE TITLE
Add "fetchpriority"

### ISSUE THREAD

**Issue by jrcarb** [Fyrd/caniuse#6213]
Addition of "fetchpriority" attribute for load speed optimization 

- https://web.dev/priority-hints/
- https://wicg.github.io/priority-hints/
- https://chromestatus.com/feature/5273474901737472

**Comment by Schweinepriester** [comment]
fetchpriority seems to be available via MDN now: https://caniuse.com/?search=fetchpriority

**Comment by Fyrd** [comment]
Closing as per last comment.
