### ISSUE TITLE
U2F API deprecated in Chrome v. 98

### ISSUE THREAD

**Issue by ph00lt0** [Fyrd/caniuse#6217]
Please update the website a like.

Would be good to add distinction between the standards by adding FIDO2/WebAuthm API to the website separately. Currently only U2F API is mentioned which has stopped working.

https://www.yubico.com/blog/google-chrome-u2f-api-decommission-what-the-change-means-for-your-users-and-how-to-prepare/

**Comment by ph00lt0** [comment]
@Schweinepriester correct! 

I didn't find that page earlier, it should also show up under [webauthm](https://caniuse.com/?search=webauthm&static=1) probably.

**Comment by Schweinepriester** [comment]
Well, it does already show up for https://caniuse.com/?search=webauthn - but I got to ask, since you keep mentioning it with m at the end: Isn't it just webauthn, with n?

**Comment by ph00lt0** [comment]
@Schweinepriester oh excuse for the consistent typo, my bad.

**Comment by Schweinepriester** [comment]
Didn't manage to create a PR just yet, but some links for now:
- https://developer.chrome.com/origintrials/#/view_trial/-6366963973195038719
- https://chromestatus.com/feature/5759004926017536
- https://chromeenterprise.google/intl/en/policies/#U2fSecurityKeyApiEnabled
