### ISSUE TITLE
Add Model element

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#6227]
I'd like to request the addition of a page for the `<model>` element. 

Much like the `img`, `audio`, and `video` elements, the `model` element provides a way to embed 3D models into a web page. This code example demonstrates how a `.usdz` file can be shown on a webpage, with a video files as fallbacks. The `.usdz` file is a format for 3D geometric data.

```
<model style="width: 400px; height: 300px">
    <source src="assets/example.usdz" type="model/vnd.usdz+zip">
    <picture>
        <source src="animated-version.mp4" type="video/mp4">
        <source src="animated-version.webp" type="image/webp">
        <img src="animated-version.gif"/>
    </picture>
</model>
```
Full explainer: https://github.com/WebKit/explainers/tree/main/model

As of April 2022, support for `<model>` is in Safari Technology Preview behind a flag.

**Comment by Schweinepriester** [comment]
Hi Jen 👋
Really excited about `<model>`, but I'm sorry to say this is a duplicate of #6121.
Good summary though, maybe you'd like to bring that over? :)

**Comment by jensimmons** [comment]
Ah, right. I should have searched to see if someone else had already filed an issue. Oh, look, I'd commented on it... dang memory loss. Thanks. I'll comment there and close this.
