### ISSUE TITLE
Safari Technology Preview 143

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#6229]
We just released Safari Technology Preview 143:
https://webkit.org/blog/12563/release-notes-for-safari-technology-preview-143/

**Comment by Schweinepriester** [comment]
Cool stuff in there! 🎉 

Besides

- https://github.com/Fyrd/caniuse/pull/6230
- https://github.com/Fyrd/caniuse/issues/6182#issuecomment-1092203296
- https://github.com/Fyrd/caniuse/issues/6054#issuecomment-1092534818

anything left to add for caniuse? :)

If not, I would think this issue can be closed as a success? :)

**Comment by Fyrd** [comment]
Closing this ticket, any other specific changes/features can be added separately.
