### ISSUE TITLE
Firefox 99 was released and please add Firefox 101…

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#6237]
… so #6236 can be merged (tomorrow, after the next nightly) 0:-)

- <https://www.mozilla.org/en-US/firefox/99.0/releasenotes/>
- <https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/99>

> Firefox 99 was released on April 5, 2022.

As well as #6238, once Firefox for/on Android is at 99 B-)

**Comment by Fyrd** [comment]
Done!
