### ISSUE TITLE
Email Subscriptions for New Features

### ISSUE THREAD

**Issue by FlorianWendelborn** [Fyrd/caniuse#6239]
The [news section](https://caniuse.com/ciu/news) contains a lot of information that could help staying up-to-date with new developments in Web APIs.

It would be a nice addition if users could subscribe to it and get notified via email.

**Comment by Fyrd** [comment]
There's an [RSS feed](https://en.wikipedia.org/wiki/RSS) at https://caniuse.com/feed with that news, you can use a feed reader for that or look for RSS to email tools if you'd prefer it as email. :)

**Comment by Fyrd** [comment]
Closing as per my last comment
