### ISSUE TITLE
Remove doiuse.herokuapp.com in caniuse.com homepage

### ISSUE THREAD

**Issue by liyuhang1997** [Fyrd/caniuse#6241]
The [wiki page removed this site](https://github.com/Fyrd/caniuse/wiki/Third-party-tools/_compare/b355c048e95f94ef9f4cf484a97f38350dbfeaf8), but the [caniuse.com](https://caniuse.com/) home page still exists for this site.

**Comment by Fyrd** [comment]
Thanks, I've updated the link to point to the github repo instead.
