### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by TheNPCFISH** [Fyrd/caniuse#6242]
So I have a suggestion: support for custom elements.
Because you can make custom elements in JavaScript. 😄

**Comment by Schweinepriester** [comment]
Isn't that already covered by <https://caniuse.com/?search=custom%20elements>, esp. <https://caniuse.com/custom-elementsv1>? Or do you mean something else?

**Comment by TheNPCFISH** [comment]
Thank you!
