### ISSUE TITLE
Consider moving the IE column to the far right to diminish its importance

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#6247]
Internet Explorer is almost at its official end of life:
> the **Internet Explorer 11 desktop application will be retired and go out of support on June 15, 2022**, for certain versions of Windows 10. — https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/

Now, of course some web developers will still have to support Internet Explorer, so I do not suggest removing IE support data completely. But the current design emphasizes IE as a very important browser by listing it first. It definitely deserved this placement when Can I Use was started. But now it does not. 

I suggest no longer listing IE first. Perhaps it should be listed last — where people need to scroll sideways to get to it. Or perhaps last among the desktop browsers. Or maybe not at all until a checkbox is checked, since Microsoft itself is retiring support (and then once it appears, put it last among desktop browsers).

We need web developers to consider other browsers more. Samsung Internet has a 3% market share, Opera Mini has 1.04%, UC Browser has .83%, and Opera desktop has .80% — while IE has only .65%. Yet, IE support is much more prominently displayed. Which only helps to promote the antiquated but incessant idea that web technology cannot be used because it's not supported by IE. Meanwhile, too many developers never think about the other browsers I just listed.

**Comment by Schweinepriester** [comment]
I like this combination:
> I suggest no longer listing IE first. … Or perhaps last among the desktop browsers.

I wouldn't hide it manually but rather hope that this old bane somewhat soon slips under the default visible "> 0.5 % usage".

---

Random unweighted thoughts along the way:
- Ordering (desktop) browsers by name probably would be 'fairest', naturally moving IE to the right
- I like the grouping of browsers by desktop and mobile
- Making "Browser order: By usage" default would be (probably) fast and easy while achieving pretty much all that is mentioned here, for example (<https://caniuse.com/css-font-palette>):
   ![image](https://user-images.githubusercontent.com/2644614/164995707-bb173026-04dd-4906-a9c7-635022fc4ab1.png)
   - though the tables don't look nice then (to me)
   - and potentially shift around 'more often' (which could be countered by taking a longer period of time into account or semi-manually shifting around)

**Comment by Fyrd** [comment]
Yup, I agree it's time to change. My current plan is to update the default order roughly by usage, still keeping desktop & mobile separate. Here's what I had planned:

<img width="1177" alt="Screen Shot 2022-04-25 at 10 28 56 PM" src="https://user-images.githubusercontent.com/432336/165228202-95bb041a-e00a-440c-a090-5a72071445d2.png">

Having a fixed order is indeed still preferable to always based on usage as that can vary depending on the usage source used and in general it seems valuable for folks to be used to a certain order.

Worth noting is that the default view is "All" so all browsers tracked are included regardless of usage. Some time ago "Filtered" was the default which would result in IE eventually disappearing. I switched to "All" as default because it wasn't obvious to new visitors why various older versions weren't visible and why some browsers weren't included. Open to suggestions on another solution there. :)

**Comment by jensimmons** [comment]
I really like the design you have. Although, maybe swap Firefox and Safari in the desktop order, so it's:

`| Chrome || Safari | `

in the first two columns for both desktop and mobile.

**Comment by AnthonyLenglet** [comment]
about the order, what about ordering it relative to their usage, split between web and mobile ?

something like
Chrome | Safari | Edge | Firefox | ... | Chrome Android | Safari iOS | Samsung Internet | ...

**Comment by Fyrd** [comment]
Alright, the updated order is now live on the site. Ultimately the order I went with was based on the current snapshot of global usage from the past 3 months. As mentioned I think there's value to not changing this order too regularly so I won't change it the moment that changes, but perhaps every couple of years it may be worth revisiting.

Thanks everyone! If this change somehow caused any bugs please let me know.

**Comment by jensimmons** [comment]
Thanks!! And congratulations. It looks fantastic. A momentous occasion — diminishing the centrality of Internet Explorer. 

Not rearranging the order for every small change to browser stats is definitely the right thing to do. Keeping things in the same place is important for the usability of the site. 

By the way, for anyone reading this and contemplating browser statics — many of the trackers used to measure browser usage are often blocked by tracking protection efforts. So the count is likely more & more skewed over time, as a subset of browsers focus on stronger & stronger measures to protect privacy. 

Progressive enhancement and coding for all browsers is key.

**Comment by julian-alarcon** [comment]
Ok. It's been already 2 years. Now it is time to remove Internet Explorer and Opera Mini.
