### ISSUE TITLE
Multi-Screen Window Placement API

### ISSUE THREAD

**Issue by maxdaniel98** [Fyrd/caniuse#6259]
Google has proposed a new Multi-Screen Window Placement API. 

The draft is available here: https://w3c.github.io/window-placement/

The API is working in Chrome version 100.

**Comment by Schweinepriester** [comment]
Duplicate of #6006.

Excited for that, though!

**Comment by maxdaniel98** [comment]
Whoops, guess I missed that 😅
Excited too, will close this one.
