### ISSUE TITLE
Add Safari & Safari on iOS 15.5

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#6274]
https://webkit.org/blog/12669/new-webkit-features-in-safari-15-5/

There‘s at least 3 functional changes, see top of the article, plus more being discovered (https://twitter.com/dannymoerkerke/status/1526526459573149697), which is why I’m arguing for independent version :)

**Comment by andronocean** [comment]
A little note that 15.5 isn't getting picked up by the Google Analytics importer, either.

**Comment by Fyrd** [comment]
These were added, importer should work as expected too. Let me know if not.
