### ISSUE TITLE
Add Safari & Safari on iOS 16

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#6287]
… same procedure as every year, the obligatory issue 🙃

- https://webkit.org/blog/12824/news-from-wwdc-webkit-features-in-safari-16-beta/
- https://developer.apple.com/documentation/safari-release-notes/safari-16-release-notes
- Web Push: https://twitter.com/tomayac/status/1533918015116529664 🎉

**Comment by Fyrd** [comment]
Thanks, added! Have updated it with the main features mentioned though may have missed some.

**Comment by jensimmons** [comment]
Thank you both!!!
