### ISSUE TITLE
Add support for webcontainers

### ISSUE THREAD

**Issue by RichardWilburn** [Fyrd/caniuse#6289]
It may be useful to support this emerging feature "Web containers":

- Webcontainers appear to allow nodejs style webservers to run in a clients browser in a docker style way.
- The browsers that support this appear to be detailed here for now: https://developer.stackblitz.com/docs/platform/browser-support/
- The feature description for stackblitz and how they use it is detailed here: https://blog.stackblitz.com/posts/introducing-webcontainers/

Safari info:

- https://twitter.com/ericsimons40/status/1470819238248026114

Background info on webcontainers:

- https://news.ycombinator.com/item?id=27223012

**Comment by Schweinepriester** [comment]
But WebContainer appears to be a product built on top of web tech and not a browser feature (e.g. defined by a spec), right?

If the answer is yes, then it wouldn't really be a fit for caniuse, besides a search result with a link.

**Comment by RichardWilburn** [comment]
Fair point; it does look that way. My confusion was likely as I had seen it elsewhere too; but they likely built it too
