### ISSUE TITLE
List compatibility with SharedArrayBuffer (WebAssembly threads stuff)

### ISSUE THREAD

**Issue by cschneider4711** [Fyrd/caniuse#6290]
See the discussion around the enabling + spectre-vulnerability-based disabling + re-enabling at:
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer
* https://stackoverflow.com/questions/59550963/multithreading-in-webassembly

General background info:
* https://web.dev/wasm-threads/
* https://web.dev/webassembly-threads/

**Comment by Schweinepriester** [comment]
I'm excited for WebAssembly threads as well, but is there something missing on https://caniuse.com/sharedarraybuffer and/or not covered by #5200 (feel free to add your links there!)?

**Comment by cschneider4711** [comment]
Wow, already there... Have missed (typo?) it from testing (just tried it before creating this issue but must have misspelled something as no results then)...But yeah, it's already done, therefore issue closed ;) thx!
