### ISSUE TITLE
Order of Safari 16.0 and TP flipped

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#6296]
In https://github.com/Fyrd/caniuse/commit/439a5259078b1a99b81dc09c58910a16d278a93f you seem to have flipped the order of Safari 16.0 and TP 😱

Or is intentional...?

**Comment by Fyrd** [comment]
Whoops, yeah that was unintentional. Flipped back around now, thanks for noticing!

**Comment by Schweinepriester** [comment]
Great! :)
