### ISSUE TITLE
css `:has()` to be available in chrome 105

### ISSUE THREAD

**Issue by AnthonyLenglet** [Fyrd/caniuse#6306]
https://chromestatus.com/feature/5794378545102848

feature is currently available under the `#enable-experimental-web-platform-features` flag on the latest chrome dev build

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/36004334/172818018-daac04aa-8631-4a84-9779-40dff26e08e1.png">

**Comment by Schweinepriester** [comment]
But that's already on <https://caniuse.com/css-has>? Or am I missing something? 🤔

**Comment by AnthonyLenglet** [comment]
> But that's already on [caniuse.com/css-has](https://caniuse.com/css-has)? Or am I missing something? 🤔

the chrome 105 availability isn't noted yet, I don't know if its worth adding now or if its better to wait until more info comes out before adding it

**Comment by Schweinepriester** [comment]
Ah, now I get it, looking at
- https://chromestatus.com/feature/5794378545102848 (you linked that of course)
- https://twitter.com/intenttoship/status/1526135259355652096
- https://groups.google.com/a/chromium.org/g/blink-dev/c/bRsbl3wLuyk/m/mt3iSKNHBQAJ

It's going to be enabled by default in Chrome 105 (or that's the plan) 🎉
I'm creating a PR :)
