### ISSUE TITLE
Add Safari 15.6 on macOS and iOS

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#6310]
Safari 15.6 is in beta. So it can be added as a future release of Safari. 

https://developer.apple.com/documentation/safari-release-notes/safari-15_6-release-notes

**Comment by jensimmons** [comment]
But do this _after_ pulling in all the PRs I just made today! :P

**Comment by Fyrd** [comment]
If the version of WebKit is largely the same but with a few bug fixes I'll probably just combine it with 15.5 as done in the past. Unless you know of any specific feature support that would be different in this version?

**Comment by jensimmons** [comment]
Correct, we don't expect there to be any major features in Safari 15.6. It's a release that's about stability and fixes. Safari 15.6 beta release notes: https://developer.apple.com/documentation/safari-release-notes/safari-15_6-release-notes

When you "combine it with 15.5" — will the data table still show 15.5 as the current version, and 15.6 (along with 16.0 and STP) as future versions? ....Until 15.6 ships. And then show 15.6 as the current version, with 15.5 in the past, and 16.0 in the future… And then once 16.0 ships, _then_ combine 15.5 and 15.6?

If so, I think that works well. 

It do think it's important for web developers to be able to see which version is current (15.5, 15.6, or 16.0) and to realize these separate releases exist. I'd hate for "15.5–15.6" to be the "current version" for two cycles, stuck together all the time.

**Comment by Fyrd** [comment]
Just like minor version updates, if the engine is effectively the same to developers I've always combined the versions once the newer one is released. In the UI it will just show the latest one of the two to avoid confusion as to which is the "current" one and only show the 15.5-15.6 range in the tooltip to let users know that support is the same.

So ordinarily I would not bother adding 15.6 until it's released, at which point it will exclusively appear as the current version. If that's your main concern here I assume you're okay with that?

**Comment by Schweinepriester** [comment]
Oh, per https://github.com/Fyrd/caniuse/issues/6356#issuecomment-1185952831 is going to be different from 15.5 after all, i.e. include at least one new feature…

**Comment by jensimmons** [comment]
I just came here to say this... there is one new feature in 15.6. Which is currently in beta.

**Comment by jensimmons** [comment]
BTW, it's probably more helpful to think about Safari’s dot releases as major releases. We often have as much or more in each of the seven releases of Safari throughout the year (15.0, 15.1, 15.2, 15.3, 15.4, 15.5, 15.6) than Chrome or Firefox in their releases — even though they increment the integer each time, and we are incrementing a decimal place. 

Can I Use is currently displaying Firefox 103 & 104 as coming in the future. And Chrome 104, 105 & 106. It would be nice to see 15.6 coming in the future... before 16.0, as well as STP — since that's what maps. The numbering is different. But the way the browser ships many times a year, with technology landing in the preview browser, then the beta(s), then release... that's the same. 

Current Safari: 15.5
Future Safari: 15.6, 16.0, STP

**Comment by Fyrd** [comment]
Thanks both, 15.6 has now been added!
