### ISSUE TITLE
Firefox/Mozilla platform status appears to be dead

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#6329]
- https://platform-status.mozilla.org/ not available
- https://github.com/mozilla/platform-status is archived
- https://old.reddit.com/r/firefox/comments/tsc5mi/what_happend_to_the_firefox_platform_status_page/
- https://twitter.com/TerribleMia/status/1499824895097638912

People are mentioning https://mozilla.github.io/standards-positions/ but that's definitely not the same.
There's also <https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features>…

 I was trying to look up <https://platform-status.mozilla.org/#webspeech-recognition> (mentioned on <https://caniuse.com/speech-recognition>).

I guess we can remove all those `firefox_id`s? :/
Perhaps beforehand find out what's up? Maybe mention some people from here?

**Comment by Fyrd** [comment]
Yeah, this is unfortunate. Let's not remove the IDs just yet, though I may remove the links from the website.

@marco-c I see you have contributed to the project in the past, do you have any more information or know who we can reach out to instead?

**Comment by marco-c** [comment]
The data from the page was unfortunately not maintained anymore and so it got stale, hence we decided to remove it as it was causing more harm than good. IDK if there's anything usabe for you somewhere on MDN, CC @Rumyra.

**Comment by Fyrd** [comment]
@marco-c @Rumyra Thanks, that's helpful to know. I should note that https://chromestatus.com and https://webkit.org/status/ are still kept up to date and caniuse will continue to pull information from there and link to them for up to date development information for Chrome & Safari. Seems a shame to no longer have information for Firefox (for you as well as developers).

Is there a recommended place we can ask it be revived in some form?

**Comment by Fyrd** [comment]
Have removed the Firefox status from the site.
