### ISSUE TITLE
Safari on iOS is listed as not supporting iFrames but this is wrong

### ISSUE THREAD

**Issue by catharsis71** [Fyrd/caniuse#6333]
https://caniuse.com/mdn-html_elements_iframe

all versions of Safari iOS are listed as no iFrame support but this is wrong

not sure about super old versions but it's definitely had support for quite a while

it's listed as compatible with several iFrame attributes such as sandbox or srcdoc:

https://caniuse.com/iframe-srcdoc
https://caniuse.com/iframe-sandbox

if it's supposedly not compatible with iframes at all, how can it be compatible with these?

**Comment by Schweinepriester** [comment]
I was about to open another issue, for me regarding https://caniuse.com/mdn-css_properties_inset-inline-end, which is clearly shown on https://developer.mozilla.org/en-US/docs/Web/CSS/inset-inline-end#browser_compatibility to be supported by Safari on iOS (same data basis), but it seems like then there's a general issue in the mapping from MDN regarding Safari on iOS.

@Fyrd this one might be a bit more urgent 0:-)

**Comment by Fyrd** [comment]
Yup, there was a recent change in the way MDN BCD manages its data. Have just finished making the necessary changes and should be processing the data correctly now.

**Comment by Fyrd** [comment]
Closing as this has been fixed now.
