### ISSUE TITLE
css_types_resolution_x safari support

### ISSUE THREAD

**Issue by carlosjeurissen** [Fyrd/caniuse#6339]
Seems Safari has supported the x unit for some time at least for image-set:
https://bugs.webkit.org/show_bug.cgi?id=160934

Potentially in other locations as well.

This should be mentioned on https://caniuse.com/mdn-css_types_resolution_x.

**Comment by Fyrd** [comment]
Please file a ticket at the [browser-compat-data repo](https://github.com/mdn/browser-compat-data) for updates to data from there. Once it's updated there the change will appear on the caniuse site at the end of the week.

**Comment by carlosjeurissen** [comment]
@Fyrd Thanks! Apologies for the incorrect location for the issue! Can be found here now:
https://github.com/mdn/browser-compat-data/issues/16751
