### ISSUE TITLE
Mysteriously, `font-variant-east-asian` has no chart

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#6342]
`font-variant-east-asian` is a well-supported property that does have data in MDN’s BDC: 
https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-east-asian#browser_compatibility

But for some reason, when I search on Can I Use, I get “0 results found”: 
https://caniuse.com/?search=font-variant-east-asian

Hm. Feels like there’s something mysteriously blocking this page from being created on Can I Use. It would be a helpful page to have, especially for web developers in East Asia.

**Comment by Fyrd** [comment]
Looks like there was an old entry in the caniuse data that hadn't been verified and therefore wasn't visible, I'd incorrectly set that as an alias to the MDN version, resulting in neither one being visible! Have removed the old data and the alias, now the MDN one appears on that search.

Thanks for pointing that out!

**Comment by jensimmons** [comment]
Thanks for fixing it!
