### ISSUE TITLE
MathML discussion

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#6343]
link pending for 103 but I _need_ chrome 106!!1! for… math reasons ;)

**Comment by Schweinepriester** [comment]
Hrm.

Turns out Chrome 106 ships MathML Core and not MathML (3) - not a small feat either obviously. But that leads to the question, what to do with <https://caniuse.com/mathml>?
Define that as MathML 3 and give Chrome partial because it's "only" Core? Give all partial because it seems there are (small?) interop issues across the board?
Should I open another issue to discuss this further? Also with regard to versions 1, 2 and the upcoming 4...

Links:
- https://groups.google.com/a/chromium.org/g/blink-dev/c/n4zf_3FWmAA/m/oait3tsMAQAJ
- https://chromestatus.com/feature/5240822173794304
- https://groups.google.com/a/chromium.org/g/blink-dev/c/n4zf_3FWmAA/m/ELYOLCQtAQAJ
- v4: https://w3c.github.io/mathml/
- MathML Core issue: #6068
- https://wpt.fyi/results/?label=master&label=experimental&aligned&q=mathml

**Comment by Fyrd** [comment]
Have done the Chrome version update, as for MathML, not sure yet... one option may be to repurpose the current feature for "Basic support", if "core" could be considered basic support that may work but I haven't looked into it enough yet. But in general folks like to know what parts now have cross-browser support so I'd like to find out what that is.

**Comment by Schweinepriester** [comment]
> if "core" could be considered basic support that may work but I haven't looked into it enough yet

To me, it's really a mess - from [here](https://groups.google.com/a/chromium.org/g/blink-dev/c/n4zf_3FWmAA/m/oait3tsMAQAJ):

> > They ship MathML, but could you speak to the conformance level with the Core spec? In cases where there are gaps, are they going to cause significant web compat issues that will need to be addressed with implementation improvements to other browser implementations?
>
> Chromium implements MathML Core which is smaller than what WebKit & Gecko have today. If authors stick to formulas based on the core subset (which we believe should the case for the majority of existing content), the interoperability is quite good as can be see visually with https://people.igalia.com/fwang/2022-06-igalia-week-shipping-mathml-in-chromium/#/5 VS https://people.igalia.com/fwang/2022-06-igalia-week-shipping-mathml-in-chromium/#/6
>
> In practice interop gaps are more likely to come with existing MathML3 content that rely on more features. Our proposal is to rely on polyfills so they work in Chromium too and to try to carefully deprecate & unship these legacy features from WebKit/Gecko.
>
> Additionally, if/when web authors & developers start to make use of them, then we foresee some interop gaps will happen with the new math-related CSS properties proposed to expose the internal magic (display: math, font-family: math, math-style, etc) as well as interaction with existing CSS properties (e.g. padding/margin/borders to tweak spacing).
>
> So the short answer is that yes there is likely to be interop gaps and yes some work will be needed on the WebKit/Gecko side. Igalia actually already started to unship legacy features from WebKit (under a flag) and Gecko and did a few improvements regarding the CSS part. We've been focusing mostly on Chromium since that's where the biggest & most serious interop gap exist for users (no MathML support at all!) but it's very possible we'll put more effort on Gecko/WebKit after that (that's my personal preference but work sponsors may have a different opinion).

with the TL;DR being

> So the short answer is that yes there is likely to be interop gaps and yes some work will be needed on the WebKit/Gecko side. Igalia actually already started to unship legacy features from WebKit (under a flag) and Gecko and did a few improvements regarding the CSS part.

unshipping stuff and Core doesn't seem to be just basic features but doing some stuff different/simpler (i.e. Firefox & Safari don't match that yet)…

I'll change the title to something MathML.

**Comment by Schweinepriester** [comment]
Thinking about it again: Since interest in the context of caniuse seems on the low side ([few issues](https://github.com/Fyrd/caniuse/issues?q=is%3Aissue+is%3Aopen+mathml), no vote on the Core issue yet) and the description on https://caniuse.com/mathml is broad

> Special tags that allow mathematical formulas and notations to be written on web pages.

maybe we just wing it, as in postpone this discussion to the future if/when interest in the distinction arises?
And for now more as a signal paint Chrome 106 green? As the (coming) support definitely matches the description… 😎

**Comment by Fyrd** [comment]
Thanks, I agree. I've added support with a note for now, we'll probably want to tweak that further in the future. Let me know what you think.

**Comment by Schweinepriester** [comment]
LGTM to me for now, I'm sure we'll be wiser in the future!

Looking at the entry I noticed two minor things unrelated to this issue, will create a PR.

Closing this one, cheers! :)
