### ISSUE TITLE
Incorrect support data for Badging API

### ISSUE THREAD

**Issue by amatyulkov** [Fyrd/caniuse#6380]
Current support data tells that Badging API is fully supported in Chrome, Edge, Opera (WebKit essentially), but the support for this API is only partial. 

- https://caniuse.com/mdn-api_notification_badge -- Caniuse
- https://developer.mozilla.org/en-US/docs/Web/API/Badging_API#browser_compatibility -- MDN

The support really is partial: I can call `navigator.setAppBadge`, but `navigator.setClientBadge` is not defined.

**Comment by Fyrd** [comment]
Looks like caniuse matches MDN, but there's two different support tables here:

`setAppBadge`:
https://developer.mozilla.org/en-US/docs/Web/API/Badging_API#browser_compatibility & https://developer.mozilla.org/en-US/docs/Web/API/Navigator/setAppBadge#browser_compatibility
https://caniuse.com/mdn-api_navigator_setappbadge

`Notification.badge`:
https://developer.mozilla.org/en-US/docs/Web/API/Notification/badge#browser_compatibility
https://caniuse.com/mdn-api_notification_badge

If you feel the latter needs updating I recommend using the MDN BCD [feedback link](https://github.com/mdn/browser-compat-data/issues/new?mdn-url=https%3A%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FWeb%2FAPI%2FNotification%2Fbadge&metadata=%3C%21--+Do+not+make+changes+below+this+line+--%3E%0A%3Cdetails%3E%0A%3Csummary%3EMDN+page+report+details%3C%2Fsummary%3E%0A%0A*+Query%3A+%60api.Notification.badge%60%0A*+Report+started%3A+2022-09-10T19%3A30%3A27.851Z%0A%0A%3C%2Fdetails%3E&title=api.Notification.badge+-+%3CSUMMARIZE+THE+PROBLEM%3E&template=data-problem.yml).
