### ISSUE TITLE
Update `revert-layer` information.

### ISSUE THREAD

**Issue by coderfin** [Fyrd/caniuse#6382]
`revert-layer` does work in more browsers than just Firefox.  An update is needed.

Tests here: https://wpt.fyi/results/css/css-cascade?label=master&label=experimental&aligned&q=revert-layer
Can be tested live: http://wpt.live/css/css-cascade/revert-layer-001.html

Issues:
See: https://github.com/mdn/browser-compat-data/issues/16336

Chrome Bug:
See: https://bugs.chromium.org/p/chromium/issues/detail?id=1345101

**Comment by Schweinepriester** [comment]
Do you mean this entry? https://caniuse.com/mdn-css_types_global_keywords_revert-layer

If so, that data is from MDN, so https://github.com/mdn/browser-compat-data/issues/16336 will suffice to fix it :)

**Comment by coderfin** [comment]
Yes.  Sounds good.  Thanks
