### ISSUE TITLE
How are browser scores derived?

### ISSUE THREAD

**Issue by mattpilott** [Fyrd/caniuse#6394]
Hello,

I've tried to work this out but after an hour or so i'm still unclear on how the browser scores are calculated.

Looking at the json I believe the `data` key holds all the features of which there are 529 (currently) if you then subtract the ones marked `unoff` you get 460; However the caniuse site says the feature count is 479, how is this derived?

Beyond that, adding up all the features that each browser supports (marked as 'y') those scores also differ from the values displayed in the browser score section. For example Safari 15.5 on caniuse is 357 where as I get 339

If anyone could help me understand how the scores are generated it would be greatly appreciated!

Thanks

**Comment by Fyrd** [comment]
Hey, good question, I just checked the logic there and realized that it was including "hidden" features (features that are added to the database but were never verified or were hidden from the site for other reasons).

So I went ahead and fixed that, glad you brought it up. Another thing worth noting is that support can include other indicators like `y x` or `y #1` so in case you were only checking for just the `y` string you may have missed that.

**Comment by mattpilott** [comment]
Glad my curiosity helped! Thanks that's now aligned with the numbers im getting which is great. Only other question i had as an aside; Is there somewhere in the data that the current browser version is marked? Or how are those pulled out correctly?

**Comment by Fyrd** [comment]
Yes, the easiest way is to use `fulldata-json/data-2.0.json` and look for `current_version`. Hope that helps!

**Comment by mattpilott** [comment]
Perfect thank you!
