### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by stacksize** [Fyrd/caniuse#6397]
Hi Alexis,

I did 2 pull requests earlier to recommend fixes for broken links, but it looks like there are quite a few pages with broken external links, and a number of them are MDN pages that have had their permalink structure changed.

Here is a table for all the currently dead links. While not necessarily bothersome, I think it would be nice to keep the Resources section clean, tidy, and up-to-date.

|URL                                      |Link URL                                                                                                                              |HTTP Code|
|--------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------|---------|
|https://caniuse.com/cors                                |https://developer.mozilla.org/en-US/docs/Web/API/XDomainRequest                                                                       |404      |
|https://caniuse.com/webgl                               |https://webkit.org/blog/603/webgl-now-available-in-webkit-nightlies/                                                                  |404      |
|https://caniuse.com/canvas                              |https://developer.mozilla.org/en-US/Canvas_tutorial                                                                                   |404      |
|https://caniuse.com/indexeddb                           |https://webplatform.github.io/docs/apis/indexedDB                                                                                     |404      |
|https://caniuse.com/transforms2d                        |https://www.designbombs.com/cross-browser-css-transforms-csssandpaper/                                                                |404      |
|https://caniuse.com/transforms2d                        |https://webplatform.github.io/docs/css/transforms/transform                                                                           |404      |
|https://caniuse.com/apng                                |https://developer.mozilla.org/en-US/docs/Mozilla/Tech/APNG                                                                            |404      |
|https://caniuse.com/apng                                |https://addons.opera.com/en/extensions/details/apng/?display=en                                                                       |404      |
|https://caniuse.com/css-filters                         |http://html5-demos.appspot.com/static/css/filters/index.html                                                                          |404      |
|https://caniuse.com/fullscreen                          |https://jlongster.com/2011/11/21/canvas.html                                                                                          |404      |
|https://caniuse.com/eventsource                         |http://samshull.blogspot.com/2010/10/ajax-push-in-ios-safari-and-chrome-with.html                                                     |404      |
|https://caniuse.com/json                                |http://www.json.org/js.html                                                                                                           |404      |
|https://caniuse.com/json                                |https://developer.mozilla.org/en-US/Using_native_JSON                                                                                 |404      |
|https://caniuse.com/transforms3d                        |https://webplatform.github.io/docs/css/transforms/transform                                                                           |404      |
|https://caniuse.com/fontface                            |https://webplatform.github.io/docs/css/atrules/@font-face                                                                             |404      |
|https://caniuse.com/css-mediaqueries                    |https://webplatform.github.io/docs/css/atrules/@media                                                                                 |404      |
|https://caniuse.com/download                            |http://html5-demos.appspot.com/static/a.download.html                                                                                 |404      |
|https://caniuse.com/datalist                            |http://afarkas.github.com/webshim/demos/                                                                                              |404      |
|https://caniuse.com/spdy                                |https://http2.github.io/http2-spec/index.html                                                                                         |404      |
|https://caniuse.com/getelementsbyclassname              |https://webplatform.github.io/docs/dom/HTMLElement/getElementsByClassName                                                             |404      |
|https://caniuse.com/css-fixed                           |https://css-101.org/fixed-positioning/05.php                                                                                          |404      |
|https://caniuse.com/css-featurequeries                  |https://webplatform.github.io/docs/css/atrules/@supports                                                                              |404      |
|https://caniuse.com/css-selection                       |https://webplatform.github.io/docs/css/selectors/pseudo-elements/::selection                                                          |404      |
|https://caniuse.com/mediasource                         |http://html5-demos.appspot.com/static/media-source.html                                                                               |404      |
|https://caniuse.com/css-sel2                            |http://sixrevisions.com/css/visited-pseudo-class-strange/                                                                             |404      |
|https://caniuse.com/shadowdom                           |http://html5-demos.appspot.com/static/shadowdom-visualizer/index.html                                                                 |404      |
|https://caniuse.com/cryptography                        |https://docs.google.com/spreadsheets/d/1IcevZuPg-_7Lfoi_I_55Gs8ToHjVcW-Lopo7uvqoJFU/edit                                              |404      |
|https://caniuse.com/pagevisibility                      |https://webplatform.github.io/docs/wiki/dom/Document/visibilityState                                                                  |404      |
|https://caniuse.com/css-rrggbbaa                        |https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/17366608--rrggbbaa-and-rgba-color-notation-support     |404      |
|https://caniuse.com/css-scrollbar                       |http://utatti.github.io/perfect-scrollbar/                                                                                            |404      |
|https://caniuse.com/css-text-align-last                 |https://blog.adobe.com/webplatform/2014/02/25/improving-your-sites-visual-details-css3-text-align-last/                               |404      |
|https://caniuse.com/input-range                         |https://tiffanybbrown.com/2012/02/07/input-typerange-and-androids-stock-browser/                                                      |404      |
|https://caniuse.com/css-counters                        |https://developer.mozilla.org/en-US/CSS_Counters                                                                                      |404      |
|https://caniuse.com/wake-lock                           |https://developer.mozilla.org/en-US/docs/Archive/B2G_OS/API/Wake_Lock_API                                                             |404      |
|https://caniuse.com/getcomputedstyle                    |https://webplatform.github.io/docs/css/cssom/methods/getComputedStyle                                                                 |404      |
|https://caniuse.com/iframe-srcdoc                       |https://webplatform.github.io/docs/wiki/html/elements/iframe                                                                          |404      |
|https://caniuse.com/payment-request                     |https://emerald-eon.appspot.com/                                                                                                      |404      |
|https://caniuse.com/pointerlock                         |http://mdn.github.io/pointer-lock-demo                                                                                                |404      |
|https://caniuse.com/css-color-adjust                    |https://codepen.io/yuriyalekseyev/pen/XEpJLr                                                                                          |404      |
|https://caniuse.com/ruby                                |https://addons.mozilla.org/en-US/firefox/addon/1935/                                                                                  |404      |
|https://caniuse.com/css-touch-action                    |https://thx.github.io/mobile/300ms-click-delay/                                                                                       |404      |
|https://caniuse.com/wav                                 |http://www-mmsp.ece.mcgill.ca/documents/AudioFormats/WAVE/WAVE.html                                                                   |404      |
|https://caniuse.com/canvas-blending                     |https://blog.adobe.com/webplatform/2013/01/28/blending-features-in-canvas/                                                            |404      |
|https://caniuse.com/imports                             |https://www.polymer-project.org/platform/html-imports                                                                                 |404      |
|https://caniuse.com/css-zoom                            |https://www.satzansatz.de/cssd/onhavinglayout.html                                                                                    |404      |
|https://caniuse.com/css-zoom                            |https://webplatform.github.io/docs/wiki/css/properties/zoom                                                                           |404      |
|https://caniuse.com/xhtml                               |https://webplatform.github.io/docs/concepts/internet_and_web/the_web_standards_model                                                  |404      |
|https://caniuse.com/css-repeating-gradients             |https://webplatform.github.io/docs/css/repeating-linear-gradient                                                                      |404      |
|https://caniuse.com/custom-elements                     |https://www.polymer-project.org/platform/custom-elements                                                                              |404      |
|https://caniuse.com/ambient-light                       |https://developer.mozilla.org/en-US/docs/Web/API/Ambient_Light_Events                                                                 |404      |
|https://caniuse.com/svg-html                            |https://developer.mozilla.org/en-US/Applying_SVG_effects_to_HTML_content                                                              |404      |
|https://caniuse.com/dom-manip-convenience               |https://developer.mozilla.org/en-US/docs/Web/API/ParentNode                                                                           |404      |
|https://caniuse.com/dom-manip-convenience               |https://developer.mozilla.org/en-US/docs/Web/API/ChildNode                                                                            |404      |
|https://caniuse.com/css-hyphenate                       |http://webdesign.about.com/od/fonts/a/hyphenation-in-css3.htm                                                                         |404      |
|https://caniuse.com/input-event                     |https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/10182111--input-type-checkbox-type-radio-should-fire-in|404      |

**Comment by Schweinepriester** [comment]
For the record, for webplatform there is #4384.

**Comment by mokipedia** [comment]
Here seems to be another one:
https://developer.mozilla.org/docs/Web/API/HTMLElement/draggable in https://caniuse.com/mdn-api_htmlelement_draggable

**Comment by Fyrd** [comment]
Thanks for making this list, slowly working my way through them :)

**Comment by stacksize** [comment]
Great work, Alexis! Thanks for all the effort.

**Comment by mokipedia** [comment]
@Fyrd what is BCD and where would I need to open a ticket to get it to the right ppl?
thank you for your work!
