### ISSUE TITLE
Too light font for body copy

### ISSUE THREAD

**Issue by charakterziffer** [Fyrd/caniuse#641]
Is there a reason why Open Sans Light was chosen for the copy of the caniuse website?

Type designers normally decide very carefully what weight the stems should have, the amount of whitespace in and between letters so that the fonts becomes optimal readable. The “normal” (400, 500) weights of a font should perform best at reading sizes. Light fonts aren’t designed for body copy but for headlines and other jobbing.

Interface designers in contrast like light fonts very much because they give a very elegant, evenly colored look-and-feel. Erik Spiekermann commented on this in connection to Apple’s light Helvetica in iOS7 → http://www.youtube.com/watch?v=Sw0syzCeH4Q

So: Other for “aesthetic” reasons, are there any factors to choose a less readable weight for text that should be readable?

**Comment by Fyrd** [comment]
The font weight currently on the beta site (https://beta.caniuse.com) now uses regular weight for body copy. Will close this issue once it's on the main site.

**Comment by Fyrd** [comment]
This is now available on the main site.
