### ISSUE TITLE
news page is broken

### ISSUE THREAD

**Issue by Kikobeats** [Fyrd/caniuse#6414]
![CleanShot 2022-08-08 at 20 24 23@2x](https://user-images.githubusercontent.com/2096101/183487230-1df4ae8c-6d00-4af9-83e7-419f5f9d1c85.png)

**Comment by Schweinepriester** [comment]
I could reproduce before, but seems to be back now:

![image](https://user-images.githubusercontent.com/2644614/184182752-dba2959d-7690-4dce-95e7-ff95b47c0f04.png)

**Comment by Kikobeats** [comment]
yay, it's back!
