### ISSUE TITLE
String.raw Opera support data

### ISSUE THREAD

**Issue by EladHeller** [Fyrd/caniuse#6417]
The data for Opera support is incorrect. Opera support String.raw from version 28.
Example code to test: `String.raw({raw: ['a','c']},['b'])`, the result should be `abc`.

**Comment by Schweinepriester** [comment]
Saw you opened https://github.com/mdn/browser-compat-data/issues/17308. Once that's fixed, it should after a while going through the cache(s) be fixed on caniuse as well :)

https://caniuse.com/mdn-javascript_builtins_string_raw

**Comment by EladHeller** [comment]
Fixed.
