### ISSUE TITLE
Current version of Safari on iOS is 15.6

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#6425]
I noticed today that for desktop, the current version of Safari is correctly listed as 15.6, but for iOS, it's incorrectly listed as 15.5.

<img width="838" alt="Screenshot 2022-08-19 at 3 54 12 PM" src="https://user-images.githubusercontent.com/108474/185697112-fca2009c-40b8-464e-8bd4-443da73320fe.png">

Actually Safari on iOS is also currently at 15.6.

**Comment by andronocean** [comment]
It's also not being recognized by the Google Analytics importer ("Safari & Chrome for iOS 15.6" doesn't match — pretty good chunk of traffic).

**Comment by Fyrd** [comment]
Added!
