### ISSUE TITLE
The sum of browsers audience coverage in 29 regions >100%

### ISSUE THREAD

**Issue by a-chabin** [Fyrd/caniuse#6426]
Hi!
I'm involved in updating the browserslist website with caniuse audience coverage data by regions.

We [noticed](https://github.com/browserslist/browsersl.ist/issues/423) that in **29 region** audience coverage is more than **100%** (Antarctic 103.9%, North Korea 105% etc.)

I created demo with caniuse-db@1.0.30001379 from CDN. Large values ​​are shown **in bold**
https://codepen.io/nibach/pen/QWmYMOP

Why is this happening? Can we fix it?

![image](https://user-images.githubusercontent.com/22644149/185701428-588be583-e9e5-4a80-9edd-199e5bc96456.png)

**Comment by ai** [comment]
We found this issue during Browserslist website development

**Comment by Fyrd** [comment]
Thanks for pointing this out, bit hard to tell what caused this, possibly an issue with the source StatCounter data at the beginning of the month. I've regenerated the files and all percentages are < 100% now. Will keep an eye out again next month.

**Comment by simevidas** [comment]
Relevant thread by @developit: https://twitter.com/_developit/status/1367169135977902082

**Comment by a-chabin** [comment]
> @Fyrd: Thanks for pointing this out, bit hard to tell what caused this, possibly an issue with the source StatCounter data at the beginning of the month. I've regenerated the files and all percentages are < 100% now. Will keep an eye out again next month.

Thanks for the answer! Now the stats look normal again.


> @simevidas: Relevant thread by @developit

Thank you for sharing other issues in StatCounter statistics. It seems that one should be able to check these values.

**Comment by a-chabin** [comment]
Found the problem after updating the database.
At the beginning of the month, Chome for Android 104 in Russia was used by 29.4% of users. Today **43.1%**.

I prepared a demo to find problems in stats.

**Before. Previous version (1.0.30001379) with stats bug**
https://preview-450---browserslist-vw3nqlhdtq-ue.a.run.app/?q=%3E+0.5%25&region=RU

**After. Current version (1.0.30001380)**
https://browsersl.ist/?q=%3E+0.5%25&region=RU

![tg_image_3907698296](https://user-images.githubusercontent.com/22644149/185795257-5dd1fbff-9c0f-49cc-bda8-5366032f8003.jpeg)

**Comment by a-chabin** [comment]
> @Fyrd: Will keep an eye out again next month.

Thank you! This is very important for audience coverage queries in browserslist.

I think that we need to prepare tests (validations) to check regional usage data. Something like diffcheker between previous and current StatCounter statistics.

Ideas for tracking:
- The sum of browsers audience coverage `>100%`
- Changing in browser version usage statistics by `>10%` per month

**Comment by Fyrd** [comment]
No issues were found for the August import so I'm going to close this ticket. Will continue monitoring in the future.
