### ISSUE TITLE
Background pattern as accessibility help

### ISSUE THREAD

**Issue by charakterziffer** [Fyrd/caniuse#643]
What about using a background pattern to better distinguish the colors, for example for the red boxes:

```
background-color: #DD4938;
background-image: repeating-linear-gradient(135deg, transparent,
   transparent 0.3em, rgba(0,0,0,.13) 0.3em, rgba(0,0,0,.13) 0.6em);
```

The feature `background-image` seems to be pretty well supported (according to caniuse.com ☺).

I know that there’s a setting for different colors but why should visually impaired people be constrained to use a special option, when there’s a solution that doesn’t discriminate?

**Comment by notabene** [comment]
I just worked with a colour-blind person and found this issue. +1 
(I had to tell them about the link-at-the-bottom-look-there and thought maybe it was worth doing something).

Alternately, has adding pictograms been considered?
One or the other would be OK, I guess.

**Comment by Fyrd** [comment]
The beta site (https://beta.caniuse.com) now uses different patterns for different support levels. Will close this issue once it's on the main site.

**Comment by notabene** [comment]
That's great!

**Comment by Fyrd** [comment]
This is now available on the main site.

**Comment by ffoodd** [comment]
Great feature, **thanks a lot**!

It seems to not work when using color-friendly theme, is that expected?
