### ISSUE TITLE
Text Overflow issue in mobile caniuse website

### ISSUE THREAD

**Issue by muchisx** [Fyrd/caniuse#6442]
Its on the properties titles

I'm on chrome 105 - Samsung Galaxy Note 10+

![Screenshot_20220906-204246_Chrome.jpg](https://user-images.githubusercontent.com/34131801/188770334-7bec2e16-f1cd-4b68-aa9a-59dbdb2c9557.jpg)

**Comment by Fyrd** [comment]
Thanks for reporting! Should now be fixed.
