### ISSUE TITLE
Add passkeys

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#6450]
Passkeys provide a new way to log in. Instead of having a username and password, you create a username and your device creates a cryptographic key pair — keeping the private key secret while sharing the public key with the website. Anytime you want to login again, your device communicates with the website, and authenticates that it's you. Using a passkey is far more secure than using a password, and it's far easier to use.

The set of technologies that make passkeys possible are defined in a set of open standards from the FIDO Alliance and the W3C. Learn more at: https://fidoalliance.org/multi-device-fido-credentials

WebAuthn is part of the story — and Can I Use already has a page for [Web Authentication API](https://caniuse.com/webauthn). But support for Web Authn alone does not signal whether or not a device or browser has support for passkeys. Web developers are going to want to know which browsers have support for passkeys as they start offering it as an option.

It would be great for Can I Use to add a page for passkeys. Since it's not a single API — it's an overall feature made possible by multiple APIs, only some of which are web-specific — this makes sense to be on Can I Use (and not in data provided by MDN BCD). Passkeys is a common noun, not a product brand. It's a word that can be used by anyone, much like the word "password". 

Currently, support for passkeys is available in Safari 16.0 for iOS, and will be available in Safari 16.1 for macOS. 

Both Google and Microsoft have announced their intentions to support passkeys. [Google](https://developers.google.com/identity/fido) says: "On Android, we aim to have passkey support available to developers towards the end of 2022." [Microsoft](https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/expansion-of-fido-standard-and-new-updates-for-microsoft/ba-p/3290633) said: "We enthusiastically encourage website owners and app developers to join Microsoft, Apple, Google, and the FIDO Alliance to support passkeys and help realize our vision of a truly passwordless world."

**Comment by jensimmons** [comment]
Is adding a page for Passkeys something you are willing to do? 

Chrome 108 now has support. It shipped Dec 8, 2022. 
https://blog.chromium.org/2022/12/introducing-passkeys-in-chrome.html

**Comment by Fyrd** [comment]
Probably, yes. Just want to be careful that we can test it appropriately so the data is accurate. The test at https://www.passkeys.io _may_ be sufficient, will need to take a closer look.

**Comment by Synchro** [comment]
Surprised this wasn't in here already! This is now especially relevant since [Google announced full support for them for all their services](https://blog.google/technology/safety-security/the-beginning-of-the-end-of-the-password/) on May 3rd, 2023.

**Comment by jensimmons** [comment]
I created a PR. If someone can update it, perhaps it can be landed this time.

It may be that it's not possible to have automated tests on Can I Use confirm support, since passkeys involves deep integration with operating systems + having signed up with a passkey at a website that uses passkeys + confirming the whole user flow works correctly. Passkeys are however, a big enough consumer-facing feature that if a company like Google, Microsoft or Apple says they have support, then they do have support.

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/passkeys (feedback welcome!)
