### ISSUE TITLE
Safari 16.1 is now in beta

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#6453]
It would be helpful if you could add Safari 16.1 to Can I Use. It's in beta now.

**Comment by jensimmons** [comment]
The beta release notes are at: https://developer.apple.com/documentation/safari-release-notes/safari-16_1-release-notes

**Comment by jensimmons** [comment]
The beta release notes are at: https://developer.apple.com/documentation/safari-release-notes/safari-16_1-release-notes

cc @Schweinepriester

**Comment by Schweinepriester** [comment]
> Added support for AVIF animated image sequences on macOS Ventura, iPadOS 16, and iOS 16.

dayum, not bad, if I might say so!

**Comment by jensimmons** [comment]
Once Safari 16.1 is added, this AVIF PR will pass automated checks. 
https://github.com/Fyrd/caniuse/pull/6452

**Comment by Fyrd** [comment]
Has been added!
