### ISSUE TITLE
QQ Browser data is incorrect, current version is 13.1.1

### ISSUE THREAD

**Issue by developit** [Fyrd/caniuse#6454]
I've noticed that all tools based on a Browserslist query of `supports es6-module` end up with `and_qq:10.4` as a wild outlier in the resulting set of browsers. QQ Browser for Android is currently at version 13.1.1, but no data for anything other than this 10.4 version seems to exist.

I pulled the statcounter global stats data, and QQ currently has `0.04%` usage globally, and `0.36%` usage in Asia. StatCounter doesn't seem to even track QQ for Android 10.4 anymore. They have `10.8` and `10.9`, which have a combined usage in Asia of `0.01%`.

**Comment by Fyrd** [comment]
Thanks, has now been updated to 13.1.
