### ISSUE TITLE
The version number for Safari on iOS is not tied to the operating system

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#6460]
I just noticed this note about Safari for iOS that appears when you hover over the label.

> The Safari browser for iOS is tied to the operating system, so the numbers used are based on the
OS version.

<img width="312" alt="Screenshot 2022-09-15 at 6 55 31 PM" src="https://user-images.githubusercontent.com/108474/190522687-19a67b38-bb0c-45ab-aa29-7a83b25e6fd5.png">

That's actually not true. The number for Safari on iOS is independent of how iOS is numbered — even though they are very often the same number. Safari 15.4 for iOS shipped with iOS 15.4. But they could get out of sync, because they are independent.

**Comment by jensimmons** [comment]
For example, recently iOS 15 updated to iOS 15.7, while the version of Safari updated to 15.6.1.

**Comment by Fyrd** [comment]
Is there ever a difference in the WebKit version used when they're not in sync though? If not I'd prefer to refer to the iOS version as long as it's correct.

One of the reasons is that we're using the same support value used for other browsers on iOS as they share the same WebKit version. As far as I can tell Safari's version number isn't exposed for these browsers so "Safari and Chrome on iOS 16" works (related: #6476) but I'm not sure how to make that that description work if only Safari has a known version and other browsers use a version that's _not_ tied to the WebKit version being used, and therefore referencing the iOS version makes the most sense.

**Comment by adrianosmond** [comment]
I think it can be different, especially as the devices fall out of support and only get security patches. [wikipedia for iOS Safari 12](https://en.wikipedia.org/wiki/Safari_version_history#Safari_12_2) shows there's been no change in webkit version since 12.2 and the latest version is 12.5.6. I have an old iPhone 6 lying around and that reports its user agent as 12.1 (which is in line with what wikipedia says) even though the OS is up to date.

**Comment by Fyrd** [comment]
Thanks for the example @adrianosmond . I guess I should point out that what matters most is for the WebKit version to match an iOS version range, which it still does: 12.0-12.1 = 606.1.36 and 12.2-12.5.5 = 607.1.40

I think as long as we _can_ accurately refer to the WebKit version using iOS version ranges, the Safari version doesn't particularly matter (to most developers). As far as I can tell there isn't even a way on iOS to look up the version Safari is on, only way seems to be looking up the User Agent string. The OS version however is relatively easy to find out.

So I think the OS version should continue to be used as a more helpful identifier, but the tooltip description should be clarified. For now I plan on going with this:

> As all iOS browsers use the same version of WebKit on the OS, support is identified based on iOS version rather than any particular browser version.

**Comment by Fyrd** [comment]
Closing based on my last comment.
