### ISSUE TITLE
Page Transitions

### ISSUE THREAD

**Issue by chesamel** [Fyrd/caniuse#6461]
Please could we add Page Transitions?

https://www.youtube.com/watch?v=JCJUPJ_zDQ4

Early days but I would love to track the progress of this spec.

**Comment by Yojimb0** [comment]
I believe it might be because the spec is still a draft, and hasn't been filed to W3C yet: https://tabatkins.github.io/specs/css-shared-element-transitions/

But regardless, I would love to track support for this feature too 👍

**Comment by Mubelotix** [comment]
There is information on [their github repo](https://github.com/WICG/shared-element-transitions/)

**Comment by jelmerdemaat** [comment]
It is now called the View Transition API. 

Explainer: https://developer.chrome.com/docs/web-platform/view-transitions/

**Comment by niklas-dahl** [comment]
Its now shipped in chrome 🥳 
https://developer.chrome.com/blog/new-in-chrome-111/

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/view-transitions
