### ISSUE TITLE
Importing Google Analytics data requires giving a third party permissions

### ISSUE THREAD

**Issue by alopatin** [Fyrd/caniuse#647]
This refers to the "Import browser usage data from Google Analytics" feature recently launched at http://caniuse.com:

I love the concept, and would love to be able to use the feature, but don't feel comfortable granting a third party full read permissions to Google Analytics.

I'm not entirely sure what the best way to work around this would be. You could allow users the option to supply their own `clientId`/`apiKey` pairs, perhaps?

(Also, given the launch of this feature, you probably want to post some sort of privacy policy.)

**Comment by SeanHayes** [comment]
I'd really like to use this feature as well, but I can't hand over my company's data without any TOS or Privacy Policy in place.

**Comment by tech4him1** [comment]
I would really appreciate a Privacy Policy as well.

**Comment by tordans** [comment]
@Fyrd can you tell us more about how the data is handelt? 

A few questions:
- Is there a file in this codebase that handels the implementation? (Where?) So we can check out what is happening in the backend.
- Is any data stored on any server? Access-permission(keys)? Actual Data?
- What is done locally and what is done on the server side?
- Who has access to the data or keys, only you?

Thanks

**Comment by ntucakovic** [comment]
I have to bump this one too, same questions as @tordans 

I want to suggest using Google Analytics per site instead of the bulk percentage across the web, but I definitely need to check some of those boxes before doing so.

Thank you for the service!

**Comment by jayphelps** [comment]
Giving this the bi-yearly bump to say indeed, the lack of privacy policy, or information about what is stored, how it's used, etc. was unfortunate to find and prevents me from using it in most cases due to revenue/conversion information of clients. Thanks for this free service, regardless.

**Comment by Fyrd** [comment]
The new GA4 import no longer requires direct access and instead relies on a CSV upload, hopefully this allays any permission concerns?

Also apologies as this is way late but there is a (very brief) privacy policy at https://caniuse.com/tos.html (linked to from the google login). This is still the case, the data is never sent to a server.

**Comment by Fyrd** [comment]
Closing as no longer relevant (see last comment)
