### ISSUE TITLE
Implement OpenSearch ("make the search-field usable as browser-search")

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#648]
title says it all

i want to add caniuse.com as search engine in chrome

**Comment by Schweinepriester** [comment]
push for opensearch B-)

**Comment by Tigt** [comment]
+1

**Comment by inoyakaigor** [comment]
Vote!

**Comment by Tigt** [comment]
If it makes it easier, the following should work:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/" xmlns:moz="http://www.mozilla.org/2006/browser/search/">
  <ShortName>caniuse</ShortName>
  <LongName>Can I Use...</LongName>
  <Description>Search for feature support across browsers on caniuse.com</Description>

  <InputEncoding>UTF-8</InputEncoding>

  <Image width="16" height="16" type="image/x-icon">http://caniuse.com/favicon.ico</Image>
  <Image width="128" height="128" type="image/png">http://caniuse.com/img/favicon-128.png</Image>

  <Url type="text/html" method="get" template="http://caniuse.com/#search={searchTerms}"/>
  <Url type="application/opensearchdescription+xml" rel="self" template="http://caniuse.com/search.xml" /> <!-- or wherever you put it -->

  <moz:SearchForm>http://caniuse.com/</moz:SearchForm>
</OpenSearchDescription>
```

**Comment by Schweinepriester** [comment]
push again, see @Tigt's comment :)

**Comment by Fyrd** [comment]
Now implemented! Sorry for the delay, and many thanks to @tigt for making it easy to add. :)

**Comment by Schweinepriester** [comment]
Thank you very much :)

**Comment by makoConstruct** [comment]
Great, but perhaps not quite finished. In chrome most search inputs will have "Add Search Engine" in their right click menu, which is really convenient. To get that to work it seems that a search input needs to be inside a form element having the attribute `action="/search"`, or something along the lines of "/search". It varies. If you check out the form above, for instance, you'll see `action="/Fyrd/caniuse/search"` (and if you backspace the [This Repository] qualifier it'll change to `action="/search"`)

**Comment by tigt** [comment]
@makoConstruct Firefox has similar functionality (Context menu > "Add a keyword for this search"), which I can activate by adding an empty, attribute-less `<form>` element around the search input.

**Comment by gdoron** [comment]
@Fyrd I can't find it on caniuse, can you paste the link?
Thanks.

**Comment by gdoron** [comment]
@Fyrd 
Ohh wait, this issue is about adding it to the site...
I'm asking adding which browsers support it... :smile: 

Couldn't find any info about it.

**Comment by inoyakaigor** [comment]
@gdoron OpenSearch is not part of HTML/CSS standards

**Comment by gdoron** [comment]
@inoyakaigor ohh that makes sense.
Anyway, since I spammed this thread already :smile:  , do you know which browsers support it beside Chrome?

**Comment by inoyakaigor** [comment]
@gdoron Firefox, IE, Safari. About mobile browsers I have no information
