### ISSUE TITLE
Cannot hide tooltip on mobile

### ISSUE THREAD

**Issue by zznidar** [Fyrd/caniuse#6480]
On mobile, in order to show the tooltip on [caniuse.com](https://caniuse.com), a user has to touch a browser version. Once done, however, it is impossible to hide it. On desktop, clicking outside of versions and then hovering over another version hides it. On mobile, there's no hovering as such, hence the tooltip is always shown. This makes it impossible to select a different version that's hidden under the tooltip.

## Repro steps
1. Search for something on https://caniuse.com
2. Tap on any browser version
3. Now try to hide that tooltip and select another version

## Expected result
User should be able to hide the tooltip (for example, deselect the current version by touching outside the browser versions) even if the device doesn't have a mouse.

## Actual result
User cannot hide the tooltip. The only option is to select another browser version, but this only opens a new tooltip – still covering a part of the table.

## Screnshot
In the example below, I cannot select the Nightly version of Firefox because a tooltip is covering it at all times.

![image](https://user-images.githubusercontent.com/20877556/193449436-1038858c-5c6b-4fc3-a28c-78d13a2fd599.png)

**Comment by Fyrd** [comment]
Thanks for reporting! This was definitely a bug for both mobile and desktop where clicking/tapping outside the tooltip should have hidden it. Just pushed a fix, I believe it's working as expected now.
