### ISSUE TITLE
`link-rel-preconnect`: Incorrect data for Firefox

### ISSUE THREAD

**Issue by saurabhchardereal** [Fyrd/caniuse#6481]
Firefox does support the `preconnect` link directive. Checked out MDN BCD too which also says it still supports it. Thought it was a mismatch of data between MDN and CanIUse, so opened an issue there as well but when I checked it, turns out, firefox indeed have support for `preconnect` (or at least in version `105.0.1`).

Ref: https://github.com/mdn/browser-compat-data/issues/17926#issuecomment-1265056877

**Comment by Schweinepriester** [comment]
https://github.com/Fyrd/caniuse/pull/5652 => https://bugzilla.mozilla.org/show_bug.cgi?id=1543990

CC @da2x

**Comment by saurabhchardereal** [comment]
Did my own testing using the methodology given in the bug report, and unfortunately it still doesn't work. FF reports it is "supported" but currently it is not functional due to the aforementioned bug. 

Closing this issue, as it is clear now.
