### ISSUE TITLE
iOS & iPadOS 16.1 don't animate the AVIF

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#6505]
<https://tests.caniuse.com/avif>:

https://user-images.githubusercontent.com/2644614/197596582-6877560b-e0ba-4356-8c5a-44542e698ab9.MP4

Checked iPadOS 16.1 as well.

This time as an issue first, perhaps it was encoded using an old encoder as well?
Are there other examples showing it works?

CC @jensimmons 

EDIT:

The files in the Firefox bug at https://bugzilla.mozilla.org/show_bug.cgi?id=1686338 also don't work, having been added to the bug a year ago.
sequence-without-pitm.avif works in Chrome 106.0.5249.119 on Windows 10, sequence-with-pitm.avif flickers, but not sure if that is proper and sequence-with-pitm-avif-major.avif doesn't move.

**Comment by jensimmons** [comment]
Please do create new images for your tests. The specs for AVIF changed. Image encoders have been updated — including recently when bugs in them were found.

**Comment by Schweinepriester** [comment]
Fixed by https://github.com/Fyrd/caniuse/pull/6557.
