### ISSUE TITLE
Beautify `data.json`

### ISSUE THREAD

**Issue by ai** [Fyrd/caniuse#651]
Now `data.json` is one line file for machines only.

Of course, it is generated by your scripts and mostly used by another scripts. But unreadable format make script developemtn harder.

Maybe we should to add some JSON beautifier to `data.json` generator?

**Comment by MayhemYDG** [comment]
You can beautify any json with something simple like:
```javascript
var obj = JSON.parse(data);
var beauty = JSON.stringify(obj, null, 2);
```

**Comment by ai** [comment]
@Fyrd can I send a PR with beautifylized `data.json` or you generate it by some internal scripts?

**Comment by Fyrd** [comment]
Yeah, it's generated. I could easily beautify it too but I worry that if I did that people would think they could just submit PRs to that file which I can't do anything with. So best to leave it compressed so it's only used for people who need the whole thing and won't mind parsing/expanding it themselves if they need to.
