### ISSUE TITLE
What part of the website's data is contained in data.json?

### ISSUE THREAD

**Issue by chrillek** [Fyrd/caniuse#6511]
On caniuse.com, I can (for example) search for "masonry" and I get three entries. `data.json` contains none of them. Similarly, searching on caniuse.com for "arrow" returns 5 results, while data.json contains only 1 ("Arrow function"). 

What is the relationship between data on caniuse.com and data.json (or data-2.0.json, for that matter)?

**Comment by Fyrd** [comment]
There's a caniuse-specific database of features that is part of this repository, then there's the [MDN browser-compat-data](https://github.com/mdn/browser-compat-data) database that is included in searches for features on the website.

Any BCD feature you'll see on the site will always have this in the footer:
<img width="348" alt="Screen Shot 2022-10-29 at 4 11 20 PM" src="https://user-images.githubusercontent.com/432336/198855841-f848c1ed-83dd-4459-9495-f85c0330fbc4.png">

**Comment by Fyrd** [comment]
Closing as answered.
