### ISSUE TITLE
Ant Design Mobile  5.25.1在IOS16.1版本是否支持

### ISSUE THREAD

**Issue by 1601463525** [Fyrd/caniuse#6516]
Ant Design Mobile  5.25.1在IOS16.1版本是否支持

**Comment by Ugoku** [comment]
Not the scope of Caniuse

**Comment by linxz** [comment]
> Ant Design Mobile 5.25.1在IOS16.1版本是否支持

* https://mobile.ant.design/zh
* https://github.com/ant-design/ant-design-mobile/issues

@1601463525  你走错片场了……上面这两个网址才是你应该去的

**Comment by Fyrd** [comment]
Indeed, as mentioned libraries and frameworks are not tracked on caniuse.
