### ISSUE TITLE
Safari 16.2 & 16.3

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#6546]
the old obligatorily issue:

Safari & Safari on iOS 16.2 have been released
- https://developer.apple.com/documentation/safari-release-notes/safari-16_2-release-notes
- https://www.macrumors.com/2022/12/13/apple-releases-ios-16-2/

Safari & Safari on iOS 16.3 are coming
- https://www.macrumors.com/2022/12/14/apple-seeds-ios-16-3-beta-1-to-developers/
- Safari 16.3 seem to be pending

**Comment by Schweinepriester** [comment]
Safari 16.3 release notes are here now:
https://developer.apple.com/documentation/safari-release-notes/safari-16_3-release-notes

@Fyrd has already updated the website, but without adding 16.3 to the files? 🤔 
Is there `git push` missing perhaps? 🙃

**Comment by Fyrd** [comment]
@Schweinepriester Oops, yeah something went a little wonky recently, I think it's good now.

**Comment by Schweinepriester** [comment]
looking good indeed :)
