### ISSUE TITLE
https://html5demos.com/storage sends me to VPN site

### ISSUE THREAD

**Issue by per-oestergaard** [Fyrd/caniuse#6562]
When clicking on the link https://caniuse.com/?search=localstorage and using the `Simple demo (https://html5demos.com/storage)` link, I end up on the broken page https://bestvpn.org/html5demos/storage.  bestvpn.org does not translate, at least not in my corporate network.

**Comment by Schweinepriester** [comment]
calling the original author @remy for comment? :)

**Comment by Fyrd** [comment]
Yeah I noticed some of these... they're a little on the spammy side but still serve their main purpose so I'll leave them for now, unless a better demo can replace them.
