### ISSUE TITLE
Accessbility tools are missing in the browser list

### ISSUE THREAD

**Issue by astuanax** [Fyrd/caniuse#6572]
I would love to see any accessibility tool listed among the browsers.

the support for ARIA attributes might differ depending on when using JAWS, [NVDA](https://alternativeto.net/software/nvda/about/), free and Open Source. 

Other great apps are [Thunder](https://alternativeto.net/software/thunder/about/), [Microsoft Narrator](https://alternativeto.net/software/microsoft-narrator/about/), [Orca Screen Reader](https://alternativeto.net/software/orca/about/) and [TalkBack](https://alternativeto.net/software/talkback/about/).

Is there any option to add those?

**Comment by Fyrd** [comment]
While this would certainly be valuable, since there are many screen readers and each will work differently with each browser the amount of overhead for testing purposes would be too large for a project like caniuse to handle. So no plans to add these I'm afraid.
