### ISSUE TITLE
Suspense tags

### ISSUE THREAD

**Issue by DerekDcq** [Fyrd/caniuse#6599]
I do not find Caniuse page for Suspense tags

**Comment by Schweinepriester** [comment]
@DerekDcq do you have a link to what you mean by any chance?

do you mean <https://vuejs.org/guide/built-ins/suspense.html>…?

**Comment by Fyrd** [comment]
Yeah I'm guessing it's that one or this: https://17.reactjs.org/docs/concurrent-mode-suspense.html

As these are constructs used in their respective frameworks and not native DOM elements they will not be tracked on caniuse.
