### ISSUE TITLE
Broken data: Support for spread in destructuring

### ISSUE THREAD

**Issue by LayZeeDK** [Fyrd/caniuse#6600]
The page [Support for spread in destructuring](https://caniuse.com/mdn-javascript_operators_spread_spread_in_destructuring) is broken. No data is shown as the HTTP request GET https://caniuse.com/process/get_feat_data.php?type=support-data&feat=mdn-javascript_builtins_regexp_lookbehind_assertion returns `[]`.

**Comment by Fyrd** [comment]
Thanks, turns out that data was [removed from BCD](https://github.com/mdn/browser-compat-data/issues/9457). I have updated the [link to it](https://caniuse.com/sr_es9) accordingly (now points at [Rest in arrays](https://caniuse.com/mdn-javascript_operators_destructuring_rest_in_arrays)).
