### ISSUE TITLE
Broken data: Support for RegExp: lookbehind assertions

### ISSUE THREAD

**Issue by LayZeeDK** [Fyrd/caniuse#6601]
The page [Support for RegExp: lookbehind assertions](https://caniuse.com/mdn-javascript_builtins_regexp_lookbehind_assertion) is broken. No data is shown as the HTTP request GET https://caniuse.com/process/get_feat_data.php?type=support-data&feat=mdn-javascript_builtins_regexp_lookbehind_assertion returns `[]`.

**Comment by Fyrd** [comment]
Thanks, that link was incorrect, should go to https://caniuse.com/js-regexp-lookbehind instead. Have updated the link at https://caniuse.com/sr_es9 accordingly.
