### ISSUE TITLE
Tab to search on caniuse.com has stopped working

### ISSUE THREAD

**Issue by panstromek** [Fyrd/caniuse#6602]
The search manifest xml is still online and linked from the document, but I can't use "tab to search" from Chrome anymore.

It works on most other sites (e.g. youtube), but I found it stopped working for some (one where I actually implemented it myself), so maybe Chrome changed some rules around it?

**Comment by Fyrd** [comment]
Sounds like a change made on Chrome's side, in fact it doesn't seem to work for me for youtube either (hitting tab cycles through the dropdown).

Let me know if there's something obvious caniuse.com is doing wrong, else I'll close this ticket.

**Comment by panstromek** [comment]
Hmm, I managed to fix it by enabling it in settings, based on [this answer](https://support.google.com/chrome/thread/174290928/tab-key-after-typing-youtube-com-in-address-bar-no-longer-allows-direct-youtube-search?hl=en).

> 1) go to chrome://settings/searchEngines
> 2) scroll down to inactive sites, you should see youtube.com
> 3) activate it.

It was disabled with a long list of other sites. I'm not sure how it got there though, I use it all the time and didn't disable anything.

Seems like there's nothing wrong with the site in the end.
