### ISSUE TITLE
Web API for Raycast

### ISSUE THREAD

**Issue by bobbymannino** [Fyrd/caniuse#6603]
I can't seem to find it online but I may not be looking in the right places. Is there an api for caniuse but in web form eg 'caniuse.com/api/?q=border' or a similar variation of this. It must be in web url format to reap the biggest benefits for a Raycast extension, Thank you!

**Comment by Fyrd** [comment]
There is a third party command line version at https://www.npmjs.com/package/caniuse-api, but no, no plans to support a web API, sorry.
