### ISSUE TITLE
Broken link/document: Support for Logical nullish assignment

### ISSUE THREAD

**Issue by LayZeeDK** [Fyrd/caniuse#6606]
The link/document [Support for Logical nullish assignment](https://caniuse.com/mdn-javascript_operators_logical_nullish_assignment) shows no data. It is also listed in the [ES2021](https://caniuse.com/sr_es12) document  and the [ES2021 feature support list](https://caniuse.com/?feats=mdn-javascript_builtins_string_replaceall,mdn-javascript_builtins_promise_any,mdn-javascript_builtins_weakref,mdn-javascript_operators_logical_or_assignment,mdn-javascript_operators_logical_and_assignment,mdn-javascript_operators_logical_nullish_assignment,mdn-javascript_grammar_numeric_separators,mdn-javascript_builtins_finalizationregistry).

Related to #6600 and #6601.

**Comment by Fyrd** [comment]
Thanks! Link has now been updated/corrected to https://caniuse.com/mdn-javascript_operators_nullish_coalescing_assignment
