### ISSUE TITLE
CSS `leading-trim`

### ISSUE THREAD

**Issue by coreh** [Fyrd/caniuse#6611]
Safari / WebKit just [added support for `leading-trim` on Developer Preview 163](https://webkit.org/blog/13839/release-notes-for-safari-technology-preview-163/).

The [caniuse page on the topic](https://caniuse.com/sr_leading-trim-text-edge) currently says:

> “As of February 2021 [...] there do not yet appear to be any plans by browsers to implement this functionality”

Now that browsers are implementing it, it might make sense to add the compatibility table and start tracking browser progress. It might also make sense to split it from `text-edge` in case browsers implement one but not the other.

**Comment by Schweinepriester** [comment]
+1, related https://github.com/Fyrd/caniuse/issues/5571

**Comment by Fyrd** [comment]
Now available at https://caniuse.com/css-text-box-trim

For now I'll assume browsers will implement them together, if that changes we can add a separate feature for text-box-edge.
