### ISSUE TITLE
Add Safari 16.4

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#6613]
I believe you have to manually add support for the ability to provide data about Safari 16.4, yes? Since Safari 16.3 is the current version, it might be a nice time for you to add such support.

**Comment by Schweinepriester** [comment]
@Fyrd +1 even more now!

https://twitter.com/webkit/status/1626289183122677760

**Comment by jensimmons** [comment]
There are over 135 new features in Safari 16.4 beta 1. And hundreds of bug fixes, some of which are documented on Can I Use and will need to be updated. They are all listed here: 
https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes

**Comment by Fyrd** [comment]
Cool, yeah I prefer to wait until there's a publicly accessible version of the browser available else it's hard to verify any information. Glad to see the beta is available now, have added the versions.

**Comment by Schweinepriester** [comment]
@jensimmons 

> And hundreds of bug fixes, some of which are documented on Can I Use and will need to be updated.

Did you have any particular bug fixes on your mind? :)

For features I think https://github.com/Fyrd/caniuse/pull/6616 covers most of it (and also went fully through the changelog).
