### ISSUE TITLE
Version numbers do not wrap when showing "All" browsers

### ISSUE THREAD

**Issue by DanielHeath** [Fyrd/caniuse#6624]
Look at the "Safari on iOS" label in this screenshot, for instance.

![image](https://user-images.githubusercontent.com/47430/220761446-f73421bb-3ffe-4c56-995c-cc49e569ae30.png)

Can reproduce on desktop chrome & firefox.

**Comment by Fyrd** [comment]
Thanks for reporting! Yeah this has been due for some improvement, just made some tweaks that result in more wrapping and better text scaling in some cases. See what you think.
