### ISSUE TITLE
Compare browsers: selection not working completely

### ISSUE THREAD

**Issue by thany** [Fyrd/caniuse#6626]
When I go to compare browsers and select any two browsers, I get to see the comparison totally fine and as expected. When I then add a third browser to the comparison, it doesn't get added anywhere.

To reproduce:
1. Go to https://caniuse.com/ciu/comparison
2. Select Edge 110
3. Select Firefox 110
4. Observe the comparison
5. Select Firefox for Android 109
6. Observe the comparison - still only the first two

As a bonus issue - deeplinking to a comparison doesn't work: https://caniuse.com/?compare=edge+110,firefox+110,and_ff+109&compareCats=all

This will display the three browser checkboxes ticked, but does not show their comparison.

It might help to know I'm doing this on desktop Firefox 110.

**Comment by romaricpascal** [comment]
Got the same deep linking issue on both Chrome (Version 110.0.5481.177), Safari (Version 16.3 (18614.4.6.1.5)) and Firefox (110.0 (64-bit)) on MacOS (13.2), with the following URL:

https://caniuse.com/?compare=chrome+61,edge+16,safari+10.1,firefox+60,opera+48,and_chr+109,ios_saf+10.3,samsung+8.2,op_mob+73,and_uc+13.4,android+109,and_ff+109,and_qq+13.1,baidu+13.18,kaios+2.5&compareCats=JS,JS%20API

The console displays the following error:

```
Uncaught (in promise) Error: Expected to find and_chr+109 in chrome+61,edge+16,safari+10.1,firefox+60,opera+48,ios_saf+10.3,samsung+8.2,op_mob+73,and_uc+13.4,android+109,and_qq+13.1,baidu+13.18,kaios+2.5
    at ciu-comparison.ts:195:11
    at Array.map (<anonymous>)
    at CiuComparison.getVersionData (ciu-comparison.ts:193:43)
    at CiuComparison.renderComparisonTable (ciu-comparison.ts:266:25)
    at CiuComparison.renderResults (ciu-comparison.ts:333:12)
    at CiuComparison.render (ciu-comparison.ts:352:12)
    at CiuComparison.update (lit-element.ts:293:33)
    at CiuComparison.performUpdate (updating-element.ts:774:14)
    at CiuComparison._enqueueUpdate (updating-element.ts:724:25)
```

**Comment by Fyrd** [comment]
Thanks for reporting! This was due to a client/server mismatch and should be fixed now. I've also added better handling if an unknown browser version is included in the URL (it will still compare the known ones)
