### ISSUE TITLE
Add feature: `text-wrap`

### ISSUE THREAD

**Issue by GrossDesignCo** [Fyrd/caniuse#6645]
## Add `text-wrap`
And especially `text-wrap: balance`

This feature is gaining popular awareness and is supported in Chrome Canary (with the experimental flag turned on) as of Adam Argyle's tweet:
https://twitter.com/argyleink/status/1631797057840349184

CodePen test he uses: https://codepen.io/argyleink/pen/bGxWZZj

Spec: https://drafts.csswg.org/css-text-4/#text-wrap

**Comment by Schweinepriester** [comment]
Excited as well, but this is a duplicate of https://github.com/Fyrd/caniuse/issues/1064.

**Comment by GrossDesignCo** [comment]
Ah, ty, didn’t see that.
