### ISSUE TITLE
CSS media query range syntax

### ISSUE THREAD

**Issue by patrikjuvonen** [Fyrd/caniuse#6650]
It would be great to be able to follow browser support progress for media query range syntax described at https://developer.chrome.com/blog/media-query-range-syntax/

**Comment by Schweinepriester** [comment]
Isn't that this entry? https://caniuse.com/css-media-range-syntax

If it is and in case you didn't find it, what were you searching for? I.e. whats missing to make it better findable?

**Comment by patrikjuvonen** [comment]
Ah! That's it. Thank you.

I was searching for "media query range syntax", "media query syntax", "media query range", "css media query range syntax".

I should have tried a few more variations.

I think, if possible, the "query" word could be added to work on this perhaps, although I do understand it is vague and could grow the size of the search index.

This issue may be closed.

**Comment by Schweinepriester** [comment]
Thank you, created a PR to improve findability: https://github.com/Fyrd/caniuse/pull/6651
