### ISSUE TITLE
Add relative color (syntax)

### ISSUE THREAD

**Issue by t0byman** [Fyrd/caniuse#6683]
- https://www.w3.org/TR/css-color-5/#relative-colors
- https://github.com/w3c/csswg-drafts/issues/7978
- https://evilmartians.com/chronicles/oklch-in-css-why-quit-rgb-hsl#:~:text=valid%20syntax%20*/%0A%7D-,Color%20modifications,-In%20CSS%20Colors
- Tests:
  - https://wpt.fyi/results/css/css-color/parsing/relative-color-invalid.html?label=experimental&label=master&aligned
  - https://wpt.fyi/results/css/css-color/parsing/relative-color-valid.html?label=experimental&label=master&aligned

**Comment by Schweinepriester** [comment]
Excited as well, but technically covered by aka. duplicate of https://github.com/Fyrd/caniuse/issues/5405.

**Comment by t0byman** [comment]
My bad, I'll go ahead and close this issue then
