### ISSUE TITLE
OffscreenCanvas support in Safari 16.4 is partial

### ISSUE THREAD

**Issue by AshleyScirra** [Fyrd/caniuse#6690]
OffscreenCanvas support is listed as "yes" (implying full support) for Safari 16.4: https://caniuse.com/offscreencanvas

However Safari 16.4 only ships support for the "2d" context. There is no support for WebGL, as other browsers support. Therefore its status should be changed to "Partial" and a note added explaining this.

**Comment by Fyrd** [comment]
Has now been fixed (WebGL support is coming in Safari 17 FYI)
