### ISSUE TITLE
AV1 test suit video must be MP4 instead of MKV

### ISSUE THREAD

**Issue by tats-u** [Fyrd/caniuse#6693]
[![image](https://user-images.githubusercontent.com/12870451/235280151-c29c4674-e224-471c-97d5-212888084c2b.png)](https://tests.caniuse.com/av1)
[![image](https://user-images.githubusercontent.com/12870451/235280808-9267dd26-04e7-417b-8bf6-7847510dabaa.png)](https://test-videos.co.uk/vids/sintel/mp4/av1/360/Sintel_360_10s_1MB.mp4)

MKV is not supported in Firefox.
Must be replaced with AV1 in MP4 (ISOBMFF) container.

AV1 in WebM is not official but just a de facto standard.

> [Video Codec Name: VP8 or VP9](https://www.webmproject.org/docs/container/)

Test case: https://test-videos.co.uk/bigbuckbunny/webm-av1

**Comment by tats-u** [comment]
How can I edit tests.caniuse.com?

**Comment by tats-u** [comment]
Is its audio Opus, right?
FFmpeg claimed it's experimental.
Succeeded to play in Firefox after converting audio to AAC.

```
ffmpeg -i .\video.av1.mkv -c:a aac -c:v copy ./video.av1.mp4
```

https://user-images.githubusercontent.com/12870451/235286393-6fd3ee9a-8b6b-42a7-9d7b-0f4a6da9712e.mp4

**Comment by Fyrd** [comment]
Thanks for the files! Have updated the tests to include them.
