### ISSUE TITLE
In the comparison show also feature with previously unknown support

### ISSUE THREAD

**Issue by eyaler** [Fyrd/caniuse#6697]
when comparing browsers, unknown features that re now supported are ignored.

for example: safari 16.4 added support for:
https://caniuse.com/mdn-svg_elements_text_rotate
prior versions are marked as support unknown (spoiler: they did not support)

when i want to see what support was added between versions, it is misleading to leave out the features that their support was previously unknown. see eg, it is absent from here:
https://caniuse.com/?compare=safari+16.3,safari+16.4,safari+16.5&compareCats=all

**Comment by Sora2455** [comment]
The fact that the URL path starts with "mdn-" means that this data doesn't come from caniuse, but MDN (specifically https://github.com/mdn/browser-compat-data). You're lodging your issue on the wrong repo.

**Comment by Fyrd** [comment]
The comparison feature only works for the caniuse data, not MDN BCD data, which is the reason why the example you gave is not included (it's not related to features with unknown support).

If you'd like BCD data to be shown in the support comparison you may want to file a different ticket, though there are no plans to do so currently as its dataset is significantly larger so the comparison page would be pretty huge.
