### ISSUE TITLE
Add column for React

### ISSUE THREAD

**Issue by jfbrennan** [Fyrd/caniuse#6699]
Considering how React frequently prevents thousands of developers from using new HTML features like `inert`, I'd propose adding a "React" column in the support tables. Right next to IE seems like the appropriate place for it.

**Comment by Fyrd** [comment]
That might make sense for some HTML features but it would not for the many other web technologies tracked on caniuse. Additionally there's no plans to track any framework/library support on caniuse, so closing this ticket.

**Comment by jfbrennan** [comment]
I don't know, considering how widespread React is I think we have another IE situation here 😜
