### ISSUE TITLE
List supported browsers for each version of Angular framework

### ISSUE THREAD

**Issue by Pigeo** [Fyrd/caniuse#6704]
I need to know things like:
- What is the oldest Firefox version supported by Angular 13?
- What is the latest Angular version that supports Firefox 52?

Currently, trying to find such information is a nightmare:
- The [official Angular documentation](https://v13.angular.io/guide/browser-support) says "2 most recent major versions [at the date of release of this Angular version]", which is totally unhelpful (when did that particular Angular version was released? Are they meaning "2 most recent major versions... at the date of first release of this major Angular version", or "... at the date of release of latest minor version of this Angular major version" ?? And what was the "2 most recent major versions" of this browser at that time?)
- Wikipedia and other main sources of information aren't giving this information either
- even Chat-GPT can't give you a proper list of all browser versions supported by a given Angular version (or vice-versa)

When searching for `angular` in [caniuse.com](https://caniuse.com/?search=angular), it says: "This framework is not part of any web browser, THUS support is not listed here." ==> this verbiage isn't very helpful: since angular framework is designed to be used on web browsers, it would be nice to have a compatibility matrix of supported web browsers for each version of Angular.
(and same thing for each major web frameworks)

**Comment by Pigeo** [comment]
I'm anticipating you're going to tell me that you don't have enough resources to add such compatibility matrixes for each major web frameworks, and that's perfectly fairly understandable, because that would require a lot of work. But maybe you could set-up a kind of REST API that would enable the developers of those web frameworks to populate (and update) those compatibility matrixes on caniuse.com?

**Comment by Fyrd** [comment]
While I sympathize with the issue stated here I'd like to keep caniuse for native web technologies alone. I'm also not to keen on going through the work to set up and manage an API for this purpose, if these frameworks aren't willing/able to update their own sites with this information, they probably couldn't be expected to reliably update the caniuse data either.

Probably the biggest challenge here is testing support, it's a lot easier to test a single web tech feature than an entire framework, which is probably why it's so hard to find this information. May be a worthwhile separate project.
