### ISSUE TITLE
Add Safari 16.5

### ISSUE THREAD

**Issue by manake** [Fyrd/caniuse#6713]
Add: Safari 16.5.

Fix: In Safari 16.5 nesting selector `&` is supported but https://caniuse.com/?search=nesting-selector says it's not.

**Comment by jensimmons** [comment]
That data actually comes from MND's BCD project. Open an issue there: https://github.com/mdn/browser-compat-data

**Comment by lukewarlow** [comment]
I've opened a PR to address this at the source. https://github.com/mdn/browser-compat-data/pull/19935

**Comment by manake** [comment]
Ah, I didn't know.

Thanks, I'm closing this then.
