### ISSUE TITLE
Edge 114 Beta now supports AVIF with "--enable-features=msEdgeAVIF"

### ISSUE THREAD

**Issue by tats-u** [Fyrd/caniuse#6715]
![image](https://github.com/Fyrd/caniuse/assets/12870451/02529134-670b-4245-89a9-9fbbc2b8b7e3)
Supports animated AVIF too

**Comment by StigNygaard** [comment]
Not by "default":
https://winaero.com/avif-support-is-now-available-in-microsoft-edge/
My Edge 115 Dev Edition doesn't yet show AVIFs in default setup. But it's good to se it's on its way...

**Comment by tats-u** [comment]
@StigNygaard I forgot I have changed boot option in the shortcut.
I reinstalled Edge Beta.

**Comment by tats-u** [comment]
The stable version doesn't support AVIF even with this flag... Seems to be opted out.
