### ISSUE TITLE
Chrome supports scrollbar-width behind a flag

### ISSUE THREAD

**Issue by lukewarlow** [Fyrd/caniuse#6718]
As of chrome canary 115, Chrome now supports [`scrollbar-width`](https://drafts.csswg.org/css-scrollbars/#scrollbar-width) behind the Experimental Web Platform Features flag.

**Comment by Fyrd** [comment]
Looks like `[scrollbar-width](https://caniuse.com/mdn-css_properties_scrollbar-width)` includes this info now.

**Comment by lukewarlow** [comment]
Yes but the caniuse CSS scrollbar styling listing doesn't have this information.
