### ISSUE TITLE
Baseline

### ISSUE THREAD

**Issue by stefanhamburger** [Fyrd/caniuse#6721]
[MDN](https://developer.mozilla.org/en-US/blog/baseline-unified-view-stable-web-features/) and [Google](https://web.dev/introducing-baseline/) will use the term "Baseline" to communicate which Web features are stable and supported across all three browser engines.

According to [this comment](https://github.com/web-platform-dx/feature-set/issues/132#issuecomment-1550419618), caniuse.com was consulted but it does not look like anything came off it. Are there any plans to add a Baseline label to caniuse.com, e.g. by highlighting which browser versions are part of Baseline in the compatibility table?

**Comment by Fyrd** [comment]
Yes, I plan on adding Baseline-related information in some form in the future and am in contact with some of the folks involved, that's all I can say on this for now. :)

**Comment by Schweinepriester** [comment]
<https://caniuse.com/ciu/news>

> Dec 12, 2023
>
> ### Baseline badges now on Can I use
> 
> Starting today, you will start noticing badges on feature tables that map to [Web Features](https://github.com/web-platform-dx/web-features/blob/main/README.md). These badges match those seen on [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Glossary/Baseline/Compatibility#badges) and offer a quick at-a-glance view of feature support based on the Baseline definition.
> 
> To learn more about the badges on Can I use and what they mean [see this web.dev announcement](https://web.dev/blog/baseline2023). If you'd like to learn more about Baseline see [this explanation](https://github.com/web-platform-dx/web-features/blob/main/docs/baseline.md) from the WebDX community group.
> 
> Note that the badges are intended as a helpful way to see if support meets a certain defined threshold, the full support table should always be consulted to learn details about a feature's support.

Example:

<https://caniuse.com/css-grid>

![image](https://github.com/Fyrd/caniuse/assets/2644614/d4562793-5654-491c-9e76-02d8e2264f79)

I believe this issue can be closed 0:-)
