### ISSUE TITLE
Browser Release Dates not available in data.json

### ISSUE THREAD

**Issue by dfabulich** [Fyrd/caniuse#6726]
In #2175, browser release dates were made available on caniuse.com, which is super useful. But, surprisingly, this information is not available in `data.json`.

I'm working on a project to estimate how long it typically takes for a browser version to reach widespread availability, but without this information, I had to consult another source of data at https://github.com/mdn/browser-compat-data/tree/main/browsers to convert browser versions to dates.

It would have been more convenient if this information had been available data.json somewhere!

**Comment by Fyrd** [comment]
It's available in the 2.0 version:
https://github.com/Fyrd/caniuse/blob/main/fulldata-json/data-2.0.json

**Comment by dfabulich** [comment]
I had no idea that existed! I've filed #6728 to update the README.
