### ISSUE TITLE
-webkit-appearance on IE mobile

### ISSUE THREAD

**Issue by dstorey** [Fyrd/caniuse#675]
IE 11 Mobile has been [updated](http://blogs.msdn.com/b/ie/archive/2014/07/31/the-mobile-web-should-just-work-for-everyone.aspx) to add `-webkit-appearance` support. 

It is in Windows 8.1 Update, which is currently on the developer preview, but will be rolled out to the public in due course.

It should probably be listed as partial as it only supports `-webkit-` (there is no standard so no prefix doesn't make sense and no one uses `-ms-appearance` so that doesn’t make sense either), and AFAICT it only supports `-webkit-appearance: none` as that is the one used time and again in the wild. The other values, not so much.

**Comment by Fyrd** [comment]
Added as partial with note. Thanks!
