### ISSUE TITLE
RegExp `unicodeSets` or `v` flag 

### ISSUE THREAD

**Issue by verhovsky** [Fyrd/caniuse#6750]
https://v8.dev/features/regexp-v-flag

https://github.com/tc39/proposal-regexp-v-flag says that

> [SpiderMonkey/Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1713657), shipping in Firefox 116
>[V8/Chrome](https://bugs.chromium.org/p/v8/issues/detail?id=11935), enabled by default in V8 v11.2 / Chrome 112 (behind the --harmony-regexp-unicode-sets flag in earlier versions)
>[JavaScriptCore/Safari](https://bugs.webkit.org/show_bug.cgi?id=241593), enabled by default in [Safari Technology Preview 166](https://webkit.org/blog/13964/release-notes-for-safari-technology-preview-166/)

So it's a stage 4 proposal but you can already use it (without any flags) on Chrome 112 and Node 20 and Firefox 116

**Comment by atjn** [comment]
This is tracked now via the MDN dataset: https://caniuse.com/mdn-javascript_builtins_regexp_unicodesets

**Comment by Fyrd** [comment]
Closing as per above
