### ISSUE TITLE
Chromium subgrid status

### ISSUE THREAD

**Issue by Ugoku** [Fyrd/caniuse#6757]
Subgrid currently shows as unavailable in Chromium: https://caniuse.com/css-subgrid
However, it's available behind a flag from version 114 on, and will be enabled by default in version 116 🎉 

Source: https://chromestatus.com/feature/5663795354533888 and various DevRel tweets

**Comment by Schweinepriester** [comment]
I'll amend https://github.com/Fyrd/caniuse/pull/6754 to cover the flag as well B-)
