### ISSUE TITLE
Chrome for Android versions are missing versions lower current stable

### ISSUE THREAD

**Issue by philippmoehler0440** [Fyrd/caniuse#6758]
Hi there,

no matter which feature I look at, for android only the support till 4.4.4 and the last stable version is shown.

Example:

Currently we are at chrome 114 and caniuse shows:

![image](https://github.com/Fyrd/caniuse/assets/39621103/0c86516f-709b-4333-a4e5-8c874c66cf26)

full-data.json contains:

`"android":{"2.1":"n","2.2":"n","2.3":"n","3":"n","4":"n","4.1":"n","4.2-4.3":"n","4.4":"n","4.4.3-4.4.4":"n","114":"y"}`
If I go back in the commit history it seems, that this was handled all the time on this way.

Is there a reason for showing the latest stable only?

Thanks in advance!

**Comment by atjn** [comment]
Yes there is, check out this answer: https://github.com/Fyrd/caniuse/issues/3518#issuecomment-308931205

**Comment by philippmoehler0440** [comment]
Thank you @atjn, that is a sufficient explanation
