### ISSUE TITLE
Lottie-Files attribute <lottie-player>  and support

### ISSUE THREAD

**Issue by Stefan-Espant** [Fyrd/caniuse#6761]
Is it possible that the html element could be added to caniuse.com?

**Comment by Schweinepriester** [comment]
what exactly do you mean? do you have a link?

**Comment by Schweinepriester** [comment]
as lottie-player [is](https://github.com/LottieFiles/lottie-player) 

> a Web Component for easily embedding and playing Lottie animations and the Lottie-based Telegram Sticker (tgs) animations in websites.

it's not a browser web tech and as such probably doesn't fit for caniuse. also couldn't find a support table on their end. perhaps open an issue over there at <https://github.com/LottieFiles/lottie-player>?

**Comment by Fyrd** [comment]
Closing as per above
