### ISSUE TITLE
Add Edge score to homepage

### ISSUE THREAD

**Issue by peterlukerow** [Fyrd/caniuse#6762]
On the home page there is a "Browser Score" section that allows you to see overall scores of what canIUse tracks for both current and latest dev versions.

At present this only includes Chrome, Firefox and Safari, can Edge be added to this list?

**Comment by Fyrd** [comment]
I decided to keep it as one browser per engine, so Edge was removed since it switched to Chromium as support would be near-identical to Chrome.

**Comment by peterlukerow** [comment]
Hmmm... but both MS and Chrome contribute to the engine and one can get ahead of the other depending on when they pull the latest updates that have been contributed.

If you don't want to add Edge then could we perhaps have it relabelled as "Chromium Based" or similar since, as I'm sure you know, "Chrome" is Googles browser not the engine.
