### ISSUE TITLE
caniuse Data or API / Question ( Not Issue )

### ISSUE THREAD

**Issue by sawacrow** [Fyrd/caniuse#6766]
Hello,

I want to make a project that queries CSS properties with caniuse.json data.
But data.json format is not suitable for querying CSS properties separately ?

Is there a method to this?

I want to find the css property of the loop.

**Comment by Fyrd** [comment]
For individual CSS properties you'll want the MDN BCD data set, see here:
https://github.com/mdn/browser-compat-data/tree/main/css/properties
and the package info here:
https://www.npmjs.com/package/@mdn/browser-compat-data
