### ISSUE TITLE
Post

### ISSUE THREAD

**Issue by aws11142** [Fyrd/caniuse#6782]
[GIWA.COM](www.giwa.COM)
<https://fedoraproject.org/wiki/Licensing:MIT#Modern_Style_with_sublicense>.

"Submit" means to use some mode of digital communication (for example,
without limitation, mailing lists, bug tracking systems, and source
code version control systems administered by Fedora) to voluntarily
provide a Contribution to Fedora.

"Unlicensed" means not Licensed.

"Work" means a copyrightable work of authorship. A Work may be a
portion of a larger Work, and a Work may be a modification of or
addition to another Work.

"You" means the individual accepting this instance of the FPCA.

1. Copyright Permission Required for All Contributions.

If You are not the copyright holder of a given Contribution that You
wish to Submit to Fedora (for example, if Your employer or university
holds copyright in it), it is Your responsibility to first obtain
authorization from the copyright holder to Submit the Contribution

**Comment by Fyrd** [comment]
Not sure what's being asked for here.
