### ISSUE TITLE
modules in service workers

### ISSUE THREAD

**Issue by johndeighan** [Fyrd/caniuse#6786]
I need to know which browsers/version support modules in service workers. Chrome does, but it seems like Firefox does not. 

Background: I use Svelte and SvelteKit. They give an example service-worker.js file, but specify that the example will only work in a browser that supports modules in service workers.

**Comment by Fyrd** [comment]
Looks like this is covered by this table:
https://caniuse.com/mdn-api_serviceworker_ecmascript_modules
