### ISSUE TITLE
Unexpected UC Browser version

### ISSUE THREAD

**Issue by SuperOleg39** [Fyrd/caniuse#6794]
Hello!

Found that UC Browser version is 15.5 in current caniuse data.
But can't find any relative versions, because of real last version is 13.4.

Or I miss something?

**Comment by Artoria2e5** [comment]
The latest on Chinese app markets is not 15.5, but 16.0. Companies like UC are not exactly known for having versions that make sense... https://www.wandoujia.com/apps/36557/history

**Comment by SuperOleg39** [comment]
> The latest on Chinese app markets is not 15.5, but 16.0. Companies like UC are not exactly known for having versions that make sense... https://www.wandoujia.com/apps/36557/history

Thanks a lot! Don't find this link in Google)

**Comment by Artoria2e5** [comment]
UC seems to use a very different version scheme overseas. I found this one by web search "UC浏览器 apk".
