### ISSUE TITLE
Safari on iOS 15.7 isn’t displayed on the site

### ISSUE THREAD

**Issue by dieulot** [Fyrd/caniuse#6798]
On caniuse.com, there’s data for “Safari & other browsers on iOS 15.6” but not for iOS 15.7, which is an important version as it’s the last version for some devices — it has more users than 15.6.

iOS 15.7 incorporates Safari 15.6 still, so its data should be grouped with iOS 15.6.

caniuse.com thus leads you to believe that Safari 15.6 on iOS has 0.58% of usage while in reality it has 1.55%. That discrepancy is growing every month.

## Confirming that the problem exist

Without knowing the inner working of this repo, the easiest way to confirm that this problem — 15.7 not being already grouped with 15.6 — exists is through [the CSV](https://gs.statcounter.com/os-version-market-share/ios/mobile-tablet/chart.php?device=Mobile%20%26%20Tablet&device_hidden=mobile%2Btablet&multi-device=true&statType_hidden=ios_version&region_hidden=ww&granularity=monthly&statType=iOS%20Version&region=Worldwide&fromInt=202207&toInt=202307&fromMonthYear=2022-07&toMonthYear=2023-07&csv=1) of [GlobalStats for iOS devices](https://gs.statcounter.com/os-version-market-share/ios/mobile-tablet/worldwide) (the website isn’t granular enough) and comparing the difference with [caniuse.com’s numbers](https://caniuse.com/mdn-css_selectors_modal) among different versions.

| iOS version | iOS 15.6 | iOS 15.7 | iOS 16.0 |
| - | - | - | - |
| GlobalStats 2023-07 % of iOS | 3.2 | 5.44 | 3.67 |
| caniuse % | 0.58 | — | 0.65 |
| Difference | 5.52x | ∞ | 5.65x

**Comment by Fyrd** [comment]
Thanks! Has now been fixed.
