### ISSUE TITLE
Nesting parent '&' selector data seems to be out of date or missing

### ISSUE THREAD

**Issue by mirisuzanne** [Fyrd/caniuse#6808]
https://caniuse.com/mdn-css_selectors_nesting

- The links to MDN documentation and data are missing
- From testing, it seems clear to me that the `&` selector is supported in Firefox 117+

**Comment by Fyrd** [comment]
This data's provided by [BCD](https://github.com/mdn/browser-compat-data) so can't fix anything from this repo... though it looks like it may have been updated since you shared this as I see Firefox 117+ as supported now.

**Comment by mirisuzanne** [comment]
Oh yeah, the link is still broken, but the data looks better. I'll close out here.
