### ISSUE TITLE
Global data doesn't match `alt-ww` region since `1.0.30001520`

### ISSUE THREAD

**Issue by MonstraG** [Fyrd/caniuse#6811]
Whilst using https://browsersl.ist, I found a problem in how it was reporting coverage wrongly, and [traced ](https://github.com/browserslist/browsersl.ist/issues/512#issuecomment-1693954679) the problem to here.

It seems that `30001520` changed `usage_global` in `data.json` quite considerably, but regional data, and therefore `alt-ww` (which in principle should match `usage_global` exactly), stayed the same.

That resulted in `cover: 80%` request in `alt-ww` only covering `73.7%`, for [example](https://browsersl.ist/#q=cover+80%25).

Regional data seems to be updated around monthly.

Can I request regional data to be updated off-schedule to fix this mismatch?

**Comment by Fyrd** [comment]
Ah you're right, looks like the regional data didn't get pushed for this month. Should be fixed now, apologies and thanks for reporting this!
