### ISSUE TITLE
caniuse.com analytics import fails without any error message if you choose a Google account with no GA access

### ISSUE THREAD

**Issue by isGabe** [Fyrd/caniuse#682]
Managing multiple Google accounts can be a pain, as we all know. I ran into an issue where I was choosing the wrong account, which I thought had GA access, but it did not. The import process on caniuse.com would stop when I picked that account, but with no visible errors to let me know what was happening. I found the error by looking at the console:

`There was an error querying accounts: User does not have any Google Analytics account. retrieve_ga.js:138`

Step to reproduce:
1. Click Settings, Add usage source > from Google Analytics: Import.
2. In the auth modal that pops up, choose a Google account without any analytics access attached.
3. The import process stops without visible errors.

![caniuse-analytics-error](https://cloud.githubusercontent.com/assets/1437322/3907932/49a8d580-22ff-11e4-87a1-37bc36775588.gif)

**Comment by Fyrd** [comment]
No longer relevant for new GA4 analytics importer, so closing.
