### ISSUE TITLE
Add Samsung Internet 22–23

### ISSUE THREAD

**Issue by nilaallj** [Fyrd/caniuse#6822]
Samsung Internet 22 was released on July 14, 2023 and runs Chromium 111.
Samsung Internet 23 is currently in beta and runs Chromium 115.

Got Chromium versions from the following user agent strings:
https://user-agents.net/s/IRS0L3EBpN
https://user-agents.net/s/IRS0pRSiDD

Filing this issue since it's not possible to add browser versions through PRs.

**Comment by Fyrd** [comment]
Thanks, have added version 22 for now.

**Comment by Fyrd** [comment]
23 was added since this was opened as well, so closing.
