### ISSUE TITLE
Add JFIF File format

### ISSUE THREAD

**Issue by vardumper** [Fyrd/caniuse#6826]
I just ran into this file format for the first time ever. 
Yii2 php framework has a method call getExtensionsByMimeType() 
It returns this:
```
array (size=6)
  0 => string 'jfif' (length=4)
  1 => string 'jpe' (length=3)
  2 => string 'jpeg' (length=4)
  3 => string 'jpg' (length=3)
  4 => string 'pjp' (length=3)
  5 => string 'pjpeg' (length=5)
```

So my first reaction what the ho0ps is `jfif` and "can I even use this? Does any browser support it"

**Comment by Fyrd** [comment]
Looks to be more of an older image format, I don't think it's used commonly enough to be worth tracking. A quick test though suggests Firefox & Chrome support it, but Safari does not.
