### ISSUE TITLE
Font-size-adjust needs update to new spec

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#6827]
`font-size-adjust` was added to Can I Use years ago. Since then, two new details have been added to what this feature should do. In 2023, to fully support how `font-size-adjust` is suppose to work, a browser should have support for:

1. basic syntax
2. two-value syntax
3. `from-font` value

The page at https://caniuse.com/font-size-adjust only reflects the first, the basic syntax. 

There is a page coming from MDN BCD data: https://caniuse.com/mdn-css_properties_font-size-adjust_two-values which shows the support for two-value syntax. 

There's nothing available about `from-font` (which is supported in Safari 17.0, and not yet in Firefox). 

It seems like MDN BCD should have a separate data table for each of these three parts of the whole, where the details can be found about which browser added support for each when.

And that Can I Use should evolve the overall feature page to include how browsers are doing overall with `font-size-adjust` as a whole. Which would mean any browser that doesn't support all three parts gets "partial support" designation. 

Does that make sense to you all? If so, I can create the PR. But I wanted to discuss a plan first.

**Comment by Fyrd** [comment]
Agree with all of these! Thanks for bringing this up, happy to receive a PR on the changes.

I see `from-font` is now on BCD as well and found on caniuse:
https://caniuse.com/mdn-css_properties_font-size-adjust_from-font

**Comment by jensimmons** [comment]
Here's the PR: https://github.com/Fyrd/caniuse/pull/6841

**Comment by jensimmons** [comment]
Done. Thanks!
