### ISSUE TITLE
caniuse: snappy

### ISSUE THREAD

**Issue by 3xploiton3** [Fyrd/caniuse#6831]
[snappy](https://github.com/google/snappy)

Snappy is a compression/decompression library. It does not aim for maximum compression, or compatibility with any other compression library; instead, it aims for very high speeds and reasonable compression. For instance, compared to the fastest mode of zlib, Snappy is an order of magnitude faster for most inputs, but the resulting compressed files are anywhere from 20% to 100% bigger. (For more information, see "Performance", below.)

**Comment by jensimmons** [comment]
Snappy is a third-party tool, not a web-standards-based web technology. 

The purpose of Can I Use is not to offer a list of popular third-party tools. It's to document how many browsers have support for web-standards-based web technology built into their engine.

**Comment by Fyrd** [comment]
Closing as per @jensimmons' comment
