### ISSUE TITLE
Safari 17.0 for macOS has shipped 

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#6832]
As announced at Apple's event this week, Safari 17.0 will arrive on Monday, September 18. I see it's listed as "17", but it would probably be better for it to say "17.0" on the compat charts.

This might also be a handy time to add Safari 17.1 into the CIU system, so that it's possible to add data about it sometime in the future.

**Comment by jensimmons** [comment]
To clarify, Safari 17.0 for iOS and iPadOS will arrive today, Monday, September 18. 
Safari 17.0 for macOS will arrive on Sept 26.

**Comment by bershanskiy** [comment]
Relevant blog post from WebKit blog: https://webkit.org/blog/14445/webkit-features-in-safari-17-0/

**Comment by Elycin** [comment]
Writing to subscribe to this - This is a huge breakthrough in terms of technical rollout given the demographics of mobile users.

Finally means that a lot of transcoding pipelines can start utilizing dedicated encoders, and save on bandwidth and storage costs.

Looking forward to seeing browser availability.

**Comment by jensimmons** [comment]
@Elycin Which technology are you referring to?

**Comment by Elycin** [comment]
> @Elycin Which technology are you referring to?

HEIC/AV1 support.

**Comment by jensimmons** [comment]
Oh hello @Fyrd. Could you update so that Safari 17.0 is the current version on Mac? It shipped yesterday (for macOS Sonoma, macOS Ventura, and macOS Monterey).

**Comment by Fyrd** [comment]
Done!
