### ISSUE TITLE
Setup GitHub sponsoring?

### ISSUE THREAD

**Issue by romainmenke** [Fyrd/caniuse#6846]
At work we sponsor all our dependencies solely through GitHub bulk sponsoring.
Is it possible to setup GitHub sponsoring for caniuse?

I know this can be connected somehow to open collective, maybe a similar setup is also possible for patreon?

**Comment by Fyrd** [comment]
Sounds good, I hadn't heard of this! Will look into it, thanks for the suggestion :)

**Comment by Fyrd** [comment]
GitHub sponsoring has now been added, if there's some follow-up connection necessary let me know!

**Comment by romainmenke** [comment]
Everything seems setup perfectly from our end!
Thank you for this!
