### ISSUE TITLE
Release notes for Safari 17.2 beta

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#6873]
Just going to put this here:
https://developer.apple.com/documentation/safari-release-notes/safari-17_2-release-notes

Highlights include:
• Fullscreen API on iPhone
• updates to CSS Motion Path and Masking
• `cap`, `rcap`, `rex`, `ric` & `rch` units
• CSS Highlight API
• name attribute in `<details>` element
• import attributes
• WebCodecs HEVC
• preloading responsive images
• Fetch Priority
• login cookies copied over when saving website to Home Screen on iOS and iPadOS (just like macOS)
• blob partitioning

**Comment by Schweinepriester** [comment]
@Fyrd there seems to be push to the repo missing 😢
wanted to create a PR for all the changes, but 17.2 is only on the website, not in the data…
