### ISSUE TITLE
COLRv0 fonts do not appear to be supported in Safari

### ISSUE THREAD

**Issue by HM100** [Fyrd/caniuse#6878]
As according to https://pixelambacht.nl/chromacheck/
![IMG_0482](https://github.com/Fyrd/caniuse/assets/30199227/845ed4e4-2fa8-425a-a761-53feab90748d)

**Comment by rutopio** [comment]
It appears to be a bug. I have submitted a PR about it.

Bug report: COLR support vanished between Safari 16 and 17: [WebKit Bugzilla Bug 262223](https://bugs.webkit.org/show_bug.cgi?id=262223)

**Comment by Schweinepriester** [comment]
@rutopio Thank you for linking that bug, I just couldn't find https://github.com/Fyrd/caniuse/issues/1018#issuecomment-1737111439 again 😅
Also mentioning it to have direct link here.

**Comment by Schweinepriester** [comment]
I believe this can be closed as https://github.com/Fyrd/caniuse/pull/6883#event-10839326292 has been merged.
