### ISSUE TITLE
proposal relative indexing method: .at()

### ISSUE THREAD

**Issue by ikarosu** [Fyrd/caniuse#6879]
TC39: [github.com](https://github.com/tc39/proposal-relative-indexing-method/)/tc39/proposal-relative-indexing-method/](github)
MDN:
Array.prototype.at()
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/at
String.prototype.at()
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/at

**Comment by Ugoku** [comment]
Already available: 

* https://caniuse.com/mdn-javascript_builtins_array_at
* https://caniuse.com/mdn-javascript_builtins_string_at
