### ISSUE TITLE
AV1 on Safari on macOS

### ISSUE THREAD

**Issue by o-t-w** [Fyrd/caniuse#6884]
Caniuse shows AV1 as green on iOS but not macOS. I believe this is because only the new iPhone has a hardware decoder for this codec, rather than anything to do with the browser itself? The new M3 chips all support AV1 so this data should probably be updated to show as green for Safari on macOS.

**Comment by Schweinepriester** [comment]
Will be fixed by https://github.com/Fyrd/caniuse/pull/6882 :)

**Comment by tats-u** [comment]
@o-t-w This is because no devices for macOS ones supporting AV1 were available as of #6837, as you believe. Now that M3 MBP is available, we can mark AV1 as partially supported in macOS Safari *now*.
