### ISSUE TITLE
Add `Promise.withResolvers`

### ISSUE THREAD

**Issue by csvn** [Fyrd/caniuse#6892]
Proposal is stage 3: https://github.com/tc39/proposal-promise-with-resolvers

Seems to be [implemented in Chrome currently](https://groups.google.com/a/chromium.org/g/blink-dev/c/JL4uXtfrCdU/m/aK1t8LJMAAAJ).

```ts
function demo() {
  const { promise, resolve, reject } = Promise.withResolvers();
  
  // ...
  event.on('end', () => resolve());
  event.on('error', err => reject(err));
 
  return promise;
}
```

**Comment by opusonline** [comment]
As of today, it is even implemented also in Firefox since v121 and has already landed in Safari Technology Preview.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers#browser_compatibility

**Comment by Fyrd** [comment]
Available at https://caniuse.com/mdn-javascript_builtins_promise_withresolvers
