### ISSUE TITLE
Update MDN BCD logo

### ISSUE THREAD

**Issue by pepelsbey** [Fyrd/caniuse#6902]
The current MDN BCD logo’s font looks off. It’s probably caused by some outline or export mistakes. The last letter is even clipped a bit at certain resolutions. But the worst is the “b”.

![bcd](https://github.com/Fyrd/caniuse/assets/105274/6d1d2d30-577a-46ed-b649-d2c47ea13b6c)

Unfortunately, I couldn’t find a repository for Can I use to send a PR (still happy to do it), so here’s the updated file. It’s also slightly smaller.

![mdn-bcd](https://github.com/Fyrd/caniuse/assets/105274/777b1d58-9b73-4c25-897f-39a391080e84)

**Comment by Fyrd** [comment]
Many thanks, much better!! The image has now been replaced.
