### ISSUE TITLE
Remove https://caniuse.com/css-scroll-timeline

### ISSUE THREAD

**Issue by bramus** [Fyrd/caniuse#6906]
The feature described at https://caniuse.com/css-scroll-timeline dates back to an old specification that was retracted and has since been replaced by https://drafts.csswg.org/scroll-animations-1/

The features covered by https://drafts.csswg.org/scroll-animations-1/ as included in MDN’s browser-compat-data, exposed on these URLs:

- https://caniuse.com/mdn-css_properties_scroll-timeline
- https://caniuse.com/mdn-css_properties_view-timeline
- https://caniuse.com/mdn-css_properties_animation-timeline
- https://caniuse.com/mdn-css_properties_timeline-scope

I’m not sure how deprecation works for this repo. Can `/features-json/css-scroll-timeline.json` simply be removed or is their some other process that needs to be followed?

**Comment by bramus** [comment]
Any reason why this is blocked? I’m asking because people are getting confused about this – e.g. https://x.com/meelix_protogen/status/1787711699933401483

If deletion is not an option, maybe there is a way to deprioritize this result? After all, it’s a feature from an unofficial spec that never made it beyond the point of experimental implementation.

**Comment by jensimmons** [comment]
I agree. This needs to be updated.

**Comment by bramus** [comment]
@Fyrd Friendly ping on removing this as people are very confused about the state of Scroll-Driven Animations when looking up `"scroll-timeline"` on CanIUse.

Most recently the folks from Syntax FM (Wes Bos and Scott Tolinski) couldn’t figure out why CanIUse was showing this outdated data – https://youtu.be/JhTMIBLCaNw?si=SLW_izU1mBPTTfkG&t=949

I believe this `@scroll-timeline` entry can simply be removed as it never was part of a spec that made it beyond an editor’s draft + also never made it unflagged into a browser.

What can I do to help to get this through? Do you need more info on this?

**Comment by jensimmons** [comment]
The next step @bramus is to make a pull-request. Can I Use depends on people to volunteer to make ideas into PRs for review.

**Comment by Fyrd** [comment]
Sorry, I think I was originally wanting to update the feature as mentioned in #6956 as I generally prefer not to remove features (since people will often learn about deprecated features anyway and want to learn more about them). That said for now I agree it's best to avoid the confusion by removing it entirely which has been done, will follow up by adding a search result on the site for the deprecated spec.

Thanks for reminding me about this!

**Comment by bramus** [comment]
Thank you @Fyrd!
