### ISSUE TITLE
How often is MDN BCD data refreshed?

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#6912]
This is a question, rather than an issue.

How often are pages like this one 
https://caniuse.com/mdn-css_properties_counter-set
updated with data?

A PR landed two days ago with lots of Safari 17.2 updates, include this page:
https://github.com/mdn/browser-compat-data/blob/main/css/properties/counter-set.json
but Can I Use still show no support. 

I was guessing it updates every 24 hours, but maybe it's once a week? I'm curious how often it refreshes.

**Comment by Fyrd** [comment]
It's currently once a week (Friday night), which I believe matches how often the MDN Web Docs are updated with the info as well.

**Comment by jensimmons** [comment]
Thank you!
