### ISSUE TITLE
Incorrect URL (404) for MDN documentation on CSS Nesting Selectors

### ISSUE THREAD

**Issue by ozhasta** [Fyrd/caniuse#6917]
**Issue Description:**

There is an error on CanIUse.com regarding the link to MDN documentation on CSS Nesting Selectors. The current link is "https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selectors", but the correct link should be "https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector".

**Step-by-Step Error Reproduction:**

1. Visit the page at https://caniuse.com/mdn-css_selectors_nesting.
2. Click on the link under "See full reference on MDN Web Docs"

**Expected Behavior:**

The link should redirect to "https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector".

I kindly request the necessary corrections to be made to fix this issue. Thank you.

**Comment by queengooborg** [comment]
Hi @ozhasta!  That feature data comes from the [browser-compat-data](https://github.com/mdn/browser-compat-data) repository, including the MDN URL.  I've just created a pull request to fix the link!

**Comment by ozhasta** [comment]
@queengooborg Sorry, I reported the problem to the wrong repo, thanks for your attention and time.
