### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by Bilge** [Fyrd/caniuse#6925]
* https://caniuse.com/
* https://downforeveryoneorjustme.com/caniuse.com?proto=https

![image](https://github.com/Fyrd/caniuse/assets/470626/f9bf2d3b-2318-46cc-aea4-1a42f5344ebc)

🤷🏻

**Comment by Fyrd** [comment]
Thanks for reporting, yeah there's been some intermittent outages lately, still trying to determine the cause.

**Comment by Fyrd** [comment]
Seems to have stabilized now, so closing this ticket.
