### ISSUE TITLE
iOS Safari fullscreen API support 

### ISSUE THREAD

**Issue by lukewarlow** [Fyrd/caniuse#6928]
Caniuse says that iOS Safari 17.2 now fully supports the fullscreen API. However it doesn't appear to be true (iPadOS only restriction still exists). It seemed to be in the betas but not make it to final release.

**Comment by jensimmons** [comment]
This is correct. It was on in Safari 17.2 beta 1 for iOS, but was later put back into Preview (available behind a flag only). 

https://front-end.social/@jensimmons/111495353776714977

Support for Fullscreen API for iOS  is also not on by default in Safari 17.3 beta. We ask that people help beta test by flipping the flag. 

(Fullscreen is still supported on macOS and iPadOS, as it has been for years.)
