### ISSUE TITLE
Allow changing the default option for usage percentage

### ISSUE THREAD

**Issue by SebastianZ** [Fyrd/caniuse#6934]
Currently, the option for the percentage of users is not configurable.

Users should be able to choose which one is selected by default, so they immediately see the value they are most interested in.

(This was previously also suggested in https://github.com/Fyrd/caniuse/issues/4058#issuecomment-443142014 and https://github.com/Fyrd/caniuse/issues/6813#issuecomment-1696830786.)

Sebastian

**Comment by Fyrd** [comment]
This option is now available under [Default display settings](https://caniuse.com/ciu/settings#display):

<img width="719" alt="Screen Shot 2024-01-19 at 9 58 34 PM" src="https://github.com/Fyrd/caniuse/assets/432336/5bab4ae6-e566-4284-8341-7d86444a784d">

**Comment by SebastianZ** [comment]
Thanks you very much for adding this!

Sebastian
