### ISSUE TITLE
`quality` parameter supported in api.HTMLCanvasElement.toBlob in Safari since version 11

### ISSUE THREAD

**Issue by francescorn** [Fyrd/caniuse#6935]
The `quality` parameter in api.HTMLCanvasElement.toBlob is supported by Safari os and safari iOS as of version 11.

It is updated in MDN from the issue: https://github.com/mdn/browser-compat-data/issues/21770#issuecomment-1875681179
commit: https://github.com/francescorn/browser-compat-data/commit/f88de142160440390fa619319db508dc623dcb0f

Webkit commit (which was committed two months before Safari Version 11's release and when toBlob started being supported in Safari Version 11 https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob):
https://github.com/WebKit/WebKit/commit/d79600d2a2e805ab46022cfa1d550bc90067b01a

@opusonline

**Comment by Schweinepriester** [comment]
Compared to https://github.com/mdn/browser-compat-data/issues/21770#issuecomment-1875146488 the data at https://caniuse.com/mdn-api_htmlcanvaselement_toblob_quality_parameter has been updated (surely by refetching/redeploying the MDN data) by now:

<img width="1509" alt="Bildschirmfoto 2024-01-06 um 13 19 00" src="https://github.com/Fyrd/caniuse/assets/2644614/1ede3535-ea08-421b-acd5-dbb13c8d60f8">

Therefore I believe this issue can be closed :)
