### ISSUE TITLE
Wrong supported Firefox versions for options.signDisplay parameter: negative value

### ISSUE THREAD

**Issue by m-akinc** [Fyrd/caniuse#6940]
The page for:
[JavaScript built-in: Intl: NumberFormat: NumberFormat() constructor: options.signDisplay parameter: negative value](https://caniuse.com/mdn-javascript_builtins_intl_numberformat_numberformat_options_signdisplay_parameter_negative)
shows that Firefox added support in version 93, but it was [added in version 116](https://hg.mozilla.org/integration/autoland/rev/9f247edc6c08).
![image](https://github.com/Fyrd/caniuse/assets/7282195/3a3faefc-ff0c-49a1-8749-3a01ac71a5d6)

**Comment by Fyrd** [comment]
This data comes from [MDN BCD](https://github.com/mdn/browser-compat-data) (file [here](https://github.com/mdn/browser-compat-data/blob/main/javascript/builtins/Intl/NumberFormat.json)), please report the issue there, thanks!
