### ISSUE TITLE
tabs.saveAsPDF() exists in Firefox

### ISSUE THREAD

**Issue by Hoxolotl** [Fyrd/caniuse#6941]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/saveAsPDF

I couldn't find "saveAsPDF" in caniuse.

Kind regards, keep up the awesome work!

**Comment by Fyrd** [comment]
Browser extensions are currently not tracked on caniuse so no plans to include this.
