### ISSUE TITLE
Are Google Anyltics imports local-only?

### ISSUE THREAD

**Issue by Simon-Hayden-iteratec** [Fyrd/caniuse#6955]
Because our client was asking, if it is safe to use their Google Anyltics data to caniuse, I tried to understand if the file may be sent to some server or not.

I found the original change log entry here: https://caniuse.com/feed/116
While it states that all data is local, it's from 2011. I'd be surprised if this has changed, however, there is no mention on the importer what will happen with the data.

Either way - local or not - I would also request adding this information to the [importer](https://caniuse.com/ciu/import).

**Comment by Fyrd** [comment]
I can confirm they're local only, yes. There used to be a link to this bare-banes TOS page: https://caniuse.com/tos.html
Will indeed need to link to that again with the new importer, thanks for the reminder!

**Comment by Simon-Hayden-iteratec** [comment]
Thanks a lot for your response and effort :)

You can close this issue if you want. From my side it's resolved.
