### ISSUE TITLE
JavaScript statement: import: Import attributes (with syntax): with {type: 'json'} and {type:'css'} support chrome 123

### ISSUE THREAD

**Issue by juner** [Fyrd/caniuse#6973]
import attribute support chrome 123 (canary) !

# chrome platform status: Feature: Import attributes 'with' syntax
https://chromestatus.com/feature/5205869105250304

# import attribute {type: 'css'} and {type:'json'} sample
https://codepen.io/juner/pen/rNRoqMo

**Comment by jogibear9988** [comment]
issue for this was here: https://issues.chromium.org/issues/40067513

**Comment by jogibear9988** [comment]
Safari also has support: https://webkit.org/blog/14787/webkit-features-in-safari-17-2/

**Comment by jogibear9988** [comment]
it's already merged in there

**Comment by juner** [comment]
thank you!
