### ISSUE TITLE
Alignment everywhere is here!

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#6985]
Yeas ago, when the CSS Working Group was creating Grid, they realized that the alignment features from Flexbox should also work inside Grid. And then they decided, actually, they should work everywhere — including Flow layout and Table layout. 

So the [Box Alignment](https://www.w3.org/TR/css-align-3/) specification was born. 

Now, finally browsers are implementing. It will be supported in Safari 17.4 and Chrome 123. 

It would be great to have a page on Can I Use about this. It's not a new property. It's a new aspect to layout / a new concept.

**Comment by jensimmons** [comment]
https://chromestatus.com/feature/5159040328138752
https://developer.apple.com/documentation/safari-release-notes/safari-17_4-release-notes

**Comment by Schweinepriester** [comment]
Excited as well, but isn't this issue the same as your own https://github.com/Fyrd/caniuse/issues/6978 as well as https://github.com/Fyrd/caniuse/issues/2537? 🤔
At least the latter also seems to point to `css-align-3`, but maybe the meaning has changed over time or it's different parts (flex & grid vs. outside of those)…?

**Comment by jensimmons** [comment]
Hahahaha, I filed _last week_ and forgot? Zeesh.
