### ISSUE TITLE
iOS 16 supports AVIF video

### ISSUE THREAD

**Issue by phil2phil** [Fyrd/caniuse#6999]
https://caniuse.com/avif

https://developer.chrome.com/docs/lighthouse/performance/uses-webp-images states "Note that webp, avif images and webm videos will not work on iPhones below iOS 16."

https://webkit.org/blog/14445/webkit-features-in-safari-17-0/ states "Safari 17.0 adds support for AV1 video on devices with hardware decoding support".

Please update the documentation.

**Comment by Fyrd** [comment]
Closing as per @jensimmons 's explanation.
