### ISSUE TITLE
Support HTML/CSS renderers for print

### ISSUE THREAD

**Issue by liZe** [Fyrd/caniuse#7000]
Hi!

Would caniuse be interested in getting support for HTML/CSS renderers for print?

There are many tools that can generate PDFs and support paged media, such as WeasyPrint (disclaimer: I’m one of the maintainers), PagedJS, Vivliostyle, Prince… They don’t appear in websites visits, because they’re rarely used on public websites, but they’re "quite popular": for example, WeasyPrint is downloaded more than 1 million times a month, and it’s probably not the most widely used of the list 😄.

This topic has also been discussed a bit in #1510.

If you think that it would be nice, don’t hesitate to ping me, I can find some time to work on this!

If you think that it’s not worth it, no problem, we’ll find another way to advertise our supported features.

(And thanks for this amazing tool 💜)

**Comment by Fyrd** [comment]
Sounds like a great thing to track! But indeed out of scope for caniuse.com 

Perhaps if someone were to create a similar project (or like caniemail.com) specific to print renderers that would be great and I'd be happy to link there!
