### ISSUE TITLE
Add the CSS Anchor API

### ISSUE THREAD

**Issue by RentecTravis** [Fyrd/caniuse#7001]
The CSS Anchor API allows you to define positioning rules for an element to keep it on screen. A classic use case is tooltips. Normally you may want the tooltip above the element on the y axis. But if the element with a tooltip is too high up on the page, you may want the tooltip to below the element.

The Anchor API provides a way to do that in CSS so we don't have to re-invent the wheel every time we encounter this problem.

https://www.w3.org/TR/css-anchor-position-1/
https://developer.chrome.com/blog/tether-elements-to-each-other-with-css-anchor-positioning/

**Comment by Schweinepriester** [comment]
I share the excitement, but per [this comment](https://github.com/Fyrd/caniuse/issues/6471#issuecomment-1950609010) already at <https://caniuse.com/css-anchor-positioning>, right?

**Comment by RentecTravis** [comment]
@Schweinepriester ah, thanks. I had searched for "css anchor api" which I see now is incorrect.
