### ISSUE TITLE
Blink/Chrome does NOT support HTML defer attribute

### ISSUE THREAD

**Issue by jabcreations** [Fyrd/caniuse#7007]
Blink browsers such as Chrome do NOT support the defer attribute.

The follow will incorrectly return false in the developer console:

```
<html>
<head>
<script defer>
var r = document.getElementById('example');
console.log('r',r);
</script>
</head>

<body>

<div id="example"></div>

</body>
</html>
```

The correct behavior is to wait until the DOM has finished loading and _then_ execute the script element.

Tested and verified with Chrome 34 and 121.

**Comment by Fyrd** [comment]
My understanding of [the specification](https://html.spec.whatwg.org/multipage/scripting.html#attr-script-defer) is that the `defer` attribute is not expected to have any effect on `script` blocks, only external scripts.

"Classic scripts may specify defer or async, but must not specify either unless the src attribute is present"

MDN [also mentions](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#defer) "This attribute must not be used if the src attribute is absent (i.e. for inline scripts), in this case it would have no effect"
