### ISSUE TITLE
"TP"? Safari Technology Preview would be better abbreviated "STP"

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#7011]
I just noticed Safari Technology Preview is abbreviated "TP".

<img width="504" alt="Screenshot 2024-03-20 at 1 04 20 PM" src="https://github.com/Fyrd/caniuse/assets/108474/54b3a0dc-dbf9-4db4-a3c9-97b3645ca3ab">

Can we change this to "STP"?

**Comment by Fyrd** [comment]
Hmm, well it's used in place of a version number so that could potentially mean that it's referred to as "Safari STP" in places which I think would be wrong?

**Comment by jensimmons** [comment]
I don't expect that people will read the label at the top of the column, and then think it means "Safari STP". 

The S stands for Safari. STP is what people call it when they don't want to type or say Safari Technology Preview.

**Comment by Fyrd** [comment]
I'm referring to other places on the site or third party uses of the caniuse data where the browser name and version might get combined to refer to a specific build/version.

**Comment by jensimmons** [comment]
Oh that's interesting. Right. What kind of places? Do we have examples?

**Comment by Fyrd** [comment]
The browser score section is one place that comes to mind, not sure if there's others.

<img width="402" alt="Screen Shot 2024-03-23 at 5 26 56 PM" src="https://github.com/Fyrd/caniuse/assets/432336/ca4a2793-4490-48c8-a17c-7ed25129a54e">

If someday other browser's preview builds get explicitly added they'd probably also just state "Canary" or "Nightly" under the "Chrome" and "Firefox" headers, I think it's clear enough to visitors.
