### ISSUE TITLE
Declarative Shadow DOM in Chrome 90-110 needs a note

### ISSUE THREAD

**Issue by foolip** [Fyrd/caniuse#7025]
Note in https://developer.chrome.com/docs/css-ui/declarative-shadow-dom:

> Declarative Shadow DOM has been available since Chrome 90 and Edge 91, but it used an older non-standard attribute called `shadowroot` instead of the standardized `shadowrootmode` attribute.

It would be good if this was reflected in https://caniuse.com/declarative-shadow-dom with a note for Chrome 90-110. I'm not sure about Edge 90, but assume that comment is right and it was shipped in Edge 91.

**Comment by Fyrd** [comment]
Thanks, updated accordingly!

**Comment by foolip** [comment]
Thank you @Fyrd! https://github.com/Fyrd/caniuse/commit/0d04b2e12f62cb33e2bdf046df3216998b3a7be3 looks good to me.

**Comment by foolip** [comment]
Updating web-features in https://github.com/web-platform-dx/web-features/pull/885
