### ISSUE TITLE
CustomStateSet needs a caveat about Chrome

### ISSUE THREAD

**Issue by o-t-w** [Fyrd/caniuse#7027]
The CustomStateSet data is misleading. It lists Chrome as supporting the API even though it Chrome uses a deprecated syntax.

**Comment by Fyrd** [comment]
CustomStateSet data is provided via BCD, please [file an issue there](https://github.com/mdn/browser-compat-data/issues). (see [support data](https://github.com/mdn/browser-compat-data/blob/main/api/CustomStateSet.json))
