### ISSUE TITLE
Safari 3.1 supported <video> and <audio>

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#7050]
We had reason today to track down when media queries were first supported on the `video` element in Safari. After a lot of digging, we confirmed the work was done in 2007, and shipped in Safari 3.1. Oddly, though, Can I Use says `video` itself wasn't supported until Safari 4.0 in 2009. So we dug some more to make sure... and turns out, both `video` and `audio` shipped in Safari 3.1, not 4.0. 

I'll submit two PRs to update that data, but since it involves two files, I thought I'd file a single issue to discuss both in one place.

**Comment by jensimmons** [comment]
> Safari supports the `<video>` and `<audio>` media elements on iOS 3.0 and later and in Safari 3.1 and later on the desktop (Mac OS X and Windows).

https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Introduction/Introduction.html

**Comment by jensimmons** [comment]
Here's the commit from Oct 2007.
https://github.com/WebKit/WebKit/commit/13e3659e55eeec5a96acf0f2e85298ed89ad1316

Safari 3.1 shipped in March 2008. 
Safari 4.0 shipped in June 2009.

It does not make sense that work finished in October 2007 would have waited until June 2009 to ship. That's not what happened. It shipped in March 2008.

**Comment by Fyrd** [comment]
Wow this is kinda blowing my mind since it looks like that's been wrong at least since I added the data to the repo (2012)... wonder how that happened! Well better late than never, thanks for the corrections 😅
