### ISSUE TITLE
Pointer Lock API not supported On Chrome for Android

### ISSUE THREAD

**Issue by JeffreyBlanz** [Fyrd/caniuse#7065]
MDN docs and caniuse both say pointer lock API is supported on chrome for android. It should say it is not supported.

When doing a pointer lock API test, it does not work: https://mdn.github.io/dom-examples/pointer-lock/

MDN doc: https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API

Caniuse doc: https://caniuse.com/pointerlock

Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=153419

Chrome Feature announce stating android does not support it: https://chromestatus.com/feature/6753200417800192

**Comment by Fyrd** [comment]
Thanks, has been updated!
