### ISSUE TITLE
Feature Request: Expose Baseline Status in fulldata-json

### ISSUE THREAD

**Issue by ireade** [Fyrd/caniuse#7099]
As far as I can tell, the Baseline status of features isn't currently exposed via the features data JSON file. Would like to include the Baseline status in my [embed](https://caniuse.bitsofco.de/), any plans for making this available?

**Comment by Fyrd** [comment]
As the baseline status comes from the [web-features](https://github.com/web-platform-dx/web-features) repo I'd suggest instead to reference that data source instead, it includes caniuse IDs to map to. That's currently how the caniuse.com site gets it.

**Comment by ireade** [comment]
Thanks @Fyrd ! Will do this
