### ISSUE TITLE
Safari Technology Preview now supports a favicon in SVG format

### ISSUE THREAD

**Issue by pereorga** [Fyrd/caniuse#7102]
I couldn't find any mention in [Safari Technology Preview Release Notes](https://developer.apple.com/documentation/safari-technology-preview-release-notes), but that works for me:

https://notes.orga.cat/example

<img width="827" alt="SCR-20240628-pjdj" src="https://github.com/Fyrd/caniuse/assets/919779/214b23bb-4dee-41a1-ab82-aa482edb8707">

For reference, that SVG file is https://github.com/pereorga/minimalist-web-notepad/blob/master/favicon.svg.

**Comment by Schweinepriester** [comment]
No way, huge if true!

I also want to test later, but if you're faster, can you check both SVG versions at <https://tests.caniuse.com/icon-test.php>?

**Comment by pereorga** [comment]
In that link, SVG favicons do not display to me on Safari TP. (On Chrome and Firefox, only the first one did, "SVG as ICO" did not work).

I noticed that in my working example, I am not setting `sizes="any"`.

**Comment by karlcow** [comment]
@pereorga which versions of Safari are you using in your screenshot?
Does it reproduce after erasing the cache?

**Comment by pereorga** [comment]
> @pereorga which versions of Safari are you using in your screenshot?

Release 192 (Safari 17.4, WebKit 19619.1.8.1)

> Does it reproduce after erasing the cache?

No, it does not :(

**Comment by pereorga** [comment]
I understand this was just a random, isolated, unexpected behavior?

I had removed my old favicon.ico when I noticed the SVG file was rendered instead. Furthermore, now that clearing the cache made this functionality disappear, I have now put the .ico file back, and it's now the one displayed.

**Comment by karlcow** [comment]
yes that looks like it could have been coming from the cache.

**Comment by pereorga** [comment]
Thanks @karlcow.

How the cache was filled, and why Safari can render SVG favicons when coming from the cache, may still be a mystery.

Closing, sorry for the noise.
