### ISSUE TITLE
Firefox 127 fully supports the async clipboard API

### ISSUE THREAD

**Issue by foolip** [Fyrd/caniuse#7107]
This is about https://caniuse.com/async-clipboard

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/127 says "The async Clipboard API is now fully supported."

I would send a PR, but am not sure about the current note for Firefox and how to update it.

**Comment by Fyrd** [comment]
The specification also mentions supporting the "clipboard-write" permission as part of the API which I don't think Firefox supports yet. So based on that I don't think it's really fully supported?

**Comment by foolip** [comment]
The permissions situation for clipboard access is complicated, and I don't know the details. It looks like the security teams of different browsers disagree about what the model should be, but that it's possible to use the API in all browsers without really know about these details, by just ensuring that `navigator.clipboard.writeText()` and similar are called from click event handlers.

Looping in @EdgarChen who implemented this in Firefox and @saschanaz who filed https://github.com/w3c/clipboard-apis/pull/164.

**Comment by saschanaz** [comment]
Both clipboard-read and clipboard-write permissions are Blink only as AFAIK standards positions are negative from Mozilla and Apple.

**Comment by Fyrd** [comment]
Thanks for added context! Have switched support to full and added some notes on the security considerations.
