### ISSUE TITLE
HTTP/3 usage might be underestimated, what does "partial support" i.e. "Enabled by default for a portion of users" really mean?

### ISSUE THREAD

**Issue by PallHaraldsson** [Fyrd/caniuse#7114]
See:
https://caniuse.com/http3

Support could be as low as  75.86% or as high as 98% so it matters which and the numbers only depend on availability on Apple products.

E.g., for "tracked mobile" the "22.22%" "partial support" to get to 98.08% depends on how many users of Safari 14 up to 17 have have it enabled.

This "Enabled by default for a portion of users." seems like A/B testing, and wouldn't Apple have enabled for all users be now? Can someone test for me and see if HTTP/3 doesn't work for some version on iOS or macOS? To give me some confidence inn the low (or high) number.

It doesn't seem plausible that Apple enabled first for only some users with 14.4 in Sept 2020 and is still doing it year later with 17.5, so simply wrongly marked/not updated here?

**Comment by Schweinepriester** [comment]
Please see the discussion in this PR: https://github.com/Fyrd/caniuse/pull/6664

[The last update at the time of writing](https://github.com/Fyrd/caniuse/pull/6664#issuecomment-1726305685):

> I don't believe anything changed in our HTTP3 support. We did not announce a change in our Safari 17.0 release notes or article. I am looking into it.

**Comment by jensimmons** [comment]
Safari now supports HTTP3 for all users, as of September 2024, no matter which version of Safari they are running.

**Comment by Schweinepriester** [comment]
Wuhu, say no more, PR incoming!

**Comment by jensimmons** [comment]
https://github.com/Fyrd/caniuse/pull/7200/files

**Comment by jensimmons** [comment]
It's a complicated PR, but I think this properly conveys the message. See the note in the PR for more details.

**Comment by Schweinepriester** [comment]
the autoclose didn’t work, but I believe this issue can be closed now :)
