### ISSUE TITLE
Add calc-size css funcionality

### ISSUE THREAD

**Issue by Eric-llos** [Fyrd/caniuse#7116]
Hi,

if you could add to caniuse this feature: https://drafts.csswg.org/css-values-5/#calc-size

Thanks :)

**Comment by nt1m** [comment]
The design of this feature is still being debated fwiw: https://github.com/w3ctag/design-reviews/issues/955

**Comment by yisibl** [comment]
It's already shipping in Chrome 129. 🤣🤣
https://chromestatus.com/feature/5196713071738880

**Comment by nt1m** [comment]
I'm aware, there's still recent comments from Google on that issue however.

**Comment by Fyrd** [comment]
Available via BCD: https://caniuse.com/mdn-css_types_calc-size
