### ISSUE TITLE
Stable Safari 17.6 has WebGPU as feature flag.

### ISSUE THREAD

**Issue by birkskyum** [Fyrd/caniuse#7124]
I'm not sure exactly what version of Safari it started, but it seems that stable Safari 17.6 on macOS has a WebGPU feature flag which isn't mentioned in the table.

<img width="129" alt="Screenshot 2024-08-05 at 14 14 25" src="https://github.com/user-attachments/assets/92c5976a-6e90-480a-b6f2-fc47e31248ba">

<img width="844" alt="Screenshot 2024-08-05 at 14 14 58" src="https://github.com/user-attachments/assets/dce40cc1-c391-4a9c-af4c-7dafd1e74375">

**Comment by Ugoku** [comment]
17.5 also has this flag

**Comment by jensimmons** [comment]
I'm looking into exactly when this feature flag was added (off by default) to Safari. I know it shipped on by default in Safari Technology Preview 190 (as 'preview') on March 6, 2024.

**Comment by jensimmons** [comment]
It was added in Safari 17.4.
https://bugs.webkit.org/show_bug.cgi?id=265948

**Comment by jensimmons** [comment]
I have an email notification where @birkskyum asked:
> Just out of curiosity, how do you set the flag on iOS?

On iOS, iPadOS and visionOS:
Settings > Apps > Safari > Advanced > Feature Flags

**Comment by jensimmons** [comment]
Thanks for filing this issue!
