### ISSUE TITLE
 Many CSS variables are undefined. 

### ISSUE THREAD

**Issue by icebale** [Fyrd/caniuse#7146]
The webpage style is displaying abnormally.  Checking the elements revealed that many CSS variables are undefined. 
![image](https://github.com/user-attachments/assets/8fdc0bfb-b47f-4daa-8047-8218e2220ccc)
![image](https://github.com/user-attachments/assets/be3e56cd-4032-49f3-ab9b-39b82f20482e)

**Comment by Fyrd** [comment]
This was fixed recently, thanks for reporting!
