### ISSUE TITLE
Light mode seems to be not working correctly

### ISSUE THREAD

**Issue by Maingron** [Fyrd/caniuse#7147]
I just noticed the lightmode seems to be broken, see screenshot.

![Screenshot (92).png](https://github.com/user-attachments/assets/d1b555b4-bd9c-4cb1-a73a-af7aff595c2c)

**Comment by char8x** [comment]
Same problem here

<img width="1516" alt="图片" src="https://github.com/user-attachments/assets/cad523ae-7229-409f-ad19-af99fe36a57c">

**Comment by Benimation** [comment]
Colorblind-friendly isn't working either, whether is dark mode or light mode

**Comment by Fyrd** [comment]
This was fixed recently, thanks for reporting!
