### ISSUE TITLE
Light Theme style error

### ISSUE THREAD

**Issue by Whiskeyi** [Fyrd/caniuse#7148]
Light Theme:
<img width="1498" alt="image" src="https://github.com/user-attachments/assets/02a03b73-75b0-45bf-9549-565d03c4f900">

Dark Theme:
<img width="1499" alt="image" src="https://github.com/user-attachments/assets/59697101-4f4d-4a2c-bb60-323185a39caf">

light Theme var undefined:
<img width="329" alt="image" src="https://github.com/user-attachments/assets/fb92f703-46c4-4e5b-be1e-067af0cc3bb7">

**Comment by Fyrd** [comment]
This was fixed recently, thanks for reporting!
