### ISSUE TITLE
Safari 17.6 shipped July 29

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#7151]
Can I Use seems to think Safari 17.5 is the current version. Actually Safari 17.6 is. 

It was released July 29, 2024.
https://webkit.org/blog/15739/webkit-features-in-safari-17-6/

**Comment by jensimmons** [comment]
<img width="600" alt="Screenshot 2024-09-09 at 4 03 59 PM" src="https://github.com/user-attachments/assets/0701b706-5d6a-4ce3-a0f5-3fb9992e1b65">

17.6 should be in the current row.

**Comment by Fyrd** [comment]
Thanks, updated!
