### ISSUE TITLE
Safari 18.0 is here!

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#7156]
Safari 18.0 shipped yesterday, Sept 16, 2024.
https://developer.apple.com/documentation/safari-release-notes/safari-18-release-notes
https://webkit.org/blog/15865/webkit-features-in-safari-18-0/

It'd also be a nice time to add the slot for Safari 18.1 to the system.

**Comment by Schweinepriester** [comment]
Also Safari 17.7, at least on iOS, no?

Seemingly there is Safari 17.7 on macOS?

**Comment by jensimmons** [comment]
There is no Safari 17.7 on any platform, no. iOS did bump up to iOS 17.7, but the Safari version number is separate from the iOS/iPadOS version number. We should just have a Safari 17.6 on all platforms, and then Safari 18.0.

**Comment by Schweinepriester** [comment]
The User agent seems to report otherwise, based on what you are saying I would have expected it to stay at 17.6 🤔

![image](https://github.com/user-attachments/assets/9239abbd-4e14-4a70-ac4c-b4902cfc87df)

**Comment by jensimmons** [comment]
Safari 18.1 release notes!
https://developer.apple.com/documentation/safari-release-notes/safari-18_1-release-notes

(And I'm digging further into the 17.7 question...)

**Comment by Schweinepriester** [comment]
Fyrd seems to have added 18.0 and 18.1, so I suppose technically this issue can be closed.

As for 17.7 however, in addition to my single example I can report that in the stats of my company version 17.7 on mobile is already the 11th most used version.
Somehow even on desktop there are 500-ish sessions (mis?)reported with that version.

So I really think there should be an entry for 17.7, at least for mobile, to have that mapping available, e.g. for in the future for browserslist to be able to target the last version of 17.x.

**Comment by jensimmons** [comment]
I can confirm that iOS went to Safari 17.7, while macOS stayed at 17.6. This is unusual, but perhaps should be documented for the sake of the user agent & yes, user stats. There are zero meaningful-to-web-developer differences between 17.6 and 17.7.

**Comment by Fyrd** [comment]
iOS 17.7 now included with iOS17.6 so seems safe to close this now. :)
