### ISSUE TITLE
Add Opus in MP4/WebM container testcase

### ISSUE THREAD

**Issue by tats-u** [Fyrd/caniuse#7158]
iOS used to lack support for Opus in MP4 and lacks support for Opus in OGG container, so we need a test case for it.

https://tests.caniuse.com/opus

↓MP4

https://github.com/user-attachments/assets/f5c61400-a235-4304-b23a-40826d696c57

`https://github.com/user-attachments/assets/f5c61400-a235-4304-b23a-40826d696c57`

↓WebM

[audio.opus.webm](https://github.com/user-attachments/assets/4948b8e7-00fe-4096-a525-f30b86c758a2)

`https://github.com/user-attachments/assets/4948b8e7-00fe-4096-a525-f30b86c758a2`

(We may have to open its URL directly to play it)

**Comment by Fyrd** [comment]
Many thanks! Have now added these to the opus tests.
