### ISSUE TITLE
Video API - iOS volume is read-only

### ISSUE THREAD

**Issue by shalanah** [Fyrd/caniuse#7163]
Video API on iOS suffers the fate as Audio API on iOS where the relative volume can only be 100% of the selected user volume (read-only volume) which breaks UI surrounding volume sliders. 

I'm happy to add a note and PR for this but wondering if this raises to the level of only partially supported since it does on Audio API but understand why we might still want to say fully even with the two notes since Video clearly is more involved than just Audio.

Audio Current: https://caniuse.com/?search=audio
Video Current: https://caniuse.com/?search=video

**Comment by Fyrd** [comment]
Thanks! I have added a note on this. Agree that for video it makes less sense to mark it as partial support.
