### ISSUE TITLE
`hanging-punctuation`- Add Safari support caveat

### ISSUE THREAD

**Issue by jamesnw** [Fyrd/caniuse#7184]
https://caniuse.com/css-hanging-punctuation

- Safari does not support the `force-end` keyword - or rather, it recognizes the keyword but does nothing with it. 
  -  https://github.com/mdn/browser-compat-data/pull/5637
  - https://github.com/mdn/browser-compat-data/issues/5541
  - https://bugs.webkit.org/show_bug.cgi?id=233761
- Safari does not support the characters <code>U+0027</code> and <code>U+0022</code> in the first and last keywords.
  - https://github.com/mdn/content/pull/22022#issuecomment-1304291411
  - https://github.com/mdn/browser-compat-data/pull/18444

**Comment by Fyrd** [comment]
Thanks, has now been updated: https://caniuse.com/css-hanging-punctuation
