### ISSUE TITLE
Update MDN BCD logo

### ISSUE THREAD

**Issue by pepelsbey** [Fyrd/caniuse#7187]
MDN [updated its logo in 2022](https://hacks.mozilla.org/2022/03/a-new-year-a-new-mdn/#:~:text=A%20new%20logo), so it would be fair to use it for BCD as well.

## Before/after

<img width="1436" alt="diff" src="https://github.com/user-attachments/assets/5f618f7e-7e4a-447f-8e1c-f0bbae27337e">

## mdn-bcd.svg

![mdn-bcd](https://github.com/user-attachments/assets/b7872142-61a4-4ff3-a499-db344df70ab5)

**Comment by Fyrd** [comment]
Many thanks! Has now been updated.
