### ISSUE TITLE
Relative Color fixes applied to wrong browser

### ISSUE THREAD

**Issue by jamesnw** [Fyrd/caniuse#7191]
It appears that https://github.com/Fyrd/caniuse/pull/7159 was meant to be applied to Chrome, but it was instead applied to Firefox. However, it looks like the note can also be removed from Firefox 133- https://bugzilla.mozilla.org/show_bug.cgi?id=1893966

In other words:

- Firefox 131 and 132 SHOULD have a note, and 133 should not.
- Chrome 131+ should NOT have a note.

https://caniuse.com/css-relative-colors

**Comment by Schweinepriester** [comment]
Whoops, my bad, creating PR to fix now!
