### ISSUE TITLE
Add ReadableStream as request body

### ISSUE THREAD

**Issue by Arzumify** [Fyrd/caniuse#7195]
Whilst Chromium has full out-the-box support for ReadableStreams as a request body, Safari's implementation appears to be a little buggy in some areas, whilst Firefox has no support at all.

I'll test everything and make a PR when I have time.

**Comment by arzustudent** [comment]
Nevermind, didn't see https://caniuse.com/mdn-api_request_request_request_body_readablestream exists

**Comment by Arzumify** [comment]
Nevermind, didn't see https://caniuse.com/mdn-api_request_request_request_body_readablestream
