### ISSUE TITLE
Please add support information for the new CSS property 'overflow-style'

### ISSUE THREAD

**Issue by farooqbinmunir** [Fyrd/caniuse#7197]

**Comment by Schweinepriester** [comment]
Any info on `overflow-style`?

Or is this the same as https://github.com/Fyrd/caniuse/issues/2429?

**Comment by Fyrd** [comment]
AFAICT there was indeed only ever a `-ms-overflow-style` supported in IE10 & IE11. Probably worth a search result but yeah I think this counts as a duplicate.
