### ISSUE TITLE
Safari 18.1 shipped & 18.2 is in beta

### ISSUE THREAD

**Issue by jensimmons** [Fyrd/caniuse#7202]
Safari 18.1 shipped last Monday, October 28. And Safari 18.2 is now in beta. 

https://developer.apple.com/documentation/safari-release-notes

**Comment by jensimmons** [comment]
It'd be great for Can I Use to be updated to reflect Safari 18.2's existence. The MDN BCD data has been updated: https://github.com/mdn/browser-compat-data/pull/24939 but doesn't yet show on Can I Use.

**Comment by Fyrd** [comment]
Added now, thanks for the reminder.
