### ISSUE TITLE
Popover API: Bug 267688 (Resolved iOS > 18.0)

### ISSUE THREAD

**Issue by Aspvik** [Fyrd/caniuse#7203]
Clicking outside the popover element will close the popover if mode="auto" as per spec on iOS > 18.0

Ref: https://caniuse.com/mdn-api_htmlelement_popover
Bug ref: https://bugs.webkit.org/show_bug.cgi?id=267688

**Comment by Fyrd** [comment]
As this data comes from the [BCD project](https://github.com/mdn/browser-compat-data), please file an issue there, thanks!
