### ISSUE TITLE
IE results for input-number are just not true

### ISSUE THREAD

**Issue by jwatt** [Fyrd/caniuse#743]
http://caniuse.com/#feat=input-number claims that IE 10 and 11 partially support the number input type without up/down button UI, and the caveat that there's one known bug that valueAsNumber doesn't work. In fact as far as I can tell though _nothing_ that would make the input act as a number input works other than the fact that IE seems to allow the 'type' to be set to "number". (For example, stepUp() doesn't work either.) It seems like IE is coning test suites like caniuse here, and that IE 10 and 11 should be flat out fails. You simply can't use number inputs in IE yet.

(I'd also note that if you put <input type="number"> in the markup of a page it gets given the type "text".)

**Comment by HolgerJeromin** [comment]
This should be closed after the merge of #796 ?
