### ISSUE TITLE
flexbox family incomplete

### ISSUE THREAD

**Issue by tomByrer** [Fyrd/caniuse#778]
Seems there are more CSS properties that are missing from the single [flexbox entry](caniuse.com/#feat=flexbox).  Coverage varies between browsers & versions:
* [align-self](https://developer.mozilla.org/en-US/docs/Web/CSS/align-self#Browser_compatibility)
* [align-content](https://developer.mozilla.org/en-US/docs/Web/CSS/align-content#Browser_compatibility)
* [flex-basis](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis#Browser_compatibility)
* [flex-direction](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-direction#Browser_compatibility) Safari?
* [flex-flow](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-flow#Browser_compatibility)
* [flex-grow](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-grow#Browser_compatibility)/[-shrink](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-shrink#Browser_compatibility)

I suspect [some](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-wrap#Browser_compatibility) need updating on MDN, but some seem to have recent updates in FireFox that aren't reflected on your site.

Not sure if you want to clump everything under your existing flexbox entry, but the 'Notes/Known issues; would get long & messy.  Could list individual properties, or clump similar brothers together:
* [flex](https://developer.mozilla.org/en-US/docs/Web/CSS/flex#Summary) / flex-grow / flex-shrink / flex-basis
* align-content / align-self (align-items seem to be supported)
* [flex-flow](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-flow#Summary) / flex-direction / flex-wrap

What do you think?

**Comment by Fyrd** [comment]
Since browsers supporting the latest spec have support for all these properties (save from the occasional bug) I see no benefit in separating them.
