### ISSUE TITLE
BlackBerry10 IndexedDB appears to use the current standard

### ISSUE THREAD

**Issue by dlmiles** [Fyrd/caniuse#789]
Certainly for BB10 OS version 10.2.1.

Can you point me to the source of the original information use to make the claim in the foot notes referencing that is supports the 2011 (http://www.w3.org/TR/2011/WD-IndexedDB-20110419/) specification ?

In real world app development (at this time) it appears to use the latest standard, much like Chrome/38.  The APIs are different in a number of ways but when using Web Inspector on a real BB10 device I am unable to locate the symbols defined in the 2011 specification.  Only the current symbols presents in a more recent spec.

So if you can point me at the source of the original data I can try to re-verify using the same method.

Maybe an OS update (there have been 3 since the original release) improved the support ?

**Comment by Fyrd** [comment]
This got updated at some point to confirm that it's using the current standard.
