### ISSUE TITLE
Add Firefox OS in the list. 

### ISSUE THREAD

**Issue by dolftax** [Fyrd/caniuse#841]
Release notes for all versions - https://developer.mozilla.org/en-US/Firefox_OS/Releases

**Comment by yukulele** [comment]
:+1:

**Comment by dolftax** [comment]
I would like to work on this. Would someone tell me how to proceed and assign this to me?

**Comment by yukulele** [comment]
the problem: caniuse works with browsers stats (http://gs.statcounter.com/ datas are used), and Firefox OS not appear in stats

**Comment by dolftax** [comment]
Firefox OS is based on Gecko. Like,

- Firefox OS 1.2 - Gecko 26
- Firefox OS 2.0 - Gecko 32

So, whatever works in Firefox 26 works exactly as it is on Firefox OS 1.2.

**Comment by Fyrd** [comment]
Yeah, Firefox OS support seems close enough to the browser that it doesn't seem worth adding by itself.
