### ISSUE TITLE
Pin a feature

### ISSUE THREAD

**Issue by aronduby** [Fyrd/caniuse#846]
I wish there was a way on the site to be able to pin a feature to keep it showing, and then search and pin some other features, to create a little run-down of the features that are used (or I want to use) for a specific site. 

Presentation wise it could be really similar to the hash link setup you use now, but with the ability to keep adding more.

**Comment by Fyrd** [comment]
There's a feature for this now on the beta site (https://beta.caniuse.com). You can star any feature and see a list of these saved features. Will close this issue once it's on the main site.

**Comment by Fyrd** [comment]
This is now available on the main site.
