### ISSUE TITLE
Incorrect info in flexbox's known issues section.

### ISSUE THREAD

**Issue by philipwalton** [Fyrd/caniuse#848]
The known issues section for flexbox says the following:

 > IE10 and IE11 default values for `flex` are `0 0 auto` rather than `0 1 auto`, as per the draft spec, as of September 2013.

There are two things wrong here:

1. IE 11 actually uses the correct value of `initial`, or `0 1 auto`
2. The spec that suggested `0 0 auto` is actually from [March 2012](http://www.w3.org/TR/2012/WD-css3-flexbox-20120322/#flexibility)

Also, I've put together a repo called [Flexbugs](https://github.com/philipwalton/flexbugs), which may be a useful resource, but it also could go under known issues, so I'll let you decide if/where to include it.

Thanks!

**Comment by Fyrd** [comment]
Corrected this some time ago, now have also added a link to Flexbugs. Thanks!
