### ISSUE TITLE
Add triggers to feature data

### ISSUE THREAD

**Issue by kvendrik** [Fyrd/caniuse#849]
Hi everyone,

First of all, caniuse.com is awesome! Great work!

I'm writing this issue because I recently ran into something that you might find interesting. I was working on a web tool that uses the caniuse.com database. It allows people to test their JS code against the db.

While doing this I noticed that the features JSON doesn't have any reference to the actual functions or methods needed to use the feature. This means that if someone would for example search for `globalCompositeOperation` on caniuse.com they wouldn't get the `Canvas blend modes` info.

This was also a problem for me as I needed to check the user's code against the db. To solve this I copied all features that are JS related and added a `triggers` array to them which is basically an array of every function or method people might use to trigger that feature.

The `triggers` array in the [JSON I'm currently using](https://github.com/kvendrik/browser-check.js/blob/master/dev/js/libs/caniusedb.js#L1317) is by far not accurate enough for production but implementing this concept into the caniuse db might be a good idea as it would allow users to search for actual method names.

This might not be relevant to the caniuse.com goal but I thought I'd post it anyway just in case someone would find it useful.

Cheers.

**Comment by MattivdWeem** [comment]
+1

**Comment by baskaal** [comment]
+1

**Comment by Fyrd** [comment]
Thanks for the kind words! This sounds like issue #732 and you can see my reasoning for not including the data you refer to there. It's a compelling idea, but ultimately I fear it's too much work & maintenance.
