### ISSUE TITLE
WebGL in Safari 8

### ISSUE THREAD

**Issue by dhritzkiv** [Fyrd/caniuse#867]
I noticed that WebGL in Safari 8 is listed as partial support, potentially because not all users had it enabled by default (it was enabled by an option). While this was true in Safari 7, AFAIK, all users in 8+ have WebGL enabled by default. Though, I very well may be mistaken.

**Comment by pkuczynski** [comment]
Good point. Created a pull request for this change...

**Comment by Fyrd** [comment]
Yup, this was merged.
