### ISSUE TITLE
CSS Property CurrentColor

### ISSUE THREAD

**Issue by marcobiedermann** [Fyrd/caniuse#870]
Can you please add browser support for the currentColor property?!
http://css-tricks.com/currentcolor/

**Comment by cvrebert** [comment]
> If you'd like to propose a new web technology feature to be added, please submit/vote for the issue on [Google Moderator](http://www.google.com/moderator/#15/e=ae425&t=ae425.40) rather than submitting an issue. This way features can be added based on the popularity of the feature.

— https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md#filing-issues

**Comment by marcobiedermann** [comment]
@cvrebert thank you very much
