### ISSUE TITLE
Up to date issues on for Date and time input types

### ISSUE THREAD

**Issue by GiancarloGomez** [Fyrd/caniuse#875]
Since I am working on a project at them moment and appear to run into the following issues I thought I would share to see if we can get the information updated.

iOS 8.1.3 still does not support min and max attributes.

Chrome 40 on Android 5.0.1 supports the attributes in the UI aspect. Out of range dates are grayed out but can still be selected. 

http://caniuse.com/#feat=input-datetime

**Comment by Fyrd** [comment]
Looks like this information was added to the data at some point, so closing the issue.
