### ISSUE TITLE
Opera Mobile uses -webkit- prefix since 24

### ISSUE THREAD

**Issue by ai** [Fyrd/caniuse#883]
Opera’s prefix is `-webkit-` in `data.json` with `prefix_exceptions`.

But Opera Mobile (`op_mob`) has no `prefix_exceptions` and has `-o-` prefix, but Opera Moile 24 was released with Blink engine.

@pepelsbey from Opera team can confirm, that it uses `-webkit-`

@Fyrd I am glad to send PR, but `data.json` is complitly unreadable: #651

**Comment by pepelsbey** [comment]
There are two Opera’s mobile browsers:

[Opera Mobile Classic](https://play.google.com/store/apps/details?id=com.opera.browser.classic&hl=en) based on Presto, latest version is 12.1. It supports `-o-`prefixes as well as subset of `-webkit-`prefixes only for compatibility reasons, see [docs](http://www.opera.com/docs/specs/presto2.12/css/o-vendor/) and [article](https://dev.opera.com/articles/opera-mobile-emulator-webkit-prefix-support/). I would strongly ask you **not to include** `-webkit-`prefixes support in your data as it’s just a mapping to existing prefixed or prefixless properties.

[Opera for Android](https://play.google.com/store/apps/details?id=com.opera.browser&hl=en), based on Blink, latest version is 27. First version based on WebKit is 14 (beta), first final version based on Blink is 15.

**Comment by ai** [comment]
@Fyrd does I undersand right, that `op_mob 24` is a Opera for Android?

**Comment by Fyrd** [comment]
@ai Looking at data.json I see `"prefix_exceptions":{"24":"webkit"}}` And as this file is auto-generated from my database, a PR would do no good. If you'd like to see it expanded, I recommend something like this [Chrome add-on](https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc) on the [raw JSON file](https://raw.githubusercontent.com/Fyrd/caniuse/master/fulldata-json/data-2.0.json)

@pepelsbey No worries, I'm well aware of all this and have no intention of adding `webkit` prefixes for Presto-based Opera.

**Comment by ai** [comment]
Hm. Maybe I miss it last time :-/. There was to many work on my, sorry :).
