### ISSUE TITLE
HTML5 Video support on IE

### ISSUE THREAD

**Issue by Zeromax** [Fyrd/caniuse#884]
The Element is not supported under IE11 under Win7 and maybe as well IE10 under win 7.
On IE 9 under Win 7 everything is fine.

> IE11 introduces support for MPEG-DASH media streaming through HTML5 Media Source Extensions (MSE). MSE extends the video and audio elements that you can dynamically change for a media stream without using plug-ins. This gives you such things as adaptive media streaming, live streaming, splicing videos, and video editing.

> Important  This feature is not supported in IE11 on Windows 7.

Source: https://msdn.microsoft.com/en-us/library/ie/bg182646(v=vs.85).aspx#mse

It is marked as Full supported and leads lots of users wrong: http://caniuse.com/#feat=video

**Comment by dstorey** [comment]
I don’t understand this bug report. You’re saying the video element is not supported by IE11? That is patently false.

The quote included is about MPEG-DASH and MSE. Very different to the video element itself.

**Comment by Zeromax** [comment]
@dstorey I never said that it is not supported under IE11. It is not Supported under __Windows 7 and IE 11__. I have tested this also with a demo site for the HTML5 Video Player.
So IE11 has only a partial HTML5 Video Element Support. -> http://www.html5rocks.com/de/tutorials/video/basics/
Just check it out under Windows 7 and IE 11. It does not work. I have used browserstack to try this.

The Quote is only a further detailed Explanation why it doesn't work.

**Comment by dstorey** [comment]
@Zeromax The video element is supported in IE11 on Windows 7. It was added in IE9 https://msdn.microsoft.com/en-us/library/ie/hh772959(v=vs.85).aspx

**Comment by Zeromax** [comment]
@dstorey Please go to Browserstack. Start a Session with IE11 and Windows 7 use this link: http://www.html5rocks.com/de/tutorials/video/basics/ Check it out.

If everythig works. Close it.

**Comment by Fyrd** [comment]
@Zeromax It seems the only reason it doesn't work on that page is due to the addition of the codecs being specified ( ` codecs="avc1.42E01E, mp4a.40.2"`) if you remove that it works fine. So at worst that's a minor bug.

**Comment by Zeromax** [comment]
@Fyrd Thanks for that explanation. That's a really stupid bug...
