### ISSUE TITLE
input:autofill 

### ISSUE THREAD

**Issue by hellier** [Fyrd/caniuse#887]
Please add :autofill to the DB.

:-webkit-autofill
:-moz-autofill

http://caniuse.com/#search=:autofill

**Comment by cvrebert** [comment]
> If you'd like to propose a new web technology feature to be added, please submit/vote for the issue on [Google Moderator](http://www.google.com/moderator/#15/e=ae425&t=ae425.40) rather than submitting an issue. This way features can be added based on the popularity of the feature.

— https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md#filing-issues

**Comment by Fyrd** [comment]
Closing as per @cvrebert 's comment.
