### ISSUE TITLE
dataset data set seems inaccurate. 

### ISSUE THREAD

**Issue by patrickkettner** [Fyrd/caniuse#899]
You currently have `dataset` as a partial match when you are able `to use data-* attributes and access them using getAttribute.` I don't see this anywhere in the spec, and considering every single browser supports the `getAttribute` version, it dilutes actual support quite a bit.

I think this should only list elements who have `dataset` on their HTMLElement IDL.

**Comment by Fyrd** [comment]
The feature refers to "dataset & data-* attributes", not just `dataset`. The reason for the partial support is so people know they can still use data-* attributes even without dataset support.

**Comment by patrickkettner** [comment]
hey @Fyrd!
Totally get that now - my main point was that listing support for `data-*` isn't useful, when literally every browser listed supports it. Since dataset is _not_ supported by everything, it ends up diluting an otherwise very useful list.

**Comment by Fyrd** [comment]
@patrickkettner I see what you're saying, but I feel the usefulness of just using data-* attributes outweighs the benefit of only tracking dataset support. There's a clear distinction between partial and full support so the difference should be notable enough.

**Comment by patrickkettner** [comment]
Perhaps I just don't follow why its useful information.

`data-*` are technically valid in markup, but otherwise in no way special - unless you are using `dataset`, in which case the api (and data) is totally different.

You are really just returning support for getAttribute. While very useful to know, it feels like it is just more suited for a `notes` section, rather than taking over the entire data set.

**Comment by Fyrd** [comment]
I'm thinking more of web devs who may have heard of or seen data-* attributes somewhere and lack the awareness that there's nothing special about them and that it's obvious they'd be supported using getAttribute everywhere. For them, they can look up this feature and see they can be safely used. If they just saw "no support" in say IE10 and below they may just give up on them entirely, which seems like a shame.

**Comment by patrickkettner** [comment]
fair enough - and I am all for encouraging devs to use this sort of thing.
But why not make it a separate feature. Since all browser already support
it, it will never need any updating. Then the browser support for dataset
will be useful, and devs who see data-* attrs will still be confident in
using them.

On Tue, Mar 10, 2015 at 12:21 AM, Alexis Deveria <notifications@github.com>
wrote:

> I'm thinking more of web devs who may have heard of or seen data-*
> attributes somewhere and lack the awareness that there's nothing special
> about them and that it's obvious they'd be supported using getAttribute
> everywhere. For them, they can look up this feature and see they can be
> safely used. If they just saw "no support" in say IE10 and below they may
> just give up on them entirely, which seems like a shame.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Fyrd/caniuse/issues/899#issuecomment-77993720>.
>



-- 
patrick

**Comment by Fyrd** [comment]
Closing as per my points back in May. Splitting it into separate issues does not seem worthwhile.

**Comment by patrickkettner** [comment]
Disappointing, but understood. Thank you for the consideration.
