### ISSUE TITLE
Add QQbrowser in the list

### ISSUE THREAD

**Issue by mbbill** [Fyrd/caniuse#901]
As one of the most widely used mobile browsers in China, it would be great if it could get listed, but as the guideline for contributing, adding a new browser is unsupported, so is there anything I could do for it? Thanks!
Sorry for posting here if it's not the right way of making the request.

**Comment by bitinn** [comment]
People struggle to provide data for UC, which has a wider usage across the globe, so unless there are both metrics and test data for QQ Browsers, I don't see it happening.

**Comment by mbbill** [comment]
May I ask how do you generate test data for these browsers? Is there anything I could do for a help?

**Comment by bitinn** [comment]
Since features are grouped as individual json(s), you will have to update all of them to get QQ browser in the list (not to mention different versions).

I am not sure if one can auto generate report from http://tests.caniuse.com/

**Comment by Fyrd** [comment]
As far as I can tell QQ browser just uses the browser engine of whatever OS it's on, so there's no need to list it separately. If I'm wrong about that please let me know.

**Comment by mbbill** [comment]
No, it's not. Although it's another webkit-based browser just like uc or something else do, it's definitely not a webview shell.

**Comment by Fyrd** [comment]
@mbbill Interesting, I first thought it was the same as http://en.wikipedia.org/wiki/Tencent#Tencent_Traveler which says it uses Trident, but I get the impression this is something else then. It's hard to find any info on this browser in English, do you have a Google Play link or something where I can get it?

**Comment by mbbill** [comment]
That page is kind of out of date. Below is the Google Play link
https://play.google.com/store/apps/details?id=com.tencent.mtt&hl=en
Unfortunately it's in Chinese, probably because it's mainly targeting the domestic market.

**Comment by Fyrd** [comment]
QQ Browser got added some time ago, so closing this issue.
