### ISSUE TITLE
firefox 38 defaults to true for unicode-range support

### ISSUE THREAD

**Issue by patrickkettner** [Fyrd/caniuse#902]
`layout.css.unicode-range.enabled` is true on Firefox 38, but listed as unsupported (but works behind flag) on the site.

**Comment by hebbet** [comment]
not sure if firefox 38 will really ship with unicode-range support as it is still an early release.

**Comment by patrickkettner** [comment]
sure, but as of now its `y`. data can always be updated if something changes

**Comment by patrickkettner** [comment]
also  -thanks for opening a PR!

**Comment by patrickkettner** [comment]
closed since #911 merged
