### ISSUE TITLE
Bug: Google Analytics import

### ISSUE THREAD

**Issue by iBobik** [Fyrd/caniuse#904]
Hi,
I tried to import data in Safari (disabled all plugins), but after Activate button it freezed and did nothing:
![snimek obrazovky 2015-03-05 v 13 56 37](https://cloud.githubusercontent.com/assets/614232/6505159/7a6450e2-c33f-11e4-88ae-f153d19ac6cb.PNG)

In console it printed this:

```
[Error] Blocked a frame with origin "http://googleads.g.doubleclick.net" from accessing a frame with origin "http://caniuse.com". Protocols, domains, and ports must match.
    (anonymní funkce) (ads, line 5)
    c (ads, line 5)
    La (ads, line 5)
    nb (ads, line 5)
    (anonymní funkce) (ads, line 5)
    oa (ads, line 5)
    (anonymní funkce) (ads, line 5)
[Error] Blocked a frame with origin "http://googleads.g.doubleclick.net" from accessing a frame with origin "http://caniuse.com". Protocols, domains, and ports must match.
    (anonymní funkce) (ads, line 5)
    c (ads, line 5)
    (anonymní funkce) (ads, line 5)
    oa (ads, line 5)
    (anonymní funkce) (ads, line 5)
[Error] Missing note for #3 on feature "xml-serializer"
    addNumberedNoteEl (js.php, line 149)
    makeNotesPanel (js.php, line 149)
    makeTabs (js.php, line 153)
    render (js.php, line 141)
    updateList (js.php, line 125)
    emitEvents (js.php, line 6)
    emit (js.php, line 10)
    filterByFeatures (js.php, line 115)
    initialDisplay (js.php, line 112)
    (anonymní funkce) (js.php, line 188)
    b (js.php, line 32)
    f (js.php, line 59)
    b (js.php, line 32)
    (anonymní funkce) (js.php, line 189)
    b (js.php, line 32)
    m (js.php, line 54)
    (anonymní funkce) (js.php, line 54)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (accounts, line 0)
[Error] There was an error querying accounts: Login Required
    validateResults (retrieve_ga.js, line 141)
    makeAccountsTable (retrieve_ga.js, line 239)
    (anonymní funkce) (cb=gapi.loaded_0, line 602)
    (anonymní funkce) (cb=gapi.loaded_0, line 576)
    (anonymní funkce) (cb=gapi.loaded_0, line 168)
    __cb (cb=gapi.loaded_0, line 91)
    g (cb=gapi.loaded_0, line 85)
    c (cb=gapi.loaded_0, line 76)
```

Same happens when I am logged in to Analytics or not.

Then I tried it in Chrome. While initializing browser showed notice about blocked popup, I confirmed it, popup opened and I successfully gave permission.

**Comment by Fyrd** [comment]
Should be fixed now. Can you try again and let me know?

**Comment by iBobik** [comment]
Hello,
it works in clean Safari, but not works with Ghostery plugin enabled.

Instead in clean Safari there are many errors in console:
[Warning] Unexpected CSS token: ; (ads, line 1)
[Error] Blocked a frame with origin "http://googleads.g.doubleclick.net"
from accessing a frame with origin "http://caniuse.com". Protocols,
domains, and ports must match.
(anonymní funkce) (ads, line 123)
c (ads, line 123)
Ma (ads, line 123)
ob (ads, line 123)
(anonymní funkce) (ads, line 123)
oa (ads, line 123)
(anonymní funkce) (ads, line 123)
[Error] Blocked a frame with origin "http://googleads.g.doubleclick.net"
from accessing a frame with origin "http://caniuse.com". Protocols,
domains, and ports must match.
(anonymní funkce) (ads, line 123)
c (ads, line 123)
(anonymní funkce) (ads, line 123)
oa (ads, line 123)
(anonymní funkce) (ads, line 123)
[Error] Blocked a frame with origin "http://googleads.g.doubleclick.net"
from accessing a frame with origin "http://caniuse.com". Protocols,
domains, and ports must match.
(anonymní funkce) (lidar.js, line 75)
global code (lidar.js, line 97)
[Error] Blocked a frame with origin "http://googleads.g.doubleclick.net"
from accessing a frame with origin "http://caniuse.com". Protocols,
domains, and ports must match.
(anonymní funkce) (ads, line 123)
c (ads, line 123)
(anonymní funkce) (ads, line 123)
oa (ads, line 123)
(anonymní funkce) (ads, line 123)
[Error] Blocked a frame with origin "http://googleads.g.doubleclick.net"
from accessing a frame with origin "http://caniuse.com". Protocols,
domains, and ports must match.
Yb (lidar.js, line 22)
af (lidar.js, line 88)
(anonymní funkce) (lidar.js, line 9)
Na (lidar.js, line 8)
(anonymní funkce) (lidar.js, line 9)
[Error] Blocked a frame with origin "http://googleads.g.doubleclick.net"
from accessing a frame with origin "http://caniuse.com". Protocols,
domains, and ports must match.
Qd (lidar.js, line 75)
af (lidar.js, line 88)
(anonymní funkce) (lidar.js, line 9)
Na (lidar.js, line 8)
(anonymní funkce) (lidar.js, line 9)
[Error] Blocked a frame with origin "http://googleads.g.doubleclick.net"
from accessing a frame with origin "http://caniuse.com". Protocols,
domains, and ports must match.
af (lidar.js, line 88)
(anonymní funkce) (lidar.js, line 9)
Na (lidar.js, line 8)
(anonymní funkce) (lidar.js, line 9)
[Error] Blocked a frame with origin "http://googleads.g.doubleclick.net"
from accessing a frame with origin "http://caniuse.com". Protocols,
domains, and ports must match.
(anonymní funkce) (ads, line 123)
c (ads, line 123)
(anonymní funkce) (ads, line 123)
oa (ads, line 123)
(anonymní funkce) (ads, line 123)
[Error] Missing note for #3 on feature "xml-serializer"
addNumberedNoteEl (js.php, line 148)
makeNotesPanel (js.php, line 149)
makeTabs (js.php, line 153)
render (js.php, line 141)
updateList (js.php, line 125)
emitEvents (js.php, line 6)
emit (js.php, line 10)
filterByFeatures (js.php, line 115)
initialDisplay (js.php, line 112)
(anonymní funkce) (js.php, line 187)
n (js.php, line 32)
da (js.php, line 59)
n (js.php, line 32)
(anonymní funkce) (js.php, line 189)
n (js.php, line 32)
aa (js.php, line 53)
(anonymní funkce) (js.php, line 53)
[Log] versionCache  (retrieve_ga.js, line 899)
Object




Jan Pobořil

2015-03-10 4:54 GMT+01:00 Alexis Deveria <notifications@github.com>:

**Comment by getsnoopy** [comment]
I'm seeing an issue with the Google Analytics integration itself:

![screen shot 2017-04-24 at 17 00 08](https://cloud.githubusercontent.com/assets/2997884/25363479/95534e2a-290f-11e7-8002-35088c792b11.png)

**Comment by paulswartz** [comment]
I'm seeing a 401 trying to import from Analytics (both Safari and Chrome, even in private mode).
```json
{"error":{"errors":[{"domain":"global","reason":"required","message":"Login Required","locationType":"header","location":"Authorization"}],"code":401,"message":"Login Required"}}
```

Being logged in or not logged in to Google doesn't appear to make a difference.

**Comment by Fyrd** [comment]
I think there were follow-up issues that got subsequently fixed over time, so for now I am closing this ticket. Any new bugs with google analytics import can be opened as new tickets.
