### ISSUE TITLE
Overall usage percentages are confusing

### ISSUE THREAD

**Issue by pembeci** [Fyrd/caniuse#905]
On a feature page, when you add up the usage rates of browsers that doesn't support a feature for instance you find 5%, but when you check the top right value you saw something like Global: %88. I am expecting 95% and it is not easy to tell what makes that 7% difference (95-88). Is it because of some browsers are not being tracked and it is assumed that they don't support any of the features. [Usage table page](http://caniuse.com/usage_table.php) currently shows 97.17% of browsers are accounted for. Does that mean ratios of not supporting browsers are subtracted from 97.17 instead of 100 to compute Global support percentage?

**Comment by Fyrd** [comment]
Yes, the percentage supported is of all browsers, including untracked, which is why it doesn't add up to 100%. Safer to assume the browsers not being tracked have no support.

**Comment by pembeci** [comment]
Thanks for the quick reply. It makes sense. A title attr to percentages, a footnote, or an entry in FAQ explaining this may be added for users like me.

**Comment by Krinkle** [comment]
It's still confusing to see http://caniuse.com/#search=inline-block.

It says 97.6% support with no indication of what that other 2.4% might be. Perhaps a note somewhere that 2.4% of browsers is untracked and as such totals will never exceed 97.6% – or whatever the total percentage is that caniuse supports.
