### ISSUE TITLE
IE 10 issues with rem in font property

### ISSUE THREAD

**Issue by jwhitley** [Fyrd/caniuse#915]
IE 10 doesn't support rem units in the shorthand `font` property, but does in the individual `font-*` properties.  See [this StackOverflow post](http://stackoverflow.com/questions/16157342/css-rem-unit-not-working-with-font-declarations) for details.

According to the SO post, and confirmed by my own experience just now, IE 11 has indeed fixed this issue.

**Comment by jwhitley** [comment]
Argh, so I now see that this is already noted under bugs/known issues, but unlike notes isn't called out for the affected browser versions (IE 9 &10).  So the real issue here is that it would be nice if this bug were called out on the site on the relevant browsers like Notes are.

**Comment by Fyrd** [comment]
Made this change some time ago (marked as partial support now) so closing the issue.
