### ISSUE TITLE
Split HTTP/2 and SPDY support into two separate pages

### ISSUE THREAD

**Issue by bagder** [Fyrd/caniuse#924]
These protocols differ and they are supported differently by browsers. Would be useful with a single page showing HTTP/2 support only or adequately differentiated from SPDY. Thanks for a great resource!

**Comment by dstorey** [comment]
If this is done, SPDY should be moved to "unofficial" status rather than "other" as it was never a standard. Hopefully we’ll start to see browsers deprecate it in favour of HTTP/2.

**Comment by Fyrd** [comment]
Done:
http://caniuse.com/#feat=spdy
http://caniuse.com/#feat=http2

**Comment by bagder** [comment]
Awesome, thank you!
