### ISSUE TITLE
Initial list of features is broken

### ISSUE THREAD

**Issue by dstorey** [Fyrd/caniuse#935]
When you first load the site listing all the features, it incorrectly shows the unofficial features as well. If you check then uncheck the unofficial check it works as expected

Steps:

1. Click settings to see list of features

Expected:

List of features and percentage scoring to respect the default settings with unofficial unchecked

Actual:

Unofficial is unchecked but they are still listed. Check and uncheck unofficial and it fixes itself.

This has just started happening recently.

**Comment by Fyrd** [comment]
@dstorey Good find, thanks for pointing that out. Should be fixed now, can you confirm?

**Comment by dstorey** [comment]
@fyrd Confirmed. Thanks!
