### ISSUE TITLE
clipboard API

### ISSUE THREAD

**Issue by paulirish** [Fyrd/caniuse#943]
[The entry on caniuse](http://caniuse.com/#feat=clipboard) says "API to provide copy, cut and paste functionality using the OS clipboard." but its not really describing that.

AFAIK this is the lay of the land…

# Clipboard events
* It's a little in the air.. https://www.lucidchart.com/techblog/2014/12/02/definitive-guide-copying-pasting-javascript/ covers it

# system clipboard access
(like JS being able to copy to your real clipboard)
* IE will allow access to system clipboard if the user accepts a security prompt
* chrome 42 will allow without a prompt, just has to be part of a user action (click, keydown, etc): http://jsbin.com/yanamebope/quiet
* FF has a clipboardevent constructor (mentioned in the entry) but it doesn't actually do anything, AFAICT.

Willing to be corrected here but right now I dont think the entry is too accurate.

**Comment by Fyrd** [comment]
@paulirish Yeah, I admit that currently the data is more based on something testable than actual usability and I've seen some other complaints about it, so thanks for bringing this up. Let me do some research here (thanks for your info!) and update it to be more useful.

**Comment by Fyrd** [comment]
@paulirish Alright, I think my latest changes capture the support much better. Just for desktop browsers for now, but that's where the difference really matters anyway:
http://caniuse.com/#feat=clipboard

Let me know what you think.

**Comment by paulirish** [comment]
cc @mattgaunt who is looking at this too

**Comment by gauntface** [comment]
This is just a rough list of things I found while looking into this:
- I thought it was going to be Chrome 43 which would support the cut and copy commands?
- Firefox has the added weirdness where apparently you can enable cut and copy commands in preferences somehwere: https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand
- IE10+ had support for cut and copy same as Chrome v43, only difference was that IE10+ shows a permission dialog

**Comment by Fyrd** [comment]
Cool, thanks @gauntface, have updated the data appropriately.
I think that should be good enough for now then, so closing this issue.

**Comment by Yaffle** [comment]
@Fyrd , thanks, very nice table!

One remark:
for Firefox you have:
[2] Only fires copy event on a valid selection and only cut and paste in focused editable fields
but, seems, in FF41 copy event is not fired for empty selection.
