### ISSUE TITLE
font-kerning property

### ISSUE THREAD

**Issue by chrislachance** [Fyrd/caniuse#946]
Afternoon! Thanks for caniuse. I use it all the time.

I just noticed that the "font-kerning" property's support wasn't on the site, so I figured I'd suggest it. Thanks!

http://www.w3.org/TR/css3-fonts/#font-kerning-prop

**Comment by pkuczynski** [comment]
Thanks for the tip!

**Comment by Fyrd** [comment]
After more research on this I've updated it and made it visible on the site: http://caniuse.com/#feat=font-kerning
