### ISSUE TITLE
Replace Google Moderator for feature suggestions

### ISSUE THREAD

**Issue by medmunds** [Fyrd/caniuse#958]
Heads up that Google Moderator is [shutting down on June 30, 2015](https://docs.google.com/document/u/1/d/1sPmkuVqoHKue7SlL3tSLrDsyufB8owMeR8AHx4LG8FA/pub), so the "why not suggest this feature be added" link will need some other approach.

Given the relatively-technical audience, maybe GitHub issues are sufficient? (If you're comfortable with voting being expressed as "+1" comments.)

**Comment by Fyrd** [comment]
Yeah, I'm looking into finding an alternative, will make sure I do before June 30. I don't think GitHub issues are sufficient unless there's some easy way to sort issues by amounts of +1s?

**Comment by Fyrd** [comment]
While I don't see an easy way to do what I mentioned, it does look like the github API would allow that. So with a bit of work I think this may be a pretty good solution.

**Comment by medmunds** [comment]
A few other possibilities:

* [Bitbucket has issue voting](https://blog.bitbucket.org/2013/08/14/no-more-1s-bitbucket-issues-now-has-voting/). You could create a "requests-only" repository there solely for voting, just to replace Google Moderator. (Or depending on your opinion of Bitbucket, it might not be crazy to move there.)

* [Sort GitHub issues by most-commented](https://github.com/Fyrd/caniuse/issues?q=is%3Aissue+is%3Aopen+sort%3Acomments-desc) might be good enough -- and requires no implementation. Sure, it would miscount "-1" as an upvote, but as a general guide for what requests have the most interest, it's pretty easy.

(There's some unofficial discussion of GitHub issue voting [here](https://github.com/isaacs/github/issues/9) -- apparently GitHub had that feature long ago. There are some options like GitPoll or ZenHub, but they're not really direct replacements for what you were doing with Moderator -- and some of them require the voters to install Chrome extensions, which seems like a non-starter.)

That said, if you're still thinking GitHub API and looking for help, I'd be happy to pitch in.

**Comment by mkurz** [comment]
I just stumpled over http://feathub.com/
Looks nice. But maybe a bit to simplistic?

**Comment by Fyrd** [comment]
So I was able to successfully import moderator data and made http://caniuse.com/issue-list to show issues in order of votes, so closing this now. Thanks @medmunds for suggesting GitHub as a solution here, I think it should work out pretty well. :)

**Comment by medmunds** [comment]
Nice!
