### ISSUE TITLE
Support for High Resolution Time API inconsistent in iOS Safari

### ISSUE THREAD

**Issue by AurelioDeRosa** [Fyrd/caniuse#959]
Hi.

The data show that this API is supported in version 8.0 but not in 8.1-8.3 and I'm sure this isn't the case. Which one is correct?

**Comment by Fyrd** [comment]
The data is correct as it is. They briefly supported it in 8.0 then removed it in 8.1. Still not supported in 8.3.

**Comment by AurelioDeRosa** [comment]
Thank you for the reply @Fyrd. I was pretty sure it was an error because I was weird.
