### ISSUE TITLE
fix FAQ that lists the wrong license, also update to CC 4.0

### ISSUE THREAD

**Issue by wolftune** [Fyrd/caniuse#960]
The license as stated here is CC-BY (thank you for that, the NC term violates Open Source and free software principles and causes incompatibilities). The FAQ still says CC-BY-NC though. That should be fixed.

Also, you should update to CC-BY 4.0 International. The newer CC version is cleaned up and better fits international law.

**Comment by Fyrd** [comment]
Thanks, done!
