### ISSUE TITLE
Corrupt file `region-usage-json/US.json`

### ISSUE THREAD

**Issue by phamann** [Fyrd/caniuse#966]
Since your latest release to npm (~5 hours ago) the file: `node_modules/caniuse-db/region-usage-json/US.json` is corrupt missing a closing `}` bracket on the JSON file. This is causing unexpected errors within tasks such as grunt-autoprefixer: 

`Error: Unexpected end of input`

This is visible in the file within master:
https://github.com/Fyrd/caniuse/blob/master/region-usage-json/US.json

**Comment by Fyrd** [comment]
Sorry about that, need to add checks of those files in the validator. 

Fixed in 1.0.30000141

**Comment by sndrs** [comment]
@Fyrd thanks!
