### ISSUE TITLE
redirect to /undefined/#feat=...

### ISSUE THREAD

**Issue by stephtr** [Fyrd/caniuse#974]
When following links from Google, for example http://caniuse.com/canvas, IE11 gets redirected to http://caniuse.com/undefined/#feat=canvas which can't be opened (404).
(Redirect is working correct on Microsoft Edge.)

**Comment by Fyrd** [comment]
Couldn't reproduce this with IE11, but I could see how it would fail in older IEs so I fixed it for them.

**Comment by stephtr** [comment]
Maybe it was the combination of IE11 and Windows 10. After clearing the cache the redirection works now without any Problems.
