### ISSUE TITLE
html5 input email should be added

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#975]
html5 input email should be added: http://dev.w3.org/html5/markup/input.email.html

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+84__
Issue added by __Thomas G&uuml;ttler__ on __2012-03-01__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by mkurz** [comment]
+1

**Comment by Fyrd** [comment]
Added at http://caniuse.com/#feat=input-email-tel-url
