### ISSUE TITLE
autocomplete= on|off functionality of <input> fields

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#976]
Would like to see the browser support for the &quot;autocomplete= on|off&quot; functionality of &lt;input&gt; fields

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+54__
Issue added by __Code Man__ on __2014-03-31__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by mkurz** [comment]
+1

**Comment by cvrebert** [comment]
There is also notable Firefox quirkiness here; see last paragraph of https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-autocomplete and also http://stackoverflow.com/questions/5985839/bug-with-firefox-disabled-attribute-of-input-not-resetting-when-refreshing

**Comment by Ugoku** [comment]
+1

**Comment by aneves** [comment]
+1

**Comment by valtlait** [comment]
+1

**Comment by greenido** [comment]
+10

**Comment by simevidas** [comment]
+1

**Comment by davidelrizzo** [comment]
It would also be great to know which browsers support the autocomplete tokens as specified by [WHATWG](https://html.spec.whatwg.org/multipage/forms.html#attr-fe-autocomplete), I am pretty sure that modern Firefox and Chrome use them after dropping the `x-autocompletetoken` experimental attribute.

**Comment by Schweinepriester** [comment]
+1

**Comment by erinstraub** [comment]
+1

**Comment by tnguyen14** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=input-autocomplete-onoff 

Turns out support is pretty messy as there's various conditions in which many browsers ignore the "off" value to provide support for password managers, etc.
