### ISSUE TITLE
Add: transform-style: flat | preserve-3d

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#977]
Add: transform-style: flat | preserve-3d

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+44__
Issue added by __Joseph Lust__ on __2012-06-17__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by Fyrd** [comment]
originally this included `perspective`, `transform-origin` and `backface-visibility` values which are already covered by http://caniuse.com/#feat=transforms3d

**Comment by cvrebert** [comment]
There is already a note in http://caniuse.com/#feat=transforms3d about how IE<=11 doesn't support `preserve-3d`.

**Comment by bvisness** [comment]
+1

**Comment by valtlait** [comment]
-1 (because of note on “CSS3 3D Transforms”)

**Comment by dstorey** [comment]
yeah, this seems covered already to me. Seems weird to make preserve-3d one item while every other transform feature is combined as one entry.

**Comment by Fyrd** [comment]
Yeah, agreed. Closing this issue.
