### ISSUE TITLE
Beacon 

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#978]
Beacon https://dvcs.w3.org/hg/webperf/raw-file/tip/specs/Beacon/Overview.html

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+58__
Issue added by __Christian Wesselhoeft__ on __2014-06-07__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
-1

**Comment by realityking** [comment]
+1

**Comment by alexsom** [comment]
+1

**Comment by AdamMerrifield** [comment]
+1

**Comment by mbonaci** [comment]
+1

**Comment by rifler** [comment]
+1

**Comment by connorshea** [comment]
+1

**Comment by tobiasurff** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=beacon
