### ISSUE TITLE
Server Name Indication (SNI)

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#979]
I would like to know which browsers support &quot;Server Name Indication&quot; (SNI).

Amazon now allow us to use SNI for their CloudFront project: http://aws.typepad.com/aws/2014/03/server-name-indication-sni-and-http-redirection-for-amazon-cloudfront.html

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+56__
Issue added by __tfotherby__ on __2014-03-07__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by MrMcFortna** [comment]
+1

**Comment by tjconcept** [comment]
+1

**Comment by jacksonj04** [comment]
:+1:

**Comment by Schweinepriester** [comment]
+1

**Comment by radkodinev** [comment]
+1

**Comment by avesus** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=sni
