### ISSUE TITLE
Basic console functions: console.log, console.dir, console.warn, console.error, console.info

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#980]
console
console.log
console.warn
console.error
console.info

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+53__
Issue added by __petero__ on __2014-06-01__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by tjconcept** [comment]
+1

**Comment by gluons** [comment]
+1

**Comment by shalomb** [comment]
+1

**Comment by cvrebert** [comment]
+1

**Comment by memolog** [comment]
+1

**Comment by wpaix** [comment]
+1

**Comment by cvrebert** [comment]
Spec: https://github.com/DeveloperToolsWG/console-object

**Comment by sandhya25rani** [comment]
+1

**Comment by Ugoku** [comment]
+1

**Comment by joshclick** [comment]
:+1:

**Comment by ximex** [comment]
+1

**Comment by aneves** [comment]
+1

**Comment by NARKOZ** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=console-basic
