### ISSUE TITLE
Pointer Lock API

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#983]
Pointer Lock API 
https://developer.mozilla.org/en/API/Pointer_Lock_API
http://dvcs.w3.org/hg/pointerlock/raw-file/default/index.html
Implementet in Chrome http://updates.html5rocks.com/tag/gaming
and FF14 http://goo.gl/QEUuD
(includes requestPointerLock, exitPointerLock, aka Mouse Lock)

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+50__
Issue added by __sobi3ch__ on __2012-05-09__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by yukulele** [comment]
+1

**Comment by connorshea** [comment]
+1

**Comment by simevidas** [comment]
+1

**Comment by Krinkle** [comment]
Also Event.movementX and Event.movementY.

Chrome currently emits this warning:
> 'webkitMovementX' is deprecated. Please use 'movementX' instead.

Would be nice if caniuser can gather and publish exactly which versions of Safari and Chrome are affected so people can easily make an informed decision about dropping use of `webkitMovementX`.

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=pointerlock
