### ISSUE TITLE
Add microdata

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#984]
Add microdata

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+31__
Issue added by __Dan__ on __2011-11-24__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by agraboso** [comment]
+1

**Comment by Lynda333** [comment]
+1

**Comment by AdamMerrifield** [comment]
+1

**Comment by rotsee** [comment]
+1

**Comment by dstorey** [comment]
Nobody supports this and was dropped from the spec, so is there much point including this?

**Comment by Webysther** [comment]
@dstorey Maybe to know is unsuported more easily.

**Comment by Jedarc** [comment]
+1

**Comment by DiMFail** [comment]
+1

**Comment by cvrebert** [comment]
X-Ref: https://github.com/whatwg/html/pull/213

**Comment by Fyrd** [comment]
Added as search results entry at http://caniuse.com/#search=microdata to indicate lack of support.

**Comment by znerd** [comment]
There is still some activity on this front, it seems, see (last updated: Nov 14, 2018):
- https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/itemprop

Also, it is mentioned here:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta

And here, in the HTML Living Standard:
- https://html.spec.whatwg.org/multipage/microdata.html#names:-the-itemprop-attribute
