### ISSUE TITLE
Missing CSS attributes: orphans, widow

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#985]
Missing CSS attributes: orphans, widow

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+32__
Issue added by __Apff__ on __2014-06-04__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by dacz** [comment]
+1

**Comment by chrisveness** [comment]
+1

**Comment by artdodson** [comment]
+1

**Comment by tgraham-antenna** [comment]
+1

**Comment by kwkbtr** [comment]
+1

**Comment by MurakamiShinyu** [comment]
+1

**Comment by bassplayer7** [comment]
+1

**Comment by mormegil-cz** [comment]
+1

**Comment by innovimax** [comment]
+1

**Comment by seanvinci** [comment]
+1

**Comment by graysonwright** [comment]
:+1: 

Renaming this issue from `widow` -> `widows` might help people find it. didn't show up when I searched for `widows`.

**Comment by dauwhe** [comment]
+1

**Comment by johanneswilm** [comment]
+1

**Comment by xaddict** [comment]
+1

**Comment by sobolz** [comment]
+1

**Comment by cweiske** [comment]
+1

**Comment by ierhyna** [comment]
+1

**Comment by vincentorback** [comment]
+1

**Comment by tiffehr** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by miclf** [comment]
+1

**Comment by evaferreira** [comment]
+1

**Comment by DJDavid98** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=css-widows-orphans
