### ISSUE TITLE
Media Source Extensions  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#986]
Media Source Extensions
http://www.w3.org/TR/media-source/

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+52__
Issue added by __Kirix__ on __2014-03-04__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by duanyao** [comment]
+1

**Comment by pkese** [comment]
+1

**Comment by ximex** [comment]
+1

**Comment by jrbasso** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=mediasource
