### ISSUE TITLE
Audio codec: AAC.

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#988]
Audio codecs: MP3, OGG, WAV, AAC. Currently video formats appear on caniuse, but not audio formats.

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+55__
Issue added by __maboa__ on __2013-05-06__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by samjgarnham** [comment]
+1

**Comment by ximex** [comment]
+1

**Comment by SirCmpwn** [comment]
:+1:

**Comment by tobiasurff** [comment]
+1

**Comment by gertdude** [comment]
:+1:

**Comment by Aranjedeath** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by Fyrd** [comment]
MP3 now available at http://caniuse.com/#feat=mp3

**Comment by vdclouis** [comment]
+1

**Comment by Fyrd** [comment]
WAV now available at http://caniuse.com/#feat=wav

**Comment by Fyrd** [comment]
Ogg Vorbis now available at http://caniuse.com/#feat=ogg-vorbis

**Comment by Fyrd** [comment]
AAC now available at http://caniuse.com/#feat=aac

That's all four! Closing this issue.
