### ISSUE TITLE
support for css background-position-x and background-position-y

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#989]
support for css background-position-x and background-position-y

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+30__
Issue added by __Neil__ on __2014-08-17__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by duanemck** [comment]
+1

**Comment by piotr-cz** [comment]
+1

**Comment by AdamMerrifield** [comment]
+1

**Comment by SkyHolder** [comment]
+1

**Comment by retinafunk** [comment]
+1

**Comment by Nav-Appaiya** [comment]
+1

**Comment by kevnk** [comment]
+1

**Comment by extempl** [comment]
+1

**Comment by stof** [comment]
+1

**Comment by TheJaredWilcurt** [comment]
+1

**Comment by mik-laj** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=background-position-x-y
