### ISSUE TITLE
first-letter

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#990]
first-letter

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+38__
Issue added by ____ on __2014-05-26__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by nighto** [comment]
+1

**Comment by Ugoku** [comment]
+1

**Comment by WheelyWonka** [comment]
+1

**Comment by connorshea** [comment]
+1

**Comment by RainyRae** [comment]
+1

**Comment by Juburin** [comment]
+1

**Comment by Badestrand** [comment]
+1

**Comment by Jonathan-Eyler-Werve** [comment]
+1

**Comment by cvrebert** [comment]
Now available at http://caniuse.com/#feat=css-first-letter

**Comment by nighto** [comment]
Thank you, @cvrebert! :)
