### ISSUE TITLE
element.getBoundingClientRect()

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#991]
element.getBoundingClientRect()

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+31__
Issue added by __Kiph__ on __2014-04-17__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by cvrebert** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect#Browser_compatibility

**Comment by himynameisdave** [comment]
+1

**Comment by AdamMerrifield** [comment]
+1

**Comment by IonDen** [comment]
+1

**Comment by jespertheend** [comment]
+1

**Comment by q--** [comment]
+1

**Comment by simevidas** [comment]
+1
