### ISSUE TITLE
text-space-collapse css property

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#992]
It would be nice to show support for the `text-space-collapse` css property (previously defined as the `white-space-collapsing` property):
https://drafts.csswg.org/css-text-4/#propdef-text-space-collapse

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+33__
Issue added by __James@Sharewire__ on __2012-04-04__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by AdamMerrifield** [comment]
+1

**Comment by piotr-cz** [comment]
+1,
Anyway it seems that it's fully supported everywhere: https://css-tricks.com/almanac/properties/w/whitespace/

**Comment by abhianet** [comment]
+1

**Comment by thesmart** [comment]
+1 * 1000

**Comment by Shadowen** [comment]
+1

**Comment by chrona** [comment]
+1

**Comment by Schweinepriester** [comment]
+1

**Comment by pixelspring** [comment]
+1

**Comment by gibatronic** [comment]
+1

**Comment by Fyrd** [comment]
There appear to be no plans to support this in any browser, so have added it as a basic search results entry until that changes:
http://caniuse.com/#search=text-space-collapse
