### ISSUE TITLE
Please add info on "accept" attribute of input[type=file]

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#993]
Please add info on &quot;accept&quot; attribute of input[type=file]

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+42__
Issue added by __mnesov__ on __2014-02-25__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by memolog** [comment]
+1

**Comment by humantorch** [comment]
+1

**Comment by aneves** [comment]
+1

**Comment by zarelit** [comment]
Would be very useful since it's inconsistent across browsers yet. On Firefox it enables a filter on the dropdown menu but it's not enabled by default...

**Comment by zarelit** [comment]
+1

**Comment by Koelli91** [comment]
+1

**Comment by janyksteenbeek** [comment]
+1

**Comment by cuixiping** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=input-file-accept
