### ISSUE TITLE
HTML5 naturalHeight/naturalWidth attributes in images

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#994]
HTML5 naturalHeight/naturalWidth attributes in images (see https://developer.mozilla.org/en-US/docs/DOM/HTMLImageElement)

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+26__
Issue added by __Juan__ on __2012-08-20__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by thornbrook** [comment]
+1

**Comment by valtlait** [comment]
+1

**Comment by hopkins-matt** [comment]
test

**Comment by hopkins-matt** [comment]
+300

**Comment by jokagent** [comment]
+1

**Comment by sandstrom** [comment]
Already supported in virtually all browsers (IE9+ and all others). This is issue was added in 2012 when support wasn't widespread.

**Comment by leo** [comment]
+1

**Comment by aligajani** [comment]
+1

**Comment by jaddison** [comment]
+1

**Comment by MarkMurphy** [comment]
+1

**Comment by DiMFail** [comment]
+1

**Comment by leo** [comment]
<img width="180" alt="34ecad7a-eb8e-11e5-992b-494dcc4e9635" src="https://cloud.githubusercontent.com/assets/6170607/14954387/3f8f5a12-1072-11e6-86be-b3b6fe560741.png">

**Comment by mfeineis** [comment]
+1

**Comment by kagawagao** [comment]
+1

**Comment by Fyrd** [comment]
May not be worth for much longer, but for those still supporting IE8...this feature's now available at
http://caniuse.com/#feat=img-naturalwidth-naturalheight
