### ISSUE TITLE
FileReaderSync API:  

### ISSUE THREAD

**Issue by Fyrd** [Fyrd/caniuse#997]
FileReaderSync API:

http://dev.w3.org/2006/webapi/FileAPI/#FileReaderSync

---------
##### This issue was imported from [Google Moderator](https://www.google.com/moderator/)
Moderator votes: __+24__
Issue added by __stpasha__ on __2014-08-25__
To vote this issue up or down, simply include `+1` or `-1` in your comment.

**Comment by YuichiNukiyama** [comment]
+1

**Comment by Fyrd** [comment]
Now available at http://caniuse.com/#feat=filereadersync
